 /*
 * pair.c
 */

#define usage "\n\n\
NAME\n\
	nuketrailobjects - mask satellite trails etc\n\
\n\
SYNOPSIS\n\
	nuketrailobjects [options....] srcfits d w\n\
		-u		# print this man page\n\
\n\
DESCRIPTION\n\
        'nuketrailobjects' reads a catalogue from stdin which must contain\n\
	a 2 vector 'x' and a scalar phi (possibly generated by\n\
	'findtrailobjects') and then sets to MAGIC any pixels\n\
	in srcimage lying in a strip of width (2 w + 1) straddling the\n\
	line of half-length d passing through x with orientation phi.\n\
	Resulting FITS image is sent to stdout.\n\
\n\
AUTHOR\n\
	Nick Kaiser --- kaiser@hawaii.edu\n\
\n\n"


#include <stdio.h>
#include <math.h>
#include <limits.h>
#include "../../utils/error.h"
#include "../../utils/args.h"
#include "../../imlib/fits.h"

main(int argc, char *argv[])
{
	char		*flag, *srcfitsname, command[512];
	double		*x, phi, ipbuff[3], xp, yp;
	FILE		*ipf, *opf, *fitsf;
	fitsheader	*fits;
	int		N1, N2, w, d, id;

	/* defaults */

	/* parse the args */
	argsinit(argc, argv, usage);
	while (nextargtype() == FLAG_ARG) {
		flag = getflag();
		switch (flag[0]) {
			case 'u':
			default:
				error_exit(usage);
		}
	}
	srcfitsname = getargs();
	d = getargi();
	w = getargi();

	/* read the fits image header - just to get the image size */
	fitsf = fopen(srcfitsname, "r");
	if (!fitsf) {
		error_exit("nuketrailobjects: failed to open fits file\n");
	}
	fits = readfitsheader(fitsf);
	N1 = fits->n[0];
	N2 = fits->n[1];
	close(fitsf);

	/* process the catalogue */
	ipf = popen("lc -b -o x phi", "r");
	if (!ipf) {
		error_exit("nuketrailobjects: failed to open input pipe\n");
	}
	sprintf(command, "lc -C -N '1 2 x' | makedensity x 0 %d %d 0 %d %d | ic 'MAGIC 1 %%1 ?' - | growmagic -n %d | ic -h COMMENT 'nuketrailobjects:' '%%1 %%2 *' %s -", 
		N1, N1, N2, N2, w, srcfitsname);

	opf = popen(command, "w");
	if (!opf) {
		error_exit("nuketrailobjects: failed to open output pipe\n");
	}
	while (3 == fread(ipbuff, sizeof(double), 3, ipf)) {
		x = ipbuff;
		phi = ipbuff[2];
		for (id = -d; id <= d; id++) {
			xp = x[0] + id * cos(phi);
			yp = x[1] + id * sin(phi);
			fprintf(opf, "%14.8lf %14.8lf\n", xp, yp);
		}
	}
	exit(pclose(opf));
}



