#define	usage "\n\n\n\
NAME\n\
	maskfits - set pixels in rectangles to MAGIC\n\
\n\
SYNOPSIS\n\
	maskfits yyy.msk\n\n\
DESCRIPTION\n\
	Filter which sets to magic any pixels falling\n\
	within rectangles defined in yyy.msk.\n\
	The latter must be an lc-format catalogue containing\n\
	at least a pair of position vectors x1, x2 for\n\
	diagonally opposite corners of the rectangle.\n\
	Mask files may be generated by 'plotcat'.\n\
	In general, these coords are floating point numbers,\n\
	but get integerised on input using 'floor'.\n\
\n\
AUTHOR\n\
	Nick Kaiser:  kaiser@cita.utoronto.ca\n\
\n\n\n"		

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>

#include "../utils/error.h"
#include "../imlib/fits.h"

#define MAX_RECTS 1000

#define MAGIC FLOAT_MAGIC

main(int argc, char *argv[])	
{
	int	l[MAX_RECTS], b[MAX_RECTS], r[MAX_RECTS], t[MAX_RECTS];
	FILE	*maskpipe;
	char	tempstring[1024], systemstring[1024], line[1024];
	int	rect, nrects, inrect, pixtype;
	float	**f, x1, x2, y1, y2;
	int	i, j, N1, N2, temp;
	fitsheader	*fits;

	if (argc != 2 || argv[1][0] == '-')
		error_exit(usage);
	sprintf(tempstring, "lc x1 x2 < %s", argv[1]);
	maskpipe = popen(tempstring, "r");
	if (!maskpipe)
		error_exit("maskfits: unable to open mask file\n");
	nrects = 0;
	while(fgets(line, 1024, maskpipe)) {
		if (line[0] != '#') {
			if (4 != sscanf(line, "%f %f %f %f", &x1, &y1, &x2, &y2)) {
				error_exit("maskfits: mask file corrupted!\n");
			}
			l[nrects] = floor(x1);
			b[nrects] = floor(y1);
			r[nrects] = floor(x2);
			t[nrects] = floor(y2);
			if (l[nrects] > r[nrects]) {
				temp = l[nrects];
				l[nrects] = r[nrects];
				r[nrects] = temp;
			}
			if (b[nrects] > t[nrects]) {
				temp = b[nrects];
				b[nrects] = t[nrects];
				t[nrects] = temp;
			}
			nrects ++;
			if (nrects == MAX_RECTS)
				error_exit("maskfits: too many rects\n");
		}
	}
	pclose(maskpipe);
	read2Dfloatimage(&f, &N1, &N2, &fits, stdin);
	for  (rect = 0; rect < nrects; rect++) {
		for (i = b[rect]; i <= t[rect]; i++) {
			for (j = l[rect]; j <= r[rect]; j++) {
				if (i >= 0 && i < N2 && j >= 0 && j < N1)
					f[i][j] = MAGIC;
			}
		}
	}
	add_comment(argc, argv, fits);
	write2Dfloatimage(f, fits);
	exit(0);
}










