#! /usr/bin/perl


$offset = 5;


# generate a grid of stacked images
$usage = "NAME\
	makemosaicstacks - tool for registering mosaic CCD images\
SYNOPSIS\
	makemosaicstacks ix1 ix2 iy1 iy2 dX dY destdir imdir\
DESCRIPTION\
\tgenerate a grid of stacked images of size dX, dY.\
\tloop over ix = ix1 ... ix2; iy = iy1 ... iy\
\torigin is at (ix - $offset) * dX, (iy - $offset) * dY\
\tstacked images placed in destdir/ix_iy/\
\tExpects to find source images in imdir/chip?\n";

$| = 1;



die $usage if ($#ARGV < 7);
$ix1 = shift @ARGV;
$ix2 = shift @ARGV;
$iy1 = shift @ARGV;
$iy2 = shift @ARGV;
$dX = shift @ARGV;
$dY = shift @ARGV;
die "non-positive sub-image size\n" if ($dX <= 0 || $dY <= 0);
$destdir = shift @ARGV;
$imdir = shift @ARGV;

for ($ix = $ix1; $ix <= $ix2; $ix++) {
	for ($iy = $iy1; $iy <= $iy2; $iy++) {
		$X = ($ix - $offset) * $dX;
		$Y = ($iy - $offset) * $dY;
		$subdir = "$destdir/$ix"."_$iy";
		&echosys("mkdir $subdir") unless -d $subdir;
		&echosys("makemosaicstack $X $Y $dX $dY $subdir $imdir");
	}
}


sub echosys {
        print @_, "\n";
       system(@_) && die "$0: System call $_[0] failed!\n";
}
