.TH "_AppResources" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_AppResources \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBfmin\fP"
.br
.ti -1c
.RI "float \fBfmax\fP"
.br
.ti -1c
.RI "int \fBblocksize\fP"
.br
.ti -1c
.RI "int \fBcolormapindex\fP"
.br
.ti -1c
.RI "int \fBfmin\fP"
.br
.ti -1c
.RI "int \fBfmax\fP"
.br
.ti -1c
.RI "int \fBgoodwindowsize\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fB_AppResources::blocksize\fP"
.PP
Definition at line 39 of file front.c.
.PP
Referenced by main().
.SS "int \fB_AppResources::colormapindex\fP"
.PP
Definition at line 39 of file front.c.
.PP
Referenced by main().
.SS "int \fB_AppResources::fmax\fP"
.PP
Definition at line 37 of file ximfront.c.
.SS "float \fB_AppResources::fmax\fP"
.PP
Definition at line 38 of file front.c.
.PP
Referenced by main(), and xfgetvalue().
.SS "int \fB_AppResources::fmin\fP"
.PP
Definition at line 37 of file ximfront.c.
.SS "float \fB_AppResources::fmin\fP"
.PP
Definition at line 38 of file front.c.
.PP
Referenced by main(), and xfgetvalue().
.SS "int \fB_AppResources::goodwindowsize\fP"
.PP
Definition at line 38 of file ximfront.c.
.PP
Referenced by main(), and xfgetvalue().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
