acf.c
NAME
acf.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
#include '../utils/arrays.h'
#include '../fftlib/myfft.h'
Defines
#define usage '\n\n\n\NAME\n\	acf --- calculates 2-D autocorrelation function of a fits image\n\\n\SYNOPSIS\n\	acf [options...]\n\\n\DESCRIPTION\n\	'acf' reads a fits file from stdin and writes the autocorrelation\n\	function to stdout. If the input image is fin(r) then we compute\n\		fout(r) = sum_r' fin(r') fin(r' + r) / (N1 * N2)\n\	and resulting image is wrapped so that zero lag is at pixel (N1/2, N2/2).\n\\n\	Options are:\n\		-p		# calculate power spectrum instead\n\		-c f1 f2	# cross correlate named fits files\n\		-P pixtype	# output pixtype (FLOAT_PIXTYPE)\n\		-n		# no MAGIC substitution\n\		-m magicval	# replacement for MAGIC pixels (0) \n\\n\	Power is defined so that white noise with variance sigma2\n\	will produce P = sigma2. Power is translated so that zero frequency\n\	lies at N1/2, N2/2.\n\\n\	With '-c fits0 fits1' we compute\n\\n\		c(r) = sum_r' f0(r') f1(r' + r) / (N1 * N2)\n\\n\	to compute instead\n\\n\		c(r) = sum_r' f0(r') f1(r - r') / (N1 * N2)\n\\n\	you should first rotate the first image by 180 degrees.\n\\n\	Supply file name '-' to read from stdin.\n\\n\	Default output image format is BITPIX = -32 (i.e. 4-byte float).\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	acf --- calculates 2-D autocorrelation function of a fits image\n\\n\SYNOPSIS\n\	acf [options...]\n\\n\DESCRIPTION\n\	'acf' reads a fits file from stdin and writes the autocorrelation\n\	function to stdout. If the input image is fin(r) then we compute\n\		fout(r) = sum_r' fin(r') fin(r' + r) / (N1 * N2)\n\	and resulting image is wrapped so that zero lag is at pixel (N1/2, N2/2).\n\\n\	Options are:\n\		-p		# calculate power spectrum instead\n\		-c f1 f2	# cross correlate named fits files\n\		-P pixtype	# output pixtype (FLOAT_PIXTYPE)\n\		-n		# no MAGIC substitution\n\		-m magicval	# replacement for MAGIC pixels (0) \n\\n\	Power is defined so that white noise with variance sigma2\n\	will produce P = sigma2. Power is translated so that zero frequency\n\	lies at N1/2, N2/2.\n\\n\	With '-c fits0 fits1' we compute\n\\n\		c(r) = sum_r' f0(r') f1(r' + r) / (N1 * N2)\n\\n\	to compute instead\n\\n\		c(r) = sum_r' f0(r') f1(r - r') / (N1 * N2)\n\\n\	you should first rotate the first image by 180 degrees.\n\\n\	Supply file name '-' to read from stdin.\n\\n\	Default output image format is BITPIX = -32 (i.e. 4-byte float).\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file acf.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 55 of file acf.c.
References add_comment(), alloc_fft(), allocFloatArray(), allocFloatArray_shm(), argsinit(), ccf(), copyfitsheader(), error_exit, exit(), fft_type, flag, FLOAT_PIXTYPE, forward_fft(), getargf(), getargi(), getargs(), getflag(), i, j, M1, M2, N1, N2, power(), read2Dfloatimage(), read2Dfloatimage_shm(), setextpixtype(), shmfree(), substitute(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.