acfregister.c
NAME
acfregister.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'utils/arrays.h'
#include 'fftlib/myfft.h'
#include 'utils/error.h'
#include 'utils/ipbuff.h'
#include 'imlib/fits.h'
#include 'imlib/filters.h'
Defines
#define usage '\n\n\NAME\n\	acfregister - determine approximate transformation coefficients\n\\n\SYNOPSIS\n\	acfregister [options...] a.cat b.cat\n\		-x xname	# name for spatial coords ('x')\n\		-i imsize	# internal image size (512)\n\		-p phi1 phi2	# range for phi wrapping (0, PI)\n\		-a a1 a2	# die if solution has scale factor outside this range\n\		-d dlnr		# range of (natural) log(r) for wrapping (1.0)\n\		-v 		# pipe images to 'iis -p ~/dev/saopipe' for display\n\DESCRIPTION\n\	'acfregister' reads 2 catalogues and determines\n\	scale, rotation and translation that maps (x_a,y_a) => (x_b,y_b)\n\\n\		x_b = a (x_a cos phi - y_a sin phi) + x0\t\n\		y_b = a (x_a sin phi + y_a cos phi) + y0\t\n\\n\	It works by cross-correlating images of wrapped lnr, phi\n\	values for pairs of objects and locating peak to determine\n\	a, phi. We then rotate and scale x_b y_b, generate images\n\	of x,y positions and cross correlate these to get x0, y0.\n\\n\	Outputs x0, y0, a, phi to stdout.\n\\n\	Use the -v option to get some visual feedback. You must first\n\	have saoimage running and listening to the FIFO ~/dev/saopipe\n\	so make this pipe if necessary (using mknod) and then run the\n\	image display using 'saoimage -idev ~/dev/saopipe'. Acfregister\n\	will then pipe the various images it generates internally to the viewer.\n\\n\	Acfregister will not work properly if the scale difference is\n\	very large (|log(a)| > dlnr/2) as the wrapping will cause it to\n\	return log(a) in range +- dlnr/2. You can increase dlnr, but at\n\	the cost of reduced precision in log(a). It is probably better to\n\	rescale one of the input cats to get roughly similar coordinate scales.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
#define PI M_PI
#define BIG_NEG -1.e20
#define BIG_POS 1.e20;
#define TINY 1.e-20
#define DISPLAY_COMMAND 'iis -p ~/dev/saopipe'
Functions
float mexicanfilterfunction (float ki, float kj)
void display (float **f, int N1, int N2, char *name)
int findpeak (float **f, int imsize, double *xpeak, double *ypeak, double *peakval)
main (int argc, char *argv[])
Define Documentation
#define BIG_NEG -1.e20
Definition at line 60 of file acfregister.c.
#define BIG_POS 1.e20;
Definition at line 61 of file acfregister.c.
#define DISPLAY_COMMAND 'iis -p ~/dev/saopipe'
Definition at line 64 of file acfregister.c.
Referenced by display().
#define PI M_PI
Definition at line 59 of file acfregister.c.
#define TINY 1.e-20
Definition at line 62 of file acfregister.c.
#define usage '\n\n\NAME\n\	acfregister - determine approximate transformation coefficients\n\\n\SYNOPSIS\n\	acfregister [options...] a.cat b.cat\n\		-x xname	# name for spatial coords ('x')\n\		-i imsize	# internal image size (512)\n\		-p phi1 phi2	# range for phi wrapping (0, PI)\n\		-a a1 a2	# die if solution has scale factor outside this range\n\		-d dlnr		# range of (natural) log(r) for wrapping (1.0)\n\		-v 		# pipe images to 'iis -p ~/dev/saopipe' for display\n\DESCRIPTION\n\	'acfregister' reads 2 catalogues and determines\n\	scale, rotation and translation that maps (x_a,y_a) => (x_b,y_b)\n\\n\		x_b = a (x_a cos phi - y_a sin phi) + x0\t\n\		y_b = a (x_a sin phi + y_a cos phi) + y0\t\n\\n\	It works by cross-correlating images of wrapped lnr, phi\n\	values for pairs of objects and locating peak to determine\n\	a, phi. We then rotate and scale x_b y_b, generate images\n\	of x,y positions and cross correlate these to get x0, y0.\n\\n\	Outputs x0, y0, a, phi to stdout.\n\\n\	Use the -v option to get some visual feedback. You must first\n\	have saoimage running and listening to the FIFO ~/dev/saopipe\n\	so make this pipe if necessary (using mknod) and then run the\n\	image display using 'saoimage -idev ~/dev/saopipe'. Acfregister\n\	will then pipe the various images it generates internally to the viewer.\n\\n\	Acfregister will not work properly if the scale difference is\n\	very large (|log(a)| > dlnr/2) as the wrapping will cause it to\n\	return log(a) in range +- dlnr/2. You can increase dlnr, but at\n\	the cost of reduced precision in log(a). It is probably better to\n\	rescale one of the input cats to get roughly similar coordinate scales.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 17 of file acfregister.c.
Function Documentation
void display (float ** f, int N1, int N2, char * name)
Definition at line 288 of file acfregister.c.
References DISPLAY_COMMAND, error_exit, f, fits, FLOAT_PIXTYPE, N1, N2, new2Dfitsheader(), fitsheader::opstream, and write2Dfloatimage().
Referenced by main().
int findpeak (float ** f, int imsize, double * xpeak, double * ypeak, double * peakval)
Definition at line 303 of file acfregister.c.
References BIG_NEG, f, ff, i, j, and TINY.
Referenced by main().
main (int argc, char * argv[])
Definition at line 70 of file acfregister.c.
References a1, a2, alloc_fft(), allocFloatArray(), BIG_NEG, BIG_POS, c, ccf(), display(), dx, dy, error_exit, exit(), fft_type, findpeak(), forward_fft(), i, ipf, ix, mexicanfilter(), n, nobj, phi, PI, readdoublebuff(), usage, X, and x.
float mexicanfilterfunction (float ki, float kj)
Definition at line 498 of file filters.c.
Author
Generated automatically by Doxygen for imcat from the source code.