airmassmin.h
NAME
airmassmin.h -
SYNOPSIS
Functions
double airmassmin (double lat, double lon, double phaseofyear, double zd_solar_min, double zd_lunar_min, int nstepsperday, double *phaseofday, double *zd_target_min)
Function Documentation
double airmassmin (double lat, double lon, double phaseofyear, double zd_solar_min, double zd_lunar_min, int nstepsperday, double * phaseofday, double * zd_target_min)
Definition at line 17 of file airmassmin.c.
References assign(), AXISTILTINDEG, copy(), dot(), LATOBSINDEG, length(), phi, roty(), and scale().
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.