album.c
NAME
album.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	album --- paste fits images into a larger image\n\\n\SYNOPSIS\n\	album [options... ] nx ny fits1 fits2 ...\n\	album -f offsetsfile [options... ] N1 N2 fits1 fits2 ...\n\		-d dx dy	# grid spacing\n\		-b		# draw a line around each chip\n\		-f file		# file for offsets\n\		-M		# initialise to MAGIC.\n\\n\DESCRIPTION\n\	\'album\' combines a set of images into an album.\n\	With -f option the layout of the image is determined\n\	from the'offsetsfile', amd the size of the output\n\	image is specified after the options.\n\	The format of this file should be a single comment line\n\	followed by x,y pairs to define location of bottom left\n\	corners of the images to be pasted.\n\	Without the -f option, the grid spacing will be\n\	equal to the dimensions of the first image (unless\n\	you override this with -d option) and the images will\n\	be placed on a nx by ny grid.\n\\n\	The output image is initialised to zero, images are painted\n\	on sequentially, erasing any previously painted values, except\n\	that MAGIC values are not painted. Us the -M option to\n\	intialise to MAGIC instead.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	album --- paste fits images into a larger image\n\\n\SYNOPSIS\n\	album [options... ] nx ny fits1 fits2 ...\n\	album -f offsetsfile [options... ] N1 N2 fits1 fits2 ...\n\		-d dx dy	# grid spacing\n\		-b		# draw a line around each chip\n\		-f file		# file for offsets\n\		-M		# initialise to MAGIC.\n\\n\DESCRIPTION\n\	\'album\' combines a set of images into an album.\n\	With -f option the layout of the image is determined\n\	from the'offsetsfile', amd the size of the output\n\	image is specified after the options.\n\	The format of this file should be a single comment line\n\	followed by x,y pairs to define location of bottom left\n\	corners of the images to be pasted.\n\	Without the -f option, the grid spacing will be\n\	equal to the dimensions of the first image (unless\n\	you override this with -d option) and the images will\n\	be placed on a nx by ny grid.\n\\n\	The output image is initialised to zero, images are painted\n\	on sequentially, erasing any previously painted values, except\n\	that MAGIC values are not painted. Us the -M option to\n\	intialise to MAGIC instead.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file album.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 48 of file album.c.
References add_comment(), allocFloatArray(), COM_LENGTH, dx, dy, error_exit, exit(), fits, FLOAT_MAGIC, i, ipf, j, line, magicinit(), fitsheader::n, N1, N2, nx, ny, read2Dfloatimage(), readfitsheader(), set2Dimagesize(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.