.TH "alist" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alist \- 
.SH SYNOPSIS
.br
.PP
\fC#include <f2c.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBflag\fP \fBaerr\fP"
.br
.ti -1c
.RI "\fBftnint\fP \fBaunit\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBflag\fP \fBalist::aerr\fP"
.PP
Definition at line 91 of file myf2c.h.
.SS "\fBftnint\fP \fBalist::aunit\fP"
.PP
Definition at line 92 of file myf2c.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
