amoeba_dbl.h
NAME
amoeba_dbl.h -
SYNOPSIS
Functions
void amoeba (double **p, double y[], int ndim, double ftol, double(*funk)(double[]), int *nfunk)
Function Documentation
void amoeba (double ** p, double y[], int ndim, double ftol, double(* funk)(double[]), int * nfunk)
Definition at line 18 of file orbits/orbitutils/amoeba_dbl.c.
References amotry(), free(), GET_PSUM, i, j, NMAX, nrerror(), SWAP, swap, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.