.TH "amoeba_dbl.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amoeba_dbl.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBamoeba\fP (double **p, double y[], int \fBndim\fP, double ftol, double(*funk)(double[]), int *nfunk)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void amoeba (double ** p, double y[], int ndim, double ftol, double(* funk)(double[]), int * nfunk)"
.PP
Definition at line 18 of file orbits/orbitutils/amoeba_dbl.c.
.PP
References amotry(), free(), GET_PSUM, i, j, NMAX, nrerror(), SWAP, swap, and y.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
