.TH "amotry_dbl.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amotry_dbl.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBamotry\fP (double **p, double y[], double psum[], int \fBndim\fP, double(*funk)(double[]), int ihi, double fac)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double amotry (double ** p, double y[], double psum[], int ndim, double(* funk)(double[]), int ihi, double fac)"
.PP
Definition at line 11 of file orbits/orbitutils/amotry_dbl.c.
.PP
References free(), j, and y.
.PP
Referenced by amoeba().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
