analyse.h
NAME
analyse.h -
SYNOPSIS
Functions
void dosky (float **f, int N1, int N2, int i, int j, int a1, int a2, skyquad *sky, float fmode, float sigma)
void do_object_stats (object *pk, float **f, int N1, int N2, float(*fsky)(int i, int j), float sigma, float ne, float rc, float alpha)
int objectcmp (object *pk1, object *pk2)
int shortcmp (short *s1, short *s2)
float fsky (int di, int dj)
void setskyparameters (skyquad *sky)
void zap (int zapmode, object *obj, int radiustype, float a, float **f, float **fzap, short **nzap, int N1, int N2)
Function Documentation
void do_object_stats (object * pk, float ** f, int N1, int N2, float(* fsky)(int i, int j), float sigma, float ne, float rc, float alpha)
Definition at line 424 of file analyse.c.
References a, alpha, b, d, di, dj, dx, dy, object::e, f, fit, fsky(), gaussfit(), GC_MAX, object::i, i, object::j, j, MAGIC, N1, N2, ne, phi, PI, powerlawwindow, r, RMAX_MIN, sigma, and W.
Referenced by main().
void dosky (float ** f, int N1, int N2, int ip, int jp, int a1, int a2, skyquad * sky, float fmode, float sigma)
calculates occupation and mode for NSEW sectors; Definition at line 324 of file analyse.c.
References a1, a2, error_exit, f, free(), i, j, liststats(), m, MAGIC, median(), N1, N2, and PI.
Referenced by main().
float fsky (int di, int dj)
Definition at line 629 of file analyse.c.
References di, dj, ff, ffi, ffj, ffmode, and nosky.
Referenced by do_object_stats(), and main().
int objectcmp (object * pk1, object * pk2)
void setskyparameters (skyquad * sky)
Definition at line 622 of file analyse.c.
References ff, ffi, and ffj.
Referenced by main().
int shortcmp (short * s1, short * s2)
void zap (int zapmode, object * obj, int radiustype, float a, float ** f, float ** fzap, short ** nzap, int N1, int N2)
Definition at line 640 of file analyse.c.
References a, d, error_exit, f, G_RADIUS, object::i, i, object::j, j, MAGIC, N1, N2, N_RADIUS, RESTORE, and ZAP.
Author
Generated automatically by Doxygen for imcat from the source code.