analyse.c
NAME
analyse.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'fits.h'
#include 'error.h'
#include 'arrays.h'
#include 'stats_stuff.h'
#include 'object_stuff.h'
#include 'analyse.h'
#include 'magic.h'
#include 'catio.h'
#include 'gaussfit/gaussfit.h'
#include 'status.h'
Defines
#define usage '\n\n\n\SYNOPSIS\n\		analyse	[option...] < input.cat > output.cat\n\			-n nu		# threshold nu (default -10.0)\n\			-a a1 a2	# annulus for sky: a1 < r <= a2, (default 16 32)\n\			-f		# fit objects to Gaussian ellipsoids\n\			-R r0		# gaussian window scale (3.0)\n\			-x mul		# gaussian window scale = mul * obj->rg (1.0)\n\			-e n rc		# use W(r) = (r^2 + rc^2)^n/2 window (-2, 2)\n\			-s		# force recalculation of local sky params\n\			-z		# switch off local sky determination\n\			-r alpha	# aperture = alpha * r_petrosian (3.0)\n\			-m x a		# zap neighbouring images\n\			-S		# force recalculation of image sigma, mode\n\			-Q		# sky annulus matched to aperture\n\			-F deltam	# filter output to reject bad rh, mag\n\\n\DESCRIPTION\n\		\'analyse\' analyses images around a catalogue of objects\n\		created by (h)findpeaks. It determines a constant plus gradient model\n\		for the local sky parameters using NE, NW, SW, SE quadrants of\n\		an annulus (unless you tell it not to).\n\		Only uses objects with nu (determined by findpeaks) above threshold.\n\		-f to do gaussian ellipsoid fit.\n\		By default, moments etc are determined with gaussian window scale 3.0 pixels.\n\		-e to specify a softened power law window.\n\		-R option to change scale length.\n\		-x option to override this and set window scale for moments\n\		to be mul * obj.rg (rg as determined by hcat2cat)\n\		Use -ve alpha to use aperture = (-alpha) * obj->rg for photometry.\n\		Luminosities incorporate 1 / normfactor from fits header\n\		-m x a to zap disks radius r * r_x, where x = \'g\' or \'n\'\n\		(for r_numax), around neighbours\n\		-Q with -ve alpha to make reference annlus run from r_ap to 2 * r_ap\n\		With -F option, if total mag differs from hfindpeaks mag estimate by > deltam\n\		we ignore rh, total mag in favor of hfindpeaks values.\n\\n\n\n'
#define RMAX_MIN 6
#define G_RADIUS 0
#define N_RADIUS 1
#define ZAP 0
#define RESTORE 1
Functions
main (int argc, char *argv[])
void dosky (float **f, int N1, int N2, int ip, int jp, int a1, int a2, skyquad *sky, float fmode, float sigma)
void do_object_stats (object *pk, float **f, int N1, int N2, float(*fsky)(int i, int j), float sigma, float ne, float rc, float alpha)
void setskyparameters (skyquad *sky)
float fsky (int di, int dj)
void zap (int zapmode, object *obj, int radiustype, float a, float **f, float **fzap, short **nzap, int N1, int N2)
Variables
float ff
float ffi
float ffj
float ffmode
int fit = 0
int powerlawwindow
int nosky = 0
Define Documentation
#define G_RADIUS 0
Definition at line 106 of file analyse.c.
Referenced by main(), and zap().
#define N_RADIUS 1
Definition at line 107 of file analyse.c.
Referenced by main(), and zap().
#define RESTORE 1
Definition at line 110 of file analyse.c.
Referenced by main(), and zap().
#define RMAX_MIN 6
Definition at line 99 of file analyse.c.
Referenced by do_object_stats().
#define usage '\n\n\n\SYNOPSIS\n\		analyse	[option...] < input.cat > output.cat\n\			-n nu		# threshold nu (default -10.0)\n\			-a a1 a2	# annulus for sky: a1 < r <= a2, (default 16 32)\n\			-f		# fit objects to Gaussian ellipsoids\n\			-R r0		# gaussian window scale (3.0)\n\			-x mul		# gaussian window scale = mul * obj->rg (1.0)\n\			-e n rc		# use W(r) = (r^2 + rc^2)^n/2 window (-2, 2)\n\			-s		# force recalculation of local sky params\n\			-z		# switch off local sky determination\n\			-r alpha	# aperture = alpha * r_petrosian (3.0)\n\			-m x a		# zap neighbouring images\n\			-S		# force recalculation of image sigma, mode\n\			-Q		# sky annulus matched to aperture\n\			-F deltam	# filter output to reject bad rh, mag\n\\n\DESCRIPTION\n\		\'analyse\' analyses images around a catalogue of objects\n\		created by (h)findpeaks. It determines a constant plus gradient model\n\		for the local sky parameters using NE, NW, SW, SE quadrants of\n\		an annulus (unless you tell it not to).\n\		Only uses objects with nu (determined by findpeaks) above threshold.\n\		-f to do gaussian ellipsoid fit.\n\		By default, moments etc are determined with gaussian window scale 3.0 pixels.\n\		-e to specify a softened power law window.\n\		-R option to change scale length.\n\		-x option to override this and set window scale for moments\n\		to be mul * obj.rg (rg as determined by hcat2cat)\n\		Use -ve alpha to use aperture = (-alpha) * obj->rg for photometry.\n\		Luminosities incorporate 1 / normfactor from fits header\n\		-m x a to zap disks radius r * r_x, where x = \'g\' or \'n\'\n\		(for r_numax), around neighbours\n\		-Q with -ve alpha to make reference annlus run from r_ap to 2 * r_ap\n\		With -F option, if total mag differs from hfindpeaks mag estimate by > deltam\n\		we ignore rh, total mag in favor of hfindpeaks values.\n\\n\n\n'
Definition at line 1 of file analyse.c.
#define ZAP 0
Definition at line 109 of file analyse.c.
Referenced by main(), and zap().
Function Documentation
void do_object_stats (object * pk, float ** f, int N1, int N2, float(* fsky)(int i, int j), float sigma, float ne, float rc, float alpha)
Definition at line 424 of file analyse.c.
References a, alpha, b, d, di, dj, dx, dy, object::e, f, fit, fsky(), gaussfit(), GC_MAX, i, object::i, j, object::j, MAGIC, N1, N2, ne, phi, PI, powerlawwindow, r, RMAX_MIN, sigma, and W.
Referenced by main().
void dosky (float ** f, int N1, int N2, int ip, int jp, int a1, int a2, skyquad * sky, float fmode, float sigma)
calculates occupation and mode for NSEW sectors; Definition at line 324 of file analyse.c.
References a1, a2, error_exit, f, free(), i, j, liststats(), m, MAGIC, median(), N1, N2, and PI.
Referenced by main().
float fsky (int di, int dj)
Definition at line 629 of file analyse.c.
References di, dj, ff, ffi, ffj, ffmode, and nosky.
Referenced by do_object_stats(), and main().
main (int argc, char * argv[])
Definition at line 112 of file analyse.c.
References a1, a2, allocFloatArray(), allocShortArray(), alpha, deltam(), do_object_stats(), dosky(), error_exit, exit(), f, fdo_stats(), ffmode, fit, fstatsrec::fmode, fread_fits(), fsky(), G_RADIUS, object::i, i, object::j, j, N1, N2, N_RADIUS, ne, nosky, powerlawwindow, RESTORE, RFACTOR, set_fits_ipf(), setskyparameters(), fstatsrec::sigma, usage, write_object(), ZAP, and zap().
void setskyparameters (skyquad * sky)
Definition at line 622 of file analyse.c.
References ff, ffi, and ffj.
Referenced by main().
void zap (int zapmode, object * obj, int radiustype, float a, float ** f, float ** fzap, short ** nzap, int N1, int N2)
Definition at line 640 of file analyse.c.
Variable Documentation
float ff
Definition at line 101 of file analyse.c.
Referenced by apphot(), contourplot(), doplot(), findpeak(), fsky(), gaussfit(), gaussfitn(), getsky(), iisdisplay(), main(), makemodel(), project(), rpetrosian(), and setskyparameters().
float ffi
Definition at line 101 of file analyse.c.
Referenced by fsky(), and setskyparameters().
float ffj
Definition at line 101 of file analyse.c.
Referenced by fsky(), and setskyparameters().
float ffmode
Definition at line 101 of file analyse.c.
Referenced by fsky(), and main().
int fit = 0
Definition at line 102 of file analyse.c.
Referenced by do_object_stats(), and main().
int nosky = 0
Definition at line 104 of file analyse.c.
Referenced by fsky(), and main().
int powerlawwindow
Definition at line 103 of file analyse.c.
Referenced by do_object_stats(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.