apphot.c
NAME
apphot.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include 'apphot.h'
Defines
#define GC_MAX 32
#define R_AP_MIN 1
#define R_SOFTEN 0.3
#define P_MIN 5
#define MAGIC FLOAT_MAGIC
Functions
int apphot (double *flux, double *rh, double *rql, double *rqu, double *rp, double *nbad, double *fmax, double *x, double rap, double *fb0, double *dfb, float **f, int N1, int N2)
double rpetrosian (double *x, float **f, int N1, int N2, double *fb0, double *dfb)
int pixcmp (pixel *pix1, pixel *pix2)
Define Documentation
#define GC_MAX 32
Definition at line 12 of file apphot.c.
Referenced by do_object_stats(), and rpetrosian().
#define MAGIC FLOAT_MAGIC
Definition at line 17 of file apphot.c.
#define P_MIN 5
Definition at line 15 of file apphot.c.
Referenced by apphot().
#define R_AP_MIN 1
Definition at line 13 of file apphot.c.
#define R_SOFTEN 0.3
Definition at line 14 of file apphot.c.
Referenced by apphot().
Function Documentation
int apphot (double * flux, double * rh, double * rql, double * rqu, double * rp, double * nbad, double * fmax, double * x, double rap, double * fb0, double * dfb, float ** f, int N1, int N2)
Definition at line 19 of file apphot.c.
References dr, dx, dy, f, ff, free(), i, ix, MAGIC, N1, N2, P_MIN, pix, pixcmp(), r, R_SOFTEN, rh, and x.
Referenced by main().
int pixcmp (pixel * pix1, pixel * pix2)
Definition at line 187 of file apphot.c.
References pixel::r.
Referenced by apphot().
double rpetrosian (double * x, float ** f, int N1, int N2, double * fb0, double * dfb)
Definition at line 140 of file apphot.c.
References dx, dy, f, ff, GC_MAX, ix, MAGIC, N1, N2, and x.
Author
Generated automatically by Doxygen for imcat from the source code.