apphotmain.c
NAME
apphotmain.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../catlib/cat.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/iostream.h'
#include '../../utils/stats_stuff.h'
#include 'apphot.h'
#include 'zap.h'
Defines
#define usage '\n\n\n\NAME\n\	apphot --- perform aperture photometry\n\\n\SYNOPSIS\n\	apphot	[options...]\n\		-m mul		# r_aperture = mul * r (3.0)\n\		-r rname	# name for aperture radius ('rg')\n\		-R rap		# fixed aperture\n\		-f fitsfile	# specify fits file explicitly\n\		-i 		# ignore local sky parameters\n\		-s		# use local sky model from getsky\n\		-z zeropoint	# zeropoint for magnitude scale (20)\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\		-M rapmax	# maximum aperture for photometry (50)\n\		-o		# send the source image to stdout followed by the catalog\n\\n\DESCRIPTION\n\	By default, 'apphot' measures flux and mag for aperture of radius\n\	mul * rg as determined by hfindpeaks, though you can use the -r\n\	(and optionally the -m option) to choose an alternative, or use\n\	the -R option to specify a fixed aperture.\n\\n\	It adds to the catalogue objects the following items\n\\n\		flux	# flux (sum of pixel values) within the aperture\n\		mag	# magnitude = zeropoint - 2.5 * log_10(flux)\n\		rh	# radius within which 1/2 of flux is found\n\		rp	# Petrosian radius\n\		rql	# radius within which 1/4 of flux is found\n\		rqu	# radius within which 3/4 of flux is found\n\		nbad	# number of magic pixels within the aperture\n\		fmax	# highest pixel value within aperture. \n\\n\	The 'Petrosian' radius 'rp' is defined to be the first\n\	maximum in the cumulative enclosed flux divided by the radius.\n\	In order to avoid assigning an unreasonably small petrosian radii\n\	to small objects where the centroid happens to lie very close to\n\	the centre of a pixel we 'soften' the radius: r -> sqrt(r^2 + 0.3^2)\n\\n\	Apphot takes all of the pixels whose centres fall within a distance\n\	less than r_aperture, sorts them by (softened) distance, and computes the\n\	half-light radius, and also the 'quartile' radii rql, rqu which\n\	contain 25 and 75 percent of the light respectively.\n\	It also outputs a count of 'bad pixels' nbad, which are pixels\n\	whose centres fall within the aperture, but are either MAGIC or\n\	lie off the image.\n\	To compute the magnitude it looks for zeropoint in the input catalogue\n\	header unless you override this with -z option.\n\\n\	It looks for fits filename in the header variable 'fits_name'\n\	unless you specify alternative with -f option. The argument here\n\	can be 'somecommand |' to generate the image on the fly.\n\\n\	With the -s option it will use local sky background parameters\n\	fb0 and dfb generated by getsky. This used to be controlled\n\	by a header item and could be overridden with the -i option.\n\	The -i option is now ignorred.\n\\n\	With the '-Z' option, we ignore pixels around other objects if\n\	distance is <= r * mul.\n\\n\	Objects with negative fluxes are assigned magnitude -100.0.\n\\n\	In order to get good 'total' magnitudes, it is necessary that you\n\	use a good radius (big enough to get nearly all the light, but small\n\	enough to avoid counting neighbour object light). This is a tricky\n\	problem in general. I have found that 'rg' computed by 'hfindpeaks'\n\	provides a good choice (that's why I adopted it as the default), but\n\	if you have a catalogue of objects with no decent size parameter\n\	a reasonable alternative is to run apphot to compute the petrosian\n\	radius using a fixed aperture of say 10 pixels, and then use a suitable\n\	multiple (say 2.0) of rp as the aperture for a second pass.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	apphot --- perform aperture photometry\n\\n\SYNOPSIS\n\	apphot	[options...]\n\		-m mul		# r_aperture = mul * r (3.0)\n\		-r rname	# name for aperture radius ('rg')\n\		-R rap		# fixed aperture\n\		-f fitsfile	# specify fits file explicitly\n\		-i 		# ignore local sky parameters\n\		-s		# use local sky model from getsky\n\		-z zeropoint	# zeropoint for magnitude scale (20)\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\		-M rapmax	# maximum aperture for photometry (50)\n\		-o		# send the source image to stdout followed by the catalog\n\\n\DESCRIPTION\n\	By default, 'apphot' measures flux and mag for aperture of radius\n\	mul * rg as determined by hfindpeaks, though you can use the -r\n\	(and optionally the -m option) to choose an alternative, or use\n\	the -R option to specify a fixed aperture.\n\\n\	It adds to the catalogue objects the following items\n\\n\		flux	# flux (sum of pixel values) within the aperture\n\		mag	# magnitude = zeropoint - 2.5 * log_10(flux)\n\		rh	# radius within which 1/2 of flux is found\n\		rp	# Petrosian radius\n\		rql	# radius within which 1/4 of flux is found\n\		rqu	# radius within which 3/4 of flux is found\n\		nbad	# number of magic pixels within the aperture\n\		fmax	# highest pixel value within aperture. \n\\n\	The 'Petrosian' radius 'rp' is defined to be the first\n\	maximum in the cumulative enclosed flux divided by the radius.\n\	In order to avoid assigning an unreasonably small petrosian radii\n\	to small objects where the centroid happens to lie very close to\n\	the centre of a pixel we 'soften' the radius: r -> sqrt(r^2 + 0.3^2)\n\\n\	Apphot takes all of the pixels whose centres fall within a distance\n\	less than r_aperture, sorts them by (softened) distance, and computes the\n\	half-light radius, and also the 'quartile' radii rql, rqu which\n\	contain 25 and 75 percent of the light respectively.\n\	It also outputs a count of 'bad pixels' nbad, which are pixels\n\	whose centres fall within the aperture, but are either MAGIC or\n\	lie off the image.\n\	To compute the magnitude it looks for zeropoint in the input catalogue\n\	header unless you override this with -z option.\n\\n\	It looks for fits filename in the header variable 'fits_name'\n\	unless you specify alternative with -f option. The argument here\n\	can be 'somecommand |' to generate the image on the fly.\n\\n\	With the -s option it will use local sky background parameters\n\	fb0 and dfb generated by getsky. This used to be controlled\n\	by a header item and could be overridden with the -i option.\n\	The -i option is now ignorred.\n\\n\	With the '-Z' option, we ignore pixels around other objects if\n\	distance is <= r * mul.\n\\n\	Objects with negative fluxes are assigned magnitude -100.0.\n\\n\	In order to get good 'total' magnitudes, it is necessary that you\n\	use a good radius (big enough to get nearly all the light, but small\n\	enough to avoid counting neighbour object light). This is a tricky\n\	problem in general. I have found that 'rg' computed by 'hfindpeaks'\n\	provides a good choice (that's why I adopted it as the default), but\n\	if you have a catalogue of objects with no decent size parameter\n\	a reasonable alternative is to run apphot to compute the petrosian\n\	radius using a fixed aperture of say 10 pixels, and then use a suitable\n\	multiple (say 2.0) of rp as the aperture for a second pass.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n\n'
Definition at line 5 of file apphotmain.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 100 of file apphotmain.c.
References add_comment(), addargscomment(), addobjectitem(), object::addrlist, allocFloatArray(), allocitemcontents(), allocobjectcontents(), allocShortArray(), apphot(), BINARY_FILE_TYPE, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), error_exit, exit(), iostream::f, f, fits, getheaderitemaddress(), getobjectitemindex(), inheritcontents(), ix, mag, N1, N2, newitem(), newobject(), NUM_TYPE, openiostream(), r, read2Dfloatimage(), readcathead(), readobject(), rh, setcatipf(), setcatopf(), setcatopfiletype(), UNZAP_MODE, usage, writecathead(), writefitsheader(), writefitsplane(), writeobject(), x, zap(), and ZAP_MODE.
Author
Generated automatically by Doxygen for imcat from the source code.