apphot.h
NAME
apphot.h -
SYNOPSIS
Data Structures
struct pixel
Typedefs
typedef pixel pixel
Functions
int apphot (double *flux, double *rh, double *rql, double *rqu, double *rp, double *nbad, double *fmax, double *x, double rap, double *fb0, double *dfb, float **f, int N1, int N2)
double rpetrosian (double *x, float **f, int N1, int N2, double *fb0, double *dfb)
int pixcmp (pixel *pix1, pixel *pix2)
Typedef Documentation
typedef struct pixel pixel
Referenced by alloc_grays(), alloc_shades(), set_grays(), and set_shades().
Function Documentation
int apphot (double * flux, double * rh, double * rql, double * rqu, double * rp, double * nbad, double * fmax, double * x, double rap, double * fb0, double * dfb, float ** f, int N1, int N2)
Definition at line 19 of file apphot.c.
References dr, dx, dy, f, ff, free(), i, ix, MAGIC, N1, N2, P_MIN, pix, pixcmp(), r, R_SOFTEN, rh, and x.
Referenced by main().
int pixcmp (pixel * pix1, pixel * pix2)
Definition at line 187 of file apphot.c.
References pixel::r.
Referenced by apphot().
double rpetrosian (double * x, float ** f, int N1, int N2, double * fb0, double * dfb)
Definition at line 140 of file apphot.c.
References dx, dy, f, ff, GC_MAX, ix, MAGIC, N1, N2, and x.
Author
Generated automatically by Doxygen for imcat from the source code.