applytrans.c
NAME
applytrans.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'fmode.h'
Defines
#define usage '\n\NAME\n\	applytrans --- apply transformations from fitstack\n\\n\SYNOPSIS\n\	applytrans parfile\n\\n\DESCRIPTION\n\	'applytrans' reads from stdin a catalogue containing the result of\n\	merging all pairs of cats for a stack of 'nexp' images (as created\n\	by 'mergestacks1') and applies the transformations \n\	defined in 'parfile' (as created by fitstack)\n\	to generate sky coords r, so we can then filter to remove\n\	discrepant pairs.\n\	See also fitstack.tex.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
#define SCALE 1.0
Functions
main (int argc, char *argv[])
Define Documentation
#define SCALE 1.0
Definition at line 25 of file applytrans.c.
#define usage '\n\NAME\n\	applytrans --- apply transformations from fitstack\n\\n\SYNOPSIS\n\	applytrans parfile\n\\n\DESCRIPTION\n\	'applytrans' reads from stdin a catalogue containing the result of\n\	merging all pairs of cats for a stack of 'nexp' images (as created\n\	by 'mergestacks1') and applies the transformations \n\	defined in 'parfile' (as created by fitstack)\n\	to generate sky coords r, so we can then filter to remove\n\	discrepant pairs.\n\	See also fitstack.tex.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
Definition at line 1 of file applytrans.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 27 of file applytrans.c.
References a, d, e, error_exit, exit(), f(), i, j, l, line, ll, M, m, mag, n, phi, r, usage, x, and xp().
Author
Generated automatically by Doxygen for imcat from the source code.