args.c
NAME
args.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include 'args.h'
Functions
int argsinit (int argc, char *argv[], char *theusage)
char * getflag (void)
void argserror (char *errorstring, int argshift)
char * getargs (void)
int getargi (void)
float getargf (void)
double getargd (void)
int nextargtype (void)
Variables
int garg
int gargc
char ** gargv
char * gusage
Function Documentation
void argserror (char * errorstring, int argshift)
Definition at line 45 of file args.c.
References exit(), garg, gargv, and gusage.
Referenced by getargd(), getargf(), getargi(), getflag(), and main().
int argsinit (int argc, char * argv[], char * theusage)
Definition at line 16 of file args.c.
References garg, gargc, gargv, and gusage.
Referenced by main().
double getargd (void)
Definition at line 113 of file args.c.
References argserror(), f, garg, gargc, gargv, and pos.
Referenced by main().
float getargf (void)
Definition at line 94 of file args.c.
References argserror(), f, garg, gargc, gargv, and pos.
Referenced by main().
int getargi (void)
Definition at line 73 of file args.c.
References argserror(), garg, gargc, gargv, i, and pos.
Referenced by main().
char* getargs (void)
Definition at line 59 of file args.c.
References exit(), garg, gargc, gargv, and gusage.
Referenced by main().
char* getflag (void)
Definition at line 25 of file args.c.
References argserror(), garg, gargc, and gargv.
Referenced by main().
int nextargtype (void)
Definition at line 131 of file args.c.
References f, FLAG_ARG, FNUM_ARG, garg, gargc, gargv, i, INUM_ARG, NO_ARG, pos, STDSTREAM_ARG, and TEXT_ARG.
Referenced by main().
Variable Documentation
int garg [static]
Definition at line 12 of file args.c.
Referenced by argserror(), argsinit(), getargd(), getargf(), getargi(), getargs(), getflag(), and nextargtype().
int gargc [static]
Definition at line 12 of file args.c.
Referenced by argsinit(), getargd(), getargf(), getargi(), getargs(), getflag(), and nextargtype().
char** gargv [static]
Definition at line 13 of file args.c.
Referenced by argserror(), argsinit(), getargd(), getargf(), getargi(), getargs(), getflag(), and nextargtype().
char * gusage [static]
Definition at line 13 of file args.c.
Referenced by argserror(), argsinit(), and getargs().
Author
Generated automatically by Doxygen for imcat from the source code.