arrays.h
NAME
arrays.h -
SYNOPSIS
Functions
void * checkalloc (int nel, int size)
void allocShortArray (short ***f, int N1, int N2)
void allocFloatArray (float ***f, int N1, int N2)
void freeShortArray (short **f, int N1, int N2)
void freeFloatArray (float **f, int N1, int N2)
void copyFloatToShort (float **fsrc, short **fdst, int N1, int N2)
void copyShortToFloat (short **fsrc, float **fdst, int N1, int N2)
float *** alloc3DFloatArray (int N1, int N2, int N3)
void free3DFloatArray (float ***f, int N1, int N2, int N3)
Function Documentation
float*** alloc3DFloatArray (int N1, int N2, int N3)
Definition at line 109 of file arrays.c.
References checkalloc(), f, i, j, N1, and N2.
void allocFloatArray (float *** f, int N1, int N2)
Definition at line 43 of file arrays.c.
References error_exit, f, i, N1, and N2.
Referenced by fread_fits(), main(), read2Dfloatimage(), readimheader(), start_command(), and surfaceplot().
void allocShortArray (short *** f, int N1, int N2)
routines for allocating, freeing and copying 2-D arrays
these are the old style non-contiguous storage versions no longer used Definition at line 26 of file arrays.c.
References error_exit, f, i, N1, and N2.
Referenced by main().
void* checkalloc (int nel, int size)
routines for allocating, freeing and copying 2-D/3-D arrays
these are the newstyle contiguous storage versions Definition at line 15 of file arrays.c.
References error_exit, and size.
Referenced by alloc3DFloatArray(), and main().
void copyFloatToShort (float ** fsrc, short ** fdst, int N1, int N2)
Definition at line 85 of file arrays.c.
References i, j, N1, and N2.
void copyShortToFloat (short ** fsrc, float ** fdst, int N1, int N2)
Definition at line 98 of file arrays.c.
References i, j, N1, and N2.
void free3DFloatArray (float *** f, int N1, int N2, int N3)
Definition at line 127 of file arrays.c.
References f, free(), and i.
void freeFloatArray (float ** f, int N1, int N2)
Definition at line 73 of file arrays.c.
References f, free(), i, and N2.
Referenced by main(), and start_command().
void freeShortArray (short ** f, int N1, int N2)
Definition at line 61 of file arrays.c.
References f, free(), i, and N2.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.