arrays.c
NAME
arrays.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include 'error.h'
#include 'arrays.h'
Functions
void * checkalloc (int nel, int size)
void allocShortArray (short ***f, int N1, int N2)
void allocFloatArray (float ***f, int N1, int N2)
void freeShortArray (short **f, int N1, int N2)
void freeFloatArray (float **f, int N1, int N2)
void copyFloatToShort (float **fsrc, short **fdst, int N1, int N2)
void copyShortToFloat (short **fsrc, float **fdst, int N1, int N2)
float *** alloc3DFloatArray (int N1, int N2, int N3)
void free3DFloatArray (float ***f, int N1, int N2, int N3)
Function Documentation
float*** alloc3DFloatArray (int N1, int N2, int N3)
Definition at line 109 of file arrays.c.
References checkalloc(), f, i, j, N1, and N2.
void allocFloatArray (float *** f, int N1, int N2)
Definition at line 43 of file arrays.c.
void allocShortArray (short *** f, int N1, int N2)
Definition at line 26 of file arrays.c.
void* checkalloc (int nel, int size)
routines for allocating, freeing and copying 2-D/3-D arrays
these are the newstyle contiguous storage versions Definition at line 15 of file arrays.c.
References error_exit, and size.
Referenced by alloc3DFloatArray(), and main().
void copyFloatToShort (float ** fsrc, short ** fdst, int N1, int N2)
Definition at line 85 of file arrays.c.
void copyShortToFloat (short ** fsrc, float ** fdst, int N1, int N2)
Definition at line 98 of file arrays.c.
void free3DFloatArray (float *** f, int N1, int N2, int N3)
Definition at line 127 of file arrays.c.
References f, free(), and i.
void freeFloatArray (float ** f, int N1, int N2)
Definition at line 73 of file arrays.c.
void freeShortArray (short ** f, int N1, int N2)
Definition at line 61 of file arrays.c.
Author
Generated automatically by Doxygen for imcat from the source code.