arrays_noncontig.c
NAME
arrays_noncontig.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include 'error.h'
#include 'arrays.h'
Functions
void allocShortArray (short ***f, int N1, int N2)
void allocFloatArray (float ***f, int N1, int N2)
void freeShortArray (short **f, int N1, int N2)
void freeFloatArray (float **f, int N1, int N2)
void copyFloatToShort (float **fsrc, short **fdst, int N1, int N2)
void copyShortToFloat (short **fsrc, float **fdst, int N1, int N2)
Function Documentation
void allocFloatArray (float *** f, int N1, int N2)
Definition at line 34 of file arrays_noncontig.c.
References error_exit, f, i, N1, and N2.
Referenced by fread_fits(), main(), read2Dfloatimage(), readimheader(), start_command(), and surfaceplot().
void allocShortArray (short *** f, int N1, int N2)
routines for allocating, freeing and copying 2-D arrays
these are the old style non-contiguous storage versions no longer used Definition at line 16 of file arrays_noncontig.c.
References error_exit, f, i, N1, and N2.
Referenced by main().
void copyFloatToShort (float ** fsrc, short ** fdst, int N1, int N2)
Definition at line 79 of file arrays_noncontig.c.
References i, j, N1, and N2.
void copyShortToFloat (short ** fsrc, float ** fdst, int N1, int N2)
Definition at line 92 of file arrays_noncontig.c.
References i, j, N1, and N2.
void freeFloatArray (float ** f, int N1, int N2)
Definition at line 66 of file arrays_noncontig.c.
References f, free(), i, and N2.
Referenced by main(), and start_command().
void freeShortArray (short ** f, int N1, int N2)
Definition at line 53 of file arrays_noncontig.c.
References f, free(), i, and N2.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.