asciitofits.c
NAME
asciitofits.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	asciitofits --- converts an ascii image to fits format\n\\n\SYNOPSIS\n\	asciitofits [option...]\n\\n\DESCRIPTION\n\	'asciitofits' reads an ascii format image from stdin\n\	and writes a fits image to stdout\n\		-f	# create float format fits file\n\		-i	# create 32 bit int format fits file\n\		-p	# data in 2-hex digits a la postscript \n\	ascii format is # N2 N1 then N2 x N1 pixvals \n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	asciitofits --- converts an ascii image to fits format\n\\n\SYNOPSIS\n\	asciitofits [option...]\n\\n\DESCRIPTION\n\	'asciitofits' reads an ascii format image from stdin\n\	and writes a fits image to stdout\n\		-f	# create float format fits file\n\		-i	# create 32 bit int format fits file\n\		-p	# data in 2-hex digits a la postscript \n\	ascii format is # N2 N1 then N2 x N1 pixvals \n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file asciitofits.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 31 of file asciitofits.c.
References add_comment(), allocFloatArray(), error_exit, exit(), f, fits, FLOAT_PIXTYPE, i, INT_PIXTYPE, j, N1, N2, new2Dfitsheader(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.