.TH "asciitofits.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asciitofits.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include '../imlib/fits.h'\fP
.br
\fC#include '../utils/error.h'\fP
.br
\fC#include '../utils/arrays.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	asciitofits --- converts an \fBascii\fP image to \fBfits\fP format\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	asciitofits [option...]\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'asciitofits' reads an \fBascii\fP format image from stdin\\\fBn\fP\\	and writes \fBa\fP \fBfits\fP image to stdout\\\fBn\fP\\		-f	# create float format \fBfits\fP file\\\fBn\fP\\		-\fBi\fP	# create 32 bit int format \fBfits\fP file\\\fBn\fP\\		-p	# \fBdata\fP in 2-hex digits \fBa\fP la postscript   \\\fBn\fP\\	\fBascii\fP format is # \fBN2\fP \fBN1\fP then \fBN2\fP x \fBN1\fP pixvals \\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@cita.utoronto.ca\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	asciitofits --- converts an \fBascii\fP image to \fBfits\fP format\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	asciitofits [option...]\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'asciitofits' reads an \fBascii\fP format image from stdin\\\fBn\fP\\	and writes \fBa\fP \fBfits\fP image to stdout\\\fBn\fP\\		-f	# create float format \fBfits\fP file\\\fBn\fP\\		-\fBi\fP	# create 32 bit int format \fBfits\fP file\\\fBn\fP\\		-p	# \fBdata\fP in 2-hex digits \fBa\fP la postscript   \\\fBn\fP\\	\fBascii\fP format is # \fBN2\fP \fBN1\fP then \fBN2\fP x \fBN1\fP pixvals \\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@cita.utoronto.ca\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 1 of file asciitofits.c.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 31 of file asciitofits.c.
.PP
References add_comment(), allocFloatArray(), error_exit, exit(), f, fits, FLOAT_PIXTYPE, i, INT_PIXTYPE, j, N1, N2, new2Dfitsheader(), usage, and write2Dfloatimage().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
