.TH "average.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
average.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBF_INTERP\fP   0"
.br
.ti -1c
.RI "#define \fBF_MEAN\fP   1"
.br
.ti -1c
.RI "#define \fBF_MEDIAN\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBmean\fP (double **y, int \fBj\fP)"
.br
.ti -1c
.RI "double \fBmedian\fP (double **y, int \fBj\fP)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define F_INTERP   0"
.PP
Definition at line 6 of file average.h.
.PP
Referenced by main(), and painttriangle().
.SS "#define F_MEAN   1"
.PP
Definition at line 7 of file average.h.
.PP
Referenced by main(), and painttriangle().
.SS "#define F_MEDIAN   2"
.PP
Definition at line 8 of file average.h.
.PP
Referenced by main(), and painttriangle().
.SH "Function Documentation"
.PP 
.SS "double mean (double ** y, int j)"
.PP
Definition at line 8 of file average.c.
.SS "double median (double ** y, int j)"
.PP
Definition at line 20 of file average.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
