average.c
NAME
average.c -
SYNOPSIS
#include <math.h>
Functions
double mean (double **y, int j)
double median (double **y, int j)
Function Documentation
double mean (double ** y, int j)
Definition at line 8 of file average.c.
Referenced by computeSigma(), and fitLine().
double median (double ** y, int j)
Definition at line 20 of file average.c.
Referenced by avsigclip(), cdl_zscale(), dosky(), fdo_stats(), getsky(), liststats(), main(), pointmedian(), and pruneextreme().
Author
Generated automatically by Doxygen for imcat from the source code.