.TH "average.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
average.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBmean\fP (double **y, int \fBj\fP)"
.br
.ti -1c
.RI "double \fBmedian\fP (double **y, int \fBj\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double mean (double ** y, int j)"
.PP
Definition at line 8 of file average.c.
.PP
Referenced by computeSigma(), and fitLine().
.SS "double median (double ** y, int j)"
.PP
Definition at line 20 of file average.c.
.PP
Referenced by avsigclip(), cdl_zscale(), dosky(), fdo_stats(), getsky(), liststats(), main(), pointmedian(), and pruneextreme().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
