avgpixstack.c
NAME
avgpixstack.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'avgpixstack.h'
#include 'utils/error.h'
#include 'imlib/fits.h'
Functions
int thefloatcmp ()
float median (float *f, int nel)
float rankedimage (float *f, int nel, int rank)
int avgpixstack (int opmode, int rank, int nplanes, float *f, float *weight, float *ftemp, float *favg, float *weightsum)
int thefloatcmp (float *s1, float *s2)
Function Documentation
int avgpixstack (int opmode, int rank, int nplanes, float * f, float * weight, float * ftemp, float * favg, float * weightsum)
Definition at line 21 of file avgpixstack.c.
References APS_MEDIAN, APS_RANK, f, FLOAT_MAGIC, i, j, median(), opmode, and rankedimage().
Referenced by main().
float median (float * f, int nel)
Definition at line 74 of file avgpixstack.c.
References error_exit, f, and thefloatcmp().
float rankedimage (float * f, int nel, int rank)
Definition at line 90 of file avgpixstack.c.
References error_exit, f, and thefloatcmp().
int thefloatcmp (float * s1, float * s2)
Definition at line 109 of file avgpixstack.c.
int thefloatcmp ()
Referenced by avsigclip(), median(), and rankedimage().
Author
Generated automatically by Doxygen for imcat from the source code.