avgpixstack.h
NAME
avgpixstack.h -
SYNOPSIS
Defines
#define APS_STRAIGHT_AVERAGE 0
#define APS_WEIGHTED_AVERAGE 1
#define APS_MEDIAN 2
#define APS_RANK 3
Functions
int avgpixstack (int opmode, int rank, int nplanes, float *f, float *weight, float *ftemp, float *favg, float *weightsum)
Define Documentation
#define APS_MEDIAN 2
Definition at line 20 of file avgpixstack.h.
Referenced by avgpixstack(), and main().
#define APS_RANK 3
Definition at line 21 of file avgpixstack.h.
Referenced by avgpixstack(), and main().
#define APS_STRAIGHT_AVERAGE 0
Definition at line 18 of file avgpixstack.h.
Referenced by main().
#define APS_WEIGHTED_AVERAGE 1
Definition at line 19 of file avgpixstack.h.
Referenced by main().
Function Documentation
int avgpixstack (int opmode, int rank, int nplanes, float * f, float * weight, float * ftemp, float * favg, float * weightsum)
Definition at line 21 of file avgpixstack.c.
References APS_MEDIAN, APS_RANK, f, FLOAT_MAGIC, i, j, median(), opmode, and rankedimage().
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.