back.h
NAME
back.h -
SYNOPSIS
Functions
void readimheader (int *n1, int *n2)
void set_shades (void)
void alloc_shades (void)
void create_pixmap (void)
void fill_pixmap (void)
void makeXImage (void)
void showpixmap (void)
int myworkproc1 (XtPointer client_data)
void setblocksize (int b)
void setfrange (float ffmin, float ffmax)
void setcolormapindex (int theindex)
Function Documentation
void alloc_shades (void)
Definition at line 104 of file back.c.
void create_pixmap (void)
Definition at line 165 of file back.c.
References blocksize, depth, mydisplay, mywindow, N1, N2, and pixmap.
void fill_pixmap (void)
Definition at line 174 of file back.c.
void makeXImage (void)
Definition at line 205 of file back.c.
References blocksize, depth, exit(), malloc(), mydisplay, myscreen, N1, N2, and theimage.
int myworkproc1 (XtPointer client_data)
Definition at line 246 of file back.c.
void readimheader (int * n1, int * n2)
Definition at line 52 of file back.c.
References allocFloatArray(), error_exit, f, fits, getcommentbyname(), getnumericvalue(), fitsheader::n, N1, N2, fitsheader::ndim, nframes, readfitsheader(), and timestep.
Referenced by main().
void set_shades (void)
Definition at line 76 of file back.c.
void setblocksize (int b)
Definition at line 282 of file back.c.
References b, and blocksize.
Referenced by main().
void setcolormapindex (int theindex)
Definition at line 295 of file back.c.
References colormapindex.
Referenced by main().
void setfrange (float ffmin, float ffmax)
Definition at line 287 of file back.c.
References gfmax, and gfmin.
Referenced by main().
void showpixmap (void)
Definition at line 268 of file back.c.
Author
Generated automatically by Doxygen for imcat from the source code.