back.c
NAME
back.c -
SYNOPSIS
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include 'front.h'
#include 'back.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/colormaps.h'
Defines
#define MAX_SHADES 4096
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
#define MAGIC SHORT_MAGIC
#define MAX_COLS 65535
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
Functions
void readimheader (int *n1, int *n2)
void set_shades (void)
void alloc_shades (void)
void create_pixmap (void)
void fill_pixmap (void)
void makeXImage (void)
int myworkproc1 (XtPointer client_data)
void showpixmap (void)
void setblocksize (int b)
void setfrange (float ffmin, float ffmax)
void setcolormapindex (int theindex)
Variables
int ncolors
int myscreen
int depth
GC mygc
Window mywindow
XImage * theimage
Pixmap pixmap
Colormap cmap
Display * mydisplay
XColor shade [MAX_SHADES]
unsigned long pixel [MAX_SHADES]
unsigned int n_shades
float ** f
float gfmin
float gfmax
int N1
int N2
int blocksize
int colormapindex
int nframes
fitsheader * fits
float timestep
Define Documentation
#define MAGIC SHORT_MAGIC
Definition at line 25 of file back.c.
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
Definition at line 47 of file back.c.
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
Definition at line 47 of file back.c.
#define MAX_COLS 65535
Definition at line 46 of file back.c.
Referenced by main(), and set_shades().
#define MAX_SHADES 4096
Definition at line 20 of file back.c.
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
Definition at line 48 of file back.c.
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
Definition at line 48 of file back.c.
Function Documentation
void alloc_shades (void)
Definition at line 104 of file back.c.
Referenced by main(), and myworkproc1().
void create_pixmap (void)
Definition at line 165 of file back.c.
Referenced by main(), and myworkproc1().
void fill_pixmap (void)
Definition at line 174 of file back.c.
Referenced by main(), makepreview(), myworkproc1(), and myworkproc3().
void makeXImage (void)
Definition at line 205 of file back.c.
Referenced by main(), and myworkproc1().
int myworkproc1 (XtPointer client_data)
Definition at line 246 of file back.c.
Referenced by main().
void readimheader (int * n1, int * n2)
Definition at line 52 of file back.c.
References allocFloatArray(), error_exit, f, fits, getcommentbyname(), getnumericvalue(), fitsheader::n, N1, N2, fitsheader::ndim, nframes, readfitsheader(), and timestep.
Referenced by main().
void set_shades (void)
Definition at line 76 of file back.c.
Referenced by alloc_shades(), myworkproc1(), and sliderChanged().
void setblocksize (int b)
Definition at line 282 of file back.c.
References b, and blocksize.
Referenced by main().
void setcolormapindex (int theindex)
Definition at line 295 of file back.c.
References colormapindex.
Referenced by main().
void setfrange (float ffmin, float ffmax)
Definition at line 287 of file back.c.
References gfmax, and gfmin.
Referenced by main().
void showpixmap (void)
Definition at line 268 of file back.c.
Referenced by main(), myworkproc1(), myworkproc3(), UnZoom(), and Zoom().
Variable Documentation
int blocksize [static]
Definition at line 41 of file back.c.
Referenced by create_pixmap(), fill_pixmap(), makeXImage(), setblocksize(), and showpixmap().
Colormap cmap [static]
Definition at line 35 of file back.c.
Referenced by alloc_shades().
int colormapindex [static]
Definition at line 41 of file back.c.
Referenced by set_shades(), and setcolormapindex().
int depth [static]
Definition at line 29 of file back.c.
Referenced by alloc_shades(), create_pixmap(), and makeXImage().
float** f [static]
Definition at line 40 of file back.c.
fitsheader* fits [static]
Definition at line 42 of file back.c.
float gfmax [static]
Definition at line 40 of file back.c.
Referenced by fill_pixmap(), and setfrange().
float gfmin [static]
Definition at line 40 of file back.c.
Referenced by fill_pixmap(), and setfrange().
Display* mydisplay [static]
Definition at line 36 of file back.c.
Referenced by alloc_shades(), create_pixmap(), fill_pixmap(), makeXImage(), and myworkproc1().
GC mygc [static]
Definition at line 30 of file back.c.
Referenced by alloc_shades(), and fill_pixmap().
int myscreen [static]
Definition at line 29 of file back.c.
Referenced by alloc_shades(), and makeXImage().
Window mywindow [static]
Definition at line 31 of file back.c.
Referenced by alloc_shades(), and create_pixmap().
int N1 [static]
Definition at line 41 of file back.c.
int N2 [static]
Definition at line 41 of file back.c.
unsigned int n_shades [static]
Definition at line 39 of file back.c.
Referenced by alloc_shades(), fill_pixmap(), and set_shades().
int ncolors [static]
Definition at line 28 of file back.c.
int nframes [static]
Definition at line 41 of file back.c.
unsigned long pixel[MAX_SHADES] [static]
Definition at line 38 of file back.c.
Pixmap pixmap [static]
Definition at line 34 of file back.c.
Referenced by create_pixmap(), fill_pixmap(), and showpixmap().
XColor shade[MAX_SHADES] [static]
Definition at line 37 of file back.c.
Referenced by alloc_shades(), fill_pixmap(), and set_shades().
XImage* theimage [static]
Definition at line 32 of file back.c.
Referenced by fill_pixmap(), and makeXImage().
float timestep [static]
Definition at line 43 of file back.c.
Referenced by myworkproc1(), and readimheader().
Author
Generated automatically by Doxygen for imcat from the source code.