.TH "badface" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
badface \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtriedge\fP \fBbadfacetri\fP"
.br
.ti -1c
.RI "REAL \fBkey\fP"
.br
.ti -1c
.RI "\fBpoint\fP \fBfaceorg\fP"
.br
.ti -1c
.RI "\fBpoint\fP \fBfacedest\fP"
.br
.ti -1c
.RI "\fBpoint\fP \fBfaceapex\fP"
.br
.ti -1c
.RI "\fBbadface\fP * \fBnextface\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBtriedge\fP \fBbadface::badfacetri\fP"
.PP
Definition at line 531 of file triangle.c.
.SS "\fBpoint\fP \fBbadface::faceapex\fP"
.PP
Definition at line 533 of file triangle.c.
.SS "\fBpoint\fP \fBbadface::facedest\fP"
.PP
Definition at line 533 of file triangle.c.
.SS "\fBpoint\fP \fBbadface::faceorg\fP"
.PP
Definition at line 533 of file triangle.c.
.SS "REAL \fBbadface::key\fP"
.PP
Definition at line 532 of file triangle.c.
.SS "struct \fBbadface\fP* \fBbadface::nextface\fP"
.PP
Definition at line 534 of file triangle.c.
.PP
Referenced by dequeuebadtri(), and enqueuebadtri().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
