.TH "badsegment" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
badsegment \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBedge\fP \fBencsegment\fP"
.br
.ti -1c
.RI "\fBpoint\fP \fBsegorg\fP"
.br
.ti -1c
.RI "\fBpoint\fP \fBsegdest\fP"
.br
.ti -1c
.RI "\fBbadsegment\fP * \fBnextsegment\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBedge\fP \fBbadsegment::encsegment\fP"
.PP
Definition at line 521 of file triangle.c.
.SS "struct \fBbadsegment\fP* \fBbadsegment::nextsegment\fP"
.PP
Definition at line 523 of file triangle.c.
.SS "\fBpoint\fP \fBbadsegment::segdest\fP"
.PP
Definition at line 522 of file triangle.c.
.SS "\fBpoint\fP \fBbadsegment::segorg\fP"
.PP
Definition at line 522 of file triangle.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
