betafit.c
NAME
betafit.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../../utils/stats_stuff.h'
#include '../../../utils/powell.h'
#include '../../../utils/nrutil.h'
#include 'betafit.h'
#include 'amoeba.h'
Functions
int fitall (float **n, int N1, int N2, float *f0, float *x0, float *y0, float *rc2, float beta, float *loglhood, float N)
float func (float *p)
void makebetamodel (float **nmodel, int N1, int N2, float f0, float x0, float y0, float rc2, float beta, float N)
Variables
int n1
int n2
float ** gn
float gN
float gbeta
Function Documentation
int fitall (float ** n, int N1, int N2, float * f0, float * x0, float * y0, float * rc2, float beta, float * loglhood, float N)
Definition at line 23 of file betafit.c.
References free_matrix(), free_vector(), func(), gbeta, gn, gN, i, j, matrix(), n, N, n1, N1, n2, N2, powell(), and vector().
Referenced by main().
float func (float * p)
Definition at line 67 of file betafit.c.
Referenced by fitall(), frprmn(), gaussfit(), gaussfitn(), linmin(), mnbrak(), and powell().
void makebetamodel (float ** nmodel, int N1, int N2, float f0, float x0, float y0, float rc2, float beta, float N)
Definition at line 91 of file betafit.c.
References ix, N, N1, and N2.
Referenced by main().
Variable Documentation
float gbeta [static]
Definition at line 20 of file betafit.c.
Referenced by fitall(), and func().
float gN [static]
Definition at line 19 of file betafit.c.
Referenced by fitall(), and func().
float** gn [static]
Definition at line 18 of file betafit.c.
Referenced by fitall(), and func().
int n1 [static]
function for fitting a beta model Definition at line 17 of file betafit.c.
Referenced by fitall(), and func().
int n2 [static]
function for fitting a beta model Definition at line 17 of file betafit.c.
Referenced by fitall(), and func().
Author
Generated automatically by Doxygen for imcat from the source code.