betafit.h
NAME
betafit.h -
SYNOPSIS
Functions
float func (float *p)
int fitall (float **n, int N1, int N2, float *f0, float *x0, float *y0, float *rc2, float beta, float *loglhood, float N)
void makebetamodel (float **nmodel, int N1, int N2, float f0, float x0, float y0, float rc2, float beta, float N)
Function Documentation
int fitall (float ** n, int N1, int N2, float * f0, float * x0, float * y0, float * rc2, float beta, float * loglhood, float N)
Definition at line 23 of file betafit.c.
References free_matrix(), free_vector(), func(), gbeta, gN, gn, i, j, matrix(), N, n, N1, n1, N2, n2, powell(), and vector().
Referenced by main().
float func (float * p)
Definition at line 67 of file betafit.c.
void makebetamodel (float ** nmodel, int N1, int N2, float f0, float x0, float y0, float rc2, float beta, float N)
Definition at line 91 of file betafit.c.
References ix, N, N1, and N2.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.