betafitmain.c
NAME
betafitmain.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../../imlib/fits.h'
#include '../../../utils/error.h'
#include 'betafit.h'
Defines
#define usage '\n\n\n\NAME\n\	betafit --- fit image to beta model\n\\n\SYNOPSIS\n\	betafit [options....]\n\		-u		# print this message\n\		-f		# output the model as fits image\n\		-N N		# number of micropixels per pixel (1.e4)\n\		-v		# verbose mode\n\		-r rc		# initial core radius (1.0)\n\		-b beta		# assumed beta\n\\n\DESCRIPTION\n\	\'betafit\' reads a fits image of counts n[][] from stdin and fits\n\	this to a simple beta model for mean counts with central\n\	value f0; core radius rc; index beta centered on x0, y0:\n\\n\		n_model = n0 * (1 + r^2 / rc^2)^-beta\n\\n\	where n0 = f0 * f and r^2 = (x - x0)^2 + (y - y0)^2\n\\n\	by minimising\n\		sum_pixels N * f - sum_pixels (n[iy][ix] * log(f))\n\\n\	Where N is the number of micropixels per real pixel.\n\\n\	output is\n\\n\		N * f0, x0, y0, rc, beta\n\\n\	We start with x0, y0 given by mean of x,y for input counts\n\	and core radius unity by default and with initial\n\	f = sum n / (N * rc2)\n\\n\BUGS\n\	Couldn't get it to work stably with beta as free parameter.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
#define PI M_PI
Functions
int main (int argc, char *argv[])
Define Documentation
#define PI M_PI
Definition at line 55 of file betafitmain.c.
#define usage '\n\n\n\NAME\n\	betafit --- fit image to beta model\n\\n\SYNOPSIS\n\	betafit [options....]\n\		-u		# print this message\n\		-f		# output the model as fits image\n\		-N N		# number of micropixels per pixel (1.e4)\n\		-v		# verbose mode\n\		-r rc		# initial core radius (1.0)\n\		-b beta		# assumed beta\n\\n\DESCRIPTION\n\	\'betafit\' reads a fits image of counts n[][] from stdin and fits\n\	this to a simple beta model for mean counts with central\n\	value f0; core radius rc; index beta centered on x0, y0:\n\\n\		n_model = n0 * (1 + r^2 / rc^2)^-beta\n\\n\	where n0 = f0 * f and r^2 = (x - x0)^2 + (y - y0)^2\n\\n\	by minimising\n\		sum_pixels N * f - sum_pixels (n[iy][ix] * log(f))\n\\n\	Where N is the number of micropixels per real pixel.\n\\n\	output is\n\\n\		N * f0, x0, y0, rc, beta\n\\n\	We start with x0, y0 given by mean of x,y for input counts\n\	and core radius unity by default and with initial\n\	f = sum n / (N * rc2)\n\\n\BUGS\n\	Couldn't get it to work stably with beta as free parameter.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
Definition at line 1 of file betafitmain.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 59 of file betafitmain.c.
References add_comment(), allocFloatArray(), error_exit, exit(), fitsheader::extpixtype, fitall(), fits, FLOAT_PIXTYPE, ix, makebetamodel(), N, n, N1, N2, read2Dfloatimage(), usage, verbose, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.