boxavg.c
NAME
boxavg.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
#include '../utils/fmedian.h'
Defines
#define usage '\n\n\n\NAME\n\	boxavg - boxcar smooth FITS image of arbitrary dimensionality\n\\n\SYNOPSIS\n\	boxavg [-u] [-m] [-d d0 d1...]\n\\n\DESCRIPTION\n\	\'boxavg\' reads a FITS image of arbitrary dimensionality from\n\	stdin and applies a simple boxcar smoothing. By default the width\n\	of the boxcar is 3 in each dimension, but you can specify an array\n\	d[] with the -d option such that the width in the i'th direction\n\	is 1 + 2 * d[i].\n\\n\	Options:\n\		-u		# print this message\n\		-d d0 d1...	# specify (width-1)/2 of box car (1,1,...)\n\		-m		# take median\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
void getpix (int level)
void accumulate (int level)
int main (int argc, char *argv[])
Variables
float * f0
float * f1
float fsum
float * flist
int * x0
int * x1
int * dx
int * fsize
int domedian
int nsum
fitsheader * fits
Define Documentation
#define usage '\n\n\n\NAME\n\	boxavg - boxcar smooth FITS image of arbitrary dimensionality\n\\n\SYNOPSIS\n\	boxavg [-u] [-m] [-d d0 d1...]\n\\n\DESCRIPTION\n\	\'boxavg\' reads a FITS image of arbitrary dimensionality from\n\	stdin and applies a simple boxcar smoothing. By default the width\n\	of the boxcar is 3 in each dimension, but you can specify an array\n\	d[] with the -d option such that the width in the i'th direction\n\	is 1 + 2 * d[i].\n\\n\	Options:\n\		-u		# print this message\n\		-d d0 d1...	# specify (width-1)/2 of box car (1,1,...)\n\		-m		# take median\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file boxavg.c.
Function Documentation
void accumulate (int level)
Definition at line 165 of file boxavg.c.
References domedian, dx, f0, fits, flist, FLOAT_MAGIC, fsize, fsum, i, fitsheader::n, fitsheader::ndim, nsum, x0, and x1.
Referenced by getpix(), and main().
void getpix (int level)
Definition at line 137 of file boxavg.c.
References accumulate(), domedian, f1, fits, flist, fmedian(), fsize, fsum, getpix(), i, fitsheader::n, fitsheader::ndim, nsum, and x1.
int main (int argc, char * argv[])
Definition at line 44 of file boxavg.c.
References add_comment(), argsinit(), domedian, dx, error_exit, exit(), f0, f1, fits, flag, FLAG_ARG, flist, fsize, getargi(), getflag(), getpix(), i, fitsheader::n, fitsheader::ndim, nextargtype(), readfitsheader(), readfitsline(), usage, writefitsheader(), writefitsline(), writefitstail(), x0, and x1.
Variable Documentation
int domedian [static]
Definition at line 38 of file boxavg.c.
Referenced by accumulate(), getpix(), and main().
int * dx [static]
Definition at line 38 of file boxavg.c.
float* f0 [static]
Definition at line 37 of file boxavg.c.
Referenced by accumulate(), and main().
float * f1 [static]
Definition at line 37 of file boxavg.c.
Referenced by getpix(), and main().
fitsheader* fits [static]
Definition at line 39 of file boxavg.c.
float * flist [static]
Definition at line 37 of file boxavg.c.
Referenced by accumulate(), getpix(), and main().
int * fsize [static]
Definition at line 38 of file boxavg.c.
Referenced by accumulate(), getpix(), and main().
float fsum [static]
Definition at line 37 of file boxavg.c.
Referenced by accumulate(), and getpix().
int nsum [static]
Definition at line 38 of file boxavg.c.
Referenced by accumulate(), and getpix().
int* x0 [static]
Definition at line 38 of file boxavg.c.
Referenced by accumulate(), and main().
int * x1 [static]
Definition at line 38 of file boxavg.c.
Referenced by accumulate(), getpix(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.