.TH "brent.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brent.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBbrent\fP (float ax, float bx, float cx, float(*f)(float), float tol, float *\fBxmin\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float brent (float ax, float bx, float cx, float(* f)(float), float tol, float * xmin)"
.PP
Definition at line 19 of file brent.c.
.PP
References a, b, CGOLD, d, e, getfitstatus(), ITMAX, r, setfitstatus(), SHFT, SIGN, TOO_MANY_ITERATIONS, v, w, x, xmin, and ZEPS.
.PP
Referenced by linmin(), and main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
