brent.h
NAME
brent.h -
SYNOPSIS
Functions
float brent (float ax, float bx, float cx, float(*f)(float), float tol, float *xmin)
Function Documentation
float brent (float ax, float bx, float cx, float(* f)(float), float tol, float * xmin)
Definition at line 19 of file brent.c.
References a, b, CGOLD, d, e, getfitstatus(), ITMAX, r, setfitstatus(), SHFT, SIGN, TOO_MANY_ITERATIONS, v, w, x, xmin, and ZEPS.
Referenced by linmin(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.