brent.c
NAME
brent.c -
SYNOPSIS
#include <math.h>
#include 'brent.h'
#include 'fitstatus.h'
#include 'nrutil.h'
Defines
#define ITMAX 100
#define CGOLD 0.3819660
#define ZEPS 1.0e-10
#define SIGN(a, b) ((b) > 0.0 ? fabs(a) : -fabs(a))
#define SHFT(a, b, c, d) (a)=(b);(b)=(c);(c)=(d);
Functions
float brent (float ax, float bx, float cx, float(*f)(float), float tol, float *xmin)
Define Documentation
#define CGOLD 0.3819660
Definition at line 14 of file brent.c.
#define ITMAX 100
Definition at line 13 of file brent.c.
#define SHFT(a, b, c, d) (a)=(b);(b)=(c);(c)=(d);
Definition at line 17 of file brent.c.
#define SIGN(a, b) ((b) > 0.0 ? fabs(a) : -fabs(a))
Definition at line 16 of file brent.c.
#define ZEPS 1.0e-10
Definition at line 15 of file brent.c.
Function Documentation
float brent (float ax, float bx, float cx, float(* f)(float), float tol, float * xmin)
Definition at line 19 of file brent.c.
References a, b, CGOLD, d, e, getfitstatus(), ITMAX, r, setfitstatus(), SHFT, SIGN, TOO_MANY_ITERATIONS, v, w, x, xmin, and ZEPS.
Referenced by linmin(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.