bscale.c
NAME
bscale.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	bscale - set or check BSCALE, BZERO header values in FITS file\n\\n\SYNOPSIS\n\	bscale [fmin fmax | -g | -u ]\n\\n\DESCRIPTION\n\	\'bscale fmin fmax\' reads an image (which must be an integer\n\	format BITPIX = 8, 16 or 32) from stdin and modifies\n\	or generates BZERO, BSCALE values such that the max and\n\	min representable values are fmin, fmax.\n\	This has the effect of rescaling the image values.\n\\n\	Use \'bscale -g\' to get the current fmin, fmax values.\n\\n\	Use -u option to print this message.\n\\n\	Beware that the minimum representable values for\n\	BITPIX 16, 32 and the maximum representable values\n\	for BITPIX 8 are 'magic' values used by imcat to flag bad\n\	or missing data.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define SETRANGEMODE 0
#define GETRANGEMODE 1
Functions
int main (int argc, char *argv[])
Define Documentation
#define GETRANGEMODE 1
Definition at line 41 of file bscale.c.
Referenced by main().
#define SETRANGEMODE 0
Definition at line 40 of file bscale.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	bscale - set or check BSCALE, BZERO header values in FITS file\n\\n\SYNOPSIS\n\	bscale [fmin fmax | -g | -u ]\n\\n\DESCRIPTION\n\	\'bscale fmin fmax\' reads an image (which must be an integer\n\	format BITPIX = 8, 16 or 32) from stdin and modifies\n\	or generates BZERO, BSCALE values such that the max and\n\	min representable values are fmin, fmax.\n\	This has the effect of rescaling the image values.\n\\n\	Use \'bscale -g\' to get the current fmin, fmax values.\n\\n\	Use -u option to print this message.\n\\n\	Beware that the minimum representable values for\n\	BITPIX 16, 32 and the maximum representable values\n\	for BITPIX 8 are 'magic' values used by imcat to flag bad\n\	or missing data.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file bscale.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 44 of file bscale.c.
References add_comment(), argsinit(), fitsheader::bscale, fitsheader::bscaling, fitsheader::bzero, DBL_PIXTYPE, error_exit, exit(), fitsheader::extpixtype, f, fits, flag, FLAG_ARG, FLOAT_PIXTYPE, fmin, getargd(), getflag(), GETRANGEMODE, INT_PIXTYPE, fitsheader::n, fitsheader::ndim, nextargtype(), opmode, pixsize(), readfitsheader(), SETRANGEMODE, SHORT_PIXTYPE, UCHAR_PIXTYPE, usage, writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.