callbacks.h
NAME
callbacks.h -
SYNOPSIS
Defines
#define IDLE_MODE 0
#define RUN_MODE 1
Functions
char * counter_filter (FL_OBJECT *obj, double value, int prec)
void start_command (void)
Define Documentation
#define IDLE_MODE 0
Definition at line 5 of file callbacks.h.
Referenced by forwardstep_button_callback(), main(), rewind_button_callback(), and stop_button_callback().
#define RUN_MODE 1
Definition at line 6 of file callbacks.h.
Referenced by go_button_callback(), and main().
Function Documentation
char* counter_filter (FL_OBJECT * obj, double value, int prec)
Definition at line 115 of file callbacks.c.
References buf.
Referenced by main().
void start_command (void)
Definition at line 84 of file callbacks.c.
References allocFloatArray(), f, fits, fitsgencommand, framenumber, freeFloatArray(), ipf, fitsheader::n, fitsheader::ndim, nframes, Nx, Ny, and readfitsheader().
Referenced by command_input_callback(), and rewind_button_callback().
Author
Generated automatically by Doxygen for imcat from the source code.