cat.h
NAME
cat.h -
SYNOPSIS
Data Structures
struct cathead
struct comment
struct item
struct object
Defines
#define MAX_DIMS 7
#define NUM_TYPE 0
#define TEXT_TYPE 1
#define COMMENT_TYPE 2
#define CONTENTS_TYPE 3
#define NUM1_OP_TYPE 4
#define NUM2_OP_TYPE 5
#define GEN_OP_TYPE 6
#define BINARY_FILE_TYPE 0
#define TEXT_FILE_TYPE 1
#define BIG_ENDIAN_CAT_BYTE_ORDER 0
#define LITTLE_ENDIAN_CAT_BYTE_ORDER 1
#define NATIVE_CAT_BYTE_ORDER BIG_ENDIAN_CAT_BYTE_ORDER
#define NON_NATIVE_CAT_BYTE_ORDER LITTLE_ENDIAN_CAT_BYTE_ORDER
#define LC_NUM_FMT ' %14.8lg'
#define LC_TEXT_FMT ' %14s'
#define LC_RIGHT_TEXT_FMT ' %14s'
#define LC_HEADER_NAME_FMT '# %-20s %-20s'
#define LC_OBJECT_NAME_FMT ' %s %s'
Typedefs
typedef item item
typedef comment comment
typedef cathead cathead
typedef object object
Functions
cathead * readcathead (void)
void copyheaderinfo (cathead *thecathead, cathead *sourcecathead)
void copycontentinfo (cathead *thecathead, cathead *sourcecathead)
void writecathead (cathead *thecathead)
void freecathead (cathead *thecathead)
void makeitemlist (cathead *thecathead)
int gettype (void)
item * readnewitem (int itype)
item * sscannewitem (int itype, char *string)
item * newitem (char *name, int itype, int ndim,...)
item * newitembydimarray (char *name, int itype, int ndim, int *dim)
item * copyitem (item *sourceitem)
int allocitemcontents (item *theitem, void **addr, int level)
void copyitemcontents (item *dstitem, void *dstaddr, item *srcitem, void *srcaddr, int level)
void freeitem (item *theitem)
void freeitemcontents (item *theitem, void *addr, int level)
int readitem (item *theitem, void *addr, int level)
int sscanitem (item *theitem, void *addr, int level, char **string)
int writeitem (item *theitem, void *addr, int level)
int writelabel (item *theitem, int level)
int writename (item *theitem)
int size (int itype)
int installitem (item *theitem, item **base)
void installcomment (comment *thecomment, comment **base)
void addcomment (char *thetext, cathead *thecathead)
void addargscomment (int argc, char *argv[], cathead *thecathead)
comment * copycomment (comment *sourcecomment)
object * newobject (cathead *thecathead)
void allocobjectcontents (object *theobject)
void connectcatheadtoobject (object *theobject)
void connectobjecttocathead (object *theobject)
int readobject (object *theobject)
void writeobject (object *theobject)
void freeobject (object *theobject)
item * getheaderitem (char *name, cathead *thecathead)
void * getheaderitemaddress (char *name, cathead *thecathead)
void setheaderitemaddress (char *name, cathead *thecathead, void *theaddr)
void deleteheaderitem (char *name, cathead *thecathead)
void addobjectitem (item *newitem, cathead *thecathead)
void deleteobjectitem (char *name, cathead *thecathead)
item * getobjectitem (char *name, cathead *thecathead)
int getobjectitemindex (char *name, object *theobject)
int inheritcontents (object *theobject, object *sourceobject)
void * getaddress (object *theobject, int theindex)
void setaddress (object *theobject, int theindex, void *theaddr)
void copystring (char **thestring, char *sourcestring)
void setcatipf (FILE *stream)
void setcatopf (FILE *stream)
void getcatipfiletype (int *filetype)
void setcatipfiletype (int filetype)
void getcatopfiletype (int *filetype)
void setcatopfiletype (int filetype)
void swapbytes (void *addr, int ndoubles)
void swapint (void *addr, int nint)
int install1numericheaderitem (char *name, double value, cathead *thecat)
int install1textheaderitem (char *name, char *value, cathead *thecat)
Define Documentation
#define BIG_ENDIAN_CAT_BYTE_ORDER 0
Definition at line 21 of file cat.h.
Referenced by readcathead(), and writecathead().
#define BINARY_FILE_TYPE 0
Definition at line 18 of file cat.h.
Referenced by main(), readcathead(), readitem(), writecathead(), and writeitem().
#define COMMENT_TYPE 2
Definition at line 12 of file cat.h.
Referenced by readcathead().
#define CONTENTS_TYPE 3
Definition at line 13 of file cat.h.
Referenced by readcathead().
#define GEN_OP_TYPE 6
Definition at line 16 of file cat.h.
Referenced by evalrpnfunction(), and newopitem().
#define LC_HEADER_NAME_FMT '# %-20s %-20s'
Definition at line 38 of file cat.h.
Referenced by writename().
#define LC_NUM_FMT ' %14.8lg'
Definition at line 33 of file cat.h.
Referenced by main(), writegridcat(), and writeitem().
#define LC_OBJECT_NAME_FMT ' %s %s'
Definition at line 39 of file cat.h.
#define LC_RIGHT_TEXT_FMT ' %14s'
Definition at line 35 of file cat.h.
Referenced by writelabel().
#define LC_TEXT_FMT ' %14s'
Definition at line 34 of file cat.h.
Referenced by writeitem(), and writelabel().
#define LITTLE_ENDIAN_CAT_BYTE_ORDER 1
Definition at line 22 of file cat.h.
Referenced by readcathead().
#define MAX_DIMS 7
Definition at line 8 of file cat.h.
Referenced by main(), readnewitem(), sscannewitem(), and vectorinit().
#define NATIVE_CAT_BYTE_ORDER BIG_ENDIAN_CAT_BYTE_ORDER
Definition at line 28 of file cat.h.
Referenced by readcathead(), and writecathead().
#define NON_NATIVE_CAT_BYTE_ORDER LITTLE_ENDIAN_CAT_BYTE_ORDER
Definition at line 29 of file cat.h.
#define NUM1_OP_TYPE 4
Definition at line 14 of file cat.h.
Referenced by evalrpnfunction(), and newopitem().
#define NUM2_OP_TYPE 5
Definition at line 15 of file cat.h.
Referenced by evalrpnfunction(), and newopitem().
#define NUM_TYPE 0
Definition at line 10 of file cat.h.
Referenced by copyitemcontents(), derefinit(), dospecialname(), dotinit(), evalrpnfunction(), getnumericaddresses(), getop(), grandinit(), ifinit(), install1numericheaderitem(), inverseinit(), lintransinit(), maddinit(), main(), mscaleinit(), msubinit(), newlmodel(), num1func(), num2func(), randinit(), readcathead(), readitem(), readlmodel(), size(), sscanitem(), streqinit(), vaddinit(), vectordoit(), vectorinit(), vscaleinit(), vshiftinit(), vsubinit(), writeitem(), and writelmodel().
#define TEXT_FILE_TYPE 1
Definition at line 19 of file cat.h.
Referenced by main(), readcathead(), readitem(), writecathead(), writeitem(), and writeobject().
#define TEXT_TYPE 1
Definition at line 11 of file cat.h.
Referenced by adddate(), copyitemcontents(), derefinit(), evalrpnfunction(), getop(), install1textheaderitem(), main(), readcathead(), readitem(), size(), sscanitem(), streqinit(), vectordoit(), vectorinit(), writecathead(), writeitem(), writelabel(), and writelmodel().
Typedef Documentation
typedef struct cathead cathead
Referenced by main().
typedef struct comment comment
Referenced by add_1comment(), hputcom(), main(), newnumericcomment(), and newtextcomment().
typedef struct item item
typedef struct object object
Function Documentation
void addargscomment (int argc, char * argv[], cathead * thecathead)
Definition at line 803 of file cat.c.
References cathead::commentbase, installcomment(), len, and comment::text.
Referenced by main().
void addcomment (char * thetext, cathead * thecathead)
Definition at line 789 of file cat.c.
References cathead::commentbase, installcomment(), and comment::text.
Referenced by main(), and readtabheader().
void addobjectitem (item * newitem, cathead * thecathead)
Definition at line 1020 of file cat.c.
References installitem(), makeitemlist(), newitem(), cathead::nobjectitems, and cathead::objectitembase.
Referenced by dospecialname(), main(), parsename(), and writelmodel().
int allocitemcontents (item * theitem, void ** addr, int level)
Definition at line 413 of file cat.c.
References allocitemcontents(), item::dim, i, item::itype, item::ndim, and size.
Referenced by adddate(), addheadercontents(), allocitemcontents(), allocobjectcontents(), copycontentinfo(), copyheaderinfo(), enterinit(), getop(), ifinit(), install1numericheaderitem(), install1textheaderitem(), main(), newfourierlmodel(), newpolylmodel(), newzernikelmodel(), num1func(), num2func(), readcathead(), writecathead(), and writelmodel().
void allocobjectcontents (object * theobject)
Definition at line 854 of file cat.c.
References item::addr, object::addrlist, allocitemcontents(), object::cathead, and object::nitems.
Referenced by main(), and readlmodel().
void connectcatheadtoobject (object * theobject)
Definition at line 869 of file cat.c.
References item::addr, object::addrlist, object::cathead, and object::nitems.
Referenced by main().
void connectobjecttocathead (object * theobject)
Definition at line 881 of file cat.c.
References item::addr, object::addrlist, object::cathead, and object::nitems.
Referenced by main().
comment* copycomment (comment * sourcecomment)
Definition at line 823 of file cat.c.
References comment::text.
Referenced by copyheaderinfo().
void copycontentinfo (cathead * thecathead, cathead * sourcecathead)
Definition at line 147 of file cat.c.
References item::addr, allocitemcontents(), copyitem(), copyitemcontents(), installitem(), cathead::itemlist, item::next, cathead::nobjectitems, and cathead::objectitembase.
Referenced by main().
void copyheaderinfo (cathead * thecathead, cathead * sourcecathead)
Definition at line 124 of file cat.c.
References item::addr, allocitemcontents(), cathead::commentbase, copycomment(), copyitem(), copyitemcontents(), cathead::headeritembase, installcomment(), installitem(), comment::next, and item::next.
Referenced by main(), and readlmodel().
item* copyitem (item * sourceitem)
Definition at line 396 of file cat.c.
References item::addr, item::name, and item::next.
Referenced by copycontentinfo(), copyheaderinfo(), dospecialname(), getop(), main(), and parsename().
void copyitemcontents (item * dstitem, void * dstaddr, item * srcitem, void * srcaddr, int level)
Definition at line 429 of file cat.c.
References copyitemcontents(), item::dim, exit(), i, item::itype, item::ndim, NUM_TYPE, and TEXT_TYPE.
Referenced by copycontentinfo(), copyheaderinfo(), copyitemcontents(), enterdoit(), ifdoit(), and main().
void copystring (char ** thestring, char * sourcestring)
Definition at line 1163 of file cat.c.
References free().
Referenced by getop(), and main().
void deleteheaderitem (char * name, cathead * thecathead)
Definition at line 991 of file cat.c.
References exit(), freeitem(), cathead::headeritembase, item::name, and item::next.
Referenced by main().
void deleteobjectitem (char * name, cathead * thecathead)
Definition at line 1030 of file cat.c.
References exit(), makeitemlist(), item::name, item::next, cathead::nobjectitems, and cathead::objectitembase.
Referenced by main().
void freecathead (cathead * thecathead)
Definition at line 230 of file cat.c.
References free(), freeitem(), cathead::headeritembase, cathead::itemlist, item::next, and cathead::objectitembase.
void freeitem (item * theitem)
Definition at line 474 of file cat.c.
References item::addr, free(), freeitemcontents(), and item::name.
Referenced by deleteheaderitem(), and freecathead().
void freeitemcontents (item * theitem, void * addr, int level)
Definition at line 460 of file cat.c.
References item::dim, free(), freeitemcontents(), i, and item::ndim.
Referenced by freeitem(), freeitemcontents(), and freeobject().
void freeobject (object * theobject)
Definition at line 927 of file cat.c.
References object::addrlist, object::cathead, free(), freeitemcontents(), and object::nitems.
void* getaddress (object * theobject, int theindex)
Definition at line 1139 of file cat.c.
References object::addrlist, exit(), and object::nitems.
Referenced by main().
void getcatipfiletype (int * filetype)
Definition at line 1185 of file cat.c.
References inputfiletype.
Referenced by main().
void getcatopfiletype (int * filetype)
Definition at line 1198 of file cat.c.
References outputfiletype.
Referenced by main(), and writecathead().
item* getheaderitem (char * name, cathead * thecathead)
Definition at line 942 of file cat.c.
References cathead::headeritembase, item::name, and item::next.
Referenced by getheaderitemaddress(), getop(), main(), readlmodel(), and setheaderitemaddress().
void* getheaderitemaddress (char * name, cathead * thecathead)
Definition at line 962 of file cat.c.
References item::addr, exit(), and getheaderitem().
Referenced by main(), and readlmodel().
item* getobjectitem (char * name, cathead * thecathead)
Definition at line 1059 of file cat.c.
References exit(), item::name, item::next, and cathead::objectitembase.
Referenced by getop(), main(), parsename(), and readlmodel().
int getobjectitemindex (char * name, object * theobject)
Definition at line 1080 of file cat.c.
References object::cathead, exit(), item::name, and object::nitems.
Referenced by main(), and readlmodel().
int gettype (void)
Definition at line 269 of file cat.c.
References catipf, exit(), N_TYPES, type, and WORD_SIZE.
int inheritcontents (object * theobject, object * sourceobject)
Definition at line 1101 of file cat.c.
References object::addrlist, object::cathead, item::dim, exit(), identical(), item::itype, item::ndim, and object::nitems.
Referenced by main().
int install1numericheaderitem (char * name, double value, cathead * thecat)
Definition at line 1248 of file cat.c.
References item::addr, allocitemcontents(), cathead::headeritembase, installitem(), newitem(), and NUM_TYPE.
Referenced by writelmodel().
int install1textheaderitem (char * name, char * value, cathead * thecat)
Definition at line 1259 of file cat.c.
References item::addr, allocitemcontents(), cathead::headeritembase, installitem(), newitem(), and TEXT_TYPE.
Referenced by writelmodel().
void installcomment (comment * thecomment, comment ** base)
Definition at line 773 of file cat.c.
References comment::next.
Referenced by addargscomment(), addcomment(), copyheaderinfo(), and readcathead().
int installitem (item * theitem, item ** base)
Definition at line 740 of file cat.c.
References item::name, and item::next.
Referenced by adddate(), addheadercontents(), addobjectitem(), copycontentinfo(), copyheaderinfo(), install1numericheaderitem(), install1textheaderitem(), main(), parseheaderexpr(), readcathead(), writecathead(), and writelmodel().
void makeitemlist (cathead * thecathead)
Definition at line 252 of file cat.c.
References free(), cathead::itemlist, item::next, cathead::nobjectitems, and cathead::objectitembase.
Referenced by addobjectitem(), deleteobjectitem(), and readcathead().
item* newitem (char * name, int itype, int ndim, ...)
Definition at line 351 of file cat.c.
References item::dim, exit(), item::itype, N_TYPES, item::name, and item::ndim.
Referenced by adddate(), dospecialname(), getop(), install1numericheaderitem(), install1textheaderitem(), main(), newopitem(), readlmodel(), and writelmodel().
item* newitembydimarray (char * name, int itype, int ndim, int * dim)
Definition at line 374 of file cat.c.
References item::dim, exit(), item::itype, N_TYPES, item::name, and item::ndim.
Referenced by main().
object* newobject (cathead * thecathead)
Definition at line 836 of file cat.c.
References object::addrlist, object::cathead, object::nitems, and cathead::nobjectitems.
Referenced by main(), and readlmodel().
cathead* readcathead (void)
Definition at line 36 of file cat.c.
References item::addr, allocitemcontents(), BIG_ENDIAN_CAT_BYTE_ORDER, BINARY_FILE_TYPE, catipf, COMMENT_TYPE, cathead::commentbase, CONTENTS_TYPE, item::dim, error_exit, exit(), gettype(), cathead::headeritembase, i, installcomment(), installitem(), line, LINE1_BINARY, LINE1_TEXT, LINE2, LINE_SIZE, LITTLE_ENDIAN_CAT_BYTE_ORDER, makeitemlist(), item::name, NATIVE_CAT_BYTE_ORDER, item::ndim, cathead::nobjectitems, NUM_TYPE, cathead::objectitembase, readitem(), readnewitem(), setcatipfiletype(), item::swapbytesi, swapbytesoninput(), comment::text, TEXT_FILE_TYPE, and TEXT_TYPE.
int readitem (item * theitem, void * addr, int level)
Definition at line 485 of file cat.c.
References BINARY_FILE_TYPE, catipf, item::dim, error_exit, exit(), free(), i, inputfiletype, item::itype, len, item::ndim, NUM_TYPE, readitem(), swapbytes(), swapbytesi, item::swapbytesi, swapint(), TEXT_FILE_TYPE, TEXT_TYPE, and WORD_SIZE.
Referenced by readcathead(), readitem(), and readobject().
item* readnewitem (int itype)
Definition at line 296 of file cat.c.
References catipf, item::dim, exit(), item::itype, MAX_DIMS, item::name, item::ndim, and WORD_SIZE.
Referenced by readcathead().
int readobject (object * theobject)
Definition at line 894 of file cat.c.
References object::addrlist, object::cathead, object::nitems, and readitem().
Referenced by main(), and readlmodel().
void setaddress (object * theobject, int theindex, void * theaddr)
Definition at line 1151 of file cat.c.
References object::addrlist, exit(), and object::nitems.
Referenced by main().
void setcatipf (FILE * stream)
Definition at line 1172 of file cat.c.
References catipf.
Referenced by main(), and readlmodel().
void setcatipfiletype (int filetype)
Definition at line 1191 of file cat.c.
References inputfiletype.
Referenced by main(), and readcathead().
void setcatopf (FILE * stream)
Definition at line 1178 of file cat.c.
References catopf.
Referenced by main(), and writelmodel().
void setcatopfiletype (int filetype)
Definition at line 1205 of file cat.c.
References outputfiletype.
Referenced by main(), and writecathead().
void setheaderitemaddress (char * name, cathead * thecathead, void * theaddr)
Definition at line 975 of file cat.c.
References item::addr, exit(), and getheaderitem().
Referenced by main().
int size (int itype)
Definition at line 723 of file cat.c.
References exit(), NUM_TYPE, and TEXT_TYPE.
int sscanitem (item * theitem, void * addr, int level, char ** string)
Definition at line 566 of file cat.c.
References item::dim, exit(), free(), i, item::itype, item::ndim, NUM_TYPE, sscanitem(), TEXT_TYPE, and WORD_SIZE.
Referenced by addheadercontents(), and sscanitem().
item* sscannewitem (int itype, char * string)
Definition at line 323 of file cat.c.
References item::dim, exit(), item::itype, MAX_DIMS, item::name, item::ndim, and WORD_SIZE.
Referenced by main(), and writecathead().
void swapbytes (void * addr, int ndoubles)
Definition at line 1212 of file cat.c.
void swapint (void * addr, int nint)
Definition at line 1230 of file cat.c.
References b, i, and nint.
Referenced by readitem().
void writecathead (cathead * thecathead)
Definition at line 165 of file cat.c.
References item::addr, allocitemcontents(), BIG_ENDIAN_CAT_BYTE_ORDER, BINARY_FILE_TYPE, catopf, cathead::commentbase, error_exit, getcatopfiletype(), cathead::headeritembase, installitem(), LINE1_BINARY, LINE1_TEXT, LINE2, NATIVE_CAT_BYTE_ORDER, comment::next, item::next, cathead::nobjectitems, cathead::objectitembase, setcatopfiletype(), sscannewitem(), comment::text, TEXT_FILE_TYPE, TEXT_TYPE, writeitem(), writelabel(), and writename().
Referenced by main(), and writelmodel().
int writeitem (item * theitem, void * addr, int level)
Definition at line 606 of file cat.c.
References BINARY_FILE_TYPE, catopf, item::dim, error_exit, exit(), i, item::itype, LC_NUM_FMT, LC_TEXT_FMT, len, item::ndim, NUM_TYPE, outputfiletype, swapbytes(), swapbyteso, TEXT_FILE_TYPE, TEXT_TYPE, and writeitem().
Referenced by main(), writecathead(), writeitem(), writelmodel(), and writeobject().
int writelabel (item * theitem, int level)
Definition at line 671 of file cat.c.
References catopf, item::dim, i, item::idim, item::itype, label, LC_RIGHT_TEXT_FMT, LC_TEXT_FMT, item::name, item::ndim, TEXT_TYPE, WORD_SIZE, and writelabel().
Referenced by main(), writecathead(), and writelabel().
int writename (item * theitem)
Definition at line 700 of file cat.c.
References catopf, item::dim, free(), i, item::itype, LC_HEADER_NAME_FMT, item::name, item::ndim, type, and WORD_SIZE.
Referenced by writecathead().
void writeobject (object * theobject)
Definition at line 908 of file cat.c.
References object::addrlist, object::cathead, catopf, object::nitems, outputfiletype, TEXT_FILE_TYPE, and writeitem().
Referenced by dispose(), main(), and write_object().
Author
Generated automatically by Doxygen for imcat from the source code.