cat_aj.c
NAME
cat_aj.c -
SYNOPSIS
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include 'cat.h'
#include 'error.h'
Defines
#define N_TYPES 8
#define WORD_SIZE 128
#define LINE_SIZE 100000
#define LINE1_TEXT '# text format catalogue file --- do not edit manually, use 'lc'\n'
#define LINE1_BINARY '# binary catalogue file --- use 'lc' to list contents\n'
#define LINE2 '# header:\n'
Functions
cathead * readcathead (void)
void copyheaderinfo (cathead *thecathead, cathead *sourcecathead)
void copycontentinfo (cathead *thecathead, cathead *sourcecathead)
void writecathead (cathead *thecathead)
void freecathead (cathead *thecathead)
void makeitemlist (cathead *thecathead)
int gettype (void)
item * readnewitem (int itype)
item * sscannewitem (int itype, char *string)
item * newitem (char *name, int itype, int ndim,...)
item * newitembydimarray (char *name, int itype, int ndim, int *dim)
item * copyitem (item *sourceitem)
int allocitemcontents (item *theitem, void **addr, int level)
void copyitemcontents (item *dstitem, void *dstaddr, item *srcitem, void *srcaddr, int level)
void freeitemcontents (item *theitem, void *addr, int level)
void freeitem (item *theitem)
int readitem (item *theitem, void *addr, int level)
int sscanitem (item *theitem, void *addr, int level, char **string)
int writeitem (item *theitem, void *addr, int level)
int writelabel (item *theitem, int level)
int writename (item *theitem)
int size (int itype)
int installitem (item *theitem, item **base)
void installcomment (comment *thecomment, comment **base)
void addcomment (char *thetext, cathead *thecathead)
void addargscomment (int argc, char *argv[], cathead *thecathead)
comment * copycomment (comment *sourcecomment)
object * newobject (cathead *thecathead)
void allocobjectcontents (object *theobject)
void connectcatheadtoobject (object *theobject)
void connectobjecttocathead (object *theobject)
int readobject (object *theobject)
void writeobject (object *theobject)
void freeobject (object *theobject)
item * getheaderitem (char *name, cathead *thecathead)
void * getheaderitemaddress (char *name, cathead *thecathead)
void setheaderitemaddress (char *name, cathead *thecathead, void *theaddr)
void deleteheaderitem (char *name, cathead *thecathead)
void addobjectitem (item *newitem, cathead *thecathead)
void deleteobjectitem (char *name, cathead *thecathead)
item * getobjectitem (char *name, cathead *thecathead)
int getobjectitemindex (char *name, object *theobject)
int inheritcontents (object *theobject, object *sourceobject)
void * getaddress (object *theobject, int theindex)
void setaddress (object *theobject, int theindex, void *theaddr)
void copystring (char **thestring, char *sourcestring)
void setcatipf (FILE *stream)
void setcatopf (FILE *stream)
void getcatipfiletype (int *filetype)
void setcatipfiletype (int filetype)
void getcatopfiletype (int *filetype)
void setcatopfiletype (int filetype)
void swapbytes (void *addr, int ndoubles)
void swapbytesonoutput (void)
void swapbytesoninput (void)
int install1numericheaderitem (char *name, double value, cathead *thecat)
int install1textheaderitem (char *name, char *value, cathead *thecat)
Variables
FILE * catipf
FILE * catopf
int inputfiletype = TEXT_FILE_TYPE
int outputfiletype = TEXT_FILE_TYPE
int swapbytesi = 0
int swapbyteso = 0
char * type [N_TYPES]
Define Documentation
#define LINE1_BINARY '# binary catalogue file --- use 'lc' to list contents\n'
Definition at line 39 of file cat_aj.c.
#define LINE1_TEXT '# text format catalogue file --- do not edit manually, use 'lc'\n'
Definition at line 38 of file cat_aj.c.
#define LINE2 '# header:\n'
Definition at line 40 of file cat_aj.c.
#define LINE_SIZE 100000
Definition at line 36 of file cat_aj.c.
#define N_TYPES 8
Definition at line 30 of file cat_aj.c.
#define WORD_SIZE 128
Definition at line 35 of file cat_aj.c.
Function Documentation
void addargscomment (int argc, char * argv[], cathead * thecathead)
Definition at line 779 of file cat_aj.c.
References cathead::commentbase, installcomment(), len, and comment::text.
Referenced by main().
void addcomment (char * thetext, cathead * thecathead)
Definition at line 765 of file cat_aj.c.
References cathead::commentbase, installcomment(), and comment::text.
Referenced by main(), and readtabheader().
void addobjectitem (item * newitem, cathead * thecathead)
Definition at line 993 of file cat_aj.c.
References installitem(), makeitemlist(), newitem(), cathead::nobjectitems, and cathead::objectitembase.
Referenced by dospecialname(), main(), parsename(), and writelmodel().
int allocitemcontents (item * theitem, void ** addr, int level)
Definition at line 389 of file cat_aj.c.
References allocitemcontents(), item::dim, i, item::itype, item::ndim, and size.
Referenced by adddate(), addheadercontents(), allocitemcontents(), allocobjectcontents(), copycontentinfo(), copyheaderinfo(), enterinit(), getop(), ifinit(), install1numericheaderitem(), install1textheaderitem(), main(), newfourierlmodel(), newpolylmodel(), newzernikelmodel(), num1func(), num2func(), readcathead(), writecathead(), and writelmodel().
void allocobjectcontents (object * theobject)
Definition at line 830 of file cat_aj.c.
References item::addr, object::addrlist, allocitemcontents(), object::cathead, and object::nitems.
Referenced by main(), and readlmodel().
void connectcatheadtoobject (object * theobject)
Definition at line 845 of file cat_aj.c.
References item::addr, object::addrlist, object::cathead, and object::nitems.
Referenced by main().
void connectobjecttocathead (object * theobject)
Definition at line 857 of file cat_aj.c.
References item::addr, object::addrlist, object::cathead, and object::nitems.
Referenced by main().
comment* copycomment (comment * sourcecomment)
Definition at line 799 of file cat_aj.c.
References comment::text.
Referenced by copyheaderinfo().
void copycontentinfo (cathead * thecathead, cathead * sourcecathead)
Definition at line 132 of file cat_aj.c.
References item::addr, allocitemcontents(), copyitem(), copyitemcontents(), installitem(), cathead::itemlist, item::next, cathead::nobjectitems, and cathead::objectitembase.
Referenced by main().
void copyheaderinfo (cathead * thecathead, cathead * sourcecathead)
Definition at line 109 of file cat_aj.c.
References item::addr, allocitemcontents(), cathead::commentbase, copycomment(), copyitem(), copyitemcontents(), cathead::headeritembase, installcomment(), installitem(), comment::next, and item::next.
Referenced by main(), and readlmodel().
item* copyitem (item * sourceitem)
Definition at line 372 of file cat_aj.c.
References item::addr, item::name, and item::next.
Referenced by copycontentinfo(), copyheaderinfo(), dospecialname(), getop(), main(), and parsename().
void copyitemcontents (item * dstitem, void * dstaddr, item * srcitem, void * srcaddr, int level)
Definition at line 405 of file cat_aj.c.
References copyitemcontents(), item::dim, exit(), i, item::itype, item::ndim, NUM_TYPE, and TEXT_TYPE.
Referenced by copycontentinfo(), copyheaderinfo(), copyitemcontents(), enterdoit(), ifdoit(), and main().
void copystring (char ** thestring, char * sourcestring)
Definition at line 1135 of file cat_aj.c.
References free().
Referenced by getop(), and main().
void deleteheaderitem (char * name, cathead * thecathead)
Definition at line 964 of file cat_aj.c.
References exit(), freeitem(), cathead::headeritembase, item::name, and item::next.
Referenced by main().
void deleteobjectitem (char * name, cathead * thecathead)
Definition at line 1002 of file cat_aj.c.
References exit(), makeitemlist(), item::name, item::next, cathead::nobjectitems, and cathead::objectitembase.
Referenced by main().
void freecathead (cathead * thecathead)
Definition at line 204 of file cat_aj.c.
References free(), freeitem(), cathead::headeritembase, cathead::itemlist, item::next, and cathead::objectitembase.
void freeitem (item * theitem)
Definition at line 450 of file cat_aj.c.
References item::addr, free(), freeitemcontents(), and item::name.
Referenced by deleteheaderitem(), and freecathead().
void freeitemcontents (item * theitem, void * addr, int level)
Definition at line 436 of file cat_aj.c.
References item::dim, free(), freeitemcontents(), i, and item::ndim.
Referenced by freeitem(), freeitemcontents(), and freeobject().
void freeobject (object * theobject)
Definition at line 904 of file cat_aj.c.
References object::addrlist, object::cathead, free(), freeitemcontents(), and object::nitems.
void* getaddress (object * theobject, int theindex)
Definition at line 1111 of file cat_aj.c.
References object::addrlist, exit(), and object::nitems.
Referenced by main().
void getcatipfiletype (int * filetype)
Definition at line 1157 of file cat_aj.c.
References inputfiletype.
Referenced by main().
void getcatopfiletype (int * filetype)
Definition at line 1170 of file cat_aj.c.
References outputfiletype.
Referenced by main(), and writecathead().
item* getheaderitem (char * name, cathead * thecathead)
Definition at line 919 of file cat_aj.c.
References cathead::headeritembase, item::name, and item::next.
Referenced by getheaderitemaddress(), getop(), main(), readlmodel(), and setheaderitemaddress().
void* getheaderitemaddress (char * name, cathead * thecathead)
Definition at line 942 of file cat_aj.c.
References item::addr, exit(), and getheaderitem().
Referenced by main(), and readlmodel().
item* getobjectitem (char * name, cathead * thecathead)
Definition at line 1031 of file cat_aj.c.
References exit(), item::name, item::next, and cathead::objectitembase.
Referenced by getop(), main(), parsename(), and readlmodel().
int getobjectitemindex (char * name, object * theobject)
Definition at line 1052 of file cat_aj.c.
References object::cathead, exit(), item::name, and object::nitems.
Referenced by main(), and readlmodel().
int gettype (void)
Definition at line 243 of file cat_aj.c.
References catipf, exit(), N_TYPES, type, and WORD_SIZE.
int inheritcontents (object * theobject, object * sourceobject)
Definition at line 1073 of file cat_aj.c.
References object::addrlist, object::cathead, item::dim, exit(), identical(), item::itype, item::ndim, and object::nitems.
Referenced by main().
int install1numericheaderitem (char * name, double value, cathead * thecat)
Definition at line 1214 of file cat_aj.c.
References item::addr, allocitemcontents(), cathead::headeritembase, installitem(), newitem(), and NUM_TYPE.
Referenced by writelmodel().
int install1textheaderitem (char * name, char * value, cathead * thecat)
Definition at line 1225 of file cat_aj.c.
References item::addr, allocitemcontents(), cathead::headeritembase, installitem(), newitem(), and TEXT_TYPE.
Referenced by writelmodel().
void installcomment (comment * thecomment, comment ** base)
Definition at line 749 of file cat_aj.c.
References comment::next.
Referenced by addargscomment(), addcomment(), copyheaderinfo(), and readcathead().
int installitem (item * theitem, item ** base)
Definition at line 717 of file cat_aj.c.
References item::name, and item::next.
Referenced by adddate(), addheadercontents(), addobjectitem(), copycontentinfo(), copyheaderinfo(), install1numericheaderitem(), install1textheaderitem(), main(), parseheaderexpr(), readcathead(), writecathead(), and writelmodel().
void makeitemlist (cathead * thecathead)
Definition at line 226 of file cat_aj.c.
References free(), cathead::itemlist, item::next, cathead::nobjectitems, and cathead::objectitembase.
Referenced by addobjectitem(), deleteobjectitem(), and readcathead().
item* newitem (char * name, int itype, int ndim, ...)
Definition at line 327 of file cat_aj.c.
References item::dim, exit(), item::itype, N_TYPES, item::name, and item::ndim.
Referenced by adddate(), dospecialname(), getop(), install1numericheaderitem(), install1textheaderitem(), main(), newopitem(), readlmodel(), and writelmodel().
item* newitembydimarray (char * name, int itype, int ndim, int * dim)
Definition at line 350 of file cat_aj.c.
References item::dim, exit(), item::itype, N_TYPES, item::name, and item::ndim.
Referenced by main().
object* newobject (cathead * thecathead)
Definition at line 812 of file cat_aj.c.
References object::addrlist, object::cathead, object::nitems, and cathead::nobjectitems.
Referenced by main(), and readlmodel().
cathead* readcathead (void)
Definition at line 43 of file cat_aj.c.
References item::addr, allocitemcontents(), BIG_ENDIAN_CAT_BYTE_ORDER, BINARY_FILE_TYPE, catipf, COMMENT_TYPE, cathead::commentbase, CONTENTS_TYPE, item::dim, error_exit, exit(), gettype(), cathead::headeritembase, i, installcomment(), installitem(), line, LINE1_BINARY, LINE1_TEXT, LINE2, LINE_SIZE, LITTLE_ENDIAN_CAT_BYTE_ORDER, makeitemlist(), item::name, NATIVE_CAT_BYTE_ORDER, item::ndim, cathead::nobjectitems, NUM_TYPE, cathead::objectitembase, readitem(), readnewitem(), setcatipfiletype(), item::swapbytesi, swapbytesoninput(), comment::text, TEXT_FILE_TYPE, and TEXT_TYPE.
int readitem (item * theitem, void * addr, int level)
Definition at line 461 of file cat_aj.c.
References BINARY_FILE_TYPE, catipf, item::dim, error_exit, exit(), free(), i, inputfiletype, item::itype, len, item::ndim, NUM_TYPE, readitem(), swapbytes(), swapbytesi, swapint(), TEXT_FILE_TYPE, TEXT_TYPE, and WORD_SIZE.
Referenced by readcathead(), readitem(), and readobject().
item* readnewitem (int itype)
Definition at line 271 of file cat_aj.c.
References catipf, item::dim, exit(), item::itype, MAX_DIMS, item::name, item::ndim, and WORD_SIZE.
Referenced by readcathead().
int readobject (object * theobject)
Definition at line 870 of file cat_aj.c.
References object::addrlist, object::cathead, object::nitems, and readitem().
Referenced by main(), and readlmodel().
void setaddress (object * theobject, int theindex, void * theaddr)
Definition at line 1123 of file cat_aj.c.
References object::addrlist, exit(), and object::nitems.
Referenced by main().
void setcatipf (FILE * stream)
Definition at line 1144 of file cat_aj.c.
References catipf.
Referenced by main(), and readlmodel().
void setcatipfiletype (int filetype)
Definition at line 1163 of file cat_aj.c.
References inputfiletype.
Referenced by main(), and readcathead().
void setcatopf (FILE * stream)
Definition at line 1150 of file cat_aj.c.
References catopf.
Referenced by main(), and writelmodel().
void setcatopfiletype (int filetype)
Definition at line 1177 of file cat_aj.c.
References outputfiletype.
Referenced by main(), and writecathead().
void setheaderitemaddress (char * name, cathead * thecathead, void * theaddr)
Definition at line 956 of file cat_aj.c.
References item::addr, exit(), and getheaderitem().
Referenced by main().
int size (int itype)
Definition at line 700 of file cat_aj.c.
References exit(), NUM_TYPE, and TEXT_TYPE.
int sscanitem (item * theitem, void * addr, int level, char ** string)
Definition at line 540 of file cat_aj.c.
References item::dim, exit(), free(), i, item::itype, item::ndim, NUM_TYPE, sscanitem(), TEXT_TYPE, and WORD_SIZE.
Referenced by addheadercontents(), and sscanitem().
item* sscannewitem (int itype, char * string)
Definition at line 299 of file cat_aj.c.
References item::dim, exit(), item::itype, MAX_DIMS, item::name, item::ndim, and WORD_SIZE.
Referenced by main(), and writecathead().
void swapbytes (void * addr, int ndoubles)
Definition at line 1184 of file cat_aj.c.
References b, and i.
void swapbytesoninput (void)
Definition at line 1208 of file cat_aj.c.
References swapbytesi.
Referenced by readcathead().
void swapbytesonoutput (void)
Definition at line 1202 of file cat_aj.c.
References swapbyteso.
void writecathead (cathead * thecathead)
Definition at line 150 of file cat_aj.c.
References item::addr, allocitemcontents(), BIG_ENDIAN_CAT_BYTE_ORDER, BINARY_FILE_TYPE, catopf, cathead::commentbase, error_exit, getcatopfiletype(), cathead::headeritembase, installitem(), LINE1_BINARY, LINE1_TEXT, LINE2, NATIVE_CAT_BYTE_ORDER, comment::next, item::next, cathead::nobjectitems, cathead::objectitembase, setcatopfiletype(), sscannewitem(), comment::text, TEXT_FILE_TYPE, TEXT_TYPE, writeitem(), writelabel(), and writename().
Referenced by main(), and writelmodel().
int writeitem (item * theitem, void * addr, int level)
Definition at line 580 of file cat_aj.c.
References BINARY_FILE_TYPE, catopf, item::dim, error_exit, exit(), i, item::itype, LC_NUM_FMT, LC_TEXT_FMT, len, item::ndim, NUM_TYPE, outputfiletype, swapbytes(), swapbyteso, TEXT_FILE_TYPE, TEXT_TYPE, and writeitem().
Referenced by main(), writecathead(), writeitem(), writelmodel(), and writeobject().
int writelabel (item * theitem, int level)
Definition at line 646 of file cat_aj.c.
References catopf, item::dim, i, item::idim, item::itype, label, LC_RIGHT_TEXT_FMT, LC_TEXT_FMT, item::name, item::ndim, TEXT_TYPE, WORD_SIZE, and writelabel().
Referenced by main(), writecathead(), and writelabel().
int writename (item * theitem)
Definition at line 676 of file cat_aj.c.
References catopf, item::dim, free(), i, item::itype, LC_HEADER_NAME_FMT, item::name, item::ndim, type, and WORD_SIZE.
Referenced by writecathead().
void writeobject (object * theobject)
Definition at line 884 of file cat_aj.c.
References object::addrlist, object::cathead, catopf, object::nitems, outputfiletype, TEXT_FILE_TYPE, and writeitem().
Referenced by dispose(), main(), and write_object().
Variable Documentation
FILE* catipf [static]
Definition at line 20 of file cat_aj.c.
Referenced by gettype(), readcathead(), readitem(), readnewitem(), and setcatipf().
FILE* catopf [static]
Definition at line 21 of file cat_aj.c.
Referenced by setcatopf(), writecathead(), writeitem(), writelabel(), writename(), and writeobject().
int inputfiletype = TEXT_FILE_TYPE [static]
Definition at line 23 of file cat_aj.c.
Referenced by getcatipfiletype(), readitem(), and setcatipfiletype().
int outputfiletype = TEXT_FILE_TYPE [static]
Definition at line 24 of file cat_aj.c.
Referenced by getcatopfiletype(), setcatopfiletype(), writeitem(), and writeobject().
int swapbytesi = 0 [static]
Definition at line 26 of file cat_aj.c.
Referenced by readitem(), and swapbytesoninput().
int swapbyteso = 0 [static]
Definition at line 27 of file cat_aj.c.
Referenced by swapbytesonoutput(), and writeitem().
char* type[N_TYPES] [static]
Initial value:.nf
 {'number', 'text', 'comment:', 'contents:',
'op2', 'op1', 'genericop', 'rpn_function'}
Definition at line 31 of file cat_aj.c.
Referenced by gettype(), and writename().
Author
Generated automatically by Doxygen for imcat from the source code.