catstats.c
NAME
catstats.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../utils/error.h'
#include '../utils/stats_stuff.h'
#include '../catlib/cat.h'
Data Structures
struct statobj
Defines
#define usage '\n\n\NAME\n\	catstats - calculate statistics for catalogue object values\n\\n\SYNOPSIS\n\	catstats [options....]\n\		-s		# only output count, min, max, mean, sigma1\n\		-v statistic	# only output 'statistic'\n\\n\DESCRIPTION\n\	'catstats' reads a catalogue from stdin and creates a new\n\	catalogue whose first object item is a text entry 'statistic'\n\	which takes values 'count', 'min', 'max', 'mean'....\n\	and whose subsequent object items have the same names as the\n\	numerical items in the input catalogue and which\n\	contain the appropriate statistic.\n\\n\	Catstats will always output the basic statistics:\n\		count		# number of objects\n\		min		# minimum value\n\		max		# maximum value\n\		mean		# <f> = sum f / count\n\		sigma1		# sqrt(<f^2> - <f>^2)\t\n\	and by default will also calculate\n\		mode		# 'robust' mode estimator\n\		median		# median\n\		lquart		# upper quartile\n\		uquart		# lower quartile\n\		sigma2		# 'robust' sigma estimator \n\	provided there are are least 8 objects in the catalogue.\n\\n\	The statistics 'mode' and 'sigma2' are designed to be\n\	insensitive to outliers.\n\\n\	The 'mode' is estimated by first making a crude\n\	estimate of sigma as (uquart - lquart) / 1.34; smoothing\n\	the histogram of values with a gaussian of width sigma\n\	and returning the location of the peak.\n\\n\	'sigma2' is estimated from the width of the region around\n\	the mode containing 25 percent of the values (and assuming)\n\	a gaussian distribution. Thus, sigma2 is effectively\n\	measured from the curvature of the distribution around the\n\	mode and will, for example, overestimate the real sigma\n\	for a very boxy distribution.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
#define SIMPLE_STATS_MODE 0
#define ALL_STATS_MODE 1
#define N_STATS 9
#define MIN_INDEX 0
#define MAX_INDEX 1
#define MEAN_INDEX 2
#define SIGMA1_INDEX 3
#define MODE_INDEX 4
#define MEDIAN_INDEX 5
#define LQUART_INDEX 6
#define UQUART_INDEX 7
#define SIGMA2_INDEX 8
#define MAX_NUMBERS 10000
#define MIN_COUNT 8
Typedefs
typedef statobj statobj
Functions
void getnumericaddresses (object *obj)
void getitemaddresses (item *theitem, void *addr, int level)
main (int argc, char *argv[])
Variables
char statname [N_STATS][64]
double * fin [MAX_NUMBERS]
double * fstat [N_STATS][MAX_NUMBERS]
int g_istat
int findex
Define Documentation
#define ALL_STATS_MODE 1
Definition at line 66 of file catstats.c.
Referenced by main().
#define LQUART_INDEX 6
Definition at line 74 of file catstats.c.
Referenced by main().
#define MAX_INDEX 1
Definition at line 69 of file catstats.c.
Referenced by main().
#define MAX_NUMBERS 10000
Definition at line 100 of file catstats.c.
Referenced by main().
#define MEAN_INDEX 2
Definition at line 70 of file catstats.c.
Referenced by main().
#define MEDIAN_INDEX 5
Definition at line 73 of file catstats.c.
Referenced by main().
#define MIN_COUNT 8
Definition at line 102 of file catstats.c.
Referenced by main().
#define MIN_INDEX 0
Definition at line 68 of file catstats.c.
Referenced by main().
#define MODE_INDEX 4
Definition at line 72 of file catstats.c.
Referenced by main().
#define N_STATS 9
Definition at line 67 of file catstats.c.
Referenced by main().
#define SIGMA1_INDEX 3
Definition at line 71 of file catstats.c.
Referenced by main().
#define SIGMA2_INDEX 8
Definition at line 76 of file catstats.c.
Referenced by main().
#define SIMPLE_STATS_MODE 0
Definition at line 65 of file catstats.c.
Referenced by main().
#define UQUART_INDEX 7
Definition at line 75 of file catstats.c.
Referenced by main().
#define usage '\n\n\NAME\n\	catstats - calculate statistics for catalogue object values\n\\n\SYNOPSIS\n\	catstats [options....]\n\		-s		# only output count, min, max, mean, sigma1\n\		-v statistic	# only output 'statistic'\n\\n\DESCRIPTION\n\	'catstats' reads a catalogue from stdin and creates a new\n\	catalogue whose first object item is a text entry 'statistic'\n\	which takes values 'count', 'min', 'max', 'mean'....\n\	and whose subsequent object items have the same names as the\n\	numerical items in the input catalogue and which\n\	contain the appropriate statistic.\n\\n\	Catstats will always output the basic statistics:\n\		count		# number of objects\n\		min		# minimum value\n\		max		# maximum value\n\		mean		# <f> = sum f / count\n\		sigma1		# sqrt(<f^2> - <f>^2)\t\n\	and by default will also calculate\n\		mode		# 'robust' mode estimator\n\		median		# median\n\		lquart		# upper quartile\n\		uquart		# lower quartile\n\		sigma2		# 'robust' sigma estimator \n\	provided there are are least 8 objects in the catalogue.\n\\n\	The statistics 'mode' and 'sigma2' are designed to be\n\	insensitive to outliers.\n\\n\	The 'mode' is estimated by first making a crude\n\	estimate of sigma as (uquart - lquart) / 1.34; smoothing\n\	the histogram of values with a gaussian of width sigma\n\	and returning the location of the peak.\n\\n\	'sigma2' is estimated from the width of the region around\n\	the mode containing 25 percent of the values (and assuming)\n\	a gaussian distribution. Thus, sigma2 is effectively\n\	measured from the curvature of the distribution around the\n\	mode and will, for example, overestimate the real sigma\n\	for a very boxy distribution.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file catstats.c.
Referenced by main().
Typedef Documentation
typedef struct statobj statobj
Function Documentation
void getitemaddresses (item * theitem, void * addr, int level)
Definition at line 286 of file catstats.c.
References item::dim, fin, findex, fstat, g_istat, i, and item::ndim.
Referenced by getnumericaddresses().
void getnumericaddresses (object * obj)
Definition at line 272 of file catstats.c.
References item::addr, object::cathead, findex, getitemaddresses(), item::itype, item::next, and NUM_TYPE.
Referenced by main().
main (int argc, char * argv[])
Definition at line 108 of file catstats.c.
References addargscomment(), addobjectitem(), item::addr, ALL_STATS_MODE, allocitemcontents(), allocobjectcontents(), connectobjecttocathead(), copyheaderinfo(), copyitem(), error_exit, exit(), statobj::f, f, fin, findex, findmode(), fmedian(), fstat, g_istat, getnumericaddresses(), i, item::itype, liststats(), LQUART_INDEX, MAX_INDEX, MEAN_INDEX, MEDIAN_INDEX, MIN_COUNT, MIN_INDEX, MODE_INDEX, N_STATS, newitem(), newobject(), statobj::next, item::next, NUM_TYPE, cathead::objectitembase, opmode, readcathead(), readobject(), SIGMA1_INDEX, SIGMA2_INDEX, SIMPLE_STATS_MODE, statname, TEXT_TYPE, UQUART_INDEX, usage, writecathead(), and writeobject().
Variable Documentation
double* fin[MAX_NUMBERS] [static]
Definition at line 104 of file catstats.c.
Referenced by getitemaddresses(), and main().
int findex [static]
Definition at line 106 of file catstats.c.
Referenced by getitemaddresses(), getnumericaddresses(), and main().
double* fstat[N_STATS][MAX_NUMBERS] [static]
Definition at line 105 of file catstats.c.
Referenced by getitemaddresses(), main(), and skiplines().
int g_istat [static]
Definition at line 106 of file catstats.c.
Referenced by getitemaddresses(), and main().
char statname[N_STATS][64]
Initial value:.nf
 {
  'min',
  'max',
  'mean',
  'sigma1',
  'mode',
  'median',
  'lquart',
  'uquart',
  'sigma2'
}
Definition at line 79 of file catstats.c.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.