.TH "error.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBerror_exit\fP(\fBa\fP)   fprintf(stderr, (\fBa\fP)); exit(-1)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define error_exit(\fBa\fP)   fprintf(stderr, (\fBa\fP)); exit(-1)"
.PP
Definition at line 8 of file cattools/lc/error.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
