operators.c
NAME
operators.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../catlib/cat.h'
#include 'stack.h'
#include 'operators.h'
#include 'op_math.h'
#include 'op_logic.h'
#include 'op_deref.h'
#include 'op_vector.h'
#include 'op_dot.h'
#include 'op_rand.h'
#include 'op_misc.h'
#include 'op_lintrans.h'
#include 'error.h'
#include 'op_strings.h'
Defines
#define N_NUM1_OPS 17
#define N_NUM2_OPS 18
#define N_GEN_OPS 18
Functions
item * newopitem (char *thename)
void num1func (item *operand, item *operator)
void num2func (item *operand1, item *operand2, item *operator)
void genfunc (item *operator)
Variables
char * num1funcname [N_NUM1_OPS]
double(* num1funcarray [N_NUM1_OPS])(double)=
char * num2funcname [N_NUM2_OPS]
double(* num2funcarray [N_NUM2_OPS])(double, double)=
char * genfuncname [N_GEN_OPS]
void(* genfuncinit [N_GEN_OPS])(item *)=
void(* genfuncdoit [N_GEN_OPS])(item *)=
Define Documentation
#define N_GEN_OPS 18
Definition at line 46 of file cattools/lc/operators.c.
Referenced by newopitem().
#define N_NUM1_OPS 17
Definition at line 23 of file cattools/lc/operators.c.
Referenced by newop(), and newopitem().
#define N_NUM2_OPS 18
Definition at line 34 of file cattools/lc/operators.c.
Referenced by newop(), and newopitem().
Function Documentation
void genfunc (item * operator)
Definition at line 146 of file cattools/lc/operators.c.
References genfuncdoit, and genfuncinit.
Referenced by evalrpnfunction().
item* newopitem (char * thename)
Definition at line 57 of file cattools/lc/operators.c.
References item::addr, item::dim, exit(), GEN_OP_TYPE, genfuncname, N_GEN_OPS, N_NUM1_OPS, N_NUM2_OPS, newitem(), NUM1_OP_TYPE, num1funcarray, num1funcname, NUM2_OP_TYPE, num2funcarray, and num2funcname.
Referenced by getop().
void num1func (item * operand, item * operator)
Definition at line 100 of file cattools/lc/operators.c.
void num2func (item * operand1, item * operand2, item * operator)
Definition at line 120 of file cattools/lc/operators.c.
Variable Documentation
void(* genfuncdoit[N_GEN_OPS])(item *) =
Definition at line 53 of file cattools/lc/operators.c.
Referenced by genfunc().
void(* genfuncinit[N_GEN_OPS])(item *) =
Definition at line 50 of file cattools/lc/operators.c.
Referenced by genfunc().
char* genfuncname[N_GEN_OPS] [static]
Initial value:.nf
 {
'deref', 'vector', 'dot', 'rand', 'grand', 'if', '?', 'enter', 'lintrans', 'vsub', 'vadd', 'vscale', 'vshift',
  'inverse', 'msub', 'madd', 'mscale', 'eq'}
Definition at line 47 of file cattools/lc/operators.c.
Referenced by newopitem().
double(* num1funcarray[N_NUM1_OPS])(double) =
Definition at line 28 of file cattools/lc/operators.c.
Referenced by main(), newop(), newopitem(), and num1func().
char* num1funcname[N_NUM1_OPS] [static]
Initial value:.nf
 {
'acos', 'asin', 'atan', 'ceil', 'cos', 'cosh', 'exp', 'fabs', 'floor',
'log', 'log10', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', '!'
}
Definition at line 24 of file cattools/lc/operators.c.
Referenced by newopitem().
double(* num2funcarray[N_NUM2_OPS])(double, double) =
Definition at line 39 of file cattools/lc/operators.c.
Referenced by main(), newop(), newopitem(), and num2func().
char* num2funcname[N_NUM2_OPS] [static]
Initial value:.nf
 {
'mult', '*', '+', '/', '-', 'atan2', 'pow', 'fmod',
'>', '>=', '<', '<=', '==', '!=', 'and', 'or', 'max', 'min'
}
Definition at line 35 of file cattools/lc/operators.c.
Referenced by newopitem().
Author
Generated automatically by Doxygen for imcat from the source code.