stack.c
NAME
stack.c -
SYNOPSIS
#include <stdio.h>
#include '../../catlib/cat.h'
#include 'stack.h'
#include 'error.h'
Defines
#define STACK_DEPTH 100
Functions
void push (item *theitem)
item * pop (void)
Variables
item * itemstack [STACK_DEPTH]
int stackpos = 0
Define Documentation
#define STACK_DEPTH 100
Definition at line 11 of file cattools/lc/stack.c.
Referenced by main(), and push().
Function Documentation
item* pop (void)
Definition at line 32 of file cattools/lc/stack.c.
Referenced by derefdoit(), derefinit(), dotdoit(), dotinit(), enter(), enterdoit(), enterinit(), evalrpnfunction(), If(), ifdoit(), ifinit(), inversedoit(), inverseinit(), lintransdoit(), lintransinit(), madddoit(), maddinit(), main(), mscaledoit(), mscaleinit(), msubdoit(), msubinit(), streqdoit(), streqinit(), vadddoit(), vaddinit(), vectordoit(), vectorinit(), vscaledoit(), vscaleinit(), vshiftdoit(), vshiftinit(), vsubdoit(), and vsubinit().
void push (item * theitem)
Definition at line 16 of file cattools/lc/stack.c.
Variable Documentation
item* itemstack[STACK_DEPTH]
Definition at line 13 of file cattools/lc/stack.c.
Referenced by pop(), and push().
int stackpos = 0
Definition at line 14 of file cattools/lc/stack.c.
Referenced by constfunc(), imvalfunc(), num0func(), num1func(), num2func(), pop(), push(), and resetstack().
Author
Generated automatically by Doxygen for imcat from the source code.