test.c
NAME
test.c -
SYNOPSIS
#include <stdio.h>
#include '../../catlib/cat.h'
Functions
main (int argc, char *argv[])
Function Documentation
main (int argc, char * argv[])
Definition at line 5 of file cattools/lc/test.c.
References addargscomment(), addcomment(), addobjectitem(), allocobjectcontents(), copystring(), d, deleteheaderitem(), deleteobjectitem(), f, g(), getaddress(), getheaderitemaddress(), getobjectitemindex(), inheritcontents(), newitem(), newobject(), NUM_TYPE, readcathead(), readobject(), setaddress(), setheaderitemaddress(), TEXT_TYPE, writecathead(), writeobject(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.