operators.h
NAME
operators.h -
SYNOPSIS
Functions
item * newopitem (char *name)
void num1func (item *operand, item *operator)
void num2func (item *operand1, item *operand2, item *operator)
void genfunc (item *operator)
Function Documentation
void genfunc (item * operator)
Definition at line 146 of file cattools/lc/operators.c.
References genfuncdoit, and genfuncinit.
Referenced by evalrpnfunction().
item* newopitem (char * name)
Definition at line 57 of file cattools/lc/operators.c.
References item::addr, item::dim, exit(), GEN_OP_TYPE, genfuncname, N_GEN_OPS, N_NUM1_OPS, N_NUM2_OPS, newitem(), NUM1_OP_TYPE, num1funcarray, num1funcname, NUM2_OP_TYPE, num2funcarray, and num2funcname.
Referenced by getop().
void num1func (item * operand, item * operator)
Definition at line 100 of file cattools/lc/operators.c.
References item::addr, allocitemcontents(), item::dim, error_exit, item::itype, item::ndim, item::next, num1funcarray, NUM_TYPE, and output().
void num2func (item * operand1, item * operand2, item * operator)
Definition at line 120 of file cattools/lc/operators.c.
References item::addr, allocitemcontents(), item::dim, error_exit, item::itype, item::ndim, item::next, num2funcarray, NUM_TYPE, and output().
Author
Generated automatically by Doxygen for imcat from the source code.