.TH "stack.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stack.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpush\fP (\fBitem\fP *theitem)"
.br
.ti -1c
.RI "\fBitem\fP * \fBpop\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBitem\fP* pop (void)"
.PP
Definition at line 32 of file cattools/lc/stack.c.
.SS "void push (\fBitem\fP * theitem)"
.PP
Definition at line 16 of file cattools/lc/stack.c.
.PP
References error_exit, itemstack, STACK_DEPTH, and stackpos.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
