op_math.c
NAME
op_math.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
Functions
double times (double x, double y)
double plus (double x, double y)
double divide (double x, double y)
double minus (double x, double y)
double max (double x, double y)
double min (double x, double y)
Function Documentation
double divide (double x, double y)
Definition at line 21 of file cattools/lc/op_math.c.
Referenced by num2funcarray().
double max (double x, double y)
Definition at line 36 of file cattools/lc/op_math.c.
References x, and y.
double min (double x, double y)
Definition at line 41 of file cattools/lc/op_math.c.
References x, and y.
double minus (double x, double y)
Definition at line 31 of file cattools/lc/op_math.c.
Referenced by num2funcarray().
double plus (double x, double y)
Definition at line 15 of file cattools/lc/op_math.c.
Referenced by num2funcarray().
double times (double x, double y)
Definition at line 9 of file cattools/lc/op_math.c.
Referenced by num2funcarray().
Author
Generated automatically by Doxygen for imcat from the source code.