.TH "op_math.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
op_math.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBtimes\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBplus\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBdivide\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBminus\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBmax\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBmin\fP (double x, double y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double divide (double x, double y)"
.PP
Definition at line 21 of file cattools/lc/op_math.c.
.PP
Referenced by num2funcarray().
.SS "double max (double x, double y)"
.PP
Definition at line 36 of file cattools/lc/op_math.c.
.PP
References x, and y.
.SS "double min (double x, double y)"
.PP
Definition at line 41 of file cattools/lc/op_math.c.
.PP
References x, and y.
.SS "double minus (double x, double y)"
.PP
Definition at line 31 of file cattools/lc/op_math.c.
.PP
Referenced by num2funcarray().
.SS "double plus (double x, double y)"
.PP
Definition at line 15 of file cattools/lc/op_math.c.
.PP
Referenced by num2funcarray().
.SS "double times (double x, double y)"
.PP
Definition at line 9 of file cattools/lc/op_math.c.
.PP
Referenced by num2funcarray().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
