cdl.c
NAME
cdl.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/stat.h>
#include <math.h>
#include 'cdl.h'
Defines
#define CDL_LIBRARY_SOURCE
#define CDL_NEED_COLORMAPS
Functions
void cdl_applyZscale ()
void cdl_flip ()
CDLPtr cdl_open (char *imtdev)
int cdl_displayPix (CDLPtr cdl, uchar *pix, int nx, int ny, int bitpix, int frame, int fbconfig, int zscale)
char cdl_readCursor (CDLPtr cdl, int sample, float *x, float *y, char *key)
int cdl_setCursor (CDLPtr cdl, int x, int y, int wcs)
int cdl_setWCS (CDLPtr cdl, char *imname, char *imtitle, float a, float b, float c, float d, float tx, float ty, float z1, float z2, int zt)
int cdl_getWCS (CDLPtr cdl, char *name, char *title, float *a, float *b, float *c, float *d, float *tx, float *ty, float *z1, float *z2, int *zt)
int cdl_clearFrame (CDLPtr cdl)
void cdl_selectFB (CDLPtr cdl, int nx, int ny, int *fb, int *w, int *h, int *nf, int reset)
void cdl_close (CDLPtr cdl)
int cdl_readImage (CDLPtr cdl, uchar **pix, int *nx, int *ny)
int cdl_readFrameBuffer (CDLPtr cdl, uchar **pix, int *nx, int *ny)
void cdl_computeZscale (CDLPtr cdl, uchar *pix, int nx, int ny, int bitpix, float *z1, float *z2)
void cdl_zscaleImage (CDLPtr cdl, uchar **pix, int nx, int ny, int bitpix, float z1, float z2)
int cdl_printPix (CDLPtr cdl, char *cmd, uchar *pix, int nx, int ny, int annotate)
int cdl_printPixToFile (CDLPtr cdl, char *fname, uchar *pix, int nx, int ny, int annotate)
int cdl_readSubRaster (CDLPtr cdl, int lx, int ly, int nx, int ny, uchar **pix)
int cdl_writeSubRaster (CDLPtr cdl, int lx, int ly, int nx, int ny, uchar *pix)
void cdl_setFBConfig (CDLPtr cdl, int configno)
void cdl_getFBConfig (CDLPtr cdl, int *configno, int *w, int *h, int *nframes)
void cdl_lookupFBSize (CDLPtr cdl, int configno, int *w, int *h, int *nf)
void cdl_setFrame (CDLPtr cdl, int frame)
void cdl_setZTrans (CDLPtr cdl, int ztrans)
void cdl_setZScale (CDLPtr cdl, float z1, float z2)
void cdl_setSample (CDLPtr cdl, int nsample)
void cdl_setSampleLines (CDLPtr cdl, int nlines)
void cdl_setContrast (CDLPtr cdl, float contrast)
void cdl_setName (CDLPtr cdl, char *imname)
void cdl_setTitle (CDLPtr cdl, char *imtitle)
void cdl_getFrame (CDLPtr cdl, int *frame)
void cdl_getZTrans (CDLPtr cdl, int *ztrans)
void cdl_getZScale (CDLPtr cdl, float *z1, float *z2)
void cdl_getSample (CDLPtr cdl, int *nsample)
void cdl_getSampleLines (CDLPtr cdl, int *nlines)
void cdl_getContrast (CDLPtr cdl, float *contrast)
void cdl_getName (CDLPtr cdl, char *imname)
void cdl_getTitle (CDLPtr cdl, char *imtitle)
void cdl_setDebug (int state)
void cdl_applyZscale (CDLPtr cdl, uchar **pix, int nx, int ny, int bitpix)
void cdl_flip (uchar *buffer, int nx, int ny)
Variables
MarkerPtr DLHead [MAX_FRAMES]
MarkerPtr DLTail [MAX_FRAMES]
int cdl_debug = 0
Define Documentation
#define CDL_LIBRARY_SOURCE
Definition at line 6 of file cdl.c.
#define CDL_NEED_COLORMAPS
Definition at line 7 of file cdl.c.
Function Documentation
void cdl_applyZscale (CDLPtr cdl, uchar ** pix, int nx, int ny, int bitpix) [static]
Definition at line 1503 of file cdl.c.
References bitpix, cdl_debug, cdl_getZScale(), cdl_getZTrans(), CDL_LINEAR, CDL_LOG, CDL_UNITARY, CDLPtr, free(), i, malloc(), max, min, n, nx, ny, pix, scale, uchar, z1, z2, and zt.
void cdl_applyZscale () [static]
Referenced by cdl_zscaleImage().
int cdl_clearFrame (CDLPtr cdl)
Definition at line 489 of file cdl.c.
References cdl_debug, CDLPtr, and imd_clearFrame().
void cdl_close (CDLPtr cdl)
Definition at line 586 of file cdl.c.
References cdl_debug, CDLPtr, free(), and imd_close().
void cdl_computeZscale (CDLPtr cdl, uchar * pix, int nx, int ny, int bitpix, float * z1, float * z2)
Definition at line 692 of file cdl.c.
References bitpix, cdl_debug, cdl_zscale(), CDLPtr, nx, ny, pix, uchar, z1, and z2.
int cdl_displayPix (CDLPtr cdl, uchar	* pix, int nx, int ny, int bitpix, int frame, int fbconfig, int zscale)
Definition at line 253 of file cdl.c.
References bitpix, cdl_computeZscale(), cdl_debug, cdl_freeDisplayList(), cdl_selectFB(), cdl_setFBConfig(), cdl_setZScale(), cdl_zscaleImage(), CDLPtr, DLHead, fb, FB_AUTO, fbconfig, frame, h, imd_displayImage(), INDEF, MarkerPtr, max, nframes, nx, ny, pix, True, uchar, w, z1, z2, and zscale.
void cdl_flip (uchar 	* buffer, int nx, int ny) [static]
Definition at line 1671 of file cdl.c.
References i, j, nx, ny, uchar, and v.
void cdl_flip ()
Referenced by cdl_printPix(), and cdl_printPixToFile().
void cdl_getContrast (CDLPtr cdl, float * contrast)
Definition at line 1393 of file cdl.c.
References cdl_debug, and CDLPtr.
void cdl_getFBConfig (CDLPtr cdl, int * configno, int	* w, int * h, int	* nframes)
Definition at line 998 of file cdl.c.
References cdl_debug, CDLPtr, h, nframes, and w.
void cdl_getFrame (CDLPtr cdl, int	* frame)
Definition at line 1266 of file cdl.c.
References cdl_debug, CDLPtr, and frame.
void cdl_getName (CDLPtr cdl, char * imname)
Definition at line 1418 of file cdl.c.
References cdl_debug, and CDLPtr.
void cdl_getSample (CDLPtr cdl, int * nsample)
Definition at line 1343 of file cdl.c.
References cdl_debug, and CDLPtr.
void cdl_getSampleLines (CDLPtr cdl, int * nlines)
Definition at line 1368 of file cdl.c.
References cdl_debug, and CDLPtr.
void cdl_getTitle (CDLPtr cdl, char * imtitle)
Definition at line 1444 of file cdl.c.
References cdl_debug, and CDLPtr.
int cdl_getWCS (CDLPtr cdl, char * name, char * title, float * a, float * b, float * c, float * d, float * tx, float * ty, float * z1, float * z2, int * zt)
Definition at line 453 of file cdl.c.
References a, b, c, cdl_debug, CDLPtr, d, imd_getWCS(), title, tx, ty, z1, z2, and zt.
void cdl_getZScale (CDLPtr cdl, float * z1, float * z2)
Definition at line 1317 of file cdl.c.
References cdl_debug, CDLPtr, z1, and z2.
void cdl_getZTrans (CDLPtr cdl, int * ztrans)
Definition at line 1291 of file cdl.c.
References cdl_debug, and CDLPtr.
void cdl_lookupFBSize (CDLPtr cdl, int configno, int	* w, int * h, int	* nf)
Definition at line 1031 of file cdl.c.
References cdl_debug, CDLPtr, h, nf, and w.
CDLPtr cdl_open (char	* imtdev)
Definition at line 158 of file cdl.c.
References CDL::a, CDL::b, CDL::c, cdl_debug, CDL_LINEAR, cdl_setDebug(), CDL_VERSION, CDLPtr, CDL::contrast, CDL::d, DEF_CONTRAST, DEF_NSAMPLE, DEF_NSAMPLINES, DLHead, DLTail, F_ROMAN, CDL::fbconfig, CDL::fbheight, CDL::fbnf, CDL::fbwidth, CDL::font, CDL::frame, i, CDL::im_nx, CDL::im_ny, imd_open(), imd_setFBConfig(), imd_setFrame(), IMDPtr, CDL::imname, imtdev, CDL::imtitle, L_SOLID, CDL::linestyle, CDL::linewidth, MarkerPtr, MAX_FRAMES, CDL::nsample, CDL::nsamplines, SZ_NAME, CDL::textwidth, CDL::tx, CDL::ty, CDL::z1, CDL::z2, and CDL::ztrans.
int cdl_printPix (CDLPtr cdl, char	* cmd, uchar	* pix, int nx, int ny, int annotate)
Definition at line 764 of file cdl.c.
References annotate, cdl_debug, cdl_flip(), CDLPtr, eps_close(), eps_init(), eps_print(), EPS_PSEUDOCOLOR, eps_setCmap(), eps_setColorType(), eps_setCorners(), eps_setLabel(), ERR, nx, ny, OK, pix, PSImagePtr, SZ_NAME, and uchar.
int cdl_printPixToFile (CDLPtr cdl, char	* fname, uchar	* pix, int nx, int ny, int annotate)
Definition at line 834 of file cdl.c.
References annotate, cdl_debug, cdl_flip(), CDLPtr, eps_close(), eps_init(), eps_print(), EPS_PSEUDOCOLOR, eps_setCmap(), eps_setColorType(), eps_setCorners(), eps_setLabel(), ERR, nx, ny, OK, pix, PSImagePtr, and uchar.
char cdl_readCursor (CDLPtr cdl, int sample, float * x, float * y, char * key)
Definition at line 320 of file cdl.c.
References cdl_debug, CDLPtr, imd_readCursor(), key, x, and y.
int cdl_readFrameBuffer (CDLPtr cdl, uchar ** pix, int * nx, int * ny)
Definition at line 654 of file cdl.c.
References cdl_debug, CDLPtr, imd_readFrameBuffer(), malloc(), nx, ny, pix, and uchar.
int cdl_readImage (CDLPtr cdl, uchar ** pix, int * nx, int * ny)
Definition at line 619 of file cdl.c.
References cdl_debug, CDLPtr, imd_readImage(), malloc(), nx, ny, pix, and uchar.
int cdl_readSubRaster (CDLPtr cdl, int lx, int ly, int nx, int ny, uchar ** pix)
Definition at line 895 of file cdl.c.
References cdl_debug, CDLPtr, imd_readSubRaster(), ly, malloc(), nx, ny, pix, and uchar.
void cdl_selectFB (CDLPtr cdl, int nx, int ny, int	* fb, int	* w, int * h, int	* nf, int reset)
Definition at line 521 of file cdl.c.
References cdl_debug, cdl_setFBConfig(), CDLPtr, FBTab::config, edges, fb, h, FBTab::height, i, MAX_FBCONFIG, nf, FBTab::nframes, nx, ny, reset, w, and FBTab::width.
void cdl_setContrast (CDLPtr cdl, float contrast)
Definition at line 1191 of file cdl.c.
References cdl_debug, and CDLPtr.
int cdl_setCursor (CDLPtr cdl, int x, int y, int wcs)
Definition at line 354 of file cdl.c.
References cdl_debug, CDLPtr, imd_setCursor(), wcs, x, and y.
void cdl_setDebug (int state)
Definition at line 1473 of file cdl.c.
References cdl_debug, com_setDebug(), and imd_setDebug().
void cdl_setFBConfig (CDLPtr cdl, int configno)
Definition at line 964 of file cdl.c.
References cdl_debug, CDLPtr, imd_setFBConfig(), and max.
void cdl_setFrame (CDLPtr cdl, int frame)
Definition at line 1063 of file cdl.c.
References cdl_debug, CDLPtr, frame, and imd_setFrame().
void cdl_setName (CDLPtr cdl, char	* imname)
Definition at line 1216 of file cdl.c.
References cdl_debug, CDLPtr, and imd_setName().
void cdl_setSample (CDLPtr cdl, int nsample)
Definition at line 1141 of file cdl.c.
References cdl_debug, and CDLPtr.
void cdl_setSampleLines (CDLPtr cdl, int nlines)
Definition at line 1166 of file cdl.c.
References cdl_debug, and CDLPtr.
void cdl_setTitle (CDLPtr cdl, char	* imtitle)
Definition at line 1241 of file cdl.c.
References cdl_debug, CDLPtr, and imd_setTitle().
int cdl_setWCS (CDLPtr cdl, char * imname, char * imtitle, float a, float b, float c, float d, float tx, float ty, float z1, float z2, int zt)
Definition at line 397 of file cdl.c.
References a, b, c, cdl_debug, CDLPtr, d, imd_setWCS(), tx, ty, z1, z2, and zt.
void cdl_setZScale (CDLPtr cdl, float z1, float z2)
Definition at line 1115 of file cdl.c.
References cdl_debug, CDLPtr, z1, and z2.
void cdl_setZTrans (CDLPtr cdl, int ztrans)
Definition at line 1089 of file cdl.c.
References cdl_debug, and CDLPtr.
int cdl_writeSubRaster (CDLPtr cdl, int lx, int ly, int nx, int ny, uchar * pix)
Definition at line 935 of file cdl.c.
References cdl_debug, CDLPtr, imd_writeSubRaster(), ly, nx, ny, pix, and uchar.
void cdl_zscaleImage (CDLPtr cdl, uchar ** pix, int nx, int ny, int bitpix, float z1, float z2)
Definition at line 729 of file cdl.c.
References bitpix, cdl_applyZscale(), cdl_debug, cdl_setZScale(), CDLPtr, nx, ny, pix, uchar, z1, and z2.
Variable Documentation
int cdl_debug = 0
Definition at line 141 of file cdl.c.
Referenced by cdl_applyZscale(), cdl_clearFrame(), cdl_clearOverlay(), cdl_close(), cdl_computeZscale(), cdl_deleteMark(), cdl_displayFITS(), cdl_displayIRAF(), cdl_displayPix(), cdl_doDashedLine(), cdl_doPolygonMark(), cdl_findNearest(), cdl_freeDisplayList(), cdl_getContrast(), cdl_getFBConfig(), cdl_getFrame(), cdl_getName(), cdl_getSample(), cdl_getSampleLines(), cdl_getTitle(), cdl_getWCS(), cdl_getZScale(), cdl_getZTrans(), cdl_lookupFBSize(), cdl_markBox(), cdl_markCircAnnuli(), cdl_markCircle(), cdl_markEllipAnnuli(), cdl_markEllipse(), cdl_markLine(), cdl_markPoint(), cdl_markPointLabel(), cdl_markPolygon(), cdl_markPolyline(), cdl_markText(), cdl_open(), cdl_printPix(), cdl_printPixToFile(), cdl_readCursor(), cdl_readFITS(), cdl_readFITSHdr(), cdl_readFrameBuffer(), cdl_readImage(), cdl_readImageHdr(), cdl_readIRAF(), cdl_readSubRaster(), cdl_redrawOverlay(), cdl_selectFB(), cdl_setContrast(), cdl_setCursor(), cdl_setDebug(), cdl_setFBConfig(), cdl_setFrame(), cdl_setName(), cdl_setSample(), cdl_setSampleLines(), cdl_setTitle(), cdl_setWCS(), cdl_setZScale(), cdl_setZTrans(), cdl_writeSubRaster(), cdl_zscale(), cdl_zscaleImage(), and sampleImage().
MarkerPtr DLHead[MAX_FRAMES]
Definition at line 137 of file cdl.c.
Referenced by cdl_clearOverlay(), cdl_deleteMark(), cdl_displayPix(), cdl_insertMarker(), cdl_open(), cdl_redrawOverlay(), and cdl_removeMarker().
MarkerPtr DLTail[MAX_FRAMES]
Definition at line 138 of file cdl.c.
Referenced by cdl_clearOverlay(), cdl_insertMarker(), cdl_markBox(), cdl_markCircAnnuli(), cdl_markCircle(), cdl_markEllipAnnuli(), cdl_markEllipse(), cdl_markLine(), cdl_markPoint(), cdl_markPointLabel(), cdl_markPolygon(), cdl_markPolyline(), cdl_markText(), cdl_open(), and cdl_removeMarker().
Author
Generated automatically by Doxygen for imcat from the source code.