.TH "CDL" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDL \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cdl.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBframe\fP"
.br
.ti -1c
.RI "int \fBfbconfig\fP"
.br
.ti -1c
.RI "int \fBfbwidth\fP"
.br
.ti -1c
.RI "int \fBfbheight\fP"
.br
.ti -1c
.RI "int \fBfbnf\fP"
.br
.ti -1c
.RI "float \fBcontrast\fP"
.br
.ti -1c
.RI "int \fBnsample\fP"
.br
.ti -1c
.RI "int \fBnsamplines\fP"
.br
.ti -1c
.RI "int \fBim_nx\fP"
.br
.ti -1c
.RI "int \fBim_ny\fP"
.br
.ti -1c
.RI "int \fBfont\fP"
.br
.ti -1c
.RI "int \fBtextwidth\fP"
.br
.ti -1c
.RI "int \fBlinewidth\fP"
.br
.ti -1c
.RI "int \fBlinestyle\fP"
.br
.ti -1c
.RI "char * \fBimname\fP"
.br
.ti -1c
.RI "char * \fBimtitle\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.ti -1c
.RI "float \fBd\fP"
.br
.ti -1c
.RI "float \fBtx\fP"
.br
.ti -1c
.RI "float \fBty\fP"
.br
.ti -1c
.RI "float \fBz1\fP"
.br
.ti -1c
.RI "float \fBz2\fP"
.br
.ti -1c
.RI "int \fBztrans\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float \fBCDL::a\fP"
.PP
Definition at line 115 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "float \fBCDL::b\fP"
.PP
Definition at line 115 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "float \fBCDL::c\fP"
.PP
Definition at line 115 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "float \fBCDL::contrast\fP"
.PP
Definition at line 99 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "float \fBCDL::d\fP"
.PP
Definition at line 115 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::fbconfig\fP"
.PP
Definition at line 94 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::fbheight\fP"
.PP
Definition at line 96 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::fbnf\fP"
.PP
Definition at line 97 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::fbwidth\fP"
.PP
Definition at line 95 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::font\fP"
.PP
Definition at line 107 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::frame\fP"
.PP
Definition at line 93 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::im_nx\fP"
.PP
Definition at line 103 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::im_ny\fP"
.PP
Definition at line 104 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "char* \fBCDL::imname\fP"
.PP
Definition at line 113 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "char* \fBCDL::imtitle\fP"
.PP
Definition at line 114 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::linestyle\fP"
.PP
Definition at line 110 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::linewidth\fP"
.PP
Definition at line 109 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::nsample\fP"
.PP
Definition at line 100 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::nsamplines\fP"
.PP
Definition at line 101 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::textwidth\fP"
.PP
Definition at line 108 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "float \fBCDL::tx\fP"
.PP
Definition at line 116 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "float \fBCDL::ty\fP"
.PP
Definition at line 116 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "float \fBCDL::z1\fP"
.PP
Definition at line 117 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "float \fBCDL::z2\fP"
.PP
Definition at line 117 of file cdl.h.
.PP
Referenced by cdl_open().
.SS "int \fBCDL::ztrans\fP"
.PP
Definition at line 118 of file cdl.h.
.PP
Referenced by cdl_open().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
