iis.c
NAME
iis.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include <values.h>
#include <unistd.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../cdllib/cdl.h'
#include '../../cdllib/cdlP.h'
#include '../../catlib/cat.h'
Defines
#define usage '\n\n\NAME\n\	iis - pipe fits image data into saopipe or ximtool in IIS format\n\\n\SYNOPSIS\n\	iis [-u] [-f fmin fmax] [-F fitsfile] [-p pscom] [-P pscom]\n\		[-c catfile [-s size] [-t type] [-T tname] [-e ename]\n\		[-r rname] [-n nname] [-l]]\n\\n\DESCRIPTION\n\	\'iis\' reads a fits image from stdin, linearly scales the\n\	pixel values to range 0-199, prepends an iis header\n\	and writes the output to a FIFO pipe /dev/imt1o so that saoimage\n\	or ximtool can display it. This saves all the fiddle faddle\n\	with the viewers GUI and is useful to get visual feedback\n\	from scripts which process a series of images.\n\\n\	The first version of this program was devised from a fax of\n\	a photocopy of the arcane IIS display device protocol from\n\	George Miyashiro. Karl Glazebrook then refined this, improving\n\	efficiency - thanks Karl - but I have now ditched his library\n\	in favour of the IRAF/NOAO cdl library due to Michael\n\	Fitzpatrick, which does the same thing, but which is\n\	better documented and has some useful extensions.\n\\n\	Bad pixels (flagged by the MAGIC value) are highlighted in green.\n\\n\	Options:\n\\n\	-u	print this mesage\n\	-f	set the limits for pixel values\n\	-F	read the image from 'fitsfile'\n\	-p	send postscript output to command 'pscom'\n\	-P	send annotated postscript output to command 'pscom'\n\	-c 	read in the objects from 'catfile' and display them\n\		as overlay markers. If catfile = '-' the catalogue\n\		will be read from stdin (but be sure then to use -F\n\		option also). With -c you can use the following options\n\		to control the appearance of markers:\n\	-s 	set default size of markers (5)\n\	-t	set default type (8). Allowed types are:			POINT		2\n\			BOX		4\n\			PLUS		8\n\			CROSS		16\n\			DIAMOND		32\n\			CIRCLE		64\n\			STAR		128\n\			HLINE		256\n\			VLINE		512\n\		you can add these to make composite markers and/or\n\		add 1 to fill them.\n\	-e 	option to draw ellipses with polarisation ename\n\	-r 	set size to input variable rname\n\	-T	set type from inut variable tname\n\	-n	label marker with input variable 'nname'\n\	-C	set color from input variable 'cname'. Allowed colors are\n\			BLACK	1	CORAL	9\n\			WHITE	2	MAROON	10\n\			RED	3	ORANGE	11\n\			GREEN	4	KHAKI	12\n\			BLUE	5	ORCHID	13\n\			YELLOW	6	TQUOISE	14\n\			CYAN	7	VIOLET	15\n\			MAGENTA	8	WHEAT	16\n\	-l	enter edit loop after displaying cat in which we do the following\n\		in response to key strokes:\n\			Key		Action\n\			---		---\n\			d		delete marker nearest cursor\n\			q		quit edit loop\n\			[0-9]		set overlay color\n\			l		start or end a line\n\			b		start or end a box\n\			r		redraw overlay\n\			f		toggle fill state for boxes\n\\n\AUTHOR\n\	Nick Kaiser -- kaiser@hawaii.edu\n\\n\n'
#define MAGIC FLOAT_MAGIC
#define PIX_MAX 200
#define DIM_MAX 4096
#define COLORBASE 201
#define NKBOX 0
#define NKLINE 1
Functions
main (int argc, char *argv[])
Define Documentation
#define COLORBASE 201
Definition at line 104 of file cdl/iis.c.
#define DIM_MAX 4096
Definition at line 103 of file cdl/iis.c.
#define MAGIC FLOAT_MAGIC
Definition at line 101 of file cdl/iis.c.
#define NKBOX 0
Definition at line 105 of file cdl/iis.c.
#define NKLINE 1
Definition at line 106 of file cdl/iis.c.
#define PIX_MAX 200
Definition at line 102 of file cdl/iis.c.
#define usage '\n\n\NAME\n\	iis - pipe fits image data into saopipe or ximtool in IIS format\n\\n\SYNOPSIS\n\	iis [-u] [-f fmin fmax] [-F fitsfile] [-p pscom] [-P pscom]\n\		[-c catfile [-s size] [-t type] [-T tname] [-e ename]\n\		[-r rname] [-n nname] [-l]]\n\\n\DESCRIPTION\n\	\'iis\' reads a fits image from stdin, linearly scales the\n\	pixel values to range 0-199, prepends an iis header\n\	and writes the output to a FIFO pipe /dev/imt1o so that saoimage\n\	or ximtool can display it. This saves all the fiddle faddle\n\	with the viewers GUI and is useful to get visual feedback\n\	from scripts which process a series of images.\n\\n\	The first version of this program was devised from a fax of\n\	a photocopy of the arcane IIS display device protocol from\n\	George Miyashiro. Karl Glazebrook then refined this, improving\n\	efficiency - thanks Karl - but I have now ditched his library\n\	in favour of the IRAF/NOAO cdl library due to Michael\n\	Fitzpatrick, which does the same thing, but which is\n\	better documented and has some useful extensions.\n\\n\	Bad pixels (flagged by the MAGIC value) are highlighted in green.\n\\n\	Options:\n\\n\	-u	print this mesage\n\	-f	set the limits for pixel values\n\	-F	read the image from 'fitsfile'\n\	-p	send postscript output to command 'pscom'\n\	-P	send annotated postscript output to command 'pscom'\n\	-c 	read in the objects from 'catfile' and display them\n\		as overlay markers. If catfile = '-' the catalogue\n\		will be read from stdin (but be sure then to use -F\n\		option also). With -c you can use the following options\n\		to control the appearance of markers:\n\	-s 	set default size of markers (5)\n\	-t	set default type (8). Allowed types are:			POINT		2\n\			BOX		4\n\			PLUS		8\n\			CROSS		16\n\			DIAMOND		32\n\			CIRCLE		64\n\			STAR		128\n\			HLINE		256\n\			VLINE		512\n\		you can add these to make composite markers and/or\n\		add 1 to fill them.\n\	-e 	option to draw ellipses with polarisation ename\n\	-r 	set size to input variable rname\n\	-T	set type from inut variable tname\n\	-n	label marker with input variable 'nname'\n\	-C	set color from input variable 'cname'. Allowed colors are\n\			BLACK	1	CORAL	9\n\			WHITE	2	MAROON	10\n\			RED	3	ORANGE	11\n\			GREEN	4	KHAKI	12\n\			BLUE	5	ORCHID	13\n\			YELLOW	6	TQUOISE	14\n\			CYAN	7	VIOLET	15\n\			MAGENTA	8	WHEAT	16\n\	-l	enter edit loop after displaying cat in which we do the following\n\		in response to key strokes:\n\			Key		Action\n\			---		---\n\			d		delete marker nearest cursor\n\			q		quit edit loop\n\			[0-9]		set overlay color\n\			l		start or end a line\n\			b		start or end a box\n\			r		redraw overlay\n\			f		toggle fill state for boxes\n\\n\AUTHOR\n\	Nick Kaiser -- kaiser@hawaii.edu\n\\n\n'
Definition at line 8 of file cdl/iis.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 108 of file cdl/iis.c.
References b, color, d, e, exit(), f, fb, frame, h, key, l, n, nf, not(), r, t, tmp, vector(), w, and x.
Author
Generated automatically by Doxygen for imcat from the source code.