.TH "cdlfont.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cdlfont.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCHARACTER_START\fP   32"
.br
.ti -1c
.RI "#define \fBCHARACTER_END\fP   126"
.br
.ti -1c
.RI "#define \fBCHARACTER_HEIGHT\fP   26"
.br
.ti -1c
.RI "#define \fBCHARACTER_WIDTH\fP   17"
.br
.ti -1c
.RI "#define \fBFONT_LEFT\fP   0"
.br
.ti -1c
.RI "#define \fBFONT_CENTER\fP   9"
.br
.ti -1c
.RI "#define \fBFONT_RIGHT\fP   27"
.br
.ti -1c
.RI "#define \fBFONT_TOP\fP   36"
.br
.ti -1c
.RI "#define \fBFONT_CAP\fP   34"
.br
.ti -1c
.RI "#define \fBFONT_HALF\fP   23"
.br
.ti -1c
.RI "#define \fBFONT_BASE\fP   9"
.br
.ti -1c
.RI "#define \fBFONT_BOTTOM\fP   0"
.br
.ti -1c
.RI "#define \fBFONT_WIDTH\fP   27"
.br
.ti -1c
.RI "#define \fBFONT_HEIGHT\fP   36"
.br
.ti -1c
.RI "#define \fBCOORD_X_START\fP   7"
.br
.ti -1c
.RI "#define \fBCOORD_Y_START\fP   1"
.br
.ti -1c
.RI "#define \fBCOORD_PEN_START\fP   13"
.br
.ti -1c
.RI "#define \fBCOORD_X_LEN\fP   6"
.br
.ti -1c
.RI "#define \fBCOORD_Y_LEN\fP   6"
.br
.ti -1c
.RI "#define \fBCOORD_PEN_LEN\fP   1"
.br
.ti -1c
.RI "#define \fBPAINT_BEGIN_START\fP   14"
.br
.ti -1c
.RI "#define \fBPAINT_END_START\fP   15"
.br
.ti -1c
.RI "#define \fBPAINT_BEGIN_LEN\fP   1"
.br
.ti -1c
.RI "#define \fBPAINT_END_LEN\fP   1"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "short \fBchridx\fP []"
.br
.ti -1c
.RI "short \fBchrtab\fP []"
.br
.ti -1c
.RI "short \fBgchidx\fP []"
.br
.ti -1c
.RI "short \fBgchwid\fP []"
.br
.ti -1c
.RI "short \fBgchtab\fP []"
.br
.ti -1c
.RI "short \fBtimidx\fP []"
.br
.ti -1c
.RI "short \fBtimwid\fP []"
.br
.ti -1c
.RI "short \fBtimtab\fP []"
.br
.ti -1c
.RI "short \fBfutidx\fP []"
.br
.ti -1c
.RI "short \fBfutwid\fP []"
.br
.ti -1c
.RI "short \fBfuttab\fP []"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CHARACTER_END   126"
.PP
Definition at line 5 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker(), and cdl_strlen().
.SS "#define CHARACTER_HEIGHT   26"
.PP
Definition at line 6 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker(), cdl_markText(), and cdl_strlen().
.SS "#define CHARACTER_START   32"
.PP
Definition at line 4 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker(), and cdl_strlen().
.SS "#define CHARACTER_WIDTH   17"
.PP
Definition at line 7 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker(), cdl_markPoint(), cdl_markText(), and cdl_strlen().
.SS "#define COORD_PEN_LEN   1"
.PP
Definition at line 25 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "#define COORD_PEN_START   13"
.PP
Definition at line 22 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "#define COORD_X_LEN   6"
.PP
Definition at line 23 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "#define COORD_X_START   7"
.PP
Definition at line 20 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "#define COORD_Y_LEN   6"
.PP
Definition at line 24 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "#define COORD_Y_START   1"
.PP
Definition at line 21 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "#define FONT_BASE   9"
.PP
Definition at line 15 of file cdlfont.h.
.SS "#define FONT_BOTTOM   0"
.PP
Definition at line 16 of file cdlfont.h.
.SS "#define FONT_CAP   34"
.PP
Definition at line 13 of file cdlfont.h.
.SS "#define FONT_CENTER   9"
.PP
Definition at line 10 of file cdlfont.h.
.SS "#define FONT_HALF   23"
.PP
Definition at line 14 of file cdlfont.h.
.SS "#define FONT_HEIGHT   36"
.PP
Definition at line 18 of file cdlfont.h.
.PP
Referenced by cdl_markText().
.SS "#define FONT_LEFT   0"
.PP
Definition at line 9 of file cdlfont.h.
.SS "#define FONT_RIGHT   27"
.PP
Definition at line 11 of file cdlfont.h.
.SS "#define FONT_TOP   36"
.PP
Definition at line 12 of file cdlfont.h.
.SS "#define FONT_WIDTH   27"
.PP
Definition at line 17 of file cdlfont.h.
.SS "#define PAINT_BEGIN_LEN   1"
.PP
Definition at line 29 of file cdlfont.h.
.SS "#define PAINT_BEGIN_START   14"
.PP
Definition at line 27 of file cdlfont.h.
.SS "#define PAINT_END_LEN   1"
.PP
Definition at line 30 of file cdlfont.h.
.SS "#define PAINT_END_START   15"
.PP
Definition at line 28 of file cdlfont.h.
.SH "Variable Documentation"
.PP 
.SS "short \fBchridx\fP[]"
.PP
\fBInitial value:\fP.nf
 {   
     1,   3,  12,  21,  30,  45,  66,  79,  85,  92,
    99, 106, 111, 118, 121, 128, 131, 141, 145, 154,
   168, 177, 187, 199, 203, 221, 233, 246, 259, 263,
   268, 272, 287, 307, 314, 327, 336, 344, 352, 359,
   371, 378, 385, 391, 398, 402, 408, 413, 425, 433,
   445, 455, 468, 473, 480, 484, 490, 495, 501, 506,
   511, 514, 519, 523, 526, 529, 543, 554, 563, 574,
   585, 593, 607, 615, 625, 638, 645, 650, 663, 671,
   681, 692, 703, 710, 723, 731, 739, 743, 749, 754,
   759, 764, 776, 781, 793, 801
}
.fi
.PP
Definition at line 55 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "short \fBchrtab\fP[]"
.PP
Definition at line 69 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "short \fBfutidx\fP[]"
.PP
\fBInitial value:\fP.nf
 {    
      1,    3,   11,   16,   25,   50,   80,  115,  123,  134,  145,  152,
    157,  165,  168,  174,  177,  195,  200,  215,  231,  237,  255,  279,
    284,  314,  338,  349,  362,  366,  371,  375,  395,  448,  455,  477,
    496,  511,  520,  527,  549,  556,  559,  570,  577,  582,  591,  598,
    620,  633,  657,  672,  693,  698,  709,  714,  723,  728,  734,  741,
    750,  753,  762,  767,  770,  778,  795,  812,  827,  844,  862,  870,
    892,  902,  910,  921,  928,  931,  948,  958,  976,  993, 1010, 1018,
   1036, 1044, 1054, 1059, 1068, 1073, 1082, 1089, 1127, 1130, 1168, 1191,
}
.fi
.PP
Definition at line 640 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "short \fBfuttab\fP[]"
.PP
Definition at line 666 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "short \fBfutwid\fP[]"
.PP
\fBInitial value:\fP.nf
 {    
     21,   15,   21,   26,   25,   29,   31,   15,   19,   19,
     21,   31,   13,   31,   13,   27,   25,   25,   25,   25,
     25,   25,   25,   25,   25,   25,   13,   13,   29,   31,
     29,   23,   32,   23,   26,   26,   26,   24,   23,   26,
     27,   13,   21,   26,   22,   29,   27,   27,   26,   27,
     26,   25,   21,   27,   23,   29,   25,   23,   25,   19,
     19,   19,   21,   23,   13,   24,   24,   23,   24,   23,
     17,   24,   24,   11,   15,   22,   13,   34,   24,   24,
     24,   24,   20,   22,   17,   24,   21,   27,   22,   21,
     22,   19,   13,   19,   29,   21 
}
.fi
.PP
Definition at line 652 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker(), and cdl_strlen().
.SS "short \fBgchidx\fP[]"
.PP
\fBInitial value:\fP.nf
 {    
      1,    3,   16,   29,   38,   77,  107,  154,  162,  181,  200,  205,
    212,  233,  240,  246,  259,  297,  306,  348,  392,  402,  437,  483,
    510,  568,  614,  645,  658,  666,  673,  681,  688,  741,  767,  793,
    795,  806,  821,  863,  874,  883,  888,  899,  901,  912,  921,  930,
    972,  987, 1037, 1067, 1083, 1088, 1117, 1143, 1182, 1207, 1242, 1244,
   1253, 1256, 1265, 1267, 1276, 1284, 1321, 1373, 1394, 1436, 1465, 1500,
   1520, 1549, 1563, 1605, 1630, 1650, 1674, 1694, 1724, 1741, 1783, 1812,
   1844, 1857, 1886, 1888, 1929, 1970, 2001, 2031, 2069, 2074, 2112, 2121,
}
.fi
.PP
Definition at line 154 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "short \fBgchtab\fP[]"
.PP
Definition at line 180 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "short \fBgchwid\fP[]"
.PP
\fBInitial value:\fP.nf
 {    
     21,   15,   15,   26,   25,   29,   30,   15,   19,   19,
     27,   29,   30,   29,   15,   31,   25,   25,   25,   25,
     25,   25,   25,   25,   25,   25,   29,   15,   29,   31,
     29,   31,   32,   25,   30,   21,   25,   29,   26,   23,
     26,   19,   25,   21,   25,   21,   21,   27,   29,   27,
     29,   26,   19,   24,   25,   27,   27,   28,   21,   19,
     19,   19,   21,   31,   27,   28,   26,   23,   24,   23,
     27,   25,   27,   17,   24,   25,   25,   28,   25,   23,
     27,   28,   24,   26,   25,   25,   21,   28,   22,   28,
     23,   19,   19,   19,   31,   19 
}
.fi
.PP
Definition at line 166 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker(), and cdl_strlen().
.SS "short \fBtimidx\fP[]"
.PP
\fBInitial value:\fP.nf
 {    
      1,    3,   16,   33,   42,   81,  111,  158,  163,  182,  201,  208,
    213,  221,  224,  230,  233,  271,  280,  322,  366,  376,  411,  457,
    484,  542,  588,  599,  612,  616,  621,  625,  655,  708,  721,  761,
    792,  819,  836,  851,  887,  906,  915,  933,  952,  963,  984,  999,
   1041, 1066, 1126, 1165, 1198, 1211, 1231, 1242, 1259, 1274, 1289, 1302,
   1311, 1314, 1323, 1330, 1333, 1339, 1375, 1404, 1431, 1462, 1491, 1510,
   1565, 1587, 1601, 1623, 1642, 1651, 1686, 1708, 1742, 1773, 1802, 1821,
   1852, 1866, 1888, 1899, 1916, 1931, 1949, 1962, 2000, 2003, 2041, 2064,
}
.fi
.PP
Definition at line 399 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "short \fBtimtab\fP[]"
.PP
Definition at line 425 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker().
.SS "short \fBtimwid\fP[]"
.PP
\fBInitial value:\fP.nf
 {    
     21,   15,   23,   26,   25,   29,   30,   13,   19,   19,
     21,   31,   13,   31,   13,   27,   25,   25,   25,   25,
     25,   25,   25,   25,   25,   25,   13,   13,   29,   31,
     29,   23,   32,   25,   27,   26,   27,   26,   25,   28,
     29,   16,   20,   27,   23,   32,   28,   27,   27,   27,
     27,   25,   24,   29,   25,   29,   25,   26,   25,   19,
     19,   19,   27,   25,   17,   25,   26,   24,   26,   24,
     18,   24,   27,   16,   16,   26,   16,   36,   27,   25,
     26,   25,   22,   22,   20,   27,   23,   29,   25,   24,
     23,   19,   13,   19,   29,   21 
}
.fi
.PP
Definition at line 411 of file cdlfont.h.
.PP
Referenced by cdl_doTextMarker(), and cdl_strlen().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
