cdlfits.c
NAME
cdlfits.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <ctype.h>
#include 'cdl.h'
Data Structures
struct FITS
Defines
#define CDL_LIBRARY_SOURCE
#define NCARDS 36
#define BLOCKSIZE 2880
#define SZ_CARD 80
#define f_max(a, b) ((a) > (b) ? (a) : (b))
#define f_min(a, b) ((a) < (b) ? (a) : (b))
Enumerations
enum datatype { T_INT, T_LOG, T_REAL, T_STR, T_NOVAL }
Functions
char * cdl_getFITSPixels ()
char * cdl_openFITS ()
char ** cdl_readHeader ()
char * cdl_rdCard ()
char ** cdl_getData ()
char *** cdl_fixData ()
int cdl_readFITSHdr ()
int cdl_displayFITS (CDLPtr cdl, char *fname, int frame, int fbconfig, int zscale)
int cdl_isFITS (char *fname)
int cdl_readFITS (char *fname, uchar **pix, int *nx, int *ny, int *bitpix, char *title)
int cdl_readFITSHdr (char *fname, float *bscale, float *bzero, char *obj)
char * cdl_getFITSPixels (char *fname, uchar **pix, int *nx, int *ny, int *bitpix)
char * cdl_openFITS (FITS *fs, char *file, int *nx, int *ny, int *bitpix)
char * cdl_readHeader (FITS *fs)
char * cdl_rdCard (char *card, char *name, enum datatype dtype, long *kvalue, float *rvalue, char *svalue)
char * cdl_getData (FITS *fs, uchar *buffer, int nelem)
char * cdl_fixData (FITS *fs, void *buffer, int nelem)
Variables
int cdl_debug
Define Documentation
#define BLOCKSIZE 2880
Definition at line 18 of file cdlfits.c.
Referenced by cdl_getData(), and cdl_readHeader().
#define CDL_LIBRARY_SOURCE
Definition at line 4 of file cdlfits.c.
#define f_max(a, b) ((a) > (b) ? (a) : (b))
Definition at line 42 of file cdlfits.c.
Referenced by cdl_getFITSPixels().
#define f_min(a, b) ((a) < (b) ? (a) : (b))
Definition at line 44 of file cdlfits.c.
#define NCARDS 36
Definition at line 17 of file cdlfits.c.
Referenced by cdl_readHeader().
#define SZ_CARD 80
Definition at line 19 of file cdlfits.c.
Referenced by cdl_displayFITS(), cdl_rdCard(), and cdl_readHeader().
Enumeration Type Documentation
enum datatype
Enumeration values:
T_INT
T_LOG
T_REAL
T_STR
T_NOVAL
Definition at line 22 of file cdlfits.c.
Referenced by cdl_rdCard().
Function Documentation
int cdl_displayFITS (CDLPtr cdl, char	* fname, int frame, int fbconfig, int zscale)
Definition at line 86 of file cdlfits.c.
References bitpix, cdl_debug, cdl_displayPix(), cdl_isFITS(), cdl_readFITS(), cdl_readFITSHdr(), cdl_setName(), cdl_setTitle(), CDLPtr, ERR, fbconfig, frame, free(), nx, ny, pix, SZ_CARD, uchar, z1, z2, and zscale.
char* cdl_fixData (FITS 	* fs, void 	* buffer, int nelem) [static]
Definition at line 718 of file cdlfits.c.
References i, j, k, l, n, and uchar.
char* * * cdl_fixData ()
Referenced by cdl_getData().
char* cdl_getData (FITS 	* fs, uchar 	* buffer, int nelem) [static]
Definition at line 665 of file cdlfits.c.
References BLOCKSIZE, cdl_fixData(), and uchar.
char* * cdl_getData ()
Referenced by cdl_getFITSPixels().
char* cdl_getFITSPixels (char 	* fname, uchar ** pix, int 	* nx, int * ny, int	* bitpix) [static]
Definition at line 293 of file cdlfits.c.
References FITS::bitpix, bitpix, FITS::bscale, buf, FITS::bzero, cdl_getData(), cdl_openFITS(), f_max, FITS::fp, free(), i, malloc(), nx, ny, pix, FITS::size, and uchar.
char* cdl_getFITSPixels () [static]
Referenced by cdl_readFITS().
int cdl_isFITS (char	* fname)
Definition at line 142 of file cdlfits.c.
References val.
Referenced by cdl_displayFITS(), cdl_readFITS(), and cdl_readFITSHdr().
char* cdl_openFITS (FITS 	* fs, char	* file, int	* nx, int * ny, int * bitpix) [static]
Definition at line 384 of file cdlfits.c.
References bitpix, cdl_readHeader(), i, nx, and ny.
char* cdl_openFITS () [static]
Referenced by cdl_getFITSPixels().
char* cdl_rdCard (char	* card, char	* name, enum datatype dtype, long 	* kvalue, float 	* rvalue, char 	* svalue) [static]
Definition at line 583 of file cdlfits.c.
References datatype, i, SZ_CARD, SZ_FNAME, T_INT, T_LOG, T_REAL, and T_STR.
char* cdl_rdCard () [static]
Referenced by cdl_readHeader().
int cdl_readFITS (char	* fname, uchar	** pix, int	* nx, int * ny, int	* bitpix, char	* title)
Definition at line 178 of file cdlfits.c.
References bitpix, cdl_debug, cdl_getFITSPixels(), cdl_isFITS(), cdl_readFITSHdr(), ERR, nx, ny, OK, pix, title, and uchar.
int cdl_readFITSHdr (char	* fname, float	* bscale, float * bzero, char	* obj) [static]
Definition at line 231 of file cdlfits.c.
References FITS::bitpix, FITS::bscale, FITS::bzero, cdl_debug, cdl_isFITS(), cdl_readHeader(), FITS::cpos, ERR, FITS::fp, free(), malloc(), FITS::naxis, FITS::object, and OK.
int cdl_readFITSHdr () [static]
Referenced by cdl_displayFITS(), and cdl_readFITS().
char* cdl_readHeader (FITS * fs) [static]
Definition at line 437 of file cdlfits.c.
References BLOCKSIZE, cdl_rdCard(), free(), i, j, malloc(), NCARDS, SZ_CARD, SZ_FNAME, T_INT, T_LOG, T_REAL, T_STR, and val.
char* * cdl_readHeader ()
Referenced by cdl_openFITS(), and cdl_readFITSHdr().
Variable Documentation
int cdl_debug
Definition at line 46 of file cdlfits.c.
Author
Generated automatically by Doxygen for imcat from the source code.