cdlmark.c
NAME
cdlmark.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include 'cdl.h'
#include 'cdlfont.h'
Defines
#define CDL_NEED_LINESTYLES
#define CDL_LIBRARY_SOURCE
#define ABS(a) (((a)<0) ? -(a) : (a))
#define SGN(a) (((a)<0) ? -1 : 1)
#define N_CIRCLE_PTS 48
#define N_ELLIPSE_PTS 64
#define FONT_SCALE 0.4
#define FONT_SPACE 4
Functions
int cdl_freeDisplayList ()
void cdl_setFont ()
void cdl_setLineWidth ()
void cdl_setLineStyle ()
void cdl_beginDList ()
void cdl_drawDList ()
void cdl_clearDList ()
void cdl_endDList ()
void cdl_setTextWidth ()
int cdl_getPixRegion ()
uchar cdl_setpixel ()
void cdl_insertMarker ()
void cdl_removeMarker ()
void cdl_doLineInSubRas ()
void cdl_drawThickVector ()
void cdl_drawVector ()
void cdl_doPointMark ()
void cdl_doLineMark ()
void cdl_doBoxMark ()
void cdl_doPolygonMark ()
void cdl_doCircleMark ()
void cdl_doCircAnnuliMark ()
void cdl_doEllipseMark ()
void cdl_doEllipAnnuliMark ()
void cdl_getCircleCoords ()
void cdl_getEllipseCoords ()
void cdl_printDisplayList ()
void cdl_initMarkPos ()
void cdl_fillArea ()
void cdl_minmax ()
void cdl_doDashedLine ()
void cdl_drawThickDashVec ()
void cdl_drawDashVec ()
int cdl_strlen ()
int bitupk ()
MarkerPtr cdl_initPointMarker ()
MarkerPtr cdl_initLineMarker ()
MarkerPtr cdl_initBoxMarker ()
MarkerPtr cdl_initPolylineMarker ()
MarkerPtr cdl_initPolygonMarker ()
MarkerPtr cdl_initCircleMarker ()
MarkerPtr cdl_initCircAnnMarker ()
MarkerPtr cdl_initEllipseMarker ()
MarkerPtr cdl_initEllAnnMarker ()
MarkerPtr cdl_findNearest ()
MarkerPtr cdl_initTextMarker ()
MarkerPtr cdl_initPointLabelMarker ()
int cdl_mapFrame (CDLPtr cdl, int frame)
int cdl_markPoint (CDLPtr cdl, int x, int y, int number, int size, int type, int color)
int cdl_markPointLabel (CDLPtr cdl, int x, int y, char *label, int size, int type, int color)
int cdl_markCoordsFile (CDLPtr cdl, char *fname, int type, int size, int color, int label)
int cdl_markLine (CDLPtr cdl, int xs, int ys, int xe, int ye, int color)
int cdl_markBox (CDLPtr cdl, int lx, int ly, int ux, int uy, int fill, int color)
int cdl_markPolygon (CDLPtr cdl, xarray, yarray, int npts, int fill, int color)
int cdl_markPolyline (CDLPtr cdl, int *xarray, int *yarray, int npts, int color)
int cdl_markCircle (CDLPtr cdl, int x, int y, int radius, int fill, int color)
int cdl_markCircAnnuli (CDLPtr cdl, int x, int y, int radius, int nannuli, int sep, int color)
int cdl_markEllipse (CDLPtr cdl, int x, int y, int xrad, int yrad, float rotang, int fill, int color)
int cdl_markEllipAnnuli (CDLPtr cdl, int x, int y, int xrad, int yrad, float ang, int nannuli, int sep, int color)
int cdl_markText (CDLPtr cdl, int x, int y, char *str, float size, float angle, int color)
void cdl_setFont (CDLPtr cdl, int font)
void cdl_setTextWidth (CDLPtr cdl, int width)
void cdl_setLineWidth (CDLPtr cdl, int width)
void cdl_setLineStyle (CDLPtr cdl, int style)
int cdl_deleteMark (CDLPtr cdl, int x, int y)
int cdl_clearOverlay (CDLPtr cdl)
int cdl_redrawOverlay (CDLPtr cdl)
void cdl_beginDList (int frame)
void cdl_endDList (int frame, int flush)
void cdl_clearDList (int frame)
void cdl_drawDList (int frame)
int cdl_getPixRegion (CDLPtr cdl, int lx, int ly, int nx, int ny, uchar *ras)
void cdl_doPointMark (int color, int type, uchar *pix, int sz)
void cdl_doLineMark (int color, int width, int style, uchar *pix, int xs, int ys, int xe, int ye)
void cdl_doBoxMark (int color, int width, int style, int fill, uchar *pix, int lx, int ly, int nx, int ny)
void cdl_doPolygonMark (int color, int width, int style, int fill, int *x, int *y, int npts, uchar *pix, int lx, int ly, int nx, int ny, int close)
void cdl_doCircleMark (int x, int y, int radius, int color, int width, int style, int fill, uchar *pix, int lx, int ly, int nx, int ny)
void cdl_doCircAnnuliMark (int x, int y, int radius, int nannuli, int sep, int color, int width, int style, uchar *pix, int lx, int ly, int nx, int ny)
void cdl_doEllipseMark (int color, int width, int style, int fill, int xc, int yc, int xrad, int yrad, float ang, uchar *pix, int lx, int ly, int nx, int ny)
void cdl_doEllipAnnuliMark (int x, int y, int xrad, int yrad, float ang, int nannuli, int sep, int color, int width, int style, uchar *pix, int lx, int ly, int nx, int ny)
int cdl_doTextMarker (int x, int y, char *string, float txtsize, float angle, int color, int width, int txtfont, uchar *pix, int lx, int ly, int nx, int ny)
int cdl_freeDisplayList (CDLPtr cdl, MarkerPtr head)
void cdl_insertMarker (CDLPtr cdl, MarkerPtr back, MarkerPtr new)
void cdl_removeMarker (CDLPtr cdl, MarkerPtr mk)
MarkerPtr cdl_findNearest (MarkerPtr head, int x, int y)
void cdl_printDisplayList (FILE *fd, MarkerPtr head)
MarkerPtr cdl_initPointMarker (int x, int y, int number, int size, int type, int color)
MarkerPtr cdl_initPointLabelMarker (int x, int y, char *label, int size, int type, int color, int font)
MarkerPtr cdl_initLineMarker (int x1, int y1, int x2, int y2, int color, int width, int style)
MarkerPtr cdl_initBoxMarker (int lx, int ly, int ux, int uy, int fill, int color, int width, int style)
MarkerPtr cdl_initPolylineMarker (int *x, int *y, int npts, int color, int width, int style)
MarkerPtr cdl_initPolygonMarker (int *x, int *y, int npts, int fill, int color, int width, int style)
MarkerPtr cdl_initCircleMarker (int x, int y, int radius, int fill, int color, int width, int style)
MarkerPtr cdl_initCircAnnMarker (int x, int y, int radius, int nannuli, int sep, int color, int width, int style)
MarkerPtr cdl_initEllipseMarker (int x, int y, int xrad, int yrad, float ang, int fill, int color, int width, int style)
MarkerPtr cdl_initEllAnnMarker (int x, int y, int xrad, int yrad, float ang, int nannuli, int sep, int color, int width, int style)
MarkerPtr cdl_initTextMarker (int x, int y, char *string, float size, int color, int font, int width)
void cdl_initMarkPos (MarkerPtr mk, int nx, int ny, int lx, int ly)
void cdl_doLineInSubRas (uchar *pix, int color, int width, int style, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny)
void cdl_doDashedLine (uchar *pix, int color, int width, int style, int *x, int *y, int npts, int lx, int ly, int nx, int ny)
void cdl_drawThickVector (uchar *pix, int color, int width, int style, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny)
void cdl_drawVector (uchar *pix, int color, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny)
void cdl_drawThickDashVec (uchar *pix, int color, int width, int style, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny)
void cdl_drawDashVec (uchar *pix, int color, int style, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny)
uchar cdl_setpixel (uchar pix, int style, int color)
void cdl_fillArea (uchar *pix, int nx, int ny, int color)
void cdl_getCircleCoords (int xcen, int ycen, int radius, int *x, int *y, int npts)
void cdl_getEllipseCoords (int xcen, int ycen, int xradius, int yradius, float rotang, int *x, int *y)
void cdl_minmax (int *array, int npts, int *amin, int *amax)
int cdl_strlen (char *str, float txtsize, int txtfont)
int bitupk (unsigned int wordp, int offset, int nbits)
Variables
MarkerPtr DLHead [MAX_FRAMES]
MarkerPtr DLTail [MAX_FRAMES]
int DLFlag []
uchar * DLFBPix [MAX_FRAMES]
int cdl_debug
unsigned bitmask []
Define Documentation
#define ABS(a) (((a)<0) ? -(a) : (a))
Definition at line 141 of file cdlmark.c.
Referenced by cdl_doLineMark(), cdl_drawDashVec(), cdl_drawVector(), cdl_findNearest(), cdl_markLine(), cdl_markPolygon(), cdl_markPolyline(), and doplot().
#define CDL_LIBRARY_SOURCE
Definition at line 6 of file cdlmark.c.
#define CDL_NEED_LINESTYLES
Definition at line 5 of file cdlmark.c.
#define FONT_SCALE 0.4
Definition at line 148 of file cdlmark.c.
Referenced by cdl_doTextMarker(), cdl_markPoint(), cdl_markText(), and cdl_strlen().
#define FONT_SPACE 4
Definition at line 149 of file cdlmark.c.
Referenced by cdl_doTextMarker(), cdl_markText(), and cdl_strlen().
#define N_CIRCLE_PTS 48
Definition at line 146 of file cdlmark.c.
Referenced by cdl_doCircleMark().
#define N_ELLIPSE_PTS 64
Definition at line 147 of file cdlmark.c.
Referenced by cdl_doEllipseMark(), and cdl_getEllipseCoords().
#define SGN(a) (((a)<0) ? -1 : 1)
Definition at line 144 of file cdlmark.c.
Referenced by cdl_drawDashVec(), and cdl_drawVector().
Function Documentation
int bitupk (unsigned int wordp, int offset, int nbits) [static]
Definition at line 3818 of file cdlmark.c.
References bitmask.
int bitupk ()
Referenced by cdl_doTextMarker().
void cdl_beginDList (int frame)
Definition at line 1350 of file cdlmark.c.
References frame.
void cdl_beginDList ()
void cdl_clearDList (int frame)
Definition at line 1394 of file cdlmark.c.
References frame.
void cdl_clearDList ()
int cdl_clearOverlay (CDLPtr cdl)
Definition at line 1278 of file cdlmark.c.
References Marker::back, cdl_debug, cdl_removeMarker(), cdl_writeSubRaster(), CDLPtr, DLHead, DLTail, ERR, Marker::lx, Marker::ly, MarkerPtr, Marker::nx, Marker::ny, OK, and Marker::refpix.
int cdl_deleteMark (CDLPtr cdl, int x, int y)
Definition at line 1218 of file cdlmark.c.
References Marker::back, cdl_debug, cdl_findNearest(), cdl_removeMarker(), cdl_writeSubRaster(), CDLPtr, DLHead, ERR, Marker::lx, Marker::ly, MarkerPtr, MK_POINT, MK_TEXT, Marker::next, Marker::number, Marker::nx, Marker::ny, OK, Marker::refpix, Marker::type, x, and y.
void cdl_doBoxMark (int color, int width, int style, int fill, uchar	* pix, int lx, int ly, int nx, int ny) [static]
Definition at line 1649 of file cdlmark.c.
References cdl_doDashedLine(), color, dot(), fill, i, j, k, L_HOLLOW, L_SHADOW, L_SOLID, ly, nx, ny, pix, uchar, w, x, and y.
void cdl_doBoxMark ()
Referenced by cdl_doPointMark(), and cdl_markBox().
void cdl_doCircAnnuliMark (int x, int y, int radius, int nannuli, int sep, int color, int width, int style, uchar	* pix, int lx, int ly, int nx, int ny) [static]
Definition at line 1905 of file cdlmark.c.
References cdl_doCircleMark(), color, False, i, ly, nannuli, nx, ny, pix, radius, sep, uchar, x, and y.
void cdl_doCircAnnuliMark ()
Referenced by cdl_markCircAnnuli().
void cdl_doCircleMark (int x, int y, int radius, int color, int width, int style, int fill, uchar	* pix, int lx, int ly, int nx, int ny) [static]
Definition at line 1858 of file cdlmark.c.
References cdl_doPolygonMark(), cdl_getCircleCoords(), color, fill, ly, N_CIRCLE_PTS, nx, ny, pix, radius, True, uchar, x, xp(), y, and yp().
void cdl_doCircleMark ()
Referenced by cdl_doCircAnnuliMark(), cdl_doPointMark(), and cdl_markCircle().
void cdl_doDashedLine (uchar	* pix, int color, int width, int style, int	* x, int * y, int npts, int lx, int ly, int nx, int ny) [static]
Definition at line 3071 of file cdlmark.c.
References cdl_debug, cdl_drawDashVec(), cdl_drawThickDashVec(), color, dot(), i, ly, npts, nx, ny, pix, uchar, x, and y.
void cdl_doDashedLine ()
Referenced by cdl_doBoxMark(), cdl_doLineMark(), and cdl_doPolygonMark().
void cdl_doEllipAnnuliMark (int x, int y, int xrad, int yrad, float ang, int nannuli, int sep, int color, int width, int style, uchar	* pix, int lx, int ly, int nx, int ny) [static]
Definition at line 2002 of file cdlmark.c.
References ang, cdl_doEllipseMark(), color, False, i, ly, nannuli, nx, ny, pix, sep, uchar, x, xrad, y, and yrad.
void cdl_doEllipAnnuliMark ()
Referenced by cdl_markEllipAnnuli().
void cdl_doEllipseMark (int color, int width, int style, int fill, int xc, int yc, int xrad, int yrad, float ang, uchar	* pix, int lx, int ly, int nx, int ny) [static]
Definition at line 1952 of file cdlmark.c.
References ang, cdl_doPolygonMark(), cdl_getEllipseCoords(), color, fill, ly, N_ELLIPSE_PTS, nx, ny, pix, True, uchar, xp(), xrad, yp(), and yrad.
void cdl_doEllipseMark () [static]
Referenced by cdl_doEllipAnnuliMark(), and cdl_markEllipse().
void cdl_doLineInSubRas (uchar	* pix, int color, int width, int style, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny) [static]
Definition at line 3024 of file cdlmark.c.
References cdl_drawThickVector(), cdl_drawVector(), color, L_HOLLOW, L_SOLID, ly, nx, ny, pix, and uchar.
void cdl_doLineInSubRas () [static]
Referenced by cdl_doLineMark(), cdl_doPolygonMark(), cdl_doTextMarker(), and cdl_markText().
void cdl_doLineMark (int color, int width, int style, uchar	* pix, int xs, int ys, int xe, int ye) [static]
Definition at line 1593 of file cdlmark.c.
References ABS, cdl_doDashedLine(), cdl_doLineInSubRas(), color, L_DASHED, L_DOTDASH, L_DOTTED, L_HOLLOW, L_SOLID, ly, min, nx, ny, pix, uchar, x, xe, y, ye, and ys.
void cdl_doLineMark ()
Referenced by cdl_markLine().
void cdl_doPointMark (int color, int type, uchar	* pix, int sz) [static]
Definition at line 1474 of file cdlmark.c.
References cdl_doBoxMark(), cdl_doCircleMark(), cdl_doPolygonMark(), color, fill, i, j, k, L_SOLID, M_BOX, M_CIRCLE, M_CROSS, M_DIAMOND, M_FILL, M_HBLINE, M_HLINE, M_PLUS, M_POINT, M_STAR, M_VBLINE, M_VLINE, npts, pix, True, type, uchar, x, xp(), y, and yp().
void cdl_doPointMark () [static]
Referenced by cdl_markPoint(), and cdl_markPointLabel().
void cdl_doPolygonMark (int color, int width, int style, int fill, int	* x, int * y, int npts, uchar	* pix, int lx, int ly, int nx, int ny, int close) [static]
Definition at line 1753 of file cdlmark.c.
References cdl_debug, cdl_doDashedLine(), cdl_doLineInSubRas(), cdl_fillArea(), color, fill, i, L_DASHED, L_DOTDASH, L_DOTTED, L_HOLLOW, L_SOLID, ly, malloc(), npts, nx, ny, pix, uchar, x, xp(), y, and yp().
void cdl_doPolygonMark () [static]
Referenced by cdl_doCircleMark(), cdl_doEllipseMark(), cdl_doPointMark(), cdl_markPolygon(), and cdl_markPolyline().
int cdl_doTextMarker (int x, int y, char * string, float txtsize, float angle, int color, int width, int txtfont, uchar * pix, int lx, int ly, int nx, int ny)
Definition at line 2053 of file cdlmark.c.
References angle, bitupk(), cdl_doLineInSubRas(), CHARACTER_END, CHARACTER_HEIGHT, CHARACTER_START, CHARACTER_WIDTH, chridx, chrtab, color, COORD_PEN_LEN, COORD_PEN_START, COORD_X_LEN, COORD_X_START, COORD_Y_LEN, COORD_Y_START, F_FUTURA, F_GREEK, F_ROMAN, F_TIMES, FONT_SCALE, FONT_SPACE, futidx, futtab, futwid, gchidx, gchtab, gchwid, i, j, L_SOLID, len, ly, mx, my, nx, ny, OK, pix, size, timidx, timtab, timwid, uchar, w, x, and y.
Referenced by cdl_markText().
void cdl_drawDashVec (uchar	* pix, int color, int style, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny) [static]
Definition at line 3365 of file cdlmark.c.
References ABS, cdl_setpixel(), color, d, dx, dy, i, ly, max, min, nx, ny, pix, SGN, uchar, x, and y.
void cdl_drawDashVec ()
Referenced by cdl_doDashedLine(), and cdl_drawThickDashVec().
void cdl_drawDList (int frame)
Definition at line 1413 of file cdlmark.c.
References frame.
void cdl_drawDList ()
void cdl_drawThickDashVec (uchar	* pix, int color, int width, int style, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny) [static]
Definition at line 3277 of file cdlmark.c.
References abs, cdl_drawDashVec(), color, dot(), dx, dy, i, L_DASHED, L_DOTDASH, L_DOTTED, ly, n, nx, ny, pix, sign, and uchar.
void cdl_drawThickDashVec () [static]
Referenced by cdl_doDashedLine().
void cdl_drawThickVector (uchar	* pix, int color, int width, int style, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny) [static]
Definition at line 3129 of file cdlmark.c.
References abs, cdl_drawVector(), color, dx, dy, i, L_HOLLOW, L_SHADOW, ly, n, nx, ny, pix, sign, uchar, and w.
void cdl_drawThickVector ()
Referenced by cdl_doLineInSubRas().
void cdl_drawVector (uchar	* pix, int color, int x1, int x2, int y1, int y2, int lx, int ly, int nx, int ny) [static]
Definition at line 3211 of file cdlmark.c.
References ABS, color, d, dx, dy, i, ly, max, min, nx, ny, pix, SGN, uchar, x, and y.
void cdl_drawVector ()
Referenced by cdl_doLineInSubRas(), and cdl_drawThickVector().
void cdl_endDList (int frame, int flush)
Definition at line 1374 of file cdlmark.c.
References frame.
void cdl_endDList ()
void cdl_fillArea (uchar	* pix, int nx, int ny, int color) [static]
Definition at line 3464 of file cdlmark.c.
References color, i, j, l, nx, ny, pix, r, and uchar.
void cdl_fillArea () [static]
Referenced by cdl_doPolygonMark().
MarkerPtr cdl_findNearest (MarkerPtr head, int x, int y)
Definition at line 2381 of file cdlmark.c.
References A, ABS, C, cdl_debug, dist, dmin, i, MarkerPtr, min, MK_BOX, MK_CIRCANN, MK_CIRCLE, MK_ELLIPANN, MK_ELLIPSE, MK_LINE, MK_POINT, MK_POLYGON, MK_POLYLINE, MK_TEXT, Marker::next, Marker::npts, Marker::type, Marker::x, x, Marker::xp, Marker::y, y, and Marker::yp.
MarkerPtr cdl_findNearest ()
Referenced by cdl_deleteMark().
int cdl_freeDisplayList (CDLPtr cdl, MarkerPtr head)
Definition at line 2258 of file cdlmark.c.
References cdl_debug, cdl_removeMarker(), CDLPtr, MarkerPtr, Marker::next, and OK.
int cdl_freeDisplayList ()
Referenced by cdl_displayPix().
void cdl_getCircleCoords (int xcen, int ycen, int radius, int	* x, int * y, int npts) [static]
Definition at line 3513 of file cdlmark.c.
References a1, a2, a3, b1, b2, b3, b4, i, npts, radius, x, and y.
void cdl_getCircleCoords () [static]
Referenced by cdl_doCircleMark().
void cdl_getEllipseCoords (int xcen, int ycen, int xradius, int yradius, float rotang, int	* x, int * y) [static]
Definition at line 3598 of file cdlmark.c.
References a2, b1, b3, i, N_ELLIPSE_PTS, x, and y.
void cdl_getEllipseCoords ()
Referenced by cdl_doEllipseMark().
int cdl_getPixRegion (CDLPtr cdl, int lx, int ly, int nx, int ny, uchar	* ras) [static]
Definition at line 1444 of file cdlmark.c.
References cdl_readSubRaster(), CDLPtr, ly, malloc(), nx, ny, and uchar.
int cdl_getPixRegion () [static]
Referenced by cdl_markBox(), cdl_markCircAnnuli(), cdl_markCircle(), cdl_markEllipAnnuli(), cdl_markEllipse(), cdl_markLine(), cdl_markPoint(), cdl_markPointLabel(), cdl_markPolygon(), cdl_markPolyline(), and cdl_markText().
MarkerPtr cdl_initBoxMarker (int lx, int ly, int ux, int uy, int fill, int color, int width, int style) [static]
Definition at line 2630 of file cdlmark.c.
References Marker::color, color, Marker::fill, fill, Marker::linestyle, Marker::linewidth, ly, malloc(), MarkerPtr, MK_BOX, Marker::type, ux, uy, Marker::x, Marker::xp, Marker::y, and Marker::yp.
MarkerPtr cdl_initBoxMarker () [static]
Referenced by cdl_markBox().
MarkerPtr cdl_initCircAnnMarker (int x, int y, int radius, int nannuli, int sep, int color, int width, int style) [static]
Definition at line 2809 of file cdlmark.c.
References Marker::color, color, Marker::linestyle, Marker::linewidth, MarkerPtr, MK_CIRCANN, Marker::nannuli, nannuli, Marker::radius, radius, Marker::sep, sep, Marker::type, Marker::x, x, Marker::y, and y.
MarkerPtr cdl_initCircAnnMarker () [static]
Referenced by cdl_markCircAnnuli().
MarkerPtr cdl_initCircleMarker (int x, int y, int radius, int fill, int color, int width, int style) [static]
Definition at line 2766 of file cdlmark.c.
References Marker::color, color, Marker::fill, fill, Marker::linestyle, Marker::linewidth, MarkerPtr, MK_CIRCLE, Marker::radius, radius, Marker::type, Marker::x, x, Marker::y, and y.
MarkerPtr cdl_initCircleMarker ()
Referenced by cdl_markCircle().
MarkerPtr cdl_initEllAnnMarker (int x, int y, int xrad, int yrad, float ang, int nannuli, int sep, int color, int width, int style) [static]
Definition at line 2903 of file cdlmark.c.
References Marker::ang, ang, Marker::color, color, Marker::linestyle, Marker::linewidth, MarkerPtr, MK_ELLIPANN, Marker::nannuli, nannuli, Marker::sep, sep, Marker::type, Marker::x, x, Marker::xrad, xrad, Marker::y, y, Marker::yrad, and yrad.
MarkerPtr cdl_initEllAnnMarker () [static]
Referenced by cdl_markEllipAnnuli().
MarkerPtr cdl_initEllipseMarker (int x, int y, int xrad, int yrad, float ang, int fill, int color, int width, int style) [static]
Definition at line 2855 of file cdlmark.c.
References Marker::ang, ang, Marker::color, color, Marker::fill, fill, Marker::linestyle, Marker::linewidth, MarkerPtr, MK_ELLIPSE, Marker::type, Marker::x, x, Marker::xrad, xrad, Marker::y, y, Marker::yrad, and yrad.
MarkerPtr cdl_initEllipseMarker ()
Referenced by cdl_markEllipse().
MarkerPtr cdl_initLineMarker (int x1, int y1, int x2, int y2, int color, int width, int style) [static]
Definition at line 2585 of file cdlmark.c.
References Marker::color, color, Marker::linestyle, Marker::linewidth, malloc(), MarkerPtr, MK_LINE, Marker::type, Marker::x, Marker::xp, Marker::y, and Marker::yp.
MarkerPtr cdl_initLineMarker ()
Referenced by cdl_markLine().
void cdl_initMarkPos (MarkerPtr mk, int nx, int ny, int lx, int ly) [static]
Definition at line 2981 of file cdlmark.c.
References ly, MarkerPtr, nx, and ny.
void cdl_initMarkPos ()
Referenced by cdl_markBox(), cdl_markCircAnnuli(), cdl_markCircle(), cdl_markEllipAnnuli(), cdl_markEllipse(), cdl_markLine(), cdl_markPoint(), cdl_markPointLabel(), cdl_markPolygon(), cdl_markPolyline(), and cdl_markText().
MarkerPtr cdl_initPointLabelMarker (int x, int y, char * label, int size, int type, int color, int font) [static]
Definition at line 2543 of file cdlmark.c.
References Marker::color, color, Marker::font, label, malloc(), MarkerPtr, MK_POINT, Marker::pt_type, Marker::size, size, Marker::str, Marker::type, type, Marker::x, x, Marker::y, and y.
MarkerPtr cdl_initPointLabelMarker ()
Referenced by cdl_markPointLabel().
MarkerPtr cdl_initPointMarker (int x, int y, int number, int size, int type, int color) [static]
Definition at line 2502 of file cdlmark.c.
References Marker::color, color, MarkerPtr, MK_POINT, Marker::number, number, Marker::pt_type, Marker::size, size, Marker::type, type, Marker::x, x, Marker::y, and y.
MarkerPtr cdl_initPointMarker () [static]
Referenced by cdl_markPoint().
MarkerPtr cdl_initPolygonMarker (int * x, int * y, int npts, int fill, int color, int width, int style) [static]
Definition at line 2720 of file cdlmark.c.
References Marker::color, color, Marker::fill, fill, Marker::linestyle, Marker::linewidth, malloc(), MarkerPtr, MK_POLYGON, Marker::npts, npts, Marker::type, Marker::x, x, Marker::xp, Marker::y, y, and Marker::yp.
MarkerPtr cdl_initPolygonMarker () [static]
Referenced by cdl_markPolygon().
MarkerPtr cdl_initPolylineMarker (int * x, int * y, int npts, int color, int width, int style) [static]
Definition at line 2676 of file cdlmark.c.
References Marker::color, color, Marker::linestyle, Marker::linewidth, malloc(), MarkerPtr, MK_POLYLINE, Marker::npts, npts, Marker::type, Marker::x, x, Marker::xp, Marker::y, y, and Marker::yp.
MarkerPtr cdl_initPolylineMarker ()
Referenced by cdl_markPolyline().
MarkerPtr cdl_initTextMarker (int x, int y, char * string, float size, int color, int font, int width) [static]
Definition at line 2949 of file cdlmark.c.
References Marker::color, color, Marker::font, malloc(), MarkerPtr, MK_TEXT, size, Marker::str, Marker::textwidth, Marker::txsize, Marker::type, Marker::x, x, Marker::y, and y.
MarkerPtr cdl_initTextMarker () [static]
Referenced by cdl_markText().
void cdl_insertMarker (CDLPtr cdl, MarkerPtr back, MarkerPtr new) [static]
Definition at line 2291 of file cdlmark.c.
References Marker::back, CDLPtr, DLHead, DLTail, MarkerPtr, Marker::next, and tmp.
void cdl_insertMarker () [static]
Referenced by cdl_markBox(), cdl_markCircAnnuli(), cdl_markCircle(), cdl_markEllipAnnuli(), cdl_markEllipse(), cdl_markLine(), cdl_markPoint(), cdl_markPointLabel(), cdl_markPolygon(), cdl_markPolyline(), and cdl_markText().
int cdl_mapFrame (CDLPtr cdl, int frame)
Definition at line 173 of file cdlmark.c.
References a, b, c, cdl_getWCS(), CDL_LINEAR, cdl_setFrame(), cdl_setWCS(), CDLPtr, d, frame, malloc(), OK, SZ_NAME, title, tx, ty, xo, yo, z1, z2, and zt.
int cdl_markBox (CDLPtr cdl, int lx, int ly, int ux, int uy, int fill, int color)
Definition at line 533 of file cdlmark.c.
References cdl_debug, cdl_doBoxMark(), cdl_getPixRegion(), cdl_initBoxMarker(), cdl_initMarkPos(), cdl_insertMarker(), cdl_writeSubRaster(), CDLPtr, color, DLTail, ERR, fill, ly, malloc(), MarkerPtr, Marker::markpix, nx, ny, OK, pix, Marker::refpix, tmp, uchar, ux, and uy.
int cdl_markCircAnnuli (CDLPtr cdl, int x, int y, int radius, int nannuli, int sep, int color)
Definition at line 804 of file cdlmark.c.
References cdl_debug, cdl_doCircAnnuliMark(), cdl_getPixRegion(), cdl_initCircAnnMarker(), cdl_initMarkPos(), cdl_insertMarker(), cdl_writeSubRaster(), CDLPtr, color, DLTail, ERR, ly, malloc(), MarkerPtr, Marker::markpix, nannuli, nx, ny, OK, pix, radius, Marker::refpix, sep, uchar, x, and y.
int cdl_markCircle (CDLPtr cdl, int x, int y, int radius, int fill, int color)
Definition at line 739 of file cdlmark.c.
References cdl_debug, cdl_doCircleMark(), cdl_getPixRegion(), cdl_initCircleMarker(), cdl_initMarkPos(), cdl_insertMarker(), cdl_writeSubRaster(), CDLPtr, color, DLTail, ERR, fill, ly, malloc(), MarkerPtr, Marker::markpix, nx, ny, OK, pix, radius, Marker::refpix, uchar, x, and y.
int cdl_markCoordsFile (CDLPtr cdl, char * fname, int type, int size, int color, int label)
Definition at line 401 of file cdlmark.c.
References cdl_markPoint(), CDLPtr, color, ERR, i, label, OK, size, type, x, and y.
int cdl_markEllipAnnuli (CDLPtr cdl, int x, int y, int xrad, int yrad, float ang, int nannuli, int sep, int color)
Definition at line 941 of file cdlmark.c.
References ang, cdl_debug, cdl_doEllipAnnuliMark(), cdl_getPixRegion(), cdl_initEllAnnMarker(), cdl_initMarkPos(), cdl_insertMarker(), cdl_writeSubRaster(), CDLPtr, color, DLTail, ERR, ly, malloc(), MarkerPtr, Marker::markpix, max, nannuli, nx, ny, OK, pix, Marker::refpix, sep, uchar, x, xrad, y, and yrad.
int cdl_markEllipse (CDLPtr cdl, int x, int y, int xrad, int yrad, float rotang, int fill, int color)
Definition at line 872 of file cdlmark.c.
References cdl_debug, cdl_doEllipseMark(), cdl_getPixRegion(), cdl_initEllipseMarker(), cdl_initMarkPos(), cdl_insertMarker(), cdl_writeSubRaster(), CDLPtr, color, DLTail, ERR, fill, ly, malloc(), MarkerPtr, Marker::markpix, max, nx, ny, OK, pix, Marker::refpix, uchar, x, xrad, y, and yrad.
int cdl_markLine (CDLPtr cdl, int xs, int ys, int xe, int ye, int color)
Definition at line 468 of file cdlmark.c.
References ABS, cdl_debug, cdl_doLineMark(), cdl_getPixRegion(), cdl_initLineMarker(), cdl_initMarkPos(), cdl_insertMarker(), cdl_writeSubRaster(), CDLPtr, color, DLTail, ERR, L_HOLLOW, ly, malloc(), MarkerPtr, Marker::markpix, min, nx, ny, OK, pix, Marker::refpix, uchar, xe, ye, and ys.
int cdl_markPoint (CDLPtr cdl, int x, int y, int number, int size, int type, int color)
Definition at line 239 of file cdlmark.c.
References cdl_debug, cdl_doPointMark(), cdl_getPixRegion(), cdl_initMarkPos(), cdl_initPointMarker(), cdl_insertMarker(), cdl_markText(), cdl_writeSubRaster(), CDLPtr, CHARACTER_WIDTH, color, DLTail, ERR, FONT_SCALE, ly, malloc(), MarkerPtr, Marker::markpix, max, number, OK, pix, Marker::refpix, size, type, uchar, x, and y.
int cdl_markPointLabel (CDLPtr cdl, int x, int y, char 	* label, int size, int type, int color)
Definition at line 321 of file cdlmark.c.
References cdl_debug, cdl_doPointMark(), cdl_getPixRegion(), cdl_initMarkPos(), cdl_initPointLabelMarker(), cdl_insertMarker(), cdl_markText(), cdl_strlen(), cdl_writeSubRaster(), CDLPtr, color, DLTail, ERR, Marker::font, label, ly, malloc(), MarkerPtr, Marker::markpix, max, OK, pix, Marker::refpix, size, Marker::txsize, type, uchar, x, and y.
int cdl_markPolygon (CDLPtr cdl, xarray, yarray, int npts, int fill, int color)
Definition at line 601 of file cdlmark.c.
References ABS, cdl_debug, cdl_doPolygonMark(), cdl_getPixRegion(), cdl_initMarkPos(), cdl_initPolygonMarker(), cdl_insertMarker(), cdl_minmax(), cdl_writeSubRaster(), CDLPtr, color, DLTail, ERR, fill, ly, malloc(), MarkerPtr, Marker::markpix, min, npts, nx, ny, OK, pix, Marker::refpix, True, uchar, xmax, xmin, yarray, ymax, and ymin.
int cdl_markPolyline (CDLPtr cdl, int	* xarray, int * yarray, int npts, int color)
Definition at line 670 of file cdlmark.c.
References ABS, cdl_debug, cdl_doPolygonMark(), cdl_getPixRegion(), cdl_initMarkPos(), cdl_initPolylineMarker(), cdl_insertMarker(), cdl_minmax(), cdl_writeSubRaster(), CDLPtr, color, DLTail, ERR, False, ly, malloc(), MarkerPtr, Marker::markpix, min, npts, nx, ny, OK, pix, Marker::refpix, uchar, xmax, xmin, yarray, ymax, and ymin.
int cdl_markText (CDLPtr cdl, int x, int y, char * str, float size, float angle, int color)
Definition at line 1010 of file cdlmark.c.
References angle, cdl_debug, cdl_doLineInSubRas(), cdl_doTextMarker(), cdl_getPixRegion(), cdl_initMarkPos(), cdl_initTextMarker(), cdl_insertMarker(), cdl_minmax(), cdl_strlen(), cdl_writeSubRaster(), CDLPtr, CHARACTER_HEIGHT, CHARACTER_WIDTH, color, DLTail, ERR, Marker::font, FONT_HEIGHT, FONT_SCALE, FONT_SPACE, len, ly, malloc(), MarkerPtr, Marker::markpix, nx, ny, OK, pix, Marker::refpix, size, str, uchar, w, x, xmax, xmin, y, ymax, and ymin.
void cdl_minmax (int	* array, int npts, int	* amin, int * amax) [static]
Definition at line 3683 of file cdlmark.c.
References i, and npts.
void cdl_minmax ()
Referenced by cdl_markPolygon(), cdl_markPolyline(), and cdl_markText().
void cdl_printDisplayList (FILE		* fd, MarkerPtr head) [static]
Definition at line 2459 of file cdlmark.c.
References Marker::back, MarkerPtr, MK_BOX, MK_CIRCANN, MK_CIRCLE, MK_ELLIPANN, MK_ELLIPSE, MK_LINE, MK_POINT, MK_POLYGON, MK_POLYLINE, MK_TEXT, Marker::next, and Marker::type.
void cdl_printDisplayList () [static]
int cdl_redrawOverlay (CDLPtr cdl)
Definition at line 1318 of file cdlmark.c.
References cdl_debug, cdl_writeSubRaster(), CDLPtr, DLHead, ERR, Marker::lx, Marker::ly, MarkerPtr, Marker::markpix, Marker::next, Marker::nx, Marker::ny, and OK.
void cdl_removeMarker (CDLPtr cdl, MarkerPtr mk) [static]
Definition at line 2335 of file cdlmark.c.
References Marker::back, CDLPtr, DLHead, DLTail, free(), MarkerPtr, Marker::markpix, Marker::next, Marker::refpix, Marker::str, uchar, Marker::xp, and Marker::yp.
void cdl_removeMarker ()
Referenced by cdl_clearOverlay(), cdl_deleteMark(), and cdl_freeDisplayList().
void cdl_setFont (CDLPtr cdl, int font)
Definition at line 1120 of file cdlmark.c.
References cdl_setTextWidth(), CDLPtr, F_BOLD, F_FUTURA, F_GREEK, F_ROMAN, and F_TIMES.
void cdl_setFont ()
void cdl_setLineStyle (CDLPtr cdl, int style)
Definition at line 1194 of file cdlmark.c.
References CDLPtr.
void cdl_setLineStyle ()
void cdl_setLineWidth (CDLPtr cdl, int width)
Definition at line 1172 of file cdlmark.c.
References CDLPtr.
void cdl_setLineWidth ()
uchar cdl_setpixel (uchar pix, int style, int color) [static]
Definition at line 3421 of file cdlmark.c.
References color, L_DASHED, L_DOTDASH, L_DOTTED, pix, and uchar.
uchar cdl_setpixel () [static]
Referenced by cdl_drawDashVec().
void cdl_setTextWidth (CDLPtr cdl, int width)
Definition at line 1149 of file cdlmark.c.
References CDLPtr.
void cdl_setTextWidth ()
int cdl_strlen (char	* str, float txtsize, int txtfont) [static]
Definition at line 3712 of file cdlmark.c.
References CHARACTER_END, CHARACTER_HEIGHT, CHARACTER_START, CHARACTER_WIDTH, F_FUTURA, F_GREEK, F_ROMAN, F_TIMES, FONT_SCALE, FONT_SPACE, futwid, gchwid, i, len, size, str, and timwid.
int cdl_strlen () [static]
Referenced by cdl_markPointLabel(), and cdl_markText().
Variable Documentation
unsigned bitmask[]
Initial value:.nf
 { 0,
        01, 03, 07,
        017, 037, 077,
        0177, 0377, 0777,
        01777, 03777, 07777,
        017777, 037777, 077777,
        0177777, 0377777, 0777777,
        01777777, 03777777, 07777777,
        017777777, 037777777, 077777777,
        0177777777, 0377777777, 0777777777,
        01777777777, 03777777777, 07777777777,
        017777777777, 037777777777
}
Definition at line 3793 of file cdlmark.c.
Referenced by bitupk().
int cdl_debug
Definition at line 152 of file cdlmark.c.
uchar* DLFBPix[MAX_FRAMES]
Definition at line 137 of file cdlmark.c.
int DLFlag[]
Initial value:.nf
 {
        0, 0, 0, 0,
        0, 0, 0, 0
         }
Definition at line 133 of file cdlmark.c.
MarkerPtr DLHead[MAX_FRAMES]
Definition at line 131 of file cdlmark.c.
Referenced by cdl_clearOverlay(), cdl_deleteMark(), cdl_displayPix(), cdl_insertMarker(), cdl_open(), cdl_redrawOverlay(), and cdl_removeMarker().
MarkerPtr DLTail[MAX_FRAMES]
Definition at line 132 of file cdlmark.c.
Referenced by cdl_clearOverlay(), cdl_insertMarker(), cdl_markBox(), cdl_markCircAnnuli(), cdl_markCircle(), cdl_markEllipAnnuli(), cdl_markEllipse(), cdl_markLine(), cdl_markPoint(), cdl_markPointLabel(), cdl_markPolygon(), cdl_markPolyline(), cdl_markText(), cdl_open(), and cdl_removeMarker().
Author
Generated automatically by Doxygen for imcat from the source code.