cdlProto.h
NAME
cdlProto.h -
SYNOPSIS
Functions
IMDPtr imd_open ()
int imd_setFBConfig ()
int imd_writeDisplay ()
int imd_readDisplay ()
int imd_setFrame ()
int imd_setCursor ()
int imd_readCursor ()
int imd_close ()
int imd_readSubRaster ()
int imd_writeSubRaster ()
int imd_clearFrame ()
int imd_setWCS ()
int imd_getWCS ()
int com_writeData ()
int com_readData ()
int com_setFBConfig ()
int com_readCursor ()
int com_setCursor ()
int com_setFrame ()
int com_writeWCS ()
int com_readWCS ()
int com_eraseFrame ()
int com_setDebug ()
PSImage * eps_init ()
void eps_print ()
void eps_close ()
void eps_setPage ()
void eps_setCmap ()
void eps_setCompress ()
void eps_setColorType ()
void eps_setLabel ()
void eps_setTransform ()
void eps_setCorners ()
void eps_getImageSize ()
void eps_getImagePos ()
Function Documentation
int com_eraseFrame ()
Referenced by imd_clearFrame().
int com_readCursor ()
Referenced by imd_readCursor().
int com_readData ()
Referenced by imd_readLine().
int com_readWCS ()
Referenced by imd_getWCS().
int com_setCursor ()
Referenced by imd_setCursor().
int com_setDebug ()
Referenced by cdl_setDebug().
int com_setFBConfig ()
Referenced by imd_getFBConfig(), and imd_setFBConfig().
int com_setFrame ()
Referenced by imd_setFrame().
int com_writeData ()
Referenced by imd_writeLine().
int com_writeWCS ()
Referenced by imd_setWCS().
void eps_close ()
Referenced by cdl_printPix(), and cdl_printPixToFile().
void eps_getImagePos ()
void eps_getImageSize ()
PSImage* eps_init ()
Definition at line 154 of file eps.c.
References EPS_AUTOSCALE, EPS_GRAYSCALE, EPS_LETTER, EPS_PORTRAIT, eps_setPage(), i, MAX_LENLABEL, NoCompression, pixbuf, ps(), SZ_EPSBUF, and uchar.
Referenced by cdl_printPix(), and cdl_printPixToFile().
void eps_print ()
Referenced by cdl_printPix(), and cdl_printPixToFile().
void eps_setCmap ()
Referenced by cdl_printPix(), and cdl_printPixToFile().
void eps_setColorType ()
Referenced by cdl_printPix(), and cdl_printPixToFile().
void eps_setCompress ()
void eps_setCorners ()
Referenced by cdl_printPix(), and cdl_printPixToFile().
void eps_setLabel ()
Referenced by cdl_printPix(), and cdl_printPixToFile().
void eps_setPage ()
Referenced by eps_init().
void eps_setTransform ()
int imd_clearFrame ()
Referenced by cdl_clearFrame(), and imd_displayImage().
int imd_close ()
Referenced by cdl_close().
int imd_getWCS ()
Referenced by cdl_getWCS().
IMDPtr imd_open ()
Referenced by cdl_open().
int imd_readCursor ()
Referenced by cdl_readCursor().
int imd_readDisplay ()
int imd_readSubRaster ()
Referenced by cdl_readSubRaster(), imd_readFrameBuffer(), and imd_readImage().
int imd_setCursor ()
Referenced by cdl_setCursor().
int imd_setFBConfig ()
Referenced by cdl_open(), cdl_setFBConfig(), and imd_displayImage().
int imd_setFrame ()
Referenced by cdl_open(), cdl_setFrame(), and imd_displayImage().
int imd_setWCS ()
Referenced by cdl_setWCS(), and imd_displayImage().
int imd_writeDisplay ()
int imd_writeSubRaster ()
Referenced by cdl_writeSubRaster().
Author
Generated automatically by Doxygen for imcat from the source code.