.TH "cfftb1.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfftb1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcfftb1_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *c__, \fBreal\fP *ch, \fBreal\fP *wa, \fBinteger\fP *ifac)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cfftb1_ (\fBinteger\fP * n, \fBreal\fP * c__, \fBreal\fP * ch, \fBreal\fP * wa, \fBinteger\fP * ifac)"
.PP
Definition at line 9 of file cfftb1.c.
.PP
References integer, n, nf, passb2_(), passb3_(), passb4_(), passb5_(), passb_(), and real.
.PP
Referenced by cfftb_().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
