cfftb1.c
NAME
cfftb1.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int cfftb1_ (integer *n, real *c__, real *ch, real *wa, integer *ifac)
Function Documentation
int cfftb1_ (integer * n, real * c__, real * ch, real * wa, integer * ifac)
Definition at line 9 of file cfftb1.c.
References integer, n, nf, passb2_(), passb3_(), passb4_(), passb5_(), passb_(), and real.
Referenced by cfftb_().
Author
Generated automatically by Doxygen for imcat from the source code.