cfftf1.c
NAME
cfftf1.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int cfftf1_ (integer *n, real *c__, real *ch, real *wa, integer *ifac)
Function Documentation
int cfftf1_ (integer * n, real * c__, real * ch, real * wa, integer * ifac)
Definition at line 9 of file cfftf1.c.
References integer, n, nf, passf2_(), passf3_(), passf4_(), passf5_(), passf_(), and real.
Referenced by cfftf_().
Author
Generated automatically by Doxygen for imcat from the source code.