cffti.c
NAME
cffti.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int cffti_ (integer *n, real *wsave)
Function Documentation
int cffti_ (integer * n, real * wsave)
Definition at line 9 of file cffti.c.
References cffti1_(), integer, n, and real.
Referenced by forward_cfft(), forward_fft(), inverse_cfft(), inverse_fft(), main(), and MAIN__().
Author
Generated automatically by Doxygen for imcat from the source code.