.TH "cffti.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cffti.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcffti_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *wsave)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cffti_ (\fBinteger\fP * n, \fBreal\fP * wsave)"
.PP
Definition at line 9 of file cffti.c.
.PP
References cffti1_(), integer, n, and real.
.PP
Referenced by forward_cfft(), forward_fft(), inverse_cfft(), inverse_fft(), main(), and MAIN__().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
