.TH "cfftb.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfftb.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcfftb_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *c__, \fBreal\fP *wsave)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cfftb_ (\fBinteger\fP * n, \fBreal\fP * c__, \fBreal\fP * wsave)"
.PP
Definition at line 9 of file cfftb.c.
.PP
References cfftb1_(), integer, n, and real.
.PP
Referenced by inverse_cfft(), inverse_fft(), main(), and MAIN__().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
