cfftb.c
NAME
cfftb.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int cfftb_ (integer *n, real *c__, real *wsave)
Function Documentation
int cfftb_ (integer * n, real * c__, real * wsave)
Definition at line 9 of file cfftb.c.
References cfftb1_(), integer, n, and real.
Referenced by inverse_cfft(), inverse_fft(), main(), and MAIN__().
Author
Generated automatically by Doxygen for imcat from the source code.