cfftf.c
NAME
cfftf.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int cfftf_ (integer *n, real *c__, real *wsave)
Function Documentation
int cfftf_ (integer * n, real * c__, real * wsave)
Definition at line 9 of file cfftf.c.
References cfftf1_(), integer, n, and real.
Referenced by forward_cfft(), forward_fft(), main(), and MAIN__().
Author
Generated automatically by Doxygen for imcat from the source code.