changesex.c
NAME
changesex.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
#include 'changesex.h'
Defines
#define usage '\n\n\n\NAME\n\	changesex - switch byte order of a FITS file\n\\n\SYNOPSIS\n\	changesex [-u] [-n]\n\\n\DESCRIPTION\n\	The filter \'changesex\' swaps the byte order in a fits image.\n\\n\	Imcat commands can work with either big- or little-endian images.\n\	Since 2/99 imcat written images contain a header value\n\	with keyword BYTEORDR whose value can be either BIG_ENDIAN or\n\	LITTLE_ENDIAN, and the value of which is set by the presence\n\	or absence of the environment variable IMCATSWAPFITSBYTES.\n\	If IMCATSWAPFITSBYTES is set then the image is stored in\n\	non-native byte order.\n\\n\	Non-imcat images are assumed to be BIG_ENDIAN, while pre 2/99\n\	imcat images are assumed to be in the native byte order.\n\	If you have set IMCATSWAPFITSBYTES then you will need to filter\n\	old style images through 'changesex' to bring them into non-native order.\n\\n\	Use 'changesex -n' to force images with BYTEORDR=LITTLE_ENDIAN\n\	to BIG_ENDIAN format for compatibility with non-imcat software.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	changesex - switch byte order of a FITS file\n\\n\SYNOPSIS\n\	changesex [-u] [-n]\n\\n\DESCRIPTION\n\	The filter \'changesex\' swaps the byte order in a fits image.\n\\n\	Imcat commands can work with either big- or little-endian images.\n\	Since 2/99 imcat written images contain a header value\n\	with keyword BYTEORDR whose value can be either BIG_ENDIAN or\n\	LITTLE_ENDIAN, and the value of which is set by the presence\n\	or absence of the environment variable IMCATSWAPFITSBYTES.\n\	If IMCATSWAPFITSBYTES is set then the image is stored in\n\	non-native byte order.\n\\n\	Non-imcat images are assumed to be BIG_ENDIAN, while pre 2/99\n\	imcat images are assumed to be in the native byte order.\n\	If you have set IMCATSWAPFITSBYTES then you will need to filter\n\	old style images through 'changesex' to bring them into non-native order.\n\\n\	Use 'changesex -n' to force images with BYTEORDR=LITTLE_ENDIAN\n\	to BIG_ENDIAN format for compatibility with non-imcat software.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file changesex.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 44 of file changesex.c.
References add_comment(), argsinit(), byteswapline(), error_exit, exit(), fitsheader::extpixtype, f, fits, flag, getflag(), i, fitsheader::n, N1, N2, fitsheader::ndim, pixsize(), readfitsheader(), usage, writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.