chisquare.c
NAME
chisquare.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
#include 'Ffunc.h'
#include 'utils/gaussdev.h'
#include 'tcl.h'
Defines
#define usage '\nNAME\n\	chisquare\n\\n\SYNOPSIS\n\	chisquare obscat\n\\n\DESCRIPTION\n\	chisquare finds a minimum chi-squared solution for a set of three observations\n\	given a starting point (possible generated by laplace3).\n\\n\	It does this by generating a cloud of phase-points x[6] around the initial\n\	solution and computes, for each point a chi-squared and then fits this\n\	to a second order polynomial in dx[6]. The ML solution and the curvature\n\	matrix are then read off the resulting output file.\n\\n\	chisquare reads an lc format catalog from stdin containing the\n\	a preliminary solution ra[3], va[3] and an estimate of the uncertainty\n\	in the distance, sigmad and d. These are generated by laplace3.\n\\n\	It then reads a set of observations from obscat, and for each phase-point\n\	computes the chi-squared statistic.\n\\n\SEE ALSO\n\	makeobs_inertial makeobs_circ laplace3 tcl_evolve r2n chisquare\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	chisquare\n\\n\SYNOPSIS\n\	chisquare obscat\n\\n\DESCRIPTION\n\	chisquare finds a minimum chi-squared solution for a set of three observations\n\	given a starting point (possible generated by laplace3).\n\\n\	It does this by generating a cloud of phase-points x[6] around the initial\n\	solution and computes, for each point a chi-squared and then fits this\n\	to a second order polynomial in dx[6]. The ML solution and the curvature\n\	matrix are then read off the resulting output file.\n\\n\	chisquare reads an lc format catalog from stdin containing the\n\	a preliminary solution ra[3], va[3] and an estimate of the uncertainty\n\	in the distance, sigmad and d. These are generated by laplace3.\n\\n\	It then reads a set of observations from obscat, and for each phase-point\n\	computes the chi-squared statistic.\n\\n\SEE ALSO\n\	makeobs_inertial makeobs_circ laplace3 tcl_evolve r2n chisquare\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 9 of file chisquare.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 37 of file chisquare.c.
References a, alpha, assign(), b, c, C, chi2(), d, dr, dx, exit(), fprintvec(), gaussdev(), i, indx, invertmatrix(), iota, ipf, j, length(), M, myludcmp(), n, nobs, nt, phi, printvec(), r, ra, re, rho, scale(), sigma, t, tcl(), tmp, tmpvec, usage, v, and va.
Author
Generated automatically by Doxygen for imcat from the source code.