.TH "cilist" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cilist \- 
.SH SYNOPSIS
.br
.PP
\fC#include <f2c.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBflag\fP \fBcierr\fP"
.br
.ti -1c
.RI "\fBftnint\fP \fBciunit\fP"
.br
.ti -1c
.RI "\fBflag\fP \fBciend\fP"
.br
.ti -1c
.RI "char * \fBcifmt\fP"
.br
.ti -1c
.RI "\fBftnint\fP \fBcirec\fP"
.br
.ti -1c
.RI "char * \fBcifmt\fP"
.br
.ti -1c
.RI "char * \fBcifmt\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBflag\fP \fBcilist::ciend\fP"
.PP
Definition at line 54 of file myf2c.h.
.SS "\fBflag\fP \fBcilist::cierr\fP"
.PP
Definition at line 52 of file myf2c.h.
.SS "char* \fBcilist::cifmt\fP"
.PP
Definition at line 55 of file myf2c.h.
.SS "char* \fBcilist::cifmt\fP"
.PP
Definition at line 88 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBcilist::cifmt\fP"
.PP
Definition at line 49 of file fftpack_c/f2c.h.
.SS "\fBftnint\fP \fBcilist::cirec\fP"
.PP
Definition at line 56 of file myf2c.h.
.SS "\fBftnint\fP \fBcilist::ciunit\fP"
.PP
Definition at line 53 of file myf2c.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
