circimfromcat.c
NAME
circimfromcat.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <limits.h>
#include 'imlib/fits.h'
#include 'utils/error.h'
#include 'utils/arrays.h'
Functions
main (int argc, char *argv[])
Variables
char * usage
Function Documentation
main (int argc, char * argv[])
Definition at line 39 of file circimfromcat.c.
References add_comment(), allocFloatArray(), dr, error_exit, exit(), f, F(), fits, FLOAT_PIXTYPE, ix, lcpipe, N, new2Dfitsheader(), r, usage, write2Dfloatimage(), x, and y.
Variable Documentation
char* usage
Initial value:.nf
 '\n\
NAME\n\
  circimfromcat --- generate a circularly symmetric image\n\
\n\
SYNOPSIS\n\
  circimfromcat [options]\n\
\n\
DESCRIPTION\n\
  'circimfromcat' reads an lc-format catalogue from standard\n\
  input containing at least a single scalar (default name F)\n\
  which is interpreted as a set uf uniformly spaced samples\n\
  of a function F(r), and generates a square circularly\n\
  symmetric 2-D image f(x,y) = F(r = sqrt(x^2 + y^2)).\n\
  Options are:\n\
    -d dr # spacing of input samples in pixels (1.0)\n\
    -n N # size of output image (512)\n\
    -N nrmax # input array size (10000)\n\
    -F Fname # name for the input value\n\
\n\
AUTHOR\n\
  Nick Kaiser --- kaiser@ifa.hawaii.edu\n\
\n'
Definition at line 15 of file circimfromcat.c.
Author
Generated automatically by Doxygen for imcat from the source code.