cleancat.c
NAME
cleancat.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../../utils/error.h'
#include '../../catlib/cat.h'
#include 'grid.h'
Defines
#define usage '\n\n\NAME\n\	cleancat - remove objects with brighter close neighbours\n\\n\SYNOPSIS\n\	cleancat [options....] dmax\n\		-u		# print this man page\n\		-x xname 	# specify name for coords (x)\n\		-m magname 	# specify name for magnitude (mag)\n\\n\DESCRIPTION\n\ 'cleancat' reads a catalogue from stdin and writes to stdout\n\	a catalogue containing only those objects from the input\n\	catalogue which have no brighter neighbours within distance\n\	dmax.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
#define BIG_POS 1.e100
#define BIG_NEG -1.e100
Functions
double sep2 (object *obj1, object *obj2, int xindex)
main (int argc, char *argv[])
Define Documentation
#define BIG_NEG -1.e100
Definition at line 36 of file cleancat.c.
Referenced by findpeak(), and main().
#define BIG_POS 1.e100
Definition at line 35 of file cleancat.c.
Referenced by main().
#define usage '\n\n\NAME\n\	cleancat - remove objects with brighter close neighbours\n\\n\SYNOPSIS\n\	cleancat [options....] dmax\n\		-u		# print this man page\n\		-x xname 	# specify name for coords (x)\n\		-m magname 	# specify name for magnitude (mag)\n\\n\DESCRIPTION\n\ 'cleancat' reads a catalogue from stdin and writes to stdout\n\	a catalogue containing only those objects from the input\n\	catalogue which have no brighter neighbours within distance\n\	dmax.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file cleancat.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 38 of file cleancat.c.
References addargscomment(), object::addrlist, allocgrid(), allocobjectcontents(), BIG_NEG, BIG_POS, cathead, d, item::dim, dmax, error_exit, exit(), getcatipfiletype(), getgridcoords(), getneighbours(), getobjectitem(), getobjectitemindex(), getobjects(), i, item::itype, ix, j, MAX_NEIGHBOURS, item::ndim, newobject(), object::next, NUM_TYPE, readcathead(), readobject(), sep2(), setcatopfiletype(), setgridsize(), usage, writecathead(), writeobject(), x, xmax, and xmin.
double sep2 (object * obj1, object * obj2, int xindex)
Definition at line 172 of file cleancat.c.
References object::addrlist, dx, and dy.
Author
Generated automatically by Doxygen for imcat from the source code.