.TH "cllist" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cllist \- 
.SH SYNOPSIS
.br
.PP
\fC#include <f2c.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBflag\fP \fBcerr\fP"
.br
.ti -1c
.RI "\fBftnint\fP \fBcunit\fP"
.br
.ti -1c
.RI "char * \fBcsta\fP"
.br
.ti -1c
.RI "char * \fBcsta\fP"
.br
.ti -1c
.RI "char * \fBcsta\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBflag\fP \fBcllist::cerr\fP"
.PP
Definition at line 84 of file myf2c.h.
.SS "char* \fBcllist::csta\fP"
.PP
Definition at line 86 of file myf2c.h.
.SS "char* \fBcllist::csta\fP"
.PP
Definition at line 119 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBcllist::csta\fP"
.PP
Definition at line 80 of file fftpack_c/f2c.h.
.SS "\fBftnint\fP \fBcllist::cunit\fP"
.PP
Definition at line 85 of file myf2c.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
