colormaps.c
NAME
colormaps.c -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
Defines
#define CMAP_INDEX_MAX 5
Functions
int getcolormap (float **lp, float **rp, float **gp, float **bp, float *contra, float *bright, int *n, int index)
int getrgbfromcmap (float **r, float **g, float **b, int n, int cmapindex)
Define Documentation
#define CMAP_INDEX_MAX 5
Definition at line 8 of file colormaps.c.
Referenced by getcolormap().
Function Documentation
int getcolormap (float ** lp, float ** rp, float ** gp, float ** bp, float * contra, float * bright, int * n, int index)
Definition at line 11 of file colormaps.c.
References b, c, cmap, CMAP_INDEX_MAX, error_exit, g(), l, n, and r.
Referenced by getrgbfromcmap(), and main().
int getrgbfromcmap (float ** r, float ** g, float ** b, int n, int cmapindex)
Definition at line 52 of file colormaps.c.
References b, f, g(), getcolormap(), i, j, l, m, n, and r.
Referenced by set_shades().
Author
Generated automatically by Doxygen for imcat from the source code.