color.h
NAME
color.h -
SYNOPSIS
Defines
#define Q0_MAX 1
#define A_MAX 4
Functions
void setcolorscheme (void)
void set_shades (void)
int color_index (int i, int j)
double gray (int i, int j)
Define Documentation
#define A_MAX 4
Definition at line 6 of file color.h.
Referenced by myworkproc1(), newslidervalue(), set_shades(), and setcolorscheme().
#define Q0_MAX 1
Definition at line 5 of file color.h.
Referenced by newslidervalue(), and set_shades().
Function Documentation
int color_index (int i, int j)
Referenced by make_pixmap().
double gray (int i, int j)
Referenced by printall(), and printselection().
void set_shades (void)
Definition at line 76 of file back.c.
void setcolorscheme (void)
Definition at line 59 of file ximcolor.c.
Referenced by alloc_shades().
Author
Generated automatically by Doxygen for imcat from the source code.