colorbox.c
NAME
colorbox.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	colorbox - generate example color image\n\\n\SYNOPSIS\n\	colourbox N\n\\n\DESCRIPTION\n\	\'colourbox\' generates a N x N 2-colour image which spans the spectrum\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Variables
short * f
int ncolours
Define Documentation
#define usage '\n\n\n\NAME\n\	colorbox - generate example color image\n\\n\SYNOPSIS\n\	colourbox N\n\\n\DESCRIPTION\n\	\'colourbox\' generates a N x N 2-colour image which spans the spectrum\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file colorbox.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 29 of file colorbox.c.
References add_comment(), appendcomment(), fitsheader::bscaling, color, COM_LENGTH, error_exit, exit(), fitsheader::extpixtype, f, fits, i, fitsheader::intpixtype, j, fitsheader::linebuffer, fitsheader::n, N, ncolours, fitsheader::ndim, newtextcomment(), fitsheader::opstream, SHORT_PIXTYPE, usage, writefitsheader(), writefitsline(), and writefitstail().
Variable Documentation
short* f [static]
Definition at line 26 of file colorbox.c.
int ncolours [static]
Definition at line 27 of file colorbox.c.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.