colorize.c
NAME
colorize.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
#include '../utils/colormaps.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	colorize --- convert gray fits file to rgb colormapped version\n\\n\SYNOPSIS\n\	colorize colormapindex [options...] \n\\n\DESCRIPTION\n\	If \'colorize\' reads a 2-dimensional fits file f[N2][N1] from standard\n\	input and writes a 3-dimensional rgb version f[3][N2][N1] with\n\	f[0][][] = r[][], f[1][][] = g[][], f[2][][] = b[][].\n\\n\	If it reads a 3 dimensional image f[N3][N2][N1] it generates a four\n\	dimensional version f[N3][3][N2][N1] -- i.e. a stream of 3-D rgb\n\	images.\n\\n\	The rgb colors are computed by linear interpolation on a\n\	color ramp.\n\\n\	Options are:\n\		-f fmin fmax	# limits for input image (0, 255)\n\		-a		# use autoscaling\n\		-p bitpix	# output pixtype (8) \n\\n\	There are currently three colormaps available (0,1,2).\n\\n\BUGS\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define FRAC_MAX 0.9999999999999
Functions
int main (int argc, char *argv[])
Define Documentation
#define FRAC_MAX 0.9999999999999
Definition at line 47 of file colorize.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	colorize --- convert gray fits file to rgb colormapped version\n\\n\SYNOPSIS\n\	colorize colormapindex [options...] \n\\n\DESCRIPTION\n\	If \'colorize\' reads a 2-dimensional fits file f[N2][N1] from standard\n\	input and writes a 3-dimensional rgb version f[3][N2][N1] with\n\	f[0][][] = r[][], f[1][][] = g[][], f[2][][] = b[][].\n\\n\	If it reads a 3 dimensional image f[N3][N2][N1] it generates a four\n\	dimensional version f[N3][3][N2][N1] -- i.e. a stream of 3-D rgb\n\	images.\n\\n\	The rgb colors are computed by linear interpolation on a\n\	color ramp.\n\\n\	Options are:\n\		-f fmin fmax	# limits for input image (0, 255)\n\		-a		# use autoscaling\n\		-p bitpix	# output pixtype (8) \n\\n\	There are currently three colormaps available (0,1,2).\n\\n\BUGS\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file colorize.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 49 of file colorize.c.
References add_comment(), allocFloatArray(), argsinit(), c, color, copyfitsheader(), error_exit, exit(), fitsheader::extpixtype, f, flag, FLAG_ARG, fmin, FRAC_MAX, getargf(), getargi(), getcolormap(), getflag(), fitsheader::n, N1, N2, fitsheader::ndim, nextargtype(), readfitsheader(), readfitsplane(), usage, writefitsheader(), writefitsline(), writefitstail(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.