combinestamps.c
NAME
combinestamps.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include 'combine_stuff.h'
Defines
#define usage '\n\n\n\NAME\n\	combinestamps --- take mean, median etc of a stack of images\n\\n\SYNOPSIS\n\	combinestamps [options...]\n\\n\DESCRIPTION\n\	'combinestamps' reads a set of Nim images in the form of a\n\	Nim x N2 x N1 fits image (as created by 'makestamps' for\n\	instance) and performs some kind of\n\	average. By default it takes the median. Options are:\n\		-m	# take mean instead\n\		-a clip	# take average clipping at +- clip * sigma \n\	Input images must have identical sizes. Combinestamps is\n\	functionally very similar to 'combineimages', but is unsuitable\n\	for large images as it reads all of the images into memory.\n\	However, it is therefore capable for reading very large\n\	*numbers* of images unlike 'combinimages' which reads images\n\	line by line and must therefore have a file open for each\n\	input image.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define MEAN_MODE 0
#define MEDIAN_MODE 1
#define ASG_MODE 2
Functions
int main (int argc, char *argv[])
Define Documentation
#define ASG_MODE 2
Definition at line 41 of file combinestamps.c.
Referenced by main().
#define MEAN_MODE 0
Definition at line 39 of file combinestamps.c.
Referenced by main().
#define MEDIAN_MODE 1
Definition at line 40 of file combinestamps.c.
#define usage '\n\n\n\NAME\n\	combinestamps --- take mean, median etc of a stack of images\n\\n\SYNOPSIS\n\	combinestamps [options...]\n\\n\DESCRIPTION\n\	'combinestamps' reads a set of Nim images in the form of a\n\	Nim x N2 x N1 fits image (as created by 'makestamps' for\n\	instance) and performs some kind of\n\	average. By default it takes the median. Options are:\n\		-m	# take mean instead\n\		-a clip	# take average clipping at +- clip * sigma \n\	Input images must have identical sizes. Combinestamps is\n\	functionally very similar to 'combineimages', but is unsuitable\n\	for large images as it reads all of the images into memory.\n\	However, it is therefore capable for reading very large\n\	*numbers* of images unlike 'combinimages' which reads images\n\	line by line and must therefore have a file open for each\n\	input image.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file combinestamps.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 43 of file combinestamps.c.
References add_comment(), allocFloatArray(), ASG_MODE, avsigclip(), clip, error_exit, f, fits, FLOAT_MAGIC, ipf, fitsheader::ipstream, mean(), MEAN_MODE, median(), MEDIAN_MODE, fitsheader::n, N1, N2, fitsheader::ndim, readfitsheader(), readfitsline(), usage, write2Dfloatimage(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.