combineimages.c
NAME
combineimages.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
#include 'avgpixstack.h'
Defines
#define usage '\n\n\n\NAME\n\	combineimages - create mean, median, avsigclip of a stack of images\n\\n\SYNOPSIS\n\	combineimages [options....] infile1 infile2....\n\		-a clip		# reject pixels with |f - f_median| > clip * sigma\n\		-r r		# output the r'th image\n\		-s		# get sigmas from fits headers\n\		-e		# get sigmas from exposure map images\n\		-f f1 f2	# allow all pixels with f1 < (f - fmedian) / |fmedian| < f2\n\		-v		# verbose mode.\n\		-o name		# output average (.fits) and exposure (.exp) images\n\		-O name		# output average (.fits), exposure (.exp) and bad planes (.bp) images\n\		-F		# force 4 byte float format output image\n\		-I bscale bzero	# force 2-byte output with b-scaling\n\		-m bscale	# bscale factor for sigma image (0.0001)\n\\n\DESCRIPTION\n\	\'combineimages\' reads a collection of fits images (which\n\	must have identical sizes) and writes an average image\n\	to stdout. Default behaviour is to calculate the median.\n\\n\	Use -a option for various types of averaging.\n\	With -a option we do avsigclip style rejection, rejecting pixels with\n\	f - fmedian > clip * sigma, and take the weighted average of what's left.\n\	With negative clip we take straight mean.\n\\n\	With -s option we read sigma's from 'SIGMA' value in fits header.\n\	With -e option we get sigma's from exposure map images containing 1/sigma^2.\n\	These images must have the same names as the source images, but with\n\	suffix '.exp'.\n\\n\	With (-s or -e) and -a options we reject pixels which differ from\n\	the median by more than clip * sigma and also lie outside the range\n\	f1 < (f - fmedian) / |fmedian| < f2. The extra tolerance for large\n\	|fmedian| values is to allow for variations in the shapes of stars\n\	due to seeing variations. Sensible values for a range of 3:5 in seeing\n\	(eg 0.6'' - 1.0'') are f1 = -0.5, f2 = 1.0. \n\\n\	With (-s or -e) but without the -a option we take the weighted mean\n\	with no rejection.\n\\n\	If sigma values are supplied (with -s or -e options) then the pixels\n\	which survive selection are averaged with weight proportional\n\	to 1 / sigma^2.\n\\n\	With '-o foo' option (and -s or -e) we output two images:\n\		foo.fits	# the average image\n\		foo.exp		# the exposure map = sum 1/sigma^2 \n\\n\	With '-O foo' option (and -s or -e) we output three images:\n\		foo.fits	# the average image\n\		foo.exp		# the exposure map = sum 1/sigma^2 \n\		foo.bp		# bad-planes image: n'th bit set if n'th image rejected\n\\n\	With -r option we output the pixel value of a certain rank.\n\	With rank = n and n > 0 we output the n'th lowest image, unless\n\	there are fewer than n non-MAGIC values in which case we output\n\	the highest pixel.\n\	With rank = -n and n > 0 we output the n'th highest image, unless\n\	there are fewer than n non-MAGIC values in which case we output\n\	the lowest pixel.\n\\n\	With -v option we print the SIGMA values to stderr.\n\	Use -F option to generate float format image -- otherwise\n\	we inherit the value from the first input image.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define MEDIAN_MODE 0
#define STRAIGHT_AVG_MODE 1
#define WEIGHTED_AVG_MODE 2
#define AVSIGCLIP_MODE 3
#define RANK_MODE 4
#define BATCH_SIZE 64
Functions
int main (int argc, char *argv[])
Define Documentation
#define AVSIGCLIP_MODE 3
Definition at line 89 of file combineimages.c.
Referenced by main().
#define BATCH_SIZE 64
Definition at line 92 of file combineimages.c.
Referenced by main().
#define MEDIAN_MODE 0
Definition at line 86 of file combineimages.c.
Referenced by main().
#define RANK_MODE 4
Definition at line 90 of file combineimages.c.
Referenced by main().
#define STRAIGHT_AVG_MODE 1
Definition at line 87 of file combineimages.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	combineimages - create mean, median, avsigclip of a stack of images\n\\n\SYNOPSIS\n\	combineimages [options....] infile1 infile2....\n\		-a clip		# reject pixels with |f - f_median| > clip * sigma\n\		-r r		# output the r'th image\n\		-s		# get sigmas from fits headers\n\		-e		# get sigmas from exposure map images\n\		-f f1 f2	# allow all pixels with f1 < (f - fmedian) / |fmedian| < f2\n\		-v		# verbose mode.\n\		-o name		# output average (.fits) and exposure (.exp) images\n\		-O name		# output average (.fits), exposure (.exp) and bad planes (.bp) images\n\		-F		# force 4 byte float format output image\n\		-I bscale bzero	# force 2-byte output with b-scaling\n\		-m bscale	# bscale factor for sigma image (0.0001)\n\\n\DESCRIPTION\n\	\'combineimages\' reads a collection of fits images (which\n\	must have identical sizes) and writes an average image\n\	to stdout. Default behaviour is to calculate the median.\n\\n\	Use -a option for various types of averaging.\n\	With -a option we do avsigclip style rejection, rejecting pixels with\n\	f - fmedian > clip * sigma, and take the weighted average of what's left.\n\	With negative clip we take straight mean.\n\\n\	With -s option we read sigma's from 'SIGMA' value in fits header.\n\	With -e option we get sigma's from exposure map images containing 1/sigma^2.\n\	These images must have the same names as the source images, but with\n\	suffix '.exp'.\n\\n\	With (-s or -e) and -a options we reject pixels which differ from\n\	the median by more than clip * sigma and also lie outside the range\n\	f1 < (f - fmedian) / |fmedian| < f2. The extra tolerance for large\n\	|fmedian| values is to allow for variations in the shapes of stars\n\	due to seeing variations. Sensible values for a range of 3:5 in seeing\n\	(eg 0.6'' - 1.0'') are f1 = -0.5, f2 = 1.0. \n\\n\	With (-s or -e) but without the -a option we take the weighted mean\n\	with no rejection.\n\\n\	If sigma values are supplied (with -s or -e options) then the pixels\n\	which survive selection are averaged with weight proportional\n\	to 1 / sigma^2.\n\\n\	With '-o foo' option (and -s or -e) we output two images:\n\		foo.fits	# the average image\n\		foo.exp		# the exposure map = sum 1/sigma^2 \n\\n\	With '-O foo' option (and -s or -e) we output three images:\n\		foo.fits	# the average image\n\		foo.exp		# the exposure map = sum 1/sigma^2 \n\		foo.bp		# bad-planes image: n'th bit set if n'th image rejected\n\\n\	With -r option we output the pixel value of a certain rank.\n\	With rank = n and n > 0 we output the n'th lowest image, unless\n\	there are fewer than n non-MAGIC values in which case we output\n\	the highest pixel.\n\	With rank = -n and n > 0 we output the n'th highest image, unless\n\	there are fewer than n non-MAGIC values in which case we output\n\	the lowest pixel.\n\\n\	With -v option we print the SIGMA values to stderr.\n\	Use -F option to generate float format image -- otherwise\n\	we inherit the value from the first input image.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file combineimages.c.
#define WEIGHTED_AVG_MODE 2
Definition at line 88 of file combineimages.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 95 of file combineimages.c.
References add_comment(), APS_MEDIAN, APS_RANK, APS_STRAIGHT_AVERAGE, APS_WEIGHTED_AVERAGE, argsinit(), avgpixstack(), AVSIGCLIP_MODE, BATCH_SIZE, fitsheader::bscale, fitsheader::bscaling, fitsheader::bzero, c, clip, copyfitsheader(), error_exit, fitsheader::extpixtype, fits, flag, FLAG_ARG, FLOAT_MAGIC, FLOAT_PIXTYPE, getargf(), getargi(), getargs(), getcommentbyname(), getflag(), getnumericvalue(), INT_PIXTYPE, fitsheader::intpixtype, ipf, MEDIAN_MODE, fitsheader::n, N1, N2, fitsheader::ndim, nextargtype(), opmode, fitsheader::opstream, pix, RANK_MODE, readfitsheader(), readfitsline(), SHORT_PIXTYPE, sigma, STRAIGHT_AVG_MODE, UCHAR_PIXTYPE, usage, verbose, WEIGHTED_AVG_MODE, writefitsheader(), writefitsline(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.