combine_stuff.c
NAME
combine_stuff.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../utils/error.h'
#include '../utils/stats_stuff.h'
#include 'combine_stuff.h'
#include '../imlib/fits.h'
Functions
int thefloatcmp ()
float rankedimage (float *f, int nel, int rank)
float median (float *f, int nel)
float mean (float *f, int nel)
float avsigclip (float *f, int nel, float clip)
int thefloatcmp (float *s1, float *s2)
float avsigclip2 (float *f, float *sigma, int nel, float clip, float frac1, float frac2, float *sigmaout)
float getsigma (float *sigmavec, int nel)
Function Documentation
float avsigclip (float * f, int nel, float clip)
Definition at line 71 of file combine_stuff.c.
References clip, error_exit, f, FLOAT_MAGIC, i, median(), sigma, and thefloatcmp().
Referenced by main().
float avsigclip2 (float * f, float * sigma, int nel, float clip, float frac1, float frac2, float * sigmaout)
Definition at line 114 of file combine_stuff.c.
References clip, f, FLOAT_MAGIC, fmedian(), free(), i, median(), and sigma.
float getsigma (float * sigmavec, int nel)
Definition at line 164 of file combine_stuff.c.
References FLOAT_MAGIC, and i.
float mean (float * f, int nel)
Definition at line 55 of file combine_stuff.c.
References error_exit, f, and i.
Referenced by main(), and painttriangle().
float median (float * f, int nel)
Definition at line 40 of file combine_stuff.c.
References error_exit, f, and thefloatcmp().
Referenced by avgpixstack(), avsigclip2(), main(), and painttriangle().
float rankedimage (float * f, int nel, int rank)
Definition at line 21 of file combine_stuff.c.
References error_exit, f, and thefloatcmp().
Referenced by avgpixstack().
int thefloatcmp (float * s1, float * s2)
Definition at line 102 of file combine_stuff.c.
int thefloatcmp ()
Author
Generated automatically by Doxygen for imcat from the source code.