.TH "comment" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
comment \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cat.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "\fBcomment\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBcomment\fP* \fBcomment::next\fP"
.PP
Definition at line 58 of file cat.h.
.PP
Referenced by chopcomments(), copyheaderinfo(), installcomment(), and writecathead().
.SS "char* \fBcomment::text\fP"
.PP
Definition at line 57 of file cat.h.
.PP
Referenced by addargscomment(), addcomment(), copycomment(), readcathead(), and writecathead().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
