comm.c
NAME
comm.c -
SYNOPSIS
#include <stdio.h>
#include 'cdl.h'
Data Structures
struct iis_hdr
Defines
#define CDL_LIBRARY_SOURCE
#define MEMORY 01
#define LUT 02
#define FEEDBACK 05
#define IMCURSOR 020
#define WCS 021
#define SZ_IMCURVAL 160
#define SZ_WCSBUF 320
#define PACKED 0040000
#define IMC_SAMPLE 0040000
#define COMMAND 0100000
#define IIS_WRITE 0400000
#define IIS_READ 0100000
#define OK 0
#define ERR 1
#define min(a, b) (a < b ? a : b)
Functions
int com_whdr ()
int com_write ()
int com_read ()
int com_writeData (int fd, short x, short y, uchar *pix, int nbytes)
int com_readData (int fdin, int fdout, short x, short y, uchar *pix, int *npix)
int com_readCursor (int fdin, int fdout, int sample, float *x, float *y, char *key)
int com_setCursor (int fd, int x, int y, int wcs)
int com_setFBConfig (int fd, int configno)
int com_setFrame (int fd, int frame_num)
int com_writeWCS (int fd, char *name, float a, float b, float c, float d, float tx, float ty, float z1, float z2, int zt)
int com_readWCS (int fdin, int fdout, char *name, float *a, float *b, float *c, float *d, float *tx, float *ty, float *z1, float *z2, int *zt)
int com_eraseFrame (int fd)
int com_whdr (int fd, int tid, int subunit, int thingct, int x, int y, int z, int t)
int com_write (int fd, char *buf, int nbytes)
int com_read (int fd, char *buf, int maxbytes, int *nbytes)
int com_setDebug (int state)
Variables
int frame = 1 fbconfig = 1
int com_debug = 0
Define Documentation
#define CDL_LIBRARY_SOURCE
Definition at line 2 of file comm.c.
#define COMMAND 0100000
Definition at line 49 of file comm.c.
Referenced by com_setFrame(), and vx_iisio().
#define ERR 1
Definition at line 54 of file comm.c.
#define FEEDBACK 05
Definition at line 40 of file comm.c.
Referenced by com_eraseFrame(), iis_display(), and vx_iisio().
#define IIS_READ 0100000
Definition at line 51 of file comm.c.
Referenced by com_readCursor(), com_readData(), com_readWCS(), and vx_iisio().
#define IIS_WRITE 0400000
Definition at line 50 of file comm.c.
Referenced by com_eraseFrame(), com_setCursor(), com_setFrame(), com_writeData(), and com_writeWCS().
#define IMC_SAMPLE 0040000
Definition at line 48 of file comm.c.
Referenced by com_readCursor(), and vx_iisio().
#define IMCURSOR 020
Definition at line 41 of file comm.c.
Referenced by com_readCursor(), com_setCursor(), iis_cur(), and vx_iisio().
#define LUT 02
Definition at line 39 of file comm.c.
Referenced by com_setFrame(), and vx_iisio().
#define MEMORY 01
Definition at line 38 of file comm.c.
Referenced by com_readData(), com_writeData(), and vx_iisio().
#define min(a, b) (a < b ? a : b)
Definition at line 57 of file comm.c.
#define OK 0
Definition at line 53 of file comm.c.
#define PACKED 0040000
Definition at line 47 of file comm.c.
Referenced by com_readData(), com_whdr(), com_writeData(), com_writeWCS(), iis_display(), iis_drawcirc(), and vx_iisio().
#define SZ_IMCURVAL 160
Definition at line 43 of file comm.c.
Referenced by com_readCursor(), vx_iisio(), and vx_retCursorVal().
#define SZ_WCSBUF 320
Definition at line 44 of file comm.c.
Referenced by com_readWCS(), com_writeWCS(), and vx_iisio().
#define WCS 021
Definition at line 42 of file comm.c.
Referenced by com_readWCS(), com_writeWCS(), iis_display(), iis_drawcirc(), and vx_iisio().
Function Documentation
int com_eraseFrame (int fd)
Definition at line 413 of file comm.c.
References com_whdr(), ERR, fbconfig, FEEDBACK, frame, IIS_WRITE, and OK.
int com_read (int fd, char 	* buf, int maxbytes, int 	* nbytes) [static]
Definition at line 545 of file comm.c.
References buf, ERR, and OK.
int com_read ()
Referenced by com_readCursor(), com_readData(), and com_readWCS().
int com_readCursor (int fdin, int fdout, int sample, float	* x, float * y, char	* key)
Definition at line 185 of file comm.c.
References buf, com_read(), com_whdr(), ERR, IIS_READ, IMC_SAMPLE, IMCURSOR, key, n, SZ_IMCURVAL, wcs, x, and y.
int com_readData (int fdin, int fdout, short x, short y, uchar 	* pix, int	* npix)
Definition at line 138 of file comm.c.
References com_read(), com_whdr(), ERR, frame, IIS_READ, malloc(), MEMORY, n, OK, PACKED, pix, uchar, x, and y.
int com_readWCS (int fdin, int fdout, char	* name, float	* a, float * b, float * c, float * d, float	* tx, float * ty, float	* z1, float * z2, int	* zt)
Definition at line 366 of file comm.c.
References a, b, c, com_read(), com_whdr(), d, ERR, IIS_READ, n, OK, SZ_WCSBUF, tx, ty, WCS, z1, z2, and zt.
int com_setCursor (int fd, int x, int y, int wcs)
Definition at line 225 of file comm.c.
References com_whdr(), ERR, IIS_WRITE, IMCURSOR, OK, wcs, x, and y.
int com_setDebug (int state)
Definition at line 571 of file comm.c.
References com_debug, and OK.
int com_setFBConfig (int fd, int configno)
Definition at line 252 of file comm.c.
References fbconfig, and OK.
int com_setFrame (int fd, int frame_num)
Definition at line 275 of file comm.c.
References com_whdr(), com_write(), COMMAND, ERR, frame, IIS_WRITE, and LUT.
int com_whdr (int fd, int tid, int subunit, int thingct, int x, int y, int z, int t) [static]
Definition at line 450 of file comm.c.
References iis_hdr::checksum, com_debug, com_write(), PACKED, iis_hdr::subunit, iis_hdr::t, t, iis_hdr::thingct, iis_hdr::tid, iis_hdr::x, x, iis_hdr::y, y, iis_hdr::z, and z.
int com_whdr () [static]
Referenced by com_eraseFrame(), com_readCursor(), com_readData(), com_readWCS(), com_setCursor(), com_setFrame(), com_writeData(), and com_writeWCS().
int com_write (int fd, char 	* buf, int nbytes) [static]
Definition at line 509 of file comm.c.
References buf, ERR, min, n, and OK.
int com_write ()
Referenced by com_setFrame(), com_whdr(), com_writeData(), and com_writeWCS().
int com_writeData (int fd, short x, short y, uchar 	* pix, int nbytes)
Definition at line 103 of file comm.c.
References com_whdr(), com_write(), ERR, frame, IIS_WRITE, MEMORY, PACKED, pix, uchar, x, and y.
int com_writeWCS (int fd, char	* name, float a, float b, float c, float d, float tx, float ty, float z1, float z2, int zt)
Definition at line 316 of file comm.c.
References a, b, c, com_whdr(), com_write(), d, ERR, fbconfig, frame, IIS_WRITE, PACKED, SZ_WCSBUF, tx, ty, WCS, z1, z2, and zt.
Variable Documentation
int com_debug = 0 [static]
Definition at line 70 of file comm.c.
Referenced by com_setDebug(), and com_whdr().
int frame = 1 fbconfig = 1 [static]
Definition at line 69 of file comm.c.
Author
Generated automatically by Doxygen for imcat from the source code.