composite.c
NAME
composite.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'fits.h'
#include 'error.h'
#include 'stats_stuff.h'
#include 'object_stuff.h'
#include 'magic.h'
#include 'catio.h'
#include 'arrays.h'
#include 'composite.h'
Defines
#define usage '\n\n\n\SYNOPSIS\n\		composite	[option...] a.cat b.cat ....\n\			-r	min max	# range of half-light radii (default 2-3)\n\			-l 	min max	# range of log luminosity (default 4-8)\n\			-m	M	# array size (32)\n\			-s		# scale by r * r / l\n\			-i 		# generate an image: text -> stderr\n\\n\DESCRIPTION\n\		\'composite()\' forms a MODAL galaxy surface brightness profile\n\		from a collection of cat files created by findpeaks().\n\		Outputs modal SB + ellpticity alpha parameter to stdout\n\\n\n\n'
#define MAX_VALS 20000
#define N_ALPHA 6
Functions
main (int argc, char *argv[])
void accumulate (object obj, float ***fval, int **index, int M, short **f, int N)
Variables
float lbar
float rbar
int scale
Define Documentation
#define MAX_VALS 20000
Definition at line 32 of file composite.c.
Referenced by accumulate(), and main().
#define N_ALPHA 6
Definition at line 33 of file composite.c.
Referenced by main().
#define usage '\n\n\n\SYNOPSIS\n\		composite	[option...] a.cat b.cat ....\n\			-r	min max	# range of half-light radii (default 2-3)\n\			-l 	min max	# range of log luminosity (default 4-8)\n\			-m	M	# array size (32)\n\			-s		# scale by r * r / l\n\			-i 		# generate an image: text -> stderr\n\\n\DESCRIPTION\n\		\'composite()\' forms a MODAL galaxy surface brightness profile\n\		from a collection of cat files created by findpeaks().\n\		Outputs modal SB + ellpticity alpha parameter to stdout\n\\n\n\n'
Definition at line 1 of file composite.c.
Function Documentation
void accumulate (object obj, float *** fval, int ** index, int M, short ** f, int N)
Definition at line 220 of file composite.c.
main (int argc, char * argv[])
Definition at line 38 of file composite.c.
References accumulate(), add_comment(), allocShortArray(), alpha, error_exit, exit(), f, freeShortArray(), i, j, lbar, liststats(), M, MAX_VALS, median(), n, N, N_ALPHA, r, rbar, read_fits(), scale, set_fits_ipf(), sigma, usage, and write_fits().
Variable Documentation
float lbar
Definition at line 35 of file composite.c.
Referenced by accumulate(), and main().
float rbar
Definition at line 35 of file composite.c.
Referenced by accumulate(), and main().
int scale
Definition at line 36 of file composite.c.
Referenced by accumulate(), cdl_applyZscale(), eps_pageParams(), eps_setPage(), eps_setTransform(), iisdisplay(), inverse_fft(), main(), make_pixmap(), myfftwcfft(), and power().
Author
Generated automatically by Doxygen for imcat from the source code.