.TH "complex.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include '../imlib/fits.h'\fP
.br
\fC#include '../utils/error.h'\fP
.br
\fC#include '../utils/args.h'\fP
.br
\fC#include '../utils/arrays.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	\fBcomplex\fP --- perform operations on \fBcomplex\fP images\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	\fBcomplex\fP \fBop\fP [files...]\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	Complex works with 2-D \fBcomplex\fP images stored in f[2][\fBn2\fP][\fBn1\fP] \fBFITS\fP format.\\\fBn\fP\\	Examples\\\fBn\fP\\\\\fBn\fP\\		\fBcomplex\fP multiply \fBf1\fP f2\\\fBt\fP\\\fBn\fP\\		\fBcomplex\fP conjugate f\\\fBt\fP\\\fBn\fP\\		\fBcomplex\fP ab2rphi f\\\fBt\fP\\\fBn\fP\\		\fBcomplex\fP rphi2ab f\\\fBt\fP\\\fBn\fP\\\\\fBn\fP\\	where f, \fBf1\fP, f2 are filenames or '-' for standard input.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.br
.ti -1c
.RI "#define \fBMULTIPLY\fP   0"
.br
.ti -1c
.RI "#define \fBCONJUGATE\fP   1"
.br
.ti -1c
.RI "#define \fBAB2RPHI\fP   2"
.br
.ti -1c
.RI "#define \fBRPHI2AB\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfitsheader\fP * \fBopenfits\fP (char *fn)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define AB2RPHI   2"
.PP
Definition at line 36 of file complex.c.
.PP
Referenced by main().
.SS "#define CONJUGATE   1"
.PP
Definition at line 35 of file complex.c.
.PP
Referenced by main().
.SS "#define MULTIPLY   0"
.PP
Definition at line 34 of file complex.c.
.PP
Referenced by main().
.SS "#define RPHI2AB   3"
.PP
Definition at line 37 of file complex.c.
.PP
Referenced by main().
.SS "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	\fBcomplex\fP --- perform operations on \fBcomplex\fP images\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	\fBcomplex\fP \fBop\fP [files...]\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	Complex works with 2-D \fBcomplex\fP images stored in f[2][\fBn2\fP][\fBn1\fP] \fBFITS\fP format.\\\fBn\fP\\	Examples\\\fBn\fP\\\\\fBn\fP\\		\fBcomplex\fP multiply \fBf1\fP f2\\\fBt\fP\\\fBn\fP\\		\fBcomplex\fP conjugate f\\\fBt\fP\\\fBn\fP\\		\fBcomplex\fP ab2rphi f\\\fBt\fP\\\fBn\fP\\		\fBcomplex\fP rphi2ab f\\\fBt\fP\\\fBn\fP\\\\\fBn\fP\\	where f, \fBf1\fP, f2 are filenames or '-' for standard input.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 1 of file complex.c.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 41 of file complex.c.
.PP
References AB2RPHI, add_comment(), allocFloatArray(), argsinit(), CONJUGATE, error_exit, exit(), fits, FLAG_ARG, getargs(), MULTIPLY, fitsheader::n, N1, N2, nextargtype(), NO_ARG, op, openfits(), readfitsplane(), RPHI2AB, usage, writefitsheader(), writefitsplane(), writefitstail(), x, and y.
.SS "\fBfitsheader\fP * openfits (char * fn)"
.PP
Definition at line 124 of file complex.c.
.PP
References error_exit, exit(), f, fits, fitsheader::n, fitsheader::ndim, and readfitsheader().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
