.TH "complex" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fft_FFTPACK.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBr\fP"
.br
.ti -1c
.RI "float \fBi\fP"
.br
.ti -1c
.RI "\fBreal\fP \fBr\fP"
.br
.ti -1c
.RI "\fBreal\fP \fBi\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBreal\fP \fBcomplex::i\fP"
.PP
Definition at line 16 of file myf2c.h.
.SS "\fBreal\fP \fBcomplex::i\fP"
.PP
Definition at line 16 of file myf2c.h.
.PP
Referenced by MAIN__().
.SS "\fBreal\fP \fBcomplex::r\fP"
.PP
Definition at line 16 of file myf2c.h.
.SS "\fBreal\fP \fBcomplex::r\fP"
.PP
Definition at line 16 of file myf2c.h.
.PP
Referenced by MAIN__().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
