complex.c
NAME
complex.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	complex --- perform operations on complex images\n\SYNOPSIS\n\	complex op [files...]\n\\n\DESCRIPTION\n\	Complex works with 2-D complex images stored in f[2][n2][n1] FITS format.\n\	Examples\n\\n\		complex multiply f1 f2\t\n\		complex conjugate f\t\n\		complex ab2rphi f\t\n\		complex rphi2ab f\t\n\\n\	where f, f1, f2 are filenames or '-' for standard input.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define MULTIPLY 0
#define CONJUGATE 1
#define AB2RPHI 2
#define RPHI2AB 3
Functions
fitsheader * openfits (char *fn)
int main (int argc, char *argv[])
Define Documentation
#define AB2RPHI 2
Definition at line 36 of file complex.c.
Referenced by main().
#define CONJUGATE 1
Definition at line 35 of file complex.c.
Referenced by main().
#define MULTIPLY 0
Definition at line 34 of file complex.c.
Referenced by main().
#define RPHI2AB 3
Definition at line 37 of file complex.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	complex --- perform operations on complex images\n\SYNOPSIS\n\	complex op [files...]\n\\n\DESCRIPTION\n\	Complex works with 2-D complex images stored in f[2][n2][n1] FITS format.\n\	Examples\n\\n\		complex multiply f1 f2\t\n\		complex conjugate f\t\n\		complex ab2rphi f\t\n\		complex rphi2ab f\t\n\\n\	where f, f1, f2 are filenames or '-' for standard input.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file complex.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 41 of file complex.c.
References AB2RPHI, add_comment(), allocFloatArray(), argsinit(), CONJUGATE, error_exit, exit(), fits, FLAG_ARG, getargs(), MULTIPLY, fitsheader::n, N1, N2, nextargtype(), NO_ARG, op, openfits(), readfitsplane(), RPHI2AB, usage, writefitsheader(), writefitsplane(), writefitstail(), x, and y.
fitsheader * openfits (char * fn)
Definition at line 124 of file complex.c.
References error_exit, exit(), f, fits, fitsheader::n, fitsheader::ndim, and readfitsheader().
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.