.TH "composite.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
composite.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBaccumulate\fP (\fBobject\fP \fBobj\fP, float ***fval, int **index, int \fBM\fP, short **f, int \fBN\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void accumulate (\fBobject\fP obj, float *** fval, int ** index, int M, short ** f, int N)"
.PP
Definition at line 220 of file composite.c.
.PP
References di, dj, error_exit, f, object::i, i, object::j, j, lbar, M, MAGIC, MAX_VALS, N, rbar, and scale.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
