.TH "consts_1_" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
consts_1_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdoublereal\fP \fBpi\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBtwopi\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBxmu\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBdummy\fP [4]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBdoublereal\fP \fBconsts_1_::dummy\fP[4]"
.PP
Definition at line 11 of file kepler_jh.c.
.SS "\fBdoublereal\fP \fBconsts_1_::pi\fP"
.PP
Definition at line 11 of file kepler_jh.c.
.SS "\fBdoublereal\fP \fBconsts_1_::twopi\fP"
.PP
Definition at line 11 of file kepler_jh.c.
.SS "\fBdoublereal\fP \fBconsts_1_::xmu\fP"
.PP
Definition at line 11 of file kepler_jh.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
