.TH "consts_2_" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
consts_2_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdoublereal\fP \fBpi\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBtwopi\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBxmu\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBxk\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBeps\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBc__\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBrearth\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBdoublereal\fP \fBconsts_2_::c__\fP"
.PP
Definition at line 14 of file kepler_jh.c.
.SS "\fBdoublereal\fP \fBconsts_2_::eps\fP"
.PP
Definition at line 14 of file kepler_jh.c.
.SS "\fBdoublereal\fP \fBconsts_2_::pi\fP"
.PP
Definition at line 14 of file kepler_jh.c.
.SS "\fBdoublereal\fP \fBconsts_2_::rearth\fP"
.PP
Definition at line 14 of file kepler_jh.c.
.SS "\fBdoublereal\fP \fBconsts_2_::twopi\fP"
.PP
Definition at line 14 of file kepler_jh.c.
.SS "\fBdoublereal\fP \fBconsts_2_::xk\fP"
.PP
Definition at line 14 of file kepler_jh.c.
.SS "\fBdoublereal\fP \fBconsts_2_::xmu\fP"
.PP
Definition at line 14 of file kepler_jh.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
