control_panel.h
NAME
control_panel.h -
SYNOPSIS
Data Structures
struct FD_control_panel
Functions
void rewind_button_callback (FL_OBJECT *, long)
void stop_button_callback (FL_OBJECT *, long)
void rec_button_callback (FL_OBJECT *, long)
void forwardstep_button_callback (FL_OBJECT *, long)
void quit_button_callback (FL_OBJECT *, long)
void command_input_callback (FL_OBJECT *, long)
void zscale_counter_callback (FL_OBJECT *, long)
void go_button_callback (FL_OBJECT *, long)
FD_control_panel * create_form_control_panel (void)
Function Documentation
void command_input_callback (FL_OBJECT *, long)
Definition at line 75 of file callbacks.c.
References DrawMesh(), fitsgencommand, ReadNewFrame(), and start_command().
Referenced by create_form_control_panel().
FD_control_panel* create_form_control_panel (void)
Definition at line 7 of file control_panel.c.
References FD_control_panel::command_input, command_input_callback(), FD_control_panel::control_panel, FD_control_panel::forward_step_button, forwardstep_button_callback(), FD_control_panel::frame_number_text, FD_control_panel::go_button, go_button_callback(), FD_control_panel::quit_button, quit_button_callback(), FD_control_panel::rec_button, rec_button_callback(), FD_control_panel::rewind_button, rewind_button_callback(), FD_control_panel::stop_button, stop_button_callback(), FD_control_panel::zscale_counter, and zscale_counter_callback().
Referenced by main().
void forwardstep_button_callback (FL_OBJECT *, long)
Definition at line 43 of file callbacks.c.
References DrawMesh(), f, IDLE_MODE, opmode, and ReadNewFrame().
Referenced by create_form_control_panel().
void go_button_callback (FL_OBJECT *, long)
Definition at line 57 of file callbacks.c.
References f, opmode, and RUN_MODE.
Referenced by create_form_control_panel().
void quit_button_callback (FL_OBJECT *, long)
Definition at line 69 of file callbacks.c.
References exit().
Referenced by create_form_control_panel().
void rec_button_callback (FL_OBJECT *, long)
Definition at line 64 of file callbacks.c.
References recording.
Referenced by create_form_control_panel().
void rewind_button_callback (FL_OBJECT *, long)
Callbacks, globals and object handlers * Definition at line 32 of file callbacks.c.
References DrawMesh(), f, IDLE_MODE, opmode, ReadNewFrame(), and start_command().
Referenced by create_form_control_panel().
void stop_button_callback (FL_OBJECT *, long)
Definition at line 52 of file callbacks.c.
References IDLE_MODE, and opmode.
Referenced by create_form_control_panel().
void zscale_counter_callback (FL_OBJECT *, long)
Definition at line 23 of file callbacks.c.
References DrawMesh(), f, log2zscale, thecontrolpanel, zscale, and FD_control_panel::zscale_counter.
Referenced by create_form_control_panel().
Author
Generated automatically by Doxygen for imcat from the source code.