.TH "control_panel.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
control_panel.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'forms.h'\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'control_panel.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFD_control_panel\fP * \fBcreate_form_control_panel\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBFD_control_panel\fP* create_form_control_panel (void)"
.PP
Definition at line 7 of file control_panel.c.
.PP
References FD_control_panel::command_input, command_input_callback(), FD_control_panel::control_panel, FD_control_panel::forward_step_button, forwardstep_button_callback(), FD_control_panel::frame_number_text, FD_control_panel::go_button, go_button_callback(), FD_control_panel::quit_button, quit_button_callback(), FD_control_panel::rec_button, rec_button_callback(), FD_control_panel::rewind_button, rewind_button_callback(), FD_control_panel::stop_button, stop_button_callback(), FD_control_panel::zscale_counter, and zscale_counter_callback().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
