control_panel.c
NAME
control_panel.c -
SYNOPSIS
#include 'forms.h'
#include <stdlib.h>
#include 'control_panel.h'
Functions
FD_control_panel * create_form_control_panel (void)
Function Documentation
FD_control_panel* create_form_control_panel (void)
Definition at line 7 of file control_panel.c.
References FD_control_panel::command_input, command_input_callback(), FD_control_panel::control_panel, FD_control_panel::forward_step_button, forwardstep_button_callback(), FD_control_panel::frame_number_text, FD_control_panel::go_button, go_button_callback(), FD_control_panel::quit_button, quit_button_callback(), FD_control_panel::rec_button, rec_button_callback(), FD_control_panel::rewind_button, rewind_button_callback(), FD_control_panel::stop_button, stop_button_callback(), FD_control_panel::zscale_counter, and zscale_counter_callback().
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.