.TH "contourplot.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contourplot.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include '../../imlib/fits.h'\fP
.br
\fC#include 'psutils.h'\fP
.br
\fC#include 'contourplot.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcontourplot\fP (\fBfitsheader\fP *\fBfits\fP, int \fBN1\fP, int \fBN2\fP, int ncont, float *fcont, float width, float height)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void contourplot (\fBfitsheader\fP * fits, int N1, int N2, int ncont, float * fcont, float width, float height)"
.PP
Definition at line 14 of file contourplot.c.
.PP
References f, ff, fits, ix, N1, N2, psline(), readfitsline(), x, xp(), y, and yp().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
