contourplot.c
NAME
contourplot.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include '../../imlib/fits.h'
#include 'psutils.h'
#include 'contourplot.h'
Functions
void contourplot (fitsheader *fits, int N1, int N2, int ncont, float *fcont, float width, float height)
Function Documentation
void contourplot (fitsheader * fits, int N1, int N2, int ncont, float * fcont, float width, float height)
Definition at line 14 of file contourplot.c.
References f, ff, fits, ix, N1, N2, psline(), readfitsline(), x, xp(), y, and yp().
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.