contour_3Dtest.c
NAME
contour_3Dtest.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <unistd.h>
#include <values.h>
#include 'cpgplot.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/colormaps.h'
#include 'labels.h'
Defines
#define usage '\n\NAME\n\	contour --- create contour plot from fits image\n\\n\SYNOPSIS\n\	contour [option....] < fitsin\n\		-n nc		# number of contour intervals (10)\n\		-f fmin fmax	# range of contour heights\n\		-d device	# pgplot style device ('/xserve')\n\		-t title	# text for title ('contour plot')\n\		-l xlab ylab	# labels for axes ('x' 'y')\n\		-w lwidth	# line width (1)\n\		-H charheight	# character height (1)\n\		-X X1 X2 Y1 Y2	# range for tick-labels\n\		-j		# switch off justification\n\		-a axis		# pgenv 'axis' value (0)\n\		-g		# add gray-scale background image\n\		-c colmap	# add color-mapped background image\n\		-L x y text	# add a label\n\		-W		# add a wedge for image range\n\\n\DESCRIPTION\n\	\'contour\' produces a contour plot from a fits image\n\	using pgplot routines.\n\\n\	If fmin, fmax values are not specified these are\n\	calculated from the input image.\n\\n\	It then draws (nc + 1) contours at levels\n\	f - fmin + i * df, with df = (fmax - fmin) / nc.\n\	By default, it produces output in an X-window on\n\	the screen, but use -d option to specify alternative.\n\\n\	Use -c to display a colorised image - colmap can be 0,1,2.\n\\n\	Use -L option to add labels at arbitrary positions.\n\\n\	Use -W option to add a wedge showing the range of image values.\n\\n\	Use -a option to control axes, box tickmarks etc. See\n\	plotcat usage for more info.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	contour --- create contour plot from fits image\n\\n\SYNOPSIS\n\	contour [option....] < fitsin\n\		-n nc		# number of contour intervals (10)\n\		-f fmin fmax	# range of contour heights\n\		-d device	# pgplot style device ('/xserve')\n\		-t title	# text for title ('contour plot')\n\		-l xlab ylab	# labels for axes ('x' 'y')\n\		-w lwidth	# line width (1)\n\		-H charheight	# character height (1)\n\		-X X1 X2 Y1 Y2	# range for tick-labels\n\		-j		# switch off justification\n\		-a axis		# pgenv 'axis' value (0)\n\		-g		# add gray-scale background image\n\		-c colmap	# add color-mapped background image\n\		-L x y text	# add a label\n\		-W		# add a wedge for image range\n\\n\DESCRIPTION\n\	\'contour\' produces a contour plot from a fits image\n\	using pgplot routines.\n\\n\	If fmin, fmax values are not specified these are\n\	calculated from the input image.\n\\n\	It then draws (nc + 1) contours at levels\n\	f - fmin + i * df, with df = (fmax - fmin) / nc.\n\	By default, it produces output in an X-window on\n\	the screen, but use -d option to specify alternative.\n\\n\	Use -c to display a colorised image - colmap can be 0,1,2.\n\\n\	Use -L option to add labels at arbitrary positions.\n\\n\	Use -W option to add a wedge showing the range of image values.\n\\n\	Use -a option to control axes, box tickmarks etc. See\n\	plotcat usage for more info.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file contour_3Dtest.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 64 of file contour_3Dtest.c.
References c, dx, dy, error_exit, exit(), f, ff, fits, FLOAT_MAGIC, fmin, getcolormap(), MAXFLOAT, MINFLOAT, N1, N2, label::next, read2Dfloatimage(), label::text, usage, label::x, x, label::y, and y.
Author
Generated automatically by Doxygen for imcat from the source code.