.TH "convertarray.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
convertarray.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBconvertarray\fP (char *fsrc, char *fdst, int srcpixtype, int dstpixtype, int nel, int bscaling, double bscale, double bzero)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int convertarray (char * fsrc, char * fdst, int srcpixtype, int dstpixtype, int nel, int bscaling, double bscale, double bzero)"
.PP
Definition at line 13 of file convertarray.c.
.PP
References clip, DBL_MAGIC, DBL_PIXTYPE, error_exit, FLOAT_MAGIC, FLOAT_PIXTYPE, i, INT_MAGIC, INT_PIXTYPE, SHORT_MAGIC, SHORT_PIXTYPE, UCHAR_MAGIC, and UCHAR_PIXTYPE.
.PP
Referenced by readfitsline(), and writefitsline().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
