convolve.c
NAME
convolve.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
#include '../fftlib/myfft.h'
Defines
#define usage '\n\n\n\NAME\n\	convolve --- convolve one fits file with another\n\\n\SYNOPSIS\n\	convolve [options...] target.fits psf.fits\n\		-f	# psf.fits contains fft\n\		-n	# normalise psf\n\		-m mval	# substitute value for magic target pixels (0.0)\n\		-d	# don't fix magic pixels\n\		-o	# psf origin at 0,0.\n\\n\DESCRIPTION\n\	'Convolve' convolves target file 'target.fits' with a\n\	point spread function 'psf.fits'. Unlike 'acf -c', the\n\	two input files need not have the same dimensions (and\n\	will typically be used with a relatively small psf image)\n\	but should have the same pixel scale. If the two images\n\	have the same size then 'acf -c' is more efficient.\n\	By default 'convolve' expects the psf to be a M1 * M2 real-space\n\	image with spatial origin at M1 / 2, M2 / 2; use '-o' option\n\	if the origin is 0, 0. Use -f option to interpret 'psf.fits' as\n\	a fourier transform of the psf (in format generated by\n\	'fft'). The output image has the same dimensions and\n\	type as the input image.\n\	WARNING - THIS DOES NOT REALLY WORK PROPERLY - TO BE FIXED.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define PI M_PI
Functions
float rfunc (float kx, float ky)
float ifunc (float kx, float ky)
main (int argc, char *argv[])
Variables
float ** psffft
int M1
int M2
Define Documentation
#define PI M_PI
Definition at line 49 of file convolve.c.
#define usage '\n\n\n\NAME\n\	convolve --- convolve one fits file with another\n\\n\SYNOPSIS\n\	convolve [options...] target.fits psf.fits\n\		-f	# psf.fits contains fft\n\		-n	# normalise psf\n\		-m mval	# substitute value for magic target pixels (0.0)\n\		-d	# don't fix magic pixels\n\		-o	# psf origin at 0,0.\n\\n\DESCRIPTION\n\	'Convolve' convolves target file 'target.fits' with a\n\	point spread function 'psf.fits'. Unlike 'acf -c', the\n\	two input files need not have the same dimensions (and\n\	will typically be used with a relatively small psf image)\n\	but should have the same pixel scale. If the two images\n\	have the same size then 'acf -c' is more efficient.\n\	By default 'convolve' expects the psf to be a M1 * M2 real-space\n\	image with spatial origin at M1 / 2, M2 / 2; use '-o' option\n\	if the origin is 0, 0. Use -f option to interpret 'psf.fits' as\n\	a fourier transform of the psf (in format generated by\n\	'fft'). The output image has the same dimensions and\n\	type as the input image.\n\	WARNING - THIS DOES NOT REALLY WORK PROPERLY - TO BE FIXED.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file convolve.c.
Function Documentation
float ifunc (float kx, float ky)
Definition at line 159 of file convolve.c.
References ix, M1, M2, PI, and psffft.
Referenced by main().
main (int argc, char * argv[])
Definition at line 51 of file convolve.c.
References add_comment(), alloc_fft(), allocFloatArray(), cfilter(), cycleimage(), error_exit, exit(), f, fft_type, forward_fft(), get_fft(), ifunc(), inverse_fft(), M1, M2, N1, N2, psffft, read2Dfloatimage(), rfunc(), substitute(), usage, write2Dfloatimage(), x, and y.
float rfunc (float kx, float ky)
Definition at line 145 of file convolve.c.
References ix, M1, M2, PI, and psffft.
Referenced by main().
Variable Documentation
int M1 [static]
Definition at line 47 of file convolve.c.
int M2 [static]
Definition at line 47 of file convolve.c.
float** psffft [static]
Definition at line 46 of file convolve.c.
Referenced by ifunc(), main(), and rfunc().
Author
Generated automatically by Doxygen for imcat from the source code.