convertcoords.c
NAME
convertcoords.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/error.h'
#include 'radecio.h'
Defines
#define usage '\n\NAME\n\	convertcoords --- transform between different sky coordinate systems\n\\n\SYNOPSIS\n\	convertcoords convtype angle1 angle2\n\\n\DESCRIPTION\n\	convertcoords invokes Doug Mink's utilities for conversion\n\	between different sky coordinate systems.\n\\n\	Angles can be expressed in either decimal or [hd]:m:s format.\n\\n\	The string 'convtype' specifies the type of conversion and can be\n\	one of\n\		fk524 		# Convert J2000(FK5) to B1950(FK4) coordinates\n\		fk425		# Convert B1950(FK4) to J2000(FK5) coordinates\n\		fk42gal		# Convert B1950(FK4) to galactic coordinates\n\		fk52gal		# Convert J2000(FK5) to galactic coordinates\n\		gal2fk4		# Convert galactic coordinates to B1950(FK4)\n\		gal2fk5		# Convert galactic coordinates to J2000<FK5) \n\\n\	Output angles are expressed in decimal degrees.\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	convertcoords --- transform between different sky coordinate systems\n\\n\SYNOPSIS\n\	convertcoords convtype angle1 angle2\n\\n\DESCRIPTION\n\	convertcoords invokes Doug Mink's utilities for conversion\n\	between different sky coordinate systems.\n\\n\	Angles can be expressed in either decimal or [hd]:m:s format.\n\\n\	The string 'convtype' specifies the type of conversion and can be\n\	one of\n\		fk524 		# Convert J2000(FK5) to B1950(FK4) coordinates\n\		fk425		# Convert B1950(FK4) to J2000(FK5) coordinates\n\		fk42gal		# Convert B1950(FK4) to galactic coordinates\n\		fk52gal		# Convert J2000(FK5) to galactic coordinates\n\		gal2fk4		# Convert galactic coordinates to B1950(FK4)\n\		gal2fk5		# Convert galactic coordinates to J2000<FK5) \n\\n\	Output angles are expressed in decimal degrees.\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file convertcoords.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 42 of file convertcoords.c.
References error_exit, fk425(), fk42gal(), fk524(), fk52gal(), gal2fk4(), gal2fk5(), getangle(), HMS_ANGLE_TYPE, and usage.
Author
Generated automatically by Doxygen for imcat from the source code.