convertorbits.c
NAME
convertorbits.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'vectors.h'
#include 'kepler.h'
#include 'extravars.h'
Defines
#define usage '\nNAME\n\	convertorbits - convert between Kepler elements and phase-space coordinates\n\\n\SYNOPSIS\n\	convertorbits k2c | c2k [-extravars vardefs]\n\\n\DESCRIPTION\n\	convertorbits converts between Keplerian elements\n\	a, e, i, omega, Omega, M and cartesian r[3], v[3].\n\\n\	With -extravars option we carry defined variables along. For example, use\n\		-extrvars myscalar:1:myvector:3\n\	to carry along myscalar and myvector[3]\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
#define K2C_MODE 0
#define C2K_MODE 1
Functions
main (int argc, char *argv[])
Define Documentation
#define C2K_MODE 1
Definition at line 31 of file convertorbits.c.
Referenced by main().
#define K2C_MODE 0
Definition at line 30 of file convertorbits.c.
Referenced by main().
#define usage '\nNAME\n\	convertorbits - convert between Kepler elements and phase-space coordinates\n\\n\SYNOPSIS\n\	convertorbits k2c | c2k [-extravars vardefs]\n\\n\DESCRIPTION\n\	convertorbits converts between Keplerian elements\n\	a, e, i, omega, Omega, M and cartesian r[3], v[3].\n\\n\	With -extravars option we carry defined variables along. For example, use\n\		-extrvars myscalar:1:myvector:3\n\	to carry along myscalar and myvector[3]\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 13 of file convertorbits.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 33 of file convertorbits.c.
References assignkeplerorbitfrombuffer(), buff, C2K_MODE, cartesiantokepler(), exit(), fillbufferfromkeplerorbit(), ipf, K2C_MODE, keplertocartesian(), opmode, parseextravars(), r, theorbit, usage, and v.
Author
Generated automatically by Doxygen for imcat from the source code.