cosqb.c
NAME
cosqb.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int cosqb_ (integer *n, real *x, real *wsave)
Function Documentation
int cosqb_ (integer * n, real * x, real * wsave)
Definition at line 9 of file cosqb.c.
References cosqb1_(), integer, n, real, and x.
Referenced by MAIN__(), and sinqb_().
Author
Generated automatically by Doxygen for imcat from the source code.