.TH "cosqb1.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cosqb1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcosqb1_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *x, \fBreal\fP *\fBw\fP, \fBreal\fP *xh)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cosqb1_ (\fBinteger\fP * n, \fBreal\fP * x, \fBreal\fP * w, \fBreal\fP * xh)"
.PP
Definition at line 9 of file cosqb1.c.
.PP
References integer, k, n, real, rfftb_(), w, and x.
.PP
Referenced by cosqb_().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
