.TH "cost.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cost.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcost_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *x, \fBreal\fP *wsave)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cost_ (\fBinteger\fP * n, \fBreal\fP * x, \fBreal\fP * wsave)"
.PP
Definition at line 9 of file cost.c.
.PP
References integer, k, n, real, rfftf_(), and x.
.PP
Referenced by MAIN__().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
