.TH "cpgellipses.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpgellipses.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'cpgplot.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   M_PI"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcpgellipses\fP (int ne, float *x, float *y, float *\fBa\fP, float *\fBb\fP, float *phi0, float *colour, int nv, int drawoutline, float \fBfill\fP)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define PI   M_PI"
.PP
Definition at line 12 of file cpgellipses.c.
.SH "Function Documentation"
.PP 
.SS "void cpgellipses (int ne, float * x, float * y, float * a, float * b, float * phi0, float * colour, int nv, int drawoutline, float fill)"
.PP
Definition at line 21 of file cpgellipses.c.
.PP
References a, b, c, e, exit(), fill, free(), ne, phi, PI, v, X, x, Y, and y.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
