cpgellipses.h
NAME
cpgellipses.h -
SYNOPSIS
Functions
void cpgellipses (int ne, float *x, float *y, float *a, float *b, float *phi0, float *colour, int nv, int drawoutline, float fill)
Function Documentation
void cpgellipses (int ne, float * x, float * y, float * a, float * b, float * phi0, float * colour, int nv, int drawoutline, float fill)
Definition at line 21 of file cpgellipses.c.
References a, b, c, e, exit(), fill, free(), ne, phi, PI, v, x, X, y, and Y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.