cpgellipses.c
NAME
cpgellipses.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'cpgplot.h'
Defines
#define PI M_PI
Functions
void cpgellipses (int ne, float *x, float *y, float *a, float *b, float *phi0, float *colour, int nv, int drawoutline, float fill)
Define Documentation
#define PI M_PI
Definition at line 12 of file cpgellipses.c.
Function Documentation
void cpgellipses (int ne, float * x, float * y, float * a, float * b, float * phi0, float * colour, int nv, int drawoutline, float fill)
Definition at line 21 of file cpgellipses.c.
References a, b, c, e, exit(), fill, free(), ne, phi, PI, v, X, x, Y, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.