.TH "Ctran" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ctran \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBvalid\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.ti -1c
.RI "float \fBd\fP"
.br
.ti -1c
.RI "float \fBtx\fP"
.br
.ti -1c
.RI "float \fBty\fP"
.br
.ti -1c
.RI "float \fBz1\fP"
.br
.ti -1c
.RI "float \fBz2\fP"
.br
.ti -1c
.RI "int \fBzt\fP"
.br
.ti -1c
.RI "char \fBformat\fP [32]"
.br
.ti -1c
.RI "char \fBimtitle\fP [SZ_IMTITLE+1]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float \fBCtran::a\fP"
.PP
Definition at line 127 of file vximtool.c.
.SS "float \fBCtran::b\fP"
.PP
Definition at line 127 of file vximtool.c.
.SS "float \fBCtran::c\fP"
.PP
Definition at line 128 of file vximtool.c.
.SS "float \fBCtran::d\fP"
.PP
Definition at line 128 of file vximtool.c.
.SS "char \fBCtran::format\fP[32]"
.PP
Definition at line 132 of file vximtool.c.
.SS "char \fBCtran::imtitle\fP[SZ_IMTITLE+1]"
.PP
Definition at line 133 of file vximtool.c.
.SS "float \fBCtran::tx\fP"
.PP
Definition at line 129 of file vximtool.c.
.SS "float \fBCtran::ty\fP"
.PP
Definition at line 129 of file vximtool.c.
.SS "int \fBCtran::valid\fP"
.PP
Definition at line 126 of file vximtool.c.
.SS "float \fBCtran::z1\fP"
.PP
Definition at line 130 of file vximtool.c.
.SS "float \fBCtran::z2\fP"
.PP
Definition at line 130 of file vximtool.c.
.SS "int \fBCtran::zt\fP"
.PP
Definition at line 131 of file vximtool.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
