cycleimage.c
NAME
cycleimage.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../fftlib/myfft.h'
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	cycleimage - translate a FITS image\n\\n\SYNOPSIS\n\	cycleimage dx dy\n\\n\DESCRIPTION\n\	\'cycleimage\' cycles an image moving each point\n\	a distance dx, dy (in pixels).\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	cycleimage - translate a FITS image\n\\n\SYNOPSIS\n\	cycleimage dx dy\n\\n\DESCRIPTION\n\	\'cycleimage\' cycles an image moving each point\n\	a distance dx, dy (in pixels).\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file cycleimage.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 28 of file cycleimage.c.
References add_comment(), cycleimage(), dx, dy, error_exit, exit(), f, fits, N1, N2, read2Dfloatimage(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.