.TH "decimaltohms.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decimaltohms.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'utils/error.h'\fP
.br
\fC#include 'radecio.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	decimaltomhs --- convert an \fBangle\fP from decimal degrees to h:m:s format\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	decimaltohms \fBangle\fP\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	decimaltohms takes \fBa\fP decimal format \fBangle\fP as argument and\\\fBn\fP\\	generates \fBa\fP string corresponding to that argument in h:m:s\\\fBn\fP\\	format\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser	kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	decimaltomhs --- convert an \fBangle\fP from decimal degrees to h:m:s format\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	decimaltohms \fBangle\fP\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	decimaltohms takes \fBa\fP decimal format \fBangle\fP as argument and\\\fBn\fP\\	generates \fBa\fP string corresponding to that argument in h:m:s\\\fBn\fP\\	format\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser	kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 5 of file decimaltohms.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 30 of file decimaltohms.c.
.PP
References angle, decimaltoxms(), error_exit, exit(), and usage.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
