.TH "deltam.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deltam.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'deltam.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBdeltam\fP (double *rhelio, double *rgeo, double G)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double deltam (double * rhelio, double * rgeo, double G)"
.PP
Definition at line 5 of file deltam.c.
.PP
References A, alpha, B, dr, G, l, and phi.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
