.TH "deltam.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deltam.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBASTEROID_G_LIGHT\fP   0.40"
.br
.ti -1c
.RI "#define \fBASTEROID_G_MEDIUM\fP   0.23"
.br
.ti -1c
.RI "#define \fBASTEROID_G_DARK\fP   0.09"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBdeltam\fP (double *rhelio, double *rgeo, double G)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ASTEROID_G_DARK   0.09"
.PP
Definition at line 3 of file deltam.h.
.PP
Referenced by main().
.SS "#define ASTEROID_G_LIGHT   0.40"
.PP
Definition at line 1 of file deltam.h.
.PP
Referenced by main().
.SS "#define ASTEROID_G_MEDIUM   0.23"
.PP
Definition at line 2 of file deltam.h.
.PP
Referenced by main().
.SH "Function Documentation"
.PP 
.SS "double deltam (double * rhelio, double * rgeo, double G)"
.PP
Definition at line 5 of file deltam.c.
.PP
References A, alpha, B, dr, G, l, and phi.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
