deproject.c
NAME
deproject.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <unistd.h>
#include '../../utils/error.h'
#include '../../utils/ipbuff.h'
Defines
#define usage '\n\n\n\NAME\n\	deproject - deproject an image of an assumed spherically symmetric object\n\\n\SYNOPSIS\n\	deproject rmin rmax nbins [options....] \n\		-c xc yc	# spatial origin (N1/2 + 0.5, N2/2 + 0.5)\n\		-s d		# spacing of points for volume integration (0.1)\n\\n\DESCRIPTION\n\	\'deproject\' computes deprojection of an assumed spherically\n\	symmetric structure from a FITS image in the style of\n\	Fabian et al.\n\\n\	The model is\n\		f_2D = int dz f_3D(sqrt(rp^2 + z^2)).\n\\n\	Input image is read from stdin through profile (which generates\n\	an lc-format version of the asimuthal sum of the image F(r)\n\	in nbins log-spaced shells ranging from rmin to rmax.\n\\n\	We then work inward from outermost shell, computing first the\n\	volumes\n\		V[ir] = 2 pi int int dz drp rp\n\	where integrals are over volumes such that r = sqrt(rp^2 + z^2)\n\	falls in some given bin r, and where we use spacing of d times r\n\	to perform the integrals.\n\\n\	We then compute:\n\		f_3D[i] = (F[i] - sum_j>i V[j] f[j]) / V[i]\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	deproject - deproject an image of an assumed spherically symmetric object\n\\n\SYNOPSIS\n\	deproject rmin rmax nbins [options....] \n\		-c xc yc	# spatial origin (N1/2 + 0.5, N2/2 + 0.5)\n\		-s d		# spacing of points for volume integration (0.1)\n\\n\DESCRIPTION\n\	\'deproject\' computes deprojection of an assumed spherically\n\	symmetric structure from a FITS image in the style of\n\	Fabian et al.\n\\n\	The model is\n\		f_2D = int dz f_3D(sqrt(rp^2 + z^2)).\n\\n\	Input image is read from stdin through profile (which generates\n\	an lc-format version of the asimuthal sum of the image F(r)\n\	in nbins log-spaced shells ranging from rmin to rmax.\n\\n\	We then work inward from outermost shell, computing first the\n\	volumes\n\		V[ir] = 2 pi int int dz drp rp\n\	where integrals are over volumes such that r = sqrt(rp^2 + z^2)\n\	falls in some given bin r, and where we use spacing of d times r\n\	to perform the integrals.\n\\n\	We then compute:\n\		f_3D[i] = (F[i] - sum_j>i V[j] f[j]) / V[i]\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file deproject.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 49 of file deproject.c.
References d, dr, error_exit, exit(), F(), i, ipf, j, r, readdoublebuff(), usage, and z.
Author
Generated automatically by Doxygen for imcat from the source code.