.TH "test.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBdrand48\fP ()"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double drand48 ()"
.PP
.SS "main ()"
.PP
Definition at line 6 of file dev/test.c.
.PP
References alpha, drand48(), i, nstars, r, x, X, y, and Y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
