.TH "diff2Dpolymodel.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diff2Dpolymodel.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include '../utils/modefunc.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	diff2Dpolymodel --- differentiate \fBa\fP 2-dimensional spatial polynomial model\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	diff2Dpolymodel\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'diff2Dpolymodel' reads from stdin \fBa\fP 2D polynomial model file with\\\fBn\fP\\	parameters for \fBa\fP single variable and sends to stdout \fBa\fP 2D \fBpoly\fP model\\\fBn\fP\\	file for the two spatial derivatives of the variable.\\\fBn\fP\\\\\fBn\fP\\	This program requires that for each \fBl\fP, the \fBmode\fP values are\\\fBn\fP\\	supplied in the standard order: \fBi\fP.\fBe\fP. 0,1, ..... \fBl\fP.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser --- kaiser@ifa.hawaii.edu\\\fBn\fP\\\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	diff2Dpolymodel --- differentiate \fBa\fP 2-dimensional spatial polynomial model\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	diff2Dpolymodel\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'diff2Dpolymodel' reads from stdin \fBa\fP 2D polynomial model file with\\\fBn\fP\\	parameters for \fBa\fP single variable and sends to stdout \fBa\fP 2D \fBpoly\fP model\\\fBn\fP\\	file for the two spatial derivatives of the variable.\\\fBn\fP\\\\\fBn\fP\\	This program requires that for each \fBl\fP, the \fBmode\fP values are\\\fBn\fP\\	supplied in the standard order: \fBi\fP.\fBe\fP. 0,1, ..... \fBl\fP.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser --- kaiser@ifa.hawaii.edu\\\fBn\fP\\\\\fBn\fP'"
.PP
Definition at line 6 of file diff2Dpolymodel.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 30 of file diff2Dpolymodel.c.
.PP
References error_exit, get2Dpolymodel(), m, MODEFUNC_MAX_VARS, usage, and write2Dpolymodel().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
