.TH "distortion.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
distortion.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   'usage: distortion i0 j0\\\fBn\fP\\twhere (i0, j0) is nominal origin for chip\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   'usage: distortion i0 j0\\\fBn\fP\\twhere (i0, j0) is nominal origin for chip\\\fBn\fP'"
.PP
Definition at line 7 of file distortion.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 12 of file distortion.c.
.PP
References A, alpha, B, d, exit(), indx, line, m, mylubksb(), myludcmp(), usage, x, and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
