distortion.c
NAME
distortion.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
Defines
#define usage 'usage: distortion i0 j0\n\twhere (i0, j0) is nominal origin for chip\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage 'usage: distortion i0 j0\n\twhere (i0, j0) is nominal origin for chip\n'
Definition at line 7 of file distortion.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 12 of file distortion.c.
References A, alpha, B, d, exit(), indx, line, m, mylubksb(), myludcmp(), usage, x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.