.TH "doublecomplex" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doublecomplex \- 
.SH SYNOPSIS
.br
.PP
\fC#include <f2c.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdoublereal\fP \fBr\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBi\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBdoublereal\fP \fBdoublecomplex::i\fP"
.PP
Definition at line 17 of file myf2c.h.
.SS "\fBdoublereal\fP \fBdoublecomplex::r\fP"
.PP
Definition at line 17 of file myf2c.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
