ecorrect.c
NAME
ecorrect.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include '../../utils/error.h'
#include '../../catlib/cat.h'
#include 'efit_stuff.h'
Defines
#define usage '\n\n\n\NAME\n\	ecorrect --- correct ellipticities for psf anisotropy\n\\n\SYNOPSIS\n\	ecorrect [option...]\n\		-f efitdata		# file for stellar e / psm model parameters (efit.out)\n\\n\DESCRIPTION\n\	\'ecorrect\' reads a catalogue from stdin and corrects ellipticities\n\	according to model for psf polarization p = e / psm as determined by efit.\n\	Correction applied is e -= psm * p.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	ecorrect --- correct ellipticities for psf anisotropy\n\\n\SYNOPSIS\n\	ecorrect [option...]\n\		-f efitdata		# file for stellar e / psm model parameters (efit.out)\n\\n\DESCRIPTION\n\	\'ecorrect\' reads a catalogue from stdin and corrects ellipticities\n\	according to model for psf polarization p = e / psm as determined by efit.\n\	Correction applied is e -= psm * p.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file ecorrect.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 28 of file ecorrect.c.
References addargscomment(), object::addrlist, allocobjectcontents(), BINARY_FILE_TYPE, connectobjecttocathead(), e, error_exit, exit(), g(), getobjectitemindex(), i, N, newobject(), nmodes, order, readamplitudes(), readcathead(), readobject(), setcatopfiletype(), setframesize(), usage, writecathead(), writeobject(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.