.TH "ecorrect.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecorrect.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include '../../utils/error.h'\fP
.br
\fC#include '../../catlib/cat.h'\fP
.br
\fC#include 'efit_stuff.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	ecorrect --- correct ellipticities for psf anisotropy\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	ecorrect [option...]\\\fBn\fP\\		-f  efitdata		# file for stellar \fBe\fP / psm model parameters (efit.out)\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	\\'ecorrect\\' reads \fBa\fP catalogue from stdin and corrects ellipticities\\\fBn\fP\\	according to model for psf polarization p = \fBe\fP / psm as determined by efit.\\\fBn\fP\\	Correction applied is \fBe\fP -= psm * p.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser --- kaiser@cita.utoronto.ca\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	ecorrect --- correct ellipticities for psf anisotropy\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	ecorrect [option...]\\\fBn\fP\\		-f  efitdata		# file for stellar \fBe\fP / psm model parameters (efit.out)\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	\\'ecorrect\\' reads \fBa\fP catalogue from stdin and corrects ellipticities\\\fBn\fP\\	according to model for psf polarization p = \fBe\fP / psm as determined by efit.\\\fBn\fP\\	Correction applied is \fBe\fP -= psm * p.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser --- kaiser@cita.utoronto.ca\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 1 of file ecorrect.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 28 of file ecorrect.c.
.PP
References addargscomment(), object::addrlist, allocobjectcontents(), BINARY_FILE_TYPE, connectobjecttocathead(), e, error_exit, exit(), g(), getobjectitemindex(), i, N, newobject(), nmodes, order, readamplitudes(), readcathead(), readobject(), setcatopfiletype(), setframesize(), usage, writecathead(), writeobject(), and x.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
