.TH "edge" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edge \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshelle\fP * \fBsh\fP"
.br
.ti -1c
.RI "int \fBshorient\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBshelle\fP* \fBedge::sh\fP"
.PP
Definition at line 506 of file triangle.c.
.PP
Referenced by checkdelaunay(), constrainededge(), delaunayfixup(), deletesite(), flip(), highorder(), infecthull(), insertshelle(), insertsite(), plague(), printshelle(), printtriangle(), reconstruct(), regionplague(), repairencs(), scoutsegment(), tallyencs(), testtriangle(), writeedges(), and writepoly().
.SS "int \fBedge::shorient\fP"
.PP
Definition at line 507 of file triangle.c.
.PP
Referenced by printshelle(), printtriangle(), reconstruct(), tallyencs(), and writepoly().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
