edw.c
NAME
edw.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'imlib/fits.h'
#include 'utils/error.h'
#include 'utils/args.h'
#include 'utils/arrays.h'
#include 'fftlib/myfft.h'
Defines
#define usage '\nNAME\n\	edw - evolve dispersive waves\n\\n\SYNOPSIS\n\	edw dt [-ocean | -debroglie | -scalar kstar] [-verbose][-novideo]\n\\n\DESCRIPTION\n\	Edw reads a 3D FITS image f[2][Ny][Nx] from standard input,\n\	the two planes of which are the initial field f = f[0] and\n\	the initial velocity fdot = f[1].\n\\n\	It computes the transforms fk of f and fdotk of fdot and forms\n\	the positive frequency component:\n\		fp(k) 	= (fk + fdotk / i omega)\n\	It then computes and sends to stdout a stream of images\n\	containing the real part of the inverse transform of\n\		fp(k) * exp(i omega(k) * t).\n\	for t = integer multiples of dt.\n\\n\	By default, the dispersion relation is omega = k.\n\	With option -ocean we use omega = sqrt(k).\n\\n\	With the -novideo option we do not output a stream\n\	of images, rather we evolve for one step\n\	and then output an image f[2][Ny][Nx] containing the\n\	final field and velocity.\n\\n\	With -verbose option we tell stderr what we are doing.\n\\n\SEE ALSO\n\	generate_dw, evolvescalar, xfv\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
#define DR_DEFAULT 0
#define DR_OCEAN 1
#define DR_DEBROGLIE 2
#define DR_SCALAR 3
Functions
float omega (int ikx, int iky)
main (int argc, char *argv[])
Variables
float t
float dkx
float dky
float kstar
int dr
Define Documentation
#define DR_DEBROGLIE 2
Definition at line 51 of file edw.c.
Referenced by main(), and omega().
#define DR_DEFAULT 0
Definition at line 49 of file edw.c.
Referenced by main().
#define DR_OCEAN 1
Definition at line 50 of file edw.c.
Referenced by main(), and omega().
#define DR_SCALAR 3
Definition at line 52 of file edw.c.
Referenced by main(), and omega().
#define usage '\nNAME\n\	edw - evolve dispersive waves\n\\n\SYNOPSIS\n\	edw dt [-ocean | -debroglie | -scalar kstar] [-verbose][-novideo]\n\\n\DESCRIPTION\n\	Edw reads a 3D FITS image f[2][Ny][Nx] from standard input,\n\	the two planes of which are the initial field f = f[0] and\n\	the initial velocity fdot = f[1].\n\\n\	It computes the transforms fk of f and fdotk of fdot and forms\n\	the positive frequency component:\n\		fp(k) 	= (fk + fdotk / i omega)\n\	It then computes and sends to stdout a stream of images\n\	containing the real part of the inverse transform of\n\		fp(k) * exp(i omega(k) * t).\n\	for t = integer multiples of dt.\n\\n\	By default, the dispersion relation is omega = k.\n\	With option -ocean we use omega = sqrt(k).\n\\n\	With the -novideo option we do not output a stream\n\	of images, rather we evolve for one step\n\	and then output an image f[2][Ny][Nx] containing the\n\	final field and velocity.\n\\n\	With -verbose option we tell stderr what we are doing.\n\\n\SEE ALSO\n\	generate_dw, evolvescalar, xfv\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 10 of file edw.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 54 of file edw.c.
References add_comment(), allocFloatArray(), argsinit(), dkx, dky, dr, DR_DEBROGLIE, DR_DEFAULT, DR_OCEAN, DR_SCALAR, error_exit, exit(), f, fits, flag, FLAG_ARG, forward_cfft(), getargd(), getargf(), getflag(), i, inverse_cfft(), kstar, fitsheader::n, fitsheader::ndim, nextargtype(), Nx, Ny, omega(), readfitsheader(), readfitsplane(), t, usage, verbose, writefitsheader(), writefitsplane(), x, and y.
float omega (int ikx, int iky)
Definition at line 212 of file edw.c.
References dkx, dky, dr, DR_DEBROGLIE, DR_OCEAN, DR_SCALAR, and kstar.
Referenced by cartesiantokepler(), keplertocartesian(), keplertocartesian_shapiro(), and main().
Variable Documentation
float dkx
Definition at line 46 of file edw.c.
Referenced by main(), and omega().
float dky
Definition at line 46 of file edw.c.
Referenced by main(), and omega().
int dr
Definition at line 47 of file edw.c.
Referenced by apphot(), deltam(), getobjects(), main(), and omega().
float kstar
Definition at line 46 of file edw.c.
Referenced by main(), and omega().
float t
Definition at line 46 of file edw.c.
Author
Generated automatically by Doxygen for imcat from the source code.