efit_stuff.c
NAME
efit_stuff.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include '../../utils/error.h'
#include 'efit_stuff.h'
Functions
double g (int mode, double xx, double yy)
void readamplitudes (int *nmodes, int *framesize, int *order, double ***amp, FILE *stream)
void writeamplitudes (int nmodes, int order, int framesize, double **amp)
void setframesize (int N)
Variables
int framesize
Function Documentation
double g (int mode, double xx, double yy)
Definition at line 15 of file efit_stuff.c.
Referenced by addjupitergravity(), eps_setCmap(), frprmn(), getcolormap(), getrgbfromcmap(), main(), make_pop(), platepix(), poidev(), set_shades(), and tcl().
void readamplitudes (int * nmodes, int * framesize, int * order, double *** amp, FILE * stream)
Definition at line 117 of file efit_stuff.c.
void setframesize (int N)
Definition at line 164 of file efit_stuff.c.
void writeamplitudes (int nmodes, int order, int framesize, double ** amp)
Definition at line 152 of file efit_stuff.c.
Variable Documentation
int framesize [static]
Definition at line 13 of file efit_stuff.c.
Referenced by g(), readamplitudes(), setframesize(), and writeamplitudes().
Author
Generated automatically by Doxygen for imcat from the source code.