eps.c
NAME
eps.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <time.h>
#include <pwd.h>
#include 'cdl.h'
Data Structures
struct PSPageInfo
Defines
#define CDL_LIBRARY_SOURCE
#define MAX_LENLABEL 256
#define SZ_EPSBUF 8193
#define PageXdim(ps) ( PageInfo[ps->page.page_type].npixx )
#define PageYdim(ps) ( PageInfo[ps->page.page_type].npixy )
#define PageWidth(ps) ( PageInfo[ps->page.page_type].sizex )
#define PageHeight(ps) ( PageInfo[ps->page.page_type].sizey )
Functions
void eps_simpleHeader ()
void eps_colorHeader ()
void eps_pageParams ()
void eps_simpleTrailer ()
void eps_writeCmap ()
void eps_writeTrailer ()
void eps_writeMono ()
void eps_writePix ()
void eps_writeMonoRGB ()
void eps_writeRGB ()
void eps_putPix ()
void eps_flushPix ()
void eps_annotate ()
void eps_portLabels ()
void eps_landLabels ()
void eps_doColorbar ()
float ticstep ()
char * make_label ()
PSImage * eps_init ()
void eps_print (PSImage *psim, FILE *fp, uchar *data, int xdim, int ydim, int depth, int pad)
void eps_close (PSImage *psim)
void eps_setPage (PSImage *psim, int orientation, int paper_size, int scale, int flags)
void eps_setCmap (PSImage *psim, uchar *r, uchar *g, uchar *b, int ncolors)
void eps_setCompress (PSImage *psim, int compress)
void eps_setColorType (PSImage *psim, int color_class)
void eps_setLabel (PSImage *psim, char *label)
void eps_setTransform (PSImage *psim, float z1, float z2, int ztype, float offset, float scale, char *cmap_name)
void eps_setCorners (PSImage *psim, int llx, int lly, int urx, int ury)
void eps_getImageSize (PSImagePtr psim, int xdim, int ydim, float *width, float *height)
void eps_getImagePos (PSImagePtr psim, int xdim, int ydim, int *llx, int *lly)
void eps_pageParams (PSImagePtr psim, float *llx, float *lly, int *icols, int *irows, int *scols, int *srows, int *turnflag)
void eps_writePix (FILE *fp, uchar *pix, PSCmap *cmap, int npix, int xdim, int pad)
void eps_writeMono (FILE *fp, uchar *pix, PSCmap *cmap, int npix, int xdim, int pad)
void eps_writeMonoRGB (FILE *fp, uchar *pix, int npix, int xdim, int depth, int pad)
void eps_writeRGB (FILE *fp, uchar *pix, PSCmap *cmap, int npix, int xdim, int depth, int pad)
void eps_writeCmap (PSCmap *cmap, FILE *fp)
void eps_simpleHeader (PSImagePtr psim, FILE *fp)
void eps_annotate (PSImagePtr psim, FILE *fp)
void eps_portLabels (FILE *fp, PSImagePtr psim, int scols, int srows, int icols, int irows, float llx, float lly)
void eps_landLabels (FILE *fp, PSImagePtr psim, int scols, int srows, int icols, int irows, float llx, float lly)
void eps_doColorbar (FILE *fp, PSImagePtr psim, int scols, int srows, float llx, float lly, int turnflag)
void eps_colorHeader (PSImagePtr psim, FILE *fp)
void eps_writeTrailer (FILE *fp)
void eps_simpleTrailer (FILE *fp)
void eps_flushPix (FILE *fp)
float ticstep (float range, int nsteps)
Variables
char * hextab = '0123456789abcdef'
int pixnum = 0 lpix = 0
uchar * pixbuf
PSPageInfo PageInfo []
int debug = 0
char * EPSSimpleRLEProlog []
char * EPSColorProlog []
Define Documentation
#define CDL_LIBRARY_SOURCE
Definition at line 5 of file eps.c.
#define MAX_LENLABEL 256
Definition at line 59 of file eps.c.
Referenced by eps_init(), and eps_setLabel().
#define PageHeight(ps) ( PageInfo[ps->page.page_type].sizey )
Definition at line 72 of file eps.c.
#define PageWidth(ps) ( PageInfo[ps->page.page_type].sizex )
Definition at line 71 of file eps.c.
#define PageXdim(ps) ( PageInfo[ps->page.page_type].npixx )
Definition at line 69 of file eps.c.
Referenced by eps_pageParams().
#define PageYdim(ps) ( PageInfo[ps->page.page_type].npixy )
Definition at line 70 of file eps.c.
Referenced by eps_pageParams().
#define SZ_EPSBUF 8193
Definition at line 60 of file eps.c.
Referenced by eps_init(), eps_writeMono(), eps_writeMonoRGB(), eps_writePix(), and eps_writeRGB().
Function Documentation
void eps_annotate (PSImagePtr psim, FILE * fp) [static]
Definition at line 1210 of file eps.c.
References AXIS_IOFFSET, AXIS_IWIDTH, AXIS_OOFFSET, AXIS_OWIDTH, debug, eps_doColorbar(), eps_landLabels(), EPS_LINEAR, eps_pageParams(), eps_portLabels(), EPS_UNITARY, MAJOR_TICK_SIZE, MAJOR_TICK_WIDTH, make_label(), MAX, MIN, MINOR_TICK_SIZE, MINOR_TICK_WIDTH, PSImagePtr, and TITLE_OFFSET.
void eps_annotate () [static]
Referenced by eps_print().
void eps_close (PSImage * psim)
Definition at line 323 of file eps.c.
References free(), and pixbuf.
void eps_colorHeader (PSImagePtr psim, FILE	   * fp) [static]
Definition at line 1965 of file eps.c.
References eps_pageParams(), EPS_PSEUDOCOLOR, EPSColorProlog, line, MAX, NoCompression, PSImagePtr, X_ANNOT_MARGIN, and Y_ANNOT_MARGIN.
void eps_colorHeader ()
Referenced by eps_print().
void eps_doColorbar (FILE	* fp, PSImagePtr psim, int scols, int srows, float llx, float lly, int turnflag) [static]
Definition at line 1578 of file eps.c.
References EPS_GRAYSCALE, EPS_LINEAR, i, j, MAX, MIN, MONO, pos, PSImagePtr, and val.
void eps_doColorbar () [static]
Referenced by eps_annotate().
void eps_flushPix (FILE	* fp) [static]
Definition at line 2077 of file eps.c.
References pixbuf, and pixnum.
void eps_flushPix ()
Referenced by eps_writeMono(), eps_writeMonoRGB(), eps_writePix(), and eps_writeRGB().
void eps_getImagePos (PSImagePtr psim, int xdim, int ydim, int	* llx, int * lly)
Definition at line 642 of file eps.c.
References eps_pageParams(), ly, and PSImagePtr.
void eps_getImageSize (PSImagePtr psim, int xdim, int ydim, float	* width, float * height)
Definition at line 608 of file eps.c.
References eps_pageParams(), and PSImagePtr.
PSImage* eps_init ()
Definition at line 154 of file eps.c.
References EPS_AUTOSCALE, EPS_GRAYSCALE, EPS_LETTER, EPS_PORTRAIT, eps_setPage(), i, MAX_LENLABEL, NoCompression, pixbuf, ps(), SZ_EPSBUF, and uchar.
Referenced by cdl_printPix(), and cdl_printPixToFile().
void eps_landLabels (FILE	* fp, PSImagePtr psim, int scols, int srows, int icols, int irows, float llx, float lly) [static]
Definition at line 1475 of file eps.c.
References AXIS_OOFFSET, NTICMARKS, PSImagePtr, and ticstep().
void eps_landLabels ()
Referenced by eps_annotate().
void eps_pageParams (PSImagePtr psim, float	* llx, float * lly, int	* icols, int * irows, int	* scols, int * srows, int	* turnflag) [static]
Definition at line 683 of file eps.c.
References debug, DoAutoRotate, DoAutoScale, DoMaxAspect, EPS_LANDSCAPE, PageXdim, PageYdim, PSImagePtr, Scale, and scale.
void eps_pageParams () [static]
Referenced by eps_annotate(), eps_colorHeader(), eps_getImagePos(), eps_getImageSize(), and eps_simpleHeader().
void eps_portLabels (FILE	* fp, PSImagePtr psim, int scols, int srows, int icols, int irows, float llx, float lly) [static]
Definition at line 1371 of file eps.c.
References AXIS_OOFFSET, NTICMARKS, PSImagePtr, and ticstep().
void eps_portLabels ()
Referenced by eps_annotate().
void eps_print (PSImage * psim, FILE	* fp, uchar * data, int xdim, int ydim, int depth, int pad)
Definition at line 209 of file eps.c.
References debug, eps_annotate(), eps_colorHeader(), EPS_GRAYSCALE, EPS_PSEUDOCOLOR, eps_simpleHeader(), eps_simpleTrailer(), EPS_TRUECOLOR, eps_writeCmap(), eps_writeMono(), eps_writeMonoRGB(), eps_writePix(), eps_writeRGB(), eps_writeTrailer(), pix, and uchar.
void eps_putPix () [static]
void eps_setCmap (PSImage * psim, uchar * r, uchar * g, uchar * b, int ncolors)
Definition at line 407 of file eps.c.
References b, g(), i, r, and uchar.
void eps_setColorType (PSImage * psim, int color_class)
Definition at line 473 of file eps.c.
References EPS_GRAYSCALE, EPS_PSEUDOCOLOR, and EPS_TRUECOLOR.
void eps_setCompress (PSImage * psim, int compress)
Definition at line 440 of file eps.c.
References JPEGCompression, LZWCompression, NoCompression, and RLECompression.
void eps_setCorners (PSImage * psim, int llx, int lly, int urx, int ury)
Definition at line 580 of file eps.c.
void eps_setLabel (PSImage * psim, char	* label)
Definition at line 503 of file eps.c.
References label, malloc(), and MAX_LENLABEL.
void eps_setPage (PSImage * psim, int orientation, int paper_size, int scale, int flags)
Definition at line 350 of file eps.c.
References debug, DoAutoRotate, DoAutoScale, DoMaxAspect, EPS_LANDSCAPE, EPS_PORTRAIT, Orientation, PageInfo, PageType, Scale, and scale.
void eps_setTransform (PSImage * psim, float z1, float z2, int ztype, float offset, float scale, char	* cmap_name)
Definition at line 538 of file eps.c.
References debug, malloc(), scale, z1, and z2.
void eps_simpleHeader (PSImagePtr psim, FILE	   * fp) [static]
Definition at line 1122 of file eps.c.
References debug, eps_pageParams(), EPS_TRUECOLOR, EPSSimpleRLEProlog, line, MAX, PSImagePtr, RLECompression, X_ANNOT_MARGIN, and Y_ANNOT_MARGIN.
void eps_simpleHeader () [static]
Referenced by eps_print().
void eps_simpleTrailer (FILE	* fp) [static]
Definition at line 2062 of file eps.c.
void eps_simpleTrailer ()
Referenced by eps_print().
void eps_writeCmap (PSCmap 	* cmap, FILE	* fp) [static]
Definition at line 1058 of file eps.c.
References cmap, i, and j.
void eps_writeCmap () [static]
Referenced by eps_print().
void eps_writeMono (FILE	* fp, uchar * pix, PSCmap 	* cmap, int npix, int xdim, int pad) [static]
Definition at line 880 of file eps.c.
References cmap, eps_flushPix(), hextab, i, max, min, MONO, pix, PIX_PER_LINE, pixbuf, pixnum, SZ_EPSBUF, and uchar.
void eps_writeMono () [static]
Referenced by eps_print().
void eps_writeMonoRGB (FILE * fp, uchar * pix, int npix, int xdim, int depth, int pad) [static]
Definition at line 933 of file eps.c.
References eps_flushPix(), hextab, i, MONO, pix, PIX_PER_LINE, pixbuf, pixnum, SZ_EPSBUF, and uchar.
void eps_writeMonoRGB () [static]
Referenced by eps_print().
void eps_writePix (FILE * fp, uchar * pix, PSCmap 	* cmap, int npix, int xdim, int pad) [static]
Definition at line 831 of file eps.c.
References cmap, eps_flushPix(), hextab, i, max, min, pix, PIX_PER_LINE, pixbuf, pixnum, SZ_EPSBUF, and uchar.
void eps_writePix ()
Referenced by eps_print().
void eps_writeRGB (FILE * fp, uchar * pix, PSCmap 	* cmap, int npix, int xdim, int depth, int pad) [static]
Definition at line 987 of file eps.c.
References cmap, eps_flushPix(), hextab, i, max, min, pix, PIX_PER_LINE, pixbuf, pixnum, SZ_EPSBUF, uchar, and val.
void eps_writeRGB ()
Referenced by eps_print().
void eps_writeTrailer (FILE	* fp) [static]
Definition at line 2039 of file eps.c.
void eps_writeTrailer ()
Referenced by eps_print().
char * make_label () [static]
Definition at line 2150 of file eps.c.
References buf, and lt().
Referenced by eps_annotate().
float ticstep (float range, int nsteps) [static]
Definition at line 2100 of file eps.c.
References ticstep().
float ticstep () [static]
Referenced by eps_landLabels(), eps_portLabels(), and ticstep().
Variable Documentation
int debug = 0 [static]
Definition at line 141 of file eps.c.
Referenced by eps_annotate(), eps_pageParams(), eps_print(), eps_setPage(), eps_setTransform(), and eps_simpleHeader().
char* EPSColorProlog[] [static]
Definition at line 1722 of file eps.c.
Referenced by eps_colorHeader().
char* EPSSimpleRLEProlog[] [static]
Definition at line 1079 of file eps.c.
Referenced by eps_simpleHeader().
char* hextab = '0123456789abcdef'
Definition at line 65 of file eps.c.
Referenced by eps_writeMono(), eps_writeMonoRGB(), eps_writePix(), and eps_writeRGB().
PSPageInfo PageInfo[] [static]
Initial value:.nf
 {
        { 8.500, 11.000,
          612, 762
        },
        { 8.500, 14.000,
          612, 1008
        },
        { 8.267, 11.811,
          595, 850
        },
        { 7.283, 10.630,
          524, 765
        },
        {11.000, 17.000,
          762, 1224
        },
        { 3.875, 4.875,
          279, 351
        },
        { 0.945, 1.417,
          68, 102
        }
}
Definition at line 79 of file eps.c.
Referenced by eps_setPage().
uchar* pixbuf
Definition at line 67 of file eps.c.
Referenced by eps_close(), eps_flushPix(), eps_init(), eps_writeMono(), eps_writeMonoRGB(), eps_writePix(), and eps_writeRGB().
int pixnum = 0 lpix = 0
Definition at line 66 of file eps.c.
Referenced by eps_flushPix(), eps_writeMono(), eps_writeMonoRGB(), eps_writePix(), and eps_writeRGB().
Author
Generated automatically by Doxygen for imcat from the source code.