.TH "event" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
event \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "REAL \fBxkey\fP"
.br
.ti -1c
.RI "REAL \fBykey\fP"
.br
.ti -1c
.RI "VOID * \fBeventptr\fP"
.br
.ti -1c
.RI "int \fBheapposition\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "VOID* \fBevent::eventptr\fP"
.PP
Definition at line 549 of file triangle.c.
.SS "int \fBevent::heapposition\fP"
.PP
Definition at line 550 of file triangle.c.
.SS "REAL \fBevent::xkey\fP"
.PP
Definition at line 548 of file triangle.c.
.SS "REAL \fBevent::ykey\fP"
.PP
Definition at line 548 of file triangle.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
