evolveorbits.c
NAME
evolveorbits.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include 'vectors.h'
#include 'tcl.h'
#include 'utils/ipbuff.h'
#include 'kepler.h'
#include 'extravars.h'
Defines
#define usage '\nNAME\n\	evolveorbits - evolve orbits by two-body or time-centered leapfrog\n\\n\SYNOPSIS\n\	evolveorbits dt nsteps [-writekepler] [-tcl nsubsteps] [-extravars vardefs] [-jupiter phase]\n\\n\DESCRIPTION\n\	evolveorbits reads an lc catalog containing a set of positions r[3]\n\	and velocities v[3] from stdin, evolves the positions and\n\	velocities through nsteps steps of length and writes the results\n\	to stdout.\n\\n\	By default, it does this by converting from phase-space to\n\	Kepler orbital elements (a, e, i, omega, Omega, M) and incrementing\n\	M and then performing the inverse transformation.\n\\n\	With -writekepler option, we also output the orbital elements.\n\\n\	With -extravars option we carry defined variables along. For example, use\n\		-extrvars myscalar:1:myvector:3\n\	to carry along myscalar and myvector[3]\n\\n\	With option -tcl we do the evolution using time-centered\n\	leapfrog with nsubsteps steps of length dt / nsubsteps\n\\n\	Times are given in units of earths dynamical time (approx 58 days).\n\	Distances are in AU.\n\\n\SEE ALSO\n\	maketestpparfile.pl makeobs_circ laplace3 evolve\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	evolveorbits - evolve orbits by two-body or time-centered leapfrog\n\\n\SYNOPSIS\n\	evolveorbits dt nsteps [-writekepler] [-tcl nsubsteps] [-extravars vardefs] [-jupiter phase]\n\\n\DESCRIPTION\n\	evolveorbits reads an lc catalog containing a set of positions r[3]\n\	and velocities v[3] from stdin, evolves the positions and\n\	velocities through nsteps steps of length and writes the results\n\	to stdout.\n\\n\	By default, it does this by converting from phase-space to\n\	Kepler orbital elements (a, e, i, omega, Omega, M) and incrementing\n\	M and then performing the inverse transformation.\n\\n\	With -writekepler option, we also output the orbital elements.\n\\n\	With -extravars option we carry defined variables along. For example, use\n\		-extrvars myscalar:1:myvector:3\n\	to carry along myscalar and myvector[3]\n\\n\	With option -tcl we do the evolution using time-centered\n\	leapfrog with nsubsteps steps of length dt / nsubsteps\n\\n\	Times are given in units of earths dynamical time (approx 58 days).\n\	Distances are in AU.\n\\n\SEE ALSO\n\	maketestpparfile.pl makeobs_circ laplace3 evolve\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 11 of file evolveorbits.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 46 of file evolveorbits.c.
References keplerorbit::a, cartesiantokepler(), dotcl, exit(), fillbufferfromkeplerorbit(), i, ipf, jupiteron(), keplertocartesian(), keplerorbit::M, parseextravars(), r, readdoublebuff(), t, tcl(), theorbit, usage, and v.
Author
Generated automatically by Doxygen for imcat from the source code.