evolvescalar.c
NAME
evolvescalar.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/args.h'
#include 'utils/arrays.h'
#include 'imlib/fits.h'
Defines
#define NSTEPS 10
#define KSTAR 0.3
#define DT 0.2
#define LAMBDA 0.0
#define GAMMA 0.0
#define swap(a, b) tmp=(a);(b)=(a);(a)=tmp
#define MAX_FRAMES 99999
#define USAGE '\nNAME\n\	evolvescalar - evolve a 2-D scalar field\n\\n\SYNOPSIS\n\	evolvescalar [-nsteps nsteps (10)] [-nframes nframes (99999)]\n\		[-kstar kstar (0.3)] [-autoscale] [-dt dt (0.2)]\n\		[-lambda lambda (0.0)] [-gamma gamma (0.0)] [-u]\n\		[-gravity V0 sigma]\n\\n\DESCRIPTION\n\	Evolvescalar reads from stdin a 3-D FITS file f[2][Ny][Nx] consisting\n\	of 2 planes containing the initial field d[Ny][Nx] and the initial\n\	field velocity v[Ny][Nx].\n\	It then evolves the coupled equations\n\		dv/dt = laplacian(d) - kstar^2 d - 4 lambda d^3 - gamma v\n\		dd/dt = v\n\	With gamma = 0 these are equivalent to the Klein-Gordon equation\n\	with mass ~ kstar and a lambda phi^4 self-interaction.\n\\n\	With -gravity option we replace kstar by\n\	kstar (1 - V0 exp(-0.5 r**2 / sigma**2)). This simulates the effect of\n\	a fixed external gravitational potential.\n\\n\	With non-zero damping coefficient gamma, the waves evolve as\n\	in an expanding universe with H = gamma / 3.\n\\n\	If kstar is negative, it evolves\n\		dv/dt = laplacian(d) + kstar^2 d - 4 lambda d^3 - gamma v\n\		dd/dt = v\n\\n\	which has a negative mass term and gives a 'w'-shaped potential.\n\\n\	The laplacian function is computed as\n\\n\	laplacian = d[y][x-1] + d[y][x+1] + d[y-1][x] + d[y+1][x] - 4 * d[y][x].\n\\n\	The evolution scheme is\n\		v += 0.5 * dv/dt * dt\n\		d += dd/dt * dt\n\		v += 0.5 * dv/dt * dt\n\\n\	It outputs a 3-D FITS file f[nframes][Ny][Nx] containing the\n\	evolved field.\n\\n\OPTIONS\n\		-nsteps nsteps		# number of steps between output frames\n\		-nframes nframes	# total number of output frames\n\		-kstar kstar		# Compton wave-number\n\		-autoscale		# scale each output frame to 0-256\n\		-dt dt			# time-step\n\		-lambda lambda		# interaction strength\n\		-gamma gamma		# damping rate\n\		-u			# print man-page\n\\n\SEE ALSO\n\	edw, generate_dw\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
void outputframe (float **d, float **dout, int Nx, int Ny, int autoscale, int i)
main (int argc, char *argv[])
Variables
fitsheader * fits
Define Documentation
#define DT 0.2
Definition at line 13 of file evolvescalar.c.
Referenced by main().
#define GAMMA 0.0
Definition at line 15 of file evolvescalar.c.
Referenced by main().
#define KSTAR 0.3
Definition at line 12 of file evolvescalar.c.
Referenced by main().
#define LAMBDA 0.0
Definition at line 14 of file evolvescalar.c.
#define MAX_FRAMES 99999
Definition at line 18 of file evolvescalar.c.
#define NSTEPS 10
Definition at line 11 of file evolvescalar.c.
Referenced by main().
#define swap(a, b) tmp=(a);(b)=(a);(a)=tmp
Definition at line 17 of file evolvescalar.c.
Referenced by amoeba().
#define USAGE '\nNAME\n\	evolvescalar - evolve a 2-D scalar field\n\\n\SYNOPSIS\n\	evolvescalar [-nsteps nsteps (10)] [-nframes nframes (99999)]\n\		[-kstar kstar (0.3)] [-autoscale] [-dt dt (0.2)]\n\		[-lambda lambda (0.0)] [-gamma gamma (0.0)] [-u]\n\		[-gravity V0 sigma]\n\\n\DESCRIPTION\n\	Evolvescalar reads from stdin a 3-D FITS file f[2][Ny][Nx] consisting\n\	of 2 planes containing the initial field d[Ny][Nx] and the initial\n\	field velocity v[Ny][Nx].\n\	It then evolves the coupled equations\n\		dv/dt = laplacian(d) - kstar^2 d - 4 lambda d^3 - gamma v\n\		dd/dt = v\n\	With gamma = 0 these are equivalent to the Klein-Gordon equation\n\	with mass ~ kstar and a lambda phi^4 self-interaction.\n\\n\	With -gravity option we replace kstar by\n\	kstar (1 - V0 exp(-0.5 r**2 / sigma**2)). This simulates the effect of\n\	a fixed external gravitational potential.\n\\n\	With non-zero damping coefficient gamma, the waves evolve as\n\	in an expanding universe with H = gamma / 3.\n\\n\	If kstar is negative, it evolves\n\		dv/dt = laplacian(d) + kstar^2 d - 4 lambda d^3 - gamma v\n\		dd/dt = v\n\\n\	which has a negative mass term and gives a 'w'-shaped potential.\n\\n\	The laplacian function is computed as\n\\n\	laplacian = d[y][x-1] + d[y][x+1] + d[y-1][x] + d[y+1][x] - 4 * d[y][x].\n\\n\	The evolution scheme is\n\		v += 0.5 * dv/dt * dt\n\		d += dd/dt * dt\n\		v += 0.5 * dv/dt * dt\n\\n\	It outputs a 3-D FITS file f[nframes][Ny][Nx] containing the\n\	evolved field.\n\\n\OPTIONS\n\		-nsteps nsteps		# number of steps between output frames\n\		-nframes nframes	# total number of output frames\n\		-kstar kstar		# Compton wave-number\n\		-autoscale		# scale each output frame to 0-256\n\		-dt dt			# time-step\n\		-lambda lambda		# interaction strength\n\		-gamma gamma		# damping rate\n\		-u			# print man-page\n\\n\SEE ALSO\n\	edw, generate_dw\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 20 of file evolvescalar.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 85 of file evolvescalar.c.
References add_comment(), allocFloatArray(), argsinit(), d, DT, dx, error_exit, exit(), f, fits, flag, GAMMA, getargd(), getargi(), getflag(), i, KSTAR, kstar, LAMBDA, MAX_FRAMES, fitsheader::n, fitsheader::ndim, nframes, NSTEPS, Nx, Ny, outputframe(), readfitsheader(), readfitsplane(), sigma, USAGE, v, writefitsheader(), writefitstail(), x, xp(), y, and yp().
void outputframe (float ** d, float ** dout, int Nx, int Ny, int autoscale, int i)
Definition at line 221 of file evolvescalar.c.
References d, dmax, dmin, fits, i, Nx, Ny, writefitsplane(), x, and y.
Referenced by main().
Variable Documentation
fitsheader* fits [static]
Definition at line 81 of file evolvescalar.c.
Author
Generated automatically by Doxygen for imcat from the source code.