.TH "extravars.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extravars.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBparseextravars\fP (char *definitions, int *thesize, char **iplist, char **opdefs)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void parseextravars (char * definitions, int * thesize, char ** iplist, char ** opdefs)"
.PP
Definition at line 11 of file extravars.c.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
