.TH "ezffti.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ezffti.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBezffti_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *wsave)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ezffti_ (\fBinteger\fP * n, \fBreal\fP * wsave)"
.PP
Definition at line 9 of file ezffti.c.
.PP
References ezfft1_(), integer, n, and real.
.PP
Referenced by MAIN__().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
