.TH "ezfftf.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ezfftf.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBezfftf_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *r__, \fBreal\fP *azero, \fBreal\fP *\fBa\fP, \fBreal\fP *\fBb\fP, \fBreal\fP *wsave)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ezfftf_ (\fBinteger\fP * n, \fBreal\fP * r__, \fBreal\fP * azero, \fBreal\fP * a, \fBreal\fP * b, \fBreal\fP * wsave)"
.PP
Definition at line 9 of file ezfftf.c.
.PP
References a, b, integer, n, real, and rfftf_().
.PP
Referenced by MAIN__().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
