f1dim.h
NAME
f1dim.h -
SYNOPSIS
Functions
float f1dim (float x)
Function Documentation
float f1dim (float x)
Definition at line 14 of file f1dim.c.
References f, free_vector(), j, ncom, pcom, vector(), x, and xicom.
Referenced by linmin().
Author
Generated automatically by Doxygen for imcat from the source code.