.TH "f1dim.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f1dim.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBf1dim\fP (float x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float f1dim (float x)"
.PP
Definition at line 14 of file f1dim.c.
.PP
References f, free_vector(), j, ncom, pcom, vector(), x, and xicom.
.PP
Referenced by linmin().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
