f1dim.c
NAME
f1dim.c -
SYNOPSIS
#include <stdio.h>
#include 'f1dim.h'
#include 'nrutil.h'
Functions
float f1dim (float x)
Variables
int ncom
float * pcom
float * xicom
float(* nrfunc )()
Function Documentation
float f1dim (float x)
Definition at line 14 of file f1dim.c.
References f, free_vector(), j, ncom, pcom, vector(), x, and xicom.
Referenced by linmin().
Variable Documentation
int ncom
Definition at line 11 of file f1dim.c.
float(* nrfunc)()
Definition at line 12 of file f1dim.c.
float* pcom
Definition at line 12 of file f1dim.c.
float * xicom
Definition at line 12 of file f1dim.c.
Author
Generated automatically by Doxygen for imcat from the source code.