.TH "f1dim.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f1dim.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include 'f1dim.h'\fP
.br
\fC#include 'nrutil.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBf1dim\fP (float x)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBncom\fP"
.br
.ti -1c
.RI "float * \fBpcom\fP"
.br
.ti -1c
.RI "float * \fBxicom\fP"
.br
.ti -1c
.RI "float(* \fBnrfunc\fP )()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float f1dim (float x)"
.PP
Definition at line 14 of file f1dim.c.
.PP
References f, free_vector(), j, ncom, pcom, vector(), x, and xicom.
.PP
Referenced by linmin().
.SH "Variable Documentation"
.PP 
.SS "int \fBncom\fP"
.PP
Definition at line 11 of file f1dim.c.
.SS "float(* \fBnrfunc\fP)()"
.PP
Definition at line 12 of file f1dim.c.
.SS "float* \fBpcom\fP"
.PP
Definition at line 12 of file f1dim.c.
.SS "float * \fBxicom\fP"
.PP
Definition at line 12 of file f1dim.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
