.TH "FbConfig" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FbConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnframes\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBFbConfig::height\fP"
.PP
Definition at line 149 of file vximtool.c.
.SS "int \fBFbConfig::nframes\fP"
.PP
Definition at line 147 of file vximtool.c.
.SS "int \fBFbConfig::width\fP"
.PP
Definition at line 148 of file vximtool.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
