.TH "FBTab" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FBTab \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cdlP.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBconfig\fP"
.br
.ti -1c
.RI "int \fBnframes\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBFBTab::config\fP"
.PP
Definition at line 44 of file cdlP.h.
.PP
Referenced by cdl_selectFB().
.SS "int \fBFBTab::height\fP"
.PP
Definition at line 46 of file cdlP.h.
.PP
Referenced by cdl_selectFB().
.SS "int \fBFBTab::nframes\fP"
.PP
Definition at line 45 of file cdlP.h.
.PP
Referenced by cdl_selectFB().
.SS "int \fBFBTab::width\fP"
.PP
Definition at line 46 of file cdlP.h.
.PP
Referenced by cdl_selectFB().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
