.TH "FD_control_panel" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FD_control_panel \- 
.SH SYNOPSIS
.br
.PP
\fC#include <control_panel.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "FL_FORM * \fBcontrol_panel\fP"
.br
.ti -1c
.RI "void * \fBvdata\fP"
.br
.ti -1c
.RI "char * \fBcdata\fP"
.br
.ti -1c
.RI "long \fBldata\fP"
.br
.ti -1c
.RI "FL_OBJECT * \fBrewind_button\fP"
.br
.ti -1c
.RI "FL_OBJECT * \fBstop_button\fP"
.br
.ti -1c
.RI "FL_OBJECT * \fBrec_button\fP"
.br
.ti -1c
.RI "FL_OBJECT * \fBforward_step_button\fP"
.br
.ti -1c
.RI "FL_OBJECT * \fBframe_number_text\fP"
.br
.ti -1c
.RI "FL_OBJECT * \fBquit_button\fP"
.br
.ti -1c
.RI "FL_OBJECT * \fBcommand_input\fP"
.br
.ti -1c
.RI "FL_OBJECT * \fBzscale_counter\fP"
.br
.ti -1c
.RI "FL_OBJECT * \fBgo_button\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* \fBFD_control_panel::cdata\fP"
.PP
Definition at line 21 of file control_panel.h.
.SS "FL_OBJECT* \fBFD_control_panel::command_input\fP"
.PP
Definition at line 29 of file control_panel.h.
.PP
Referenced by create_form_control_panel(), and main().
.SS "FL_FORM* \fBFD_control_panel::control_panel\fP"
.PP
Definition at line 19 of file control_panel.h.
.PP
Referenced by create_form_control_panel(), and main().
.SS "FL_OBJECT* \fBFD_control_panel::forward_step_button\fP"
.PP
Definition at line 26 of file control_panel.h.
.PP
Referenced by create_form_control_panel().
.SS "FL_OBJECT* \fBFD_control_panel::frame_number_text\fP"
.PP
Definition at line 27 of file control_panel.h.
.PP
Referenced by create_form_control_panel(), and ReadNewFrame().
.SS "FL_OBJECT* \fBFD_control_panel::go_button\fP"
.PP
Definition at line 31 of file control_panel.h.
.PP
Referenced by create_form_control_panel().
.SS "long \fBFD_control_panel::ldata\fP"
.PP
Definition at line 22 of file control_panel.h.
.SS "FL_OBJECT* \fBFD_control_panel::quit_button\fP"
.PP
Definition at line 28 of file control_panel.h.
.PP
Referenced by create_form_control_panel().
.SS "FL_OBJECT* \fBFD_control_panel::rec_button\fP"
.PP
Definition at line 25 of file control_panel.h.
.PP
Referenced by create_form_control_panel().
.SS "FL_OBJECT* \fBFD_control_panel::rewind_button\fP"
.PP
Definition at line 23 of file control_panel.h.
.PP
Referenced by create_form_control_panel().
.SS "FL_OBJECT* \fBFD_control_panel::stop_button\fP"
.PP
Definition at line 24 of file control_panel.h.
.PP
Referenced by create_form_control_panel().
.SS "void* \fBFD_control_panel::vdata\fP"
.PP
Definition at line 20 of file control_panel.h.
.SS "FL_OBJECT* \fBFD_control_panel::zscale_counter\fP"
.PP
Definition at line 30 of file control_panel.h.
.PP
Referenced by create_form_control_panel(), main(), and zscale_counter_callback().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
