fft.c
NAME
fft.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
#include '../fftlib/myfft.h'
Defines
#define usage '\n\n\n\NAME\n\	fft --- take the fast fourier transform of a fits image\n\\n\SYNOPSIS\n\	fft [options...]\n\\n\DESCRIPTION\n\	'fft' creates a three dimensional image with dimensions\n\	N1 = Nx, N2 = Ny, N3 = 2 whose zeroth and first planes\n\	contain the real/imaginary parts of the discrete fft of the\n\	input image. Zero spatial fequency lives at Nx/2, Ny/2.\n\	Options are:\n\		-s		# output 16 bit image\n\		-i		# output 32 bit int format image\n\		-n		# no MAGIC substitution\n\		-m magicval	# replacement for MAGIC pixels (0)\n\		-c		# don't cycle input image.\n\		-I		# perform inverse transform.\n\		-C		# complex fft \n\	Default output image format is BITPIX = -32 (i.e. 4-byte real).\n\\n\	With the numerical-recipes fft package this only works for\n\	image dimensions 2^N.\n\\n\	This may be useful for `psf-surgery':\n\	You could 'fft' a composite psf image; modify the fft e.g.\n\	by dividing it into some desired circular psf, and then apply\n\	the fft as a filter to your original image using 'smooth -F'\n\	and --- hey presto! --- your psf is now circular.\n\\n\	By default, and when doing a forward transform\n\	the input image will be cycled by N1/2, N2/2, but\n\	you can override this with -c option.\n\\n\	There is redundancy in the fft image created from real input since\n\	f(-k) = f^*(-k).\n\\n\	Use -C option to take tranform of a complex function.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	fft --- take the fast fourier transform of a fits image\n\\n\SYNOPSIS\n\	fft [options...]\n\\n\DESCRIPTION\n\	'fft' creates a three dimensional image with dimensions\n\	N1 = Nx, N2 = Ny, N3 = 2 whose zeroth and first planes\n\	contain the real/imaginary parts of the discrete fft of the\n\	input image. Zero spatial fequency lives at Nx/2, Ny/2.\n\	Options are:\n\		-s		# output 16 bit image\n\		-i		# output 32 bit int format image\n\		-n		# no MAGIC substitution\n\		-m magicval	# replacement for MAGIC pixels (0)\n\		-c		# don't cycle input image.\n\		-I		# perform inverse transform.\n\		-C		# complex fft \n\	Default output image format is BITPIX = -32 (i.e. 4-byte real).\n\\n\	With the numerical-recipes fft package this only works for\n\	image dimensions 2^N.\n\\n\	This may be useful for `psf-surgery':\n\	You could 'fft' a composite psf image; modify the fft e.g.\n\	by dividing it into some desired circular psf, and then apply\n\	the fft as a filter to your original image using 'smooth -F'\n\	and --- hey presto! --- your psf is now circular.\n\\n\	By default, and when doing a forward transform\n\	the input image will be cycled by N1/2, N2/2, but\n\	you can override this with -c option.\n\\n\	There is redundancy in the fft image created from real input since\n\	f(-k) = f^*(-k).\n\\n\	Use -C option to take tranform of a complex function.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file fft.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 56 of file fft.c.
References add_comment(), alloc_fft(), allocFloatArray(), cycleimage(), error_exit, exit(), fitsheader::extpixtype, fft_type, fits, FLOAT_PIXTYPE, forward_cfft(), forward_fft(), freeFloatArray(), get_fft(), INT_PIXTYPE, inverse_cfft(), inverse_fft(), fitsheader::n, N1, N2, fitsheader::ndim, read2Dfloatimage(), readfitsheader(), readfitsline(), set_fft(), SHORT_PIXTYPE, substitute(), usage, write2Dfloatimage(), writefitsheader(), writefitsline(), writefitstail(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.