.TH "fft_task.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fft_task.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFORWARD_X\fP   0"
.br
.ti -1c
.RI "#define \fBFORWARD_Y\fP   1"
.br
.ti -1c
.RI "#define \fBINVERSE_X\fP   2"
.br
.ti -1c
.RI "#define \fBINVERSE_Y\fP   3"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define FORWARD_X   0"
.PP
Definition at line 7 of file fft_task.h.
.PP
Referenced by forward_fft(), and main().
.SS "#define FORWARD_Y   1"
.PP
Definition at line 8 of file fft_task.h.
.PP
Referenced by forward_fft(), and main().
.SS "#define INVERSE_X   2"
.PP
Definition at line 9 of file fft_task.h.
.PP
Referenced by inverse_fft(), and main().
.SS "#define INVERSE_Y   3"
.PP
Definition at line 10 of file fft_task.h.
.PP
Referenced by inverse_fft(), and main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
