fft_SGI.c
NAME
fft_SGI.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../lib/sgi_fft/sgi_fft.h'
#include 'myfft.h'
Functions
void forward_fft (float **f, int Nx, int Ny, fft_type fk)
void inverse_fft (fft_type fk, int Nx, int Ny, float **f)
void filter (fft_type fk, int Nx, int Ny, float(*filterfunc)(float ki, float kj))
void cfilter (fft_type fk, int Nx, int Ny, float(*rfunc)(float ki, float kj), float(*ifunc)(float ki, float kj))
void ccf (fft_type fk1, fft_type fk2, int Nx, int Ny, float **ff12, int x0, int y0)
void power (fft_type fk, int Nx, int Ny, float **p, int x0, int y0)
void alloc_fft (fft_type *fk, int Nx, int Ny)
void free_fft (fft_type fk, int Nx, int Ny)
void copy_fft (fft_type fksrc, int Nx, int Ny, fft_type fkdest)
void get_fft (fft_type fk, int Nx, int Ny, float **fdest)
void set_fft (fft_type fk, int Nx, int Ny, float **fsrc)
Function Documentation
void alloc_fft (fft_type * fk, int Nx, int Ny)
Definition at line 158 of file fft_SGI.c.
References error_exit, fft_type, n, Nx, Ny, and y.
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void ccf (fft_type fk1, fft_type fk2, int Nx, int Ny, float ** ff12, int x0, int y0)
Definition at line 103 of file fft_SGI.c.
References a1, a2, b1, b2, cycleimage(), fft_type, inverse_fft(), ix, n, Nx, and Ny.
Referenced by main().
void cfilter (fft_type fk, int Nx, int Ny, float(* rfunc)(float ki, float kj), float(* ifunc)(float ki, float kj))
Definition at line 80 of file fft_SGI.c.
References fft_type, ifunc(), ix, n, Nx, Ny, PI, and rfunc().
Referenced by main().
void copy_fft (fft_type fksrc, int Nx, int Ny, fft_type fkdest)
Definition at line 179 of file fft_SGI.c.
References fft_type, n, Nx, Ny, x, and y.
Referenced by main().
void filter (fft_type fk, int Nx, int Ny, float(* filterfunc)(float ki, float kj))
Definition at line 61 of file fft_SGI.c.
References fft_type, ix, n, Nx, Ny, and PI.
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void forward_fft (float ** f, int Nx, int Ny, fft_type fk)
Definition at line 19 of file fft_SGI.c.
References cfftf_(), cffti_(), exit(), f, fft_type, FORWARD_X, FORWARD_Y, free(), n, nx, Nx, ny, Ny, r, rfftf_(), rffti_(), shmfree(), x, and y.
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void free_fft (fft_type fk, int Nx, int Ny)
Definition at line 171 of file fft_SGI.c.
References fft_type, and free().
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void get_fft (fft_type fk, int Nx, int Ny, float ** fdest)
Definition at line 194 of file fft_SGI.c.
References fft_type, ix, n, Nx, and Ny.
Referenced by main().
void inverse_fft (fft_type fk, int Nx, int Ny, float ** f)
Definition at line 41 of file fft_SGI.c.
References cfftb_(), cffti_(), exit(), f, fft_type, free(), INVERSE_X, INVERSE_Y, n, nx, Nx, ny, Ny, r, rfftb_(), rffti_(), shmfree(), x, and y.
Referenced by ccf(), exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void power (fft_type fk, int Nx, int Ny, float ** p, int x0, int y0)
Definition at line 127 of file fft_SGI.c.
References a, b, cycleimage(), fft_type, ix, n, Nx, Ny, x, and y.
Referenced by main().
void set_fft (fft_type fk, int Nx, int Ny, float ** fsrc)
Definition at line 220 of file fft_SGI.c.
References fft_type, ix, n, Nx, and Ny.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.