.TH "fft_NR.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fft_NR.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtransform\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBtransform\fP \fBtransform\fP"
.br
.ti -1c
.RI "typedef \fBtransform\fP * \fBfft_type\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBtransform\fP* \fBfft_type\fP"
.PP
Definition at line 9 of file fft_NR.h.
.SS "typedef struct \fBtransform\fP  \fBtransform\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
