fft_FFTW.c
NAME
fft_FFTW.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <math.h>
#include <fftw.h>
#include <rfftw.h>
#include 'myfft.h'
Defines
#define PI M_PI
Functions
void myfftwcfft (float **fsrc, int nx, int ny, float **fdst, int direction)
void forward_fft (float **f, int nx, int ny, fft_type fk)
void inverse_fft (fft_type fk, int nx, int ny, float **f)
void filter (fft_type fk, int Nx, int Ny, float(*filterfunc)(float ki, float kj))
void cfilter (fft_type fk, int Nx, int Ny, float(*rfunc)(float ki, float kj), float(*ifunc)(float ki, float kj))
void ccf (fft_type fk1, fft_type fk2, int Nx, int Ny, float **ff12, int x0, int y0)
void power (fft_type fk, int Nx, int Ny, float **p, int x0, int y0)
void alloc_fft (fft_type *fk, int Nx, int Ny)
void free_fft (fft_type fk, int Nx, int Ny)
void copy_fft (fft_type fksrc, int Nx, int Ny, fft_type fkdest)
void get_fft (fft_type fk, int Nx, int Ny, float **fdest)
void set_fft (fft_type fk, int Nx, int Ny, float **fsrc)
void forward_cfft (float **fsrc, int nx, int ny, float **fdst)
void inverse_cfft (float **fsrc, int nx, int ny, float **fdst)
Define Documentation
#define PI M_PI
Definition at line 25 of file fft_FFTW.c.
Function Documentation
void alloc_fft (fft_type * fk, int Nx, int Ny)
Definition at line 155 of file fft_FFTW.c.
References error_exit, fft_type, n, Nx, Ny, and y.
void ccf (fft_type fk1, fft_type fk2, int Nx, int Ny, float ** ff12, int x0, int y0)
Definition at line 103 of file fft_FFTW.c.
References a1, a2, b1, b2, cycleimage(), fft_type, inverse_fft(), ix, n, Nx, and Ny.
void cfilter (fft_type fk, int Nx, int Ny, float(* rfunc)(float ki, float kj), float(* ifunc)(float ki, float kj))
Definition at line 77 of file fft_FFTW.c.
References fft_type, ifunc(), ix, n, Nx, Ny, PI, and rfunc().
void copy_fft (fft_type fksrc, int Nx, int Ny, fft_type fkdest)
Definition at line 179 of file fft_FFTW.c.
References fft_type, n, Nx, Ny, x, and y.
void filter (fft_type fk, int Nx, int Ny, float(* filterfunc)(float ki, float kj))
Definition at line 57 of file fft_FFTW.c.
References fft_type, ix, n, Nx, Ny, and PI.
void forward_cfft (float ** fsrc, int nx, int ny, float ** fdst)
Definition at line 242 of file fft_FFTW.c.
References c, cfftf_(), cffti_(), cycleimage(), free(), myfftwcfft(), nx, ny, x, and y.
Referenced by main().
void forward_fft (float ** f, int nx, int ny, fft_type fk)
Definition at line 30 of file fft_FFTW.c.
References f, fft_type, nx, and ny.
void free_fft (fft_type fk, int Nx, int Ny)
Definition at line 171 of file fft_FFTW.c.
References fft_type, and free().
void get_fft (fft_type fk, int Nx, int Ny, float ** fdest)
Definition at line 192 of file fft_FFTW.c.
References fft_type, ix, n, Nx, and Ny.
void inverse_cfft (float ** fsrc, int nx, int ny, float ** fdst)
Definition at line 247 of file fft_FFTW.c.
References c, cfftb_(), cffti_(), cycleimage(), free(), myfftwcfft(), nx, ny, x, and y.
Referenced by main().
void inverse_fft (fft_type fk, int nx, int ny, float ** f)
Definition at line 39 of file fft_FFTW.c.
References f, fft_type, nx, ny, scale, x, and y.
void myfftwcfft (float ** fsrc, int nx, int ny, float ** fdst, int direction)
Definition at line 252 of file fft_FFTW.c.
References cycleimage(), free(), nx, ny, scale, x, and y.
Referenced by forward_cfft(), and inverse_cfft().
void power (fft_type fk, int Nx, int Ny, float ** p, int x0, int y0)
Definition at line 128 of file fft_FFTW.c.
References fft_type, ix, n, Nx, Ny, and scale.
void set_fft (fft_type fk, int Nx, int Ny, float ** fsrc)
Definition at line 221 of file fft_FFTW.c.
References fft_type, ix, n, Nx, and Ny.
Author
Generated automatically by Doxygen for imcat from the source code.