fft_NR.c
NAME
fft_NR.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../utils/nrutil.h'
#include 'myfft.h'
Defines
#define PI M_PI
Functions
void rlft3 (float ***data, float **speq, unsigned long nn1, unsigned long nn2, unsigned long nn3, int isign)
void fft_size (int Nx, int Ny, int *NFFTx, int *NFFTy)
void rotate (float *a, float *b, float phi)
void forward_fft (float **f, int Nx, int Ny, fft_type fk)
void inverse_fft (fft_type fk, int Nx, int Ny, float **f)
void filter (fft_type fk, int Nx, int Ny, float(*filterfunc)(float ki, float kj))
void cfilter (fft_type fk, int Nx, int Ny, float(*rfunc)(float ki, float kj), float(*ifunc)(float ki, float kj))
void ccf (fft_type fk1, fft_type fk2, int Nx, int Ny, float **ff12, int x0, int y0)
void power (fft_type fk, int Nx, int Ny, float **p, int x0, int y0)
void free_fft (fft_type fk, int Nx, int Ny)
void alloc_fft (fft_type *fk, int Nx, int Ny)
void copy_fft (fft_type fksrc, int Nx, int Ny, fft_type fkdest)
void get_fft (fft_type fk, int Nx, int Ny, float **fdest)
void set_fft (fft_type fk, int Nx, int Ny, float **fsrc)
Define Documentation
#define PI M_PI
Definition at line 15 of file fft_NR.c.
Function Documentation
void alloc_fft (fft_type * fk, int Nx, int Ny)
Definition at line 208 of file fft_NR.c.
References f3tensor(), fft_size(), fft_type, matrix(), Nx, and Ny.
void ccf (fft_type fk1, fft_type fk2, int Nx, int Ny, float ** ff12, int x0, int y0)
Definition at line 105 of file fft_NR.c.
References a1, a2, b1, b2, fft_size(), fft_type, inverse_fft(), Nx, Ny, phi, PI, and rotate().
void cfilter (fft_type fk, int Nx, int Ny, float(* rfunc)(float ki, float kj), float(* ifunc)(float ki, float kj))
Definition at line 76 of file fft_NR.c.
References fft_size(), fft_type, ifunc(), Nx, Ny, PI, and rfunc().
void copy_fft (fft_type fksrc, int Nx, int Ny, fft_type fkdest)
Definition at line 219 of file fft_NR.c.
References fft_size(), fft_type, Nx, and Ny.
void fft_size (int Nx, int Ny, int * NFFTx, int * NFFTy)
Definition at line 183 of file fft_NR.c.
References Nx, and Ny.
Referenced by alloc_fft(), ccf(), cfilter(), copy_fft(), filter(), forward_fft(), free_fft(), get_fft(), inverse_fft(), power(), and set_fft().
void filter (fft_type fk, int Nx, int Ny, float(* filterfunc)(float ki, float kj))
Definition at line 54 of file fft_NR.c.
References fft_size(), fft_type, Nx, Ny, and PI.
void forward_fft (float ** f, int Nx, int Ny, fft_type fk)
Definition at line 23 of file fft_NR.c.
References f, fft_size(), fft_type, Nx, Ny, rlft3(), x, and y.
void free_fft (fft_type fk, int Nx, int Ny)
Definition at line 171 of file fft_NR.c.
References fft_size(), fft_type, free(), free_f3tensor(), free_matrix(), Nx, and Ny.
void get_fft (fft_type fk, int Nx, int Ny, float ** fdest)
Definition at line 236 of file fft_NR.c.
References exit(), fft_size(), fft_type, ix, Nx, and Ny.
void inverse_fft (fft_type fk, int Nx, int Ny, float ** f)
Definition at line 40 of file fft_NR.c.
References f, fft_size(), fft_type, Nx, Ny, rlft3(), x, and y.
void power (fft_type fk, int Nx, int Ny, float ** p, int x0, int y0)
Definition at line 140 of file fft_NR.c.
References a, b, cycleimage(), fft_size(), fft_type, Nx, Ny, x, y, and yy.
void rlft3 (float *** data, float ** speq, unsigned long nn1, unsigned long nn2, unsigned long nn3, int isign)
Definition at line 3 of file rlft3.c.
References fourn(), and nrerror().
Referenced by forward_fft(), and inverse_fft().
void rotate (float * a, float * b, float phi)
Definition at line 195 of file fft_NR.c.
References a, A, b, B, c, and phi.
Referenced by ccf(), main(), and wcsset().
void set_fft (fft_type fk, int Nx, int Ny, float ** fsrc)
Definition at line 269 of file fft_NR.c.
References exit(), fft_size(), fft_type, ix, Nx, and Ny.
Author
Generated automatically by Doxygen for imcat from the source code.