fft_task.c
NAME
fft_task.c -
SYNOPSIS
#include <stdio.h>
#include <errno.h>
#include <sys/types.h>
#include <unistd.h>
#include '../fftlib/myfft.h'
#include '../utils/error.h'
#include 'fft_task.h'
Functions
main (int argc, char *argv[])
Variables
char * usage
Function Documentation
main (int argc, char * argv[])
Definition at line 39 of file fft_task.c.
References cfftb_(), cfftf_(), cffti_(), error_exit, exit(), FORWARD_X, FORWARD_Y, free(), INVERSE_X, INVERSE_Y, n, nx, ny, r, rfftb_(), rfftf_(), rffti_(), usage, x, and y.
Variable Documentation
char* usage
Initial value:.nf
 '\n\
NAME\n\
  fft_task --- fft engine for double processor\n\
\n\
SYNOPSYS\n\
  fft_task fr_shmid fk_shmid nx ny mode\n\
\n\
DESCRIPTION\n\
  'fft_task' is invoked to handle 2-D FFTPACK fft's on\n\
  dual processor machines.\n\
  You should not have to invoke it directly.\n\
  It's first two arguments are the id's of shared\n\
  memory segments for the real-space and transformed\n\
  data. nx, ny are dimensions of the fft (must be\n\
  even), and mode can be one of\n\
    0 forward x-transforms\n\
    1 forward y-transforms\n\
    2 inverse x-transforms\n\
    3 inverse y-transforms\n\
\n\
AUTHOR\n\
  Nick Kaiser --- kaiser@ifa.hawaii.edu\n\
\n\n'
Definition at line 14 of file fft_task.c.
Author
Generated automatically by Doxygen for imcat from the source code.