test.c
NAME
test.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
MAIN__ ()
int tstfft_ ()
Variables
integer c_n1 = -1
integer c__1 = 1
Function Documentation
MAIN__ ()
Definition at line 14 of file fftpack_c/test.c.
References a, b, c__1, c_n1, cfftb_(), cfftf_(), cffti_(), cosqb_(), cosqf_(), cosqi_(), cost_(), costi_(), dabs, dmax, ezfftb_(), ezfftf_(), ezffti_(), ftnlen, complex::i, integer, j, k, max, n, complex::r, real, rfftb_(), rfftf_(), rffti_(), sinqb_(), sinqf_(), sinqi_(), sint_(), sinti_(), w, x, and y.
Referenced by tstfft_().
int tstfft_ ()
Definition at line 724 of file fftpack_c/test.c.
References MAIN__().
Variable Documentation
integer c__1 = 1 [static]
Definition at line 12 of file fftpack_c/test.c.
Referenced by MAIN__().
integer c_n1 = -1 [static]
Definition at line 11 of file fftpack_c/test.c.
Referenced by MAIN__().
Author
Generated automatically by Doxygen for imcat from the source code.