.TH "test.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBMAIN__\fP ()"
.br
.ti -1c
.RI "int \fBtstfft_\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBinteger\fP \fBc_n1\fP = -1"
.br
.ti -1c
.RI "\fBinteger\fP \fBc__1\fP = 1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "MAIN__ ()"
.PP
Definition at line 14 of file fftpack_c/test.c.
.PP
References a, b, c__1, c_n1, cfftb_(), cfftf_(), cffti_(), cosqb_(), cosqf_(), cosqi_(), cost_(), costi_(), dabs, dmax, ezfftb_(), ezfftf_(), ezffti_(), ftnlen, complex::i, integer, j, k, max, n, complex::r, real, rfftb_(), rfftf_(), rffti_(), sinqb_(), sinqf_(), sinqi_(), sint_(), sinti_(), w, x, and y.
.PP
Referenced by tstfft_().
.SS "int tstfft_ ()"
.PP
Definition at line 724 of file fftpack_c/test.c.
.PP
References MAIN__().
.SH "Variable Documentation"
.PP 
.SS "\fBinteger\fP \fBc__1\fP = 1\fC [static]\fP"
.PP
Definition at line 12 of file fftpack_c/test.c.
.PP
Referenced by MAIN__().
.SS "\fBinteger\fP \fBc_n1\fP = -1\fC [static]\fP"
.PP
Definition at line 11 of file fftpack_c/test.c.
.PP
Referenced by MAIN__().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
