.TH "Ffunc.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ffunc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'Ffunc.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBF\fP (double \fBd\fP, double mu)"
.br
.ti -1c
.RI "double \fBdFdd\fP (double \fBd\fP, double mu)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double dFdd (double d, double mu)"
.PP
Definition at line 17 of file Ffunc.c.
.PP
References d, and tmp.
.PP
Referenced by main(), and newtonraphson().
.SS "double F (double d, double mu)"
.PP
Definition at line 9 of file Ffunc.c.
.PP
References d, and tmp.
.PP
Referenced by cycleimage(), getshape2(), getshape3(), linmodelsolve(), main(), and newtonraphson().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
