Ffunc.c
NAME
Ffunc.c -
SYNOPSIS
#include <math.h>
#include 'Ffunc.h'
Functions
double F (double d, double mu)
double dFdd (double d, double mu)
Function Documentation
double dFdd (double d, double mu)
Definition at line 17 of file Ffunc.c.
References d, and tmp.
Referenced by main(), and newtonraphson().
double F (double d, double mu)
Definition at line 9 of file Ffunc.c.
References d, and tmp.
Referenced by cycleimage(), getshape2(), getshape3(), linmodelsolve(), main(), and newtonraphson().
Author
Generated automatically by Doxygen for imcat from the source code.