fillcores.c
NAME
fillcores.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/stats_stuff.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	fillcores --- patch up holes in stellar cores\n\\n\SYNOPSIS\n\	fillcores threshold replaceval [corevalue]\n\\n\DESCRIPTION\n\	fillcores is a crude kludge to patch up holes in stellar\n\	cores as sometimes get produced by clumsy image arithmetic.\n\	By default, any pixel with MAGIC value which has a neighbour with\n\	value exceeding 'threshold' will be replaced by 'replaceval'.\n\	If the optional third argument is given then any pixel\n\	with value 'corevalue' will be replaced by 'replaceval'.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	fillcores --- patch up holes in stellar cores\n\\n\SYNOPSIS\n\	fillcores threshold replaceval [corevalue]\n\\n\DESCRIPTION\n\	fillcores is a crude kludge to patch up holes in stellar\n\	cores as sometimes get produced by clumsy image arithmetic.\n\	By default, any pixel with MAGIC value which has a neighbour with\n\	value exceeding 'threshold' will be replaced by 'replaceval'.\n\	If the optional third argument is given then any pixel\n\	with value 'corevalue' will be replaced by 'replaceval'.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file fillcores.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 31 of file fillcores.c.
References add_comment(), allocFloatArray(), error_exit, exit(), f, fits, FLOAT_MAGIC, i, j, N1, N2, read2Dfloatimage(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.