filters.c
NAME
filters.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <limits.h>
#include '../utils/error.h'
#include 'filters.h'
#include 'fits.h'
#include '../fftlib/myfft.h'
Defines
#define max(a, b) ((a) < (b) ? (b) : (a))
#define min(a, b) ((a) < (b) ? (a) : (b))
#define ZMAX 10
Functions
void gaussian_kernel_filter (float **f, float **fs, int N1, int N2, int m, float rf)
void kernel_filter (float **f, float **fs, int N1, int N2, int m, float(*filterfunc)(int di, int dj))
void block_filter (float **f, float **fs, int N1, int N2, int m)
void tukey (float **f, int N1, int N2)
void schecterfilter (float **f, int N1, int N2, float **fs, float sigma1, float sigma2, float alpha, float magicsubstitute)
void kolmogorovfilter (float **f, int N1, int N2, float **fs, float sigma, float magicsubstitute)
void exponentialfilter (float **f, int N1, int N2, float **fs, float sigma, float gamma, float magicsubstitute)
void gaussfilter (float **f, int N1, int N2, float **fs, float A, float B, float phi, float magicsubstitute)
void mexicanfilter (float **f, int N1, int N2, float **fs, float sigma1, float sigma2, float magicsubstitute)
void powerlawfilter (float **f, int N1, int N2, float **fs, float alpha, float magicsubstitute)
void powerspectrum (float **f, int N1, int N2, float **P, int **nmodes)
float gaussianfilterfunc (int i, int j)
float schecterfilterfunction (float ki, float kj)
float kolmogorovfilterfunction (float ki, float kj)
float exponentialfilterfunction (float ki, float kj)
float gaussballfunction (float ki, float kj)
float gaussellipsoidfunction (float ki, float kj)
float mexicanfilterfunction (float ki, float kj)
float powerlawfilterfunction (float ki, float kj)
Variables
float gaussballsigma
float gaussfilterparam
float schectersigma1
float schectersigma2
float schecteralpha
float kolmogorovsigmasquared
float exponentialsigmasquared
float exponentialgamma
float gausssigma11
float gausssigma22
float gausssigma12
float mexicansigma1
float mexicansigma2
float powerlawalpha
Define Documentation
#define max(a, b) ((a) < (b) ? (b) : (a))
filters.c --- image processing routines Definition at line 15 of file filters.c.
#define min(a, b) ((a) < (b) ? (a) : (b))
Definition at line 16 of file filters.c.
#define ZMAX 10
Definition at line 430 of file filters.c.
Function Documentation
void block_filter (float ** f, float ** fs, int N1, int N2, int m)
Definition at line 86 of file filters.c.
void exponentialfilter (float ** f, int N1, int N2, float ** fs, float sigma, float gamma, float magicsubstitute)
Definition at line 250 of file filters.c.
References alloc_fft(), exponentialfilterfunction(), exponentialgamma, exponentialsigmasquared, f, fft_type, filter(), forward_fft(), free_fft(), i, inverse_fft(), j, N1, N2, sigma, and substitute().
Referenced by main().
float exponentialfilterfunction (float ki, float kj)
Definition at line 462 of file filters.c.
References exponentialgamma, exponentialsigmasquared, and kk.
Referenced by exponentialfilter().
float gaussballfunction (float ki, float kj)
Definition at line 471 of file filters.c.
Referenced by gaussfilter().
float gaussellipsoidfunction (float ki, float kj)
Definition at line 484 of file filters.c.
Referenced by gaussfilter().
void gaussfilter (float ** f, int N1, int N2, float ** fs, float A, float B, float phi, float magicsubstitute)
Definition at line 293 of file filters.c.
void gaussian_kernel_filter (float ** f, float ** fs, int N1, int N2, int m, float rf)
Definition at line 28 of file filters.c.
float gaussianfilterfunc (int i, int j)
Definition at line 432 of file filters.c.
Referenced by gaussian_kernel_filter().
void kernel_filter (float ** f, float ** fs, int N1, int N2, int m, float(* filterfunc)(int di, int dj))
Definition at line 35 of file filters.c.
void kolmogorovfilter (float ** f, int N1, int N2, float ** fs, float sigma, float magicsubstitute)
Definition at line 206 of file filters.c.
float kolmogorovfilterfunction (float ki, float kj)
Definition at line 454 of file filters.c.
Referenced by kolmogorovfilter().
void mexicanfilter (float ** f, int N1, int N2, float ** fs, float sigma1, float sigma2, float magicsubstitute)
Definition at line 351 of file filters.c.
float mexicanfilterfunction (float ki, float kj)
Definition at line 498 of file filters.c.
void powerlawfilter (float ** f, int N1, int N2, float ** fs, float alpha, float magicsubstitute)
Definition at line 385 of file filters.c.
float powerlawfilterfunction (float ki, float kj)
Definition at line 508 of file filters.c.
Referenced by powerlawfilter().
void powerspectrum (float ** f, int N1, int N2, float ** P, int ** nmodes)
2-D power spectrum analysis. f[][] is N2 * N1 array. N must be power of two. P[] and nmodes[] must be allocated by calling function with dimension N / 2.
Result is P[k] = sum f exp(ik.r) averages on rings in k-space. Array nmodes[k] contains the number of modes used in averaging which is needed for uncertainty. Definition at line 417 of file filters.c.
void schecterfilter (float ** f, int N1, int N2, float ** fs, float sigma1, float sigma2, float alpha, float magicsubstitute)
Definition at line 155 of file filters.c.
float schecterfilterfunction (float ki, float kj)
Definition at line 444 of file filters.c.
Referenced by schecterfilter().
void tukey (float ** f, int N1, int N2)
Definition at line 122 of file filters.c.
Variable Documentation
float exponentialgamma [static]
Definition at line 23 of file filters.c.
Referenced by exponentialfilter(), and exponentialfilterfunction().
float exponentialsigmasquared [static]
Definition at line 23 of file filters.c.
Referenced by exponentialfilter(), and exponentialfilterfunction().
float gaussballsigma [static]
Definition at line 19 of file filters.c.
Referenced by gaussballfunction(), and gaussfilter().
float gaussfilterparam [static]
Definition at line 20 of file filters.c.
Referenced by gaussian_kernel_filter(), and gaussianfilterfunc().
float gausssigma11 [static]
Definition at line 24 of file filters.c.
Referenced by gaussellipsoidfunction(), and gaussfilter().
float gausssigma12 [static]
Definition at line 24 of file filters.c.
Referenced by gaussellipsoidfunction(), and gaussfilter().
float gausssigma22 [static]
Definition at line 24 of file filters.c.
Referenced by gaussellipsoidfunction(), and gaussfilter().
float kolmogorovsigmasquared [static]
Definition at line 22 of file filters.c.
Referenced by kolmogorovfilter(), and kolmogorovfilterfunction().
float mexicansigma1 [static]
Definition at line 25 of file filters.c.
Referenced by mexicanfilter(), and mexicanfilterfunction().
float mexicansigma2 [static]
Definition at line 25 of file filters.c.
Referenced by mexicanfilter(), and mexicanfilterfunction().
float powerlawalpha [static]
Definition at line 26 of file filters.c.
Referenced by powerlawfilter(), and powerlawfilterfunction().
float schecteralpha [static]
Definition at line 21 of file filters.c.
Referenced by schecterfilter(), and schecterfilterfunction().
float schectersigma1 [static]
Definition at line 21 of file filters.c.
Referenced by schecterfilter(), and schecterfilterfunction().
float schectersigma2 [static]
Definition at line 21 of file filters.c.
Referenced by schecterfilter(), and schecterfilterfunction().
Author
Generated automatically by Doxygen for imcat from the source code.