.TH "findpeak.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
findpeak.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'findpeak.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTINY\fP   1.\fBe\fP-20"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBfindpeak\fP (float **f, int \fBN1\fP, int \fBN2\fP, int *ixpk, int *iypk, float *xpk, float *ypk, float *fpk)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define TINY   1.\fBe\fP-20"
.PP
Definition at line 4 of file findpeak.c.
.SH "Function Documentation"
.PP 
.SS "int findpeak (float ** f, int N1, int N2, int * ixpk, int * iypk, float * xpk, float * ypk, float * fpk)"
.PP
Definition at line 7 of file findpeak.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
