findtrailobjects.c
NAME
findtrailobjects.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include <float.h>
#include '../../utils/error.h'
#include '../../utils/args.h'
#include '../../catlib/cat.h'
#include '../../imlib/fits.h'
#include 'grid.h'
Defines
#define usage '\n\n\NAME\n\	findtrailobjects - find objects in very narrow satellite trails etc\n\\n\SYNOPSIS\n\	findtrailobjects [options....] dmax\n\		-u		# print this man page\n\		-x xname 	# specify name for coords (x)\n\		-n nphi		# number of bins for histogram (512)\n\\n\DESCRIPTION\n\ 'findtrailobjects' reads a catalogue from stdin which must contain\n\	a 2 vector 'x' (substitute some other name with -x option).\n\	For each object it computes a histogram of angles to neighbours\n\	within distance dmax, where angle lies in domain 0 - PI.\n\	It outputs a lc binary format catalogue containing\n\		x		# the position\n\		nmax		# the count in the highest histogram bin\n\		phi		# the angle of the highest histogram bin\n\	With judicious choice of parameters and filtering, this will\n\	detect satellite trails, diffraction spikes around stars etc.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
#define NOPBUFF 4
Functions
main (int argc, char *argv[])
Define Documentation
#define NOPBUFF 4
Definition at line 42 of file findtrailobjects.c.
Referenced by main().
#define usage '\n\n\NAME\n\	findtrailobjects - find objects in very narrow satellite trails etc\n\\n\SYNOPSIS\n\	findtrailobjects [options....] dmax\n\		-u		# print this man page\n\		-x xname 	# specify name for coords (x)\n\		-n nphi		# number of bins for histogram (512)\n\\n\DESCRIPTION\n\ 'findtrailobjects' reads a catalogue from stdin which must contain\n\	a 2 vector 'x' (substitute some other name with -x option).\n\	For each object it computes a histogram of angles to neighbours\n\	within distance dmax, where angle lies in domain 0 - PI.\n\	It outputs a lc binary format catalogue containing\n\		x		# the position\n\		nmax		# the count in the highest histogram bin\n\		phi		# the angle of the highest histogram bin\n\	With judicious choice of parameters and filtering, this will\n\	detect satellite trails, diffraction spikes around stars etc.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file findtrailobjects.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 44 of file findtrailobjects.c.
References object::addrlist, allocgrid(), allocobjectcontents(), argsinit(), argsToString(), d, item::dim, dmax, dx, dy, error_exit, exit(), flag, FLAG_ARG, getargd(), getargi(), getargs(), getflag(), getgridcoords(), getneighbours(), getobjectitem(), getobjectitemindex(), getobjects(), i, item::itype, ix, j, MAX_NEIGHBOURS, n, item::ndim, newobject(), object::next, nextargtype(), NOPBUFF, NUM_TYPE, phi, readcathead(), readobject(), setgridsize(), usage, x, xmax, and xmin.
Author
Generated automatically by Doxygen for imcat from the source code.