findpeaks.c
NAME
findpeaks.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../imlib/filters.h'
#include '../../utils/arrays.h'
#include '../../utils/stats_stuff.h'
#include '../../utils/iostream.h'
#include '../../catlib/cat.h'
Defines
#define usage '\n\n\n\NAME\n\	findpeaks --- simple object finder\n\SYNOPSIS\n\	findpeaks fitsimage [option...] >catalogue \n\		-r	sigma	# gaussian filter radius (default = 2)\n\		-n 	nu	# threshold (default = 3)\n\		-e		# find all extrema\n\		-m		# find all minima\n\		-s sigma mode	# sky statistics\n\		-d 		# add 2nd derivative information\n\		-o		# output FITS file followed by catalog\n\\n\DESCRIPTION\n\	\'findpeaks\' fft gaussian filters image and finds peaks above a threshold nu.\n\	Creates a catalogue with limited information\n\	With -e or -m option, nu parameter ignored.\n\	The position 'x' is measured relative to the bottom left\n\	corner of the bottom left pixel (so e.g. a single 'hot' pixel\n\	at (ix,iy) = (23,67), would generate an object with x = (23.5, 67.5)\n\\n\	Use -r option to control the smoothing radius. With negative\n\	sigma we don't smooth at all.\n\\n\	'findpeaks outputs\n\		x[2]		# peak position\n\		fs		# smoothed image value at the peak\n\		nu		# significance value\n\		maximum		# true if extremum is a maximum\n\\n\	and with '-d' option it also outputs\n\		ddfs[2][2]	# discretized 2nd derivative at peak\n\		detddfs		# determinant\n\\n\	'findpeaks' uses iostream library.\n\\n\	With -o option we send the source image to stdout (but without\n\	the tail) followed by the catalog.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define DEFAULT_NU 3
#define DEFAULT_RF 2
#define FINDPEAKS 0
#define FINDEXTREMA 1
#define FINDMINIMA 2
#define MAGIC FLOAT_MAGIC
#define PI M_PI
#define TINY 1.e-20
Functions
main (int argc, char *argv[])
Define Documentation
#define DEFAULT_NU 3
Definition at line 58 of file findpeaks.c.
Referenced by main().
#define DEFAULT_RF 2
Definition at line 59 of file findpeaks.c.
Referenced by main().
#define FINDEXTREMA 1
Definition at line 62 of file findpeaks.c.
Referenced by main().
#define FINDMINIMA 2
Definition at line 63 of file findpeaks.c.
Referenced by main().
#define FINDPEAKS 0
Definition at line 61 of file findpeaks.c.
Referenced by main().
#define MAGIC FLOAT_MAGIC
Definition at line 65 of file findpeaks.c.
#define PI M_PI
Definition at line 67 of file findpeaks.c.
#define TINY 1.e-20
Definition at line 69 of file findpeaks.c.
#define usage '\n\n\n\NAME\n\	findpeaks --- simple object finder\n\SYNOPSIS\n\	findpeaks fitsimage [option...] >catalogue \n\		-r	sigma	# gaussian filter radius (default = 2)\n\		-n 	nu	# threshold (default = 3)\n\		-e		# find all extrema\n\		-m		# find all minima\n\		-s sigma mode	# sky statistics\n\		-d 		# add 2nd derivative information\n\		-o		# output FITS file followed by catalog\n\\n\DESCRIPTION\n\	\'findpeaks\' fft gaussian filters image and finds peaks above a threshold nu.\n\	Creates a catalogue with limited information\n\	With -e or -m option, nu parameter ignored.\n\	The position 'x' is measured relative to the bottom left\n\	corner of the bottom left pixel (so e.g. a single 'hot' pixel\n\	at (ix,iy) = (23,67), would generate an object with x = (23.5, 67.5)\n\\n\	Use -r option to control the smoothing radius. With negative\n\	sigma we don't smooth at all.\n\\n\	'findpeaks outputs\n\		x[2]		# peak position\n\		fs		# smoothed image value at the peak\n\		nu		# significance value\n\		maximum		# true if extremum is a maximum\n\\n\	and with '-d' option it also outputs\n\		ddfs[2][2]	# discretized 2nd derivative at peak\n\		detddfs		# determinant\n\\n\	'findpeaks' uses iostream library.\n\\n\	With -o option we send the source image to stdout (but without\n\	the tail) followed by the catalog.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file findpeaks.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 71 of file findpeaks.c.
References add_comment(), addargscomment(), allocFloatArray(), BINARY_FILE_TYPE, connectcatheadtoobject(), DEFAULT_NU, DEFAULT_RF, error_exit, exit(), iostream::f, f, fdo_stats(), FILE_IOSTREAM_TYPE, FINDEXTREMA, FINDMINIMA, FINDPEAKS, fits, fstatsrec::fmode, gaussfilter(), getobjectitemindex(), i, j, lcpipe, MAGIC, n, N1, N2, newobject(), openiostream(), PI, read2Dfloatimage(), readcathead(), setaddress(), setcatipf(), setcatopfiletype(), fstatsrec::sigma, TINY, iostream::type, usage, writecathead(), writefitsheader(), writefitsplane(), and writeobject().
Author
Generated automatically by Doxygen for imcat from the source code.