.TH "findpeak.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
findpeak.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBfindpeak\fP (float **f, int \fBN1\fP, int \fBN2\fP, int *ixpk, int *iypk, float *xpk, float *ypk, float *fpk)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int findpeak (float ** f, int N1, int N2, int * ixpk, int * iypk, float * xpk, float * ypk, float * fpk)"
.PP
Definition at line 7 of file findpeak.c.
.PP
References f, ix, N1, N2, TINY, x, and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
