fit1object.c
NAME
fit1object.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../../imlib/fits.h'
#include '../../../utils/error.h'
#include 'gengaussfit.h'
Defines
#define usage '\n\n\n\NAME\n\	fit1object - fit FITS file to generalised Gaussian model\n\\n\SYNOPSIS\n\	fit1object [options....]\n\		-u		# print this message\n\\n\DESCRIPTION\n\	\'fit1object\' reads a fits image f from stdin and fits\n\	this to a simple model object of the form\n\\n\		f_model = f0 exp(-0.5 * [q_ij (r-d)_i (r-d)_j]^alpha)\n\\n\	by minimising\n\\n\		sum_r fabs(f - f_model)^beta\n\\n\	By default, alpha = 1 and beta = 2, so the program is\n\	fitting a 2-dimensional gaussian by least squares.\n\	and the ouput is in the form:\n\		f0, d_x, d_y, q_xx, q_xy, q_yy\n\	the matrix q_ij being taken to be symmetric.\n\	You can modify the behaviour with the following parameters:\n\		-a alpha	# set slope of exponential arg\n\		-b beta		# type of fit\n\		-i		# output inverse of q_ij\n\		-A		# output a, b, phi (TBI)\n\		-f		# output the model as fits image\n\ The position is measured relative to the bottom left\n\ corner of the bottom left pixel (so e.g. a single 'hot' pixel\n\ at (ix,iy) = (23,67), would generate an object with x = (23.5, 67.5)\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
#define PI M_PI
Functions
int main (int argc, char *argv[])
Define Documentation
#define PI M_PI
Definition at line 49 of file fit1object.c.
#define usage '\n\n\n\NAME\n\	fit1object - fit FITS file to generalised Gaussian model\n\\n\SYNOPSIS\n\	fit1object [options....]\n\		-u		# print this message\n\\n\DESCRIPTION\n\	\'fit1object\' reads a fits image f from stdin and fits\n\	this to a simple model object of the form\n\\n\		f_model = f0 exp(-0.5 * [q_ij (r-d)_i (r-d)_j]^alpha)\n\\n\	by minimising\n\\n\		sum_r fabs(f - f_model)^beta\n\\n\	By default, alpha = 1 and beta = 2, so the program is\n\	fitting a 2-dimensional gaussian by least squares.\n\	and the ouput is in the form:\n\		f0, d_x, d_y, q_xx, q_xy, q_yy\n\	the matrix q_ij being taken to be symmetric.\n\	You can modify the behaviour with the following parameters:\n\		-a alpha	# set slope of exponential arg\n\		-b beta		# type of fit\n\		-i		# output inverse of q_ij\n\		-A		# output a, b, phi (TBI)\n\		-f		# output the model as fits image\n\ The position is measured relative to the bottom left\n\ corner of the bottom left pixel (so e.g. a single 'hot' pixel\n\ at (ix,iy) = (23,67), would generate an object with x = (23.5, 67.5)\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
Definition at line 1 of file fit1object.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 52 of file fit1object.c.
References add_comment(), alpha, d, det(), error_exit, exit(), f, fits, gaussfit(), makemodel(), N1, N2, read2Dfloatimage(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.