fit2cats.c
NAME
fit2cats.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/modefunc.h'
Defines
#define usage '\n\NAME\n\	fit2cats --- fit for transformation/distortion for a pair of cats\n\\n\SYNOPSIS\n\	fit2cats \n\		-l lmax		# max order for distortion polynomials (1)\n\		-o x0 y0	# origin for spatial coordinates (0,0)\n\\n\DESCRIPTION\n\	'fit2cats' reads from stdin the result from 'merge2cats' of\n\	merging a pairs of cats, and which must contain entries for\n\	a pair of spatial coordinate vectors 'x[2][2]'.\n\	It then fits a model in which r = x[1] is related to (x,y) = x[0]\n\		r = x[] + sum_{l=0}^{l_max} sum_{m=0}^l a_{lm} x^{l-m} y^m\n\	With the default l_max = 1, this is just a straight linear\n\	transformation, but by going to higher order one can include\n\	distortions of the telescope optics.\n\	With -o option, these mode functios become polynomials in\n\	position relative to specified spatial origin.\n\	Transformation parameters a_{lm} are written to stdout in form\n\	to be read by warpimage or warpcat.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
#define SCALE 1.0
#define BUFF_SIZE 1000
#define N_FIELDS 4
#define MAX_BUFFS 10000
Functions
int readmergedcat (void)
main (int argc, char *argv[])
Variables
double *** x
Define Documentation
#define BUFF_SIZE 1000
Definition at line 176 of file fit2cats.c.
Referenced by readmergedcat().
#define MAX_BUFFS 10000
Definition at line 180 of file fit2cats.c.
Referenced by readmergedcat().
#define N_FIELDS 4
Definition at line 178 of file fit2cats.c.
Referenced by readmergedcat().
#define SCALE 1.0
Definition at line 38 of file fit2cats.c.
#define usage '\n\NAME\n\	fit2cats --- fit for transformation/distortion for a pair of cats\n\\n\SYNOPSIS\n\	fit2cats \n\		-l lmax		# max order for distortion polynomials (1)\n\		-o x0 y0	# origin for spatial coordinates (0,0)\n\\n\DESCRIPTION\n\	'fit2cats' reads from stdin the result from 'merge2cats' of\n\	merging a pairs of cats, and which must contain entries for\n\	a pair of spatial coordinate vectors 'x[2][2]'.\n\	It then fits a model in which r = x[1] is related to (x,y) = x[0]\n\		r = x[] + sum_{l=0}^{l_max} sum_{m=0}^l a_{lm} x^{l-m} y^m\n\	With the default l_max = 1, this is just a straight linear\n\	transformation, but by going to higher order one can include\n\	distortions of the telescope optics.\n\	With -o option, these mode functios become polynomials in\n\	position relative to specified spatial origin.\n\	Transformation parameters a_{lm} are written to stdout in form\n\	to be read by warpimage or warpcat.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file fit2cats.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 46 of file fit2cats.c.
References A, a, B, det(), error_exit, exit(), f(), i, indx, j, l, ll, M, m, modefunc_addargcomment(), mylubksb(), myludcmp(), n, nmodes, readmergedcat(), setorigin(), usage, write2Dpolymodel(), and x.
int readmergedcat (void)
Definition at line 181 of file fit2cats.c.
References buff, BUFF_SIZE, error_exit, exit(), free(), i, j, lcpipe, MAX_BUFFS, N_FIELDS, and x.
Referenced by main().
Variable Documentation
double*** x
Definition at line 41 of file fit2cats.c.
Author
Generated automatically by Doxygen for imcat from the source code.