fit2Dpolymodel.c
NAME
fit2Dpolymodel.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include '../utils/modefunc.h'
#include '../utils/lu.h'
Defines
#define usage '\n\NAME\n\	fit2Dpolymodel --- fit a 2-dimensional spatial polynomial model to a cat\n\\n\SYNOPSIS\n\	fit2Dpolymodel xname lmin lmax var [options...] \n\		-o x0 y0	# spatial origin for mode functions\n\\n\DESCRIPTION\n\	'fit2Dpolymodel' reads from stdin a catalogue which must contain\n\	at least a 2-vector 'xname[2]' and a numerical variable 'var'\n\	(which may be a scalar, vector or tensor of arbitrary rank)\n\	and determines the coefficients of a 2-D spatial poly model:\n\\n\		var_model = sum_l sum_m a_lm f_lm(x)\n\\n\	where the f_lm's are 2-D polynomials:\n\\n\		f_lm(x) = x[0]^(l - m) x[1]^m\n\\n\	with lmin <= l <= lmax and 0 <= m <= l.\n\\n\	The model coefficients are output as an lc-format catalogue\n\	containing the indices l, m, followed by the mode coefficients\n\	which have the same names as the 'var' variable.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	fit2Dpolymodel --- fit a 2-dimensional spatial polynomial model to a cat\n\\n\SYNOPSIS\n\	fit2Dpolymodel xname lmin lmax var [options...] \n\		-o x0 y0	# spatial origin for mode functions\n\\n\DESCRIPTION\n\	'fit2Dpolymodel' reads from stdin a catalogue which must contain\n\	at least a 2-vector 'xname[2]' and a numerical variable 'var'\n\	(which may be a scalar, vector or tensor of arbitrary rank)\n\	and determines the coefficients of a 2-D spatial poly model:\n\\n\		var_model = sum_l sum_m a_lm f_lm(x)\n\\n\	where the f_lm's are 2-D polynomials:\n\\n\		f_lm(x) = x[0]^(l - m) x[1]^m\n\\n\	with lmin <= l <= lmax and 0 <= m <= l.\n\\n\	The model coefficients are output as an lc-format catalogue\n\	containing the indices l, m, followed by the mode coefficients\n\	which have the same names as the 'var' variable.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file fit2Dpolymodel.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 42 of file fit2Dpolymodel.c.
References A, a, B, det(), error_exit, exit(), f(), getvars(), i, indx, l, lcpipe, ll, M, m, modefunc_addargcomment(), MODEFUNC_MAX_VARS, mylubksb(), myludcmp(), N, nmodes, setorigin(), usage, write2Dpolymodel(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.