fitdistortion.c
NAME
fitdistortion.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/modefunc.h'
#include 'utils/lu.h'
Defines
#define usage '\n\NAME\n\	fitdistortion --- fit for field distortion\n\\n\SYNOPSIS\n\	fitdistortion ne [options...] \n\		-l lmax		# max order for field distortion polynomials (3)\n\		-d parfilebase	# basename for transformation param files\n\		-o x0 y0	# spatial origin for mode functions\n\\n\DESCRIPTION\n\	'fitdistortion' reads from stdin a set of pairs of coords x[2][2]\n\	and exposure numbers e[2] (as prodced by merging a set of catalogues\n\	pair by pair, and with 0 <= e < ne) and fits a model in which sky\n\	coord 'r' is related to chip coordinate 'x' by\n\\n\		r = x + sum_M a_M f_M(x) + sum_N a_{eN} f_N(x)\n\\n\	where the f_M's are polynomials of order l = 2 to l_max and\n\	describe the field distortion and the f_N's are polynomials\n\	of order 0, 1 (i.e. linear transformations) which describe the\n\	telescope pointing as well as possible scale changes, or shear\n\	introduced by atmospheric refraction etc. With the -o option\n\	these become polynomials position relative to given spatial\n\	origin. We let exposure e = 0 define the orientation and scale\n\	of the image (so a_{0N} = 0).\n\\n\	The model is only approximate; really we should have:\n\\n\		r = x + sum_M a_M f_M(x) + sum_N a_{eN} f_N(x + sum_M a_M f_M(x))\n\\n\	which is equivalent to the simpler form above in the limit\n\	of small mode coefficient amplitudes (i.e small rotations between\n\	fields etc.\n\	By default, the transformation parameters a_{lm} are written to stdout\n\	as a concatenation of '.par' format files (which is not particularly\n\	useful), but with the -d option you can specify a basename (which\n\	might be a preexisting directory) and fitgeometry will create a set of files\n\	'parfilebase''e'.par with e = 0... ne-1 containing the coefficients\n\	a_{eN} describing the pointings (a 'null' parameter file for the\n\	e = 0 exposure is provided for convenience) and parfilebase'dist.par\n\	containing the distortion parameters a_M.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	fitdistortion --- fit for field distortion\n\\n\SYNOPSIS\n\	fitdistortion ne [options...] \n\		-l lmax		# max order for field distortion polynomials (3)\n\		-d parfilebase	# basename for transformation param files\n\		-o x0 y0	# spatial origin for mode functions\n\\n\DESCRIPTION\n\	'fitdistortion' reads from stdin a set of pairs of coords x[2][2]\n\	and exposure numbers e[2] (as prodced by merging a set of catalogues\n\	pair by pair, and with 0 <= e < ne) and fits a model in which sky\n\	coord 'r' is related to chip coordinate 'x' by\n\\n\		r = x + sum_M a_M f_M(x) + sum_N a_{eN} f_N(x)\n\\n\	where the f_M's are polynomials of order l = 2 to l_max and\n\	describe the field distortion and the f_N's are polynomials\n\	of order 0, 1 (i.e. linear transformations) which describe the\n\	telescope pointing as well as possible scale changes, or shear\n\	introduced by atmospheric refraction etc. With the -o option\n\	these become polynomials position relative to given spatial\n\	origin. We let exposure e = 0 define the orientation and scale\n\	of the image (so a_{0N} = 0).\n\\n\	The model is only approximate; really we should have:\n\\n\		r = x + sum_M a_M f_M(x) + sum_N a_{eN} f_N(x + sum_M a_M f_M(x))\n\\n\	which is equivalent to the simpler form above in the limit\n\	of small mode coefficient amplitudes (i.e small rotations between\n\	fields etc.\n\	By default, the transformation parameters a_{lm} are written to stdout\n\	as a concatenation of '.par' format files (which is not particularly\n\	useful), but with the -d option you can specify a basename (which\n\	might be a preexisting directory) and fitgeometry will create a set of files\n\	'parfilebase''e'.par with e = 0... ne-1 containing the coefficients\n\	a_{eN} describing the pointings (a 'null' parameter file for the\n\	e = 0 exposure is provided for convenience) and parfilebase'dist.par\n\	containing the distortion parameters a_M.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file fitdistortion.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 59 of file fitdistortion.c.
References A, a, B, det(), e, e1, error_exit, exit(), f(), i, indx, l, lcpipe, ll, M, m, modefunc_addargcomment(), mylubksb(), myludcmp(), N, ne, setorigin(), usage, write2Dpolymodel(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.