fitgeometry.c
NAME
fitgeometry.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include '../../utils/modefunc.h'
#include '../../utils/lu.h'
Defines
#define usage '\n\NAME\n\	fitgeometry --- fit layout of a set of images\n\\n\SYNOPSIS\n\	fitgeometry \n\		-c nimages	# number of images (8)\n\		-l lmax		# max order for distortion polynomials (1)\n\		-d parfilebase	# basename for transformation parameter files\n\		-w weightfac	# relative weight for pairs involving reference cat (1)\n\\n\DESCRIPTION\n\	'fitgeometry' reads from stdin the result of merging a set of\n\	overlapping catalogues, which must contain at least entries for\n\	a pair of spatial coordinate vectors 'x[2][2]' and image numbers c[2].\n\	It then fits a model in which the coordinates of the object on\n\	the zeroth image (the 'reference image') are related to those on\n\	the c'th image by\n\			x_0 = x_c + sum_m a_cm f_m(x_c)\n\	where mode function f_m are polynomials up to order lmax in x.\n\\n\	The solution is obtained by minimising squared residuals in x_0 space.\n\\n\	'fitgeometry' can be used in various ways. One application is to\n\	generate accurately registered (but generally somewhat distorted) images from\n\	a set of dithered images from a mosaic camera. To do this one must\n\	first generate a set of overlapping catalogues, one for each chip,\n\	by 'growing' the coordinate system for some reference exposure. This is done\n\	by finding a low order polynomial transformation which maps successive\n\	exposures onto the reference exposure. Once this is done the overlapping\n\	catalogues can be merged in pairs and the concatenation of all the merges\n\	fed to 'fitgeometry' which will then find a solution for the layout of\n\	the chips on some idealised 'detector plane' (whose coordinates coincide\n\	with pixel coordinates on one of the chips --- the zeroth chip --- which may\n\	be chosen arbitrarily). This does not take out telescope distortion, and\n\	(especially with small offsets between the dithered exposures) the process is\n\	liable to introduce additional distortion.\n\\n\	A second application is to register a set of CCD images to some external\n\	'reference' catalogue --- such as a catalogue derived from the digital\n\	sky survey or from the USNOA catalogue. In this case it may be useful to\n\	use the '-w' option with a small argument to downweight the contribution\n\	to the 'chi-squared' from pairs with one element in the reference\n\	catalogue to reflect their relatively poor precision.\n\\n\	By default, the transformation parameters a_{lm} are written to stdout\n\	as a concatenation of '.par' format files (which is not particularly\n\	useful), but with the -d option you can specify a basename\n\	 and fitgeometry will create a set of files\n\	'parfilebase'c.par for c = 0, nimages - 1, where the first of these\n\	contains mode coefficients which are all zero. You will likely\n\	want to make 'parfilebase' a directory, in which case make\n\	sure you terminate it with '/' and remember to 'mkdir' it first.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
#define SCALE 1.0
Functions
int I (int c, int m)
main (int argc, char *argv[])
Variables
int nm
Define Documentation
#define SCALE 1.0
Definition at line 70 of file fitgeometry.c.
Referenced by main().
#define usage '\n\NAME\n\	fitgeometry --- fit layout of a set of images\n\\n\SYNOPSIS\n\	fitgeometry \n\		-c nimages	# number of images (8)\n\		-l lmax		# max order for distortion polynomials (1)\n\		-d parfilebase	# basename for transformation parameter files\n\		-w weightfac	# relative weight for pairs involving reference cat (1)\n\\n\DESCRIPTION\n\	'fitgeometry' reads from stdin the result of merging a set of\n\	overlapping catalogues, which must contain at least entries for\n\	a pair of spatial coordinate vectors 'x[2][2]' and image numbers c[2].\n\	It then fits a model in which the coordinates of the object on\n\	the zeroth image (the 'reference image') are related to those on\n\	the c'th image by\n\			x_0 = x_c + sum_m a_cm f_m(x_c)\n\	where mode function f_m are polynomials up to order lmax in x.\n\\n\	The solution is obtained by minimising squared residuals in x_0 space.\n\\n\	'fitgeometry' can be used in various ways. One application is to\n\	generate accurately registered (but generally somewhat distorted) images from\n\	a set of dithered images from a mosaic camera. To do this one must\n\	first generate a set of overlapping catalogues, one for each chip,\n\	by 'growing' the coordinate system for some reference exposure. This is done\n\	by finding a low order polynomial transformation which maps successive\n\	exposures onto the reference exposure. Once this is done the overlapping\n\	catalogues can be merged in pairs and the concatenation of all the merges\n\	fed to 'fitgeometry' which will then find a solution for the layout of\n\	the chips on some idealised 'detector plane' (whose coordinates coincide\n\	with pixel coordinates on one of the chips --- the zeroth chip --- which may\n\	be chosen arbitrarily). This does not take out telescope distortion, and\n\	(especially with small offsets between the dithered exposures) the process is\n\	liable to introduce additional distortion.\n\\n\	A second application is to register a set of CCD images to some external\n\	'reference' catalogue --- such as a catalogue derived from the digital\n\	sky survey or from the USNOA catalogue. In this case it may be useful to\n\	use the '-w' option with a small argument to downweight the contribution\n\	to the 'chi-squared' from pairs with one element in the reference\n\	catalogue to reflect their relatively poor precision.\n\\n\	By default, the transformation parameters a_{lm} are written to stdout\n\	as a concatenation of '.par' format files (which is not particularly\n\	useful), but with the -d option you can specify a basename\n\	 and fitgeometry will create a set of files\n\	'parfilebase'c.par for c = 0, nimages - 1, where the first of these\n\	contains mode coefficients which are all zero. You will likely\n\	want to make 'parfilebase' a directory, in which case make\n\	sure you terminate it with '/' and remember to 'mkdir' it first.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file fitgeometry.c.
Function Documentation
int I (int c, int m)
Definition at line 268 of file fitgeometry.c.
References c, m, and nm.
Referenced by drawellipse(), main(), and zapellipse().
main (int argc, char * argv[])
Definition at line 75 of file fitgeometry.c.
References A, a, B, c, det(), error_exit, exit(), f(), I(), i, indx, j, l, lcpipe, ll, M, m, modefunc_addargcomment(), mylubksb(), myludcmp(), n, nm, usage, w, write2Dpolymodel(), and x.
Variable Documentation
int nm [static]
Definition at line 72 of file fitgeometry.c.
Referenced by I(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.