fitgeometry3.c
NAME
fitgeometry3.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/modefunc.h'
#include 'utils/lu.h'
#include 'utils/ipbuff.h'
Defines
#define usage '\n\NAME\n\	fitgeometry3 --- fit layout of a set of images\n\\n\SYNOPSIS\n\	fitgeometry3 [options...]\n\		-l lmax		# maximum order for polynomial distortion model (1)\n\		-o outputdir	# directory for the output files (must exist)\n\		-v		# 'verbose' mode\n\\n\DESCRIPTION\n\	fitgeometry3 is very similar to fitgeometry2.\n\	The difference is that fitgemetry3 reads a catalogue\n\	(usually a concatenation of catalogues from a number of images)\n\	containing, in addition to the pixel position 'x', image number 'i'\n\	and position measurement variance 's', a particle identifier 'p'\n\	which is an integer.\n\\n\	Output files are put in 'geofit3files/' by default, but you can change\n\	this with the -o option.\n\\n\	With -v option, fitgeometry3 will report how many objects read, size of\n\	system of equations etc to stderr.\n\\n\	See <a href=\'fitgeom.html\'>notes on various fitgeometry tools</a>\n\\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
#define IPRECUNIT 5
#define IPxPOS 0
#define IPiPOS 2
#define IPpPOS 3
#define IPsPOS 4
#define MAXIMAGES 1000
#define MAXPARTICLES 10000
Functions
main (int argc, char *argv[])
Define Documentation
#define IPiPOS 2
Definition at line 48 of file fitgeometry3.c.
#define IPpPOS 3
Definition at line 49 of file fitgeometry3.c.
Referenced by main().
#define IPRECUNIT 5
Definition at line 46 of file fitgeometry3.c.
#define IPsPOS 4
Definition at line 50 of file fitgeometry3.c.
#define IPxPOS 0
Definition at line 47 of file fitgeometry3.c.
#define MAXIMAGES 1000
Definition at line 52 of file fitgeometry3.c.
#define MAXPARTICLES 10000
Definition at line 53 of file fitgeometry3.c.
Referenced by main().
#define usage '\n\NAME\n\	fitgeometry3 --- fit layout of a set of images\n\\n\SYNOPSIS\n\	fitgeometry3 [options...]\n\		-l lmax		# maximum order for polynomial distortion model (1)\n\		-o outputdir	# directory for the output files (must exist)\n\		-v		# 'verbose' mode\n\\n\DESCRIPTION\n\	fitgeometry3 is very similar to fitgeometry2.\n\	The difference is that fitgemetry3 reads a catalogue\n\	(usually a concatenation of catalogues from a number of images)\n\	containing, in addition to the pixel position 'x', image number 'i'\n\	and position measurement variance 's', a particle identifier 'p'\n\	which is an integer.\n\\n\	Output files are put in 'geofit3files/' by default, but you can change\n\	this with the -o option.\n\\n\	With -v option, fitgeometry3 will report how many objects read, size of\n\	system of equations etc to stderr.\n\\n\	See <a href=\'fitgeom.html\'>notes on various fitgeometry tools</a>\n\\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 7 of file fitgeometry3.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 57 of file fitgeometry3.c.
References A, a, B, det(), error_exit, exit(), f(), i, I(), indx, IPiPOS, IPpPOS, IPRECUNIT, IPsPOS, IPxPOS, j, l, lcpipe, m, MAXIMAGES, MAXPARTICLES, modefunc_addargcomment(), mylubksb(), myludcmp(), n, nim, nmodes, nobj, r, readdoublebuff(), usage, verbose, write2Dpolymodel(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.