fitgeometry2.c
NAME
fitgeometry2.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/modefunc.h'
#include 'utils/lu.h'
#include 'utils/ipbuff.h'
Defines
#define usage '\n\NAME\n\	fitgeometry2 --- fit layout of a set of images\n\\n\SYNOPSIS\n\	fitgeometry2 np [options...]\n\		-l lmax		# maximum order for polynomial distortion model (1)\n\		-o outputdir	# directory for the output files (must exist)\n\\n\DESCRIPTION\n\	fitgeometry2 reads from stdin the result of merging (using 'mergecats')\n\	a set of np 'planes' of catalogues and solves for the location\n\	in some 'reference frame coordinates' of objects on the catalogue\n\	and also a set of parameters describing the distorted mapping between\n\	these reference frame coordinates and pixel coordinates on the\n\	images from which the catalogues were derived.\n\\n\	Fitgeometry2 was written to solve the following problem: We have a set\n\	of 'data' images from a mosiac camera (which have some uncertain\n\	layout of the chips on the detector frame - which need not be static - and\n\	also suffer from telescope field distortion and possibly atmospheric refraction).\n\	From each these images one can extract typically ~100 stars whose positions\n\	have a precision of a small fraction <~ 1/10 of a pixel. These allow one to\n\	determine a set of polynomial mappings (with one image taken to define\n\	the reference coordinate system) which map these images onto one\n\	another to a very high precision. However, this procedure does not\n\	remove telescope or atmospheric field distortion and tends to be\n\	unstable to introducing further artificial field distortion. To avoid this\n\	we incorporate in the fitting a catalogue which derives from the digital\n\	sky survey image for example, and for which a good 'plate solution'\n\	already exists. Providing this catalogue as the 'reference catalogue'\n\	solves our problem and provides one with a mapping from data pixel\n\	coordinates to the `world coordinate system'. A complication of this\n\	procedure is that the reference catalogue positions tend to be relatively\n\	imprecise, and it is necessary to incorporate this information in the\n\	fitting (as weight factors), so the input catalogues most contain both\n\	the measured position and an estimate of the precision.\n\\n\	The catalogues to be merged must contain at least the following items:\n\\n\		x[2]	# spatial coordinate\n\		i	# unique image ID (i = 0 for reference image)\n\		I	# I = 1 -- used internally\n\		s	# sigma^2 = position measurement variance \n\\n\	but will usually contain additional information such as an approximate\n\	'sky coordinate' used by mergecats to link the objects.\n\	The result of such a merging is a set of unique particles and their\n\	measured positions in each and all of the images in which they appear.\n\\n\	The 'planes' which get merged could be just the set of all images. However,\n\	in the case of a mosaic camera an object can only be detected on at most\n\	one chip per exposure, so the merged catalogue will be very sparse. It is\n\	more efficient to group sets of such 'known to be mutually non-overlapping'\n\	catalogues into planes before merging. Since one cannot then infer\n\	the 'image number' of a catalogue from its 'plane number' we include the image\n\	identifier 'i' in the catalogue.\n\\n\	Fitgeometry2 assumes that coordinates x_pi of the p'th of np stars on the i'th\n\	image is related to the coordinates r_p in the reference frame by:\n\\n\ 		r_p = x_pi + sum_m a_im f_m(x_pi) + e_pi\n\\n\	whereas for the reference image (i = 0)\n\\n\ 		r_p = x_p0 + e_p0\n\\n\	Here the f_m(x) are a set of nm polynomial mode functions\n\	and a_im denotes the amplitudes of these functions in the distortion\n\	of the i'th image. The e_pi represent the uncertainty in the position.\n\	It finds the set of parameters a_il and positions r_p which minimise\n\	the 'chi-squared' function:\n\\n\	chi^2 = sum_p [ sum_i (x_pi - sum_l a_il f_l(x_pi) - r_p)^2 / s_pi^2\n\			+ (x_p0 - r_p)^2 / s_p0]\n\\n\	Since this is quadratic in the a_il, r_p the result is a set of\n\	nm * (nimages - 1) + np linear equations for each of the 2 spatial\n\	coordinate components.\n\	The summation over 'i' here does not include the reference\n\	catalogue (i=0). For small distortions this is equivalent to the\n\	maximum likelihood solution if we assume that the position errors are\n\	gaussian distributed.\n\\n\	The result is:\n\	1) A set of parameter files ouputdir/i.par, where i is the image number.\n\	By default ouputdir = \'geofit2dir\', but you can change this\n\	with the -o flag.\n\	2) A set of catalogues ouputdir/i.cat which contains the\n\	x, i, I, s values for the points detected on the i'th image, as well\n\	as the following items:\n\		rref		# the reference catalogue solution (rref = r_p)\n\		p		# the particle number\n\		ndet		# the number of images in which particle p was detected\n\		refdet		# refdet = 1 if particle was detected in the reference cat\n\		r		# obtained by applying the approximate polynomial model \n\	3) A reference catalogue ouputdir/ref.cat containing the solutions r_p.\n\\n\ See also <a href=\'fitgeom.html\'>notes on various fitgeometry tools</a>\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
#define IPRECUNIT 5
#define IPxPOS 0
#define IPiPOS 2
#define IPIPOS 3
#define IPsPOS 4
#define MAXIMAGES 1000
Functions
main (int argc, char *argv[])
Define Documentation
#define IPIPOS 3
Definition at line 187 of file fitgeometry2.c.
Referenced by main().
#define IPiPOS 2
Definition at line 186 of file fitgeometry2.c.
Referenced by main().
#define IPRECUNIT 5
Definition at line 184 of file fitgeometry2.c.
Referenced by main().
#define IPsPOS 4
Definition at line 188 of file fitgeometry2.c.
Referenced by main().
#define IPxPOS 0
Definition at line 185 of file fitgeometry2.c.
Referenced by main().
#define MAXIMAGES 1000
Definition at line 190 of file fitgeometry2.c.
Referenced by main().
#define usage '\n\NAME\n\	fitgeometry2 --- fit layout of a set of images\n\\n\SYNOPSIS\n\	fitgeometry2 np [options...]\n\		-l lmax		# maximum order for polynomial distortion model (1)\n\		-o outputdir	# directory for the output files (must exist)\n\\n\DESCRIPTION\n\	fitgeometry2 reads from stdin the result of merging (using 'mergecats')\n\	a set of np 'planes' of catalogues and solves for the location\n\	in some 'reference frame coordinates' of objects on the catalogue\n\	and also a set of parameters describing the distorted mapping between\n\	these reference frame coordinates and pixel coordinates on the\n\	images from which the catalogues were derived.\n\\n\	Fitgeometry2 was written to solve the following problem: We have a set\n\	of 'data' images from a mosiac camera (which have some uncertain\n\	layout of the chips on the detector frame - which need not be static - and\n\	also suffer from telescope field distortion and possibly atmospheric refraction).\n\	From each these images one can extract typically ~100 stars whose positions\n\	have a precision of a small fraction <~ 1/10 of a pixel. These allow one to\n\	determine a set of polynomial mappings (with one image taken to define\n\	the reference coordinate system) which map these images onto one\n\	another to a very high precision. However, this procedure does not\n\	remove telescope or atmospheric field distortion and tends to be\n\	unstable to introducing further artificial field distortion. To avoid this\n\	we incorporate in the fitting a catalogue which derives from the digital\n\	sky survey image for example, and for which a good 'plate solution'\n\	already exists. Providing this catalogue as the 'reference catalogue'\n\	solves our problem and provides one with a mapping from data pixel\n\	coordinates to the `world coordinate system'. A complication of this\n\	procedure is that the reference catalogue positions tend to be relatively\n\	imprecise, and it is necessary to incorporate this information in the\n\	fitting (as weight factors), so the input catalogues most contain both\n\	the measured position and an estimate of the precision.\n\\n\	The catalogues to be merged must contain at least the following items:\n\\n\		x[2]	# spatial coordinate\n\		i	# unique image ID (i = 0 for reference image)\n\		I	# I = 1 -- used internally\n\		s	# sigma^2 = position measurement variance \n\\n\	but will usually contain additional information such as an approximate\n\	'sky coordinate' used by mergecats to link the objects.\n\	The result of such a merging is a set of unique particles and their\n\	measured positions in each and all of the images in which they appear.\n\\n\	The 'planes' which get merged could be just the set of all images. However,\n\	in the case of a mosaic camera an object can only be detected on at most\n\	one chip per exposure, so the merged catalogue will be very sparse. It is\n\	more efficient to group sets of such 'known to be mutually non-overlapping'\n\	catalogues into planes before merging. Since one cannot then infer\n\	the 'image number' of a catalogue from its 'plane number' we include the image\n\	identifier 'i' in the catalogue.\n\\n\	Fitgeometry2 assumes that coordinates x_pi of the p'th of np stars on the i'th\n\	image is related to the coordinates r_p in the reference frame by:\n\\n\ 		r_p = x_pi + sum_m a_im f_m(x_pi) + e_pi\n\\n\	whereas for the reference image (i = 0)\n\\n\ 		r_p = x_p0 + e_p0\n\\n\	Here the f_m(x) are a set of nm polynomial mode functions\n\	and a_im denotes the amplitudes of these functions in the distortion\n\	of the i'th image. The e_pi represent the uncertainty in the position.\n\	It finds the set of parameters a_il and positions r_p which minimise\n\	the 'chi-squared' function:\n\\n\	chi^2 = sum_p [ sum_i (x_pi - sum_l a_il f_l(x_pi) - r_p)^2 / s_pi^2\n\			+ (x_p0 - r_p)^2 / s_p0]\n\\n\	Since this is quadratic in the a_il, r_p the result is a set of\n\	nm * (nimages - 1) + np linear equations for each of the 2 spatial\n\	coordinate components.\n\	The summation over 'i' here does not include the reference\n\	catalogue (i=0). For small distortions this is equivalent to the\n\	maximum likelihood solution if we assume that the position errors are\n\	gaussian distributed.\n\\n\	The result is:\n\	1) A set of parameter files ouputdir/i.par, where i is the image number.\n\	By default ouputdir = \'geofit2dir\', but you can change this\n\	with the -o flag.\n\	2) A set of catalogues ouputdir/i.cat which contains the\n\	x, i, I, s values for the points detected on the i'th image, as well\n\	as the following items:\n\		rref		# the reference catalogue solution (rref = r_p)\n\		p		# the particle number\n\		ndet		# the number of images in which particle p was detected\n\		refdet		# refdet = 1 if particle was detected in the reference cat\n\		r		# obtained by applying the approximate polynomial model \n\	3) A reference catalogue ouputdir/ref.cat containing the solutions r_p.\n\\n\ See also <a href=\'fitgeom.html\'>notes on various fitgeometry tools</a>\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 72 of file fitgeometry2.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 192 of file fitgeometry2.c.
References A, a, B, det(), e, e1, e2, error_exit, exit(), f(), i, I(), indx, IPiPOS, IPIPOS, IPRECUNIT, IPsPOS, IPxPOS, j, l, lcpipe, m, MAXIMAGES, modefunc_addargcomment(), mylubksb(), myludcmp(), n, nim, nmodes, readdoublebuff(), usage, write2Dpolymodel(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.