fitlmodel.c
NAME
fitlmodel.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'catlib/cat.h'
#include 'utils/lu.h'
#include 'utils/error.h'
#include 'utils/args.h'
#include 'utils/lmodel.h'
Defines
#define usage '\n\NAME\n\	fitlmodel --- fit for linear superposition of mode function\n\\n\SYNOPSIS\n\	fitlmodel xname aname modeldefinition [options...] \n\\n\DESCRIPTION\n\	'fitlmodel' reads from stdin a catalogue containing at least a\n\	'postion vector' x called xname and some other variable a called aname,\n\	whch may be a scalar, vector or matrix of arbitrary rank,\n\	and fits for a model of a(x) as a linear superposition\n\	of a set of mode functions:\n\\n\		a(x) = sum_M a_M f_M(x)\n\\n\	where the mode function coefficients a_M have the same\n\	dimensionality as a.\n\\n\	The 'modeldefinition' is a combination of arguments which can be\n\	one of:\n\\n\	-p lmin lmax\n\		Fit a polynomial. The mode functions are labelled by a set\n\		of indices p[] with same length as x[], the functions are\n\\n\			f_p = x0^p0 x1^p1 .... = product x_i^p_i\n\\n\		and the order l = sum p_i lies in the inclusive interval lmin-lmax.\n\		An alternative parameterisation of the indices is in terms of\n\		the order array l[i] = l - sum_i=0^i-1 p[i], in terms of which the\n\		p-indices are p[i] = l[i] - l[i+1].\n\\n\	-z nmin nmax\n\		Fit for Zernike polynomials of order min through nmax\n\		as defined in Born and Wolf.\n\\n\	-f kmin kmax lbox\n\		Fit a sum of Fourier modes labelled by compound index m = {k[], i}\n\\n\			f_m = cos(2 PI k.x / lbox)		i = 0\n\			f_m = sin(2 PI k.x / lbox)		i = 1\n\\n\		where the modulus of the integerised wave number k lies in the\n\		range kmin - kmax inclusive.\n\\n\	-F kmax lbox\n\		As for -f option save that all modes in hypercube with edges +- kmax.\n\\n\\n\	Other options:\n\\n\	-c	# generate covariance matrix 'covar'\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	fitlmodel --- fit for linear superposition of mode function\n\\n\SYNOPSIS\n\	fitlmodel xname aname modeldefinition [options...] \n\\n\DESCRIPTION\n\	'fitlmodel' reads from stdin a catalogue containing at least a\n\	'postion vector' x called xname and some other variable a called aname,\n\	whch may be a scalar, vector or matrix of arbitrary rank,\n\	and fits for a model of a(x) as a linear superposition\n\	of a set of mode functions:\n\\n\		a(x) = sum_M a_M f_M(x)\n\\n\	where the mode function coefficients a_M have the same\n\	dimensionality as a.\n\\n\	The 'modeldefinition' is a combination of arguments which can be\n\	one of:\n\\n\	-p lmin lmax\n\		Fit a polynomial. The mode functions are labelled by a set\n\		of indices p[] with same length as x[], the functions are\n\\n\			f_p = x0^p0 x1^p1 .... = product x_i^p_i\n\\n\		and the order l = sum p_i lies in the inclusive interval lmin-lmax.\n\		An alternative parameterisation of the indices is in terms of\n\		the order array l[i] = l - sum_i=0^i-1 p[i], in terms of which the\n\		p-indices are p[i] = l[i] - l[i+1].\n\\n\	-z nmin nmax\n\		Fit for Zernike polynomials of order min through nmax\n\		as defined in Born and Wolf.\n\\n\	-f kmin kmax lbox\n\		Fit a sum of Fourier modes labelled by compound index m = {k[], i}\n\\n\			f_m = cos(2 PI k.x / lbox)		i = 0\n\			f_m = sin(2 PI k.x / lbox)		i = 1\n\\n\		where the modulus of the integerised wave number k lies in the\n\		range kmin - kmax inclusive.\n\\n\	-F kmax lbox\n\		As for -f option save that all modes in hypercube with edges +- kmax.\n\\n\\n\	Other options:\n\\n\	-c	# generate covariance matrix 'covar'\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file fitlmodel.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 75 of file fitlmodel.c.
References lmodel::a, a, A, addargscomment(), item::addr, addtomatrix(), lmodel::aflat, allocobjectcontents(), argsinit(), lmodel::asize, B, lmodel::cat, cathead::commentbase, connectobjecttocathead(), lmodel::covar, d, det(), item::dim, error_exit, exit(), flatten_a(), FOURIER_LMODEL, getargd(), getargi(), getargs(), getflag(), getobjectitem(), lmodel::hascovar, indx, invertmatrix(), ix, lmodelfunc(), m, mylubksb(), myludcmp(), n, item::ndim, newfourierlmodel(), newobject(), newpolylmodel(), newzernikelmodel(), lmodel::nmodes, POLYNOMIAL_LMODEL, readcathead(), readobject(), unflatten_a(), usage, writelmodel(), x, and ZERNIKE_LMODEL.
Author
Generated automatically by Doxygen for imcat from the source code.