fitmagshiftsplus.c
NAME
fitmagshiftsplus.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../utils/lu.h'
#include '../../utils/error.h'
Defines
#define usage '\n\NAME\n\	fitmagshifts --- fit for extinction/gain coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitmagshifts nc\n\\n\DESCRIPTION\n\	'fitmagshifts' reads a catalogue containing (at least) pairs\n\	of magnitudes mag[2], chip numbers c[2], and positions x[2][2]\n\	for a set of reference stars observed on a mosaic of nc chips\n\	and solves for any gain variations between chips and gradients\n\	thereof.\n\\n\	More explicitly, we model the magnitude of a star as measured\n\	at position x, y on the c'th chip as:\n\		m_ce = m + m_c + x * m_cx + y * m_cy\n\	where m is the true magnitude, and we solve for the coefficients.\n\	We set M_0 and m_0 to be zero.\n\\n\	We output the coefficients as a lc-format catalog.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	fitmagshifts --- fit for extinction/gain coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitmagshifts nc\n\\n\DESCRIPTION\n\	'fitmagshifts' reads a catalogue containing (at least) pairs\n\	of magnitudes mag[2], chip numbers c[2], and positions x[2][2]\n\	for a set of reference stars observed on a mosaic of nc chips\n\	and solves for any gain variations between chips and gradients\n\	thereof.\n\\n\	More explicitly, we model the magnitude of a star as measured\n\	at position x, y on the c'th chip as:\n\		m_ce = m + m_c + x * m_cx + y * m_cy\n\	where m is the true magnitude, and we solve for the coefficients.\n\	We set M_0 and m_0 to be zero.\n\\n\	We output the coefficients as a lc-format catalog.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file fitmagshiftsplus.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 37 of file fitmagshiftsplus.c.
References c, d, error_exit, exit(), indx, lcpipe, line, m, mag, mylubksb(), myludcmp(), n, usage, x, xp(), y, and yp().
Author
Generated automatically by Doxygen for imcat from the source code.