fitmagshifts.c
NAME
fitmagshifts.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../utils/lu.h'
#include '../../utils/error.h'
Defines
#define usage '\n\NAME\n\	fitmagshifts --- fit for extinction/gain coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitmagshifts nc ne [options...]\n\\n\DESCRIPTION\n\	'fitmagshifts' reads a catalogue containing (at least) pairs\n\	of magnitudes mag[2]; chip numbers c[2] and exposure numbers e[2]\n\	for a set of reference stars observed on a mosaic of\n\	nc chips with ne exposures,\n\	and solves for any gain variations between chips and any\n\	differential extinction between exposures.\n\\n\	More explicitly, we model the magnitude of a star as measured\n\	in the c'th chip and e'th exposure as:\n\		m_ce = m + m_c + M_e\n\	where m is the true magnitude, and we solve for the gain\n\	variations m_c and the extinctions M_e by least squares\n\	minimisation (these being measured relative to the 0th\n\	chip and 0th exposure respectively).\n\\n\	We output the coefficients as a pair of lc-format catalogues.\n\	By default these are concatenated to stdout, but can be sent to\n\	named files by using the -c and -e options.\n\	Options are\n\		-c chipcoefftfile\n\		-e expcoefftfile\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	fitmagshifts --- fit for extinction/gain coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitmagshifts nc ne [options...]\n\\n\DESCRIPTION\n\	'fitmagshifts' reads a catalogue containing (at least) pairs\n\	of magnitudes mag[2]; chip numbers c[2] and exposure numbers e[2]\n\	for a set of reference stars observed on a mosaic of\n\	nc chips with ne exposures,\n\	and solves for any gain variations between chips and any\n\	differential extinction between exposures.\n\\n\	More explicitly, we model the magnitude of a star as measured\n\	in the c'th chip and e'th exposure as:\n\		m_ce = m + m_c + M_e\n\	where m is the true magnitude, and we solve for the gain\n\	variations m_c and the extinctions M_e by least squares\n\	minimisation (these being measured relative to the 0th\n\	chip and 0th exposure respectively).\n\\n\	We output the coefficients as a pair of lc-format catalogues.\n\	By default these are concatenated to stdout, but can be sent to\n\	named files by using the -c and -e options.\n\	Options are\n\		-c chipcoefftfile\n\		-e expcoefftfile\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file fitmagshifts.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 45 of file fitmagshifts.c.
References c, d, e, error_exit, exit(), indx, lcpipe, line, m, mag, mylubksb(), myludcmp(), n, and usage.
Author
Generated automatically by Doxygen for imcat from the source code.