fitpolymodelmagshift.c
NAME
fitpolymodelmagshift.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../utils/lu.h'
#include '../../utils/error.h'
#include '../../utils/args.h'
#include '../../catlib/cat.h'
#include '../../utils/lmodel.h'
Defines
#define usage '\n\NAME\n\	fitpolymodelmagshift --- fit for extinction/gain coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitpolymodelmagshift ne fitorder opname [-outputarray] [-noextinction]\n\\n\DESCRIPTION\n\	'fitpolymodelmagshift' reads a catalogue containing (at least) pairs\n\	of magnitudes mag[2]; detector coords xdet[2][2] and exposure numbers e[2]\n\	for a set of reference stars observed in ne exposures.\n\\n\	It solves for differential extinction between exposures and for a\n\	spatial polynomial magnitude shift.\n\\n\	More explicitly, we model the magnitude of the i'th star as measured\n\	at position xdet and e'th exposure as:\n\		m_ei = m + m_e + sum_j m_j f_j(xdet)\n\	where m is the true magnitude and the functions f_j are\n\	polynomials (no DC term).\n\\n\	We solve for the coefficients by least squares.\n\	minimisation (these being measured relative to the 0th\n\	chip and 0th exposure respectively).\n\\n\	We output the m_e coefficients as a lc-format catalogue opname.cat.\n\	The coefficents m_j are output as a l-model par file opname.par.\n\\n\	With -outputarray option we output the A-matrix etc to stdout.\n\\n\	With -noextinction option we don't solve for the extinction terms.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Functions
double f (int m, int *e, double **xdet)
main (int argc, char *argv[])
Variables
int ne
int fitorder
int fitextinction
lmodel * thelmodel
Define Documentation
#define usage '\n\NAME\n\	fitpolymodelmagshift --- fit for extinction/gain coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitpolymodelmagshift ne fitorder opname [-outputarray] [-noextinction]\n\\n\DESCRIPTION\n\	'fitpolymodelmagshift' reads a catalogue containing (at least) pairs\n\	of magnitudes mag[2]; detector coords xdet[2][2] and exposure numbers e[2]\n\	for a set of reference stars observed in ne exposures.\n\\n\	It solves for differential extinction between exposures and for a\n\	spatial polynomial magnitude shift.\n\\n\	More explicitly, we model the magnitude of the i'th star as measured\n\	at position xdet and e'th exposure as:\n\		m_ei = m + m_e + sum_j m_j f_j(xdet)\n\	where m is the true magnitude and the functions f_j are\n\	polynomials (no DC term).\n\\n\	We solve for the coefficients by least squares.\n\	minimisation (these being measured relative to the 0th\n\	chip and 0th exposure respectively).\n\\n\	We output the m_e coefficients as a lc-format catalogue opname.cat.\n\	The coefficents m_j are output as a l-model par file opname.par.\n\\n\	With -outputarray option we output the A-matrix etc to stdout.\n\\n\	With -noextinction option we don't solve for the extinction terms.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file fitpolymodelmagshift.c.
Function Documentation
double f (int m, int * e, double ** xdet)
main (int argc, char * argv[])
Definition at line 55 of file fitpolymodelmagshift.c.
References lmodel::a, A, argsinit(), B, det(), e, error_exit, exit(), f(), fitextinction, fitorder, flag, FLAG_ARG, getargi(), getargs(), getflag(), indx, lcpipe, m, mag, modefunc(), mylubksb(), myludcmp(), n, ne, newitem(), newpolylmodel(), nextargtype(), lmodel::nmodes, NUM_TYPE, thelmodel, usage, and writelmodel().
Variable Documentation
int fitextinction
Definition at line 52 of file fitpolymodelmagshift.c.
Referenced by main().
int fitorder
Definition at line 52 of file fitpolymodelmagshift.c.
Referenced by main().
int ne
Definition at line 52 of file fitpolymodelmagshift.c.
Referenced by cpgellipses(), do_object_stats(), fittranslations(), main(), and num2funcarray().
lmodel* thelmodel
Definition at line 53 of file fitpolymodelmagshift.c.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.