fitstops.c
NAME
fitstops.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/args.h'
#include 'psutils.h'
#include 'makec.h'
#include 'printimage.h'
#include 'contourplot.h'
#include 'surfaceplot.h'
#include 'tonry3d.h'
Defines
#define usage '\n\n\n\NAME\n\	fitstops -- convert image from fits to postscript\n\\n\SYNOPSIS\n\	fitstops fitsfile [option...] \n\		-f fmin fmax	# max and min f values\n\		-n		# don't print header info\n\		-b		# draw a box oround image\n\		-c comment	# use (quoted if multiword) comment as label\n\		-p pw ph mx my	# set page width, height, xmargin, ymargin (612, 792, 50, 50)\n\		-P		# include setpagedevice command\n\		-g		# pipe output through gs to compress\n\		-C nc lw	# draw nc contours of width lw\n\		-s		# draw 3D hidden line surface plot (alt = az = 30.0; zfac = 3.0; zoff = -0.2)\n\		-S alt az zfac zoff	# draw 3D hidden line surface plot\n\\n\DESCRIPTION\n\	\'fitstops\' reads fitsfile and, by default, sends\n\	postscript gray scale or color image to stdout\n\\n\	The range of values may be specified with the -f option,\n\	otherwise the range is 0 (=white) to 255 (=black).\n\\n\	Supports 1 and 3-color images.\n\\n\	If fitsfile = '-' then we read from stdin.\n\\n\	Default page size info is 612x792 = (8.5x11)in with 50 pt margin\n\	so the actual inked area is 512x692. Use -p option to change this.\n\\n\	The -P option is provided to include a 'setpagedevice' command giving\n\	the physical total page size. This is used for big prints on\n\	the designjet, but seems to be problematic with latex epsf handling.\n\	Do not use this with -g option.\n\\n\	With the -g option we pipe the output through\n\		gs -q -sDEVICE=pswrite -sOutputFile=- -dNOPAUSE -\n\	which will result in a much smaller output file.\n\	Do not use this with -P option.\n\\n\	Use the -s, -S options to generate a 3D hidden line surface plot using\n\	Tonry's mongo routine. The simple -s option uses default parameters\n\	which work reasonably well for a positive peak of height unity near the\n\	origin. Use the -S option to fiddle with the parameters alt, az, zfac, zoff\n\	where:\n\		alt, az = altitude azimuth viewing angle in degrees.\n\		zfac = scaling of z-axis (roughly 3.0 / data max)\n\		zoff = offset of z-origin.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	fitstops -- convert image from fits to postscript\n\\n\SYNOPSIS\n\	fitstops fitsfile [option...] \n\		-f fmin fmax	# max and min f values\n\		-n		# don't print header info\n\		-b		# draw a box oround image\n\		-c comment	# use (quoted if multiword) comment as label\n\		-p pw ph mx my	# set page width, height, xmargin, ymargin (612, 792, 50, 50)\n\		-P		# include setpagedevice command\n\		-g		# pipe output through gs to compress\n\		-C nc lw	# draw nc contours of width lw\n\		-s		# draw 3D hidden line surface plot (alt = az = 30.0; zfac = 3.0; zoff = -0.2)\n\		-S alt az zfac zoff	# draw 3D hidden line surface plot\n\\n\DESCRIPTION\n\	\'fitstops\' reads fitsfile and, by default, sends\n\	postscript gray scale or color image to stdout\n\\n\	The range of values may be specified with the -f option,\n\	otherwise the range is 0 (=white) to 255 (=black).\n\\n\	Supports 1 and 3-color images.\n\\n\	If fitsfile = '-' then we read from stdin.\n\\n\	Default page size info is 612x792 = (8.5x11)in with 50 pt margin\n\	so the actual inked area is 512x692. Use -p option to change this.\n\\n\	The -P option is provided to include a 'setpagedevice' command giving\n\	the physical total page size. This is used for big prints on\n\	the designjet, but seems to be problematic with latex epsf handling.\n\	Do not use this with -g option.\n\\n\	With the -g option we pipe the output through\n\		gs -q -sDEVICE=pswrite -sOutputFile=- -dNOPAUSE -\n\	which will result in a much smaller output file.\n\	Do not use this with -P option.\n\\n\	Use the -s, -S options to generate a 3D hidden line surface plot using\n\	Tonry's mongo routine. The simple -s option uses default parameters\n\	which work reasonably well for a positive peak of height unity near the\n\	origin. Use the -S option to fiddle with the parameters alt, az, zfac, zoff\n\	where:\n\		alt, az = altitude azimuth viewing angle in degrees.\n\		zfac = scaling of z-axis (roughly 3.0 / data max)\n\		zoff = offset of z-origin.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 6 of file fitstops.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 76 of file fitstops.c.
References argsinit(), argsToString(), ascii, c, caption, color, contourplot(), error_exit, exit(), f, fits, flag, fmin, getargf(), getargi(), getargs(), getflag(), i, j, makecarray(), fitsheader::n, N, N1, N2, fitsheader::ndim, print_caption(), printimage(), ps(), psstringlen, readfitsheader(), set_print_opf(), surfaceplot(), and usage.
Author
Generated automatically by Doxygen for imcat from the source code.