fits_dev.c
NAME
fits_dev.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../utils/error.h'
#include 'fits.h'
#include '../utils/arrays.h'
Functions
void set_output_pixtype (int thetype)
void set_input_pixtype (int thetype)
void get_input_pixtype (int *thetype)
void write_fits_head (int N1, int N2, int comc, char *comv[])
void write_fits_line (short *f, int N1)
void fwrite_fits_line (float *f, int N1)
void write_fits_tail (int N1, int N2)
void write_fits (short **f, int N1, int N2, int comc, char *comv[])
void fwrite_fits (float **f, int N1, int N2, int comc, char *comv[])
void read_fits_head (int *N1, int *N2, int *comc, char *comv[])
void read_fits_line (short *f, int N1)
void fread_fits_line (float *f, int N1)
void read_fits (short ***f, int *N1, int *N2, int *comc, char *comv[])
void fread_fits (float ***f, int *N1, int *N2, int *comc, char *comv[])
void argsToString (int argc, char **argv, char *string)
void add_comment (int argc, char **argv, int *comc, char **comv)
void add_1comment (char *comment, int *comc, char **comv)
void addheadervalue (char *name, char *value, int *comc, char **comv)
char * getheadervalue (char *name, int comc, char **comv)
void set_fits_opf (FILE *opf)
void set_fits_ipf (FILE *ipf)
void read_fits_head_ND (int *Naxes, int *N, int *comc, char *comv[])
void write_fits_head_ND (int Naxes, int *N, int comc, char *comv[])
void write_fits_tail_ND (int Naxes, int *N)
Variables
FILE * theipf = stdin *theopf = stdout
int bitpixout = SHORT_PIXTYPE
int bitpixin = SHORT_PIXTYPE
Function Documentation
void add_1comment (char * comment, int * comc, char ** comv)
Definition at line 433 of file fits_dev.c.
References COM_LENGTH, and comment.
Referenced by main().
void add_comment (int argc, char ** argv, int * comc, char ** comv)
Definition at line 415 of file fits_dev.c.
References argsToString(), and COM_LENGTH.
Referenced by main().
void addheadervalue (char * name, char * value, int * comc, char ** comv)
Definition at line 447 of file fits_dev.c.
References COM_LENGTH, and error_exit.
void argsToString (int argc, char ** argv, char * string)
Definition at line 394 of file fits_dev.c.
References COM_LENGTH, i, j, len, and pos.
Referenced by add_comment(), and main().
void fread_fits (float *** f, int * N1, int * N2, int * comc, char * comv[])
Definition at line 378 of file fits_dev.c.
References allocFloatArray(), f, fread_fits_line(), i, j, N1, N2, and read_fits_head().
Referenced by main().
void fread_fits_line (float * f, int N1)
Definition at line 318 of file fits_dev.c.
References bitpixin, DBL_PIXTYPE, error_exit, f, FLOAT_PIXTYPE, free(), i, INT_PIXTYPE, N1, read_fits_line(), SHORT_PIXTYPE, and theipf.
Referenced by fread_fits(), and main().
void fwrite_fits (float ** f, int N1, int N2, int comc, char * comv[])
Definition at line 181 of file fits_dev.c.
References bitpixout, error_exit, f, FLOAT_PIXTYPE, free(), i, INT_PIXTYPE, ix, N1, N2, SHORT_PIXTYPE, write_fits_head(), and write_fits_tail().
Referenced by main().
void fwrite_fits_line (float * f, int N1)
Definition at line 112 of file fits_dev.c.
References bitpixout, error_exit, f, FLOAT_PIXTYPE, i, INT_PIXTYPE, N1, and SHORT_PIXTYPE.
Referenced by main().
void get_input_pixtype (int * thetype)
Definition at line 65 of file fits_dev.c.
References bitpixin.
Referenced by main().
char* getheadervalue (char * name, int comc, char ** comv)
Definition at line 463 of file fits_dev.c.
void read_fits (short *** f, int * N1, int * N2, int * comc, char * comv[])
Definition at line 356 of file fits_dev.c.
References error_exit, f, i, N1, N2, read_fits_head(), and read_fits_line().
Referenced by main().
void read_fits_head (int * N1, int * N2, int * comc, char * comv[])
Definition at line 233 of file fits_dev.c.
References bitpix, bitpixin, COM_LENGTH, DBL_PIXTYPE, error_exit, FLOAT_PIXTYPE, i, INT_PIXTYPE, line, N1, N2, SHORT_PIXTYPE, and theipf.
Referenced by fread_fits(), main(), make_pixmap(), and read_fits().
void read_fits_head_ND (int * Naxes, int * N, int * comc, char * comv[])
Definition at line 499 of file fits_dev.c.
References bitpix, bitpixin, COM_LENGTH, DBL_PIXTYPE, error_exit, FLOAT_PIXTYPE, i, INT_PIXTYPE, line, N, SHORT_PIXTYPE, and theipf.
void read_fits_line (short * f, int N1)
Definition at line 311 of file fits_dev.c.
References f, i, N1, and theipf.
Referenced by fread_fits_line(), make_pixmap(), print_im(), and read_fits().
void set_fits_ipf (FILE * ipf)
Definition at line 489 of file fits_dev.c.
References ipf, and theipf.
Referenced by main().
void set_fits_opf (FILE * opf)
Definition at line 482 of file fits_dev.c.
Referenced by main().
void set_input_pixtype (int thetype)
Definition at line 44 of file fits_dev.c.
References bitpixin, DBL_PIXTYPE, error_exit, FLOAT_PIXTYPE, INT_PIXTYPE, and SHORT_PIXTYPE.
void set_output_pixtype (int thetype)
Definition at line 22 of file fits_dev.c.
References bitpixout, DBL_PIXTYPE, error_exit, FLOAT_PIXTYPE, INT_PIXTYPE, and SHORT_PIXTYPE.
Referenced by main().
void write_fits (short ** f, int N1, int N2, int comc, char * comv[])
Definition at line 169 of file fits_dev.c.
References f, i, N1, N2, write_fits_head(), write_fits_line(), and write_fits_tail().
Referenced by main().
void write_fits_head (int N1, int N2, int comc, char * comv[])
Definition at line 72 of file fits_dev.c.
References bitpixout, COM_LENGTH, length(), line, N1, and N2.
Referenced by fwrite_fits(), main(), and write_fits().
void write_fits_head_ND (int Naxes, int * N, int comc, char * comv[])
Definition at line 549 of file fits_dev.c.
References bitpixout, COM_LENGTH, i, length(), line, and N.
void write_fits_line (short * f, int N1)
Definition at line 105 of file fits_dev.c.
References f, i, and N1.
Referenced by main(), and write_fits().
void write_fits_tail (int N1, int N2)
Definition at line 142 of file fits_dev.c.
References bitpixout, error_exit, FLOAT_PIXTYPE, INT_PIXTYPE, length(), N1, N2, and SHORT_PIXTYPE.
Referenced by fwrite_fits(), main(), and write_fits().
void write_fits_tail_ND (int Naxes, int * N)
Definition at line 584 of file fits_dev.c.
References bitpixout, error_exit, FLOAT_PIXTYPE, i, INT_PIXTYPE, length(), N, and SHORT_PIXTYPE.
Variable Documentation
int bitpixin = SHORT_PIXTYPE [static]
Definition at line 20 of file fits_dev.c.
Referenced by fread_fits_line(), get_input_pixtype(), read_fits_head(), read_fits_head_ND(), and set_input_pixtype().
int bitpixout = SHORT_PIXTYPE [static]
Definition at line 19 of file fits_dev.c.
Referenced by fwrite_fits(), fwrite_fits_line(), set_output_pixtype(), write_fits_head(), write_fits_head_ND(), write_fits_tail(), and write_fits_tail_ND().
FILE* theipf = stdin *theopf = stdout [static]
Definition at line 16 of file fits_dev.c.
Referenced by fread_fits_line(), read_fits_head(), read_fits_head_ND(), read_fits_line(), and set_fits_ipf().
Author
Generated automatically by Doxygen for imcat from the source code.