fits.h
NAME
fits.h -
SYNOPSIS
Data Structures
struct fitscomment
struct fitsheader
Defines
#define MAX_FITS_DIM 7
#define COM_LENGTH 80
#define COM_LENGTH1 81
#define NAME_LENGTH 8
#define NAME_LENGTH1 9
#define VALUE_LENGTH 70
#define VALUE_LENGTH1 71
#define FITS_REC_SIZE 2880
#define UCHAR_PIXTYPE 8
#define SHORT_PIXTYPE 16
#define INT_PIXTYPE 32
#define FLOAT_PIXTYPE -32
#define DBL_PIXTYPE -64
#define UCHAR_MAGIC UCHAR_MAX
#define SHORT_MAGIC SHRT_MIN
#define INT_MAGIC INT_MIN
#define FLOAT_MAGIC (-((float) 0x80000000) * ((float) 0x80000000))
#define DBL_MAGIC (-((double) 0x80000000) * ((double) 0x80000000))
#define BIG_ENDIAN_BYTE_ORDER 0
#define LITTLE_ENDIAN_BYTE_ORDER 1
#define NATIVE_BYTE_ORDER BIG_ENDIAN_BYTE_ORDER
#define NON_NATIVE_BYTE_ORDER LITTLE_ENDIAN_BYTE_ORDER
Typedefs
typedef fitscomment fitscomment
typedef fitsheader fitsheader
Functions
fitsheader * readfitsheader (FILE *stream)
fitsheader * copyfitsheader (fitsheader *theheader)
int writefitsheader (fitsheader *theheader)
int writefitstail (fitsheader *theheader)
int copycommenttostring (fitscomment *thecomment, char *string)
fitscomment * newtextcomment (char *name, char *val, char *comment)
fitscomment * newnumericcomment (char *name, double value, char *comment)
fitscomment * getcommentbyname (char *name, fitsheader *theheader)
double getnumericvalue (fitscomment *thecomment)
char * gettextvalue (fitscomment *thecomment)
void readfitsline (void *f, fitsheader *theheader)
void writefitsline (void *f, fitsheader *theheader)
void readfitsplane (void **f, fitsheader *theheader)
void writefitsplane (void **f, fitsheader *theheader)
void readfitscube (void ***f, fitsheader *theheader)
void writefitscube (void ***f, fitsheader *theheader)
void removecomment (fitscomment *thecomment, fitsheader *fitshead)
void removenamedcomments (char *name, fitsheader *fitshead)
int pixsize (int pixtype)
int read2Dfloatimage (float ***f, int *N1, int *N2, fitsheader **fits, FILE *stream)
int read2Dfloatimage_shm (float ***f, int *N1, int *N2, fitsheader **fits, FILE *stream)
int write2Dfloatimage (float **f, fitsheader *fits)
fitsheader * newfitsheader (int ndim, int *dim, int extpixtype)
fitsheader * new2Dfitsheader (int N1, int N2, int extpixtype)
void argsToString (int argc, char **argv, char *string)
void add_comment (int argc, char **argv, fitsheader *fitshead)
void appendcomment (fitscomment *newcomment, fitsheader *fitshead)
void prependcomment (fitscomment *newcomment, fitsheader *fitshead)
void setextpixtype (fitsheader *fits, int pixtype)
void set2Dimagesize (fitsheader *fits, int N1, int N2)
int skiplines (fitsheader *fits, int nlines)
int updatelinebuffer (fitsheader *theheader)
int byteswapline (void *data, int nel, int pixsize)
int convertmagictonans (void *data, int nel, int pixsize)
int convertnanstomagic (void *data, int nel, int pixsize)
Define Documentation
#define BIG_ENDIAN_BYTE_ORDER 0
Definition at line 30 of file fits.h.
Referenced by main(), readfitsheader(), and writefitsheader().
#define COM_LENGTH 80
Definition at line 9 of file fits.h.
Referenced by add_1comment(), add_comment(), addheadervalue(), argsToString(), copycommenttostring(), main(), read_fits_head(), read_fits_head_ND(), readfitsheader(), write_fits_head(), write_fits_head_ND(), and writefitsheader().
#define COM_LENGTH1 81
Definition at line 10 of file fits.h.
Referenced by add_comment(), copycommenttostring(), main(), and writefitsheader().
#define DBL_MAGIC (-((double) 0x80000000) * ((double) 0x80000000))
Definition at line 28 of file fits.h.
Referenced by convertarray(), convertmagictonans(), and convertnanstomagic().
#define DBL_PIXTYPE -64
Definition at line 22 of file fits.h.
Referenced by addtofitsarray(), convertarray(), fread_fits_line(), main(), pixsize(), read_fits_head(), read_fits_head_ND(), readfitsheader(), readfitsline(), set_input_pixtype(), set_output_pixtype(), writefitsheader(), writefitsline(), and writefitstail().
#define FITS_REC_SIZE 2880
Definition at line 16 of file fits.h.
Referenced by readfitsheader(), and writefitsheader().
#define FLOAT_MAGIC (-((float) 0x80000000) * ((float) 0x80000000))
Definition at line 27 of file fits.h.
Referenced by accumulate(), addarea(), avgpixstack(), avsigclip(), avsigclip2(), block_filter(), convertarray(), convertmagictonans(), convertnanstomagic(), fixedges(), fixholes(), fixpix(), getpixcoords(), getsigma(), iis_display(), iisdisplay(), invdeflection(), magicinit(), main(), makecarray(), project(), scrunch_stream(), setv(), smprofile(), and substitute().
#define FLOAT_PIXTYPE -32
Definition at line 21 of file fits.h.
Referenced by addtofitsarray(), convertarray(), display(), fread_fits_line(), fwrite_fits(), fwrite_fits_line(), main(), newfitsheader(), pixsize(), read_fits_head(), read_fits_head_ND(), readfitsheader(), readfitsline(), set_input_pixtype(), set_output_pixtype(), smcontour(), write_fits_tail(), write_fits_tail_ND(), writefitsheader(), writefitsline(), and writefitstail().
#define INT_MAGIC INT_MIN
Definition at line 26 of file fits.h.
Referenced by convertarray().
#define INT_PIXTYPE 32
Definition at line 20 of file fits.h.
Referenced by addtofitsarray(), convertarray(), fread_fits_line(), fwrite_fits(), fwrite_fits_line(), main(), pixsize(), read_fits_head(), read_fits_head_ND(), readfitsheader(), set_input_pixtype(), set_output_pixtype(), write_fits_tail(), write_fits_tail_ND(), and writefitstail().
#define LITTLE_ENDIAN_BYTE_ORDER 1
Definition at line 31 of file fits.h.
Referenced by readfitsheader().
#define MAX_FITS_DIM 7
Definition at line 8 of file fits.h.
Referenced by main(), and readfitsheader().
#define NAME_LENGTH 8
Definition at line 11 of file fits.h.
Referenced by getcommentbyname(), newnumericcomment(), newtextcomment(), readdataheader(), and readfitsheader().
#define NAME_LENGTH1 9
Definition at line 12 of file fits.h.
Referenced by getcommentbyname().
#define NATIVE_BYTE_ORDER BIG_ENDIAN_BYTE_ORDER
Definition at line 36 of file fits.h.
Referenced by main(), newfitsheader(), readfitsheader(), readfitsline(), and writefitsline().
#define NON_NATIVE_BYTE_ORDER LITTLE_ENDIAN_BYTE_ORDER
Definition at line 37 of file fits.h.
Referenced by newfitsheader(), readfitsheader(), readfitsline(), and writefitsline().
#define SHORT_MAGIC SHRT_MIN
Definition at line 25 of file fits.h.
Referenced by block_filter(), convertarray(), kernel_filter(), and main().
#define SHORT_PIXTYPE 16
Definition at line 19 of file fits.h.
Referenced by addtofitsarray(), convertarray(), doplot(), fread_fits_line(), fwrite_fits(), fwrite_fits_line(), main(), pixsize(), read_fits_head(), read_fits_head_ND(), readdataheader(), readfitsheader(), set_input_pixtype(), set_output_pixtype(), write_fits_tail(), write_fits_tail_ND(), and writefitstail().
#define UCHAR_MAGIC UCHAR_MAX
Definition at line 24 of file fits.h.
Referenced by convertarray().
#define UCHAR_PIXTYPE 8
Definition at line 18 of file fits.h.
Referenced by addtofitsarray(), convertarray(), main(), pixsize(), readfitsheader(), and writefitstail().
#define VALUE_LENGTH 70
Definition at line 13 of file fits.h.
Referenced by gettextvalue(), readdataheader(), and readfitsheader().
#define VALUE_LENGTH1 71
Definition at line 14 of file fits.h.
Referenced by gettextvalue().
Typedef Documentation
typedef struct fitscomment fitscomment
typedef struct fitsheader fitsheader
Function Documentation
void add_comment (int argc, char ** argv, fitsheader * fitshead)
Definition at line 772 of file fits.c.
References appendcomment(), argsToString(), COM_LENGTH1, and newtextcomment().
void appendcomment (fitscomment * newcomment, fitsheader * fitshead)
Definition at line 783 of file fits.c.
References fitsheader::basecomment, and fitscomment::next.
Referenced by add_comment(), doplot(), and main().
void argsToString (int argc, char ** argv, char * string)
Definition at line 750 of file fits.c.
References COM_LENGTH, i, j, len, and pos.
Referenced by add_comment(), and main().
int byteswapline (void * data, int nel, int pixsize)
Definition at line 858 of file fits.c.
References b, i, and pixsize().
Referenced by main(), readfitsline(), and writefitsline().
int convertmagictonans (void * data, int nel, int pixsize)
Definition at line 878 of file fits.c.
References _Dconst, _DNAN, DBL_MAGIC, error_exit, FLOAT_MAGIC, i, INIT, and pixsize().
Referenced by writefitsline().
int convertnanstomagic (void * data, int nel, int pixsize)
Definition at line 905 of file fits.c.
References _Dconst, _DNAN, DBL_MAGIC, error_exit, FLOAT_MAGIC, i, INIT, and pixsize().
Referenced by readfitsline().
int copycommenttostring (fitscomment * thecomment, char * string)
Definition at line 421 of file fits.c.
References COM_LENGTH, COM_LENGTH1, fitscomment::name, and fitscomment::value.
Referenced by writefitsheader().
fitsheader* copyfitsheader (fitsheader * theheader)
Definition at line 261 of file fits.c.
References fitsheader::basecomment, fitscomment::next, and fitscomment::prev.
Referenced by main().
fitscomment* getcommentbyname (char * name, fitsheader * theheader)
Definition at line 474 of file fits.c.
References fitsheader::basecomment, error_exit, fitscomment::name, NAME_LENGTH, NAME_LENGTH1, and fitscomment::next.
Referenced by main(), readfitsheader(), readimheader(), and removenamedcomments().
double getnumericvalue (fitscomment * thecomment)
Definition at line 494 of file fits.c.
References error_exit, val, and fitscomment::value.
Referenced by main(), readfitsheader(), and readimheader().
char* gettextvalue (fitscomment * thecomment)
Definition at line 505 of file fits.c.
References pos, val, fitscomment::value, VALUE_LENGTH, and VALUE_LENGTH1.
Referenced by main(), and readfitsheader().
fitsheader* new2Dfitsheader (int N1, int N2, int extpixtype)
Definition at line 740 of file fits.c.
References N1, N2, and newfitsheader().
Referenced by display(), doplot(), main(), and smcontour().
fitsheader* newfitsheader (int ndim, int * dim, int extpixtype)
Definition at line 713 of file fits.c.
References fitsheader::bscaling, fitsheader::convertnans, fitsheader::extpixtype, fits, FLOAT_PIXTYPE, fitsheader::intpixtype, fitsheader::ipstream, fitsheader::n, NATIVE_BYTE_ORDER, fitsheader::ndim, NON_NATIVE_BYTE_ORDER, fitsheader::opbyteorder, and fitsheader::opstream.
Referenced by main(), and new2Dfitsheader().
fitscomment* newnumericcomment (char * name, double value, char * comment)
Definition at line 452 of file fits.c.
References comment, error_exit, fitscomment::name, NAME_LENGTH, and fitscomment::value.
Referenced by main(), and writefitsheader().
fitscomment* newtextcomment (char * name, char * val, char * comment)
Definition at line 431 of file fits.c.
References comment, error_exit, fitscomment::name, NAME_LENGTH, and fitscomment::value.
Referenced by add_comment(), doplot(), main(), and writefitsheader().
int pixsize (int pixtype)
Definition at line 651 of file fits.c.
References DBL_PIXTYPE, error_exit, FLOAT_PIXTYPE, INT_PIXTYPE, SHORT_PIXTYPE, and UCHAR_PIXTYPE.
Referenced by allocfitsarray(), byteswapline(), convertmagictonans(), convertnanstomagic(), main(), readfitsline(), skiplines(), updatelinebuffer(), and writefitsline().
void prependcomment (fitscomment * newcomment, fitsheader * fitshead)
Definition at line 799 of file fits.c.
References fitsheader::basecomment, fitscomment::next, and fitscomment::prev.
Referenced by main().
int read2Dfloatimage (float *** f, int * N1, int * N2, fitsheader ** fits, FILE * stream)
Definition at line 677 of file fits.c.
References allocFloatArray(), error_exit, f, fits, N1, N2, readfitsheader(), readfitsline(), and y.
Referenced by main().
int read2Dfloatimage_shm (float *** f, int * N1, int * N2, fitsheader ** fits, FILE * stream)
Definition at line 693 of file fits.c.
References error_exit.
Referenced by main().
void readfitscube (void *** f, fitsheader * theheader)
Definition at line 598 of file fits.c.
References f, i, fitsheader::n, and readfitsplane().
fitsheader* readfitsheader (FILE * stream)
Definition at line 26 of file fits.c.
References fitsheader::basecomment, BIG_ENDIAN_BYTE_ORDER, fitsheader::bscale, fitsheader::bscaling, fitsheader::bzero, COM_LENGTH, fitsheader::convertnans, DBL_PIXTYPE, error_exit, fitsheader::extpixtype, FITS_REC_SIZE, FLOAT_PIXTYPE, fitsheader::gcount, getcommentbyname(), getnumericvalue(), gettextvalue(), fitsheader::hasextensions, INT_PIXTYPE, fitsheader::intpixtype, fitsheader::ipbyteorder, fitsheader::ipstream, fitsheader::isextension, line, LITTLE_ENDIAN_BYTE_ORDER, MAX_FITS_DIM, fitsheader::n, fitscomment::name, NAME_LENGTH, NATIVE_BYTE_ORDER, fitsheader::ndim, line::next, fitscomment::next, fitsheader::nextensions, NON_NATIVE_BYTE_ORDER, fitsheader::opbyteorder, fitsheader::opstream, fitsheader::pcount, fitscomment::prev, removecomment(), SHORT_PIXTYPE, UCHAR_PIXTYPE, fitscomment::value, and VALUE_LENGTH.
Referenced by main(), openfits(), read2Dfloatimage(), readdataheader(), readimheader(), and start_command().
void readfitsline (void * f, fitsheader * theheader)
Definition at line 524 of file fits.c.
References fitsheader::bscale, fitsheader::bscaling, byteswapline(), fitsheader::bzero, convertarray(), fitsheader::convertnans, convertnanstomagic(), DBL_PIXTYPE, fitsheader::extpixtype, f, FLOAT_PIXTYPE, fitsheader::intpixtype, fitsheader::ipbyteorder, fitsheader::ipstream, fitsheader::linebuffer, fitsheader::n, N1, NATIVE_BYTE_ORDER, NON_NATIVE_BYTE_ORDER, pixsize(), and updatelinebuffer().
Referenced by contourplot(), main(), makecarray(), read2Dfloatimage(), readdata(), readfitsplane(), scrunch_stream(), and writeimage().
void readfitsplane (void ** f, fitsheader * theheader)
Definition at line 580 of file fits.c.
References f, i, fitsheader::n, and readfitsline().
Referenced by fill_pixmap(), main(), readfitscube(), ReadNewFrame(), and surfaceplot().
void removecomment (fitscomment * thecomment, fitsheader * fitshead)
Definition at line 616 of file fits.c.
References fitsheader::basecomment, fitscomment::next, and fitscomment::prev.
Referenced by readfitsheader(), and removenamedcomments().
void removenamedcomments (char * name, fitsheader * fitshead)
Definition at line 641 of file fits.c.
References getcommentbyname(), and removecomment().
Referenced by main().
void set2Dimagesize (fitsheader * fits, int N1, int N2)
Definition at line 816 of file fits.c.
References fits, fitsheader::linebuffer, fitsheader::n, N1, N2, and fitsheader::ndim.
Referenced by main().
void setextpixtype (fitsheader * fits, int pixtype)
Definition at line 809 of file fits.c.
References fitsheader::extpixtype, fits, and fitsheader::linebuffer.
Referenced by main().
int skiplines (fitsheader * fits, int nlines)
Definition at line 825 of file fits.c.
References fitsheader::extpixtype, fits, fstat, fitsheader::ipstream, fitsheader::linebuffer, fitsheader::n, pixsize(), st, and updatelinebuffer().
Referenced by main().
int updatelinebuffer (fitsheader * theheader)
Definition at line 843 of file fits.c.
References fitsheader::extpixtype, free(), fitsheader::linebuffer, fitsheader::linebuffersize, fitsheader::n, N1, and pixsize().
Referenced by readfitsline(), skiplines(), and writefitsline().
int write2Dfloatimage (float ** f, fitsheader * fits)
Definition at line 698 of file fits.c.
References error_exit, f, fits, fitsheader::n, fitsheader::ndim, writefitsheader(), writefitsline(), writefitstail(), and y.
Referenced by display(), main(), and smcontour().
void writefitscube (void *** f, fitsheader * theheader)
Definition at line 607 of file fits.c.
References f, i, fitsheader::n, and writefitsplane().
Referenced by main().
int writefitsheader (fitsheader * theheader)
Definition at line 290 of file fits.c.
References fitsheader::basecomment, BIG_ENDIAN_BYTE_ORDER, fitsheader::bscale, fitsheader::bscaling, fitsheader::bzero, COM_LENGTH, COM_LENGTH1, copycommenttostring(), DBL_PIXTYPE, error_exit, fitsheader::extpixtype, FITS_REC_SIZE, FLOAT_PIXTYPE, fitsheader::hasextensions, fitsheader::isextension, line, fitsheader::n, fitsheader::ndim, newnumericcomment(), newtextcomment(), fitscomment::next, fitsheader::nextensions, fitsheader::opbyteorder, and fitsheader::opstream.
Referenced by doplot(), main(), and write2Dfloatimage().
void writefitsline (void * f, fitsheader * theheader)
Definition at line 550 of file fits.c.
References fitsheader::bscale, fitsheader::bscaling, byteswapline(), fitsheader::bzero, convertarray(), convertmagictonans(), fitsheader::convertnans, DBL_PIXTYPE, fitsheader::extpixtype, f, FLOAT_PIXTYPE, fitsheader::intpixtype, fitsheader::linebuffer, fitsheader::n, N1, NATIVE_BYTE_ORDER, NON_NATIVE_BYTE_ORDER, fitsheader::opbyteorder, fitsheader::opstream, pixsize(), and updatelinebuffer().
Referenced by doplot(), main(), scrunch_stream(), write2Dfloatimage(), writefitsarray(), and writefitsplane().
void writefitsplane (void ** f, fitsheader * theheader)
Definition at line 589 of file fits.c.
References f, i, fitsheader::n, and writefitsline().
Referenced by main(), outputframe(), and writefitscube().
int writefitstail (fitsheader * theheader)
Definition at line 381 of file fits.c.
References DBL_PIXTYPE, error_exit, fitsheader::extpixtype, FLOAT_PIXTYPE, i, INT_PIXTYPE, length(), fitsheader::n, fitsheader::ndim, fitsheader::opstream, SHORT_PIXTYPE, and UCHAR_PIXTYPE.
Referenced by doplot(), main(), and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.