fitstack2.c
NAME
fitstack2.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'fitstack_modefunc.h'
Defines
#define usage '\n\NAME\n\	fitstack --- fit for transformation coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitstack nexp lmax\n\\n\DESCRIPTION\n\	'fitstack' reads from stdin a catalogue containing the result of\n\	merging all pairs of cats for a stack of 'nexp' images (as created\n\	by 'mergestacks1' or 'mergestacks2') and which must contain entries for\n\	spatial coords 'x', magnitude 'mag' and exposure number 'exp'.\n\	It then fits a model in which sky coords (in frame defined by exposure-0) are\n\		r = r_e + dphi_e r_e + d_e\n\	where the 2x2 matrix dphi allows for rotations between\n\	exposures and possibly atmospheric refraction, and we set\n\	dphi = d = 0 for the 0th exposure.\n\	Sky coords are related to detector (chip) coords by\n\		r_e = x + sum a_m f_m(x)\n\	where m labels the modes, and where each mode coefficient a_m\n\	is a 2-vector, f_1 = y, and the other modes are polynomials\n\	of order 2 through 'lmax', and describe distortions of the\n\	field. For ord = 4 say, the modes are:\n\		y, x^2, xy, y^2, x^3, x^2 y, x y^2, y^3,\n\		x^4, x^3 y, x^2 y^2, x y^3, y^4.\n\	Model is linearised - and so only valid for small\n\	dhi_e (d_e can be large though) - and we\n\	solve for model coefficients by minimising squared residuals.\n\	We also read magnitudes, which we model as:\n\		m_e = m + M_e\n\	where m is the true magnitude and M_e is the magnitude\n\	offset the e'th exposure (relative to exp-0).\n\	See also fitstack.tex.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
#define SCALE 1.0
Functions
main (int argc, char *argv[])
Define Documentation
#define SCALE 1.0
Definition at line 43 of file fitstack2.c.
#define usage '\n\NAME\n\	fitstack --- fit for transformation coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitstack nexp lmax\n\\n\DESCRIPTION\n\	'fitstack' reads from stdin a catalogue containing the result of\n\	merging all pairs of cats for a stack of 'nexp' images (as created\n\	by 'mergestacks1' or 'mergestacks2') and which must contain entries for\n\	spatial coords 'x', magnitude 'mag' and exposure number 'exp'.\n\	It then fits a model in which sky coords (in frame defined by exposure-0) are\n\		r = r_e + dphi_e r_e + d_e\n\	where the 2x2 matrix dphi allows for rotations between\n\	exposures and possibly atmospheric refraction, and we set\n\	dphi = d = 0 for the 0th exposure.\n\	Sky coords are related to detector (chip) coords by\n\		r_e = x + sum a_m f_m(x)\n\	where m labels the modes, and where each mode coefficient a_m\n\	is a 2-vector, f_1 = y, and the other modes are polynomials\n\	of order 2 through 'lmax', and describe distortions of the\n\	field. For ord = 4 say, the modes are:\n\		y, x^2, xy, y^2, x^3, x^2 y, x y^2, y^3,\n\		x^4, x^3 y, x^2 y^2, x y^3, y^4.\n\	Model is linearised - and so only valid for small\n\	dhi_e (d_e can be large though) - and we\n\	solve for model coefficients by minimising squared residuals.\n\	We also read magnitudes, which we model as:\n\		m_e = m + M_e\n\	where m is the true magnitude and M_e is the magnitude\n\	offset the e'th exposure (relative to exp-0).\n\	See also fitstack.tex.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
Definition at line 1 of file fitstack2.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 45 of file fitstack2.c.
References a, A, B, C, d, det(), e, error_exit, exit(), f(), i, indx, j, l, lcpipe, ll, M, m, mag, mylubksb(), myludcmp(), n, phi, SCALE, usage, x, and xp().
Author
Generated automatically by Doxygen for imcat from the source code.