fitstomovie.c
NAME
fitstomovie.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'utils/error.h'
#include 'utils/args.h'
#include 'imlib/fits.h'
#include 'mpegtemplate.h'
Defines
#define usage '\n\n\n\NAME\n\	fitstomovie --- convert a 3 dimensional FITS file to a movie file\n\SYNOPSIS\n\	fitstomovie [-c cmap] [-z zoomfac] [-g | -G dstgif | -M dstmpg] [-x]\n\\n\DESCRIPTION\n\	'fitstomovie' reads a 3 dimensional FITS image from stdin and\n\	generates a set of individual frame images in tmp/nnnnn.sfx\n\	using fitstopnm with nnnnn = 00000, 00001, 00002....\n\\n\	By default sfx = ppm or pgm depending on color/grayscale image type.\n\	With -g option we output a set of sfx = gif files\n\	and with -G dstgif we combine them with multigif to generate\n\	the multiframe output file dstgif and then deleting the temporary frames.\n\	Similarly, with -M option we generate a set of .ppm files and then combine\n\	them with 'mpeg_encode tmp/mpeg.param' where tmp/mpeg.param is generated\n\	by fitstomovie and then deleted. The -M and -G options require that you\n\	have installed mpeg_encode and/or multigif as apprioriate.\n\\n\	With -x option we don't clear up any temporary files we create.\n\\n\	Images should be scaled to min = 0, max = 255.\n\\n\	fitstomovie will first 'rm -f tmp/?????.sfx' so use with care.\n\\n\	Options are:\n\		-c cmap		# pipe fits output through colorize cmap -f 0 255\n\		-z zoomfac	# paint pixels of size 2^zoomfac (0)\n\		-u		# print this message\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define PPM_FRAME_TYPE 0
#define GIF_FRAME_TYPE 1
Functions
int main (int argc, char *argv[])
Define Documentation
#define GIF_FRAME_TYPE 1
Definition at line 49 of file fitstomovie.c.
Referenced by main().
#define PPM_FRAME_TYPE 0
Definition at line 48 of file fitstomovie.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	fitstomovie --- convert a 3 dimensional FITS file to a movie file\n\SYNOPSIS\n\	fitstomovie [-c cmap] [-z zoomfac] [-g | -G dstgif | -M dstmpg] [-x]\n\\n\DESCRIPTION\n\	'fitstomovie' reads a 3 dimensional FITS image from stdin and\n\	generates a set of individual frame images in tmp/nnnnn.sfx\n\	using fitstopnm with nnnnn = 00000, 00001, 00002....\n\\n\	By default sfx = ppm or pgm depending on color/grayscale image type.\n\	With -g option we output a set of sfx = gif files\n\	and with -G dstgif we combine them with multigif to generate\n\	the multiframe output file dstgif and then deleting the temporary frames.\n\	Similarly, with -M option we generate a set of .ppm files and then combine\n\	them with 'mpeg_encode tmp/mpeg.param' where tmp/mpeg.param is generated\n\	by fitstomovie and then deleted. The -M and -G options require that you\n\	have installed mpeg_encode and/or multigif as apprioriate.\n\\n\	With -x option we don't clear up any temporary files we create.\n\\n\	Images should be scaled to min = 0, max = 255.\n\\n\	fitstomovie will first 'rm -f tmp/?????.sfx' so use with care.\n\\n\	Options are:\n\		-c cmap		# pipe fits output through colorize cmap -f 0 255\n\		-z zoomfac	# paint pixels of size 2^zoomfac (0)\n\		-u		# print this message\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file fitstomovie.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 51 of file fitstomovie.c.
References argsinit(), checkalloc(), cmap, error_exit, exit(), fitsheader::extpixtype, fits, flag, getargi(), getargs(), getflag(), GIF_FRAME_TYPE, mpegparamtext, fitsheader::n, fitsheader::ndim, fitsheader::opstream, pixsize(), PPM_FRAME_TYPE, readfitsheader(), usage, writefitsheader(), and z.
Author
Generated automatically by Doxygen for imcat from the source code.