fitstatus.h
NAME
fitstatus.h -
SYNOPSIS
Defines
#define DET_NEG 1
#define TRACE_NEG 2
#define TOO_MANY_ITERATIONS 4
Functions
int getfitstatus (void)
void setfitstatus (int thestatus)
Define Documentation
#define DET_NEG 1
Definition at line 8 of file fitstatus.h.
#define TOO_MANY_ITERATIONS 4
Definition at line 10 of file fitstatus.h.
#define TRACE_NEG 2
Definition at line 9 of file fitstatus.h.
Function Documentation
int getfitstatus (void)
Definition at line 14 of file fitstatus.c.
References fitstatus.
Referenced by brent(), and frprmn().
void setfitstatus (int thestatus)
Definition at line 19 of file fitstatus.c.
References fitstatus.
Referenced by brent(), and frprmn().
Author
Generated automatically by Doxygen for imcat from the source code.