fitshead.h
NAME
fitshead.h -
SYNOPSIS
Data Structures
struct Keyword
Defines
#define FITSBLOCK 2880
Functions
int hgeti4 ()
int hgeti2 ()
int hgetr4 ()
int hgetr8 ()
int hgetra ()
int hgetdec ()
int hgetdate ()
int hgetl ()
int hgets ()
void hputi4 ()
void hputi2 ()
void hputr4 ()
void hputr8 ()
void hputnr8 ()
void hputra ()
void hputdec ()
void hputl ()
void hputs ()
void hputc ()
int hdel ()
int hchange ()
void ra2str ()
void dec2str ()
void deg2str ()
double str2ra ()
double str2dec ()
char * ksearch ()
int isnum ()
char * strsrch ()
char * strnsrch ()
int hlength ()
FILE * fitsropen ()
char * fitsrhead ()
char * fitsrimage ()
int fitswimage ()
FILE * fitsrtopen ()
int fitsrthead ()
void fitsrtlset ()
int fitsrtline ()
short ftgeti2 ()
int ftgeti4 ()
float ftgetr4 ()
double ftgetr8 ()
int ftgetc ()
int * irafrhead ()
char * irafrimage ()
int irafwhead ()
int irafwimage ()
char * iraf2fits ()
int fits2iraf ()
double getpix ()
void putpix ()
void movepix ()
void getvec ()
void putvec ()
void imswap ()
void imswap2 ()
void imswap4 ()
void imswap8 ()
int imswapped ()
Define Documentation
#define FITSBLOCK 2880
Definition at line 60 of file fitshead.h.
Function Documentation
void dec2str ()
Referenced by hputdec(), and pix2wcst().
void deg2str ()
Referenced by pix2wcst().
int fits2iraf ()
char* fitsrhead ()
char* fitsrimage ()
FILE* fitsropen ()
int fitsrthead ()
int fitsrtline ()
void fitsrtlset ()
FILE* fitsrtopen ()
int fitswimage ()
int ftgetc ()
short ftgeti2 ()
int ftgeti4 ()
float ftgetr4 ()
double ftgetr8 ()
double getpix ()
Referenced by getpix(), and main().
void getvec ()
int hchange ()
int hdel ()
int hgetdate ()
Referenced by wcseq(), and wcsinit().
int hgetdec ()
Referenced by wcsinit().
int hgeti2 ()
int hgeti4 ()
Referenced by wcseq(), and wcsinit().
int hgetl ()
int hgetr4 ()
int hgetr8 ()
Referenced by wcseq(), and wcsinit().
int hgetra ()
Referenced by wcsinit().
int hgets ()
Referenced by wcseq(), and wcsinit().
int hlength ()
Referenced by wcsninit().
void hputc ()
Referenced by hputi2(), hputi4(), hputl(), hputnr8(), hputr4(), hputr8(), and hputs().
void hputdec ()
void hputi2 ()
void hputi4 ()
void hputl ()
void hputnr8 ()
void hputr4 ()
void hputr8 ()
void hputra ()
void hputs ()
Referenced by hputdec(), and hputra().
void imswap ()
void imswap2 ()
void imswap4 ()
void imswap8 ()
int imswapped ()
char* iraf2fits ()
int* irafrhead ()
char* irafrimage ()
int irafwhead ()
int irafwimage ()
int isnum ()
char* ksearch ()
Referenced by hchange(), hdel(), hgetc(), hlength(), hputc(), hputcom(), and wcsinit().
void movepix ()
void putpix ()
void putvec ()
void ra2str ()
Referenced by hputra(), and pix2wcst().
double str2dec ()
Referenced by hgetdec(), and str2ra().
double str2ra ()
Referenced by hgetra().
char* strnsrch ()
Referenced by ksearch(), and strsrch().
char* strsrch ()
Referenced by hgetc(), str2dec(), str2ra(), and wcscom().
Author
Generated automatically by Doxygen for imcat from the source code.