fits.c
NAME
fits.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include 'fits.h'
#include 'convertarray.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
#include 'nan.h'
Functions
fitsheader * readfitsheader (FILE *stream)
fitsheader * copyfitsheader (fitsheader *srcfits)
int writefitsheader (fitsheader *theheader)
int writefitstail (fitsheader *theheader)
int copycommenttostring (fitscomment *thecomment, char *string)
fitscomment * newtextcomment (char *name, char *value, char *comment)
fitscomment * newnumericcomment (char *name, double value, char *comment)
fitscomment * getcommentbyname (char *name, fitsheader *theheader)
double getnumericvalue (fitscomment *thecomment)
char * gettextvalue (fitscomment *thecomment)
void readfitsline (void *f, fitsheader *theheader)
void writefitsline (void *f, fitsheader *theheader)
void readfitsplane (void **f, fitsheader *theheader)
void writefitsplane (void **f, fitsheader *theheader)
void readfitscube (void ***f, fitsheader *theheader)
void writefitscube (void ***f, fitsheader *theheader)
void removecomment (fitscomment *thecomment, fitsheader *fitshead)
void removenamedcomments (char *name, fitsheader *fitshead)
int pixsize (int pixtype)
int read2Dfloatimage (float ***f, int *N1, int *N2, fitsheader **fits, FILE *stream)
int read2Dfloatimage_shm (float ***f, int *N1, int *N2, fitsheader **fits, FILE *stream)
int write2Dfloatimage (float **f, fitsheader *fits)
fitsheader * newfitsheader (int ndim, int *dim, int extpixtype)
fitsheader * new2Dfitsheader (int N1, int N2, int extpixtype)
void argsToString (int argc, char **argv, char *string)
void add_comment (int argc, char **argv, fitsheader *fitshead)
void appendcomment (fitscomment *newcomment, fitsheader *fitshead)
void prependcomment (fitscomment *newcomment, fitsheader *fitshead)
void setextpixtype (fitsheader *fits, int pixtype)
void set2Dimagesize (fitsheader *fits, int N1, int N2)
int skiplines (fitsheader *fits, int nlines)
int updatelinebuffer (fitsheader *theheader)
int byteswapline (void *data, int nel, int pixsize)
int convertmagictonans (void *data, int nel, int pixsize)
int convertnanstomagic (void *data, int nel, int pixsize)
Function Documentation
void add_comment (int argc, char ** argv, fitsheader * fitshead)
Definition at line 772 of file fits.c.
void appendcomment (fitscomment * newcomment, fitsheader * fitshead)
Definition at line 783 of file fits.c.
References fitsheader::basecomment, and fitscomment::next.
Referenced by add_comment(), doplot(), and main().
void argsToString (int argc, char ** argv, char * string)
Definition at line 750 of file fits.c.
int byteswapline (void * data, int nel, int pixsize)
Definition at line 858 of file fits.c.
References b, i, and pixsize().
Referenced by main(), readfitsline(), and writefitsline().
int convertmagictonans (void * data, int nel, int pixsize)
Definition at line 878 of file fits.c.
References _Dconst, _DNAN, DBL_MAGIC, error_exit, FLOAT_MAGIC, i, INIT, and pixsize().
Referenced by writefitsline().
int convertnanstomagic (void * data, int nel, int pixsize)
Definition at line 905 of file fits.c.
References _Dconst, _DNAN, DBL_MAGIC, error_exit, FLOAT_MAGIC, i, INIT, and pixsize().
Referenced by readfitsline().
int copycommenttostring (fitscomment * thecomment, char * string)
Definition at line 421 of file fits.c.
References COM_LENGTH, COM_LENGTH1, fitscomment::name, and fitscomment::value.
Referenced by writefitsheader().
fitsheader* copyfitsheader (fitsheader * srcfits)
Definition at line 261 of file fits.c.
References fitsheader::basecomment, fitscomment::next, and fitscomment::prev.
Referenced by main().
fitscomment* getcommentbyname (char * name, fitsheader * theheader)
Definition at line 474 of file fits.c.
References fitsheader::basecomment, error_exit, fitscomment::name, NAME_LENGTH, NAME_LENGTH1, and fitscomment::next.
Referenced by main(), readfitsheader(), readimheader(), and removenamedcomments().
double getnumericvalue (fitscomment * thecomment)
Definition at line 494 of file fits.c.
References error_exit, val, and fitscomment::value.
Referenced by main(), readfitsheader(), and readimheader().
char* gettextvalue (fitscomment * thecomment)
Definition at line 505 of file fits.c.
References pos, val, fitscomment::value, VALUE_LENGTH, and VALUE_LENGTH1.
Referenced by main(), and readfitsheader().
fitsheader* new2Dfitsheader (int N1, int N2, int extpixtype)
Definition at line 740 of file fits.c.
References N1, N2, and newfitsheader().
Referenced by display(), doplot(), main(), and smcontour().
fitsheader* newfitsheader (int ndim, int * dim, int extpixtype)
Definition at line 713 of file fits.c.
References fitsheader::bscaling, fitsheader::convertnans, fitsheader::extpixtype, fits, FLOAT_PIXTYPE, fitsheader::intpixtype, fitsheader::ipstream, fitsheader::n, NATIVE_BYTE_ORDER, fitsheader::ndim, NON_NATIVE_BYTE_ORDER, fitsheader::opbyteorder, and fitsheader::opstream.
Referenced by main(), and new2Dfitsheader().
fitscomment* newnumericcomment (char * name, double value, char * comment)
Definition at line 452 of file fits.c.
References comment, error_exit, fitscomment::name, NAME_LENGTH, and fitscomment::value.
Referenced by main(), and writefitsheader().
fitscomment* newtextcomment (char * name, char * value, char * comment)
Definition at line 431 of file fits.c.
References comment, error_exit, fitscomment::name, NAME_LENGTH, and fitscomment::value.
Referenced by add_comment(), doplot(), main(), and writefitsheader().
int pixsize (int pixtype)
Definition at line 651 of file fits.c.
References DBL_PIXTYPE, error_exit, FLOAT_PIXTYPE, INT_PIXTYPE, SHORT_PIXTYPE, and UCHAR_PIXTYPE.
Referenced by allocfitsarray(), byteswapline(), convertmagictonans(), convertnanstomagic(), main(), readfitsline(), skiplines(), updatelinebuffer(), and writefitsline().
void prependcomment (fitscomment * newcomment, fitsheader * fitshead)
Definition at line 799 of file fits.c.
References fitsheader::basecomment, fitscomment::next, and fitscomment::prev.
Referenced by main().
int read2Dfloatimage (float *** f, int * N1, int * N2, fitsheader ** fits, FILE * stream)
Definition at line 677 of file fits.c.
References allocFloatArray(), error_exit, f, fits, N1, N2, readfitsheader(), readfitsline(), and y.
Referenced by main().
int read2Dfloatimage_shm (float *** f, int * N1, int * N2, fitsheader ** fits, FILE * stream)
Definition at line 693 of file fits.c.
References error_exit.
Referenced by main().
void readfitscube (void *** f, fitsheader * theheader)
Definition at line 598 of file fits.c.
References f, i, fitsheader::n, and readfitsplane().
fitsheader* readfitsheader (FILE * stream)
Definition at line 26 of file fits.c.
References fitsheader::basecomment, BIG_ENDIAN_BYTE_ORDER, fitsheader::bscale, fitsheader::bscaling, fitsheader::bzero, COM_LENGTH, fitsheader::convertnans, DBL_PIXTYPE, error_exit, fitsheader::extpixtype, FITS_REC_SIZE, FLOAT_PIXTYPE, fitsheader::gcount, getcommentbyname(), getnumericvalue(), gettextvalue(), fitsheader::hasextensions, INT_PIXTYPE, fitsheader::intpixtype, fitsheader::ipbyteorder, fitsheader::ipstream, fitsheader::isextension, line, LITTLE_ENDIAN_BYTE_ORDER, MAX_FITS_DIM, fitsheader::n, fitscomment::name, NAME_LENGTH, NATIVE_BYTE_ORDER, fitsheader::ndim, fitscomment::next, line::next, fitsheader::nextensions, NON_NATIVE_BYTE_ORDER, fitsheader::opbyteorder, fitsheader::opstream, fitsheader::pcount, fitscomment::prev, removecomment(), SHORT_PIXTYPE, UCHAR_PIXTYPE, fitscomment::value, and VALUE_LENGTH.
Referenced by main(), openfits(), read2Dfloatimage(), readdataheader(), readimheader(), and start_command().
void readfitsline (void * f, fitsheader * theheader)
Definition at line 524 of file fits.c.
References fitsheader::bscale, fitsheader::bscaling, byteswapline(), fitsheader::bzero, convertarray(), fitsheader::convertnans, convertnanstomagic(), DBL_PIXTYPE, fitsheader::extpixtype, f, FLOAT_PIXTYPE, fitsheader::intpixtype, fitsheader::ipbyteorder, fitsheader::ipstream, fitsheader::linebuffer, fitsheader::n, N1, NATIVE_BYTE_ORDER, NON_NATIVE_BYTE_ORDER, pixsize(), and updatelinebuffer().
Referenced by contourplot(), main(), makecarray(), read2Dfloatimage(), readdata(), readfitsplane(), scrunch_stream(), and writeimage().
void readfitsplane (void ** f, fitsheader * theheader)
Definition at line 580 of file fits.c.
References f, i, fitsheader::n, and readfitsline().
Referenced by fill_pixmap(), main(), readfitscube(), ReadNewFrame(), and surfaceplot().
void removecomment (fitscomment * thecomment, fitsheader * fitshead)
Definition at line 616 of file fits.c.
References fitsheader::basecomment, fitscomment::next, and fitscomment::prev.
Referenced by readfitsheader(), and removenamedcomments().
void removenamedcomments (char * name, fitsheader * fitshead)
Definition at line 641 of file fits.c.
References getcommentbyname(), and removecomment().
Referenced by main().
void set2Dimagesize (fitsheader * fits, int N1, int N2)
Definition at line 816 of file fits.c.
References fits, fitsheader::linebuffer, fitsheader::n, N1, N2, and fitsheader::ndim.
Referenced by main().
void setextpixtype (fitsheader * fits, int pixtype)
Definition at line 809 of file fits.c.
References fitsheader::extpixtype, fits, and fitsheader::linebuffer.
Referenced by main().
int skiplines (fitsheader * fits, int nlines)
Definition at line 825 of file fits.c.
References fitsheader::extpixtype, fits, fstat, fitsheader::ipstream, fitsheader::linebuffer, fitsheader::n, pixsize(), st, and updatelinebuffer().
Referenced by main().
int updatelinebuffer (fitsheader * theheader)
Definition at line 843 of file fits.c.
References fitsheader::extpixtype, free(), fitsheader::linebuffer, fitsheader::linebuffersize, fitsheader::n, N1, and pixsize().
Referenced by readfitsline(), skiplines(), and writefitsline().
int write2Dfloatimage (float ** f, fitsheader * fits)
Definition at line 698 of file fits.c.
References error_exit, f, fits, fitsheader::n, fitsheader::ndim, writefitsheader(), writefitsline(), writefitstail(), and y.
Referenced by display(), main(), and smcontour().
void writefitscube (void *** f, fitsheader * theheader)
Definition at line 607 of file fits.c.
References f, i, fitsheader::n, and writefitsplane().
Referenced by main().
int writefitsheader (fitsheader * theheader)
Definition at line 290 of file fits.c.
References fitsheader::basecomment, BIG_ENDIAN_BYTE_ORDER, fitsheader::bscale, fitsheader::bscaling, fitsheader::bzero, COM_LENGTH, COM_LENGTH1, copycommenttostring(), DBL_PIXTYPE, error_exit, fitsheader::extpixtype, FITS_REC_SIZE, FLOAT_PIXTYPE, fitsheader::hasextensions, fitsheader::isextension, line, fitsheader::n, fitsheader::ndim, newnumericcomment(), newtextcomment(), fitscomment::next, fitsheader::nextensions, fitsheader::opbyteorder, and fitsheader::opstream.
Referenced by doplot(), main(), and write2Dfloatimage().
void writefitsline (void * f, fitsheader * theheader)
Definition at line 550 of file fits.c.
References fitsheader::bscale, fitsheader::bscaling, byteswapline(), fitsheader::bzero, convertarray(), convertmagictonans(), fitsheader::convertnans, DBL_PIXTYPE, fitsheader::extpixtype, f, FLOAT_PIXTYPE, fitsheader::intpixtype, fitsheader::linebuffer, fitsheader::n, N1, NATIVE_BYTE_ORDER, NON_NATIVE_BYTE_ORDER, fitsheader::opbyteorder, fitsheader::opstream, pixsize(), and updatelinebuffer().
Referenced by doplot(), main(), scrunch_stream(), write2Dfloatimage(), writefitsarray(), and writefitsplane().
void writefitsplane (void ** f, fitsheader * theheader)
Definition at line 589 of file fits.c.
References f, i, fitsheader::n, and writefitsline().
Referenced by main(), outputframe(), and writefitscube().
int writefitstail (fitsheader * theheader)
Definition at line 381 of file fits.c.
References DBL_PIXTYPE, error_exit, fitsheader::extpixtype, FLOAT_PIXTYPE, i, INT_PIXTYPE, length(), fitsheader::n, fitsheader::ndim, fitsheader::opstream, SHORT_PIXTYPE, and UCHAR_PIXTYPE.
Referenced by doplot(), main(), and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.