.TH "fitstack_modefunc.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fitstack_modefunc.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBf\fP (int \fBl\fP, int \fBm\fP, double *x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double f (int l, int m, double * x)"
.PP
Definition at line 6 of file fitstack_modefunc.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
