fitstack_amoeba.c
NAME
fitstack_amoeba.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'fitstack.h'
#include 'fitstack_modefunc.h'
#include 'fitstack_read.h'
#include 'amoeba_dbl.h'
#include 'amotry_dbl.h'
Defines
#define usage '\n\NAME\n\	fitstack --- fit for transformation coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitstack nexp [options....]\n\		-l lmin lmax	# min and max order for distortion polynomials\n\		-t ftol		# fractional tolerance (1.e-10)\n\\n\DESCRIPTION\n\	'fitstack' reads from stdin a catalogue containing the result of\n\	merging all pairs of cats for a stack of 'nexp' images (as created\n\	by 'mergestacks1' or 'mergestacks2') and which must contain entries for\n\	spatial coords 'x[2][2]', magnitude 'mag[2]' and exposure number 'exp[2]'.\n\	It then fits a model in which sky coords (in frame defined by exposure-0) are\n\		r = r_e + dphi_e r_e + d_e\n\	where the 2x2 matrix dphi allows for rotations between\n\	exposures and possibly atmospheric refraction, and we set\n\	dphi = d = 0 for the 0th exposure.\n\	It will also optionally then fit for distortion of telescope\n\	using a model in which sky coords r are related to detector coords x by\n\		r_e = x_e + sum a_m f_m(x_e)\n\	where m labels the modes, and where each mode coefficient a_m\n\	is a 2-vector and the modes are polynomials\n\	of order 'lmin' through 'lmax'. 	For lmin = 2, lmax = 4 say, the modes are:\n\		x^2, xy, y^2, x^3, x^2 y, x y^2, y^3,\n\		x^4, x^3 y, x^2 y^2, x y^3, y^4.\n\	We also read magnitudes, which we model as:\n\		m_e = m + M_e\n\	where m is the true magnitude and M_e is the magnitude\n\	offset the e'th exposure (relative to exp-0).\n\	See also fitstack.tex.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
#define SCALE 1.0
Functions
main (int argc, char *argv[])
int make_r (void)
int allocatearrays (void)
double *** allocpositionvector (void)
int printtranslations (void)
int printdistortions (void)
double chisquared (double *v)
int outputrcat (void)
int fittranslations (void)
Variables
double *** x
double ** mag
double *** r = NULL ***re
int ** e
int nprs
int nexp
int nmodes
int ncoefft
int lmin
int lmax
int * ll
int * mm
int dodistfit
double * d [2]
double * phi [2][2]
double * a [2]
Define Documentation
#define SCALE 1.0
Definition at line 53 of file fitstack_amoeba.c.
#define usage '\n\NAME\n\	fitstack --- fit for transformation coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitstack nexp [options....]\n\		-l lmin lmax	# min and max order for distortion polynomials\n\		-t ftol		# fractional tolerance (1.e-10)\n\\n\DESCRIPTION\n\	'fitstack' reads from stdin a catalogue containing the result of\n\	merging all pairs of cats for a stack of 'nexp' images (as created\n\	by 'mergestacks1' or 'mergestacks2') and which must contain entries for\n\	spatial coords 'x[2][2]', magnitude 'mag[2]' and exposure number 'exp[2]'.\n\	It then fits a model in which sky coords (in frame defined by exposure-0) are\n\		r = r_e + dphi_e r_e + d_e\n\	where the 2x2 matrix dphi allows for rotations between\n\	exposures and possibly atmospheric refraction, and we set\n\	dphi = d = 0 for the 0th exposure.\n\	It will also optionally then fit for distortion of telescope\n\	using a model in which sky coords r are related to detector coords x by\n\		r_e = x_e + sum a_m f_m(x_e)\n\	where m labels the modes, and where each mode coefficient a_m\n\	is a 2-vector and the modes are polynomials\n\	of order 'lmin' through 'lmax'. 	For lmin = 2, lmax = 4 say, the modes are:\n\		x^2, xy, y^2, x^3, x^2 y, x y^2, y^3,\n\		x^4, x^3 y, x^2 y^2, x y^3, y^4.\n\	We also read magnitudes, which we model as:\n\		m_e = m + M_e\n\	where m is the true magnitude and M_e is the magnitude\n\	offset the e'th exposure (relative to exp-0).\n\	See also fitstack.tex.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
Definition at line 6 of file fitstack_amoeba.c.
Function Documentation
int allocatearrays (void)
Definition at line 229 of file fitstack_amoeba.c.
References a, Ad, Am, At, Bd, Bm, Bt, Cd, Cm, Ct, d, dm, dodistfit, i, indxd, indxm, indxt, j, m, ndcoefft, nexp, nmcoefft, nmodes, ntcoefft, and phi.
double*** allocpositionvector (void)
Definition at line 247 of file fitstack_amoeba.c.
References allocpositionvector(), error_exit, i, j, n, and nprs.
double chisquared (double * v)
Definition at line 289 of file fitstack_amoeba.c.
int fittranslations (void)
Definition at line 336 of file fitstack_amoeba.c.
References At, Bt, Ct, d, det, e, i, indxt, j, m, mylubksb(), myludcmp(), n, ne, nexp, nprs, ntcoefft, phi, and re.
main (int argc, char * argv[])
Definition at line 66 of file fitstack_amoeba.c.
References chisquared(), d, and n.
int make_r (void)
Definition at line 195 of file fitstack_amoeba.c.
References a, allocpositionvector(), d, e, f(), i, j, ll, M, mm, n, nmodes, nprs, phi, r, x, and xx.
int outputrcat (void)
Definition at line 320 of file fitstack_amoeba.c.
References C, n, N, w, and x.
int printdistortions (void)
Definition at line 279 of file fitstack_amoeba.c.
References d, and n.
int printtranslations (void)
Definition at line 268 of file fitstack_amoeba.c.
References n.
Variable Documentation
double* a[2] [static]
Definition at line 64 of file fitstack_amoeba.c.
double* d[2] [static]
Definition at line 62 of file fitstack_amoeba.c.
int dodistfit [static]
Definition at line 60 of file fitstack_amoeba.c.
int** e
Definition at line 57 of file fitstack_amoeba.c.
int * ll [static]
Definition at line 60 of file fitstack_amoeba.c.
int lmax [static]
Definition at line 60 of file fitstack_amoeba.c.
int lmin [static]
Definition at line 60 of file fitstack_amoeba.c.
double ** mag
Definition at line 56 of file fitstack_amoeba.c.
int * mm [static]
Definition at line 60 of file fitstack_amoeba.c.
int ncoefft [static]
Definition at line 60 of file fitstack_amoeba.c.
int nexp [static]
Definition at line 60 of file fitstack_amoeba.c.
int nmodes [static]
Definition at line 60 of file fitstack_amoeba.c.
int nprs [static]
Definition at line 60 of file fitstack_amoeba.c.
double * phi[2][2] [static]
Definition at line 62 of file fitstack_amoeba.c.
double *** r = NULL ***re
Definition at line 56 of file fitstack_amoeba.c.
double*** x
Definition at line 56 of file fitstack_amoeba.c.
Author
Generated automatically by Doxygen for imcat from the source code.