fitstatus.c
NAME
fitstatus.c -
SYNOPSIS
Defines
#define DET_NEG 1
#define TRACE_NEG 2
#define TOO_MANY_ITERATIONS 4
Functions
int getfitstatus (void)
void setfitstatus (int thestatus)
Variables
int fitstatus
Define Documentation
#define DET_NEG 1
Definition at line 8 of file fitstatus.c.
#define TOO_MANY_ITERATIONS 4
Definition at line 10 of file fitstatus.c.
Referenced by brent(), and frprmn().
#define TRACE_NEG 2
Definition at line 9 of file fitstatus.c.
Function Documentation
int getfitstatus (void)
Definition at line 14 of file fitstatus.c.
References fitstatus.
Referenced by brent(), and frprmn().
void setfitstatus (int thestatus)
Definition at line 19 of file fitstatus.c.
References fitstatus.
Referenced by brent(), and frprmn().
Variable Documentation
int fitstatus [static]
Definition at line 12 of file fitstatus.c.
Referenced by getfitstatus(), and setfitstatus().
Author
Generated automatically by Doxygen for imcat from the source code.