fitstocat.c
NAME
fitstocat.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
#include '../utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	fitstocat --- make lc format list of fits image values\n\\n\SYNOPSIS\n\	fitstocat [-u] [-b]\n\\n\DESCRIPTION\n\	'fitstocat' reads a FITS image from stdin and sends a list of\n\	pixel values to stdout as a lc format catalogue containing\n\	pixel indices x[] and values f.\n\\n\	Options:\n\		-u		# print this message\n\		-b		# generate a binary format catalogue\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Functions
void writeimage (int level)
main (int argc, char *argv[])
Variables
int binarycat
int xdim
int * idim
fitsheader * fits
double * x
double f
float * F
Define Documentation
#define usage '\n\n\n\NAME\n\	fitstocat --- make lc format list of fits image values\n\\n\SYNOPSIS\n\	fitstocat [-u] [-b]\n\\n\DESCRIPTION\n\	'fitstocat' reads a FITS image from stdin and sends a list of\n\	pixel values to stdout as a lc format catalogue containing\n\	pixel indices x[] and values f.\n\\n\	Options:\n\		-u		# print this message\n\		-b		# generate a binary format catalogue\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file fitstocat.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 40 of file fitstocat.c.
References argsinit(), argsToString(), binarycat, error_exit, exit(), F, fits, flag, getflag(), idim, fitsheader::n, fitsheader::ndim, readfitsheader(), usage, writeimage(), x, and xdim.
void writeimage (int level)
Definition at line 85 of file fitstocat.c.
References binarycat, F, fits, i, idim, j, fitsheader::n, readfitsline(), x, and xdim.
Referenced by main().
Variable Documentation
int binarycat [static]
Definition at line 33 of file fitstocat.c.
Referenced by main(), and writeimage().
float* F [static]
Definition at line 36 of file fitstocat.c.
Referenced by main(), and writeimage().
double f [static]
Definition at line 35 of file fitstocat.c.
fitsheader* fits [static]
Definition at line 34 of file fitstocat.c.
int * idim [static]
Definition at line 33 of file fitstocat.c.
Referenced by main(), and writeimage().
double* x [static]
Definition at line 35 of file fitstocat.c.
int xdim [static]
Definition at line 33 of file fitstocat.c.
Referenced by main(), and writeimage().
Author
Generated automatically by Doxygen for imcat from the source code.