fixedges.h
NAME
fixedges.h -
SYNOPSIS
Functions
void fixholes (float **f, int Nx, int Ny)
void fixedges (float **f, int Nx, int Ny)
Function Documentation
void fixedges (float ** f, int Nx, int Ny)
Definition at line 21 of file fixedges.c.
References f, FLOAT_MAGIC, Nx, Ny, x, and y.
Referenced by main().
void fixholes (float ** f, int Nx, int Ny)
Definition at line 69 of file fixedges.c.
References f, fixpix(), FLOAT_MAGIC, free(), getpixcoords(), Nx, Ny, pix, x, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.