fixedges.c
NAME
fixedges.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'imlib/fits.h'
#include 'fixedges.h'
Data Structures
struct pixel
Typedefs
typedef pixel pixel
Functions
int getpixcoords (pixel *pix, int npix, float **f, int Nx, int Ny)
int fixpix (pixel *pix, int npix, float **f, int Nx, int Ny)
void fixedges (float **f, int Nx, int Ny)
void fixholes (float **f, int Nx, int Ny)
Typedef Documentation
typedef struct pixel pixel
Function Documentation
void fixedges (float ** f, int Nx, int Ny)
Definition at line 21 of file fixedges.c.
References f, FLOAT_MAGIC, Nx, Ny, x, and y.
Referenced by main().
void fixholes (float ** f, int Nx, int Ny)
Definition at line 69 of file fixedges.c.
References f, fixpix(), FLOAT_MAGIC, free(), getpixcoords(), Nx, Ny, pix, x, and y.
Referenced by main().
int fixpix (pixel * pix, int npix, float ** f, int Nx, int Ny)
Definition at line 113 of file fixedges.c.
References f, FLOAT_MAGIC, Ny, pix, x, and y.
Referenced by fixholes().
int getpixcoords (pixel * pix, int npix, float ** f, int Nx, int Ny)
Definition at line 92 of file fixedges.c.
References f, FLOAT_MAGIC, Nx, Ny, pix, x, and y.
Referenced by fixholes().
Author
Generated automatically by Doxygen for imcat from the source code.