.TH "fixedges.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fixedges.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfixholes\fP (float **f, int \fBNx\fP, int \fBNy\fP)"
.br
.ti -1c
.RI "void \fBfixedges\fP (float **f, int \fBNx\fP, int \fBNy\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fixedges (float ** f, int Nx, int Ny)"
.PP
Definition at line 21 of file fixedges.c.
.PP
References f, FLOAT_MAGIC, Nx, Ny, x, and y.
.PP
Referenced by main().
.SS "void fixholes (float ** f, int Nx, int Ny)"
.PP
Definition at line 69 of file fixedges.c.
.PP
References f, fixpix(), FLOAT_MAGIC, free(), getpixcoords(), Nx, Ny, pix, x, and y.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
