flatten.c
NAME
flatten.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	flatten --- convert 3-D fits to 2_D\n\\n\SYNOPSIS\n\	flatten [options...] \n\\n\DESCRIPTION\n\	\'flatten\' reads a 3-dimensional fits file from standard\n\	input and writes a 2-dimensional version to stdout.\n\	By default the output image is simply the concatenation\n\	of the input image planes.\n\\n\	Options are:\n\		-c ncols	# write images in rows ncols wide (1)\n\\n\BUGS\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	flatten --- convert 3-D fits to 2_D\n\\n\SYNOPSIS\n\	flatten [options...] \n\\n\DESCRIPTION\n\	\'flatten\' reads a 3-dimensional fits file from standard\n\	input and writes a 2-dimensional version to stdout.\n\	By default the output image is simply the concatenation\n\	of the input image planes.\n\\n\	Options are:\n\		-c ncols	# write images in rows ncols wide (1)\n\\n\BUGS\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file flatten.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 34 of file flatten.c.
References add_comment(), error_exit, exit(), fitsheader::extpixtype, f, fits, free(), i, fitsheader::n, N1, N2, fitsheader::ndim, pixsize(), readfitsheader(), usage, writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.