flip.c
NAME
flip.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	flip --- reflect or rotate a fits image\n\SYNOPSIS\n\	flip [h|v]\n\\n\DESCRIPTION\n\	By default \'flip\' rotates an image by 180 degrees to\n\	produce an image of the same dimensions.\n\	With optional first argument 'h' or 'v' it will reflect the image\n\	about the horizontal or vertical axis respectively.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define ROTATE_MODE 0
#define REFLECT_H_MODE 1
#define REFLECT_V_MODE 2
Functions
int main (int argc, char *argv[])
Define Documentation
#define REFLECT_H_MODE 1
Definition at line 28 of file flip.c.
Referenced by main().
#define REFLECT_V_MODE 2
Definition at line 29 of file flip.c.
Referenced by main().
#define ROTATE_MODE 0
Definition at line 27 of file flip.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	flip --- reflect or rotate a fits image\n\SYNOPSIS\n\	flip [h|v]\n\\n\DESCRIPTION\n\	By default \'flip\' rotates an image by 180 degrees to\n\	produce an image of the same dimensions.\n\	With optional first argument 'h' or 'v' it will reflect the image\n\	about the horizontal or vertical axis respectively.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file flip.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 31 of file flip.c.
References add_comment(), allocFloatArray(), error_exit, exit(), fits, i, j, N1, N2, read2Dfloatimage(), REFLECT_H_MODE, REFLECT_V_MODE, ROTATE_MODE, usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.