fmedian.h
NAME
fmedian.h -
SYNOPSIS
Functions
float fmedian (float *farray, int nel)
int descfloatcmp (void *f1, void *f2)
Function Documentation
int descfloatcmp (void * f1, void * f2)
Definition at line 28 of file fmedian.c.
Referenced by fmedian().
float fmedian (float * farray, int nel)
Definition at line 13 of file fmedian.c.
References descfloatcmp(), error_exit, and f.
Referenced by average(), avsigclip2(), getpix(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.