fmedian.c
NAME
fmedian.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'fmedian.h'
#include 'error.h'
Functions
float fmedian (float *f, int nel)
int descfloatcmp (void *p1, void *p2)
Function Documentation
int descfloatcmp (void * p1, void * p2)
Definition at line 28 of file fmedian.c.
Referenced by fmedian().
float fmedian (float * f, int nel)
Definition at line 13 of file fmedian.c.
References descfloatcmp(), error_exit, and f.
Referenced by average(), avsigclip2(), getpix(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.