.TH "fourn.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fourn.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSWAP\fP(\fBa\fP, \fBb\fP)   tempr=(\fBa\fP);(\fBa\fP)=(\fBb\fP);(\fBb\fP)=tempr"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfourn\fP (float \fBdata\fP[], unsigned long \fBnn\fP[], int \fBndim\fP, int isign)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define SWAP(\fBa\fP, \fBb\fP)   tempr=(\fBa\fP);(\fBa\fP)=(\fBb\fP);(\fBb\fP)=tempr"
.PP
Definition at line 2 of file fourn.c.
.PP
Referenced by amoeba(), fourn(), and main().
.SH "Function Documentation"
.PP 
.SS "void fourn (float data[], unsigned long nn[], int ndim, int isign)"
.PP
Definition at line 4 of file fourn.c.
.PP
References n, and SWAP.
.PP
Referenced by rlft3().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
