fp.c
NAME
fp.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/args.h'
#include '../../imlib/filters.h'
#include '../../utils/arrays.h'
Defines
#define usage '\n\n\NAME\n\ fp --- hierarchical object finder\n\\n\SYNOPSIS\n\ fp [-u] [-r r1 r2] [-n nplanes]\n\\n\DESCRIPTION\n\ fp .....\n\\n\AUTHOR\n\ Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
#define MAGIC FLOAT_MAGIC
#define PI M_PI
#define TINY 1.e-20
#define ZMAX 10
Functions
main (int argc, char *argv[])
float thefilterfunction (float ki, float kj)
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 27 of file fp.c.
#define PI M_PI
Definition at line 28 of file fp.c.
#define TINY 1.e-20
Definition at line 29 of file fp.c.
#define usage '\n\n\NAME\n\ fp --- hierarchical object finder\n\\n\SYNOPSIS\n\ fp [-u] [-r r1 r2] [-n nplanes]\n\\n\DESCRIPTION\n\ fp .....\n\\n\AUTHOR\n\ Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
Definition at line 1 of file fp.c.
#define ZMAX 10
Definition at line 82 of file fp.c.
Referenced by gaussballfunction(), gaussellipsoidfunction(), gaussianfilterfunc(), and thefilterfunction().
Function Documentation
main (int argc, char * argv[])
Definition at line 31 of file fp.c.
References add_comment(), allocFloatArray(), argsinit(), copyfitsheader(), error_exit, exit(), flag, getargd(), getargi(), getflag(), mexicanfilter(), fitsheader::n, N1, N2, fitsheader::ndim, read2Dfloatimage(), usage, writefitsheader(), writefitsplane(), and writefitstail().
float thefilterfunction (float ki, float kj)
Definition at line 87 of file fp.c.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.