.TH "FrameBuf" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrameBuf \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBframeno\fP"
.br
.ti -1c
.RI "char * \fBframebuf\fP"
.br
.ti -1c
.RI "char \fBlabel\fP [SZ_LABEL+1]"
.br
.ti -1c
.RI "\fBCtran\fP \fBctran\fP"
.br
.ti -1c
.RI "char \fBwcsbuf\fP [SZ_WCSBUF]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBCtran\fP \fBFrameBuf::ctran\fP"
.PP
Definition at line 141 of file vximtool.c.
.SS "char* \fBFrameBuf::framebuf\fP"
.PP
Definition at line 139 of file vximtool.c.
.SS "int \fBFrameBuf::frameno\fP"
.PP
Definition at line 138 of file vximtool.c.
.SS "char \fBFrameBuf::label\fP[SZ_LABEL+1]"
.PP
Definition at line 140 of file vximtool.c.
.SS "char \fBFrameBuf::wcsbuf\fP[SZ_WCSBUF]"
.PP
Definition at line 142 of file vximtool.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
