front.c
NAME
front.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include <X11/Xlib.h>
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <X11/cursorfont.h>
#include <X11/Xaw/Label.h>
#include <X11/Xaw/Box.h>
#include <X11/Xaw/Form.h>
#include <X11/Xaw/Command.h>
#include <X11/Xaw/Viewport.h>
#include <X11/Xaw/Scrollbar.h>
#include <X11/Xaw/Dialog.h>
#include <X11/Xaw/Cardinals.h>
#include 'front.h'
#include 'back.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../imlib/fits.h'
Data Structures
struct _AppResources
Typedefs
typedef _AppResources AppResources
Functions
main (int argc, char **argv)
void Syntax (XtAppContext app_con, char *call)
void xfgetargstring (char **argstrptr)
float xfgetvalue (int name)
void makewidgetdatabase (void)
int xfgetwidgetnumber (Widget thewidget)
Widget xfgetwidget (int thenumber)
void setlabelstring (Widget w, char *thestring)
void setlabelnumber (Widget w, float thenumber)
Variables
XtResource resources []
String fallback_resources []
XrmOptionDescRec options []
char * helpmsg []
Widget toplevel
Widget picwidget
Widget viewport
Widget topform
Widget stats
Widget flabel
Widget tlabel
Widget widgetlist [100]
int numberlist [100]
AppResources app_resources
char argstring [256]
Typedef Documentation
typedef struct _AppResources AppResources
Function Documentation
main (int argc, char ** argv)
Definition at line 97 of file front.c.
References alloc_shades(), app_resources, argsToString(), argstring, _AppResources::blocksize, _AppResources::colormapindex, create_pixmap(), fallback_resources, fill_pixmap(), flabel, _AppResources::fmax, _AppResources::fmin, makewidgetdatabase(), makeXImage(), myworkproc1(), N1, N2, options, picwidget, readimheader(), resources, setblocksize(), setcolormapindex(), setfrange(), showpixmap(), stats, Syntax(), tlabel, topform, toplevel, True, and viewport.
void makewidgetdatabase (void)
Definition at line 236 of file front.c.
Referenced by main().
void setlabelnumber (Widget w, float thenumber)
Definition at line 297 of file front.c.
void setlabelstring (Widget w, char * thestring)
Definition at line 284 of file front.c.
void Syntax (XtAppContext app_con, char * call)
Definition at line 193 of file front.c.
void xfgetargstring (char ** argstrptr)
Definition at line 210 of file front.c.
float xfgetvalue (int name)
Definition at line 218 of file front.c.
Widget xfgetwidget (int thenumber)
Definition at line 268 of file front.c.
int xfgetwidgetnumber (Widget thewidget)
Definition at line 252 of file front.c.
Variable Documentation
AppResources app_resources [static]
Definition at line 93 of file front.c.
Referenced by main(), and xfgetvalue().
char argstring[256] [static]
Definition at line 94 of file front.c.
Referenced by main(), and xfgetargstring().
String fallback_resources[]
Initial value:.nf
 {
  '*Viewport*allowVert: True',
  '*Viewport*allowHoriz: True',
        '*Scrollbar*length: 100',
  '*picwidget.cursor: crosshair',
  '*picwidget.foreground: yellow',
  '*Form.background: DarkSlateBlue',
  '*Command.background: CornflowerBlue',
  '*Label.background: LightBlue',
  '*Scrollbar.background: LightBlue',
  '*picwidget.background: grey',
    NULL,
}
Definition at line 54 of file front.c.
Referenced by main().
Widget flabel [static]
Definition at line 87 of file front.c.
Referenced by main(), and makewidgetdatabase().
char* helpmsg[] [static]
Initial value:.nf
 {
    '-min fmin minimum f-value (0.0)',
    '-max fmax maximum f-value (255)',
    '-b blocksize paint pixels this size (1)',
    '-c cmapindex colormap (-1)',
NULL }
Definition at line 76 of file front.c.
Referenced by Syntax().
int numberlist[100] [static]
Definition at line 90 of file front.c.
Referenced by makewidgetdatabase(), xfgetwidget(), and xfgetwidgetnumber().
XrmOptionDescRec options[] [static]
Initial value:.nf
 {
    {'-min', 'fmin', XrmoptionSepArg, NULL},
    {'-max', 'fmax', XrmoptionSepArg, NULL},
    {'-b', 'blocksize', XrmoptionSepArg, NULL},
    {'-c', 'colormapindex', XrmoptionSepArg, NULL},
}
Definition at line 68 of file front.c.
Referenced by main().
Widget picwidget [static]
Definition at line 85 of file front.c.
Referenced by main(), and makewidgetdatabase().
XtResource resources[] [static]
Initial value:.nf
 {
    {'fmin', 'Fmin', XtRFloat, sizeof(float),
     XtOffsetOf(AppResources, fmin), XtRString, '0.0' },
    {'fmax', 'Fmax', XtRFloat, sizeof(float),
     XtOffsetOf(AppResources, fmax), XtRString, '256.0' },
    {'blocksize', 'Blocksize', XtRInt, sizeof(int),
     XtOffsetOf(AppResources, blocksize), XtRImmediate, (XtPointer) 1},
    {'colormapindex', 'Colormapindex', XtRInt, sizeof(int),
     XtOffsetOf(AppResources, colormapindex), XtRImmediate, (XtPointer) -1},
}
Definition at line 43 of file front.c.
Referenced by main().
Widget stats [static]
Definition at line 86 of file front.c.
Referenced by main().
Widget tlabel [static]
Definition at line 87 of file front.c.
Referenced by main(), and makewidgetdatabase().
Widget topform [static]
Definition at line 86 of file front.c.
Referenced by main().
Widget toplevel [static]
Definition at line 84 of file front.c.
Referenced by main(), and makewidgetdatabase().
Widget viewport [static]
Definition at line 85 of file front.c.
Referenced by main().
Widget widgetlist[100] [static]
Definition at line 89 of file front.c.
Referenced by makewidgetdatabase(), xfgetwidget(), and xfgetwidgetnumber().
Author
Generated automatically by Doxygen for imcat from the source code.