.TH "frprmn.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frprmn.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfrprmn\fP (float p[], int \fBn\fP, float ftol, int *iter, float *fret, float(*func)(float[]), void(*dfunc)(float[], float[]))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void frprmn (float p[], int n, float ftol, int * iter, float * fret, float(* func)(float[]), void(* dfunc)(float[], float[]))"
.PP
Definition at line 19 of file frprmn.c.
.PP
References EPS, FREEALL, func(), g(), getfitstatus(), h, ITMAX, j, linmin(), n, setfitstatus(), TOO_MANY_ITERATIONS, and vector().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
