frprmn.h
NAME
frprmn.h -
SYNOPSIS
Functions
void frprmn (float p[], int n, float ftol, int *iter, float *fret, float(*func)(float[]), void(*dfunc)(float[], float[]))
Function Documentation
void frprmn (float p[], int n, float ftol, int * iter, float * fret, float(* func)(float[]), void(* dfunc)(float[], float[]))
Definition at line 19 of file frprmn.c.
References EPS, FREEALL, func(), g(), getfitstatus(), h, ITMAX, j, linmin(), n, setfitstatus(), TOO_MANY_ITERATIONS, and vector().
Author
Generated automatically by Doxygen for imcat from the source code.