frprmn.c
NAME
frprmn.c -
SYNOPSIS
#include <math.h>
#include <stdio.h>
#include 'frprmn.h'
#include 'linmin.h'
#include 'nrutil.h'
#include 'fitstatus.h'
Defines
#define ITMAX 200
#define EPS 1.0e-10
#define FREEALL free_vector(xi,1,n);free_vector(h,1,n);free_vector(g,1,n);
Functions
void frprmn (float p[], int n, float ftol, int *iter, float *fret, float(*func)(float[]), void(*dfunc)(float[], float[]))
Define Documentation
#define EPS 1.0e-10
Definition at line 15 of file frprmn.c.
#define FREEALL free_vector(xi,1,n);free_vector(h,1,n);free_vector(g,1,n);
Definition at line 16 of file frprmn.c.
Referenced by frprmn().
#define ITMAX 200
Definition at line 14 of file frprmn.c.
Function Documentation
void frprmn (float p[], int n, float ftol, int * iter, float * fret, float(* func)(float[]), void(* dfunc)(float[], float[]))
Definition at line 19 of file frprmn.c.
References EPS, FREEALL, func(), g(), getfitstatus(), h, ITMAX, j, linmin(), n, setfitstatus(), TOO_MANY_ITERATIONS, and vector().
Author
Generated automatically by Doxygen for imcat from the source code.