.TH "fstatsrec" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fstatsrec \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stats_stuff.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBfmin\fP"
.br
.ti -1c
.RI "float \fBfmax\fP"
.br
.ti -1c
.RI "float \fBfmean\fP"
.br
.ti -1c
.RI "float \fBfmedian\fP"
.br
.ti -1c
.RI "float \fBfupperquartile\fP"
.br
.ti -1c
.RI "float \fBflowerquartile\fP"
.br
.ti -1c
.RI "float \fBfmode\fP"
.br
.ti -1c
.RI "float \fBsigma\fP"
.br
.ti -1c
.RI "long \fBbadpix\fP"
.br
.ti -1c
.RI "long \fBgoodpix\fP"
.br
.ti -1c
.RI "long \fBsamplesize\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long \fBfstatsrec::badpix\fP"
.PP
Definition at line 10 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "float \fBfstatsrec::flowerquartile\fP"
.PP
Definition at line 7 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "float \fBfstatsrec::fmax\fP"
.PP
Definition at line 3 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "float \fBfstatsrec::fmean\fP"
.PP
Definition at line 4 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "float \fBfstatsrec::fmedian\fP"
.PP
Definition at line 5 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "float \fBfstatsrec::fmin\fP"
.PP
Definition at line 2 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "float \fBfstatsrec::fmode\fP"
.PP
Definition at line 8 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "float \fBfstatsrec::fupperquartile\fP"
.PP
Definition at line 6 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "long \fBfstatsrec::goodpix\fP"
.PP
Definition at line 11 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "long \fBfstatsrec::samplesize\fP"
.PP
Definition at line 12 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().
.SS "float \fBfstatsrec::sigma\fP"
.PP
Definition at line 9 of file stats_stuff.h.
.PP
Referenced by fdo_stats(), and main().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
