gaussfitn.c
NAME
gaussfitn.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../../utils/arrays.h'
#include '../../../utils/stats_stuff.h'
#include '../../../utils/frprmn.h'
#include '../../../utils/fitstatus.h'
#include '../../../utils/powell.h'
#include '../../../utils/nrutil.h'
#include 'gaussfitn.h'
Functions
int gaussfitn (float **ff, int N1, int N2, float *f0, float *x, float *y, float *a, float *b, float *phi, int n, float **fmod)
float func (float *p)
Variables
int n1
int n2
int nn
float ** f
float ** fmodel
Function Documentation
float func (float * p)
Definition at line 78 of file gaussfitn.c.
References a, b, c, chi2(), f, fmodel, i, ix, n1, n2, nn, phi, x, xp(), y, and yp().
int gaussfitn (float ** ff, int N1, int N2, float * f0, float * x, float * y, float * a, float * b, float * phi, int n, float ** fmod)
Definition at line 24 of file gaussfitn.c.
References a, b, f, ff, fmodel, free_matrix(), free_vector(), func(), i, matrix(), n, n1, N1, n2, N2, nn, phi, powell(), vector(), x, and y.
Referenced by main().
Variable Documentation
float** f [static]
Definition at line 22 of file gaussfitn.c.
float ** fmodel [static]
Definition at line 22 of file gaussfitn.c.
Referenced by func(), and gaussfitn().
int n1 [static]
function for fitting a Gaussian ellipsiod Definition at line 21 of file gaussfitn.c.
Referenced by func(), and gaussfitn().
int n2 [static]
function for fitting a Gaussian ellipsiod Definition at line 21 of file gaussfitn.c.
Referenced by func(), and gaussfitn().
int nn [static]
function for fitting a Gaussian ellipsiod Definition at line 21 of file gaussfitn.c.
Referenced by func(), and gaussfitn().
Author
Generated automatically by Doxygen for imcat from the source code.