gaussfitn.h
NAME
gaussfitn.h -
SYNOPSIS
Functions
int gaussfitn (float **ff, int N1, int N2, float *f0, float *x, float *y, float *a, float *b, float *phi, int n, float **fmod)
float func (float *p)
Function Documentation
float func (float * p)
Definition at line 67 of file betafit.c.
int gaussfitn (float ** ff, int N1, int N2, float * f0, float * x, float * y, float * a, float * b, float * phi, int n, float ** fmod)
Definition at line 24 of file gaussfitn.c.
References a, b, f, ff, fmodel, free_matrix(), free_vector(), func(), i, matrix(), n, N1, n1, N2, n2, nn, phi, powell(), vector(), x, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.