gaussfit.h
NAME
gaussfit.h -
SYNOPSIS
Functions
float func (float *p)
void dfunc (float *p, float *df)
int gaussfit (float **ff, int N1, int N2, float *f0, float *d, float *a, float *b, float *phi)
void makemodel (float **ff, int N1, int N2, float f0, float *d, float a, float b, float phi)
Function Documentation
void dfunc (float * p, float * df)
float func (float * p)
Definition at line 67 of file betafit.c.
int gaussfit (float ** ff, int N1, int N2, float * f0, float * d, float * a, float * b, float * phi)
Definition at line 23 of file gaussfit.c.
References a, b, d, f, ff, free_matrix(), free_vector(), func(), i, matrix(), N1, n1, N2, n2, phi, powell(), and vector().
void makemodel (float ** ff, int N1, int N2, float f0, float * d, float a, float b, float phi)
Definition at line 95 of file gaussfit.c.
References a, b, c, d, ff, ix, n1, n2, phi, x, xp(), y, and yp().
Author
Generated automatically by Doxygen for imcat from the source code.