.TH "gaussfitn.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaussfitn.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include '../../../utils/arrays.h'\fP
.br
\fC#include '../../../utils/stats_stuff.h'\fP
.br
\fC#include '../../../utils/frprmn.h'\fP
.br
\fC#include '../../../utils/fitstatus.h'\fP
.br
\fC#include '../../../utils/powell.h'\fP
.br
\fC#include '../../../utils/nrutil.h'\fP
.br
\fC#include 'gaussfitn.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgaussfitn\fP (float **\fBff\fP, int \fBN1\fP, int \fBN2\fP, float *\fBf0\fP, float *x, float *y, float *\fBa\fP, float *\fBb\fP, float *\fBphi\fP, int \fBn\fP, float **fmod)"
.br
.ti -1c
.RI "float \fBfunc\fP (float *p)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBn1\fP"
.br
.ti -1c
.RI "int \fBn2\fP"
.br
.ti -1c
.RI "int \fBnn\fP"
.br
.ti -1c
.RI "float ** \fBf\fP"
.br
.ti -1c
.RI "float ** \fBfmodel\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float func (float * p)"
.PP
Definition at line 78 of file gaussfitn.c.
.PP
References a, b, c, chi2(), f, fmodel, i, ix, n1, n2, nn, phi, x, xp(), y, and yp().
.SS "int gaussfitn (float ** ff, int N1, int N2, float * f0, float * x, float * y, float * a, float * b, float * phi, int n, float ** fmod)"
.PP
Definition at line 24 of file gaussfitn.c.
.PP
References a, b, f, ff, fmodel, free_matrix(), free_vector(), func(), i, matrix(), n, n1, N1, n2, N2, nn, phi, powell(), vector(), x, and y.
.PP
Referenced by main().
.SH "Variable Documentation"
.PP 
.SS "float** f\fC [static]\fP"
.PP
Definition at line 22 of file gaussfitn.c.
.SS "float ** \fBfmodel\fP\fC [static]\fP"
.PP
Definition at line 22 of file gaussfitn.c.
.PP
Referenced by func(), and gaussfitn().
.SS "int \fBn1\fP\fC [static]\fP"
.PP
function for fitting a Gaussian ellipsiod Definition at line 21 of file gaussfitn.c.
.PP
Referenced by func(), and gaussfitn().
.SS "int \fBn2\fP\fC [static]\fP"
.PP
function for fitting a Gaussian ellipsiod Definition at line 21 of file gaussfitn.c.
.PP
Referenced by func(), and gaussfitn().
.SS "int \fBnn\fP\fC [static]\fP"
.PP
function for fitting a Gaussian ellipsiod Definition at line 21 of file gaussfitn.c.
.PP
Referenced by func(), and gaussfitn().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
