.TH "gaussfitn.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaussfitn.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgaussfitn\fP (float **\fBff\fP, int \fBN1\fP, int \fBN2\fP, float *\fBf0\fP, float *x, float *y, float *\fBa\fP, float *\fBb\fP, float *\fBphi\fP, int \fBn\fP, float **fmod)"
.br
.ti -1c
.RI "float \fBfunc\fP (float *p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float func (float * p)"
.PP
Definition at line 67 of file betafit.c.
.SS "int gaussfitn (float ** ff, int N1, int N2, float * f0, float * x, float * y, float * a, float * b, float * phi, int n, float ** fmod)"
.PP
Definition at line 24 of file gaussfitn.c.
.PP
References a, b, f, ff, fmodel, free_matrix(), free_vector(), func(), i, matrix(), n, N1, n1, N2, n2, nn, phi, powell(), vector(), x, and y.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
