gaussfit.c
NAME
gaussfit.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../../utils/stats_stuff.h'
#include '../../../utils/frprmn.h'
#include '../../../utils/fitstatus.h'
#include '../../../utils/powell.h'
#include '../../../utils/nrutil.h'
#include 'gaussfit.h'
Functions
int gaussfit (float **ff, int N1, int N2, float *f0, float *d, float *a, float *b, float *phi)
float func (float *p)
void makemodel (float **ff, int N1, int N2, float f0, float *d, float a, float b, float phi)
Variables
int n1
int n2
float ** f
Function Documentation
float func (float * p)
Definition at line 69 of file gaussfit.c.
References a, b, c, chi2(), f, ix, n1, n2, phi, x, xp(), y, and yp().
int gaussfit (float ** ff, int N1, int N2, float * f0, float * d, float * a, float * b, float * phi)
Definition at line 23 of file gaussfit.c.
void makemodel (float ** ff, int N1, int N2, float f0, float * d, float a, float b, float phi)
Definition at line 95 of file gaussfit.c.
Variable Documentation
float** f [static]
Definition at line 21 of file gaussfit.c.
int n1 [static]
function for fitting a Gaussian ellipsiod Definition at line 20 of file gaussfit.c.
Referenced by func(), gaussfit(), and makemodel().
int n2 [static]
function for fitting a Gaussian ellipsiod Definition at line 20 of file gaussfit.c.
Referenced by func(), gaussfit(), and makemodel().
Author
Generated automatically by Doxygen for imcat from the source code.