gaussfitmain.c
NAME
gaussfitmain.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../../imlib/fits.h'
#include '../../../utils/error.h'
#include 'gaussfitn.h'
Defines
#define usage '\n\n\n\NAME\n\	gaussfit --- fit image to gaussian ellipsoid object model\n\\n\SYNOPSIS\n\	gaussfit [options....]\n\		-u		# print this message\n\		-f		# output the model as fits image\n\		-n	n	# fit n gaussians\n\\n\DESCRIPTION\n\	\'gaussfit\' reads a fits image f from stdin and fits\n\	to this a simple gaussian ellipsoid model with central\n\	value f0; semi-axes a,b; position angle phi; at x0, y0:\n\\n\		f(x,y) = f0 * exp(-((X / a)^2 + (Y / b)^2) / 2)\n\\n\	where\n\\n\		X = (x - x0) cos(phi) + (y - y0) sin(phi)\n\		Y = (y - y0) cos(phi) - (x - x0) sin(phi)\n\\n\	Output is:\n\		f0 x0 y0 a b phi\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
#define PI M_PI
#define NMAX 10
Functions
int main (int argc, char *argv[])
Define Documentation
#define NMAX 10
Definition at line 45 of file gaussfitmain.c.
#define PI M_PI
Definition at line 42 of file gaussfitmain.c.
#define usage '\n\n\n\NAME\n\	gaussfit --- fit image to gaussian ellipsoid object model\n\\n\SYNOPSIS\n\	gaussfit [options....]\n\		-u		# print this message\n\		-f		# output the model as fits image\n\		-n	n	# fit n gaussians\n\\n\DESCRIPTION\n\	\'gaussfit\' reads a fits image f from stdin and fits\n\	to this a simple gaussian ellipsoid model with central\n\	value f0; semi-axes a,b; position angle phi; at x0, y0:\n\\n\		f(x,y) = f0 * exp(-((X / a)^2 + (Y / b)^2) / 2)\n\\n\	where\n\\n\		X = (x - x0) cos(phi) + (y - y0) sin(phi)\n\		Y = (y - y0) cos(phi) - (x - x0) sin(phi)\n\\n\	Output is:\n\		f0 x0 y0 a b phi\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
Definition at line 1 of file gaussfitmain.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 47 of file gaussfitmain.c.
References a, add_comment(), allocFloatArray(), b, drand48(), error_exit, exit(), f, fits, gaussfitn(), i, n, N1, N2, NMAX, phi, read2Dfloatimage(), usage, write2Dfloatimage(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.