gen2Dpolymodel.c
NAME
gen2Dpolymodel.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../catlib/cat.h'
#include '../utils/error.h'
#include '../utils/modefunc.h'
Defines
#define usage '\n\n\n\NAME\n\	gen2Dpolymodel --- generate 2D spatial polynomial model\n\\n\SYNOPSIS\n\	gen2Dpolymodel parfile [options...]\n\		-x xname	# specify spatial coordinate name\n\		-s suffix 	# suffix for model values ('mod')\n\\n\DESCRIPTION\n\	'gen2Dpolymodel' reads a catalogue from stdin, and a parameter\n\	file generated by 'fit2Dpolymodel' from 'parfile' and sends to\n\	stdout a catalogue containing all the items from the stdin cat\n\	plus an extra item consisting of the fitted model values:\n\	By default the name of the spatial variable is taken from the\n\	header of the 'parfile', but you can override this with the -x\n\	option. By default the name of the new item is inherited from\n\	the names of the model coefficient item in the 'parfile' with\n\	the addition of the suffix 'mod', but you can change this with\n\	the -s option.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n\n'
Functions
void getaddresses (void *addr, int ndim, int *dim)
main (int argc, char *argv[])
Variables
double ** var
int varind
Define Documentation
#define usage '\n\n\n\NAME\n\	gen2Dpolymodel --- generate 2D spatial polynomial model\n\\n\SYNOPSIS\n\	gen2Dpolymodel parfile [options...]\n\		-x xname	# specify spatial coordinate name\n\		-s suffix 	# suffix for model values ('mod')\n\\n\DESCRIPTION\n\	'gen2Dpolymodel' reads a catalogue from stdin, and a parameter\n\	file generated by 'fit2Dpolymodel' from 'parfile' and sends to\n\	stdout a catalogue containing all the items from the stdin cat\n\	plus an extra item consisting of the fitted model values:\n\	By default the name of the spatial variable is taken from the\n\	header of the 'parfile', but you can override this with the -x\n\	option. By default the name of the new item is inherited from\n\	the names of the model coefficient item in the 'parfile' with\n\	the addition of the suffix 'mod', but you can change this with\n\	the -s option.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n\n'
Definition at line 6 of file gen2Dpolymodel.c.
Function Documentation
void getaddresses (void * addr, int ndim, int * dim)
Definition at line 154 of file gen2Dpolymodel.c.
References getaddresses(), var, and varind.
main (int argc, char * argv[])
Definition at line 46 of file gen2Dpolymodel.c.
References a, addargscomment(), addobjectitem(), object::addrlist, allocitemcontents(), allocobjectcontents(), BINARY_FILE_TYPE, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), error_exit, exit(), f(), get2Dpolymodel(), getaddresses(), getobjectitemindex(), i, inheritcontents(), l, m, MODEFUNC_MAX_VARS, newitembydimarray(), newobject(), nmodes, NUM_TYPE, pos, readcathead(), readobject(), setcatopfiletype(), usage, var, varind, writecathead(), writeobject(), and x.
Variable Documentation
double** var [static]
Definition at line 42 of file gen2Dpolymodel.c.
Referenced by getaddresses(), and main().
int varind [static]
Definition at line 43 of file gen2Dpolymodel.c.
Referenced by getaddresses(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.