gen2Dpolymodelimage.c
NAME
gen2Dpolymodelimage.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../catlib/cat.h'
#include '../utils/error.h'
#include '../utils/modefunc.h'
#include '../utils/arrays.h'
#include '../imlib/fits.h'
Defines
#define usage '\n\n\n\NAME\n\	gen2Dpolymodelimage --- generate 2D spatial polynomial model as fits image\n\\n\SYNOPSIS\n\	gen2Dpolymodelimage parfile N1 N2\n\\n\DESCRIPTION\n\	'gen2Dpolymodelimage' generates a N1 x N2 float format fits image\n\	whose value is given by\n\		f = sum_l sum_m a_lm f_lm(x)\n\	where the mode coefficients are given in a parameters file (as\n\	generated by fit2Dpolymodel perhaps) 'parfile'.\n\\n\	Currently only works for fit to a scalar function.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n\n'
Functions
void getaddresses (void *addr, int ndim, int *dim)
main (int argc, char *argv[])
Variables
double ** var
int varind
Define Documentation
#define usage '\n\n\n\NAME\n\	gen2Dpolymodelimage --- generate 2D spatial polynomial model as fits image\n\\n\SYNOPSIS\n\	gen2Dpolymodelimage parfile N1 N2\n\\n\DESCRIPTION\n\	'gen2Dpolymodelimage' generates a N1 x N2 float format fits image\n\	whose value is given by\n\		f = sum_l sum_m a_lm f_lm(x)\n\	where the mode coefficients are given in a parameters file (as\n\	generated by fit2Dpolymodel perhaps) 'parfile'.\n\\n\	Currently only works for fit to a scalar function.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n\n'
Definition at line 6 of file gen2Dpolymodelimage.c.
Function Documentation
void getaddresses (void * addr, int ndim, int * dim)
main (int argc, char * argv[])
Definition at line 43 of file gen2Dpolymodelimage.c.
References a, allocFloatArray(), error_exit, exit(), f(), F(), fits, FLOAT_PIXTYPE, get2Dpolymodel(), i, ix, l, m, MODEFUNC_MAX_VARS, N1, N2, new2Dfitsheader(), nmodes, pos, usage, write2Dfloatimage(), and x.
Variable Documentation
double** var [static]
Definition at line 39 of file gen2Dpolymodelimage.c.
int varind [static]
Definition at line 40 of file gen2Dpolymodelimage.c.
Author
Generated automatically by Doxygen for imcat from the source code.