generatelmodelimage.c
NAME
generatelmodelimage.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'catlib/cat.h'
#include 'imlib/fits.h'
#include 'utils/error.h'
#include 'utils/args.h'
#include 'utils/lmodel.h'
Defines
#define usage '\n\NAME\n\	generatelmodelimage --- generate realisation of a lmodel as a FITS image\n\\n\SYNOPSIS\n\	generatelmodelimage x1 x2 nx y1 y2 ny .... \n\\n\DESCRIPTION\n\	'generatelmodelimage' reads from stdin a 'lmodel'\n\	and computes a FITS image containing the realisation of the model\n\	function on a grid of points spanning the rectangle bounded by\n\	x = x1, x2; y = y1, y2; etc and with nx samples in x etc.\n\	There must be one triplet of arguments for each dimension of x.\n\	For example, for a 2-dimensional x, the command\n\\n\		generatelmodelimage 0 1 512 0 1 512\n\\n\	will generate an image of the model on the unit square with 512\n\	pixels in each dimension.\n\\n\	If the dependent variable a is a scalar then the dimensionality\n\	of the image is the same as that of the independent variable x.\n\	For a 3-vector x[] for instance\n\\n\		f[iz][iy][ix] = sum_m a_m f_m(x)\n\	with\n\		x[0] = x1 + ix * (x2 - x1) / nx\n\		x[1] = y1 + iy * (y2 - y1) / ny\n\	etc.\n\\n\	If a is a matrix a[j0][j1]....[jn] then the image dimensionality\n\	is the sum of the rank of a and the length of x, and the pixel\n\	values are, for 2-vector x[] say\n\\n\		f[j0][j1]....[jn][iy][ix] = sum_m a_m[j0][j1]....[jn] f_m(x)\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Functions
void * allocfitsarray (fitsheader *fits, int level)
int writefitsarray (void *f, fitsheader *fits, int level)
int addtofitsarray (void *fdst, void *fsrc, double fac, fitsheader *fits, int level)
int generatefm (void *fm, int m, lmodel *themodel, fitsheader *fm_fits, int level)
int aloop (item *theitem, void *a, void *f, void *fm, fitsheader *fm_fits, int level)
main (int argc, char *argv[])
Variables
double * x1
double * x2
double * dx
double * x
Define Documentation
#define usage '\n\NAME\n\	generatelmodelimage --- generate realisation of a lmodel as a FITS image\n\\n\SYNOPSIS\n\	generatelmodelimage x1 x2 nx y1 y2 ny .... \n\\n\DESCRIPTION\n\	'generatelmodelimage' reads from stdin a 'lmodel'\n\	and computes a FITS image containing the realisation of the model\n\	function on a grid of points spanning the rectangle bounded by\n\	x = x1, x2; y = y1, y2; etc and with nx samples in x etc.\n\	There must be one triplet of arguments for each dimension of x.\n\	For example, for a 2-dimensional x, the command\n\\n\		generatelmodelimage 0 1 512 0 1 512\n\\n\	will generate an image of the model on the unit square with 512\n\	pixels in each dimension.\n\\n\	If the dependent variable a is a scalar then the dimensionality\n\	of the image is the same as that of the independent variable x.\n\	For a 3-vector x[] for instance\n\\n\		f[iz][iy][ix] = sum_m a_m f_m(x)\n\	with\n\		x[0] = x1 + ix * (x2 - x1) / nx\n\		x[1] = y1 + iy * (y2 - y1) / ny\n\	etc.\n\\n\	If a is a matrix a[j0][j1]....[jn] then the image dimensionality\n\	is the sum of the rank of a and the length of x, and the pixel\n\	values are, for 2-vector x[] say\n\\n\		f[j0][j1]....[jn][iy][ix] = sum_m a_m[j0][j1]....[jn] f_m(x)\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file generatelmodelimage.c.
Function Documentation
int addtofitsarray (void * fdst, void * fsrc, double fac, fitsheader * fits, int level)
Definition at line 233 of file generatelmodelimage.c.
References DBL_PIXTYPE, error_exit, fits, FLOAT_PIXTYPE, i, INT_PIXTYPE, fitsheader::intpixtype, fitsheader::n, SHORT_PIXTYPE, and UCHAR_PIXTYPE.
Referenced by aloop().
void * allocfitsarray (fitsheader * fits, int level)
Definition at line 181 of file generatelmodelimage.c.
References f, fits, i, fitsheader::intpixtype, fitsheader::n, and pixsize().
Referenced by main().
int aloop (item * theitem, void * a, void * f, void * fm, fitsheader * fm_fits, int level)
Definition at line 164 of file generatelmodelimage.c.
References a, addtofitsarray(), item::dim, f, i, fitsheader::ndim, and item::ndim.
Referenced by main().
int generatefm (void * fm, int m, lmodel * themodel, fitsheader * fm_fits, int level)
Definition at line 217 of file generatelmodelimage.c.
References dx, i, lmodelfunc(), m, fitsheader::n, x, and x1.
Referenced by main().
main (int argc, char * argv[])
Definition at line 66 of file generatelmodelimage.c.
References lmodel::a, a, add_comment(), lmodel::aitem, allocfitsarray(), aloop(), appendcomment(), argsinit(), dx, error_exit, exit(), f, fits, FLOAT_PIXTYPE, generatefm(), getargd(), getargi(), i, fitsheader::intpixtype, m, fitsheader::n, fitsheader::ndim, newfitsheader(), newnumericcomment(), newtextcomment(), lmodel::nmodes, nx, readlmodel(), usage, writefitsarray(), writefitsheader(), writefitstail(), x, x1, x2, and lmodel::xdim.
int writefitsarray (void * f, fitsheader * fits, int level)
Definition at line 200 of file generatelmodelimage.c.
References f, fits, i, fitsheader::n, and writefitsline().
Referenced by main().
Variable Documentation
double * dx [static]
Definition at line 63 of file generatelmodelimage.c.
Referenced by generatefm(), and main().
double * x [static]
Definition at line 63 of file generatelmodelimage.c.
Referenced by generatefm(), and main().
double* x1 [static]
Definition at line 63 of file generatelmodelimage.c.
Referenced by generatefm(), and main().
double * x2 [static]
Definition at line 63 of file generatelmodelimage.c.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.