generatelmodel.c
NAME
generatelmodel.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'catlib/cat.h'
#include 'utils/error.h'
#include 'utils/args.h'
#include 'utils/lmodel.h'
Defines
#define usage '\n\NAME\n\	generatelmodel --- generate lmodel for catalog of points\n\\n\SYNOPSIS\n\	generatelmodel [-n aname] lmodel \n\\n\DESCRIPTION\n\	'generatelmodel' reads from stdin a catalogue containing at least\n\	a position vetor and a linear mode function superposition model\n\	from 'lmodel' and computes the model function for each point in\n\	the catalog.\n\\n\	The name and dimension of the position vector must match 'xname'\n\	and 'xdim' in the lmodel header.\n\\n\	By default the realised values of the functions will be\n\	named as the 'aname' header item in the lmodel header,\n\	and will therefore overwrite any pre-existing opject item\n\	of that name but you can supply an alternative with the -n option.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	generatelmodel --- generate lmodel for catalog of points\n\\n\SYNOPSIS\n\	generatelmodel [-n aname] lmodel \n\\n\DESCRIPTION\n\	'generatelmodel' reads from stdin a catalogue containing at least\n\	a position vetor and a linear mode function superposition model\n\	from 'lmodel' and computes the model function for each point in\n\	the catalog.\n\\n\	The name and dimension of the position vector must match 'xname'\n\	and 'xdim' in the lmodel header.\n\\n\	By default the realised values of the functions will be\n\	named as the 'aname' header item in the lmodel header,\n\	and will therefore overwrite any pre-existing opject item\n\	of that name but you can supply an alternative with the -n option.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file generatelmodel.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 40 of file generatelmodel.c.
References lmodel::a, a, addargscomment(), addobjectitem(), object::addrlist, addtomatrix(), lmodel::aitem, allocitemcontents(), allocobjectcontents(), lmodel::aname, argsinit(), connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), item::dim, error_exit, exit(), flag, FLAG_ARG, getargs(), getcatipfiletype(), getflag(), getobjectitem(), getobjectitemindex(), inheritcontents(), item::itype, lmodelfunc(), m, item::ndim, newitembydimarray(), newobject(), nextargtype(), lmodel::nmodes, NUM_TYPE, readcathead(), readlmodel(), readobject(), setcatipf(), setcatopfiletype(), usage, writecathead(), writeobject(), x, lmodel::xdim, lmodel::xname, and zeromatrix().
Author
Generated automatically by Doxygen for imcat from the source code.