gengaussfit.h
NAME
gengaussfit.h -
SYNOPSIS
Functions
float func (float *p)
void dfunc (float *p, float *df)
int gaussfit (float **ff, int N1, int N2, float *d, float **q, float *f0, float alpha, float beta)
void makemodel (float **ff, int N1, int N2, float *d, float **q, float f0)
Function Documentation
void dfunc (float * p, float * df)
float func (float * p)
Definition at line 67 of file betafit.c.
References f, galpha, gbeta, gn, gN, ix, n1, n2, x, and y.
Referenced by fitall(), and gaussfitn().
int gaussfit (float ** ff, int N1, int N2, float * d, float ** q, float * f0, float alpha, float beta)
Definition at line 32 of file gengaussfit.c.
References alpha, d, f, ff, free_matrix(), free_vector(), func(), galpha, gbeta, i, matrix(), N1, n1, N2, n2, powell(), and vector().
Referenced by do_object_stats(), and main().
void makemodel (float ** ff, int N1, int N2, float * d, float ** q, float f0)
Definition at line 110 of file gengaussfit.c.
References d, ff, galpha, ix, n1, n2, x, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.