gengaussfit.c
NAME
gengaussfit.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../../utils/stats_stuff.h'
#include '../../../utils/frprmn.h'
#include '../../../utils/fitstatus.h'
#include '../../../utils/powell.h'
#include '../../../utils/nrutil.h'
#include 'gengaussfit.h'
Functions
int gaussfit (float **ff, int N1, int N2, float *d, float **q, float *f0, float alpha, float beta)
float func (float *p)
void makemodel (float **ff, int N1, int N2, float *d, float **q, float f0)
Variables
float galpha
float gbeta
int n1
int n2
float ** f
Function Documentation
float func (float * p)
Definition at line 83 of file gengaussfit.c.
References f, galpha, gbeta, gN, gn, ix, n1, n2, x, and y.
Referenced by fitall(), and gaussfitn().
int gaussfit (float ** ff, int N1, int N2, float * d, float ** q, float * f0, float alpha, float beta)
Definition at line 32 of file gengaussfit.c.
References alpha, d, f, ff, free_matrix(), free_vector(), func(), galpha, gbeta, i, matrix(), n1, N1, n2, N2, powell(), and vector().
Referenced by do_object_stats(), and main().
void makemodel (float ** ff, int N1, int N2, float * d, float ** q, float f0)
Definition at line 110 of file gengaussfit.c.
References d, ff, galpha, ix, n1, n2, x, and y.
Referenced by main().
Variable Documentation
float** f [static]
Definition at line 22 of file gengaussfit.c.
float galpha [static]
function for fitting a generalised Gaussian ellipsiod Definition at line 20 of file gengaussfit.c.
Referenced by func(), gaussfit(), and makemodel().
float gbeta [static]
function for fitting a generalised Gaussian ellipsiod Definition at line 20 of file gengaussfit.c.
Referenced by func(), and gaussfit().
int n1 [static]
Definition at line 21 of file gengaussfit.c.
Referenced by func(), gaussfit(), and makemodel().
int n2 [static]
Definition at line 21 of file gengaussfit.c.
Referenced by func(), gaussfit(), and makemodel().
Author
Generated automatically by Doxygen for imcat from the source code.