getbadpix.c
NAME
getbadpix.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../catlib/cat.h'
Defines
#define usage '\n\n\n\NAME\n\	getbadpix --- reject discrepant pixels\n\\n\SYNOPSIS\n\	getbadpix nu referenceimage [option...] \n\		-s	sigma	# rms noise value\n\		-l		# output pixel values as well as positions\n\		-f	d rg	# allow for difference in psf shape\n\\n\DESCRIPTION\n\	By default \'getbadpix\' reads a fits image from stdin, extracts\n\	the value of the image header item with keyword 'SIGMA', and\n\	sends to stdout an 'lc' format catalogue containing the a list\n\	of pixels for which the pixel value differs from the reference\n\	image pixel value by more than nu * SIGMA.\n\\n\	By default, the catalogue contains sinply the pixel position 'x[2]',\n\	but with the -l option it will also contain the input and reference\n\	image pixel values.\n\\n\	If the '-s' option is given the rms noise is read from the following\n\	command line argument rather than from the header.\n\\n\	The -f option is provided to allow for the fact the for bright\n\	objects such as stars the difference between the source and\n\	reference images may greatly exceed the statistical nu * sigma\n\	limit, so instead we reject pixels if |f - fref| exceeds the\n\	greater of:\n\\n\		nu sigma\n\		2 d fref\n\		d fref rg^2 grad(fref)^2 / (fref^2 + sigma^2)\n\\n\	the last two expressions being the difference in the flux of an\n\	approximately gaussian star of radius r in the centre and on the\n\	edge where d is the assumed fractional change in the gaussian\n\	scale length: d = delta rg / rg = d ln(rg).\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
Functions
main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 54 of file getbadpix.c.
#define usage '\n\n\n\NAME\n\	getbadpix --- reject discrepant pixels\n\\n\SYNOPSIS\n\	getbadpix nu referenceimage [option...] \n\		-s	sigma	# rms noise value\n\		-l		# output pixel values as well as positions\n\		-f	d rg	# allow for difference in psf shape\n\\n\DESCRIPTION\n\	By default \'getbadpix\' reads a fits image from stdin, extracts\n\	the value of the image header item with keyword 'SIGMA', and\n\	sends to stdout an 'lc' format catalogue containing the a list\n\	of pixels for which the pixel value differs from the reference\n\	image pixel value by more than nu * SIGMA.\n\\n\	By default, the catalogue contains sinply the pixel position 'x[2]',\n\	but with the -l option it will also contain the input and reference\n\	image pixel values.\n\\n\	If the '-s' option is given the rms noise is read from the following\n\	command line argument rather than from the header.\n\\n\	The -f option is provided to allow for the fact the for bright\n\	objects such as stars the difference between the source and\n\	reference images may greatly exceed the statistical nu * sigma\n\	limit, so instead we reject pixels if |f - fref| exceeds the\n\	greater of:\n\\n\		nu sigma\n\		2 d fref\n\		d fref rg^2 grad(fref)^2 / (fref^2 + sigma^2)\n\\n\	the last two expressions being the difference in the flux of an\n\	approximately gaussian star of radius r in the centre and on the\n\	edge where d is the assumed fractional change in the gaussian\n\	scale length: d = delta rg / rg = d ln(rg).\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file getbadpix.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 57 of file getbadpix.c.
References addargscomment(), BINARY_FILE_TYPE, connectcatheadtoobject(), error_exit, exit(), f, ff, getcommentbyname(), getnumericvalue(), getobjectitemindex(), ix, lcpipe, MAGIC, N1, N2, newobject(), read2Dfloatimage(), readcathead(), setaddress(), setcatipf(), setcatopfiletype(), sigma, usage, writecathead(), writeobject(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.