getclosepairs.c
NAME
getclosepairs.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../../utils/error.h'
#include '../../catlib/cat.h'
#include 'grid.h'
Defines
#define usage '\n\n\NAME\n\	getclosepairs - make catalogue of close pairs from 2 input cats\n\\n\SYNOPSIS\n\	getclosepairs [options....] dmax cat1 cat2\n\		-u		# print this man page\n\		-x xname 	# specify name for coords (x)\n\\n\DESCRIPTION\n\ 'getclosepairs' reads two catalogues cat1, cat2 and writes to stdout\n\	a catalogue containing pairs with |separation| < dmax \n\	Output cat has object items with the same names as in the input cats\n\	(which must have identical object items)\n\	but each object is a 2-vector formed from a pair of\n\	input objects.\n\	It works by installing the objects from the first cat into\n\	a grid of linked lists, and it then reads the objects\n\	from the second cat and outputs a pair-object for\n\	each pair with separation < dmax.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
#define BIG_POS 1.e100
#define BIG_NEG -1.e100
Functions
int identical (cathead *cat1, cathead *cat2)
double sep2 (object *obj1, object *obj2, int xindex)
main (int argc, char *argv[])
Define Documentation
#define BIG_NEG -1.e100
Definition at line 42 of file getclosepairs.c.
#define BIG_POS 1.e100
Definition at line 41 of file getclosepairs.c.
#define usage '\n\n\NAME\n\	getclosepairs - make catalogue of close pairs from 2 input cats\n\\n\SYNOPSIS\n\	getclosepairs [options....] dmax cat1 cat2\n\		-u		# print this man page\n\		-x xname 	# specify name for coords (x)\n\\n\DESCRIPTION\n\ 'getclosepairs' reads two catalogues cat1, cat2 and writes to stdout\n\	a catalogue containing pairs with |separation| < dmax \n\	Output cat has object items with the same names as in the input cats\n\	(which must have identical object items)\n\	but each object is a 2-vector formed from a pair of\n\	input objects.\n\	It works by installing the objects from the first cat into\n\	a grid of linked lists, and it then reads the objects\n\	from the second cat and outputs a pair-object for\n\	each pair with separation < dmax.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file getclosepairs.c.
Function Documentation
int identical (cathead * cat1, cathead * cat2)
Definition at line 202 of file getclosepairs.c.
References item::dim, i, item::itype, j, item::name, item::ndim, item::next, cathead::nobjectitems, and cathead::objectitembase.
Referenced by inheritcontents().
main (int argc, char * argv[])
Definition at line 44 of file getclosepairs.c.
References addargscomment(), addobjectitem(), item::addr, object::addrlist, allocgrid(), allocitemcontents(), allocobjectcontents(), BIG_NEG, BIG_POS, BINARY_FILE_TYPE, copyheaderinfo(), item::dim, dmax, error_exit, exit(), getcatipfiletype(), getgridcoords(), getneighbours(), getobjectitem(), getobjectitemindex(), i, identical(), item::itype, ix, j, MAX_NEIGHBOURS, item::name, item::ndim, newitem(), newobject(), object::next, item::next, object::nitems, NUM_TYPE, cathead::objectitembase, readcathead(), readobject(), sep2(), setcatipf(), setcatipfiletype(), setcatopfiletype(), setgridsize(), usage, writecathead(), writeobject(), x, xmax, and xmin.
double sep2 (object * obj1, object * obj2, int xindex)
Author
Generated automatically by Doxygen for imcat from the source code.