getfitsval.c
NAME
getfitsval.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../catlib/cat.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/args.h'
#include '../../utils/stats_stuff.h'
Defines
#define usage '\n\n\n\NAME\n\	getfitsval --- add values from a fits file to a catalogue\n\\n\SYNOPSIS\n\	getfitsval fitsfile valname [options...]\n\		-x xname	# spatial coordinate ('x')\n\		-m magicval	# magic value (-32768)\n\\n\DESCRIPTION\n\	'getfitsval' reads a catalogue from stdin, which must\n\	contain at least some coordinate 'x' and adds an entry\n\	named 'valname' with value derived from the FITS file\n\	'fitsfile' and writes result to stdout.\n\\n\	The dimensionality of the new entry depends on the dimensionality\n\	of the x-coordinate and the image f. If these match then the new\n\	entry is a scalar; for a two dimensional coordinate and a two\n\	dimensional image for example, the output value is v = f[iy][ix] where\n\		iy = (int) floor(x[1])\n\		ix = (int) floor(x[0])\n\	If the FITS image is of higher dimension, then the new value will\n\	be a vector or matrix. For example, with a 2-vector x and 3D image\n\	f[iz][iy][ix] with dimensions Nz, Ny, Nx, the output value v will be a\n\	vector of size v[Nz], with values\n\		v[iz] = f[iz][iy][ix]\n\	Similarly, if f has five dimensions say, and x is a 3-vector, then\n\	v is a matrix of dimensions v[N5][N4].\n\\n\	By default, getfitsval looks for a spatial coordinate named 'x' but\n\	you can substitute another name with the '-x' option.\n\\n\	Points which lie in pixels with MAGIC value or which\n\	fall outside the image are assigned the value 'magicval'.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Functions
void setv (int level, int xoff, void *v)
main (int argc, char *argv[])
Variables
double magicval
int vndim
int vdim [MAX_DIMS]
int fsize [MAX_DIMS+1]
int xdim
char * f
Define Documentation
#define usage '\n\n\n\NAME\n\	getfitsval --- add values from a fits file to a catalogue\n\\n\SYNOPSIS\n\	getfitsval fitsfile valname [options...]\n\		-x xname	# spatial coordinate ('x')\n\		-m magicval	# magic value (-32768)\n\\n\DESCRIPTION\n\	'getfitsval' reads a catalogue from stdin, which must\n\	contain at least some coordinate 'x' and adds an entry\n\	named 'valname' with value derived from the FITS file\n\	'fitsfile' and writes result to stdout.\n\\n\	The dimensionality of the new entry depends on the dimensionality\n\	of the x-coordinate and the image f. If these match then the new\n\	entry is a scalar; for a two dimensional coordinate and a two\n\	dimensional image for example, the output value is v = f[iy][ix] where\n\		iy = (int) floor(x[1])\n\		ix = (int) floor(x[0])\n\	If the FITS image is of higher dimension, then the new value will\n\	be a vector or matrix. For example, with a 2-vector x and 3D image\n\	f[iz][iy][ix] with dimensions Nz, Ny, Nx, the output value v will be a\n\	vector of size v[Nz], with values\n\		v[iz] = f[iz][iy][ix]\n\	Similarly, if f has five dimensions say, and x is a 3-vector, then\n\	v is a matrix of dimensions v[N5][N4].\n\\n\	By default, getfitsval looks for a spatial coordinate named 'x' but\n\	you can substitute another name with the '-x' option.\n\\n\	Points which lie in pixels with MAGIC value or which\n\	fall outside the image are assigned the value 'magicval'.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file getfitsval.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 60 of file getfitsval.c.
References addargscomment(), addobjectitem(), object::addrlist, allocitemcontents(), allocobjectcontents(), argsinit(), connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), item::dim, error_exit, exit(), f, fits, flag, fsize, getargf(), getargs(), getcatipfiletype(), getflag(), getobjectitem(), getobjectitemindex(), i, inheritcontents(), fitsheader::intpixtype, item::itype, ix, magicval, MAX_DIMS, fitsheader::n, fitsheader::ndim, item::ndim, newitembydimarray(), newobject(), NUM_TYPE, pixsize(), readcathead(), readfitsheader(), readfitsline(), readobject(), setcatopfiletype(), setv(), SHORT_MAGIC, usage, v, vdim, vndim, writecathead(), writeobject(), x, and xdim.
void setv (int level, int xoff, void * v)
Definition at line 196 of file getfitsval.c.
References f, FLOAT_MAGIC, fsize, i, magicval, v, vdim, vndim, and xdim.
Referenced by main().
Variable Documentation
char* f [static]
Definition at line 57 of file getfitsval.c.
int fsize[MAX_DIMS + 1] [static]
Definition at line 56 of file getfitsval.c.
Referenced by main(), and setv().
double magicval [static]
Definition at line 55 of file getfitsval.c.
Referenced by main(), and setv().
int vdim[MAX_DIMS] [static]
Definition at line 56 of file getfitsval.c.
Referenced by main(), and setv().
int vndim [static]
Definition at line 56 of file getfitsval.c.
Referenced by main(), and setv().
int xdim [static]
Definition at line 56 of file getfitsval.c.
Referenced by main(), and setv().
Author
Generated automatically by Doxygen for imcat from the source code.