getisolatedobjects.c
NAME
getisolatedobjects.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../../utils/error.h'
#include '../../catlib/cat.h'
#include 'grid.h'
Defines
#define usage '\n\n\NAME\n\	getisolatedobjects - find isolated objects\n\\n\SYNOPSIS\n\	getisolatedobjects [options....] dmax referencecat\n\		-u		# print this man page\n\		-x xname 	# specify name for coords (x)\n\		-e		# don't exclude zero separation objects\n\\n\DESCRIPTION\n\ 'getisolatedobjects' reads a source catalogue from stdin, a\n\	reference catalogue from 'referencecat' and writes to stdout\n\	a catalogue containing objects from the source cat which\n\	have no reference neighbour with |separation| < d.\n\	It works by installing the objects from the reference cat into\n\	a grid of linked lists, and it then processes the objects\n\	from the source cat sequentially.\n\	The -e option is useful if one wants to find the objects\n\	in a cat which have no close neighbours in the same catalogue.\n\	To do this simply use the source cat as reference cat.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
#define BIG_POS 1.e100
#define BIG_NEG -1.e100
Functions
double sep2 (object *ipobj, int ipxindex, object *refobj, int refxindex)
main (int argc, char *argv[])
Define Documentation
#define BIG_NEG -1.e100
Definition at line 42 of file getisolatedobjects.c.
#define BIG_POS 1.e100
Definition at line 41 of file getisolatedobjects.c.
#define usage '\n\n\NAME\n\	getisolatedobjects - find isolated objects\n\\n\SYNOPSIS\n\	getisolatedobjects [options....] dmax referencecat\n\		-u		# print this man page\n\		-x xname 	# specify name for coords (x)\n\		-e		# don't exclude zero separation objects\n\\n\DESCRIPTION\n\ 'getisolatedobjects' reads a source catalogue from stdin, a\n\	reference catalogue from 'referencecat' and writes to stdout\n\	a catalogue containing objects from the source cat which\n\	have no reference neighbour with |separation| < d.\n\	It works by installing the objects from the reference cat into\n\	a grid of linked lists, and it then processes the objects\n\	from the source cat sequentially.\n\	The -e option is useful if one wants to find the objects\n\	in a cat which have no close neighbours in the same catalogue.\n\	To do this simply use the source cat as reference cat.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file getisolatedobjects.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 44 of file getisolatedobjects.c.
References addargscomment(), object::addrlist, allocgrid(), allocobjectcontents(), BIG_NEG, BIG_POS, BINARY_FILE_TYPE, item::dim, dmax, error_exit, exit(), getcatipfiletype(), getgridcoords(), getneighbours(), getobjectitem(), getobjectitemindex(), i, item::itype, ix, j, MAX_NEIGHBOURS, item::ndim, newobject(), object::next, NUM_TYPE, readcathead(), readobject(), sep2(), setcatipf(), setcatipfiletype(), setcatopfiletype(), setgridsize(), usage, writecathead(), writeobject(), x, xmax, and xmin.
double sep2 (object * ipobj, int ipxindex, object * refobj, int refxindex)
Definition at line 188 of file getisolatedobjects.c.
References object::addrlist, dx, and dy.
Author
Generated automatically by Doxygen for imcat from the source code.