getplane.c
NAME
getplane.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	getplane --- extracts an image plane from multi-dimensional fits image\n\\n\SYNOPSIS\n\	getplane p\n\\n\DESCRIPTION\n\	\'getplane\' reads from stdin a N-dimensional fits image\n\		f_in[Nn][Nn-1]....[N2][N1]\n\	and writes to stdout a N-1 dimensional image\n\		f_out[Nn-1]....[N2][N1]\n\	with values\n\		f_out[xn-1]...[x2][x1] = f_in[p][xn-1]...[x2][x1]\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	getplane --- extracts an image plane from multi-dimensional fits image\n\\n\SYNOPSIS\n\	getplane p\n\\n\DESCRIPTION\n\	\'getplane\' reads from stdin a N-dimensional fits image\n\		f_in[Nn][Nn-1]....[N2][N1]\n\	and writes to stdout a N-1 dimensional image\n\		f_out[Nn-1]....[N2][N1]\n\	with values\n\		f_out[xn-1]...[x2][x1] = f_in[p][xn-1]...[x2][x1]\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file getplane.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 28 of file getplane.c.
References add_comment(), error_exit, exit(), fitsheader::extpixtype, f, fits, free(), fitsheader::intpixtype, fitsheader::n, fitsheader::ndim, pixsize(), readfitsheader(), readfitsline(), skiplines(), usage, writefitsheader(), writefitsline(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.