getplanes.c
NAME
getplanes.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	getplanes --- extracts a set of planes from multi-dimensional fits image\n\\n\SYNOPSIS\n\	getplanes [-f srcfits] i1 i2...\n\\n\DESCRIPTION\n\	\'getplanes\' reads from stdin a N-dimensional fits image\n\		f_in[Nm]....[N2][N1]\n\	and writes to stdout a N dimensional image with planes\n\		f_out[i1]....[N2][N1]\n\		f_out[i2]....[N2][N1]\n\	etc.\n\\n\	With -f option we read from named file (and we use fseek() to\n\	move around in the file for efficiency).\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	getplanes --- extracts a set of planes from multi-dimensional fits image\n\\n\SYNOPSIS\n\	getplanes [-f srcfits] i1 i2...\n\\n\DESCRIPTION\n\	\'getplanes\' reads from stdin a N-dimensional fits image\n\		f_in[Nm]....[N2][N1]\n\	and writes to stdout a N dimensional image with planes\n\		f_out[i1]....[N2][N1]\n\		f_out[i2]....[N2][N1]\n\	etc.\n\\n\	With -f option we read from named file (and we use fseek() to\n\	move around in the file for efficiency).\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file getplanes.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 32 of file getplanes.c.
References add_comment(), copyfitsheader(), error_exit, exit(), fitsheader::extpixtype, f, i, ipf, j, fitsheader::n, fitsheader::ndim, pixsize(), readfitsheader(), usage, writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.