.TH "getrange.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getrange.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgetrange\fP (float *f, int \fBnpts\fP, float *\fBfmin\fP, float *\fBfmax\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void getrange (float * f, int npts, float * fmin, float * fmax)"
.PP
Definition at line 5 of file getrange.c.
.PP
References f, fmin, i, max, min, and npts.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
