.TH "getshape.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getshape.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgetshape\fP (double *x, double *fb0, double *dfb, double rwindow, double *flux, double *\fBd\fP, double *\fBe\fP, double **psm, double **psh, float **f, int \fBN1\fP, int \fBN2\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int getshape (double * x, double * fb0, double * dfb, double rwindow, double * flux, double * d, double * e, double ** psm, double ** psh, float ** f, int N1, int N2)"
.PP
Definition at line 23 of file getshape.c.
.PP
References d, di, dj, dx, dy, e, f, i, j, l, m, MAGIC, N1, r, R_MAX_FACTOR, W, and x.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
