.TH "getshape1.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getshape1.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBGetshape\fP (double *x, double *fb0, double *dfb, double rwindow, double *flux, double *q, double **R, double **P, float **f, int \fBN1\fP, int \fBN2\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int Getshape (double * x, double * fb0, double * dfb, double rwindow, double * flux, double * q, double ** R, double ** P, float ** f, int N1, int N2)"
.PP
Definition at line 24 of file getshape1.c.
.PP
References a, b, di, dj, dx, f, i, j, l, M, m, MAGIC, N1, Q_DIM, r, R_MAX_FACTOR, W, and x.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
