getshapesmain.c
NAME
getshapesmain.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../catlib/cat.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/iostream.h'
#include '../../utils/stats_stuff.h'
#include 'getshape.h'
#include 'zap.h'
Defines
#define usage '\n\n\n\NAME\n\	getshapes --- calculate ellipticities etc. for catalogue of objects\n\\n\SYNOPSIS\n\	getshapes	[options...]\n\		-r rname	# name for window radius ('rg')\n\		-m rmult	# multiplier: r_window = rmult * rname (1.0)\n\		-f fitsfile	# specify fits file explicitly\n\		-i 		# ignore the sky background information.\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\		-R		# always output object\n\\n\DESCRIPTION\n\	\'getshapes\' calculates second moments of sky brightness\n\	(and related quantities) for objects detected by (h)findpeaks,\n\	though possibly after having been processed by getsky and/or\n\	apphot. It uses a gaussian window of size determined by\n\	flags -r, -m. Use '-r unity' for r_window = rmult.\n\	It adds the following items to the catalogue:\n\		e[2]		# ellipticity or polarisation\n\		psm[2][2]	# 'smear polarizability tensor'\n\		psh[2][2]	# 'shear polarizability tensor'\n\		d[2] 		# centroid\n\	Sometimes trace of quadrupole moment tensor is negative.\n\	The default behaviour is not to output such objects, but\n\	with -R option (for 'Rambo mode') we output an object\n\	with zero polarization and polarizability.\n\\n\	getshapes uses the iostream library.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	getshapes --- calculate ellipticities etc. for catalogue of objects\n\\n\SYNOPSIS\n\	getshapes	[options...]\n\		-r rname	# name for window radius ('rg')\n\		-m rmult	# multiplier: r_window = rmult * rname (1.0)\n\		-f fitsfile	# specify fits file explicitly\n\		-i 		# ignore the sky background information.\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\		-R		# always output object\n\\n\DESCRIPTION\n\	\'getshapes\' calculates second moments of sky brightness\n\	(and related quantities) for objects detected by (h)findpeaks,\n\	though possibly after having been processed by getsky and/or\n\	apphot. It uses a gaussian window of size determined by\n\	flags -r, -m. Use '-r unity' for r_window = rmult.\n\	It adds the following items to the catalogue:\n\		e[2]		# ellipticity or polarisation\n\		psm[2][2]	# 'smear polarizability tensor'\n\		psh[2][2]	# 'shear polarizability tensor'\n\		d[2] 		# centroid\n\	Sometimes trace of quadrupole moment tensor is negative.\n\	The default behaviour is not to output such objects, but\n\	with -R option (for 'Rambo mode') we output an object\n\	with zero polarization and polarizability.\n\\n\	getshapes uses the iostream library.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 5 of file getshapesmain.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 57 of file getshapesmain.c.
References addargscomment(), addobjectitem(), object::addrlist, allocFloatArray(), allocitemcontents(), allocobjectcontents(), allocShortArray(), BINARY_FILE_TYPE, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), d, e, error_exit, exit(), iostream::f, f, fits, getheaderitemaddress(), getobjectitemindex(), getshape(), cathead::headeritembase, inheritcontents(), ix, N1, N2, newitem(), newobject(), NUM_TYPE, openiostream(), r, read2Dfloatimage(), readcathead(), readobject(), setcatipf(), setcatopf(), setcatopfiletype(), UNZAP_MODE, usage, writecathead(), writeobject(), x, zap(), and ZAP_MODE.
Author
Generated automatically by Doxygen for imcat from the source code.