getskymain.c
NAME
getskymain.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../catlib/cat.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/stats_stuff.h'
#include 'getsky.h'
#include 'zap.h'
Defines
#define usage '\n\n\n\NAME\n\	getsky --- determine model for local sky background around objects\n\\n\SYNOPSIS\n\	getsky	[options...]\n\		-m mode		# mode for background sky calculation (1)\n\		-a a1 a2	# inner and outer radii (default 16 32)\n\		-f fitsfile	# specify fits file explicitly\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\\n\DESCRIPTION\n\	\'getsky\' determines the local sky background for objects detected\n\	by (h)findpeaks. We determine a mean + gradient model using\n\	modal sky value for each of four quadrants of an\n\	annulus around the object. The inner and outer annulus radii\n\	are a1, and a2 times:\n\		1 pixel		# for mode = 1\n\		rg		# for mode = 2\n\		rh		# for mode = 3\n\		rp		# for mode = 4 \n\	The latter two require that we have already run analyse once.\n\	Getsky adds entries fb0, dfb[2] to the catalogue and sets the\n\	header value 'has_sky'.\n\	By default we use the image named in the catalogue, but you can\n\	specify an alternative (if you want to use one where the objects\n\	have been 'zapped' with makechart for instance).\n\	We require at least 16 good pixels in a viable quadrant. Our strategy is:\n\		0 good quadrants:	# mean and gradient = 0.0\n\		1,2 good quadrants:	# only calculate mean, gradient = 0\n\		3 good quadrants:	# determine mean and gradient\n\		4 good quadrants:	# remove most extreme quadrant. \n\	With the '-Z' option, we ignore pixels around other objects if\n\	distance is <= r * mul.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define CONST_ANNULUS_MODE 1
#define RG_ANNULUS_MODE 2
#define RH_ANNULUS_MODE 3
#define RP_ANNULUS_MODE 4
Functions
main (int argc, char *argv[])
Define Documentation
#define CONST_ANNULUS_MODE 1
Definition at line 59 of file getskymain.c.
Referenced by main().
#define RG_ANNULUS_MODE 2
Definition at line 60 of file getskymain.c.
Referenced by main().
#define RH_ANNULUS_MODE 3
Definition at line 61 of file getskymain.c.
Referenced by main().
#define RP_ANNULUS_MODE 4
Definition at line 62 of file getskymain.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	getsky --- determine model for local sky background around objects\n\\n\SYNOPSIS\n\	getsky	[options...]\n\		-m mode		# mode for background sky calculation (1)\n\		-a a1 a2	# inner and outer radii (default 16 32)\n\		-f fitsfile	# specify fits file explicitly\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\\n\DESCRIPTION\n\	\'getsky\' determines the local sky background for objects detected\n\	by (h)findpeaks. We determine a mean + gradient model using\n\	modal sky value for each of four quadrants of an\n\	annulus around the object. The inner and outer annulus radii\n\	are a1, and a2 times:\n\		1 pixel		# for mode = 1\n\		rg		# for mode = 2\n\		rh		# for mode = 3\n\		rp		# for mode = 4 \n\	The latter two require that we have already run analyse once.\n\	Getsky adds entries fb0, dfb[2] to the catalogue and sets the\n\	header value 'has_sky'.\n\	By default we use the image named in the catalogue, but you can\n\	specify an alternative (if you want to use one where the objects\n\	have been 'zapped' with makechart for instance).\n\	We require at least 16 good pixels in a viable quadrant. Our strategy is:\n\		0 good quadrants:	# mean and gradient = 0.0\n\		1,2 good quadrants:	# only calculate mean, gradient = 0\n\		3 good quadrants:	# determine mean and gradient\n\		4 good quadrants:	# remove most extreme quadrant. \n\	With the '-Z' option, we ignore pixels around other objects if\n\	distance is <= r * mul.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 5 of file getskymain.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 64 of file getskymain.c.
References a1, a2, addargscomment(), addobjectitem(), object::addrlist, allocFloatArray(), allocitemcontents(), allocobjectcontents(), allocShortArray(), BINARY_FILE_TYPE, connectobjecttocathead(), CONST_ANNULUS_MODE, copycontentinfo(), copyheaderinfo(), error_exit, exit(), f, fits, getheaderitemaddress(), getobjectitemindex(), getsky(), inheritcontents(), ix, N1, N2, newitem(), newobject(), NUM_TYPE, r, read2Dfloatimage(), readcathead(), readobject(), RG_ANNULUS_MODE, RH_ANNULUS_MODE, RP_ANNULUS_MODE, setcatipf(), setcatopf(), setcatopfiletype(), UNZAP_MODE, usage, writecathead(), writeobject(), x, zap(), and ZAP_MODE.
Author
Generated automatically by Doxygen for imcat from the source code.