getshapes2.c
NAME
getshapes2.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../catlib/cat.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/stats_stuff.h'
#include 'getshape2.h'
#include 'zap.h'
Defines
#define usage '\n\n\n\NAME\n\	getshapes2 --- calculate ellipticities etc. for catalogue of objects\n\\n\SYNOPSIS\n\	getshapes2 psfimage rf [options...]\n\		-f fitsfile	# specify fits file explicitly\n\		-i 		# ignore the sky background information.\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\\n\DESCRIPTION\n\	\'getshapes2\' is a catalogue filter which calculates polarisation\n\	and polarisability for objects.\n\\n\	It requires that the input catalogue contain at least position\n\	vector 'x[2]', and a (aperture) flux 'flux'.\n\\n\	It uses 'makekernel' to compute the kernels W[i] and K[i][j]\n\	from the psf supplied in the fits image 'psfimage' and\n\	then computes\n\		F 	= sum f[y][x] w[y][x]\n\		q[l] 	= sum f[y][x] W[l][y][x] / F\n\		P[l][m] = sum f[y][x] K[l][m][y][x] / F\n\		R[m]	= sum f[y][x] R[m][y][x] / F\n\	for l = 0,1,2 and m = 1,2\n\\n\	If sky background values (from getsky) are present they will\n\	be used (unless you give -i flag).\n\\n\	Use -Z option to zap circles around neighbouring objects.\n\\n\	By default the source image name is taken from the catalogue\n\	header item 'fits_name', but you can specify alternative\n\	explicitly with -f option.\n\\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
Functions
main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 60 of file getshapes2.c.
#define usage '\n\n\n\NAME\n\	getshapes2 --- calculate ellipticities etc. for catalogue of objects\n\\n\SYNOPSIS\n\	getshapes2 psfimage rf [options...]\n\		-f fitsfile	# specify fits file explicitly\n\		-i 		# ignore the sky background information.\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\\n\DESCRIPTION\n\	\'getshapes2\' is a catalogue filter which calculates polarisation\n\	and polarisability for objects.\n\\n\	It requires that the input catalogue contain at least position\n\	vector 'x[2]', and a (aperture) flux 'flux'.\n\\n\	It uses 'makekernel' to compute the kernels W[i] and K[i][j]\n\	from the psf supplied in the fits image 'psfimage' and\n\	then computes\n\		F 	= sum f[y][x] w[y][x]\n\		q[l] 	= sum f[y][x] W[l][y][x] / F\n\		P[l][m] = sum f[y][x] K[l][m][y][x] / F\n\		R[m]	= sum f[y][x] R[m][y][x] / F\n\	for l = 0,1,2 and m = 1,2\n\\n\	If sky background values (from getsky) are present they will\n\	be used (unless you give -i flag).\n\\n\	Use -Z option to zap circles around neighbouring objects.\n\\n\	By default the source image name is taken from the catalogue\n\	header item 'fits_name', but you can specify alternative\n\	explicitly with -f option.\n\\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 5 of file getshapes2.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 62 of file getshapes2.c.
References addargscomment(), addobjectitem(), object::addrlist, allocFloatArray(), allocitemcontents(), allocobjectcontents(), allocShortArray(), BINARY_FILE_TYPE, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), error_exit, exit(), F(), f, fits, getheaderitemaddress(), getobjectitemindex(), getshape2(), cathead::headeritembase, inheritcontents(), ix, K, l, m, M1, M2, N1, N2, newitem(), newobject(), NUM_TYPE, read2Dfloatimage(), readcathead(), readobject(), setcatipf(), setcatopf(), setcatopfiletype(), UNZAP_MODE, usage, W, w, writecathead(), writeobject(), x, zap(), and ZAP_MODE.
Author
Generated automatically by Doxygen for imcat from the source code.