getsky.h
NAME
getsky.h -
SYNOPSIS
Functions
int getsky (double *fb0, double *dfb, double r1, double r2, double *x, float **f, int N1, int N2)
void pruneextreme (void)
int getplane (double *fb0, double *dfb)
int fmodecmp (const void *ptr1, const void *ptr2)
Function Documentation
int fmodecmp (const void * ptr1, const void * ptr2)
Definition at line 163 of file getsky.c.
References fmode.
Referenced by pruneextreme().
int getplane (double * fb0, double * dfb)
Definition at line 131 of file getsky.c.
References det(), f, fmode, i, qlist, x, xbar, y, and ybar.
Referenced by getsky().
int getsky (double * fb0, double * dfb, double r1, double r2, double * x, float ** f, int N1, int N2)
Definition at line 26 of file getsky.c.
References dx, dy, error_exit, f, ff, fmode, getplane(), ix, liststats(), MAGIC, MAX_PIX, median(), MIN_PIX, N1, N2, pix, pruneextreme(), qlist, r, sigma, x, xbar, and ybar.
Referenced by main().
void pruneextreme (void)
Definition at line 117 of file getsky.c.
References fmode, fmodecmp(), i, median(), and qlist.
Referenced by getsky().
Author
Generated automatically by Doxygen for imcat from the source code.