getshapes3.c
NAME
getshapes3.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../catlib/cat.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/stats_stuff.h'
#include 'getshape3.h'
#include 'zap.h'
Defines
#define usage '\n\n\n\NAME\n\	getshapes3 --- calculate ellipticities etc. for catalogue of objects\n\\n\SYNOPSIS\n\	getshapes3 f_image fs_image psf_image rf [options...]\n\		-i 		# ignore the sky background information.\n\\n\DESCRIPTION\n\	\'getshapes3\' is a catalogue filter which calculates polarisation\n\	and polarisability for objects.\n\\n\	It requires that the input catalogue contain at least position\n\	vector 'x[2]', and a (aperture) flux 'flux'.\n\\n\	It uses 'makekernel' to compute the kernels W[i], K[i][j], ZZ[i][j]\n\	from the psf supplied in the fits image 'psf_image' and\n\	then computes\n\\n\		F 	= sum fs[y][x] w[y][x]\t\n\		q0 	= sum fs[y][x] W[0][y][x] / F\t\n\		q[l] 	= sum fs[y][x] W[1+l][y][x] / F\t\n\		P0[m] = sum f[y][x] K[0][1+m][y][x] / F\t\n\		P[l][m] = sum f[y][x] K[1+l][1+m][y][x] / F\t\n\		Z[l][m] = sum f[y][x] ZZ[1+l][1+m][y][x] / F\t\n\		R[m]	= sum f[y][x] R[m][y][x] / F\t\n\		Psh[l][m] = 2 q0 delta[l][m] - Z[l][m] / 2 rf^2 + 2 q[l] q[m] / rf^2\t\n\		Psh[l][m] = ((rf^2 - 2 q0) delta[l][m] + Z[l][m] / 4 rf^2 - q[l] q[m] / rf^2)\t\n\\n\	for l,m = 0,1\n\\n\	If sky background values (from getsky) are present they will\n\	be used (unless you give -i flag).\n\\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
Functions
main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 59 of file getshapes3.c.
#define usage '\n\n\n\NAME\n\	getshapes3 --- calculate ellipticities etc. for catalogue of objects\n\\n\SYNOPSIS\n\	getshapes3 f_image fs_image psf_image rf [options...]\n\		-i 		# ignore the sky background information.\n\\n\DESCRIPTION\n\	\'getshapes3\' is a catalogue filter which calculates polarisation\n\	and polarisability for objects.\n\\n\	It requires that the input catalogue contain at least position\n\	vector 'x[2]', and a (aperture) flux 'flux'.\n\\n\	It uses 'makekernel' to compute the kernels W[i], K[i][j], ZZ[i][j]\n\	from the psf supplied in the fits image 'psf_image' and\n\	then computes\n\\n\		F 	= sum fs[y][x] w[y][x]\t\n\		q0 	= sum fs[y][x] W[0][y][x] / F\t\n\		q[l] 	= sum fs[y][x] W[1+l][y][x] / F\t\n\		P0[m] = sum f[y][x] K[0][1+m][y][x] / F\t\n\		P[l][m] = sum f[y][x] K[1+l][1+m][y][x] / F\t\n\		Z[l][m] = sum f[y][x] ZZ[1+l][1+m][y][x] / F\t\n\		R[m]	= sum f[y][x] R[m][y][x] / F\t\n\		Psh[l][m] = 2 q0 delta[l][m] - Z[l][m] / 2 rf^2 + 2 q[l] q[m] / rf^2\t\n\		Psh[l][m] = ((rf^2 - 2 q0) delta[l][m] + Z[l][m] / 4 rf^2 - q[l] q[m] / rf^2)\t\n\\n\	for l,m = 0,1\n\\n\	If sky background values (from getsky) are present they will\n\	be used (unless you give -i flag).\n\\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 5 of file getshapes3.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 61 of file getshapes3.c.
References addargscomment(), addobjectitem(), object::addrlist, allocitemcontents(), allocobjectcontents(), BINARY_FILE_TYPE, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), error_exit, exit(), F(), f, getheaderitemaddress(), getobjectitemindex(), getshape3(), cathead::headeritembase, inheritcontents(), ix, K, l, m, M1, M2, N1, N2, newitem(), newobject(), NUM_TYPE, read2Dfloatimage(), readcathead(), readobject(), setcatopfiletype(), usage, W, w, writecathead(), writeobject(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.