getsky.c
NAME
getsky.c -
SYNOPSIS
#include <math.h>
#include <limits.h>
#include <stdio.h>
#include '../../utils/error.h'
#include '../../imlib/fits.h'
#include 'getsky.h'
Defines
#define MAX_PIX 100000
#define MIN_PIX 16
#define X_POS 2
#define X_NEG 1
#define Y_POS 3
#define Y_NEG 0
#define MAGIC FLOAT_MAGIC
Functions
int getsky (double *fb0, double *dfb, double r1, double r2, double *x, float **f, int N1, int N2)
void pruneextreme (void)
int getplane (double *fb0, double *dfb)
int fmodecmp (const void *ptr1, const void *ptr2)
Variables
int qlist [4]
double xbar [4]
double ybar [4]
float fmode [4]
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 20 of file getsky.c.
#define MAX_PIX 100000
Definition at line 12 of file getsky.c.
Referenced by getsky().
#define MIN_PIX 16
Definition at line 13 of file getsky.c.
Referenced by getsky().
#define X_NEG 1
Definition at line 16 of file getsky.c.
#define X_POS 2
Definition at line 15 of file getsky.c.
#define Y_NEG 0
Definition at line 18 of file getsky.c.
#define Y_POS 3
Definition at line 17 of file getsky.c.
Function Documentation
int fmodecmp (const void * ptr1, const void * ptr2)
Definition at line 163 of file getsky.c.
References fmode.
Referenced by pruneextreme().
int getplane (double * fb0, double * dfb)
Definition at line 131 of file getsky.c.
References det(), f, fmode, i, qlist, x, xbar, y, and ybar.
Referenced by getsky().
int getsky (double * fb0, double * dfb, double r1, double r2, double * x, float ** f, int N1, int N2)
Definition at line 26 of file getsky.c.
References dx, dy, error_exit, f, ff, fmode, getplane(), ix, liststats(), MAGIC, MAX_PIX, median(), MIN_PIX, N1, N2, pix, pruneextreme(), qlist, r, sigma, x, xbar, and ybar.
Referenced by main().
void pruneextreme (void)
Definition at line 117 of file getsky.c.
References fmode, fmodecmp(), i, median(), and qlist.
Referenced by getsky().
Variable Documentation
float fmode[4] [static]
Definition at line 24 of file getsky.c.
Referenced by fmodecmp(), getplane(), getsky(), and pruneextreme().
int qlist[4] [static]
Definition at line 22 of file getsky.c.
Referenced by getplane(), getsky(), and pruneextreme().
double xbar[4] [static]
Definition at line 23 of file getsky.c.
Referenced by getplane(), and getsky().
double ybar[4] [static]
Definition at line 23 of file getsky.c.
Referenced by getplane(), and getsky().
Author
Generated automatically by Doxygen for imcat from the source code.