getshapes1main.c
NAME
getshapes1main.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../catlib/cat.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/stats_stuff.h'
#include 'getshape1.h'
#include 'zap.h'
Defines
#define usage '\n\n\n\NAME\n\	getshapes1 --- calculate ellipticities etc. for catalogue of objects\n\\n\SYNOPSIS\n\	getshapes1	[options...]\n\		-r rname	# name for window radius ('rg')\n\		-m rmult	# multiplier: r_window = rmult * rname (1.0)\n\		-f fitsfile	# specify fits file explicitly\n\		-i 		# ignore the sky background information.\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\		-R		# always output object\n\\n\DESCRIPTION\n\	\'getshapes1\' calculates second moments of sky brightness\n\	(and related quantities) for objects detected by (h)findpeaks,\n\	though possibly after having been processed by getsky and/or\n\	apphot. It uses a gaussian window of size determined by\n\	flags -r, -m. Use '-r unity' for r_window = rmult.\n\	It adds the following items to the catalogue:\n\		qll		# trace of flux normalised quadrupole moment matrix\n\		q[2]		# q[a] = M[a][l][m] q[l][m]\n\		R[2][2]		# response to psf anisotropy\n\		P[2][2]		# response to (post seeing) shear\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
#define Q_DIM 3
Functions
main (int argc, char *argv[])
Define Documentation
#define Q_DIM 3
Definition at line 49 of file getshapes1main.c.
#define usage '\n\n\n\NAME\n\	getshapes1 --- calculate ellipticities etc. for catalogue of objects\n\\n\SYNOPSIS\n\	getshapes1	[options...]\n\		-r rname	# name for window radius ('rg')\n\		-m rmult	# multiplier: r_window = rmult * rname (1.0)\n\		-f fitsfile	# specify fits file explicitly\n\		-i 		# ignore the sky background information.\n\		-Z r mul	# ignore pixels within mul * r of other objects\n\		-R		# always output object\n\\n\DESCRIPTION\n\	\'getshapes1\' calculates second moments of sky brightness\n\	(and related quantities) for objects detected by (h)findpeaks,\n\	though possibly after having been processed by getsky and/or\n\	apphot. It uses a gaussian window of size determined by\n\	flags -r, -m. Use '-r unity' for r_window = rmult.\n\	It adds the following items to the catalogue:\n\		qll		# trace of flux normalised quadrupole moment matrix\n\		q[2]		# q[a] = M[a][l][m] q[l][m]\n\		R[2][2]		# response to psf anisotropy\n\		P[2][2]		# response to (post seeing) shear\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 5 of file getshapes1main.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 51 of file getshapes1main.c.
References addargscomment(), addobjectitem(), object::addrlist, allocFloatArray(), allocitemcontents(), allocobjectcontents(), allocShortArray(), BINARY_FILE_TYPE, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), error_exit, exit(), f, fits, getheaderitemaddress(), getobjectitemindex(), Getshape(), cathead::headeritembase, inheritcontents(), ix, N1, N2, newitem(), newobject(), NUM_TYPE, Q_DIM, r, read2Dfloatimage(), readcathead(), readobject(), setcatipf(), setcatopf(), setcatopfiletype(), UNZAP_MODE, usage, writecathead(), writeobject(), x, zap(), and ZAP_MODE.
Author
Generated automatically by Doxygen for imcat from the source code.