.TH "getshape2.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getshape2.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgetshape2\fP (double *x, double *fb0, double *dfb, double *F, double *p, double **P, double *R, float **f, int \fBN1\fP, int \fBN2\fP, float **\fBw\fP, float ***W, float ***RR, float ****K, int \fBM1\fP, int \fBM2\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int getshape2 (double * x, double * fb0, double * dfb, double * F, double * p, double ** P, double * R, float ** f, int N1, int N2, float ** w, float *** W, float *** RR, float **** K, int M1, int M2)"
.PP
Definition at line 17 of file getshape2.c.
.PP
References dx, dy, error_exit, f, F(), ix, K, l, m, M1, M2, MAGIC, N1, N2, W, w, and x.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
