getwcsinfo.c
NAME
getwcsinfo.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/error.h'
#include 'wcs.h'
Defines
#define usage '\n\NAME\n\	getwcsinfo --- report on WCS fits header info\n\\n\SYNOPSIS\n\	getwcsinfo\n\\n\DESCRIPTION\n\	getwcsinfo reads a fits header from stdin, runs Doug\n\	Mink's wcsinit() and reports what, if any, world\n\	coordinate sysntem information is present.\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	getwcsinfo --- report on WCS fits header info\n\\n\SYNOPSIS\n\	getwcsinfo\n\\n\DESCRIPTION\n\	getwcsinfo reads a fits header from stdin, runs Doug\n\	Mink's wcsinit() and reports what, if any, world\n\	coordinate sysntem information is present.\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file getwcsinfo.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 31 of file getwcsinfo.c.
References error_exit, exit(), i, nowcs(), usage, wcs, and wcsinit().
Author
Generated automatically by Doxygen for imcat from the source code.