getworldcoords.c
NAME
getworldcoords.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/error.h'
#include 'catlib/cat.h'
#include 'imlib/fits.h'
#include 'wcs.h'
Defines
#define usage '\n\NAME\n\	getworldcoords --- add world coordinates to a catalogue\n\\n\SYNOPSIS\n\	getworldcoords fitsfile\n\\n\DESCRIPTION\n\	getworldcoords reads a catalogue from stdin and computes\n\	from the pixel coordinates x[] the celestial coordinates\n\	RA and DEC according to the transformation model encoded\n\	in 'fitsfile' (which need only be a header).\n\	RA and DEC are expressed in decimal degrees.\n\\n\	Uses Doug Mink's wcs utilities code.\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	getworldcoords --- add world coordinates to a catalogue\n\\n\SYNOPSIS\n\	getworldcoords fitsfile\n\\n\DESCRIPTION\n\	getworldcoords reads a catalogue from stdin and computes\n\	from the pixel coordinates x[] the celestial coordinates\n\	RA and DEC according to the transformation model encoded\n\	in 'fitsfile' (which need only be a header).\n\	RA and DEC are expressed in decimal degrees.\n\\n\	Uses Doug Mink's wcs utilities code.\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file getworldcoords.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 37 of file getworldcoords.c.
References addargscomment(), addcomment(), addobjectitem(), object::addrlist, allocitemcontents(), allocobjectcontents(), COM_LENGTH, COM_LENGTH1, comment, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), error_exit, exit(), getcatipfiletype(), getobjectitemindex(), i, inheritcontents(), l, m, newitem(), newobject(), nowcs(), NUM_TYPE, PC, pix2wcs(), readcathead(), readobject(), setcatopfiletype(), usage, wcs, wcsinit(), writecathead(), writeobject(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.