.TH "getworldcoords.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getworldcoords.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'utils/error.h'\fP
.br
\fC#include 'catlib/cat.h'\fP
.br
\fC#include 'imlib/fits.h'\fP
.br
\fC#include 'wcs.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	getworldcoords --- add world coordinates to \fBa\fP catalogue\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	getworldcoords fitsfile\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	getworldcoords reads \fBa\fP catalogue from stdin and computes\\\fBn\fP\\	from the \fBpixel\fP coordinates x[] the celestial coordinates\\\fBn\fP\\	RA and DEC according to the transformation model encoded\\\fBn\fP\\	in 'fitsfile' (which need only be \fBa\fP header).\\\fBn\fP\\	RA and DEC are expressed in decimal degrees.\\\fBn\fP\\\\\fBn\fP\\	Uses Doug Mink's \fBwcs\fP utilities code.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser	kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	getworldcoords --- add world coordinates to \fBa\fP catalogue\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	getworldcoords fitsfile\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	getworldcoords reads \fBa\fP catalogue from stdin and computes\\\fBn\fP\\	from the \fBpixel\fP coordinates x[] the celestial coordinates\\\fBn\fP\\	RA and DEC according to the transformation model encoded\\\fBn\fP\\	in 'fitsfile' (which need only be \fBa\fP header).\\\fBn\fP\\	RA and DEC are expressed in decimal degrees.\\\fBn\fP\\\\\fBn\fP\\	Uses Doug Mink's \fBwcs\fP utilities code.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser	kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 5 of file getworldcoords.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 37 of file getworldcoords.c.
.PP
References addargscomment(), addcomment(), addobjectitem(), object::addrlist, allocitemcontents(), allocobjectcontents(), COM_LENGTH, COM_LENGTH1, comment, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), error_exit, exit(), getcatipfiletype(), getobjectitemindex(), i, inheritcontents(), l, m, newitem(), newobject(), nowcs(), NUM_TYPE, PC, pix2wcs(), readcathead(), readobject(), setcatopfiletype(), usage, wcs, wcsinit(), writecathead(), writeobject(), and x.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
