.TH "getwcsinfo.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getwcsinfo.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'utils/error.h'\fP
.br
\fC#include 'wcs.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	getwcsinfo --- report on WCS \fBfits\fP header info\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	getwcsinfo\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	getwcsinfo reads \fBa\fP \fBfits\fP header from stdin, runs Doug\\\fBn\fP\\	Mink's wcsinit() and reports what, if any, world\\\fBn\fP\\	coordinate sysntem information is present.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser	kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	getwcsinfo --- report on WCS \fBfits\fP header info\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	getwcsinfo\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	getwcsinfo reads \fBa\fP \fBfits\fP header from stdin, runs Doug\\\fBn\fP\\	Mink's wcsinit() and reports what, if any, world\\\fBn\fP\\	coordinate sysntem information is present.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser	kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 5 of file getwcsinfo.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 31 of file getwcsinfo.c.
.PP
References error_exit, exit(), i, nowcs(), usage, wcs, and wcsinit().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
