getxsfromradec.c
NAME
getxsfromradec.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include 'catlib/cat.h'
#include 'utils/error.h'
#include 'utils/args.h'
#include 'getxfromradecfunc.h'
#include 'radecio.h'
Defines
#define usage '\n\NAME\n\	getxsfromradec --- convert from ra, dec to stereographic x-coord\n\\n\SYNOPSIS\n\	getxsfromradec [-i | -u] RA0 DEC0 [THETA]\n\\n\DESCRIPTION\n\	getxsfromradec reads from stdin a catalogue containing celestial\n\	coordinates (and perhaps other stuff) and computes the\n\	stereographic projection xs with tangent point \n\	The orientation is such that xs[0] increases with decreasing\n\	RA, and x[1] increases with DEC.\n\	The resulting vector is expressed in degrees.\n\\n\	Tangent point args may be decimal (in degrees) or colon separated\n\	triplets interpreted as h:m:s for ra and d:m:s for dec.\n\\n\	If the third optional argument THETA is given then the\n\	stereographic coords will be rotated anticlockwise through\n\	THETA degrees. THETA must be given in decimal notation.\n\\n\	With the -i flag we perform the inverse operation.\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	getxsfromradec --- convert from ra, dec to stereographic x-coord\n\\n\SYNOPSIS\n\	getxsfromradec [-i | -u] RA0 DEC0 [THETA]\n\\n\DESCRIPTION\n\	getxsfromradec reads from stdin a catalogue containing celestial\n\	coordinates (and perhaps other stuff) and computes the\n\	stereographic projection xs with tangent point \n\	The orientation is such that xs[0] increases with decreasing\n\	RA, and x[1] increases with DEC.\n\	The resulting vector is expressed in degrees.\n\\n\	Tangent point args may be decimal (in degrees) or colon separated\n\	triplets interpreted as h:m:s for ra and d:m:s for dec.\n\\n\	If the third optional argument THETA is given then the\n\	stereographic coords will be rotated anticlockwise through\n\	THETA degrees. THETA must be given in decimal notation.\n\\n\	With the -i flag we perform the inverse operation.\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file getxsfromradec.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 46 of file getxsfromradec.c.
References addargscomment(), addobjectitem(), object::addrlist, allocitemcontents(), allocobjectcontents(), argsinit(), c, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), error_exit, exit(), flag, FLAG_ARG, getargd(), getargs(), getcatipfiletype(), getdec(), getflag(), getobjectitemindex(), getra(), getxcoords(), inheritcontents(), inversegetxcoords(), ix, newitem(), newobject(), nextargtype(), NUM_TYPE, readcathead(), readobject(), rotate(), setcatopfiletype(), usage, writecathead(), writeobject(), x, and xp().
Author
Generated automatically by Doxygen for imcat from the source code.