getxfromradecfunc.c
NAME
getxfromradecfunc.c -
SYNOPSIS
#include <math.h>
#include <stdio.h>
#include 'getxfromradecfunc.h'
Functions
int getxcoords (double ra, double dec, double rao, double deco, double *x)
int inversegetxcoords (double *ra, double *dec, double rao, double deco, double *x)
Function Documentation
int getxcoords (double ra, double dec, double rao, double deco, double * x)
Definition at line 15 of file getxfromradecfunc.c.
References i, phi, ra, x, xo, and xp().
Referenced by getobjects(), and main().
int inversegetxcoords (double * ra, double * dec, double rao, double deco, double * x)
Definition at line 79 of file getxfromradecfunc.c.
References i, phi, ra, x, xo, xp(), and xx.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.