grad.c
NAME
grad.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\NAME\n\	grad --- take the gradient of a fits image\n\\n\SYNOPSIS\n\	grad [-p]\n\\n\DESCRIPTION\n\	'grad' reads a N1 by N2 2-D fits file f[][] from stdin and calculates discrete\n\	second derivatives. The output is sent to stdout in the form of a \n\	N1 by N2 by 2 image where the zeroth plane is\n\		df[0][y][x] = f[y][x+1] - f[y][x]\n\	and the second plane is\n\		df[1][y][x] = f[y+1][x] - f[y][x]\n\	By default the rightmost column of the first half and the last\n\	row are zero. Use -p option to use periodic bc's.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n'
#define MAGIC FLOAT_MAGIC
Functions
main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 32 of file grad.c.
#define usage '\n\NAME\n\	grad --- take the gradient of a fits image\n\\n\SYNOPSIS\n\	grad [-p]\n\\n\DESCRIPTION\n\	'grad' reads a N1 by N2 2-D fits file f[][] from stdin and calculates discrete\n\	second derivatives. The output is sent to stdout in the form of a \n\	N1 by N2 by 2 image where the zeroth plane is\n\		df[0][y][x] = f[y][x+1] - f[y][x]\n\	and the second plane is\n\		df[1][y][x] = f[y+1][x] - f[y][x]\n\	By default the rightmost column of the first half and the last\n\	row are zero. Use -p option to use periodic bc's.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file grad.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 34 of file grad.c.
References add_comment(), allocFloatArray(), exit(), f, fits, i, j, MAGIC, fitsheader::n, N1, N2, fitsheader::ndim, read2Dfloatimage(), usage, writefitsheader(), writefitsline(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.