grid.h
NAME
grid.h -
SYNOPSIS
Defines
#define MAX_NEIGHBOURS 100000
Functions
void setgridsize (double *xmin, double *xmax, double d)
void allocgrid (object ****gridptr)
int getgridcoords (double *x, int *ix, int *iy)
void getneighbours (double *x, object ***grid, int *nneighbours, object **neighbourobj)
void getobjects (object ***grid, int *nobjs, object **theobjlist)
Define Documentation
#define MAX_NEIGHBOURS 100000
Definition at line 12 of file grid.h.
Referenced by getneighbours(), and main().
Function Documentation
void allocgrid (object **** gridptr)
Definition at line 34 of file grid.c.
References ix, and ng.
Referenced by main().
int getgridcoords (double * x, int * ix, int * iy)
Definition at line 44 of file grid.c.
References dx, ix, ng, x, and x0.
Referenced by getneighbours(), and main().
void getneighbours (double * x, object *** grid, int * nneighbours, object ** neighbourobj)
Definition at line 55 of file grid.c.
References error_exit, getgridcoords(), ix, MAX_NEIGHBOURS, n, ng, and x.
Referenced by main().
void getobjects (object *** grid, int * nobjs, object ** theobjlist)
Definition at line 81 of file grid.c.
References ix, n, object::next, and ng.
void setgridsize (double * xmin, double * xmax, double d)
Definition at line 17 of file grid.c.
References d, dx, j, ng, NG_MAX, x0, xmax, and xmin.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.