gridavg.c
NAME
gridavg.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../utils/error.h'
#include '../utils/fmedian.h'
#include '../catlib/cat.h'
Data Structures
struct numobj
Defines
#define usage '\n\n\NAME\n\	gridavg - average objects binned onto a spatial grid\n\\n\SYNOPSIS\n\	gridavg d [options....]\n\		-x xname	# name for spatial coord ('x')\n\		-r x1 x2 y1 y2	# range of spatial coords\n\		-m		# take median\n\\n\DESCRIPTION\n\	'gridavg' first reads a catalogue of objects from stdin\n\	and then assigns them to cells in a grid with spacing d.\n\	We then average the object values for each grid cell and\n\	output the resulting catalogue to stdout. The output catalogue\n\	contains a leading column 'ncell' containing the count\n\	of objects on the cell and following columns contain average\n\	values for the numeric items in the input catalogue.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
#define MAX_NUMBERS 10000
Typedefs
typedef numobj numobj
Functions
void getaddresses (item *theitem, void *addr, int level)
void average (int count, numobj *baseobj)
main (int argc, char *argv[])
Variables
int nnum
int domedian
double * gaddr [MAX_NUMBERS]
double * fout
float ** fmed
Define Documentation
#define MAX_NUMBERS 10000
Definition at line 42 of file gridavg.c.
#define usage '\n\n\NAME\n\	gridavg - average objects binned onto a spatial grid\n\\n\SYNOPSIS\n\	gridavg d [options....]\n\		-x xname	# name for spatial coord ('x')\n\		-r x1 x2 y1 y2	# range of spatial coords\n\		-m		# take median\n\\n\DESCRIPTION\n\	'gridavg' first reads a catalogue of objects from stdin\n\	and then assigns them to cells in a grid with spacing d.\n\	We then average the object values for each grid cell and\n\	output the resulting catalogue to stdout. The output catalogue\n\	contains a leading column 'ncell' containing the count\n\	of objects on the cell and following columns contain average\n\	values for the numeric items in the input catalogue.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file gridavg.c.
Typedef Documentation
typedef struct numobj numobj
Function Documentation
void average (int count, numobj * baseobj)
Definition at line 232 of file gridavg.c.
References domedian, numobj::f, fmed, fmedian(), fout, free(), numobj::next, and nnum.
Referenced by main().
void getaddresses (item * theitem, void * addr, int level)
Definition at line 216 of file gridavg.c.
References item::dim, gaddr, i, item::ndim, and nnum.
Referenced by getaddresses(), and main().
main (int argc, char * argv[])
Definition at line 52 of file gridavg.c.
References addargscomment(), addobjectitem(), item::addr, allocitemcontents(), average(), BINARY_FILE_TYPE, connectobjecttocathead(), copyheaderinfo(), copyitem(), d, item::dim, domedian, error_exit, exit(), numobj::f, fmed, fout, gaddr, getaddresses(), item::itype, ix, MAX_NUMBERS, item::name, item::ndim, newitem(), newobject(), numobj::next, item::next, nnum, NUM_TYPE, nx, ny, cathead::objectitembase, readcathead(), readobject(), setcatopfiletype(), usage, writecathead(), x, and y.
Variable Documentation
int domedian [static]
Definition at line 44 of file gridavg.c.
Referenced by average(), and main().
float** fmed [static]
Definition at line 46 of file gridavg.c.
Referenced by average(), and main().
double * fout [static]
Definition at line 45 of file gridavg.c.
Referenced by average(), and main().
double* gaddr[MAX_NUMBERS] [static]
Definition at line 45 of file gridavg.c.
Referenced by getaddresses(), and main().
int nnum [static]
Definition at line 44 of file gridavg.c.
Referenced by average(), getaddresses(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.