grid.c
NAME
grid.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../catlib/cat.h'
#include '../../utils/error.h'
#include 'grid.h'
Defines
#define NG_MAX 100
Functions
void setgridsize (double *xmin, double *xmax, double d)
void allocgrid (object ****gridptr)
int getgridcoords (double *x, int *ix, int *iy)
void getneighbours (double *x, object ***grid, int *nneighbours, object **neighbourobj)
void getobjects (object ***grid, int *nobjs, object **theobjlist)
Variables
int ng [2]
double dx [2]
double x0 [2]
Define Documentation
#define NG_MAX 100
Definition at line 14 of file grid.c.
Referenced by setgridsize().
Function Documentation
void allocgrid (object **** gridptr)
Definition at line 34 of file grid.c.
References ix, and ng.
Referenced by main().
int getgridcoords (double * x, int * ix, int * iy)
Definition at line 44 of file grid.c.
References dx, ix, ng, x, and x0.
Referenced by getneighbours(), and main().
void getneighbours (double * x, object *** grid, int * nneighbours, object ** neighbourobj)
Definition at line 55 of file grid.c.
References error_exit, getgridcoords(), ix, MAX_NEIGHBOURS, n, ng, and x.
Referenced by main().
void getobjects (object *** grid, int * nobjs, object ** theobjlist)
Definition at line 81 of file grid.c.
void setgridsize (double * xmin, double * xmax, double d)
Definition at line 17 of file grid.c.
References d, dx, j, ng, NG_MAX, x0, xmax, and xmin.
Referenced by main().
Variable Documentation
double dx[2] [static]
Definition at line 12 of file grid.c.
Referenced by getgridcoords(), and setgridsize().
int ng[2] [static]
Definition at line 11 of file grid.c.
Referenced by allocgrid(), getgridcoords(), getneighbours(), getobjects(), and setgridsize().
double x0[2] [static]
Definition at line 12 of file grid.c.
Referenced by getgridcoords(), and setgridsize().
Author
Generated automatically by Doxygen for imcat from the source code.