growmagic.c
NAME
growmagic.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	growmagic --- expand MAGIC regions of an image\n\SYNOPSIS\n\	growmagic [-n n]\n\\n\DESCRIPTION\n\	\'growmagic\' reads a source image from stdin. It makes\n\	a copy and then sets to MAGIC any pixel for which any\n\	of its eight neighbours have the MAGIC value.\n\\n\	With '-n n' option it performs this operation n times.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define max(a, b) ((a)<(b)?(b):(a))
#define min(a, b) ((a)<(b)?(a):(b))
#define MAGIC FLOAT_MAGIC
Functions
int main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 32 of file growmagic.c.
#define max(a, b) ((a)<(b)?(b):(a))
Definition at line 29 of file growmagic.c.
#define min(a, b) ((a)<(b)?(a):(b))
Definition at line 30 of file growmagic.c.
#define usage '\n\n\n\NAME\n\	growmagic --- expand MAGIC regions of an image\n\SYNOPSIS\n\	growmagic [-n n]\n\\n\DESCRIPTION\n\	\'growmagic\' reads a source image from stdin. It makes\n\	a copy and then sets to MAGIC any pixel for which any\n\	of its eight neighbours have the MAGIC value.\n\\n\	With '-n n' option it performs this operation n times.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file growmagic.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 34 of file growmagic.c.
References add_comment(), allocFloatArray(), argsinit(), error_exit, exit(), fits, flag, getargi(), getflag(), ix, MAGIC, max, min, N1, N2, read2Dfloatimage(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.