hcat2cat.c
NAME
hcat2cat.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../utils/error.h'
#include '../../utils/stats_stuff.h'
#include '../../catlib/cat.h'
#include 'hfindpeaks.h'
Data Structures
struct oldobject
Defines
#define usage '\n\n\n\NAME\n\	hcat2cat - process hfindpeaks output\n\\n\SYNOPSIS\n\	hcat2cat [options...] < hcatfile > catfile\n\		-a		# fire on all local maxima\n\DESCRIPTION\n\	\'hcat2cat\' reads a set of peak trajectories in \'hcat\'\n\	format from stdin and applies an algorithm to pick out\n\	particular points (e.g. points of max significance).\n\	Default is to pick only the most significant local maxima\n\	along a peak trajectory, but -a option finds all local maxima.\n\	Standard format catalogue goes to stdout\n\	THIS IS NOW CALLED AUTOMATICALLY BY hfindpeaks\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define BESTPEAK 0
#define ALLPEAKS 1
#define RFACTOR 0.66
#define FFACTOR 15.41
#define EFACTOR 1.50
Typedefs
typedef oldobject oldobject
Functions
void process (peak *thepeak, int peakcount, int mode)
float interp (float d, float x1, float x2, float x3)
void write_object (oldobject *objectptr)
main (int argc, char *argv[])
Variables
object * theobject
double X [2]
double LG
double RG
double EG [2]
double FS
double NU
Define Documentation
#define ALLPEAKS 1
Definition at line 44 of file hcat2cat.c.
Referenced by main(), and process().
#define BESTPEAK 0
Definition at line 43 of file hcat2cat.c.
Referenced by main(), and process().
#define EFACTOR 1.50
Definition at line 53 of file hcat2cat.c.
Referenced by output(), and process().
#define FFACTOR 15.41
Definition at line 52 of file hcat2cat.c.
Referenced by output(), and process().
#define RFACTOR 0.66
Definition at line 51 of file hcat2cat.c.
Referenced by main(), output(), and process().
#define usage '\n\n\n\NAME\n\	hcat2cat - process hfindpeaks output\n\\n\SYNOPSIS\n\	hcat2cat [options...] < hcatfile > catfile\n\		-a		# fire on all local maxima\n\DESCRIPTION\n\	\'hcat2cat\' reads a set of peak trajectories in \'hcat\'\n\	format from stdin and applies an algorithm to pick out\n\	particular points (e.g. points of max significance).\n\	Default is to pick only the most significant local maxima\n\	along a peak trajectory, but -a option finds all local maxima.\n\	Standard format catalogue goes to stdout\n\	THIS IS NOW CALLED AUTOMATICALLY BY hfindpeaks\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file hcat2cat.c.
Typedef Documentation
typedef struct oldobject oldobject
Function Documentation
float interp (float d, float x1, float x2, float x3)
Definition at line 177 of file hcat2cat.c.
References d.
main (int argc, char * argv[])
Definition at line 58 of file hcat2cat.c.
References addargscomment(), ALLPEAKS, BESTPEAK, BINARY_FILE_TYPE, connectcatheadtoobject(), EG, error_exit, exit(), FS, getobjectitemindex(), LG, newobject(), peak::next, NU, peak, process(), readcathead(), RG, setaddress(), setcatopfiletype(), theline, theobject, usage, writecathead(), and X.
void process (peak * thepeak, int peakcount, int mode)
Definition at line 115 of file hcat2cat.c.
References ALLPEAKS, BESTPEAK, d, oldobject::e, EFACTOR, FFACTOR, free(), oldobject::fs, oldobject::i, i, interp(), oldobject::j, oldobject::l, oldobject::lg, peak::next, oldobject::nu, RFACTOR, oldobject::rg, oldobject::rh, write_object(), and oldobject::x.
Referenced by main().
void write_object (oldobject * objectptr)
Definition at line 187 of file hcat2cat.c.
References oldobject::e, EG, oldobject::fs, FS, oldobject::lg, LG, oldobject::nu, NU, oldobject::rg, RG, theobject, writeobject(), oldobject::x, and X.
Referenced by main(), and process().
Variable Documentation
double EG[2] [static]
Definition at line 56 of file hcat2cat.c.
Referenced by main(), and write_object().
double FS [static]
Definition at line 56 of file hcat2cat.c.
Referenced by main(), and write_object().
double LG [static]
Definition at line 56 of file hcat2cat.c.
Referenced by main(), and write_object().
double NU [static]
Definition at line 56 of file hcat2cat.c.
Referenced by main(), and write_object().
double RG [static]
Definition at line 56 of file hcat2cat.c.
Referenced by main(), and write_object().
object* theobject [static]
Definition at line 55 of file hcat2cat.c.
Referenced by main(), and write_object().
double X[2] [static]
Definition at line 56 of file hcat2cat.c.
Author
Generated automatically by Doxygen for imcat from the source code.