helicalscan.c
NAME
helicalscan.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'utils/error.h'
#include 'utils/args.h'
#include 'utils/ipbuff.h'
#include 'imlib/fits.h'
Defines
#define usage '\n\n\n\NAME\n\	helicalscan --- generate a helical scan of a 2D FITS image\n\SYNOPSIS\n\	helicalscan M d phi [-N nframes] [-o xo yo]\n\\n\DESCRIPTION\n\	'helicalscan' reads a 2 dimensional FITS image fin[y][x] from stdin and\n\	writes to stdout a 3 dimensional FITS image fout[i][y][x] consisting\n\	of a set of M x M subimages with origin placed at a sequence of\n\	positions on the input image:\n\\n\		x0 = (xo + i * d * cos(phi)) % N\n\		y0 = (yo + i * d * sin(phi)) % N\n\\n\	The angle phi at which the subimage moves across the source image\n\	is given in degrees.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define MIN(a, b) ((a)<(b)?(a):(b))
Functions
int main (int argc, char *argv[])
Define Documentation
#define MIN(a, b) ((a)<(b)?(a):(b))
Definition at line 35 of file helicalscan.c.
#define usage '\n\n\n\NAME\n\	helicalscan --- generate a helical scan of a 2D FITS image\n\SYNOPSIS\n\	helicalscan M d phi [-N nframes] [-o xo yo]\n\\n\DESCRIPTION\n\	'helicalscan' reads a 2 dimensional FITS image fin[y][x] from stdin and\n\	writes to stdout a 3 dimensional FITS image fout[i][y][x] consisting\n\	of a set of M x M subimages with origin placed at a sequence of\n\	positions on the input image:\n\\n\		x0 = (xo + i * d * cos(phi)) % N\n\		y0 = (yo + i * d * sin(phi)) % N\n\\n\	The angle phi at which the subimage moves across the source image\n\	is given in degrees.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file helicalscan.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 37 of file helicalscan.c.
References add_comment(), allocFloatArray(), argsinit(), d, dx, dy, error_exit, exit(), fits, flag, FLAG_ARG, getargd(), getargi(), getflag(), i, M, MIN, fitsheader::n, N1, N2, fitsheader::ndim, nextargtype(), nframes, phi, read2Dfloatimage(), usage, writefitsheader(), writefitsplane(), x, xmin, xo, y, ymin, and yo.
Author
Generated automatically by Doxygen for imcat from the source code.