hfindpeaks.c
NAME
hfindpeaks.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <math.h>
#include '../../fftlib/myfft.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/args.h'
#include '../../imlib/filters.h'
#include '../../utils/arrays.h'
#include '../../utils/stats_stuff.h'
#include 'hfindpeaks.h'
Defines
#define usage '\n\n\n\NAME\n\	hfindpeaks --- hierarchical object finder\n\\n\SYNOPSIS\n\	hfindpeaks fitsfile [option...] > catalogue \n\ 		-r rf1 rf2	# range of filter radii (0.5 20.0)\n\		-d dlnrf	# step in log(rf) (0.2)\n\		-l flink	# linking parameter(1.0)\n\		-n nu		# significance threshold (4.0)\n\		-s sigma mode	# sky statistics\n\		-a noiseacf	# supply noise autocorrelation function\n\		-N N1 N2	# set working image size\n\\n\DESCRIPTION\n\	\'hfindpeaks\' --- a heirarchical object finder\n\	fft gaussian filters an image with sequence of progressively\n\	larger smoothing radius mexican hat filters and computes\n\	the significance nu(x; rf) (defined to be the smoothed field at x divided\n\	by the rms noise fluctuation for smoothing radius rf).\n\	It then finds peaks of the nu field links these together to\n\	construct peak trajectories x_pk(rf). We define an object to be the\n\	point of highest significance along such a trajectory.\n\	rf1, rf2 are min and max filter radii and we filter\n\	with logarithmic steps in rf defined by dlnrf\n\	Peaks at adjacent smoothing levels are connected if their\n\	separation is less than flink * rf.\n\	Use -s option to supply sky mode, sigma rather than have\n\	them calculated from the image.\n\	The catalogue is in 'lc' format.\n\	The position 'x' is measured relative to the bottom left\n\	corner of the bottom left pixel (so e.g. a single 'hot' pixel\n\	at (ix,iy) = (23,67), would generate an object with x = (23.5, 67.5)\n\	The rms noise at smoothing scale rf is computed assuming that the\n\	noise is incoherent. If the noise is correlated (from resampling\n\	say) you can supply a noise psf with the -p option.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define TINY 1.e-20
#define ZMAX 10
#define RFACTOR 0.66
#define FFACTOR 15.41
#define EFACTOR 1.50
#define BUFFSIZE 8
Functions
main (int argc, char *argv[])
peak * getpeaks (int N1, int N2, float **fs, int level, float rf, float sigma)
int install (peak *thepeak, line *linehead, float dmax)
void addnewline (line **lineheadptr, peak *thepeak)
int neighbours (peak *peak1, peak *peak2, float dmax)
void removedead (line **lineheadptr, int level, float nulimit)
void disposeof (line *theline, float nulimit)
line *** makecell (line *linehead, float dmax, int ncells)
void freecell (line ***cell, int ncells)
void getcoords (peak *thepeak, int *icell, int *jcell, float dmax)
float thefilterfunction (float ki, float kj)
float interp (float d, float x1, float x2, float x3)
void output (peak *bestpk, peak *prevpk, peak *nextpk)
Variables
float sigma1
float sigma2
int nlines = 0 npeaks = 0
Define Documentation
#define BUFFSIZE 8
Definition at line 581 of file hfindpeaks.c.
#define EFACTOR 1.50
Definition at line 580 of file hfindpeaks.c.
#define FFACTOR 15.41
Definition at line 579 of file hfindpeaks.c.
#define RFACTOR 0.66
Definition at line 578 of file hfindpeaks.c.
#define TINY 1.e-20
Definition at line 81 of file hfindpeaks.c.
#define usage '\n\n\n\NAME\n\	hfindpeaks --- hierarchical object finder\n\\n\SYNOPSIS\n\	hfindpeaks fitsfile [option...] > catalogue \n\ 		-r rf1 rf2	# range of filter radii (0.5 20.0)\n\		-d dlnrf	# step in log(rf) (0.2)\n\		-l flink	# linking parameter(1.0)\n\		-n nu		# significance threshold (4.0)\n\		-s sigma mode	# sky statistics\n\		-a noiseacf	# supply noise autocorrelation function\n\		-N N1 N2	# set working image size\n\\n\DESCRIPTION\n\	\'hfindpeaks\' --- a heirarchical object finder\n\	fft gaussian filters an image with sequence of progressively\n\	larger smoothing radius mexican hat filters and computes\n\	the significance nu(x; rf) (defined to be the smoothed field at x divided\n\	by the rms noise fluctuation for smoothing radius rf).\n\	It then finds peaks of the nu field links these together to\n\	construct peak trajectories x_pk(rf). We define an object to be the\n\	point of highest significance along such a trajectory.\n\	rf1, rf2 are min and max filter radii and we filter\n\	with logarithmic steps in rf defined by dlnrf\n\	Peaks at adjacent smoothing levels are connected if their\n\	separation is less than flink * rf.\n\	Use -s option to supply sky mode, sigma rather than have\n\	them calculated from the image.\n\	The catalogue is in 'lc' format.\n\	The position 'x' is measured relative to the bottom left\n\	corner of the bottom left pixel (so e.g. a single 'hot' pixel\n\	at (ix,iy) = (23,67), would generate an object with x = (23.5, 67.5)\n\	The rms noise at smoothing scale rf is computed assuming that the\n\	noise is incoherent. If the noise is correlated (from resampling\n\	say) you can supply a noise psf with the -p option.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 20 of file hfindpeaks.c.
#define ZMAX 10
Definition at line 545 of file hfindpeaks.c.
Function Documentation
void addnewline (line ** lineheadptr, peak * thepeak)
Definition at line 410 of file hfindpeaks.c.
References line::head, peak::next, line::next, nlines, and line::tail.
Referenced by main().
void disposeof (line * theline, float nulimit)
Definition at line 461 of file hfindpeaks.c.
References free(), peak::next, nlines, peak::nu, output(), and theline.
Referenced by main(), and removedead().
void freecell (line *** cell, int ncells)
Definition at line 528 of file hfindpeaks.c.
References free().
Referenced by main().
void getcoords (peak * thepeak, int * icell, int * jcell, float dmax)
Definition at line 538 of file hfindpeaks.c.
References dmax, peak::i, and peak::j.
Referenced by main(), and makecell().
peak* getpeaks (int N1, int N2, float ** fs, int level, float rf, float sigma)
Definition at line 318 of file hfindpeaks.c.
References peak::e1, peak::e2, f, peak::fs, i, peak::i, j, peak::j, peak::level, N1, N2, peak::next, peak::nu, peak::rf, sigma, TINY, and peak::x.
Referenced by main().
int install (peak * thepeak, line * linehead, float dmax)
Definition at line 388 of file hfindpeaks.c.
float interp (float d, float x1, float x2, float x3)
Definition at line 569 of file hfindpeaks.c.
References d.
main (int argc, char * argv[])
Definition at line 83 of file hfindpeaks.c.
References acf(), addnewline(), alloc_fft(), allocFloatArray(), argsinit(), argsToString(), copy_fft(), disposeof(), dmax, error_exit, exit(), fdo_stats(), fft_type, filter(), fits, flag, FLAG_ARG, FLOAT_MAGIC, fstatsrec::fmode, forward_fft(), freecell(), getargf(), getargi(), getargs(), getcoords(), getflag(), getpeaks(), i, install(), inverse_fft(), j, M1, M2, makecell(), fitsheader::n, N1, N2, peak::next, nextargtype(), NO_ARG, readfitsheader(), readfitsline(), readfitsplane(), removedead(), fstatsrec::sigma, sigma, sigma1, sigma2, substitute(), thefilterfunction(), theline, and usage.
line*** makecell (line * linehead, float dmax, int ncells)
Definition at line 504 of file hfindpeaks.c.
References dmax, exit(), getcoords(), and theline.
Referenced by main().
int neighbours (peak * peak1, peak * peak2, float dmax)
Definition at line 426 of file hfindpeaks.c.
References di, dj, dmax, peak::i, and peak::j.
Referenced by install().
void output (peak * bestpk, peak * prevpk, peak * nextpk)
Definition at line 583 of file hfindpeaks.c.
References BUFFSIZE, d, peak::e1, peak::e2, EFACTOR, FFACTOR, peak::fs, interp(), peak::nu, peak::rf, RFACTOR, and peak::x.
Referenced by disposeof(), num1func(), and num2func().
void removedead (line ** lineheadptr, int level, float nulimit)
Definition at line 438 of file hfindpeaks.c.
References disposeof(), line::prev, and theline.
Referenced by main().
float thefilterfunction (float ki, float kj)
Definition at line 550 of file hfindpeaks.c.
References kk, sigma1, sigma2, z1, z2, and ZMAX.
Variable Documentation
int nlines = 0 npeaks = 0 [static]
Definition at line 79 of file hfindpeaks.c.
Referenced by addnewline(), and disposeof().
float sigma1 [static]
Definition at line 77 of file hfindpeaks.c.
Referenced by main(), and thefilterfunction().
float sigma2 [static]
Definition at line 77 of file hfindpeaks.c.
Referenced by main(), and thefilterfunction().
Author
Generated automatically by Doxygen for imcat from the source code.