hfindpeaks.h
NAME
hfindpeaks.h -
SYNOPSIS
Data Structures
struct line
struct peak
Typedefs
typedef peak peak
typedef line line
Functions
peak * getpeaks (int N1, int N2, float **fs, int level, float rf, float sigma)
int install (peak *thepeak, line *linehead, float dmax)
void addnewline (line **lineheadptr, peak *thepeak)
int neighbours (peak *peak1, peak *peak2, float dmax)
void removedead (line **lineheadptr, int level, float nulimit)
void disposeof (line *theline, float nulimit)
line *** makecell (line *linehead, float dmax, int ncells)
void getcoords (peak *thepeak, int *icell, int *jcell, float dmax)
void freecell (line ***cell, int ncells)
float thefilterfunction (float ki, float kj)
float interp (float d, float x1, float x2, float x3)
void output (peak *bestpk, peak *prevpk, peak *nextpk)
Typedef Documentation
typedef struct line line
Referenced by cdl_getIRAFPixels(), eps_colorHeader(), eps_simpleHeader(), getmodeamplitudes_txt(), getvars(), hgetc(), hputc(), hputcom(), ksearch(), main(), read_fits_head(), read_fits_head_ND(), readamplitudes(), readcathead(), readfitsheader(), readtabheader(), sampleImage(), write_fits_head(), write_fits_head_ND(), and writefitsheader().
typedef struct peak peak
Referenced by main().
Function Documentation
void addnewline (line ** lineheadptr, peak * thepeak)
Definition at line 410 of file hfindpeaks.c.
References line::head, line::next, peak::next, nlines, and line::tail.
Referenced by main().
void disposeof (line * theline, float nulimit)
Definition at line 461 of file hfindpeaks.c.
References free(), peak::next, nlines, peak::nu, output(), and theline.
Referenced by main(), and removedead().
void freecell (line *** cell, int ncells)
Definition at line 528 of file hfindpeaks.c.
References free().
Referenced by main().
void getcoords (peak * thepeak, int * icell, int * jcell, float dmax)
Definition at line 538 of file hfindpeaks.c.
References dmax, peak::i, and peak::j.
Referenced by main(), and makecell().
peak* getpeaks (int N1, int N2, float ** fs, int level, float rf, float sigma)
Definition at line 318 of file hfindpeaks.c.
References peak::e1, peak::e2, f, peak::fs, peak::i, i, peak::j, j, peak::level, N1, N2, peak::next, peak::nu, peak::rf, sigma, TINY, and peak::x.
Referenced by main().
int install (peak * thepeak, line * linehead, float dmax)
Definition at line 388 of file hfindpeaks.c.
References dmax, neighbours(), peak::next, and theline.
float interp (float d, float x1, float x2, float x3)
Definition at line 569 of file hfindpeaks.c.
References d.
line*** makecell (line * linehead, float dmax, int ncells)
Definition at line 504 of file hfindpeaks.c.
References dmax, exit(), getcoords(), and theline.
Referenced by main().
int neighbours (peak * peak1, peak * peak2, float dmax)
Definition at line 426 of file hfindpeaks.c.
References di, dj, dmax, peak::i, and peak::j.
Referenced by install().
void output (peak * bestpk, peak * prevpk, peak * nextpk)
Definition at line 583 of file hfindpeaks.c.
References BUFFSIZE, d, peak::e1, peak::e2, EFACTOR, FFACTOR, peak::fs, interp(), peak::nu, peak::rf, RFACTOR, and peak::x.
Referenced by disposeof(), num1func(), and num2func().
void removedead (line ** lineheadptr, int level, float nulimit)
Definition at line 438 of file hfindpeaks.c.
References disposeof(), line::prev, and theline.
Referenced by main().
float thefilterfunction (float ki, float kj)
Definition at line 87 of file fp.c.
References kk, sigma1, sigma2, z1, z2, and ZMAX.
Author
Generated automatically by Doxygen for imcat from the source code.