hget.c
NAME
hget.c -
SYNOPSIS
#include <string.h>
#include <stdio.h>
#include 'fitshead.h'
#include <stdlib.h>
#include <limits.h>
#include <float.h>
Functions
char * hgetc ()
int hlength (char *header, int lhead)
int hgeti4 (char *hstring, char *keyword, int *ival)
int hgeti2 (char *hstring, char *keyword, short *ival)
int hgetr4 (char *hstring, char *keyword, float *rval)
int hgetra (char *hstring, char *keyword, double *dval)
int hgetdec (char *hstring, char *keyword, double *dval)
int hgetr8 (char *hstring, char *keyword, double *dval)
int hgetl (char *hstring, char *keyword, int *ival)
int hgetdate (char *hstring, char *keyword, double *dval)
int hgets (char *hstring, char *keyword, int lstr, char *str)
char * hgetc (char *hstring, char *keyword0)
char * ksearch (char *hstring, char *keyword)
double str2ra (char *in)
double str2dec (char *in)
char * strsrch (char *s1, char *s2)
char * strnsrch (char *s1, char *s2, int ls1)
int isnum (char *string)
Variables
char val [30]
int lhead0 = 0
Function Documentation
char* hgetc (char * hstring, char * keyword0)
Definition at line 420 of file hget.c.
References i, ier, ksearch(), line, and strsrch().
char* hgetc ()
Referenced by hgetdate(), hgetdec(), hgeti2(), hgeti4(), hgetl(), hgetr4(), hgetr8(), hgetra(), and hgets().
int hgetdate (char * hstring, char * keyword, double * dval)
Definition at line 308 of file hget.c.
References hgetc(), and i.
int hgetdec (char * hstring, char * keyword, double * dval)
Definition at line 213 of file hget.c.
References hgetc(), and str2dec().
int hgeti2 (char * hstring, char * keyword, short * ival)
Definition at line 111 of file hget.c.
References hgetc(), and val.
int hgeti4 (char * hstring, char * keyword, int * ival)
Definition at line 69 of file hget.c.
References hgetc(), and val.
int hgetl (char * hstring, char * keyword, int * ival)
Definition at line 273 of file hget.c.
References hgetc(), and val.
int hgetr4 (char * hstring, char * keyword, float * rval)
Definition at line 152 of file hget.c.
References hgetc(), and val.
int hgetr8 (char * hstring, char * keyword, double * dval)
Definition at line 242 of file hget.c.
References hgetc(), and val.
int hgetra (char * hstring, char * keyword, double * dval)
Definition at line 183 of file hget.c.
References hgetc(), and str2ra().
int hgets (char * hstring, char * keyword, int lstr, char * str)
Definition at line 384 of file hget.c.
References hgetc(), and str.
int hlength (char	* header, int lhead)
Definition at line 52 of file hget.c.
References ksearch(), and lhead0.
int isnum (char * string)
Definition at line 804 of file hget.c.
References cstr, and i.
char* ksearch (char * hstring, char * keyword)
Definition at line 565 of file hget.c.
References ier, lhead0, line, and strnsrch().
double str2dec (char	* in)
Definition at line 678 of file hget.c.
References min, sign, and strsrch().
double str2ra (char	* in)
Definition at line 660 of file hget.c.
References ra, str2dec(), and strsrch().
char* strnsrch (char	* s1, char	* s2, int ls1)
Definition at line 744 of file hget.c.
References i.
char* strsrch (char * s1, char * s2)
Definition at line 730 of file hget.c.
References strnsrch().
Variable Documentation
int lhead0 = 0 [static]
Definition at line 50 of file hget.c.
Referenced by hlength(), and ksearch().
char val[30]
Definition at line 48 of file hget.c.
Referenced by cdl_isFITS(), cdl_readHeader(), eps_doColorbar(), eps_writeRGB(), getnumericvalue(), gettextvalue(), hgeti2(), hgeti4(), hgetl(), hgetr4(), hgetr8(), iis_display(), jpl_init_ephemeris(), main(), and setcolorscheme().
Author
Generated automatically by Doxygen for imcat from the source code.