hput.c
NAME
hput.c -
SYNOPSIS
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include 'fitshead.h'
Functions
void hputc ()
void hputi4 (char *hstring, char *keyword, int ival)
void hputi2 (char *hstring, char *keyword, short ival)
void hputr4 (char *hstring, char *keyword, float rval)
void hputr8 (char *hstring, char *keyword, double dval)
void hputnr8 (char *hstring, char *keyword, int ndec, double dval)
void hputra (char *hstring, char *keyword, double ra)
void hputdec (char *hstring, char *keyword, double dec)
void hputl (char *hstring, char *keyword, int lval)
void hputs (char *hstring, char *keyword, char *cval)
void hputc (char *hstring, char *keyword, char *value)
void hputcom (char *hstring, char *keyword, char *comment)
int hdel (char *hstring, char *keyword)
int hchange (char *hstring, char *keyword1, char *keyword2)
void ra2str (char *string, double ra, int ndec)
void dec2str (char *string, double dec, int ndec)
void deg2str (char *string, double deg, int ndec)
Variables
int verbose = 0
Function Documentation
void dec2str (char	* string, double dec, int ndec)
Definition at line 694 of file hput.c.
References a, b, and sign.
void deg2str (char	* string, double deg, int ndec)
Definition at line 813 of file hput.c.
int hchange (char * hstring, char * keyword1, char * keyword2)
Definition at line 534 of file hput.c.
References i, ksearch(), and v.
int hdel (char * hstring, char * keyword)
Definition at line 494 of file hput.c.
References ksearch(), and v.
void hputc (char * hstring, char * keyword, char * value)
Definition at line 272 of file hput.c.
References ksearch(), line, v, and verbose.
void hputc ()
void hputcom (char * hstring, char * keyword, char * comment)
Definition at line 411 of file hput.c.
References comment, ksearch(), line, and verbose.
void hputdec (char * hstring, char * keyword, double dec)
Definition at line 190 of file hput.c.
References dec2str(), and hputs().
void hputi2 (char * hstring, char * keyword, short ival)
Definition at line 72 of file hput.c.
References hputc().
void hputi4 (char * hstring, char * keyword, int ival)
Definition at line 43 of file hput.c.
References hputc().
void hputl (char * hstring, char * keyword, int lval)
Definition at line 213 of file hput.c.
References hputc().
void hputnr8 (char	* hstring, char	* keyword, int ndec, double dval)
Definition at line 139 of file hput.c.
References hputc().
void hputr4 (char * hstring, char * keyword, float rval)
Definition at line 95 of file hput.c.
References hputc().
void hputr8 (char	* hstring, char	* keyword, double dval)
Definition at line 117 of file hput.c.
References hputc().
void hputra (char * hstring, char * keyword, double ra)
Definition at line 168 of file hput.c.
References hputs(), ra, and ra2str().
void hputs (char * hstring, char * keyword, char * cval)
Definition at line 238 of file hput.c.
References hputc().
void ra2str (char	* string, double ra, int ndec)
Definition at line 570 of file hput.c.
References a, b, and ra.
Variable Documentation
int verbose = 0 [static]
Definition at line 36 of file hput.c.
Referenced by hputc(), and hputcom().
Author
Generated automatically by Doxygen for imcat from the source code.