ic.c
NAME
ic.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include 'error.h'
#include 'utils/iostream.h'
#include 'getop.h'
#include 'ic.h'
Defines
#define usage '\n\n\NAME\n\		ic -- image calculator\n\SYNOPSIS\n\		ic [options....] rpnexpr fitsfile... \n\		where options are:\n\			-u 		# print usage\n\			-c N1 N2	# create an image of this size\n\			-p pixtype	# specify output pixtype\n\			-s seed		# seed rand num generator\n\			-m magicsub	# substitute magic value\n\			-h name val	# add header comment 'name = val'\n\			-b BSCALE BZERO	# add scaling header information\n\\n\DESCRIPTION\n\		\'ic\' does arithmetic on one or more images\n\		according to the reverse-polish notation expression 'rpnexpr'.\n\		Images are referred to in rpnexpr as '%%1', '%%2'.... and\n\		must all have the same size. If the fitsfilename is given\n\		as '-' then that file will be read from stdin.\n\		If fitsfilename is given as 'command |' then we read\n\		from a pipe executing that command.\n\\n\		'ic' operates on images a line at a time, and so can be used\n\		on very large images. A reference to an input image such as\n\		'%%1' causes a line of that image to be pushed onto a stack.\n\		Single argument math functions operate on the line at the top\n\		of the stack and multi-argument functions pop lines as\n\		necessary and then push the resultant line.\n\\n\		If any of the input images is flagged as MAGIC (as defined 'fits.h')\n\		then the result will be MAGIC also (though with '-m' option\n\		'ic' will output 'magicsub' in place of the usual SHRT_MIN)\n\\n\		Fits header comments are inherited from the first image - other\n\		comments are discarded. You may add extra comments with the -h\n\		option; see below.\n\\n\		The functions supported include all of the standard C math\n\		library (including bessel functions j0(x), j1(x),\n\		jn(n,x), y0(x), y1(x), yn(n,x))\n\		plus the operators '+', '-', '*', '/', and 'mult' \n\		is provided as a synonym for '*' to avoid potential problems\n\		if you invoke ic from a script. There are the logical\n\		operations '>', '<', '>=', '<=', '!=', '==' and the negation operator\n\		'!'. There is a random number generator 'rand' which generates\n\		a uniform random number on the range 0.0-1.0 and 'grand' which\n\		generates a zero-mean, unit variance normal variate. There are\n\		two functions 'xp', 'yp' to get the horixontal and vertical pixel\n\		positions respectively, and two further functions 'x', 'y' which\n\		return the position in units of the lenght of the side of\n\		the image. There is a constant MAGIC (defined in magic.h - and\n\		currently set to -32768) which is a flag for bad data.\n\		There is a function 'if' (a.k.a. '?') which mimics the C\n\		language '(c ? t : f)' which returns 't' or 'f' respectively\n\		depending on the truth or falseness of the condition 'c'. The\n\		rpn syntax for this expression is 't f c ?' in which '?' pops the\n\		condition 'c' followed by 'f' and then 't' and pushes 't' or 'f'\n\		as appropriate. The condition 'c' will of course most likely be\n\		a compound logical expression. There are functions 'max' and 'min'\n\		which pop two values and pushes the maximum or minimum respectively.\n\\n\		There is also a function 'enter' which duplicates the top value of\n\		the stack, and a function 'swap' which unsurprisingly\n\		swaps the top two values on the stack.\n\\n\		Use -c option (with no input images) to generate an image from\n\		scratch.\n\\n\		Use -p option to specify output pixtpye which can be one of\n\			  8	# 1-byte unsigned char\n\			 16	# 2-byte signed integer\n\			 32	# 4-byte signed int\n\			-32	# 4-byte floating point\n\			-64	# 8-byte floating point \n\		Otherwise the output will have same pixtype as that of the first\n\		input image, or, with -c option, will have pixtype -32.\n\\n\		Use the -b option to apply scaling of pixel values on\n\		output and record the BSCALE, BZERO values in the header.\n\		Otherwise the BSCALE, BZERO values (if any) are inherited\n\		from the (first) input image.\n\		The definition of BSCALE and BZERO is such that the internal\n\		values are computed from disk values as:\n\\n\			f_internal = BZERO + BSCALE * f_disk\n\\n\		Output goes to stdout.\n\\n\		The '-h' option can be used to add new header values or\n\		to modify existing ones. If an existing name is provided\n\		then the existing value will be overwritten with the new value.\n\		Otherwise, or if the name is 'HISTORY' or 'COMMENT', the new header line\n\		will be appended. The -h option can be given repeatedly to\n\		insert a number of comments.\n\\n\EXAMPLES\n\		Subtract b.fits from a.fits:\n\\n\			ic '%%1 %%2 -' a.fits b.fits\n\\n\		Take sqrt of image to be read from stdin; output as float:\n\\n\			ic -p -32 '%%1 sqrt' -\n\\n\		Create a 512 x 512 image with a linear horizontal ramp and\n\		multiply by 10:\n\\n\			ic -c 512 512 'x 10 *'\n\\n\		Replace all pixels in a.fits with value < 10 with MAGIC:\n\\n\			ic '%%1 MAGIC %%1 10 > ?' a.fits\n\\n\		Filter to clip image at fmin = 0.25 fmax = 0.75:\n\\n\			ic '%%1 0.25 max 0.75 min' -\n\\n\AUTHOR\n\		Nick Kaiser - kaiser@hawaii.edu\n\\n\n\n'
#define LOOP for(ix=0;ix<N1;ix++)
#define MAX_OPS 1024
#define STACK_DEPTH 100
#define MAX_NEW_COMMENTS 100
#define MAGIC FLOAT_MAGIC
Functions
double drand48 ()
int main (int argc, char *argv[])
double xp (void)
double yp (void)
double x (void)
double y (void)
double gasdev (void)
Variables
double * st [STACK_DEPTH]
int pos
int nim = 0
int ix
int iy
int N1
int N2
float ** f
Define Documentation
#define LOOP for(ix=0;ix<N1;ix++)
Definition at line 137 of file ic.c.
Referenced by main().
#define MAGIC FLOAT_MAGIC
Definition at line 150 of file ic.c.
#define MAX_NEW_COMMENTS 100
Definition at line 148 of file ic.c.
Referenced by main().
#define MAX_OPS 1024
Definition at line 139 of file ic.c.
#define STACK_DEPTH 100
Definition at line 140 of file ic.c.
#define usage '\n\n\NAME\n\		ic -- image calculator\n\SYNOPSIS\n\		ic [options....] rpnexpr fitsfile... \n\		where options are:\n\			-u 		# print usage\n\			-c N1 N2	# create an image of this size\n\			-p pixtype	# specify output pixtype\n\			-s seed		# seed rand num generator\n\			-m magicsub	# substitute magic value\n\			-h name val	# add header comment 'name = val'\n\			-b BSCALE BZERO	# add scaling header information\n\\n\DESCRIPTION\n\		\'ic\' does arithmetic on one or more images\n\		according to the reverse-polish notation expression 'rpnexpr'.\n\		Images are referred to in rpnexpr as '%%1', '%%2'.... and\n\		must all have the same size. If the fitsfilename is given\n\		as '-' then that file will be read from stdin.\n\		If fitsfilename is given as 'command |' then we read\n\		from a pipe executing that command.\n\\n\		'ic' operates on images a line at a time, and so can be used\n\		on very large images. A reference to an input image such as\n\		'%%1' causes a line of that image to be pushed onto a stack.\n\		Single argument math functions operate on the line at the top\n\		of the stack and multi-argument functions pop lines as\n\		necessary and then push the resultant line.\n\\n\		If any of the input images is flagged as MAGIC (as defined 'fits.h')\n\		then the result will be MAGIC also (though with '-m' option\n\		'ic' will output 'magicsub' in place of the usual SHRT_MIN)\n\\n\		Fits header comments are inherited from the first image - other\n\		comments are discarded. You may add extra comments with the -h\n\		option; see below.\n\\n\		The functions supported include all of the standard C math\n\		library (including bessel functions j0(x), j1(x),\n\		jn(n,x), y0(x), y1(x), yn(n,x))\n\		plus the operators '+', '-', '*', '/', and 'mult' \n\		is provided as a synonym for '*' to avoid potential problems\n\		if you invoke ic from a script. There are the logical\n\		operations '>', '<', '>=', '<=', '!=', '==' and the negation operator\n\		'!'. There is a random number generator 'rand' which generates\n\		a uniform random number on the range 0.0-1.0 and 'grand' which\n\		generates a zero-mean, unit variance normal variate. There are\n\		two functions 'xp', 'yp' to get the horixontal and vertical pixel\n\		positions respectively, and two further functions 'x', 'y' which\n\		return the position in units of the lenght of the side of\n\		the image. There is a constant MAGIC (defined in magic.h - and\n\		currently set to -32768) which is a flag for bad data.\n\		There is a function 'if' (a.k.a. '?') which mimics the C\n\		language '(c ? t : f)' which returns 't' or 'f' respectively\n\		depending on the truth or falseness of the condition 'c'. The\n\		rpn syntax for this expression is 't f c ?' in which '?' pops the\n\		condition 'c' followed by 'f' and then 't' and pushes 't' or 'f'\n\		as appropriate. The condition 'c' will of course most likely be\n\		a compound logical expression. There are functions 'max' and 'min'\n\		which pop two values and pushes the maximum or minimum respectively.\n\\n\		There is also a function 'enter' which duplicates the top value of\n\		the stack, and a function 'swap' which unsurprisingly\n\		swaps the top two values on the stack.\n\\n\		Use -c option (with no input images) to generate an image from\n\		scratch.\n\\n\		Use -p option to specify output pixtpye which can be one of\n\			  8	# 1-byte unsigned char\n\			 16	# 2-byte signed integer\n\			 32	# 4-byte signed int\n\			-32	# 4-byte floating point\n\			-64	# 8-byte floating point \n\		Otherwise the output will have same pixtype as that of the first\n\		input image, or, with -c option, will have pixtype -32.\n\\n\		Use the -b option to apply scaling of pixel values on\n\		output and record the BSCALE, BZERO values in the header.\n\		Otherwise the BSCALE, BZERO values (if any) are inherited\n\		from the (first) input image.\n\		The definition of BSCALE and BZERO is such that the internal\n\		values are computed from disk values as:\n\\n\			f_internal = BZERO + BSCALE * f_disk\n\\n\		Output goes to stdout.\n\\n\		The '-h' option can be used to add new header values or\n\		to modify existing ones. If an existing name is provided\n\		then the existing value will be overwritten with the new value.\n\		Otherwise, or if the name is 'HISTORY' or 'COMMENT', the new header line\n\		will be appended. The -h option can be given repeatedly to\n\		insert a number of comments.\n\\n\EXAMPLES\n\		Subtract b.fits from a.fits:\n\\n\			ic '%%1 %%2 -' a.fits b.fits\n\\n\		Take sqrt of image to be read from stdin; output as float:\n\\n\			ic -p -32 '%%1 sqrt' -\n\\n\		Create a 512 x 512 image with a linear horizontal ramp and\n\		multiply by 10:\n\\n\			ic -c 512 512 'x 10 *'\n\\n\		Replace all pixels in a.fits with value < 10 with MAGIC:\n\\n\			ic '%%1 MAGIC %%1 10 > ?' a.fits\n\\n\		Filter to clip image at fmin = 0.25 fmax = 0.75:\n\\n\			ic '%%1 0.25 max 0.75 min' -\n\\n\AUTHOR\n\		Nick Kaiser - kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file ic.c.
Function Documentation
double drand48 ()
double gasdev (void)
Definition at line 607 of file ic.c.
int main (int argc, char * argv[])
Definition at line 154 of file ic.c.
References ACOS, add_comment(), appendcomment(), ASIN, ATAN, ATAN2, BESSJ0, BESSJ1, BESSJN, BESSY0, BESSY1, BESSYN, fitsheader::bscale, fitsheader::bscaling, fitsheader::bzero, CEIL, CONSTANT_TYPE, copyfitsheader(), COS, COSH, op::data, DBL_PIXTYPE, DIVIDE, drand48(), ENTER, EQ, error_exit, exit(), EXP, fitsheader::extpixtype, f, FABS, ff, fits, FLOAT_PIXTYPE, FLOOR, FMOD, gasdev(), GE, getop(), GRAND, GT, IF, IFQ, IM_VALUE_TYPE, INT_PIXTYPE, ix, iy, LE, LOG, LOG10, LOOP, LT, M1, M2, MAGIC, MAX, MAX_NEW_COMMENTS, MAX_OPS, MIN, MINUS, fitsheader::n, N1, N2, fitsheader::ndim, NE, new2Dfitsheader(), newtextcomment(), nim, NOT, NUM0_FUNC_TYPE, NUM1_FUNC_TYPE, NUM2_FUNC_TYPE, openiostream(), op::opno, PLUS, pos, POW, RAND, readfitsheader(), readfitsline(), removenamedcomments(), set_getop_N1(), SHORT_PIXTYPE, SIN, SINH, SQRT, st, STACK_DEPTH, SWAP, TAN, TANH, TIMES0, TIMES1, op::type, UCHAR_PIXTYPE, usage, writefitsheader(), writefitsline(), writefitstail(), x(), X, xp(), XP, y(), Y, yp(), and YP.
double x (void)
Definition at line 597 of file ic.c.
Referenced by main().
double xp (void)
Definition at line 587 of file ic.c.
Referenced by cdl_doCircleMark(), cdl_doEllipseMark(), cdl_doPointMark(), cdl_doPolygonMark(), contourplot(), cycleimage(), eqstrn(), func(), getxcoords(), inversegetxcoords(), main(), makemodel(), num0funcarray(), pix2wcs(), shiftandadd(), and wcs2pix().
double y (void)
Definition at line 602 of file ic.c.
Referenced by main().
double yp (void)
Definition at line 592 of file ic.c.
Referenced by cdl_doCircleMark(), cdl_doEllipseMark(), cdl_doPointMark(), cdl_doPolygonMark(), contourplot(), cycleimage(), eqstrn(), func(), main(), makemodel(), num0funcarray(), pix2wcs(), shiftandadd(), and wcs2pix().
Variable Documentation
float** f
Definition at line 146 of file ic.c.
int ix [static]
Definition at line 145 of file ic.c.
Referenced by main(), x(), and xp().
int iy [static]
Definition at line 145 of file ic.c.
Referenced by main(), y(), and yp().
int N1 [static]
Definition at line 145 of file ic.c.
int N2 [static]
Definition at line 145 of file ic.c.
int nim = 0
Definition at line 144 of file ic.c.
int pos
Definition at line 142 of file ic.c.
Referenced by adddate(), argsToString(), eps_doColorbar(), fk42gal(), fk52gal(), gal2fk4(), gal2fk5(), getangle(), getargd(), getargf(), getargi(), gettextvalue(), getvars(), jpcon(), jpcop(), main(), and nextargtype().
double* st[STACK_DEPTH]
Definition at line 141 of file ic.c.
Referenced by main(), printoption(), and skiplines().
Author
Generated automatically by Doxygen for imcat from the source code.