.TH "ic.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ic.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBxp\fP (void)"
.br
.ti -1c
.RI "double \fByp\fP (void)"
.br
.ti -1c
.RI "double \fBx\fP (void)"
.br
.ti -1c
.RI "double \fBy\fP (void)"
.br
.ti -1c
.RI "double \fBIf\fP (void)"
.br
.ti -1c
.RI "double \fBenter\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double enter (void)"
.PP
Definition at line 271 of file ic1/ic.c.
.SS "double If (void)"
.PP
Definition at line 261 of file ic1/ic.c.
.SS "double x (void)"
.PP
Definition at line 597 of file ic.c.
.SS "double xp (void)"
.PP
Definition at line 587 of file ic.c.
.SS "double y (void)"
.PP
Definition at line 602 of file ic.c.
.SS "double yp (void)"
.PP
Definition at line 592 of file ic.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
