ic_dev.c
NAME
ic_dev.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include 'error.h'
#include '../../imtools/magic.h'
#include '../../utils/arrays.h'
#include 'getop.h'
#include 'ic.h'
Defines
#define usage '\n\n\NAME\n\		ic -- image calculator\n\SYNOPSIS\n\		ic [options....] rpnexpr fitsfile... \n\		where options are:\n\			-u 		# print usage\n\			-c N1 N2	# create an image of this size\n\			-p pixtype	# specify output pixtype\n\			-s seed		# seed rand num generator\n\			-m magicsub	# substitute magic value\n\\n\DESCRIPTION\n\		\'ic\' does simple arithmetic on one or more images\n\		according to the reverse-polish notation expression 'rpnexpr'.\n\		Images are referred to in rpnexpr as '%%1', '%%2'.... and\n\		must all have the same size. If the fitsfilename is given\n\		as '-' then that file will be read from stdin.\n\		If any of the input images is MAGIC (as defined 'magic.h')\n\		then the result will be MAGIC also (though with '-m' option\n\		'ic' will output 'magicsub' in place of the usual SHRT_MIN)\n\		The functions supported include all of the standard C math\n\		library plus the operators '+', '-', '*', '/', and 'mult' \n\		is provided as a synonym for '*' to avoid potential problems\n\		if you invoke ic from a script. There are the logical\n\		operations '>', '<', '>=', '<=', '!=', '==' and the negation operator\n\		'!'. There is a random number generator 'rand' which generates\n\		a uniform random number on the range 0.0-1.0 and 'grand' which\n\		generates a zero-mean, unit variance normal variate. There are\n\		two functions 'xp', 'yp' to get the horixontal and vertical pixel\n\		positions respectively, and two further functions 'x', 'y' which\n\		return the position in units of the lenght of the side of\n\		the image. There is a constant MAGIC (defined in magic.h - and\n\		currently set to -32768) which is a flag for bad data.\n\		There is a function 'if' (a.k.a. '?') which mimics the C\n\		language '(c ? t : f)' which returns 't' or 'f' respectively\n\		depending on the truth or falseness of the condition 'c'. The\n\		rpn syntax for this expression is 't f c ?' in which '?' pops the\n\		condition 'c' followed by 'f' and then 't' and pushes 't' or 'f'\n\		as appropriate. The condition 'c' will of course most likely be\n\		a compound logical expression. There is also a function 'enter'\n\		which duplicates the top value of the stack.\n\		Use -c option (with no input images) to generate an image from\n\		scratch.\n\		Use -p option to specify output pixtpye which can be one of\n\			 16	# signed 2-byte integer\n\			-32	# 4-byte floating point\n\			 32	# 4-byte int\n\		Otherwise the output will have same pixtype as input, or, with\n\		-c option, will have pixtype -32.\n\		Output goes to stdout.\n\\n\EXAMPLES\n\		Subtract b.fits from a.fits:\n\\n\			ic '%%1 %%2 -' a.fits b.fits\n\\n\		Take sqrt of image to be read from stdin; output as float:\n\\n\			ic -f '%%1 sqrt' -\n\\n\		Create a 512 x 512 image with a linear horizontal ramp and\n\		multiply by 10:\n\\n\			ic -c 512 512 'x 10 *'\n\\n\		Replace all pixels in a.fits with value < 10 with MAGIC:\n\\n\			ic '%%1 MAGIC %%1 10 > ?' a.fits\n\\n\\n\n\n'
#define MAX_OPS 1024
#define STACK_DEPTH 100
Functions
double drand48 ()
int main (int argc, char *argv[])
double xp (void)
double yp (void)
double x (void)
double y (void)
double gasdev (void)
Variables
double st [STACK_DEPTH]
int pos = -1
int nim = 0
int ix
int iy
int N1
int N2
float ** f
Define Documentation
#define MAX_OPS 1024
Definition at line 88 of file ic_dev.c.
#define STACK_DEPTH 100
Definition at line 89 of file ic_dev.c.
#define usage '\n\n\NAME\n\		ic -- image calculator\n\SYNOPSIS\n\		ic [options....] rpnexpr fitsfile... \n\		where options are:\n\			-u 		# print usage\n\			-c N1 N2	# create an image of this size\n\			-p pixtype	# specify output pixtype\n\			-s seed		# seed rand num generator\n\			-m magicsub	# substitute magic value\n\\n\DESCRIPTION\n\		\'ic\' does simple arithmetic on one or more images\n\		according to the reverse-polish notation expression 'rpnexpr'.\n\		Images are referred to in rpnexpr as '%%1', '%%2'.... and\n\		must all have the same size. If the fitsfilename is given\n\		as '-' then that file will be read from stdin.\n\		If any of the input images is MAGIC (as defined 'magic.h')\n\		then the result will be MAGIC also (though with '-m' option\n\		'ic' will output 'magicsub' in place of the usual SHRT_MIN)\n\		The functions supported include all of the standard C math\n\		library plus the operators '+', '-', '*', '/', and 'mult' \n\		is provided as a synonym for '*' to avoid potential problems\n\		if you invoke ic from a script. There are the logical\n\		operations '>', '<', '>=', '<=', '!=', '==' and the negation operator\n\		'!'. There is a random number generator 'rand' which generates\n\		a uniform random number on the range 0.0-1.0 and 'grand' which\n\		generates a zero-mean, unit variance normal variate. There are\n\		two functions 'xp', 'yp' to get the horixontal and vertical pixel\n\		positions respectively, and two further functions 'x', 'y' which\n\		return the position in units of the lenght of the side of\n\		the image. There is a constant MAGIC (defined in magic.h - and\n\		currently set to -32768) which is a flag for bad data.\n\		There is a function 'if' (a.k.a. '?') which mimics the C\n\		language '(c ? t : f)' which returns 't' or 'f' respectively\n\		depending on the truth or falseness of the condition 'c'. The\n\		rpn syntax for this expression is 't f c ?' in which '?' pops the\n\		condition 'c' followed by 'f' and then 't' and pushes 't' or 'f'\n\		as appropriate. The condition 'c' will of course most likely be\n\		a compound logical expression. There is also a function 'enter'\n\		which duplicates the top value of the stack.\n\		Use -c option (with no input images) to generate an image from\n\		scratch.\n\		Use -p option to specify output pixtpye which can be one of\n\			 16	# signed 2-byte integer\n\			-32	# 4-byte floating point\n\			 32	# 4-byte int\n\		Otherwise the output will have same pixtype as input, or, with\n\		-c option, will have pixtype -32.\n\		Output goes to stdout.\n\\n\EXAMPLES\n\		Subtract b.fits from a.fits:\n\\n\			ic '%%1 %%2 -' a.fits b.fits\n\\n\		Take sqrt of image to be read from stdin; output as float:\n\\n\			ic -f '%%1 sqrt' -\n\\n\		Create a 512 x 512 image with a linear horizontal ramp and\n\		multiply by 10:\n\\n\			ic -c 512 512 'x 10 *'\n\\n\		Replace all pixels in a.fits with value < 10 with MAGIC:\n\\n\			ic '%%1 MAGIC %%1 10 > ?' a.fits\n\\n\\n\n\n'
Definition at line 1 of file ic_dev.c.
Function Documentation
double drand48 ()
double gasdev (void)
Definition at line 452 of file ic_dev.c.
References drand48(), r, and ran0().
int main (int argc, char * argv[])
Definition at line 99 of file ic_dev.c.
References ACOS, add_comment(), allocFloatArray(), ASIN, ATAN, ATAN2, CEIL, CONSTANT_TYPE, COS, COSH, op::data, DIVIDE, drand48(), ENTER, EQ, error_exit, exit(), EXP, f, FABS, ff, FLOAT_PIXTYPE, FLOOR, FMOD, fread_fits(), fwrite_fits(), gasdev(), GE, get_input_pixtype(), getop(), GRAND, GT, IF, IFQ, IM_VALUE_TYPE, INT_PIXTYPE, ix, iy, LE, LOG, LOG10, LT, M1, M2, MAGIC, MAX_OPS, MINUS, N1, N2, NE, nim, NOT, NUM0_FUNC_TYPE, NUM1_FUNC_TYPE, NUM2_FUNC_TYPE, op::opno, PLUS, pos, POW, RAND, set_fits_ipf(), set_output_pixtype(), SHORT_PIXTYPE, SIN, SINH, SQRT, st, STACK_DEPTH, TAN, TANH, TIMES0, TIMES1, op::type, usage, x(), X, xp(), XP, y(), Y, yp(), and YP.
double x (void)
Definition at line 442 of file ic_dev.c.
References ix, and N1.
double xp (void)
Definition at line 432 of file ic_dev.c.
References ix.
double y (void)
Definition at line 447 of file ic_dev.c.
References iy, and N2.
double yp (void)
Definition at line 437 of file ic_dev.c.
References iy.
Variable Documentation
float** f
Definition at line 95 of file ic_dev.c.
int ix [static]
Definition at line 94 of file ic_dev.c.
int iy [static]
Definition at line 94 of file ic_dev.c.
Referenced by main(), y(), and yp().
int N1 [static]
Definition at line 94 of file ic_dev.c.
int N2 [static]
Definition at line 94 of file ic_dev.c.
int nim = 0
Definition at line 93 of file ic_dev.c.
int pos = -1
Definition at line 91 of file ic_dev.c.
double st[STACK_DEPTH]
Definition at line 90 of file ic_dev.c.
Author
Generated automatically by Doxygen for imcat from the source code.