ic_stream.c
NAME
ic_stream.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	ic_stream --- apply simple arithmetic to a stream of images\n\\n\SYNOPSIS\n\	ic_stream [plus | minus | times | divide] operandfits\n\\n\DESCRIPTION\n\	'ic_stream plus myfits' reads a 2D image myfits and then\n\	reads planes from a higher dimensional image, adds the value\n\	from myfits and outputs the result.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define ADD_MODE 0
#define SUB_MODE 1
#define MUL_MODE 2
#define DIV_MODE 3
Functions
int main (int argc, char *argv[])
Define Documentation
#define ADD_MODE 0
Definition at line 28 of file ic_stream.c.
Referenced by main().
#define DIV_MODE 3
Definition at line 31 of file ic_stream.c.
Referenced by main().
#define MUL_MODE 2
Definition at line 30 of file ic_stream.c.
Referenced by main().
#define SUB_MODE 1
Definition at line 29 of file ic_stream.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	ic_stream --- apply simple arithmetic to a stream of images\n\\n\SYNOPSIS\n\	ic_stream [plus | minus | times | divide] operandfits\n\\n\DESCRIPTION\n\	'ic_stream plus myfits' reads a 2D image myfits and then\n\	reads planes from a higher dimensional image, adds the value\n\	from myfits and outputs the result.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file ic_stream.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 33 of file ic_stream.c.
References add_comment(), ADD_MODE, allocFloatArray(), DIV_MODE, error_exit, f, fits, i, MUL_MODE, fitsheader::n, N1, N2, fitsheader::ndim, readfitsheader(), readfitsplane(), SUB_MODE, usage, writefitsheader(), writefitsplane(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.