.TH "ic_stream.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ic_stream.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include '../imlib/fits.h'\fP
.br
\fC#include '../utils/error.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	ic_stream --- apply simple arithmetic to \fBa\fP stream of images\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	ic_stream [plus | minus | times | divide] operandfits\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'ic_stream plus myfits' reads \fBa\fP 2D image myfits and then\\\fBn\fP\\	reads planes from \fBa\fP higher dimensional image, adds the value\\\fBn\fP\\	from myfits and outputs the result.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.br
.ti -1c
.RI "#define \fBADD_MODE\fP   0"
.br
.ti -1c
.RI "#define \fBSUB_MODE\fP   1"
.br
.ti -1c
.RI "#define \fBMUL_MODE\fP   2"
.br
.ti -1c
.RI "#define \fBDIV_MODE\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ADD_MODE   0"
.PP
Definition at line 28 of file ic_stream.c.
.PP
Referenced by main().
.SS "#define DIV_MODE   3"
.PP
Definition at line 31 of file ic_stream.c.
.PP
Referenced by main().
.SS "#define MUL_MODE   2"
.PP
Definition at line 30 of file ic_stream.c.
.PP
Referenced by main().
.SS "#define SUB_MODE   1"
.PP
Definition at line 29 of file ic_stream.c.
.PP
Referenced by main().
.SS "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	ic_stream --- apply simple arithmetic to \fBa\fP stream of images\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	ic_stream [plus | minus | times | divide] operandfits\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'ic_stream plus myfits' reads \fBa\fP 2D image myfits and then\\\fBn\fP\\	reads planes from \fBa\fP higher dimensional image, adds the value\\\fBn\fP\\	from myfits and outputs the result.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 1 of file ic_stream.c.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 33 of file ic_stream.c.
.PP
References add_comment(), ADD_MODE, allocFloatArray(), DIV_MODE, error_exit, f, fits, i, MUL_MODE, fitsheader::n, N1, N2, fitsheader::ndim, readfitsheader(), readfitsplane(), SUB_MODE, usage, writefitsheader(), writefitsplane(), x, and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
