.TH "icilist" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
icilist \- 
.SH SYNOPSIS
.br
.PP
\fC#include <f2c.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBflag\fP \fBicierr\fP"
.br
.ti -1c
.RI "char * \fBiciunit\fP"
.br
.ti -1c
.RI "\fBflag\fP \fBiciend\fP"
.br
.ti -1c
.RI "char * \fBicifmt\fP"
.br
.ti -1c
.RI "\fBftnint\fP \fBicirlen\fP"
.br
.ti -1c
.RI "\fBftnint\fP \fBicirnum\fP"
.br
.ti -1c
.RI "char * \fBiciunit\fP"
.br
.ti -1c
.RI "char * \fBicifmt\fP"
.br
.ti -1c
.RI "char * \fBiciunit\fP"
.br
.ti -1c
.RI "char * \fBicifmt\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBflag\fP \fBicilist::iciend\fP"
.PP
Definition at line 63 of file myf2c.h.
.SS "\fBflag\fP \fBicilist::icierr\fP"
.PP
Definition at line 61 of file myf2c.h.
.SS "char* \fBicilist::icifmt\fP"
.PP
Definition at line 64 of file myf2c.h.
.SS "char* \fBicilist::icifmt\fP"
.PP
Definition at line 97 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBicilist::icifmt\fP"
.PP
Definition at line 58 of file fftpack_c/f2c.h.
.SS "\fBftnint\fP \fBicilist::icirlen\fP"
.PP
Definition at line 65 of file myf2c.h.
.SS "\fBftnint\fP \fBicilist::icirnum\fP"
.PP
Definition at line 66 of file myf2c.h.
.SS "char* \fBicilist::iciunit\fP"
.PP
Definition at line 62 of file myf2c.h.
.SS "char* \fBicilist::iciunit\fP"
.PP
Definition at line 95 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBicilist::iciunit\fP"
.PP
Definition at line 56 of file fftpack_c/f2c.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
