.TH "iis_hdr" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iis_hdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "short \fBtid\fP"
.br
.ti -1c
.RI "short \fBthingct\fP"
.br
.ti -1c
.RI "short \fBsubunit\fP"
.br
.ti -1c
.RI "short \fBchecksum\fP"
.br
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.ti -1c
.RI "short \fBz\fP"
.br
.ti -1c
.RI "short \fBt\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "short \fBiis_hdr::checksum\fP"
.PP
Definition at line 64 of file comm.c.
.PP
Referenced by com_whdr().
.SS "short \fBiis_hdr::subunit\fP"
.PP
Definition at line 63 of file comm.c.
.PP
Referenced by com_whdr().
.SS "short \fBiis_hdr::t\fP"
.PP
Definition at line 65 of file comm.c.
.PP
Referenced by com_whdr().
.SS "short \fBiis_hdr::thingct\fP"
.PP
Definition at line 62 of file comm.c.
.PP
Referenced by com_whdr().
.SS "short \fBiis_hdr::tid\fP"
.PP
Definition at line 61 of file comm.c.
.PP
Referenced by com_whdr().
.SS "short \fBiis_hdr::x\fP"
.PP
Definition at line 65 of file comm.c.
.PP
Referenced by com_whdr().
.SS "short \fBiis_hdr::y\fP"
.PP
Definition at line 65 of file comm.c.
.PP
Referenced by com_whdr().
.SS "short \fBiis_hdr::z\fP"
.PP
Definition at line 65 of file comm.c.
.PP
Referenced by com_whdr().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
