.TH "iism70" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iism70 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "short \fBtid\fP"
.br
.ti -1c
.RI "short \fBthingct\fP"
.br
.ti -1c
.RI "short \fBsubunit\fP"
.br
.ti -1c
.RI "short \fBchecksum\fP"
.br
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.ti -1c
.RI "short \fBz\fP"
.br
.ti -1c
.RI "short \fBt\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "short \fBiism70::checksum\fP"
.PP
Definition at line 108 of file vximtool.c.
.SS "short \fBiism70::subunit\fP"
.PP
Definition at line 107 of file vximtool.c.
.SS "short \fBiism70::t\fP"
.PP
Definition at line 110 of file vximtool.c.
.SS "short \fBiism70::thingct\fP"
.PP
Definition at line 106 of file vximtool.c.
.SS "short \fBiism70::tid\fP"
.PP
Definition at line 105 of file vximtool.c.
.SS "short \fBiism70::x\fP"
.PP
Definition at line 109 of file vximtool.c.
.SS "short \fBiism70::y\fP"
.PP
Definition at line 109 of file vximtool.c.
.SS "short \fBiism70::z\fP"
.PP
Definition at line 109 of file vximtool.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
