test.c
NAME
test.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <values.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/ipbuff.h'
#include '../../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	makepeff --- compute effective polarisability\n\\n\SYNOPSIS\n\	makepeff [-u]\n\\n\DESCRIPTION\n\	'makepeff' first reads from stdin a catalogue which\n\	must contain at least the following entries:\n\		F	# windowed flux\n\		q0	# size\n\		q[2]	# polarisation\n\		R[2]	# flux response\n\		P0[2]	# size response\n\		P[2][2]	# polarisation response\n\	as created by 'getshapes2'.\n\	It bins appropriate combinations of these in a cubical\n\	array in F, p0, q space and computes P_effective.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Functions
float *** alloc3Darray (int N1, int N2, int N3)
float *** boxavg3D (float ***f, int N1, int N2, int N3)
float *** grad3D (float ***f, int dir, double dx, int N1, int N2, int N3)
main (int argc, char *argv[])
Variables
Warning __pad0__
Warning int dir
Warning int double dx
Warning int double int N1
Warning int double int int N2
Define Documentation
#define usage '\n\n\n\NAME\n\	makepeff --- compute effective polarisability\n\\n\SYNOPSIS\n\	makepeff [-u]\n\\n\DESCRIPTION\n\	'makepeff' first reads from stdin a catalogue which\n\	must contain at least the following entries:\n\		F	# windowed flux\n\		q0	# size\n\		q[2]	# polarisation\n\		R[2]	# flux response\n\		P0[2]	# size response\n\		P[2][2]	# polarisation response\n\	as created by 'getshapes2'.\n\	It bins appropriate combinations of these in a cubical\n\	array in F, p0, q space and computes P_effective.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file imcattools/photometry/test.c.
Function Documentation
float*** alloc3Darray (int N1, int N2, int N3)
Referenced by boxavg3D(), grad3D(), and main().
float*** boxavg3D (float *** f, int N1, int N2, int N3)
Referenced by main().
float*** grad3D (float *** f, int dir, double dx, int N1, int N2, int N3)
Referenced by main().
main (int argc, char * argv[])
Definition at line 42 of file imcattools/photometry/test.c.
References add_comment(), alloc3Darray(), boxavg3D(), buff, error_exit, exit(), fits, FLOAT_PIXTYPE, grad3D(), ipf, MINFLOAT, n, newfitsheader(), usage, writefitscube(), writefitsheader(), and writefitstail().
Variable Documentation
Warning __pad0__
Definition at line 232 of file imcattools/photometry/test.c.
Warning int dir
Definition at line 232 of file imcattools/photometry/test.c.
Referenced by grad3D(), and makebreakpoints().
Warning int double dx
Definition at line 232 of file imcattools/photometry/test.c.
Warning int double int N1
Definition at line 232 of file imcattools/photometry/test.c.
Warning int double int int N2
Definition at line 232 of file imcattools/photometry/test.c.
Author
Generated automatically by Doxygen for imcat from the source code.