.TH "dummy_MAIN.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dummy_MAIN.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMAIN_\fP ()"
.br
.ti -1c
.RI "void \fBMAIN__\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void MAIN_ ()"
.PP
Definition at line 6 of file imcattools/orbits/kepler_heasley/dummy_MAIN.c.
.SS "void MAIN__ ()"
.PP
Definition at line 11 of file imcattools/orbits/kepler_heasley/dummy_MAIN.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
