nrutil.c
NAME
nrutil.c -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
Functions
void nrerror (char *error_text)
float * vector (int nl, int nh)
int * ivector (int nl, int nh)
double * dvector (int nl, int nh)
float ** matrix (int nrl, int nrh, int ncl, int nch)
double ** dmatrix (int nrl, int nrh, int ncl, int nch)
int ** imatrix (int nrl, int nrh, int ncl, int nch)
float ** submatrix (float **a, int oldrl, int oldrh, int oldcl, int oldch, int newrl, int newcl)
void free_vector (float *v, int nl, int nh)
void free_ivector (int *v, int nl, int nh)
void free_dvector (double *v, int nl, int nh)
void free_matrix (float **m, int nrl, int nrh, int ncl, int nch)
void free_dmatrix (double **m, int nrl, int nrh, int ncl, int nch)
void free_imatrix (int **m, int nrl, int nrh, int ncl, int nch)
void free_submatrix (float **b, int nrl, int nrh, int ncl, int nch)
float ** convert_matrix (float *a, int nrl, int nrh, int ncl, int nch)
void free_convert_matrix (float **b, int nrl, int nrh, int ncl, int nch)
Function Documentation
float** convert_matrix (float * a, int nrl, int nrh, int ncl, int nch)
Definition at line 165 of file imcattools/photometry/fitting/nrutil.c.
References a, i, j, m, malloc(), and nrerror().
double** dmatrix (int nrl, int nrh, int ncl, int nch)
Definition at line 63 of file imcattools/photometry/fitting/nrutil.c.
References i, m, malloc(), and nrerror().
double* dvector (int nl, int nh)
Definition at line 35 of file imcattools/photometry/fitting/nrutil.c.
References malloc(), nrerror(), and v.
void free_convert_matrix (float ** b, int nrl, int nrh, int ncl, int nch)
Definition at line 181 of file imcattools/photometry/fitting/nrutil.c.
References b, and free().
void free_dmatrix (double ** m, int nrl, int nrh, int ncl, int nch)
Definition at line 140 of file imcattools/photometry/fitting/nrutil.c.
References free(), i, and m.
void free_dvector (double * v, int nl, int nh)
Definition at line 125 of file imcattools/photometry/fitting/nrutil.c.
References free(), and v.
void free_imatrix (int ** m, int nrl, int nrh, int ncl, int nch)
Definition at line 148 of file imcattools/photometry/fitting/nrutil.c.
References free(), i, and m.
void free_ivector (int * v, int nl, int nh)
Definition at line 120 of file imcattools/photometry/fitting/nrutil.c.
References free(), and v.
void free_matrix (float ** m, int nrl, int nrh, int ncl, int nch)
Definition at line 132 of file imcattools/photometry/fitting/nrutil.c.
References free(), i, and m.
void free_submatrix (float ** b, int nrl, int nrh, int ncl, int nch)
Definition at line 158 of file imcattools/photometry/fitting/nrutil.c.
References b, and free().
void free_vector (float * v, int nl, int nh)
Definition at line 115 of file imcattools/photometry/fitting/nrutil.c.
References free(), and v.
int** imatrix (int nrl, int nrh, int ncl, int nch)
Definition at line 80 of file imcattools/photometry/fitting/nrutil.c.
References i, m, malloc(), and nrerror().
int* ivector (int nl, int nh)
Definition at line 26 of file imcattools/photometry/fitting/nrutil.c.
References malloc(), nrerror(), and v.
float** matrix (int nrl, int nrh, int ncl, int nch)
Definition at line 46 of file imcattools/photometry/fitting/nrutil.c.
References i, m, malloc(), and nrerror().
void nrerror (char * error_text)
Definition at line 5 of file imcattools/photometry/fitting/nrutil.c.
References exit().
float** submatrix (float ** a, int oldrl, int oldrh, int oldcl, int oldch, int newrl, int newcl)
Definition at line 98 of file imcattools/photometry/fitting/nrutil.c.
References a, i, j, m, malloc(), and nrerror().
float* vector (int nl, int nh)
Definition at line 17 of file imcattools/photometry/fitting/nrutil.c.
References malloc(), nrerror(), and v.
Author
Generated automatically by Doxygen for imcat from the source code.