.TH "test.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include 'gaussfit.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   M_PI"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define PI   M_PI"
.PP
function for testing Gaussian ellipsoid fitting Definition at line 14 of file imcattools/photometry/fitting/test.c.
.SH "Function Documentation"
.PP 
.SS "main ()"
.PP
Definition at line 17 of file imcattools/photometry/fitting/test.c.
.PP
References a, b, c, f, gaussfit(), i, j, N, phi, PI, x, and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
