.TH "IMD" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMD \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cdlP.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdatain\fP"
.br
.ti -1c
.RI "int \fBdataout\fP"
.br
.ti -1c
.RI "int \fBdomain\fP"
.br
.ti -1c
.RI "short \fBframe\fP"
.br
.ti -1c
.RI "short \fBfbconfig\fP"
.br
.ti -1c
.RI "\fBFBTab\fP * \fBfbtab\fP [MAX_FBCONFIG]"
.br
.ti -1c
.RI "short \fBxs\fP"
.br
.ti -1c
.RI "short \fBxe\fP"
.br
.ti -1c
.RI "short \fBys\fP"
.br
.ti -1c
.RI "short \fBye\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBtitle\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.ti -1c
.RI "float \fBd\fP"
.br
.ti -1c
.RI "float \fBtx\fP"
.br
.ti -1c
.RI "float \fBty\fP"
.br
.ti -1c
.RI "float \fBz1\fP"
.br
.ti -1c
.RI "float \fBz2\fP"
.br
.ti -1c
.RI "short \fBztrans\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float \fBIMD::a\fP"
.PP
Definition at line 61 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "float \fBIMD::b\fP"
.PP
Definition at line 61 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "float \fBIMD::c\fP"
.PP
Definition at line 61 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "float \fBIMD::d\fP"
.PP
Definition at line 61 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "int \fBIMD::datain\fP"
.PP
Definition at line 50 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "int \fBIMD::dataout\fP"
.PP
Definition at line 50 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "int \fBIMD::domain\fP"
.PP
Definition at line 51 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "short \fBIMD::fbconfig\fP"
.PP
Definition at line 54 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "\fBFBTab\fP* \fBIMD::fbtab\fP[MAX_FBCONFIG]"
.PP
Definition at line 55 of file cdlP.h.
.SS "short \fBIMD::frame\fP"
.PP
Definition at line 53 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "char* \fBIMD::name\fP"
.PP
Definition at line 59 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "char* \fBIMD::title\fP"
.PP
Definition at line 60 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "float \fBIMD::tx\fP"
.PP
Definition at line 62 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "float \fBIMD::ty\fP"
.PP
Definition at line 62 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "short \fBIMD::xe\fP"
.PP
Definition at line 57 of file cdlP.h.
.SS "short \fBIMD::xs\fP"
.PP
Definition at line 57 of file cdlP.h.
.SS "short \fBIMD::ye\fP"
.PP
Definition at line 58 of file cdlP.h.
.SS "short \fBIMD::ys\fP"
.PP
Definition at line 58 of file cdlP.h.
.SS "float \fBIMD::z1\fP"
.PP
Definition at line 63 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "float \fBIMD::z2\fP"
.PP
Definition at line 63 of file cdlP.h.
.PP
Referenced by imd_initialize().
.SS "short \fBIMD::ztrans\fP"
.PP
Definition at line 64 of file cdlP.h.
.PP
Referenced by imd_initialize().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
