imd.c
NAME
imd.c -
SYNOPSIS
#include <sys/stat.h>
#include <sys/file.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/un.h>
#include <netdb.h>
#include <fcntl.h>
#include <stdio.h>
#include 'cdl.h'
Defines
#define CDL_LIBRARY_SOURCE
#define SZ_BLOCK 16384
#define W_UNITARY 0
#define W_LINEAR 1
#define W_LOG 2
#define W_USER 3
#define UNIX 10
#define INET 11
#define FIFO 12
#define DEF_FBCONFIG 1
#define DEF_OSDEV_1 'unix:/tmp/.IMT%d'
#define DEF_OSDEV_2 'fifo:/dev/imt1i:/dev/imt1o'
#define FBCONFIG_1 '.imtoolrc'
#define FBCONFIG_2 '/usr/local/lib/imtoolrc'
#define FBCONFIG_ENV1 'imtoolrc'
#define FBCONFIG_ENV2 'IMTOOLRC'
#define DEF_FRAME_WIDTH 512
#define DEF_FRAME_HEIGHT 512
Functions
IMDPtr imd_initialize ()
int imd_parseImtdev ()
int imd_loadImtoolrc ()
int imd_getstr ()
int imd_writeLine ()
int imd_readLine ()
void imd_minmax ()
IMDPtr imd_open (char *imtdev)
int imd_displayImage (IMDPtr imd, uchar *pix, int nx, int ny, int frame, int fbconfig, int comp_wcs)
int imd_readCursor (IMDPtr imd, int sample, float *x, float *y, char *key)
int imd_setWCS (IMDPtr imd, char *name, char *title, float a, float b, float c, float d, float tx, float ty, float z1, float z2, int zt)
int imd_getWCS (IMDPtr imd, char *name, char *title, float *a, float *b, float *c, float *d, float *tx, float *ty, float *z1, float *z2, int *zt)
int imd_close (IMDPtr imd)
int imd_writeImage (IMDPtr imd, uchar *pix, int nx, int ny, int llx, int lly)
int imd_readImage (IMDPtr imd, uchar *pix, int *nx, int *ny)
int imd_readFrameBuffer (IMDPtr imd, uchar *pix, int *nx, int *ny)
int imd_setFrame (IMDPtr imd, int frame)
int imd_setFBConfig (IMDPtr imd, int configno)
int imd_getFBConfig (IMDPtr imd, int *configno, int *width, int *height, int *nframes)
int imd_setName (IMDPtr imd, char *name)
int imd_setTitle (IMDPtr imd, char *title)
int imd_setCursor (IMDPtr imd, int x, int y, int wcs)
int imd_clearFrame (IMDPtr imd)
int imd_readSubRaster (IMDPtr imd, int llx, int lly, int nx, int ny, uchar *pix)
int imd_writeSubRaster (IMDPtr imd, int llx, int lly, int nx, int ny, uchar *pix)
int imd_setDebug (int state)
int imd_writeLine (IMDPtr imd, uchar *pix, int nbytes, int x, int y)
int imd_readLine (IMDPtr imd, uchar *pix, int nbytes, int x, int y)
IMDPtr imd_initialize (int fdin, int fdout, int domain)
int imd_parseImtdev (char *imtdev, char *unixaddr, unsigned short *host_port, unsigned long *host_addr, char *ififo, char *ofifo)
int imd_loadImtoolrc (IMDPtr imd)
int imd_getstr (char **ipp, char *obuf, int maxch)
void imd_minmax (uchar *pix, int nbytes, int *pmin, int *pmax)
Variables
int imd_debug = 0
char buf [SZ_LINE]
Define Documentation
#define CDL_LIBRARY_SOURCE
Definition at line 10 of file imd.c.
#define DEF_FBCONFIG 1
Definition at line 67 of file imd.c.
#define DEF_FRAME_HEIGHT 512
Definition at line 77 of file imd.c.
Referenced by get_fbconfig(), and imd_loadImtoolrc().
#define DEF_FRAME_WIDTH 512
Definition at line 76 of file imd.c.
Referenced by get_fbconfig(), and imd_loadImtoolrc().
#define DEF_OSDEV_1 'unix:/tmp/.IMT%d'
Definition at line 68 of file imd.c.
#define DEF_OSDEV_2 'fifo:/dev/imt1i:/dev/imt1o'
Definition at line 69 of file imd.c.
Referenced by imd_open().
#define FBCONFIG_1 '.imtoolrc'
Definition at line 72 of file imd.c.
Referenced by get_fbconfig(), and imd_loadImtoolrc().
#define FBCONFIG_2 '/usr/local/lib/imtoolrc'
Definition at line 73 of file imd.c.
Referenced by imd_loadImtoolrc().
#define FBCONFIG_ENV1 'imtoolrc'
Definition at line 74 of file imd.c.
Referenced by get_fbconfig(), and imd_loadImtoolrc().
#define FBCONFIG_ENV2 'IMTOOLRC'
Definition at line 75 of file imd.c.
Referenced by get_fbconfig(), and imd_loadImtoolrc().
#define FIFO 12
Definition at line 64 of file imd.c.
Referenced by imd_open(), and imd_parseImtdev().
#define INET 11
Definition at line 63 of file imd.c.
Referenced by imd_open(), and imd_parseImtdev().
#define SZ_BLOCK 16384
Definition at line 53 of file imd.c.
Referenced by imd_readSubRaster(), imd_writeImage(), and imd_writeSubRaster().
#define UNIX 10
Definition at line 62 of file imd.c.
Referenced by imd_open(), and imd_parseImtdev().
#define W_LINEAR 1
Definition at line 57 of file imd.c.
Referenced by imd_displayImage(), imd_initialize(), and wcs_update().
#define W_LOG 2
Definition at line 58 of file imd.c.
#define W_UNITARY 0
Definition at line 56 of file imd.c.
Referenced by wcs_update().
#define W_USER 3
Definition at line 59 of file imd.c.
Function Documentation
int imd_clearFrame (IMDPtr imd)
Definition at line 932 of file imd.c.
References com_eraseFrame(), imd_debug, and IMDPtr.
int imd_close (IMDPtr imd)
Definition at line 527 of file imd.c.
References free(), imd_debug, IMDPtr, and OK.
int imd_displayImage (IMDPtr imd, uchar 	* pix, int nx, int ny, int frame, int fbconfig, int comp_wcs)
Definition at line 292 of file imd.c.
References ERR, fbconfig, frame, free(), i, imd_clearFrame(), imd_debug, imd_minmax(), imd_setFBConfig(), imd_setFrame(), imd_setWCS(), imd_writeImage(), IMDPtr, INDEF, ly, malloc(), min, nx, ny, pix, SZ_NAME, uchar, and W_LINEAR.
Referenced by cdl_displayPix().
int imd_getFBConfig (IMDPtr imd, int	* configno, int	* width, int * height, int	* nframes)
Definition at line 819 of file imd.c.
References com_setFBConfig(), imd_debug, IMDPtr, and nframes.
int imd_getstr (char ** ipp, char * obuf, int maxch) [static]
Definition at line 1534 of file imd.c.
References maxch, and op.
int imd_getstr ()
Referenced by imd_parseImtdev().
int imd_getWCS (IMDPtr imd, char	* name, char	* title, float	* a, float * b, float * c, float * d, float	* tx, float * ty, float	* z1, float * z2, int	* zt)
Definition at line 488 of file imd.c.
References a, b, buf, c, com_readWCS(), d, ERR, imd_debug, IMDPtr, OK, title, tx, ty, z1, z2, and zt.
IMDPtr imd_initialize (int fdin, int fdout, int domain) [static]
Definition at line 1280 of file imd.c.
References IMD::a, IMD::b, IMD::c, IMD::d, IMD::datain, IMD::dataout, IMD::domain, IMD::fbconfig, IMD::frame, imd_loadImtoolrc(), IMDPtr, IMD::name, SZ_NAME, IMD::title, IMD::tx, IMD::ty, W_LINEAR, IMD::z1, IMD::z2, and IMD::ztrans.
IMDPtr imd_initialize () [static]
Referenced by imd_open().
int imd_loadImtoolrc (IMDPtr imd) [static]
Definition at line 1429 of file imd.c.
References buf, DEF_FRAME_HEIGHT, DEF_FRAME_WIDTH, ERR, FBCONFIG_1, FBCONFIG_2, FBCONFIG_ENV1, FBCONFIG_ENV2, i, imd_debug, IMDPtr, malloc(), max, MAX_FBCONFIG, min, nframes, OK, and SZ_LINE.
int imd_loadImtoolrc ()
Referenced by imd_initialize().
void imd_minmax (uchar 	* pix, int nbytes, int	* pmin, int * pmax) [static]
Definition at line 1566 of file imd.c.
References i, max, min, pix, and uchar.
void imd_minmax () [static]
Referenced by imd_displayImage().
IMDPtr imd_open (char 	* imtdev)
Definition at line 152 of file imd.c.
References DEF_OSDEV_2, ERR, FIFO, imd_debug, imd_initialize(), imd_parseImtdev(), IMDPtr, imtdev, INET, malloc(), SZ_IMTDEV, SZ_NAME, and UNIX.
int imd_parseImtdev (char		* imtdev, char		* unixaddr, unsigned short	* host_port, unsigned long	* host_addr, char		* ififo, char * ofifo) [static]
Definition at line 1335 of file imd.c.
References ERR, FIFO, imd_getstr(), imtdev, INET, SZ_LINE, SZ_NAME, and UNIX.
int imd_parseImtdev () [static]
Referenced by imd_open().
int imd_readCursor (IMDPtr imd, int sample, float	* x, float * y, char	* key)
Definition at line 399 of file imd.c.
References com_readCursor(), imd_debug, IMDPtr, key, x, and y.
int imd_readFrameBuffer (IMDPtr imd, uchar	* pix, int	* nx, int * ny)
Definition at line 728 of file imd.c.
References imd_debug, imd_readSubRaster(), IMDPtr, malloc(), nx, ny, pix, and uchar.
Referenced by cdl_readFrameBuffer().
int imd_readImage (IMDPtr imd, uchar	* pix, int	* nx, int * ny)
Definition at line 704 of file imd.c.
References imd_debug, imd_readSubRaster(), IMDPtr, malloc(), nx, ny, pix, and uchar.
Referenced by cdl_readImage().
int imd_readLine (IMDPtr imd, uchar	* pix, int nbytes, int x, int y) [static]
Definition at line 1251 of file imd.c.
References com_readData(), imd_debug, IMDPtr, pix, uchar, x, and y.
int imd_readLine ()
Referenced by imd_readSubRaster(), and imd_writeSubRaster().
int imd_readSubRaster (IMDPtr imd, int llx, int lly, int nx, int ny, uchar	* pix)
Definition at line 947 of file imd.c.
References ERR, free(), i, imd_debug, imd_readLine(), IMDPtr, j, ly, malloc(), max, min, nx, ny, OK, pix, SZ_BLOCK, uchar, and y.
int imd_setCursor (IMDPtr imd, int x, int y, int wcs)
Definition at line 905 of file imd.c.
References com_setCursor(), imd_debug, IMDPtr, wcs, x, and y.
int imd_setDebug (int state)
Definition at line 1210 of file imd.c.
References imd_debug, and OK.
Referenced by cdl_setDebug().
int imd_setFBConfig (IMDPtr imd, int configno)
Definition at line 789 of file imd.c.
References com_setFBConfig(), imd_debug, and IMDPtr.
int imd_setFrame (IMDPtr imd, int frame)
Definition at line 763 of file imd.c.
References com_setFrame(), frame, imd_debug, and IMDPtr.
int imd_setName (IMDPtr imd, char	* name)
Definition at line 851 of file imd.c.
References imd_debug, IMDPtr, and OK.
Referenced by cdl_setName().
int imd_setTitle (IMDPtr imd, char	* title)
Definition at line 877 of file imd.c.
References imd_debug, IMDPtr, OK, and title.
Referenced by cdl_setTitle().
int imd_setWCS (IMDPtr imd, char	* name, char	* title, float a, float b, float c, float d, float tx, float ty, float z1, float z2, int zt)
Definition at line 444 of file imd.c.
References a, b, buf, c, com_writeWCS(), d, imd_debug, IMDPtr, title, tx, ty, z1, z2, and zt.
int imd_writeImage (IMDPtr imd, uchar 	* pix, int nx, int ny, int llx, int lly)
Definition at line 557 of file imd.c.
References ERR, free(), i, imd_debug, imd_writeLine(), IMDPtr, j, k, ly, malloc(), max, min, nx, ny, OK, pix, SZ_BLOCK, uchar, and y.
Referenced by imd_displayImage().
int imd_writeLine (IMDPtr imd, uchar	* pix, int nbytes, int x, int y) [static]
Definition at line 1231 of file imd.c.
References com_writeData(), imd_debug, IMDPtr, pix, uchar, x, and y.
int imd_writeLine () [static]
Referenced by imd_writeImage(), and imd_writeSubRaster().
int imd_writeSubRaster (IMDPtr imd, int llx, int lly, int nx, int ny, uchar	* pix)
Definition at line 1076 of file imd.c.
References ERR, free(), i, imd_debug, imd_readLine(), imd_writeLine(), IMDPtr, j, ly, malloc(), max, min, nx, ny, OK, pix, SZ_BLOCK, uchar, and y.
Variable Documentation
char buf[SZ_LINE]
Definition at line 81 of file imd.c.
Referenced by cdl_getFITSPixels(), com_read(), com_readCursor(), com_write(), counter_filter(), iis_cur(), iis_read(), iis_write(), imd_getWCS(), imd_loadImtoolrc(), imd_setWCS(), jpl_state(), main(), make_label(), vx_iisio(), and wcs_update().
int imd_debug = 0
Definition at line 80 of file imd.c.
Referenced by imd_clearFrame(), imd_close(), imd_displayImage(), imd_getFBConfig(), imd_getWCS(), imd_loadImtoolrc(), imd_open(), imd_readCursor(), imd_readFrameBuffer(), imd_readImage(), imd_readLine(), imd_readSubRaster(), imd_setCursor(), imd_setDebug(), imd_setFBConfig(), imd_setFrame(), imd_setName(), imd_setTitle(), imd_setWCS(), imd_writeImage(), imd_writeLine(), and imd_writeSubRaster().
Author
Generated automatically by Doxygen for imcat from the source code.