imhead.c
NAME
imhead.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	imhead --- extract fits header\n\\n\SYNOPSIS\n\	imhead [options...] \n\		-b		# output full binary header\n\		-D		# discard header\n\		-d		# discard header and tail\n\		-v name		# print value of header item 'name'\n\		-t name		# print value of header item 'name'\n\		-g pixtype NAXIS NAXIS1 ...	# generate fits header.\n\\n\DESCRIPTION\n\	\'imhead\' prints fits image header info\n\	reads/writes from/to stdin/stdout.\n\	By default it formats the header values, but with\n\	-b option it will output full header with padding\n\	exactly as it appears - this is useful if you have some\n\	data in raw bytes format and want to construct a legal\n\	fits header: use 'ic' to generate a suitable image and\n\	then pipe this into 'imhead -b' to make the header.\n\	Use -D, -d options to extract raw image data.\n\	With -v we print the value for the last header\n\	item whose name matches 'name' exactly. Only the\n\	first word of the value will be printed.\n\	With -t option we print everything following the '= '.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	imhead --- extract fits header\n\\n\SYNOPSIS\n\	imhead [options...] \n\		-b		# output full binary header\n\		-D		# discard header\n\		-d		# discard header and tail\n\		-v name		# print value of header item 'name'\n\		-t name		# print value of header item 'name'\n\		-g pixtype NAXIS NAXIS1 ...	# generate fits header.\n\\n\DESCRIPTION\n\	\'imhead\' prints fits image header info\n\	reads/writes from/to stdin/stdout.\n\	By default it formats the header values, but with\n\	-b option it will output full header with padding\n\	exactly as it appears - this is useful if you have some\n\	data in raw bytes format and want to construct a legal\n\	fits header: use 'ic' to generate a suitable image and\n\	then pipe this into 'imhead -b' to make the header.\n\	Use -D, -d options to extract raw image data.\n\	With -v we print the value for the last header\n\	item whose name matches 'name' exactly. Only the\n\	first word of the value will be printed.\n\	With -t option we print everything following the '= '.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file imhead.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 45 of file imhead.c.
References argsinit(), fitsheader::basecomment, BIG_ENDIAN_BYTE_ORDER, fitsheader::bscale, fitsheader::bscaling, fitsheader::bzero, error_exit, exit(), fitsheader::extpixtype, f, fits, flag, getargi(), getargs(), getcommentbyname(), getflag(), gettextvalue(), fitsheader::hasextensions, i, fitsheader::ipbyteorder, fitsheader::n, n, fitscomment::name, fitsheader::ndim, newfitsheader(), newnumericcomment(), newtextcomment(), fitscomment::next, fitsheader::nextensions, pixsize(), prependcomment(), printall(), readfitsheader(), usage, fitscomment::value, writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.