maptest.c
NAME
maptest.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include '../utils/arrays.h'
#include 'map.h'
#include 'fits.h'
Functions
void deflect (float ri, float rj, float *di, float *dj)
main (int argc, char *argv[])
Variables
int N = 5
int N1
int N2
int M1
int M2
Function Documentation
void deflect (float ri, float rj, float * di, float * dj)
main (int argc, char * argv[])
Definition at line 16 of file imlib/maptest.c.
References allocFloatArray(), deflect(), exit(), FLOAT_PIXTYPE, FORWARDMAPMODE, fread_fits(), fwrite_fits(), i, INVERSEMAPMODE, j, M1, M2, map(), N1, N2, set_output_pixtype(), and set_triangle_map_mode().
Variable Documentation
int M1
Definition at line 14 of file imlib/maptest.c.
int M2
Definition at line 14 of file imlib/maptest.c.
int N = 5
Definition at line 13 of file imlib/maptest.c.
int N1
Definition at line 14 of file imlib/maptest.c.
int N2
Definition at line 14 of file imlib/maptest.c.
Author
Generated automatically by Doxygen for imcat from the source code.