.TH "op_math.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
op_math.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBtimes\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBplus\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBdivide\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBminus\fP (double x, double y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double divide (double x, double y)"
.PP
Definition at line 18 of file imtools/ic/ic1/op_math.c.
.PP
References x, and y.
.SS "double minus (double x, double y)"
.PP
Definition at line 24 of file imtools/ic/ic1/op_math.c.
.PP
References x, and y.
.SS "double plus (double x, double y)"
.PP
Definition at line 12 of file imtools/ic/ic1/op_math.c.
.PP
References x, and y.
.SS "double times (double x, double y)"
.PP
Definition at line 6 of file imtools/ic/ic1/op_math.c.
.PP
References x, and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
