.TH "maptest.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maptest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include '../utils/arrays.h'\fP
.br
\fC#include '../imlib/map.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdeflect\fP (float ri, float rj, float *\fBdi\fP, float *\fBdj\fP)"
.br
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBN\fP = 5"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void deflect (float ri, float rj, float * di, float * dj)"
.PP
Referenced by main().
.SS "main (int argc, char * argv[])"
.PP
Definition at line 14 of file imtools/maptest.c.
.PP
References allocFloatArray(), deflect(), exit(), i, j, map(), N, and trianglecount().
.SH "Variable Documentation"
.PP 
.SS "int \fBN\fP = 5"
.PP
Definition at line 12 of file imtools/maptest.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
