getop.c
NAME
getop.c -
SYNOPSIS
#include <stdio.h>
#include <limits.h>
#include 'getop.h'
#include 'operators.h'
#include '../../utils/error.h'
#include '../magic.h'
Functions
op * getop (char **sptr)
char * getword (char **sptr)
Variables
int nim
Function Documentation
op* getop (char ** sptr)
Definition at line 16 of file imtools/ic/ic2/getop.c.
References item::addr, allocitemcontents(), CONSTANT_TYPE, copyitem(), copystring(), op::data, error_exit, exit(), free(), getheaderitem(), getobjectitem(), getword(), IM_VALUE_TYPE, MAGIC, newitem(), newop(), newopitem(), nim, NUM_TYPE, number, op::opno, sourcecathead, TEXT_TYPE, and op::type.
Referenced by main(), and newrpnfunction().
char* getword (char ** sptr)
Definition at line 79 of file imtools/ic/ic2/getop.c.
References c, and len.
Referenced by getop(), parseheaderexpr(), and parsename().
Variable Documentation
int nim
Definition at line 13 of file imtools/ic/ic2/getop.c.
Author
Generated automatically by Doxygen for imcat from the source code.