operators.c
NAME
operators.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'stack.h'
#include 'getop.h'
#include 'operators.h'
#include 'op_math.h'
#include 'op_logic.h'
#include 'ic.h'
Defines
#define N_NUM0_OPS 8
#define N_NUM1_OPS 17
#define N_NUM2_OPS 13
Functions
op * newop (char *thename)
Variables
char * num0funcname [N_NUM0_OPS]
double(* num0funcarray [N_NUM0_OPS])(void)=
char * num1funcname [N_NUM1_OPS]
double(* num1funcarray [N_NUM1_OPS])(double)=
char * num2funcname [N_NUM2_OPS]
double(* num2funcarray [N_NUM2_OPS])(double, double)=
Define Documentation
#define N_NUM0_OPS 8
Definition at line 23 of file imtools/ic/ic1/operators.c.
#define N_NUM1_OPS 17
Definition at line 30 of file imtools/ic/ic1/operators.c.
#define N_NUM2_OPS 13
Definition at line 41 of file imtools/ic/ic1/operators.c.
Function Documentation
op* newop (char * thename)
Definition at line 54 of file imtools/ic/ic1/operators.c.
References exit(), N_NUM0_OPS, N_NUM1_OPS, N_NUM2_OPS, NUM0_FUNC_TYPE, num0funcname, NUM1_FUNC_TYPE, num1funcname, NUM2_FUNC_TYPE, num2funcname, op::opno, and op::type.
Variable Documentation
double(* num0funcarray[N_NUM0_OPS])(void) =
Definition at line 26 of file imtools/ic/ic1/operators.c.
Referenced by main(), newop(), and num0func().
char* num0funcname[N_NUM0_OPS] [static]
Initial value:.nf
 {
'rand', 'x', 'y', 'xp', 'yp', 'if', '?', 'enter'}
Definition at line 24 of file imtools/ic/ic1/operators.c.
Referenced by newop().
double(* num1funcarray[N_NUM1_OPS])(double) =
Definition at line 35 of file imtools/ic/ic1/operators.c.
char* num1funcname[N_NUM1_OPS] [static]
Initial value:.nf
 {
'acos', 'asin', 'atan', 'ceil', 'cos', 'cosh', 'exp', 'fabs', 'floor',
'log', 'log10', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', '!'
}
Definition at line 31 of file imtools/ic/ic1/operators.c.
Referenced by newop().
double(* num2funcarray[N_NUM2_OPS])(double, double) =
Definition at line 46 of file imtools/ic/ic1/operators.c.
char* num2funcname[N_NUM2_OPS] [static]
Initial value:.nf
 {
'mult', '*', '+', '/', '-', 'atan2', 'pow', 'fmod',
'>', '>=', '<', '<=', '!='
}
Definition at line 42 of file imtools/ic/ic1/operators.c.
Referenced by newop().
Author
Generated automatically by Doxygen for imcat from the source code.