operators.h
NAME
operators.h -
SYNOPSIS
Functions
op * newop (char *name)
double drand48 (void)
double If (void)
double enter (void)
double pop (void)
Variables
void(* funcarray [])(op *)
Function Documentation
double drand48 (void)
double enter (void)
Definition at line 271 of file ic1/ic.c.
References pop(), and push().
double If (void)
Definition at line 261 of file ic1/ic.c.
References c, f, pop(), and t.
op* newop (char * name)
Definition at line 168 of file imtools/ic/getop.c.
References op::addr, exit(), N_NUM0_OPS, N_NUM1_OPS, N_NUM2_OPS, NUM0_FUNC_TYPE, num0funcarray, num0funcname, NUM1_FUNC_TYPE, num1funcarray, num1funcname, NUM2_FUNC_TYPE, num2funcarray, num2funcname, op::opno, and op::type.
Referenced by getop().
double pop (void)
Definition at line 32 of file cattools/lc/stack.c.
Variable Documentation
void(* funcarray[])(op *)
Definition at line 8 of file imtools/ic/ic2/operators.h.
Author
Generated automatically by Doxygen for imcat from the source code.