stack.c
NAME
stack.c -
SYNOPSIS
#include <stdio.h>
#include 'stack.h'
#include 'error.h'
Defines
#define STACK_DEPTH 100
Functions
void push (double number)
double pop (void)
void resetstack (void)
Variables
double stack [STACK_DEPTH]
int stackpos = 0
Define Documentation
#define STACK_DEPTH 100
Definition at line 10 of file imtools/ic/ic2/stack.c.
Function Documentation
double pop (void)
Definition at line 28 of file imtools/ic/ic2/stack.c.
References error_exit, itemstack, stack, and stackpos.
void push (double number)
Definition at line 15 of file imtools/ic/ic2/stack.c.
References error_exit, number, stack, STACK_DEPTH, and stackpos.
Referenced by enter(), enterdoit(), enterinit(), evalrpnfunction(), and main().
void resetstack (void)
Definition at line 41 of file imtools/ic/ic2/stack.c.
References stackpos.
Variable Documentation
double stack[STACK_DEPTH]
Definition at line 12 of file imtools/ic/ic2/stack.c.
int stackpos = 0
Definition at line 13 of file imtools/ic/ic2/stack.c.
Author
Generated automatically by Doxygen for imcat from the source code.