stack.h
NAME
stack.h -
SYNOPSIS
Functions
void push (double number)
double pop (void)
Function Documentation
double pop (void)
Definition at line 32 of file cattools/lc/stack.c.
References error_exit, itemstack, stack, and stackpos.
void push (double number)
Definition at line 15 of file imtools/ic/ic1/stack.c.
References error_exit, number, stack, STACK_DEPTH, and stackpos.
Referenced by enter(), enterdoit(), enterinit(), evalrpnfunction(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.