getop.h
NAME
getop.h -
SYNOPSIS
Data Structures
struct op
Defines
#define N_TYPES 5
#define NUM0_FUNC_TYPE 0
#define NUM1_FUNC_TYPE 1
#define NUM2_FUNC_TYPE 2
#define CONSTANT_TYPE 3
#define IM_VALUE_TYPE 4
Typedefs
typedef op op
Functions
op * getop (char **sptr)
char * getword (char **sptr)
Define Documentation
#define CONSTANT_TYPE 3
Definition at line 10 of file imtools/ic/ic2/getop.h.
#define IM_VALUE_TYPE 4
Definition at line 11 of file imtools/ic/ic2/getop.h.
#define N_TYPES 5
Definition at line 6 of file imtools/ic/ic2/getop.h.
#define NUM0_FUNC_TYPE 0
Definition at line 7 of file imtools/ic/ic2/getop.h.
#define NUM1_FUNC_TYPE 1
Definition at line 8 of file imtools/ic/ic2/getop.h.
#define NUM2_FUNC_TYPE 2
Definition at line 9 of file imtools/ic/ic2/getop.h.
Typedef Documentation
typedef struct op op
Function Documentation
op* getop (char ** sptr)
Definition at line 16 of file cattools/lc/getop.c.
References item::addr, allocitemcontents(), CONSTANT_TYPE, copyitem(), copystring(), op::data, error_exit, exit(), free(), getheaderitem(), getobjectitem(), getword(), IM_VALUE_TYPE, MAGIC, newitem(), newop(), newopitem(), nim, NUM_TYPE, number, op::opno, sourcecathead, TEXT_TYPE, and op::type.
Referenced by main(), and newrpnfunction().
char* getword (char ** sptr)
Definition at line 84 of file cattools/lc/getop.c.
References c, and len.
Referenced by getop(), parseheaderexpr(), and parsename().
Author
Generated automatically by Doxygen for imcat from the source code.