maptest.c
NAME
maptest.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include '../utils/arrays.h'
#include '../imlib/map.h'
Functions
void deflect (float ri, float rj, float *di, float *dj)
main (int argc, char *argv[])
Variables
int N = 5
Function Documentation
void deflect (float ri, float rj, float * di, float * dj)
Referenced by main().
main (int argc, char * argv[])
Definition at line 14 of file imtools/maptest.c.
References allocFloatArray(), deflect(), exit(), i, j, map(), N, and trianglecount().
Variable Documentation
int N = 5
Definition at line 12 of file imtools/maptest.c.
Author
Generated automatically by Doxygen for imcat from the source code.