getop.c
NAME
getop.c -
SYNOPSIS
#include <stdio.h>
#include <limits.h>
#include 'getop.h'
#include '../../utils/error.h'
#include '../../imlib/fits.h'
Defines
#define MAGIC FLOAT_MAGIC
Functions
void set_getop_N1 (int n1)
op * getop (char **sptr)
char * getword (char **sptr)
op * newop (char *thename)
Variables
int nim
int N1
char * num0funcname [N_NUM0_OPS]
char * num1funcname [N_NUM1_OPS]
char * num2funcname [N_NUM2_OPS]
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 12 of file imtools/ic/getop.c.
Function Documentation
op* getop (char ** sptr)
Definition at line 37 of file imtools/ic/getop.c.
References CONSTANT_TYPE, op::data, error_exit, exit(), getword(), IM_VALUE_TYPE, ix, MAGIC, N1, newop(), nim, number, op::opno, and op::type.
char* getword (char ** sptr)
Definition at line 108 of file imtools/ic/getop.c.
References c, and len.
op* newop (char * thename)
Definition at line 168 of file imtools/ic/getop.c.
void set_getop_N1 (int n1)
Definition at line 31 of file imtools/ic/getop.c.
References N1.
Referenced by main().
Variable Documentation
int N1 [static]
Definition at line 14 of file imtools/ic/getop.c.
int nim
Definition at line 13 of file imtools/ic/getop.c.
Referenced by getop(), and main().
char* num0funcname[N_NUM0_OPS] [static]
Initial value:.nf
 {
'rand', 'x', 'y', 'xp', 'yp', 'if', '?', 'enter', 'grand'}
Definition at line 17 of file imtools/ic/getop.c.
Referenced by newop().
char* num1funcname[N_NUM1_OPS] [static]
Initial value:.nf
 {
'acos', 'asin', 'atan', 'ceil', 'cos', 'cosh', 'exp', 'fabs', 'floor',
'log', 'log10', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', '!', 'j0', 'j1', 'y0', 'y1', 'swap'
}
Definition at line 20 of file imtools/ic/getop.c.
Referenced by newop().
char* num2funcname[N_NUM2_OPS] [static]
Initial value:.nf
 {
'mult', '*', '+', '/', '-', 'atan2', 'pow', 'fmod',
'>', '>=', '<', '<=', '!=', '==', 'jn', 'yn', 'max', 'min'
}
Definition at line 25 of file imtools/ic/getop.c.
Referenced by newop().
Author
Generated automatically by Doxygen for imcat from the source code.