.TH "op_logic.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
op_logic.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBgt\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBge\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBlt\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBle\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBne\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBnot\fP (double x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double ge (double x, double y)"
.PP
Definition at line 13 of file cattools/lc/op_logic.c.
.PP
References x, and y.
.SS "double gt (double x, double y)"
.PP
Definition at line 6 of file cattools/lc/op_logic.c.
.PP
References x, and y.
.SS "double le (double x, double y)"
.PP
Definition at line 27 of file cattools/lc/op_logic.c.
.PP
References x, and y.
.SS "double lt (double x, double y)"
.PP
Definition at line 20 of file cattools/lc/op_logic.c.
.PP
References x, and y.
.SS "double ne (double x, double y)"
.PP
Definition at line 34 of file cattools/lc/op_logic.c.
.PP
References x, and y.
.SS "double not (double x)"
.PP
Definition at line 45 of file cattools/lc/op_logic.c.
.PP
References x.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
