operators.c
NAME
operators.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'getop.h'
#include 'operators.h'
#include 'op_math.h'
#include 'op_logic.h'
#include 'ic.h'
Defines
#define STACK_DEPTH 100
#define N_NUM0_OPS 8
#define N_NUM1_OPS 17
#define N_NUM2_OPS 13
Functions
void num0func (op *theop)
void num1func (op *theop)
void num2func (op *theop)
void constfunc (op *theop)
void imvalfunc (op *theop)
double(* num0funcarray [N_NUM0_OPS])(void)=
double(* num1funcarray [N_NUM1_OPS])(double)=
double(* num2funcarray [N_NUM2_OPS])(double, double)=
op * newop (char *thename)
double If (void)
double enter (void)
double pop (void)
Variables
int ix
float ** f
double stack [STACK_DEPTH]
int stackpos = -1
double(* num0funcarray [])(void)
double(* num1funcarray [])(double)
double(* num2funcarray [])(double, double)
void(* funcarray [N_TYPES])(op *)=
char * num0funcname [N_NUM0_OPS]
char * num1funcname [N_NUM1_OPS]
char * num2funcname [N_NUM2_OPS]
Define Documentation
#define N_NUM0_OPS 8
Definition at line 44 of file imtools/ic/ic2/operators.c.
#define N_NUM1_OPS 17
Definition at line 51 of file imtools/ic/ic2/operators.c.
#define N_NUM2_OPS 13
Definition at line 62 of file imtools/ic/ic2/operators.c.
#define STACK_DEPTH 100
Definition at line 24 of file imtools/ic/ic2/operators.c.
Function Documentation
void constfunc (op * theop)
Definition at line 145 of file imtools/ic/ic2/operators.c.
References op::data, stack, and stackpos.
double enter (void)
Definition at line 170 of file imtools/ic/ic2/operators.c.
References pop(), and push().
double If (void)
Definition at line 158 of file imtools/ic/ic2/operators.c.
References c, f, pop(), and t.
void imvalfunc (op * theop)
Definition at line 151 of file imtools/ic/ic2/operators.c.
References f, ix, op::opno, stack, and stackpos.
op* newop (char * thename)
Definition at line 75 of file imtools/ic/ic2/operators.c.
References op::addr, exit(), N_NUM0_OPS, N_NUM1_OPS, N_NUM2_OPS, NUM0_FUNC_TYPE, num0funcarray, num0funcname, NUM1_FUNC_TYPE, num1funcarray, num1funcname, NUM2_FUNC_TYPE, num2funcarray, num2funcname, op::opno, and op::type.
Referenced by getop().
void num0func (op * theop)
Definition at line 127 of file imtools/ic/ic2/operators.c.
References num0funcarray, op::opno, stack, and stackpos.
double(* num0funcarray (void)
Definition at line 47 of file imtools/ic/ic2/operators.c.
References drand48(), enter(), If(), x, xp(), y, and yp().
void num1func (op * theop)
Definition at line 133 of file imtools/ic/ic2/operators.c.
References num1funcarray, op::opno, stack, and stackpos.
Referenced by evalrpnfunction().
double(* num1funcarray (double)
Definition at line 56 of file imtools/ic/ic2/operators.c.
References not().
void num2func (op * theop)
Definition at line 138 of file imtools/ic/ic2/operators.c.
References num2funcarray, op::opno, stack, and stackpos.
Referenced by evalrpnfunction().
double(* num2funcarray (double, double)
Definition at line 67 of file imtools/ic/ic2/operators.c.
References divide(), ge(), gt(), le(), lt(), minus(), ne, plus(), and times().
double pop (void)
Definition at line 182 of file imtools/ic/ic2/operators.c.
References stack, and stackpos.
Variable Documentation
float** f
Definition at line 22 of file imtools/ic/ic2/operators.c.
void(* funcarray[N_TYPES])(op *) =
Definition at line 40 of file imtools/ic/ic2/operators.c.
Referenced by main().
int ix
Definition at line 21 of file imtools/ic/ic2/operators.c.
Referenced by addarea(), addgalaxy(), allocgrid(), apphot(), assigncharge(), assigncharge_cic(), ccf(), cfilter(), contourplot(), fill_pixmap(), filter(), findpeak(), func(), fwrite_fits(), get_fft(), getcoords(), getgridcoords(), getneighbours(), getobjects(), getop(), getshape2(), getshape3(), getsky(), getsourceij(), ifunc(), iisdisplay(), imvalfunc(), main(), makebetamodel(), makemodel(), painttriangle(), power(), rfunc(), rpetrosian(), set_fft(), x(), xp(), and zap().
double(* num0funcarray[N_NUM0_OPS])(void) =
Definition at line 47 of file imtools/ic/ic2/operators.c.
char* num0funcname[N_NUM0_OPS] [static]
Initial value:.nf
 {
'rand', 'x', 'y', 'xp', 'yp', 'if', '?', 'enter'}
Definition at line 45 of file imtools/ic/ic2/operators.c.
Referenced by newop().
double(* num1funcarray[N_NUM1_OPS])(double) =
Definition at line 56 of file imtools/ic/ic2/operators.c.
char* num1funcname[N_NUM1_OPS] [static]
Initial value:.nf
 {
'acos', 'asin', 'atan', 'ceil', 'cos', 'cosh', 'exp', 'fabs', 'floor',
'log', 'log10', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', '!'
}
Definition at line 52 of file imtools/ic/ic2/operators.c.
Referenced by newop().
double(* num2funcarray[N_NUM2_OPS])(double, double) =
Definition at line 67 of file imtools/ic/ic2/operators.c.
char* num2funcname[N_NUM2_OPS] [static]
Initial value:.nf
 {
'mult', '*', '+', '/', '-', 'atan2', 'pow', 'fmod',
'>', '>=', '<', '<=', '!='
}
Definition at line 63 of file imtools/ic/ic2/operators.c.
Referenced by newop().
double stack[STACK_DEPTH]
Definition at line 26 of file imtools/ic/ic2/operators.c.
int stackpos = -1
Definition at line 27 of file imtools/ic/ic2/operators.c.
Author
Generated automatically by Doxygen for imcat from the source code.