getop.c
NAME
getop.c -
SYNOPSIS
#include <stdio.h>
#include <limits.h>
#include 'getop.h'
#include 'operators.h'
#include '../../utils/error.h'
#include '../magic.h'
Functions
op * getop (char **sptr)
char * getword (char **sptr)
Variables
int nim
Function Documentation
op* getop (char ** sptr)
Definition at line 16 of file imtools/ic/ic1/getop.c.
References CONSTANT_TYPE, op::data, error_exit, exit(), getword(), IM_VALUE_TYPE, MAGIC, newop(), nim, number, op::opno, and op::type.
char* getword (char ** sptr)
Definition at line 79 of file imtools/ic/ic1/getop.c.
References c, and len.
Variable Documentation
int nim
Definition at line 13 of file imtools/ic/ic1/getop.c.
Author
Generated automatically by Doxygen for imcat from the source code.