.TH "stack.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stack.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpush\fP (double \fBnumber\fP)"
.br
.ti -1c
.RI "double \fBpop\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double pop (void)"
.PP
Definition at line 32 of file cattools/lc/stack.c.
.PP
References error_exit, itemstack, stack, and stackpos.
.SS "void push (double number)"
.PP
Definition at line 15 of file imtools/ic/ic1/stack.c.
.PP
References error_exit, number, stack, STACK_DEPTH, and stackpos.
.PP
Referenced by enter(), enterdoit(), enterinit(), evalrpnfunction(), and main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
