.TH "operators.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
operators.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBop\fP * \fBnewop\fP (char *name)"
.br
.ti -1c
.RI "double \fBdrand48\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double(* \fBnum0funcarray\fP [])(void)"
.br
.ti -1c
.RI "double(* \fBnum1funcarray\fP [])(double)"
.br
.ti -1c
.RI "double(* \fBnum2funcarray\fP [])(double, double)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double drand48 (void)"
.PP
.SS "\fBop\fP* newop (char * name)"
.PP
Definition at line 168 of file imtools/ic/getop.c.
.SH "Variable Documentation"
.PP 
.SS "double(* num0funcarray[])(void)"
.PP
Definition at line 6 of file imtools/ic/ic1/operators.h.
.SS "double(* num1funcarray[])(double)"
.PP
Definition at line 7 of file imtools/ic/ic1/operators.h.
.SS "double(* num2funcarray[])(double, double)"
.PP
Definition at line 8 of file imtools/ic/ic1/operators.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
