imview_stuff.h
NAME
imview_stuff.h -
SYNOPSIS
Functions
void alloc_grays (int *n_cells)
Pixmap make_pixmap (int fMin, int fMax, int n_cells)
void set_grays (int n_cells, int n_lo, int n_hi)
Function Documentation
void alloc_grays (int * n_cells)
Definition at line 26 of file imview_stuff.c.
References cmap, depth, exit(), False, i, info(), main_w, MAX_GRAYS, mydisplay, mygc, myscreen, mywindow, n_cells, n_grays, and pixel.
Referenced by main().
Pixmap make_pixmap (int fMin, int fMax, int n_cells)
Definition at line 107 of file imview_stuff.c.
References color_index(), depth, error_exit, exit(), f, free(), gray, i, j, malloc(), mydisplay, mygc, myscreen, mywindow, N, n_cells, read_fits_head(), read_fits_line(), scale, and SIZE_GOAL.
Referenced by main().
void set_grays (int n_cells, int n_lo, int n_hi)
Definition at line 70 of file imview_stuff.c.
References cmap, f, gray, i, mydisplay, n_cells, and pixel.
Referenced by main(), and new_fminmax().
Author
Generated automatically by Doxygen for imcat from the source code.