.TH "interpolation_info" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interpolation_info \- 
.SH SYNOPSIS
.br
.PP
\fC#include <jpl_int.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBpc\fP [18]"
.br
.ti -1c
.RI "double \fBvc\fP [18]"
.br
.ti -1c
.RI "double \fBtwot\fP"
.br
.ti -1c
.RI "int \fBnp\fP"
.br
.ti -1c
.RI "int \fBnv\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBinterpolation_info::np\fP"
.PP
Definition at line 34 of file jpl_int.h.
.PP
Referenced by interp().
.SS "int \fBinterpolation_info::nv\fP"
.PP
Definition at line 34 of file jpl_int.h.
.PP
Referenced by interp().
.SS "double \fBinterpolation_info::pc\fP[18]"
.PP
Definition at line 33 of file jpl_int.h.
.PP
Referenced by interp().
.SS "double \fBinterpolation_info::twot\fP"
.PP
Definition at line 33 of file jpl_int.h.
.PP
Referenced by interp().
.SS "double \fBinterpolation_info::vc\fP[18]"
.PP
Definition at line 33 of file jpl_int.h.
.PP
Referenced by interp().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
