invgrad.c
NAME
invgrad.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../imlib/fits.h'
#include '../utils/arrays.h'
#include '../fftlib/myfft.h'
Defines
#define usage '\n\NAME\n\	invgrad - take the inverse gradient of a FITS image\n\\n\SYNOPSIS\n\	invgrad\n\\n\DESCRIPTION\n\	'invgrad' applies inverse gradient operator to a gradient image\n\	using the FFT. It reads a N1 by N2 by 2 image from stdin (in format\n\	as generated by 'grad') and writes N1 by N2 image to stdout.\n\	It works by first 'fixing' the end coumn of df/dx\n\	and the last row of df/dy to enforce periodic boundary conditions\n\	and we then apply the inverse discrete difference operator in k-space\n\	to generate two inverse gradient images (one from df/dx, one from\n\	df/dy) and we then combine these with weights\n\		w_x = k_x^2 / k^2\n\		w_y = k_y^2 / k^2\n\	and perform the inverse fourier transform.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n'
#define EPS 1.e-10
#define PI M_PI
Functions
float zero (float kx, float ky)
float invkx (float kx, float ky)
float invky (float kx, float ky)
float halfx (float kx, float ky)
float halfy (float kx, float ky)
main (int argc, char *argv[])
Variables
int N1
int N2
Define Documentation
#define EPS 1.e-10
Definition at line 36 of file invgrad.c.
#define PI M_PI
Definition at line 37 of file invgrad.c.
#define usage '\n\NAME\n\	invgrad - take the inverse gradient of a FITS image\n\\n\SYNOPSIS\n\	invgrad\n\\n\DESCRIPTION\n\	'invgrad' applies inverse gradient operator to a gradient image\n\	using the FFT. It reads a N1 by N2 by 2 image from stdin (in format\n\	as generated by 'grad') and writes N1 by N2 image to stdout.\n\	It works by first 'fixing' the end coumn of df/dx\n\	and the last row of df/dy to enforce periodic boundary conditions\n\	and we then apply the inverse discrete difference operator in k-space\n\	to generate two inverse gradient images (one from df/dx, one from\n\	df/dy) and we then combine these with weights\n\		w_x = k_x^2 / k^2\n\		w_y = k_y^2 / k^2\n\	and perform the inverse fourier transform.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file invgrad.c.
Function Documentation
float halfx (float kx, float ky)
Definition at line 131 of file invgrad.c.
References a, N1, N2, and PI.
Referenced by main().
float halfy (float kx, float ky)
Definition at line 146 of file invgrad.c.
References a, N1, N2, and PI.
Referenced by main().
float invkx (float kx, float ky)
Definition at line 161 of file invgrad.c.
References a, N1, and PI.
Referenced by main().
float invky (float kx, float ky)
Definition at line 175 of file invgrad.c.
References a, N2, and PI.
Referenced by main().
main (int argc, char * argv[])
Definition at line 47 of file invgrad.c.
References add_comment(), alloc_fft(), allocFloatArray(), cfilter(), error_exit, exit(), f, fft_type, fits, forward_fft(), halfx(), halfy(), i, inverse_fft(), invkx(), invky(), j, fitsheader::n, N1, N2, fitsheader::ndim, readfitsheader(), readfitsline(), usage, and write2Dfloatimage().
float zero (float kx, float ky)
Definition at line 125 of file invgrad.c.
Variable Documentation
int N1
Definition at line 45 of file invgrad.c.
int N2
Definition at line 45 of file invgrad.c.
Author
Generated automatically by Doxygen for imcat from the source code.