.TH "IoChan" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IoChan \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBvxim\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBlisten_fd\fP"
.br
.ti -1c
.RI "int \fBdatain\fP"
.br
.ti -1c
.RI "int \fBdataout\fP"
.br
.ti -1c
.RI "int \fBkeepalive\fP"
.br
.ti -1c
.RI "int \fBconnected\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "char \fBpath\fP [SZ_FNAME+1]"
.br
.ti -1c
.RI "int \fBreference_frame\fP"
.br
.ti -1c
.RI "\fBFrameBufPtr\fP \fBrf_p\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBIoChan::connected\fP"
.PP
Definition at line 160 of file vximtool.c.
.SS "int \fBIoChan::datain\fP"
.PP
Definition at line 157 of file vximtool.c.
.SS "int \fBIoChan::dataout\fP"
.PP
Definition at line 158 of file vximtool.c.
.SS "int \fBIoChan::keepalive\fP"
.PP
Definition at line 159 of file vximtool.c.
.SS "int \fBIoChan::listen_fd\fP"
.PP
Definition at line 156 of file vximtool.c.
.SS "char \fBIoChan::path\fP[SZ_FNAME+1]"
.PP
Definition at line 162 of file vximtool.c.
.SS "int \fBIoChan::port\fP"
.PP
Definition at line 161 of file vximtool.c.
.SS "int \fBIoChan::reference_frame\fP"
.PP
Definition at line 163 of file vximtool.c.
.SS "\fBFrameBufPtr\fP \fBIoChan::rf_p\fP"
.PP
Definition at line 164 of file vximtool.c.
.SS "int \fBIoChan::type\fP"
.PP
Definition at line 155 of file vximtool.c.
.SS "void* \fBIoChan::vxim\fP"
.PP
Definition at line 154 of file vximtool.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
