iostream.h
NAME
iostream.h -
SYNOPSIS
Data Structures
struct iostream
Defines
#define STD_IOSTREAM_TYPE 0
#define FILE_IOSTREAM_TYPE 1
#define PIPE_IOSTREAM_TYPE 2
Typedefs
typedef iostream iostream
Functions
iostream * openiostream (char *iostreamstring, char *mode)
int closeiostream (iostream *theiostream)
Define Documentation
#define FILE_IOSTREAM_TYPE 1
Definition at line 20 of file iostream.h.
Referenced by closeiostream(), main(), and openiostream().
#define PIPE_IOSTREAM_TYPE 2
Definition at line 21 of file iostream.h.
Referenced by closeiostream(), and openiostream().
#define STD_IOSTREAM_TYPE 0
Definition at line 19 of file iostream.h.
Referenced by closeiostream(), and openiostream().
Typedef Documentation
typedef struct iostream iostream
Function Documentation
int closeiostream (iostream * theiostream)
Definition at line 90 of file iostream.c.
References error_exit, iostream::f, FILE_IOSTREAM_TYPE, free(), PIPE_IOSTREAM_TYPE, STD_IOSTREAM_TYPE, and iostream::type.
Referenced by main().
iostream* openiostream (char * iostreamstring, char * mode)
Definition at line 11 of file iostream.c.
References error_exit, exit(), iostream::f, FILE_IOSTREAM_TYPE, hasbadchars(), i, iostream::mode, PIPE_IOSTREAM_TYPE, STD_IOSTREAM_TYPE, and iostream::type.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.