.TH "iostreamtest.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iostreamtest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include 'error.h'\fP
.br
\fC#include 'iostream.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 5 of file iostreamtest.c.
.PP
References error_exit, iostream::f, line, and openiostream().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
