iostream.c
NAME
iostream.c -
SYNOPSIS
#include <stdio.h>
#include 'iostream.h'
#include 'error.h'
Functions
int hasbadchars (char *string)
iostream * openiostream (char *iostreamstring, char *mode)
int closeiostream (iostream *theiostream)
Function Documentation
int closeiostream (iostream * theiostream)
Definition at line 90 of file iostream.c.
References error_exit, iostream::f, FILE_IOSTREAM_TYPE, free(), PIPE_IOSTREAM_TYPE, STD_IOSTREAM_TYPE, and iostream::type.
Referenced by main().
int hasbadchars (char * string)
Definition at line 108 of file iostream.c.
References i.
Referenced by openiostream().
iostream* openiostream (char * iostreamstring, char * mode)
Definition at line 11 of file iostream.c.
References error_exit, exit(), iostream::f, FILE_IOSTREAM_TYPE, hasbadchars(), i, iostream::mode, PIPE_IOSTREAM_TYPE, STD_IOSTREAM_TYPE, and iostream::type.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.