.TH "iostream" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iostream \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "FILE * \fBf\fP"
.br
.ti -1c
.RI "char * \fBmode\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "FILE* \fBiostream::f\fP"
.PP
Definition at line 13 of file iostream.h.
.PP
Referenced by closeiostream(), main(), and openiostream().
.SS "char* \fBiostream::mode\fP"
.PP
Definition at line 14 of file iostream.h.
.PP
Referenced by openiostream().
.SS "int \fBiostream::type\fP"
.PP
Definition at line 15 of file iostream.h.
.PP
Referenced by closeiostream(), main(), and openiostream().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
