.TH "ipbuff.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipbuff.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double ** \fBreaddoublebuff\fP (int width, FILE *stream, int *\fBnp\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double** readdoublebuff (int width, FILE * stream, int * np)"
.PP
Definition at line 13 of file ipbuff.c.
.PP
References buff, BUFFPTRSIZE, BUFFSIZE, and error_exit.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
