.TH "jpl_eph_data" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpl_eph_data \- 
.SH SYNOPSIS
.br
.PP
\fC#include <jpl_int.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBephem_start\fP"
.br
.ti -1c
.RI "double \fBephem_end\fP"
.br
.ti -1c
.RI "double \fBephem_step\fP"
.br
.ti -1c
.RI "long \fBncon\fP"
.br
.ti -1c
.RI "double \fBau\fP"
.br
.ti -1c
.RI "double \fBemrat\fP"
.br
.ti -1c
.RI "long \fBipt\fP [13][3]"
.br
.ti -1c
.RI "long \fBephemeris_version\fP"
.br
.ti -1c
.RI "long \fBkernel_size\fP"
.br
.ti -1c
.RI "long \fBrecsize\fP"
.br
.ti -1c
.RI "long \fBncoeff\fP"
.br
.ti -1c
.RI "long \fBswap_bytes\fP"
.br
.ti -1c
.RI "long \fBcurr_cache_loc\fP"
.br
.ti -1c
.RI "double \fBpvsun\fP [6]"
.br
.ti -1c
.RI "double * \fBcache\fP"
.br
.ti -1c
.RI "void * \fBiinfo\fP"
.br
.ti -1c
.RI "FILE * \fBifile\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double \fBjpl_eph_data::au\fP"
.PP
Definition at line 18 of file jpl_int.h.
.SS "double* \fBjpl_eph_data::cache\fP"
.PP
Definition at line 26 of file jpl_int.h.
.SS "long \fBjpl_eph_data::curr_cache_loc\fP"
.PP
Definition at line 24 of file jpl_int.h.
.SS "double \fBjpl_eph_data::emrat\fP"
.PP
Definition at line 19 of file jpl_int.h.
.SS "double \fBjpl_eph_data::ephem_end\fP"
.PP
Definition at line 16 of file jpl_int.h.
.SS "double \fBjpl_eph_data::ephem_start\fP"
.PP
Definition at line 16 of file jpl_int.h.
.SS "double \fBjpl_eph_data::ephem_step\fP"
.PP
Definition at line 16 of file jpl_int.h.
.SS "long \fBjpl_eph_data::ephemeris_version\fP"
.PP
Definition at line 21 of file jpl_int.h.
.SS "FILE* \fBjpl_eph_data::ifile\fP"
.PP
Definition at line 28 of file jpl_int.h.
.SS "void* \fBjpl_eph_data::iinfo\fP"
.PP
Definition at line 27 of file jpl_int.h.
.SS "long \fBjpl_eph_data::ipt\fP[13][3]"
.PP
Definition at line 20 of file jpl_int.h.
.SS "long \fBjpl_eph_data::kernel_size\fP"
.PP
Definition at line 22 of file jpl_int.h.
.SS "long \fBjpl_eph_data::ncoeff\fP"
.PP
Definition at line 22 of file jpl_int.h.
.SS "long \fBjpl_eph_data::ncon\fP"
.PP
Definition at line 17 of file jpl_int.h.
.SS "double \fBjpl_eph_data::pvsun\fP[6]"
.PP
Definition at line 25 of file jpl_int.h.
.SS "long \fBjpl_eph_data::recsize\fP"
.PP
Definition at line 22 of file jpl_int.h.
.SS "long \fBjpl_eph_data::swap_bytes\fP"
.PP
Definition at line 23 of file jpl_int.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
