.TH "jpl_int.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpl_int.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBinterpolation_info\fP"
.br
.ti -1c
.RI "struct \fBjpl_eph_data\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_KERNEL_SIZE\fP   2036"
.br
.ti -1c
.RI "#define \fBJPL_HEADER_SIZE\fP   (5 * sizeof( double) + 41 * sizeof( long))"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define JPL_HEADER_SIZE   (5 * sizeof( double) + 41 * sizeof( long))"
.PP
Definition at line 11 of file jpl_int.h.
.PP
Referenced by jpl_init_ephemeris().
.SS "#define MAX_KERNEL_SIZE   2036"
.PP
Definition at line 4 of file jpl_int.h.
.PP
Referenced by jpl_init_ephemeris().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
