jpleph.cpp
NAME
jpleph.cpp -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include 'jpleph.h'
#include 'jpl_int.h'
Defines
#define TRUE 1
#define FALSE 0
#define SWAP_MACRO(A, B, TEMP) { TEMP = A; A = B; B = TEMP; }
Functions
double DLL_FUNC jpl_get_double (const void *ephem, const int value)
double DLL_FUNC jpl_get_long (const void *ephem, const int value)
int DLL_FUNC jpl_pleph (void *ephem, const double et, const int ntarg, const int ncent, double rrd[], const int calc_velocity)
void interp (struct interpolation_info *iinfo, const double coef[], const double t[2], const int ncf, const int ncm, const int na, const int ifl, double posvel[])
void swap_long_integer (void *ptr)
void swap_double (void *ptr, long count)
int DLL_FUNC jpl_state (void *ephem, const double et, const int list[12], double pv[][6], double nut[4], const int bary)
void *DLL_FUNC jpl_init_ephemeris (const char *ephemeris_filename, char nam[][6], double *val)
void DLL_FUNC jpl_close_ephemeris (void *ephem)
Define Documentation
#define FALSE 0
Definition at line 40 of file jpleph.cpp.
#define SWAP_MACRO(A, B, TEMP) { TEMP = A; A = B; B = TEMP; }
Definition at line 342 of file jpleph.cpp.
Referenced by swap_double(), and swap_long_integer().
#define TRUE 1
Definition at line 39 of file jpleph.cpp.
Function Documentation
void interp (struct interpolation_info * iinfo, const double coef[], const double t[2], const int ncf, const int ncm, const int na, const int ifl, double posvel[]) [static]
Definition at line 247 of file jpleph.cpp.
References i, j, l, interpolation_info::np, interpolation_info::nv, interpolation_info::pc, t, interpolation_info::twot, and interpolation_info::vc.
Referenced by jpl_state(), output(), and process().
void DLL_FUNC jpl_close_ephemeris (void * ephem)
Definition at line 663 of file jpleph.cpp.
References DLL_FUNC, and free().
double DLL_FUNC jpl_get_double (const void * ephem, const int value)
Definition at line 42 of file jpleph.cpp.
References DLL_FUNC.
double DLL_FUNC jpl_get_long (const void * ephem, const int value)
Definition at line 47 of file jpleph.cpp.
References DLL_FUNC.
void* DLL_FUNC jpl_init_ephemeris (const char * ephemeris_filename, char nam[][6], double * val)
Definition at line 546 of file jpleph.cpp.
References DLL_FUNC, i, j, JPL_HEADER_SIZE, L, MAX_KERNEL_SIZE, swap_double(), swap_long_integer(), title, and val.
Referenced by main().
int DLL_FUNC jpl_pleph (void * ephem, const double et, const int ntarg, const int ncent, double rrd[], const int calc_velocity)
Definition at line 98 of file jpleph.cpp.
References DLL_FUNC, i, jpl_state(), and k.
Referenced by main().
int DLL_FUNC jpl_state (void * ephem, const double et, const int list[12], double pv[][6], double nut[4], const int bary)
Definition at line 443 of file jpleph.cpp.
References buf, dest, DLL_FUNC, flag, i, interp(), j, swap_double(), and t.
Referenced by jpl_pleph().
void swap_double (void * ptr, long count) [static]
Definition at line 352 of file jpleph.cpp.
References SWAP_MACRO.
Referenced by jpl_init_ephemeris(), and jpl_state().
void swap_long_integer (void * ptr) [static]
Definition at line 344 of file jpleph.cpp.
References SWAP_MACRO.
Referenced by jpl_init_ephemeris().
Author
Generated automatically by Doxygen for imcat from the source code.