jpleph.h
NAME
jpleph.h -
SYNOPSIS
Defines
#define DLL_FUNC
#define JPL_EPHEM_START_JD 0
#define JPL_EPHEM_END_JD 8
#define JPL_EPHEM_STEP 16
#define JPL_EPHEM_N_CONSTANTS 24
#define JPL_EPHEM_AU_IN_KM 28
#define JPL_EPHEM_EARTH_MOON_RATIO 36
#define JPL_EPHEM_EPHEMERIS_VERSION 200
#define JPL_EPHEM_KERNEL_SIZE 204
#define JPL_EPHEM_KERNEL_RECORD_SIZE 208
#define JPL_EPHEM_KERNEL_NCOEFF 212
#define JPL_EPHEM_KERNEL_SWAP_BYTES 216
Functions
void *DLL_FUNC jpl_init_ephemeris (const char *ephemeris_filename, char nam[][6], double *val)
void DLL_FUNC jpl_close_ephemeris (void *ephem)
int DLL_FUNC jpl_state (void *ephem, const double et, const int list[12], double pv[][6], double nut[4], const int bary)
int DLL_FUNC jpl_pleph (void *ephem, const double et, const int ntarg, const int ncent, double rrd[], const int calc_velocity)
double DLL_FUNC jpl_get_double (const void *ephem, const int value)
double DLL_FUNC jpl_get_long (const void *ephem, const int value)
int DLL_FUNC make_sub_ephem (const void *ephem, const char *sub_filename, const double start_jd, const double end_jd)
Define Documentation
#define DLL_FUNC
Definition at line 21 of file jpleph.h.
Referenced by jpl_close_ephemeris(), jpl_get_double(), jpl_get_long(), jpl_init_ephemeris(), jpl_pleph(), and jpl_state().
#define JPL_EPHEM_AU_IN_KM 28
Definition at line 51 of file jpleph.h.
#define JPL_EPHEM_EARTH_MOON_RATIO 36
Definition at line 52 of file jpleph.h.
#define JPL_EPHEM_END_JD 8
Definition at line 48 of file jpleph.h.
#define JPL_EPHEM_EPHEMERIS_VERSION 200
Definition at line 53 of file jpleph.h.
#define JPL_EPHEM_KERNEL_NCOEFF 212
Definition at line 56 of file jpleph.h.
#define JPL_EPHEM_KERNEL_RECORD_SIZE 208
Definition at line 55 of file jpleph.h.
#define JPL_EPHEM_KERNEL_SIZE 204
Definition at line 54 of file jpleph.h.
#define JPL_EPHEM_KERNEL_SWAP_BYTES 216
Definition at line 57 of file jpleph.h.
#define JPL_EPHEM_N_CONSTANTS 24
Definition at line 50 of file jpleph.h.
#define JPL_EPHEM_START_JD 0
Definition at line 47 of file jpleph.h.
#define JPL_EPHEM_STEP 16
Definition at line 49 of file jpleph.h.
Function Documentation
void DLL_FUNC jpl_close_ephemeris (void * ephem)
Definition at line 663 of file jpleph.cpp.
References DLL_FUNC, and free().
double DLL_FUNC jpl_get_double (const void * ephem, const int value)
Definition at line 42 of file jpleph.cpp.
References DLL_FUNC.
double DLL_FUNC jpl_get_long (const void * ephem, const int value)
Definition at line 47 of file jpleph.cpp.
References DLL_FUNC.
void* DLL_FUNC jpl_init_ephemeris (const char * ephemeris_filename, char nam[][6], double * val)
Definition at line 546 of file jpleph.cpp.
References DLL_FUNC, i, j, JPL_HEADER_SIZE, L, MAX_KERNEL_SIZE, swap_double(), swap_long_integer(), title, and val.
Referenced by main().
int DLL_FUNC jpl_pleph (void * ephem, const double et, const int ntarg, const int ncent, double rrd[], const int calc_velocity)
Definition at line 98 of file jpleph.cpp.
References DLL_FUNC, i, jpl_state(), and k.
Referenced by main().
int DLL_FUNC jpl_state (void * ephem, const double et, const int list[12], double pv[][6], double nut[4], const int bary)
Definition at line 443 of file jpleph.cpp.
References buf, dest, DLL_FUNC, flag, i, interp(), j, swap_double(), and t.
Referenced by jpl_pleph().
int DLL_FUNC make_sub_ephem (const void * ephem, const char * sub_filename, const double start_jd, const double end_jd)
Author
Generated automatically by Doxygen for imcat from the source code.