kappa2stuff.c
NAME
kappa2stuff.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../fftlib/myfft.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	kappa2stuff --- generate shear etc from surface density\n\\n\SYNOPSIS\n\	kappa2stuff [options...] \n\		-f Nx Ny	# set size of fft box\n\\n\DESCRIPTION\n\	\'kappa2stuff\' reads a fits file containing a smooth kappa\n\	image (perhaps generated by \'lightmap ... ... | smooth ...\')\n\	and generates a grid of distortion, shear, deflection etc values.\n\	By default it does an FFT in a box twice size of original\n\	image to remove periodic BC effects. Use -f option to\n\	to set size of FFT (must be bigger than actual image)\n\	The output is in 'lc' catalogue format with items:\n\		x[2]		# position\n\		kappa		# surface density as input\n\		def[2]		# deflection\n\		lambda[2]	# eigenvalues of distortion tensor\n\		e[2]		# distortion\n\		R		# axis ratio\n\		phi		# position angle\n\		parity		# parity\n\		amp		# magnification\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define PI M_PI
Functions
float zero (float kx, float ky)
float def1 (float kx, float ky)
float def2 (float kx, float ky)
float gamma1 (float kx, float ky)
float gamma2 (float kx, float ky)
int main (int argc, char *argv[])
Define Documentation
#define PI M_PI
Definition at line 43 of file kappa2stuff.c.
#define usage '\n\n\n\NAME\n\	kappa2stuff --- generate shear etc from surface density\n\\n\SYNOPSIS\n\	kappa2stuff [options...] \n\		-f Nx Ny	# set size of fft box\n\\n\DESCRIPTION\n\	\'kappa2stuff\' reads a fits file containing a smooth kappa\n\	image (perhaps generated by \'lightmap ... ... | smooth ...\')\n\	and generates a grid of distortion, shear, deflection etc values.\n\	By default it does an FFT in a box twice size of original\n\	image to remove periodic BC effects. Use -f option to\n\	to set size of FFT (must be bigger than actual image)\n\	The output is in 'lc' catalogue format with items:\n\		x[2]		# position\n\		kappa		# surface density as input\n\		def[2]		# deflection\n\		lambda[2]	# eigenvalues of distortion tensor\n\		e[2]		# distortion\n\		R		# axis ratio\n\		phi		# position angle\n\		parity		# parity\n\		amp		# magnification\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file kappa2stuff.c.
Function Documentation
float def1 (float kx, float ky)
Definition at line 167 of file kappa2stuff.c.
References kk.
Referenced by main().
float def2 (float kx, float ky)
Definition at line 179 of file kappa2stuff.c.
References kk.
Referenced by main().
float gamma1 (float kx, float ky)
Definition at line 190 of file kappa2stuff.c.
References kk.
Referenced by main().
float gamma2 (float kx, float ky)
Definition at line 201 of file kappa2stuff.c.
References kk.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 52 of file kappa2stuff.c.
References alloc_fft(), allocFloatArray(), cfilter(), d, def1(), def2(), error_exit, exit(), fft_type, filter(), fits, forward_fft(), g(), gamma1(), gamma2(), i, inverse_fft(), j, lcpipe, mag, N1, N2, Nx, Ny, phi, read2Dfloatimage(), usage, and zero().
float zero (float kx, float ky)
Author
Generated automatically by Doxygen for imcat from the source code.