.TH "keplerorbit" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
keplerorbit \- 
.SH SYNOPSIS
.br
.PP
\fC#include <kepler.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBe\fP"
.br
.ti -1c
.RI "double \fBi\fP"
.br
.ti -1c
.RI "double \fBomega\fP"
.br
.ti -1c
.RI "double \fBOmega\fP"
.br
.ti -1c
.RI "double \fBM\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double \fBkeplerorbit::a\fP"
.PP
Definition at line 6 of file orbitutils/kepler.h.
.PP
Referenced by assignkeplerorbitfrombuffer(), cartesiantokepler(), chisquared(), fillbufferfromkeplerorbit(), keplertocartesian(), keplertocartesian_shapiro(), and main().
.SS "double \fBkeplerorbit::e\fP"
.PP
Definition at line 7 of file orbitutils/kepler.h.
.PP
Referenced by assignkeplerorbitfrombuffer(), cartesiantokepler(), fillbufferfromkeplerorbit(), keplertocartesian(), and keplertocartesian_shapiro().
.SS "double \fBkeplerorbit::i\fP"
.PP
Definition at line 8 of file orbitutils/kepler.h.
.PP
Referenced by assignkeplerorbitfrombuffer(), cartesiantokepler(), fillbufferfromkeplerorbit(), keplertocartesian(), and keplertocartesian_shapiro().
.SS "double \fBkeplerorbit::M\fP"
.PP
Definition at line 11 of file orbitutils/kepler.h.
.PP
Referenced by assignkeplerorbitfrombuffer(), cartesiantokepler(), chisquared(), fillbufferfromkeplerorbit(), keplertocartesian(), keplertocartesian_shapiro(), and main().
.SS "double \fBkeplerorbit::Omega\fP"
.PP
Definition at line 10 of file orbitutils/kepler.h.
.PP
Referenced by assignkeplerorbitfrombuffer(), cartesiantokepler(), fillbufferfromkeplerorbit(), keplertocartesian(), and keplertocartesian_shapiro().
.SS "double \fBkeplerorbit::omega\fP"
.PP
Definition at line 9 of file orbitutils/kepler.h.
.PP
Referenced by assignkeplerorbitfrombuffer(), cartesiantokepler(), fillbufferfromkeplerorbit(), keplertocartesian(), and keplertocartesian_shapiro().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
