kepler_jh.c
NAME
kepler_jh.c -
SYNOPSIS
#include 'f2c.h'
Data Structures
struct consts_1_
struct consts_2_
Defines
#define consts_1 (*(struct consts_1_ *) &consts_)
#define consts_2 (*(struct consts_2_ *) &consts_)
Functions
integer ilmnts_ (doublereal *elem, doublereal *emu, doublereal *t, doublereal *r__, doublereal *rd)
integer irrdot_ (doublereal *elem, doublereal *emu, doublereal *t, doublereal *r__, doublereal *rd)
integer kepler_ (doublereal *em, doublereal *e, doublereal *ea)
int rotate_ (doublereal *r__, doublereal *a, integer *k, doublereal *rz)
int vcopy_ (doublereal *v1, doublereal *v2)
int vsum_ (doublereal *x, doublereal *y, doublereal *z__)
int vsub_ (doublereal *x, doublereal *y, doublereal *z__)
int vzero_ (doublereal *x)
doublereal vdot_ (doublereal *x, doublereal *y)
int vxp_ (doublereal *x, doublereal *y, doublereal *z__)
doublereal vlen_ (doublereal *x)
doublereal stp_ (doublereal *x, doublereal *y, doublereal *z__)
Variables
struct {
   doublereal e_1 [7]
} consts_
integer c__3 = 3
integer c__1 = 1
Define Documentation
#define consts_1 (*(struct consts_1_ *) &consts_)
Definition at line 17 of file kepler_jh.c.
Referenced by ilmnts_(), and kepler_().
#define consts_2 (*(struct consts_2_ *) &consts_)
Definition at line 18 of file kepler_jh.c.
Function Documentation
integer ilmnts_ (doublereal * elem, doublereal * emu, doublereal * t, doublereal * r__, doublereal * rd)
Definition at line 37 of file kepler_jh.c.
References consts_1, doublereal, f, integer, t, v, vdot_(), vlen_(), and vxp_().
Referenced by cartesiantokepler().
integer irrdot_ (doublereal * elem, doublereal * emu, doublereal * t, doublereal * r__, doublereal * rd)
Definition at line 125 of file kepler_jh.c.
References c__1, c__3, doublereal, f, integer, kepler_(), rotate_(), and t.
Referenced by keplertocartesian().
integer kepler_ (doublereal * em, doublereal * e, doublereal * ea)
Definition at line 199 of file kepler_jh.c.
References abs, consts_1, doublereal, e, and integer.
Referenced by irrdot_().
int rotate_ (doublereal * r__, doublereal * a, integer * k, doublereal * rz)
Definition at line 238 of file kepler_jh.c.
References a, doublereal, ftnlen, integer, j, and k.
Referenced by irrdot_().
doublereal stp_ (doublereal * x, doublereal * y, doublereal * z__)
Definition at line 432 of file kepler_jh.c.
References doublereal, x, and y.
int vcopy_ (doublereal * v1, doublereal * v2)
Definition at line 287 of file kepler_jh.c.
References doublereal.
doublereal vdot_ (doublereal * x, doublereal * y)
Definition at line 382 of file kepler_jh.c.
References doublereal, x, and y.
Referenced by ilmnts_(), and vlen_().
doublereal vlen_ (doublereal * x)
Definition at line 411 of file kepler_jh.c.
References doublereal, vdot_(), and x.
Referenced by ilmnts_().
int vsub_ (doublereal * x, doublereal * y, doublereal * z__)
Definition at line 329 of file kepler_jh.c.
References doublereal, ftnlen, integer, x, and y.
int vsum_ (doublereal * x, doublereal * y, doublereal * z__)
Definition at line 301 of file kepler_jh.c.
References doublereal, ftnlen, integer, x, and y.
int vxp_ (doublereal * x, doublereal * y, doublereal * z__)
Definition at line 397 of file kepler_jh.c.
References doublereal, x, and y.
Referenced by ilmnts_().
int vzero_ (doublereal * x)
Definition at line 357 of file kepler_jh.c.
References doublereal, ftnlen, integer, and x.
Variable Documentation
integer c__1 = 1 [static]
Definition at line 31 of file kepler_jh.c.
Referenced by irrdot_().
integer c__3 = 3 [static]
Definition at line 30 of file kepler_jh.c.
Referenced by irrdot_().
struct { ... } consts_
doublereal e_1[7]
Definition at line 23 of file kepler_jh.c.
Author
Generated automatically by Doxygen for imcat from the source code.