kepler.c
NAME
kepler.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'vectors.h'
#include 'kepler.h'
Defines
#define KEPLER_TINY 1.e-15
Functions
void assignkeplerorbitfrombuffer (keplerorbit *orbit, double *buffer)
void fillbufferfromkeplerorbit (keplerorbit *orbit, double *buffer)
void keplertocartesian (keplerorbit *theorbit, double *r, double *v)
void keplertocartesian_shapiro (keplerorbit *theorbit, double *r, double *v)
void cartesiantokepler (double *r, double *v, keplerorbit *theorbit)
Define Documentation
#define KEPLER_TINY 1.e-15
Definition at line 16 of file kepler_sneeuw/kepler.c.
Referenced by keplertocartesian(), and keplertocartesian_shapiro().
Function Documentation
void assignkeplerorbitfrombuffer (keplerorbit * orbit, double * buffer)
Definition at line 18 of file kepler_sneeuw/kepler.c.
References keplerorbit::a, keplerorbit::e, keplerorbit::i, keplerorbit::M, keplerorbit::Omega, and keplerorbit::omega.
void cartesiantokepler (double * r, double * v, keplerorbit * theorbit)
Definition at line 125 of file kepler_sneeuw/kepler.c.
References keplerorbit::a, a, assign(), copy(), cross(), dot(), keplerorbit::e, E, e, free(), h, keplerorbit::i, i, j, k, length(), keplerorbit::M, M, n, keplerorbit::Omega, keplerorbit::omega, omega(), r, scale(), theorbit, and v.
void fillbufferfromkeplerorbit (keplerorbit * orbit, double * buffer)
Definition at line 28 of file kepler_sneeuw/kepler.c.
References keplerorbit::a, keplerorbit::e, keplerorbit::i, keplerorbit::M, keplerorbit::Omega, and keplerorbit::omega.
void keplertocartesian (keplerorbit * theorbit, double * r, double * v)
Definition at line 39 of file kepler_sneeuw/kepler.c.
References keplerorbit::a, a, assign(), keplerorbit::e, e, E, keplerorbit::i, i, KEPLER_TINY, keplerorbit::M, M, keplerorbit::Omega, keplerorbit::omega, omega(), r, rotx(), rotz(), scale(), theorbit, and v.
void keplertocartesian_shapiro (keplerorbit * theorbit, double * r, double * v)
Definition at line 79 of file kepler_sneeuw/kepler.c.
References keplerorbit::a, A, a, assign(), B, keplerorbit::e, e, E, keplerorbit::i, i, j, KEPLER_TINY, keplerorbit::M, M, keplerorbit::Omega, keplerorbit::omega, omega(), r, theorbit, and v.
Author
Generated automatically by Doxygen for imcat from the source code.