kernels.h
NAME
kernels.h -
SYNOPSIS
Functions
void circkernel (double *K, double x0, double y0, double x, double y, double R, double eps)
void rectkernel (double *K, double *alpha, double x0, double y0, double x, double y, double NX, double NY, double eps)
double cutoff (double r, double p, double eps)
Function Documentation
void circkernel (double * K, double x0, double y0, double x, double y, double R, double eps)
Definition at line 20 of file kernels.c.
References a1, a2, cutoff(), EPS, K, r, W, x, y, Y, and z.
double cutoff (double r, double p, double eps)
Definition at line 161 of file kernels.c.
References EPS, r, and x.
Referenced by circkernel(), and rectkernel().
void rectkernel (double * K, double * alpha, double x0, double y0, double x, double y, double NX, double NY, double eps)
Definition at line 81 of file kernels.c.
References a, alpha, cutoff(), EPS, i, j, K, L, r, sign, W, x, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.