.TH "label" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
label \- 
.SH SYNOPSIS
.br
.PP
\fC#include <labels.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "\fBlabel\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBlabel\fP* \fBlabel::next\fP"
.PP
Definition at line 9 of file labels.h.
.PP
Referenced by main().
.SS "char* \fBlabel::text\fP"
.PP
Definition at line 8 of file labels.h.
.PP
Referenced by main().
.SS "float \fBlabel::x\fP"
.PP
Definition at line 6 of file labels.h.
.PP
Referenced by main().
.SS "float \fBlabel::y\fP"
.PP
Definition at line 7 of file labels.h.
.PP
Referenced by main().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
