laplace3.c
NAME
laplace3.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
#include 'Ffunc.h'
#include 'gaussdev.h'
#include 'makedddotr.h'
Defines
#define usage '\nNAME\n\	laplace3 - compute an approximate orbit from 3 observations\n\\n\SYNOPSIS\n\	laplace3\n\\n\DESCRIPTION\n\	laplace3 reads an lc format catalog (probably generated by makeobs)\n\	from stdin. This calatog must contain 3 lines, each containing\n\	at least:\n\		t		time\n\		sigma	astrometry precision in radians\n\		re[]	earth's position\n\		ve[]	earth's velocity\n\		rho[]	position of observatory vs earth\n\		ra[]	asteroid's position\n\		va[]	asteroid's velocity\n\\n\	It then solves for the phase space coordinates of the asteroid\n\	at t=0. Currently it does this graphically.\n\\n\	Times are given in units of earths dynamical time (approx\n\	57.21 days in this model).\n\\n\	Distances are expressed in AU.\n\\n\SEE ALSO\n\	maketestpscoords.pl makeobs\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
#define DTINY 1.0e-20
#define FTOL 1.0e-8
#define NITERMAX 100
Functions
int newtonraphson (double *d, double Fobs, double mu)
main (int argc, char *argv[])
Define Documentation
#define DTINY 1.0e-20
Definition at line 41 of file laplace3.c.
Referenced by main().
#define FTOL 1.0e-8
Definition at line 42 of file laplace3.c.
Referenced by main(), and newtonraphson().
#define NITERMAX 100
Definition at line 43 of file laplace3.c.
Referenced by main(), and newtonraphson().
#define usage '\nNAME\n\	laplace3 - compute an approximate orbit from 3 observations\n\\n\SYNOPSIS\n\	laplace3\n\\n\DESCRIPTION\n\	laplace3 reads an lc format catalog (probably generated by makeobs)\n\	from stdin. This calatog must contain 3 lines, each containing\n\	at least:\n\		t		time\n\		sigma	astrometry precision in radians\n\		re[]	earth's position\n\		ve[]	earth's velocity\n\		rho[]	position of observatory vs earth\n\		ra[]	asteroid's position\n\		va[]	asteroid's velocity\n\\n\	It then solves for the phase space coordinates of the asteroid\n\	at t=0. Currently it does this graphically.\n\\n\	Times are given in units of earths dynamical time (approx\n\	57.21 days in this model).\n\\n\	Distances are expressed in AU.\n\\n\SEE ALSO\n\	maketestpscoords.pl makeobs\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 9 of file laplace3.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 47 of file laplace3.c.
References copy(), d, dFdd(), diff(), dmax, dmin, dot(), dr, DTINY, exit(), F(), fprintvec(), i, iota, ipf, length(), n, nobs, nt, r, ra, re, rho, scale(), sigma, t, usage, and va.
int newtonraphson (double * d, double Fobs, double mu)
Definition at line 224 of file laplace3.c.
References d, dFdd(), exit(), F(), FTOL, and NITERMAX.
Author
Generated automatically by Doxygen for imcat from the source code.