lc.c
NAME
lc.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include '../../catlib/cat.h'
#include 'getop.h'
#include 'stack.h'
#include 'operators.h'
#include 'rpn.h'
#include 'error.h'
#include 'lc.h'
Defines
#define STD_INPUT_MODE 0
#define TAB_INPUT_MODE 1
#define STD_OUTPUT_MODE 0
#define COUNT_MODE 1
#define SORT_MODE 2
#define HEADER_ONLY_MODE 3
#define NO_HEADER_MODE 4
#define FULL_HEADER_MODE 0
#define LABELS_ONLY_MODE 1
#define NO_CHOP_MODE 0
#define CHOP_HEAD_MODE 1
#define CHOP_TAIL_MODE 2
#define SORT_ASCENDING 0
#define SORT_DESCENDING 1
#define MAX_FUNCTIONS 1024
Functions
main (int argc, char *argv[])
void parsename (char *string)
void parseheaderexpr (char *string)
void addheadercontents (item *theitem, char *string, cathead *thecathead)
char * quote (char *string)
void readtabheader (void)
void dospecialname (char *string)
void chopcomments (cathead *thecathead, int mode, int nchop)
void adddate (void)
int objcmp (const void *ptr1, const void *ptr2)
Variables
cathead * inputcathead
cathead * outputcathead
object * inputobject = NULL *outputobject
int nrpn = 0 copycomments sortmode
char commenttag = '#'
double inputobjectcount = 0 outputobjectcount = 0
char * inputcountname = NULL *outputcountname = NULL
rpnfunc * rpnfunction [MAX_FUNCTIONS]
char * rpnname [MAX_FUNCTIONS]
char * rpnstring [MAX_FUNCTIONS]
Define Documentation
#define CHOP_HEAD_MODE 1
Definition at line 35 of file lc.c.
Referenced by chopcomments(), and main().
#define CHOP_TAIL_MODE 2
Definition at line 36 of file lc.c.
Referenced by chopcomments(), and main().
#define COUNT_MODE 1
Definition at line 24 of file lc.c.
Referenced by main().
#define FULL_HEADER_MODE 0
Definition at line 30 of file lc.c.
Referenced by main().
#define HEADER_ONLY_MODE 3
Definition at line 26 of file lc.c.
Referenced by main().
#define LABELS_ONLY_MODE 1
Definition at line 31 of file lc.c.
Referenced by main().
#define MAX_FUNCTIONS 1024
Definition at line 42 of file lc.c.
Referenced by parsename().
#define NO_CHOP_MODE 0
Definition at line 34 of file lc.c.
Referenced by main().
#define NO_HEADER_MODE 4
Definition at line 27 of file lc.c.
Referenced by main().
#define SORT_ASCENDING 0
Definition at line 39 of file lc.c.
Referenced by main(), and objcmp().
#define SORT_DESCENDING 1
Definition at line 40 of file lc.c.
Referenced by main().
#define SORT_MODE 2
Definition at line 25 of file lc.c.
Referenced by main().
#define STD_INPUT_MODE 0
Definition at line 19 of file lc.c.
Referenced by main().
#define STD_OUTPUT_MODE 0
Definition at line 23 of file lc.c.
Referenced by main().
#define TAB_INPUT_MODE 1
Definition at line 20 of file lc.c.
Referenced by main().
Function Documentation
void adddate (void)
Definition at line 567 of file lc.c.
References item::addr, allocitemcontents(), error_exit, cathead::headeritembase, installitem(), newitem(), outputcathead, pos, and TEXT_TYPE.
Referenced by main().
void addheadercontents (item * theitem, char * string, cathead * thecathead)
Definition at line 457 of file lc.c.
References item::addr, allocitemcontents(), cathead::headeritembase, installitem(), and sscanitem().
void chopcomments (cathead * thecathead, int mode, int nchop)
Definition at line 535 of file lc.c.
References CHOP_HEAD_MODE, CHOP_TAIL_MODE, cathead::commentbase, error_exit, and comment::next.
Referenced by main().
void dospecialname (char * string)
Definition at line 502 of file lc.c.
References addobjectitem(), item::addr, copyitem(), error_exit, inputcathead, inputobjectcount, cathead::itemlist, newitem(), cathead::nobjectitems, NUM_TYPE, and outputcathead.
Referenced by parsename().
main (int argc, char * argv[])
Definition at line 57 of file lc.c.
References addargscomment(), addcomment(), adddate(), addobjectitem(), item::addr, object::addrlist, allocitemcontents(), BINARY_FILE_TYPE, CHOP_HEAD_MODE, CHOP_TAIL_MODE, chopcomments(), commenttag, connectobjecttocathead(), copyheaderinfo(), copyitem(), copyitemcontents(), COUNT_MODE, deleteheaderitem(), deleteobjectitem(), error_exit, evalrpnfunction(), exit(), FULL_HEADER_MODE, getcatipfiletype(), getcatopfiletype(), getheaderitem(), HEADER_ONLY_MODE, inputcathead, inputobject, inputobjectcount, cathead::itemlist, LABELS_ONLY_MODE, newitem(), newobject(), newrpnfunction(), sortobject::next, item::next, NO_CHOP_MODE, NO_HEADER_MODE, cathead::nobjectitems, nrpn, NUM_TYPE, sortobject::obj, objcmp(), cathead::objectitembase, outputcathead, parseheaderexpr(), parsename(), quote(), readcathead(), readobject(), readtabheader(), rpnfunc::result, rpnfunction, setcatopfiletype(), setsourcecathead(), SORT_ASCENDING, SORT_DESCENDING, SORT_MODE, sortobject::sortval, sscannewitem(), STD_INPUT_MODE, STD_OUTPUT_MODE, item::swapbytesi, TAB_INPUT_MODE, TEXT_FILE_TYPE, TEXT_TYPE, writecathead(), writeitem(), writelabel(), and writeobject().
int objcmp (const void * ptr1, const void * ptr2)
Definition at line 595 of file lc.c.
References SORT_ASCENDING.
Referenced by main().
void parseheaderexpr (char * string)
Definition at line 436 of file lc.c.
References error_exit, evalrpnfunction(), getword(), cathead::headeritembase, installitem(), newrpnfunction(), outputcathead, and rpnfunc::result.
Referenced by main().
void parsename (char * string)
Definition at line 403 of file lc.c.
References addobjectitem(), item::addr, copyitem(), dospecialname(), error_exit, evalrpnfunction(), getobjectitem(), getword(), inputcathead, MAX_FUNCTIONS, newrpnfunction(), nrpn, outputcathead, rpnfunction, rpnname, and rpnstring.
Referenced by main().
char* quote (char * string)
Definition at line 464 of file lc.c.
Referenced by main().
void readtabheader (void)
Definition at line 475 of file lc.c.
References addcomment(), c, commenttag, line, and outputcathead.
Referenced by main().
Variable Documentation
char commenttag = '#' [static]
Definition at line 51 of file lc.c.
Referenced by main(), and readtabheader().
cathead* inputcathead [static]
Definition at line 48 of file lc.c.
Referenced by dospecialname(), main(), and parsename().
char* inputcountname = NULL *outputcountname = NULL [static]
Definition at line 53 of file lc.c.
object* inputobject = NULL *outputobject [static]
Definition at line 49 of file lc.c.
Referenced by main().
double inputobjectcount = 0 outputobjectcount = 0 [static]
Definition at line 52 of file lc.c.
Referenced by dospecialname(), and main().
int nrpn = 0 copycomments sortmode [static]
Definition at line 50 of file lc.c.
Referenced by main(), and parsename().
cathead * outputcathead [static]
Definition at line 48 of file lc.c.
Referenced by adddate(), dospecialname(), main(), parseheaderexpr(), parsename(), and readtabheader().
rpnfunc* rpnfunction[MAX_FUNCTIONS] [static]
Definition at line 54 of file lc.c.
Referenced by main(), and parsename().
char* rpnname[MAX_FUNCTIONS] [static]
Definition at line 55 of file lc.c.
Referenced by parsename().
char * rpnstring[MAX_FUNCTIONS] [static]
Definition at line 55 of file lc.c.
Referenced by parsename().
Author
Generated automatically by Doxygen for imcat from the source code.