lc.h
NAME
lc.h -
SYNOPSIS
Data Structures
struct sortobject
Typedefs
typedef sortobject sortobject
Functions
void parsename (char *string)
void parseheaderexpr (char *string)
void addheadercontents (item *theitem, char *string, cathead *thecathead)
char * quote (char *string)
void readtabheader (void)
void dospecialname (char *string)
void chopcomments (cathead *thecathead, int mode, int nchop)
void adddate (void)
int objcmp (const void *ptr1, const void *ptr2)
Typedef Documentation
typedef struct sortobject sortobject
Function Documentation
void adddate (void)
Definition at line 567 of file lc.c.
References item::addr, allocitemcontents(), error_exit, cathead::headeritembase, installitem(), newitem(), outputcathead, pos, and TEXT_TYPE.
Referenced by main().
void addheadercontents (item * theitem, char * string, cathead * thecathead)
Definition at line 457 of file lc.c.
References item::addr, allocitemcontents(), cathead::headeritembase, installitem(), and sscanitem().
void chopcomments (cathead * thecathead, int mode, int nchop)
Definition at line 535 of file lc.c.
References CHOP_HEAD_MODE, CHOP_TAIL_MODE, cathead::commentbase, error_exit, and comment::next.
Referenced by main().
void dospecialname (char * string)
Definition at line 502 of file lc.c.
References addobjectitem(), item::addr, copyitem(), error_exit, inputcathead, inputobjectcount, cathead::itemlist, newitem(), cathead::nobjectitems, NUM_TYPE, and outputcathead.
Referenced by parsename().
int objcmp (const void * ptr1, const void * ptr2)
Definition at line 595 of file lc.c.
References SORT_ASCENDING.
Referenced by main().
void parseheaderexpr (char * string)
Definition at line 436 of file lc.c.
References error_exit, evalrpnfunction(), getword(), cathead::headeritembase, installitem(), newrpnfunction(), outputcathead, and rpnfunc::result.
Referenced by main().
void parsename (char * string)
Definition at line 403 of file lc.c.
References addobjectitem(), item::addr, copyitem(), dospecialname(), error_exit, evalrpnfunction(), getobjectitem(), getword(), inputcathead, MAX_FUNCTIONS, newrpnfunction(), nrpn, outputcathead, rpnfunction, rpnname, and rpnstring.
Referenced by main().
char* quote (char * string)
Definition at line 464 of file lc.c.
Referenced by main().
void readtabheader (void)
Definition at line 475 of file lc.c.
References addcomment(), c, commenttag, line, and outputcathead.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.