.TH "lcfilter.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lcfilter.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNOEDIT_MODE\fP   0"
.br
.ti -1c
.RI "#define \fBREJECT_MODE\fP   1"
.br
.ti -1c
.RI "#define \fBSELECT_MODE\fP   2"
.br
.ti -1c
.RI "#define \fBMASK_MODE\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstartfilter\fP (int coordsargcount, char *coordsarg[], int editmode)"
.br
.ti -1c
.RI "int \fBaddfiltercondition\fP (float \fBx1\fP, float \fBx2\fP, float y1, float y2)"
.br
.ti -1c
.RI "void \fBdofilter\fP (char *tempfilename)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MASK_MODE   3"
.PP
Definition at line 8 of file lcfilter.h.
.PP
Referenced by main().
.SS "#define NOEDIT_MODE   0"
.PP
Definition at line 5 of file lcfilter.h.
.PP
Referenced by main().
.SS "#define REJECT_MODE   1"
.PP
Definition at line 6 of file lcfilter.h.
.PP
Referenced by dofilter(), and main().
.SS "#define SELECT_MODE   2"
.PP
Definition at line 7 of file lcfilter.h.
.PP
Referenced by main().
.SH "Function Documentation"
.PP 
.SS "int addfiltercondition (float x1, float x2, float y1, float y2)"
.PP
Definition at line 35 of file lcfilter.c.
.PP
References exit(), firstclause, lcfilter, LCFILTERSTRINGLENGTH, xname, and yname.
.PP
Referenced by main().
.SS "void dofilter (char * tempfilename)"
.PP
Definition at line 52 of file lcfilter.c.
.PP
References exit(), lcfilter, mode, and REJECT_MODE.
.PP
Referenced by main().
.SS "void startfilter (int coordsargcount, char * coordsarg[], int editmode)"
.PP
Definition at line 13 of file lcfilter.c.
.PP
References exit(), firstclause, lcfilter, mode, xname, and yname.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
