lcfilter.h
NAME
lcfilter.h -
SYNOPSIS
Defines
#define NOEDIT_MODE 0
#define REJECT_MODE 1
#define SELECT_MODE 2
#define MASK_MODE 3
Functions
void startfilter (int coordsargcount, char *coordsarg[], int editmode)
int addfiltercondition (float x1, float x2, float y1, float y2)
void dofilter (char *tempfilename)
Define Documentation
#define MASK_MODE 3
Definition at line 8 of file lcfilter.h.
Referenced by main().
#define NOEDIT_MODE 0
Definition at line 5 of file lcfilter.h.
Referenced by main().
#define REJECT_MODE 1
Definition at line 6 of file lcfilter.h.
Referenced by dofilter(), and main().
#define SELECT_MODE 2
Definition at line 7 of file lcfilter.h.
Referenced by main().
Function Documentation
int addfiltercondition (float x1, float x2, float y1, float y2)
Definition at line 35 of file lcfilter.c.
References exit(), firstclause, lcfilter, LCFILTERSTRINGLENGTH, xname, and yname.
Referenced by main().
void dofilter (char * tempfilename)
Definition at line 52 of file lcfilter.c.
References exit(), lcfilter, mode, and REJECT_MODE.
Referenced by main().
void startfilter (int coordsargcount, char * coordsarg[], int editmode)
Definition at line 13 of file lcfilter.c.
References exit(), firstclause, lcfilter, mode, xname, and yname.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.