lcfilter.c
NAME
lcfilter.c -
SYNOPSIS
#include <stdio.h>
#include 'lcfilter.h'
Defines
#define LCFILTERSTRINGLENGTH 4096
Functions
void startfilter (int coordsargcount, char *coordsarg[], int editmode)
int addfiltercondition (float x1, float x2, float y1, float y2)
void dofilter (char *tempfilename)
Variables
char lcfilter [LCFILTERSTRINGLENGTH]
char xname [64]
char yname [64]
int firstclause
int mode
Define Documentation
#define LCFILTERSTRINGLENGTH 4096
Definition at line 8 of file lcfilter.c.
Referenced by addfiltercondition().
Function Documentation
int addfiltercondition (float x1, float x2, float y1, float y2)
Definition at line 35 of file lcfilter.c.
References exit(), firstclause, lcfilter, LCFILTERSTRINGLENGTH, xname, and yname.
Referenced by main().
void dofilter (char * tempfilename)
Definition at line 52 of file lcfilter.c.
References exit(), lcfilter, mode, and REJECT_MODE.
Referenced by main().
void startfilter (int coordsargcount, char * coordsarg[], int editmode)
Definition at line 13 of file lcfilter.c.
References exit(), firstclause, lcfilter, mode, xname, and yname.
Referenced by main().
Variable Documentation
int firstclause [static]
Definition at line 11 of file lcfilter.c.
Referenced by addfiltercondition(), and startfilter().
char lcfilter[LCFILTERSTRINGLENGTH] [static]
Definition at line 10 of file lcfilter.c.
Referenced by addfiltercondition(), dofilter(), and startfilter().
int mode [static]
Definition at line 11 of file lcfilter.c.
Referenced by dofilter(), and startfilter().
char xname[64] [static]
Definition at line 10 of file lcfilter.c.
Referenced by addfiltercondition(), and startfilter().
char yname[64] [static]
Definition at line 10 of file lcfilter.c.
Referenced by addfiltercondition(), and startfilter().
Author
Generated automatically by Doxygen for imcat from the source code.