leastsquares.c
NAME
leastsquares.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
#include 'Ffunc.h'
#include 'utils/gaussdev.h'
#include 'tcl.h'
Defines
#define usage '\nNAME\n\	leastsquares\n\\n\SYNOPSIS\n\	leastsquares obscat t nsteps xfactor\n\\n\DESCRIPTION\n\	leastsquares finds a minimum chi-squared solution for a set of observations\n\	given a starting point (possible generated by laplace3).\n\\n\	leastsquares reads an lc format catalog from stdin containing the\n\	a preliminary solution ra[3], va[3] and an estimate of the uncertainty\n\	in the distance, sigmad and d. These are generated by laplace3.\n\\n\	It then reads a set of observations from obscat, and finds a minimum\n\	chi^2 by dynamically propagating a set of points.\n\\n\SEE ALSO\n\	makeobs_inertial makeobs_circ laplace3 tcl_evolve r2n leastsquares\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
double chisquared (double *x)
void powell (double p[], double **xi, int n, double ftol, int *iter, double *fret, double(*func)(double[]))
void getbasis (double *n, double *i0, double *i1)
double det (double **M, int n)
void getC (void)
void printmatrix (double **m, int n, char *tag)
void findmin (double *r0, double *v0, double *x)
main (int argc, char *argv[])
Variables
double ** re
double ** rho
double ** nobs
double ** dnobs
double * n
double * t
double * sigma
double * ra
double * va
double ** tmp
double * iota [2]
double ** M
double * tmpvec
double ** C
double arcsec
double * n0
int nt
int * indx
double ** powell_xi
double powell_ftol
double powell_fret
Define Documentation
#define usage '\nNAME\n\	leastsquares\n\\n\SYNOPSIS\n\	leastsquares obscat t nsteps xfactor\n\\n\DESCRIPTION\n\	leastsquares finds a minimum chi-squared solution for a set of observations\n\	given a starting point (possible generated by laplace3).\n\\n\	leastsquares reads an lc format catalog from stdin containing the\n\	a preliminary solution ra[3], va[3] and an estimate of the uncertainty\n\	in the distance, sigmad and d. These are generated by laplace3.\n\\n\	It then reads a set of observations from obscat, and finds a minimum\n\	chi^2 by dynamically propagating a set of points.\n\\n\SEE ALSO\n\	makeobs_inertial makeobs_circ laplace3 tcl_evolve r2n leastsquares\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 9 of file leastsquares.c.
Function Documentation
double chisquared (double * x)
Definition at line 281 of file test/fitstack.c.
double det (double ** M, int n)
Definition at line 449 of file leastsquares.c.
References a, b, indx, M, myludcmp(), n, and tmp.
Referenced by counterclockwise(), counterclockwiseadapt(), getplane(), incircle(), incircleadapt(), inversedoit(), inverseinit(), linmodelsolve(), and main().
void findmin (double * r0, double * v0, double * x)
Definition at line 502 of file leastsquares.c.
References chisquared(), i, iota, n0, powell(), powell_fret, powell_ftol, powell_xi, and x.
Referenced by main().
void getbasis (double * n, double * i0, double * i1)
Referenced by main().
void getC (void)
Definition at line 467 of file leastsquares.c.
References alpha, arcsec, C, i, iota, j, M, and tmpvec.
Referenced by main().
main (int argc, char * argv[])
Definition at line 47 of file leastsquares.c.
References a, alpha, arcsec, b, C, c, chi2(), chisquared(), copy(), d, det(), diff(), dnobs, dr, dx, exit(), findmin(), fprintvec(), gaussdev(), getbasis(), getC(), i, indx, invertmatrix(), iota, ipf, j, length(), M, n, n0, nobs, nt, powell_xi, printmatrix(), printvec(), r, ra, re, rho, scale(), sigma, t, tcl(), tmp, tmpvec, usage, v, va, and x.
void powell (double p[], double ** xi, int n, double ftol, int * iter, double * fret, double(* func)(double[]))
Definition at line 15 of file orbits/orbitutils/powell_dbl.c.
void printmatrix (double ** m, int n, char * tag)
Definition at line 488 of file leastsquares.c.
References a, b, m, and n.
Referenced by main().
Variable Documentation
double arcsec
Definition at line 33 of file leastsquares.c.
double ** C
Definition at line 33 of file leastsquares.c.
double ** dnobs
Definition at line 32 of file leastsquares.c.
Referenced by main().
int * indx
Definition at line 34 of file leastsquares.c.
Referenced by det(), iis_checksum(), iisdisplay(), invertmatrix(), linmodelinit(), linmodelsolve(), lubksb(), ludcmp(), main(), mylubksb(), and myludcmp().
double* iota[2]
Definition at line 33 of file leastsquares.c.
double ** M
Definition at line 33 of file leastsquares.c.
Referenced by accumulate(), cartesiantokepler(), det(), fitdistortions(), getC(), Getshape(), keplertocartesian(), keplertocartesian_shapiro(), main(), make_r(), make_re(), and write2Dpolymodel().
double * n
Definition at line 32 of file leastsquares.c.
double * n0
Definition at line 33 of file leastsquares.c.
double ** nobs
Definition at line 32 of file leastsquares.c.
int nt
Definition at line 34 of file leastsquares.c.
double powell_fret
Definition at line 36 of file leastsquares.c.
double powell_ftol
Definition at line 36 of file leastsquares.c.
double** powell_xi
Definition at line 36 of file leastsquares.c.
double * ra
Definition at line 32 of file leastsquares.c.
double** re
Definition at line 32 of file leastsquares.c.
double ** rho
Definition at line 32 of file leastsquares.c.
double * sigma
Definition at line 32 of file leastsquares.c.
double * t
Definition at line 32 of file leastsquares.c.
double ** tmp
Definition at line 32 of file leastsquares.c.
Referenced by cdl_insertMarker(), cdl_markBox(), det(), dFdd(), F(), gammln(), and main().
double * tmpvec
Definition at line 33 of file leastsquares.c.
Referenced by getC(), and main().
double * va
Definition at line 32 of file leastsquares.c.
Author
Generated automatically by Doxygen for imcat from the source code.