lensmap.c
NAME
lensmap.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../utils/error.h'
#include '../imlib/fits.h'
#include '../imlib/map.h'
#include 'lensmap.h'
Defines
#define usage '\n\n\n\NAME\n\	lensmap --- map a source image to a target image\n\\n\SYNOPSIS\n\	lensmap	[option...]\n\		-d datafile	# file for cluster parameters (cluster.dat)\n\		-o xo, yo		# offset for the origin of the image (0,0)\n\		-m mode				# mapping mode (1)\n\\n\DESCRIPTION\n\	\'lensmap\' maps a source image to a target image using multiple\n\	isothermal sphere lens model\n\	lens properties specified in datafile in form\n\\n\	rEinstein rCore xc yc\n\\n\	all in pixel units\n\\n\	Use -m option to specify mode, where these are (in order of expense)\n\		mode = 0:	# nearest pixel\n\		mode = 1:	# linear interpolation\n\		mode = 2:	# sum over triangles\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAX_CLUSTERS 1000
Functions
main (int argc, char *argv[])
int deflection (float ri, float rj, float *di, float *dj)
Variables
float re [MAX_CLUSTERS]
float rc [MAX_CLUSTERS]
int nclusters
int ic [MAX_CLUSTERS]
int jc [MAX_CLUSTERS]
int io
int jo
Define Documentation
#define MAX_CLUSTERS 1000
Definition at line 45 of file lensmap.c.
#define usage '\n\n\n\NAME\n\	lensmap --- map a source image to a target image\n\\n\SYNOPSIS\n\	lensmap	[option...]\n\		-d datafile	# file for cluster parameters (cluster.dat)\n\		-o xo, yo		# offset for the origin of the image (0,0)\n\		-m mode				# mapping mode (1)\n\\n\DESCRIPTION\n\	\'lensmap\' maps a source image to a target image using multiple\n\	isothermal sphere lens model\n\	lens properties specified in datafile in form\n\\n\	rEinstein rCore xc yc\n\\n\	all in pixel units\n\\n\	Use -m option to specify mode, where these are (in order of expense)\n\		mode = 0:	# nearest pixel\n\		mode = 1:	# linear interpolation\n\		mode = 2:	# sum over triangles\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 5 of file lensmap.c.
Function Documentation
void deflection (float ri, float rj, float * di, float * dj)
Definition at line 142 of file lensmap.c.
References di, dj, ic, jc, nclusters, rc, and re.
Referenced by fastmap(), main(), map(), and ultrafastmap().
main (int argc, char * argv[])
Definition at line 50 of file lensmap.c.
References add_comment(), allocFloatArray(), deflection(), error_exit, exit(), FAST_MAP_MODE, fastmap(), fits, ic, io, jc, jo, map(), N1, N2, nclusters, rc, re, read2Dfloatimage(), TRIANGLE_MAP_MODE, ULTRAFAST_MAP_MODE, ultrafastmap(), usage, and write2Dfloatimage().
Variable Documentation
int ic[MAX_CLUSTERS] [static]
Definition at line 48 of file lensmap.c.
Referenced by deflection(), and main().
int io [static]
Definition at line 48 of file lensmap.c.
Referenced by main().
int jc[MAX_CLUSTERS] [static]
Definition at line 48 of file lensmap.c.
Referenced by deflection(), and main().
int jo [static]
Definition at line 48 of file lensmap.c.
Referenced by main().
int nclusters [static]
Definition at line 48 of file lensmap.c.
Referenced by deflection(), and main().
float rc[MAX_CLUSTERS] [static]
Definition at line 47 of file lensmap.c.
Referenced by deflection(), and main().
float re[MAX_CLUSTERS] [static]
Definition at line 47 of file lensmap.c.
Author
Generated automatically by Doxygen for imcat from the source code.