linesmode.c
NAME
linesmode.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../utils/stats_stuff.h'
#include '../utils/error.h'
#include '../imlib/fits.h'
Defines
#define usage '\n\n\n\NAME\n\	linesmode --- calculate mode of rows/cols of a fits file\n\\n\SYNOPSIS\n\	linesmode [options...]\n\		-c			# work in columns mode\n\		-f fitsf		# fix fits file 'fitsf'\n\\n\DESCRIPTION\n\	By default, \'linesmode\' reads a N1 * N2 fits file from stdin,\n\	calculates the median for each row (might be useful to\n\	zap detected objects with 'makechart' first) and writes the\n\	result to stdout as a 1-D fits file.\n\	With -c option, we calculate the median for each column instead.\n\	With -f option we read the line modes (or column modes with -c) mode\n\	file from stdin, and subtract mode from the named fits\n\	file, writing the result to standard out.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define LINE_ORIENT_MODE 0
#define COLS_ORIENT_MODE 1
#define GET_MODE_MODE 0
#define FIX_FITS_MODE 1
#define MIN_SAMPLE_SIZE 10
#define MAGIC FLOAT_MAGIC
Functions
int main (int argc, char *argv[])
Define Documentation
#define COLS_ORIENT_MODE 1
Definition at line 41 of file linesmode.c.
Referenced by main().
#define FIX_FITS_MODE 1
Definition at line 43 of file linesmode.c.
Referenced by main().
#define GET_MODE_MODE 0
Definition at line 42 of file linesmode.c.
Referenced by main().
#define LINE_ORIENT_MODE 0
Definition at line 40 of file linesmode.c.
Referenced by main().
#define MAGIC FLOAT_MAGIC
Definition at line 47 of file linesmode.c.
#define MIN_SAMPLE_SIZE 10
Definition at line 45 of file linesmode.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	linesmode --- calculate mode of rows/cols of a fits file\n\\n\SYNOPSIS\n\	linesmode [options...]\n\		-c			# work in columns mode\n\		-f fitsf		# fix fits file 'fitsf'\n\\n\DESCRIPTION\n\	By default, \'linesmode\' reads a N1 * N2 fits file from stdin,\n\	calculates the median for each row (might be useful to\n\	zap detected objects with 'makechart' first) and writes the\n\	result to stdout as a 1-D fits file.\n\	With -c option, we calculate the median for each column instead.\n\	With -f option we read the line modes (or column modes with -c) mode\n\	file from stdin, and subtract mode from the named fits\n\	file, writing the result to standard out.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
calculate simple statistics for an image Definition at line 7 of file linesmode.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 49 of file linesmode.c.
References COLS_ORIENT_MODE, error_exit, exit(), fitsheader::extpixtype, f, fits, FIX_FITS_MODE, FLOAT_PIXTYPE, GET_MODE_MODE, LINE_ORIENT_MODE, liststats(), lq, MAGIC, median(), MIN_SAMPLE_SIZE, fitsheader::n, N1, N2, fitsheader::ndim, opmode, read2Dfloatimage(), sigma, usage, write2Dfloatimage(), writefitsheader(), writefitsline(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.