linmodel.c
NAME
linmodel.c -
SYNOPSIS
#include <math.h>
#include 'error.h'
#include 'lu.h'
Functions
void linmodelinit (int NP)
void linmodelincrement (double f, double *p)
void linmodelsolve (double *F)
Variables
double ** A
double * B
int np
int * indx
Function Documentation
void linmodelincrement (double f, double * p)
Definition at line 31 of file linmodel.c.
References A, B, f, and np.
void linmodelinit (int NP)
Definition at line 16 of file linmodel.c.
References A, B, indx, and np.
void linmodelsolve (double * F)
Definition at line 45 of file linmodel.c.
References A, B, det(), F(), free(), indx, mylubksb(), myludcmp(), and np.
Variable Documentation
double** A [static]
Definition at line 13 of file linmodel.c.
double * B [static]
Definition at line 13 of file linmodel.c.
int * indx [static]
Definition at line 14 of file linmodel.c.
int np [static]
Definition at line 14 of file linmodel.c.
Referenced by linmodelincrement(), linmodelinit(), and linmodelsolve().
Author
Generated automatically by Doxygen for imcat from the source code.