linmin.h
NAME
linmin.h -
SYNOPSIS
Functions
void linmin (float p[], float xi[], int n, float *fret, float(*func)(float[]))
Function Documentation
void linmin (float p[], float xi[], int n, float * fret, float(* func)(float[]))
Definition at line 20 of file linmin.c.
References brent(), f1dim(), fb, free_vector(), func(), j, mnbrak(), n, ncom, nrfunc, pcom, TOL, vector(), xicom, xmin, and xx.
Referenced by frprmn(), and powell().
Author
Generated automatically by Doxygen for imcat from the source code.