linmodel.h
NAME
linmodel.h -
SYNOPSIS
Functions
void linmodelinit (int np)
void linmodelincrement (double f, double *p)
void linmodelsolve (double *F)
Function Documentation
void linmodelincrement (double f, double * p)
Definition at line 31 of file linmodel.c.
References A, B, f, and np.
void linmodelinit (int np)
Definition at line 16 of file linmodel.c.
References A, B, indx, and np.
void linmodelsolve (double * F)
Definition at line 45 of file linmodel.c.
References A, B, det(), F(), free(), indx, mylubksb(), myludcmp(), and np.
Author
Generated automatically by Doxygen for imcat from the source code.