.TH "linmodel.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linmodel.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'error.h'\fP
.br
\fC#include 'lu.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlinmodelinit\fP (int NP)"
.br
.ti -1c
.RI "void \fBlinmodelincrement\fP (double f, double *p)"
.br
.ti -1c
.RI "void \fBlinmodelsolve\fP (double *F)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double ** \fBA\fP"
.br
.ti -1c
.RI "double * \fBB\fP"
.br
.ti -1c
.RI "int \fBnp\fP"
.br
.ti -1c
.RI "int * \fBindx\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void linmodelincrement (double f, double * p)"
.PP
Definition at line 31 of file linmodel.c.
.PP
References A, B, f, and np.
.SS "void linmodelinit (int NP)"
.PP
Definition at line 16 of file linmodel.c.
.PP
References A, B, indx, and np.
.SS "void linmodelsolve (double * F)"
.PP
Definition at line 45 of file linmodel.c.
.PP
References A, B, det(), F(), free(), indx, mylubksb(), myludcmp(), and np.
.SH "Variable Documentation"
.PP 
.SS "double** \fBA\fP\fC [static]\fP"
.PP
Definition at line 13 of file linmodel.c.
.SS "double * \fBB\fP\fC [static]\fP"
.PP
Definition at line 13 of file linmodel.c.
.SS "int * \fBindx\fP\fC [static]\fP"
.PP
Definition at line 14 of file linmodel.c.
.SS "int \fBnp\fP\fC [static]\fP"
.PP
Definition at line 14 of file linmodel.c.
.PP
Referenced by linmodelincrement(), linmodelinit(), and linmodelsolve().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
