linmin.c
NAME
linmin.c -
SYNOPSIS
#include <stdio.h>
#include 'linmin.h'
#include 'brent.h'
#include 'mnbrak.h'
#include 'f1dim.h'
#include 'nrutil.h'
Defines
#define TOL 2.0e-4
Functions
void linmin (float p[], float xi[], int n, float *fret, float(*func)(float[]))
Variables
int ncom = 0
float * pcom = 0*xicom=0(*nrfunc)()
Define Documentation
#define TOL 2.0e-4
Definition at line 15 of file linmin.c.
Function Documentation
void linmin (float p[], float xi[], int n, float * fret, float(* func)(float[]))
Definition at line 20 of file linmin.c.
References brent(), f1dim(), fb, free_vector(), func(), j, mnbrak(), n, ncom, nrfunc, pcom, TOL, vector(), xicom, xmin, and xx.
Referenced by frprmn(), and powell().
Variable Documentation
int ncom = 0
Definition at line 17 of file linmin.c.
float* pcom = 0*xicom=0(*nrfunc)()
Definition at line 18 of file linmin.c.
Author
Generated automatically by Doxygen for imcat from the source code.