lintransformfit.c
NAME
lintransformfit.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
Defines
#define usage 'usage: lintransformfit [options...]\n\\t\t-r\t\t# output residuals\n\\treads file containing x, y, x', y' from stdin and fits a linear\n\\ttransformation model:\n\\t\tx' = x0 + Pxx x + Pxy y\n\\t\ty' = y0 + Pyx x + Pyy y\n\\tby least squares.\n\\tOutputs dx, dy, Pxx, Pxy, Pyx, Pyy to stdout by default.\n\\tUse -r option to output x, y, x', y', dx, dy where dx = x' - model.\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage 'usage: lintransformfit [options...]\n\\t\t-r\t\t# output residuals\n\\treads file containing x, y, x', y' from stdin and fits a linear\n\\ttransformation model:\n\\t\tx' = x0 + Pxx x + Pxy y\n\\t\ty' = y0 + Pyx x + Pyy y\n\\tby least squares.\n\\tOutputs dx, dy, Pxx, Pxy, Pyx, Pyy to stdout by default.\n\\tUse -r option to output x, y, x', y', dx, dy where dx = x' - model.\n'
Definition at line 6 of file lintransformfit.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 19 of file lintransformfit.c.
References B, d, dx, dy, exit(), indx, line, m, mylubksb(), myludcmp(), n, usage, x, xp(), y, and yp().
Author
Generated automatically by Doxygen for imcat from the source code.