lintransfit.c
NAME
lintransfit.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
Defines
#define usage '\n\n\NAME\n\	lintransfit - determine accurate transformation coefficients\n\\n\SYNOPSIS\n\	lintransfit [options...]\n\\n\DESCRIPTION\n\	'lintransfit' reads a merged catalogue (created\n\	by 'mergecats' and containing a pair of vector\n\	coordinates in x[2][2] as x[0] = (x,y), x[1] = (x',y')\n\	from stdin and fits a linear transformation model:\n\		x' = x0 + Pxx x + Pxy y\n\		y' = y0 + Pyx x + Pyy y\n\	by least squares.\n\	Outputs dx, dy, Pxx, Pxy, Pyx, Pyy to stdout by default.\n\	Options are:\n\		-r	Output catalogue containing x[2][2], dx[2]\n\			where dx = x' - x'_model.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\NAME\n\	lintransfit - determine accurate transformation coefficients\n\\n\SYNOPSIS\n\	lintransfit [options...]\n\\n\DESCRIPTION\n\	'lintransfit' reads a merged catalogue (created\n\	by 'mergecats' and containing a pair of vector\n\	coordinates in x[2][2] as x[0] = (x,y), x[1] = (x',y')\n\	from stdin and fits a linear transformation model:\n\		x' = x0 + Pxx x + Pxy y\n\		y' = y0 + Pyx x + Pyy y\n\	by least squares.\n\	Outputs dx, dy, Pxx, Pxy, Pyx, Pyy to stdout by default.\n\	Options are:\n\		-r	Output catalogue containing x[2][2], dx[2]\n\			where dx = x' - x'_model.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 6 of file lintransfit.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 33 of file lintransfit.c.
References B, d, dx, dy, error_exit, exit(), indx, lcpipe, line, m, mylubksb(), myludcmp(), n, usage, x, xp(), y, and yp().
Author
Generated automatically by Doxygen for imcat from the source code.