lmodel.h
NAME
lmodel.h -
SYNOPSIS
Data Structures
struct lmodel
Defines
#define POLYNOMIAL_LMODEL 0
#define ZERNIKE_LMODEL 1
#define FOURIER_LMODEL 2
Typedefs
typedef lmodel lmodel
Functions
lmodel * newlmodel (item *xitem, item *aitem)
lmodel * newpolylmodel (item *xitem, item *aitem, int lmin, int lmax)
int polyloop (lmodel *themodel, int l, int i)
lmodel * newzernikelmodel (item *xitem, item *aitem, int nmin, int nmax)
int zernikeloop (lmodel *themodel, int n, int i)
int makezernikeR (lmodel *themodel)
lmodel * newfourierlmodel (item *xitem, item *aitem, int kmin, int kmax, int boxlimits, double lbox)
int fourierloop (lmodel *themodel, int i)
double lmodelfunc (lmodel *themodel, int m, double *x)
int flatten_a (lmodel *themodel)
int rflatten_a (lmodel *themodel, void *a, int m, int level)
int unflatten_a (lmodel *themodel)
int runflatten_a (lmodel *themodel, void *a, int m, int level)
int addtomatrix (void *adst, void *asrc, double fac, int ndim, int *dim, int level)
int zeromatrix (void *a, int ndim, int *dim, int level)
int bang (int n)
int writelmodel (lmodel *themodel, FILE *opstream)
lmodel * readlmodel (FILE *ipstream)
lmodel * difflmodel (lmodel *iplmodel, int integratemode)
Define Documentation
#define FOURIER_LMODEL 2
Definition at line 34 of file lmodel.h.
Referenced by difflmodel(), lmodelfunc(), main(), newfourierlmodel(), readlmodel(), and writelmodel().
#define POLYNOMIAL_LMODEL 0
Definition at line 32 of file lmodel.h.
Referenced by difflmodel(), lmodelfunc(), main(), newpolylmodel(), readlmodel(), and writelmodel().
#define ZERNIKE_LMODEL 1
Definition at line 33 of file lmodel.h.
Referenced by difflmodel(), lmodelfunc(), main(), newzernikelmodel(), readlmodel(), and writelmodel().
Typedef Documentation
typedef struct lmodel lmodel
Function Documentation
int addtomatrix (void * adst, void * asrc, double fac, int ndim, int * dim, int level)
Definition at line 413 of file lmodel.c.
References i.
Referenced by main().
int bang (int n)
Definition at line 447 of file lmodel.c.
References n.
Referenced by makezernikeR().
lmodel* difflmodel (lmodel * iplmodel, int integratemode)
Definition at line 15 of file lmodelcalculus.c.
References lmodel::aflat, lmodel::aitem, lmodel::asize, lmodel::boxlimits, item::dim, error_exit, flatten_a(), FOURIER_LMODEL, i, lmodel::i, j, lmodel::k, kk, lmodel::kmax, lmodel::kmin, lmodel::lbox, lmodel::lmax, lmodel::lmin, lmodel::modeltype, item::ndim, newfourierlmodel(), newpolylmodel(), lmodel::nmodes, lmodel::p, POLYNOMIAL_LMODEL, lmodel::pp, unflatten_a(), lmodel::xdim, lmodel::xitem, and ZERNIKE_LMODEL.
Referenced by main().
int flatten_a (lmodel * themodel)
Definition at line 353 of file lmodel.c.
References lmodel::a, lmodel::aflat, lmodel::asize, lmodel::j, j, m, lmodel::nmodes, and rflatten_a().
Referenced by difflmodel(), and main().
int fourierloop (lmodel * themodel, int i)
Definition at line 253 of file lmodel.c.
References lmodel::boxlimits, lmodel::i, i, j, lmodel::k, lmodel::kk, kk, lmodel::kmax, lmodel::kmin, lmodel::nmodes, and lmodel::xdim.
Referenced by newfourierlmodel().
double lmodelfunc (lmodel * themodel, int m, double * x)
Definition at line 299 of file lmodel.c.
References abs, d, error_exit, FOURIER_LMODEL, lmodel::i, lmodel::k, lmodel::lbox, lmodel::m, m, lmodel::modeltype, lmodel::n, lmodel::p, phi, POLYNOMIAL_LMODEL, lmodel::R, r, x, lmodel::xdim, and ZERNIKE_LMODEL.
Referenced by generatefm(), and main().
int makezernikeR (lmodel * themodel)
Definition at line 187 of file lmodel.c.
References abs, bang(), lmodel::m, m, lmodel::n, n, lmodel::nmodes, and lmodel::R.
Referenced by newzernikelmodel(), and readlmodel().
lmodel* newfourierlmodel (item * xitem, item * aitem, int kmin, int kmax, int boxlimits, double lbox)
Definition at line 208 of file lmodel.c.
References lmodel::a, lmodel::aitem, allocitemcontents(), lmodel::boxlimits, FOURIER_LMODEL, fourierloop(), lmodel::i, lmodel::k, lmodel::kk, lmodel::kmax, lmodel::kmin, lmodel::lbox, m, lmodel::modeltype, newlmodel(), lmodel::nmodes, and lmodel::xdim.
Referenced by difflmodel(), and main().
lmodel* newlmodel (item * xitem, item * aitem)
Definition at line 13 of file lmodel.c.
References lmodel::aitem, lmodel::aname, lmodel::asize, lmodel::cat, d, item::dim, error_exit, item::itype, item::name, item::ndim, NUM_TYPE, lmodel::xdim, lmodel::xitem, lmodel::xname, and lmodel::xorigin.
Referenced by newfourierlmodel(), newpolylmodel(), newzernikelmodel(), and readlmodel().
lmodel* newpolylmodel (item * xitem, item * aitem, int lmin, int lmax)
Definition at line 56 of file lmodel.c.
References lmodel::a, lmodel::aitem, allocitemcontents(), d, lmodel::l, l, lmodel::lmax, lmodel::lmin, m, lmodel::modeltype, newlmodel(), lmodel::nmodes, lmodel::p, polyloop(), POLYNOMIAL_LMODEL, lmodel::pp, and lmodel::xdim.
Referenced by difflmodel(), and main().
lmodel* newzernikelmodel (item * xitem, item * aitem, int nmin, int nmax)
Definition at line 135 of file lmodel.c.
References lmodel::a, lmodel::aitem, allocitemcontents(), item::dim, error_exit, lmodel::m, m, makezernikeR(), lmodel::modeltype, lmodel::n, n, item::ndim, newlmodel(), lmodel::nmax, lmodel::nmin, lmodel::nmodes, and ZERNIKE_LMODEL.
Referenced by main().
int polyloop (lmodel * themodel, int l, int i)
Definition at line 105 of file lmodel.c.
References i, j, lmodel::l, l, lmodel::nmodes, lmodel::p, lmodel::pp, and lmodel::xdim.
Referenced by newpolylmodel().
lmodel* readlmodel (FILE * ipstream)
Definition at line 141 of file lmodelio.c.
References lmodel::a, abs, item::addr, object::addrlist, allocobjectcontents(), lmodel::boxlimits, lmodel::cat, copyheaderinfo(), lmodel::covar, d, item::dim, error_exit, FOURIER_LMODEL, getheaderitem(), getheaderitemaddress(), getobjectitem(), getobjectitemindex(), lmodel::hascovar, lmodel::hasxorigin, lmodel::i, cathead::itemlist, item::itype, lmodel::k, lmodel::kmax, lmodel::kmin, lmodel::l, lmodel::lbox, ll, lmodel::lmax, lmodel::lmin, m, lmodel::m, makezernikeR(), lmodel::modeltype, lmodel::n, item::name, item::ndim, newitem(), newlmodel(), newobject(), object::next, lmodel::nmax, lmodel::nmin, nmodes, lmodel::nmodes, NUM_TYPE, lmodel::p, POLYNOMIAL_LMODEL, readcathead(), readobject(), setcatipf(), lmodel::xorigin, and ZERNIKE_LMODEL.
Referenced by main().
int rflatten_a (lmodel * themodel, void * a, int m, int level)
Definition at line 370 of file lmodel.c.
References a, lmodel::aflat, lmodel::aitem, i, lmodel::j, and m.
Referenced by flatten_a().
int runflatten_a (lmodel * themodel, void * a, int m, int level)
Definition at line 396 of file lmodel.c.
References a, lmodel::aflat, lmodel::aitem, i, lmodel::j, and m.
Referenced by unflatten_a().
int unflatten_a (lmodel * themodel)
Definition at line 385 of file lmodel.c.
References lmodel::a, lmodel::j, m, lmodel::nmodes, and runflatten_a().
Referenced by difflmodel(), and main().
int writelmodel (lmodel * themodel, FILE * opstream)
Definition at line 15 of file lmodelio.c.
References lmodel::a, addobjectitem(), item::addr, lmodel::aitem, allocitemcontents(), lmodel::aname, lmodel::boxlimits, lmodel::cat, lmodel::covar, d, error_exit, FOURIER_LMODEL, lmodel::hascovar, lmodel::hasxorigin, lmodel::i, install1numericheaderitem(), install1textheaderitem(), installitem(), lmodel::k, lmodel::kmax, lmodel::kmin, lmodel::l, lmodel::lbox, lmodel::lmax, lmodel::lmin, m, lmodel::m, lmodel::modeltype, lmodel::n, newitem(), lmodel::nmax, lmodel::nmin, lmodel::nmodes, NUM_TYPE, lmodel::p, POLYNOMIAL_LMODEL, setcatopf(), TEXT_TYPE, writecathead(), writeitem(), lmodel::xdim, lmodel::xname, lmodel::xorigin, and ZERNIKE_LMODEL.
Referenced by main().
int zernikeloop (lmodel * themodel, int n, int i)
int zeromatrix (void * a, int ndim, int * dim, int level)
Definition at line 430 of file lmodel.c.
References a, and i.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.