lmodel.c
NAME
lmodel.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'catlib/cat.h'
#include 'utils/error.h'
#include 'lmodel.h'
Functions
lmodel * newlmodel (item *xitem, item *aitem)
lmodel * newpolylmodel (item *xitem, item *aitem, int lmin, int lmax)
int polyloop (lmodel *themodel, int l, int i)
lmodel * newzernikelmodel (item *xitem, item *aitem, int nmin, int nmax)
int makezernikeR (lmodel *themodel)
lmodel * newfourierlmodel (item *xitem, item *aitem, int kmin, int kmax, int boxlimits, double lbox)
int fourierloop (lmodel *themodel, int i)
double lmodelfunc (lmodel *themodel, int m, double *x)
int flatten_a (lmodel *themodel)
int rflatten_a (lmodel *themodel, void *a, int m, int level)
int unflatten_a (lmodel *themodel)
int runflatten_a (lmodel *themodel, void *a, int m, int level)
int addtomatrix (void *adst, void *asrc, double fac, int ndim, int *dim, int level)
int zeromatrix (void *a, int ndim, int *dim, int level)
int bang (int n)
Function Documentation
int addtomatrix (void * adst, void * asrc, double fac, int ndim, int * dim, int level)
Definition at line 413 of file lmodel.c.
References i.
Referenced by main().
int bang (int n)
Definition at line 447 of file lmodel.c.
References n.
Referenced by makezernikeR().
int flatten_a (lmodel * themodel)
Definition at line 353 of file lmodel.c.
References lmodel::a, lmodel::aflat, lmodel::asize, j, lmodel::j, m, lmodel::nmodes, and rflatten_a().
Referenced by difflmodel(), and main().
int fourierloop (lmodel * themodel, int i)
Definition at line 253 of file lmodel.c.
References lmodel::boxlimits, i, lmodel::i, j, lmodel::k, kk, lmodel::kk, lmodel::kmax, lmodel::kmin, lmodel::nmodes, and lmodel::xdim.
Referenced by newfourierlmodel().
double lmodelfunc (lmodel * themodel, int m, double * x)
Definition at line 299 of file lmodel.c.
References abs, d, error_exit, FOURIER_LMODEL, lmodel::i, lmodel::k, lmodel::lbox, m, lmodel::m, lmodel::modeltype, lmodel::n, lmodel::p, phi, POLYNOMIAL_LMODEL, r, lmodel::R, x, lmodel::xdim, and ZERNIKE_LMODEL.
Referenced by generatefm(), and main().
int makezernikeR (lmodel * themodel)
Definition at line 187 of file lmodel.c.
References abs, bang(), m, lmodel::m, n, lmodel::n, lmodel::nmodes, and lmodel::R.
Referenced by newzernikelmodel(), and readlmodel().
lmodel* newfourierlmodel (item * xitem, item * aitem, int kmin, int kmax, int boxlimits, double lbox)
Definition at line 208 of file lmodel.c.
References lmodel::a, lmodel::aitem, allocitemcontents(), lmodel::boxlimits, FOURIER_LMODEL, fourierloop(), lmodel::i, lmodel::k, lmodel::kk, lmodel::kmax, lmodel::kmin, lmodel::lbox, m, lmodel::modeltype, newlmodel(), lmodel::nmodes, and lmodel::xdim.
Referenced by difflmodel(), and main().
lmodel* newlmodel (item * xitem, item * aitem)
Definition at line 13 of file lmodel.c.
References lmodel::aitem, lmodel::aname, lmodel::asize, lmodel::cat, d, item::dim, error_exit, item::itype, item::name, item::ndim, NUM_TYPE, lmodel::xdim, lmodel::xitem, lmodel::xname, and lmodel::xorigin.
Referenced by newfourierlmodel(), newpolylmodel(), newzernikelmodel(), and readlmodel().
lmodel* newpolylmodel (item * xitem, item * aitem, int lmin, int lmax)
Definition at line 56 of file lmodel.c.
References lmodel::a, lmodel::aitem, allocitemcontents(), d, l, lmodel::l, lmodel::lmax, lmodel::lmin, m, lmodel::modeltype, newlmodel(), lmodel::nmodes, lmodel::p, polyloop(), POLYNOMIAL_LMODEL, lmodel::pp, and lmodel::xdim.
Referenced by difflmodel(), and main().
lmodel* newzernikelmodel (item * xitem, item * aitem, int nmin, int nmax)
Definition at line 135 of file lmodel.c.
References lmodel::a, lmodel::aitem, allocitemcontents(), item::dim, error_exit, m, lmodel::m, makezernikeR(), lmodel::modeltype, n, lmodel::n, item::ndim, newlmodel(), lmodel::nmax, lmodel::nmin, lmodel::nmodes, and ZERNIKE_LMODEL.
Referenced by main().
int polyloop (lmodel * themodel, int l, int i)
Definition at line 105 of file lmodel.c.
References i, j, l, lmodel::l, lmodel::nmodes, lmodel::p, lmodel::pp, and lmodel::xdim.
Referenced by newpolylmodel().
int rflatten_a (lmodel * themodel, void * a, int m, int level)
Definition at line 370 of file lmodel.c.
References a, lmodel::aflat, lmodel::aitem, i, lmodel::j, and m.
Referenced by flatten_a().
int runflatten_a (lmodel * themodel, void * a, int m, int level)
Definition at line 396 of file lmodel.c.
References a, lmodel::aflat, lmodel::aitem, i, lmodel::j, and m.
Referenced by unflatten_a().
int unflatten_a (lmodel * themodel)
Definition at line 385 of file lmodel.c.
References lmodel::a, lmodel::j, m, lmodel::nmodes, and runflatten_a().
Referenced by difflmodel(), and main().
int zeromatrix (void * a, int ndim, int * dim, int level)
Definition at line 430 of file lmodel.c.
References a, and i.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.