lmodelcalculus.c
NAME
lmodelcalculus.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'catlib/cat.h'
#include 'utils/error.h'
#include 'utils/args.h'
#include 'lmodel.h'
Functions
lmodel * difflmodel (lmodel *ipmodel, int integratemode)
Function Documentation
lmodel* difflmodel (lmodel * ipmodel, int integratemode)
Definition at line 15 of file lmodelcalculus.c.
References lmodel::aflat, lmodel::aitem, lmodel::asize, lmodel::boxlimits, item::dim, error_exit, flatten_a(), FOURIER_LMODEL, lmodel::i, i, j, lmodel::k, kk, lmodel::kmax, lmodel::kmin, lmodel::lbox, lmodel::lmax, lmodel::lmin, lmodel::modeltype, item::ndim, newfourierlmodel(), newpolylmodel(), lmodel::nmodes, lmodel::p, POLYNOMIAL_LMODEL, lmodel::pp, unflatten_a(), lmodel::xdim, lmodel::xitem, and ZERNIKE_LMODEL.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.