main.c
NAME
main.c -
SYNOPSIS
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include 'forms.h'
#include 'xforms-compat.h'
#include 'imlib/fits.h'
#include 'utils/arrays.h'
#include 'control_panel.h'
#include 'callbacks.h'
#include 'mesh.h'
Defines
#define TRUE 1
#define usage '\nNAME\n\ fits3Dviewer - use geomview to display 3D FITS files\n\\n\SYNOPSIS\n\ fits3Dviewer\n\\n\DESCRIPTION\n\ fits3Dviewer is a geomview module. To use it,\n\	move to a working directory, and run the script\n\	geomviewsetup. Then start geomview. 'FITS 3D viewer'\n\	should appear in the 'External Modules' menu. Clicking on\n\	this should bring up a window 'fits3Dviewer' into which you can enter\n\	an arbitrary command that, when executed, will generate\n\	a 3-D FITS file. The planes of that image will be rendered\n\	by geomview as a series of surface plots. This is a useful way\n\	to make animations. One can use the controls in the various\n\	windows to fine-tune the appearance of the surface and the\n\	z-scale. Then, pressing the 'record' followed by the 'play'\n\	button will result in a series of files /tmp/fits3Dviewer.nnnn.ppm\n\	being created. These can then be converted into e.g. animated\n\	GIF format using the gimp.\n\\n\	For example\n\	 ic -c 1024 1024 'grand 3 *' | smooth -p -1 | smooth -f 0 0 2 | helicalscan 64 2 22.5\n\\n\SEE ALSO\n\ geomviewsetup\n\AUTHOR\n\ Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (argc, char **argv)
Variables
float log2zscale
float zscale
float ** f
int opmode
int recording
int framenumber
int nframes
int Nx
int Ny
FD_control_panel * thecontrolpanel
fitsheader * fits
char * fitsgencommand
FILE * ipf
Define Documentation
#define TRUE 1
Definition at line 14 of file main.c.
Referenced by main().
#define usage '\nNAME\n\ fits3Dviewer - use geomview to display 3D FITS files\n\\n\SYNOPSIS\n\ fits3Dviewer\n\\n\DESCRIPTION\n\ fits3Dviewer is a geomview module. To use it,\n\	move to a working directory, and run the script\n\	geomviewsetup. Then start geomview. 'FITS 3D viewer'\n\	should appear in the 'External Modules' menu. Clicking on\n\	this should bring up a window 'fits3Dviewer' into which you can enter\n\	an arbitrary command that, when executed, will generate\n\	a 3-D FITS file. The planes of that image will be rendered\n\	by geomview as a series of surface plots. This is a useful way\n\	to make animations. One can use the controls in the various\n\	windows to fine-tune the appearance of the surface and the\n\	z-scale. Then, pressing the 'record' followed by the 'play'\n\	button will result in a series of files /tmp/fits3Dviewer.nnnn.ppm\n\	being created. These can then be converted into e.g. animated\n\	GIF format using the gimp.\n\\n\	For example\n\	 ic -c 1024 1024 'grand 3 *' | smooth -p -1 | smooth -f 0 0 2 | helicalscan 64 2 22.5\n\\n\SEE ALSO\n\ geomviewsetup\n\AUTHOR\n\ Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 22 of file main.c.
Function Documentation
main (argc, char ** argv)
Definition at line 63 of file main.c.
References FD_control_panel::command_input, FD_control_panel::control_panel, counter_filter(), create_form_control_panel(), DrawMesh(), exit(), f, framenumber, IDLE_MODE, ipf, log2zscale, opmode, ReadNewFrame(), recording, RUN_MODE, thecontrolpanel, TRUE, usage, zscale, and FD_control_panel::zscale_counter.
Variable Documentation
float ** f
Definition at line 53 of file main.c.
fitsheader* fits
Definition at line 56 of file main.c.
char* fitsgencommand
Definition at line 57 of file main.c.
Referenced by command_input_callback(), and start_command().
int framenumber
Definition at line 54 of file main.c.
FILE* ipf
Definition at line 58 of file main.c.
float log2zscale
Definition at line 53 of file main.c.
Referenced by main(), and zscale_counter_callback().
int nframes
Definition at line 54 of file main.c.
int Nx
Definition at line 54 of file main.c.
int Ny
Definition at line 54 of file main.c.
int opmode
Definition at line 54 of file main.c.
int recording
Definition at line 54 of file main.c.
FD_control_panel* thecontrolpanel
Definition at line 55 of file main.c.
float zscale
Definition at line 53 of file main.c.
Author
Generated automatically by Doxygen for imcat from the source code.