.TH "makec.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
makec.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned char *** \fBmakecarray\fP (\fBfitsheader\fP *\fBfits\fP, int \fBN1\fP, int \fBN2\fP, int Ncolors, float \fBfmin\fP, float \fBfmax\fP, int dobox)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned char*** makecarray (\fBfitsheader\fP * fits, int N1, int N2, int Ncolors, float fmin, float fmax, int dobox)"
.PP
Definition at line 9 of file makec.c.
.PP
References c, color, f, fits, FLOAT_MAGIC, fmin, i, j, N1, N2, and readfitsline().
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
