makerandcat.c
NAME
makerandcat.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include '../../utils/error.h'
#include '../../utils/args.h'
#include '../../catlib/cat.h'
Defines
#define usage '\n\n\NAME\n\ makerandcat - generate catalogue containing random values\n\\n\SYNOPSIS\n\ makerandcat n [-seed seed] [-dim dim] [-b]\n\\n\DESCRIPTION\n\	Makerandcat generates a lc-format catalogue containing random values\n\	for testing purposes. By default the catalogue contains n objects consisting\n\	of a 2-vector x[2], with values x[0], x[1] uniformly distributed\n\	on the interval 0,1 and is in text format.\n\\n\	Options:\n\		-seed 	seed	# supply an integer seed for random number generator (1)\n\		-dim	dim	# specify alternative dimension for x-vector (2)\n\		-b		# generate a binary format catalogue.\n\\n\AUTHOR\n\ Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n'
Functions
double drand48 ()
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\NAME\n\ makerandcat - generate catalogue containing random values\n\\n\SYNOPSIS\n\ makerandcat n [-seed seed] [-dim dim] [-b]\n\\n\DESCRIPTION\n\	Makerandcat generates a lc-format catalogue containing random values\n\	for testing purposes. By default the catalogue contains n objects consisting\n\	of a 2-vector x[2], with values x[0], x[1] uniformly distributed\n\	on the interval 0,1 and is in text format.\n\\n\	Options:\n\		-seed 	seed	# supply an integer seed for random number generator (1)\n\		-dim	dim	# specify alternative dimension for x-vector (2)\n\		-b		# generate a binary format catalogue.\n\\n\AUTHOR\n\ Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n'
Definition at line 12 of file makerandcat.c.
Function Documentation
double drand48 ()
Referenced by add_population(), expvar(), gasdev(), gaussdev(), main(), make_pop(), num0funcarray(), ran1(), randdoit(), and randinit().
main (int argc, char * argv[])
Definition at line 36 of file makerandcat.c.
References argsinit(), argsToString(), drand48(), error_exit, exit(), flag, FLAG_ARG, getargi(), getflag(), i, LC_NUM_FMT, n, nextargtype(), usage, and x.
Author
Generated automatically by Doxygen for imcat from the source code.