.TH "maketestcat.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maketestcat.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   'usage: maketestcat \fBnobj\fP ncols\\\fBn\fP\\SUPERSEDED BY makerandcat and makegridcat\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBdrand48\fP ()"
.br
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   'usage: maketestcat \fBnobj\fP ncols\\\fBn\fP\\SUPERSEDED BY makerandcat and makegridcat\\\fBn\fP'"
.PP
Definition at line 3 of file maketestcat.c.
.SH "Function Documentation"
.PP 
.SS "double drand48 ()"
.PP
.SS "main (int argc, char * argv[])"
.PP
Definition at line 8 of file maketestcat.c.
.PP
References drand48(), exit(), line, and usage.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
