make_image.c
NAME
make_image.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'make_image.h'
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	make_image --- generates a mock CCD image\n\\n\SYNOPSIS\n\	make_image ncolours N1 N2 [option...]\n\		-o n r f0		# number, size and central SB of gaussian objects\n\		-e n r f0		# number, size and central SB of exponential objects\n\		-s sigma		# rms sky fluctuation\n\		-b col			# a bad column\n\		-r seed			# for ran num generator\n\		-f			# generate float format image\n\		-i			# generate 32 bit int format image\n\\n\DESCRIPTION\n\	\'make_image\' generates a mock CCD image containing families\n\	of gaussian profile objects + noise + bad column defects.\n\	The first argument must be the number of colours.\n\	The second argument must be the size of the image on a side.\n\	Random number seed should precede -o or -s args\n\	Cosmic rays are indicated by a negative gaussian scale length.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define GAU 0
#define EXP 1
#define MAGIC FLOAT_MAGIC
Functions
double drand48 ()
int main (int argc, char *argv[])
int check_args (int argc, char *argv[])
void add_bad_col (int N1, int N2, int col)
void add_population (int N1, int N2, int n_objects, float csb, float r_obj, int type)
void add_noise (int N1, int N2, float sigma)
float gasdev (void)
Variables
float ** f [MAX_FITS_DIM]
int ncolours
int seed
Define Documentation
#define EXP 1
Definition at line 40 of file make_image.c.
#define GAU 0
Definition at line 39 of file make_image.c.
Referenced by add_population(), and main().
#define MAGIC FLOAT_MAGIC
Definition at line 42 of file make_image.c.
#define usage '\n\n\n\NAME\n\	make_image --- generates a mock CCD image\n\\n\SYNOPSIS\n\	make_image ncolours N1 N2 [option...]\n\		-o n r f0		# number, size and central SB of gaussian objects\n\		-e n r f0		# number, size and central SB of exponential objects\n\		-s sigma		# rms sky fluctuation\n\		-b col			# a bad column\n\		-r seed			# for ran num generator\n\		-f			# generate float format image\n\		-i			# generate 32 bit int format image\n\\n\DESCRIPTION\n\	\'make_image\' generates a mock CCD image containing families\n\	of gaussian profile objects + noise + bad column defects.\n\	The first argument must be the number of colours.\n\	The second argument must be the size of the image on a side.\n\	Random number seed should precede -o or -s args\n\	Cosmic rays are indicated by a negative gaussian scale length.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file make_image.c.
Function Documentation
void add_bad_col (int N1, int N2, int col)
Definition at line 243 of file make_image.c.
References f, j, MAGIC, N1, N2, and ncolours.
Referenced by main().
void add_noise (int N1, int N2, float sigma)
Definition at line 318 of file make_image.c.
void add_population (int N1, int N2, int n_objects, float csb, float r_obj, int type)
Definition at line 258 of file make_image.c.
References drand48(), error_exit, EXP, f, GAU, i, j, n, N1, N2, ncolours, and type.
Referenced by main().
int check_args (int argc, char * argv[])
Definition at line 190 of file make_image.c.
Referenced by main().
double drand48 ()
float gasdev (void)
Definition at line 332 of file make_image.c.
References drand48(), r, and ran0().
int main (int argc, char * argv[])
Definition at line 50 of file make_image.c.
References add_bad_col(), add_comment(), add_noise(), add_population(), allocFloatArray(), appendcomment(), check_args(), color, COM_LENGTH, error_exit, EXP, fitsheader::extpixtype, f, fits, FLOAT_PIXTYPE, GAU, i, INT_PIXTYPE, j, fitsheader::n, n, N1, N2, ncolours, fitsheader::ndim, new2Dfitsheader(), newtextcomment(), r, seed, SHORT_PIXTYPE, sigma, usage, fitscomment::value, writefitsheader(), writefitsline(), and writefitstail().
Variable Documentation
float** f[MAX_FITS_DIM] [static]
Definition at line 44 of file make_image.c.
int ncolours [static]
Definition at line 45 of file make_image.c.
Referenced by add_bad_col(), add_noise(), add_population(), and main().
int seed [static]
Definition at line 46 of file make_image.c.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.