makepeff2.c
NAME
makepeff2.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <float.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/ipbuff.h'
#include '../../utils/arrays.h'
#include '../../utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	makepeff2 --- compute effective polarisability\n\\n\SYNOPSIS\n\	makepeff2 [options...]\n\\n\DESCRIPTION\n\	'makepeff2' first reads from stdin a catalogue which\n\	must contain at least the following entries:\n\		F	# windowed flux\n\		q0	# size\n\		q[2]	# polarisation\n\		R[2]	# flux response\n\		P0[2]	# size response\n\		P[2][2]	# polarisation response\n\	as created by 'getshapes2'.\n\	It bins appropriate combinations of these in a cubical\n\	array in F, p0, q space and computes P_effective.\n\\n\OPTIONS\n\	Options are\n\		-u			# print this message\n\		-F logF1 logF2 nF	# range of log_10 F and number of bins\n\					# defaults to 2 3.6 8\n\		-q q1 q2 nq		# range of |q| and number of bins\n\					# defaults to 0.0 0.5 32\n\		-Q q01 q02 nq0		# range of q0 and number of bins\n\					# defaults to 2.5 3.5 32\n\\n\OUTPUT\n\	Output is a multi-plane FITS file with planes containing\n\		plane 0		n	# number of objects in cell = sum 1\n\		planes 1-2	nR	# sum R[0], R[1]\n\		planes 3-4	nP0	# sum P0[0], P0[1]\n\		planes 5-8	nP	# sum P[0][0], P[0][1], P[1][0], P[1][1]\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Functions
float *** alloc3Darray (int N1, int N2, int N3)
float *** boxavg3D (float ***f, int N1, int N2, int N3)
float *** grad3D (float ***f, int dir, double dx, int N1, int N2, int N3)
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	makepeff2 --- compute effective polarisability\n\\n\SYNOPSIS\n\	makepeff2 [options...]\n\\n\DESCRIPTION\n\	'makepeff2' first reads from stdin a catalogue which\n\	must contain at least the following entries:\n\		F	# windowed flux\n\		q0	# size\n\		q[2]	# polarisation\n\		R[2]	# flux response\n\		P0[2]	# size response\n\		P[2][2]	# polarisation response\n\	as created by 'getshapes2'.\n\	It bins appropriate combinations of these in a cubical\n\	array in F, p0, q space and computes P_effective.\n\\n\OPTIONS\n\	Options are\n\		-u			# print this message\n\		-F logF1 logF2 nF	# range of log_10 F and number of bins\n\					# defaults to 2 3.6 8\n\		-q q1 q2 nq		# range of |q| and number of bins\n\					# defaults to 0.0 0.5 32\n\		-Q q01 q02 nq0		# range of q0 and number of bins\n\					# defaults to 2.5 3.5 32\n\\n\OUTPUT\n\	Output is a multi-plane FITS file with planes containing\n\		plane 0		n	# number of objects in cell = sum 1\n\		planes 1-2	nR	# sum R[0], R[1]\n\		planes 3-4	nP0	# sum P0[0], P0[1]\n\		planes 5-8	nP	# sum P[0][0], P[0][1], P[1][0], P[1][1]\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file makepeff2.c.
Function Documentation
float*** alloc3Darray (int N1, int N2, int N3)
float*** boxavg3D (float *** f, int N1, int N2, int N3)
float*** grad3D (float *** f, int dir, double dx, int N1, int N2, int N3)
main (int argc, char * argv[])
Definition at line 60 of file makepeff2.c.
References add_comment(), alloc3Darray(), appendcomment(), argsinit(), buff, error_exit, exit(), F(), fits, flag, FLOAT_PIXTYPE, getargf(), getargi(), getflag(), i, ipf, j, n, newfitsheader(), newnumericcomment(), usage, writefitscube(), writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.