makeotf.c
NAME
makeotf.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'imlib/fits.h'
#include 'utils/error.h'
#include 'utils/args.h'
#include 'fftlib/myfft.h'
Defines
#define usage '\n\n\n\NAME\n\	makeotf --- make fast guiding otf\n\SYNOPSIS\n\	makeotf [-N N] [-R r_outer] [-r r0] [-D D] [-o opfile] [-z zmax] [-i imname]\n\\n\DESCRIPTION\n\	'makeotf' computes the OTF gk(z) for perfect fast guiding.\n\\n\	Options are\n\		-N N		# image size in pixels (256)\n\		-R r_outer	# outer scale in m (infinite)\n\		-r r0		# Fried length in m (0.4)\n\		-D D		# telescope diameter (1.6)\n\		-e e		# obscuration = D_2 / D (0.0)\n\		-o opfile	# output file\n\		-z zmax		# upper limit for integerized z (N/2)\n\		-d dz		# step in integer z (1)\n\		-i imname	# output image 'imname' and exit\n\		-g xg yg	# location of the guide star\n\\n\	Output is a table (in lc or human readable format) containing:\n\		z		# argument of transfer function (in m)\n\		S(z)		# atmospheric phase structure function\n\		gknatl		# atmospheric OTF = exp(-S/2)\n\		gkdiff		# diffraction limited OTF\n\		gktilt		# fast guiding OTF\n\		gkfried		# Fried approximation\n\	except with -i option in which case it will output FITS image\n\	'imname' which can be one of\n\		T, S, Sg, TT, TTxS, WxS, TxT\n\\n\	Currently, -g option only works with pure Kolmogorov (infinite outer\n\	scale) spectrum.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
void gradx (float **f, int N1, int N2, float **fx)
void mult (float **f, int N1, int N2, float fac)
void zero (float **f, int N1, int N2)
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	makeotf --- make fast guiding otf\n\SYNOPSIS\n\	makeotf [-N N] [-R r_outer] [-r r0] [-D D] [-o opfile] [-z zmax] [-i imname]\n\\n\DESCRIPTION\n\	'makeotf' computes the OTF gk(z) for perfect fast guiding.\n\\n\	Options are\n\		-N N		# image size in pixels (256)\n\		-R r_outer	# outer scale in m (infinite)\n\		-r r0		# Fried length in m (0.4)\n\		-D D		# telescope diameter (1.6)\n\		-e e		# obscuration = D_2 / D (0.0)\n\		-o opfile	# output file\n\		-z zmax		# upper limit for integerized z (N/2)\n\		-d dz		# step in integer z (1)\n\		-i imname	# output image 'imname' and exit\n\		-g xg yg	# location of the guide star\n\\n\	Output is a table (in lc or human readable format) containing:\n\		z		# argument of transfer function (in m)\n\		S(z)		# atmospheric phase structure function\n\		gknatl		# atmospheric OTF = exp(-S/2)\n\		gkdiff		# diffraction limited OTF\n\		gktilt		# fast guiding OTF\n\		gkfried		# Fried approximation\n\	except with -i option in which case it will output FITS image\n\	'imname' which can be one of\n\		T, S, Sg, TT, TTxS, WxS, TxT\n\\n\	Currently, -g option only works with pure Kolmogorov (infinite outer\n\	scale) spectrum.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file makeotf.c.
Function Documentation
void gradx (float ** f, int N1, int N2, float ** fx)
Definition at line 303 of file makeotf.c.
References f, N1, N2, x, and y.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 57 of file makeotf.c.
References alloc_fft(), allocFloatArray(), argsinit(), argsToString(), ccf(), e, error_exit, exit(), fft_type, fits, flag, FLOAT_PIXTYPE, forward_fft(), getargd(), getargi(), getargs(), getflag(), gradx(), M1, M2, mult(), N, N2, new2Dfitsheader(), pixsize(), r, read2Dfloatimage(), S, usage, write2Dfloatimage(), x, xp(), xx, y, yy, and z.
void mult (float ** f, int N1, int N2, float fac)
Definition at line 314 of file makeotf.c.
References f, N1, N2, x, and y.
Referenced by fan(), and main().
void zero (float ** f, int N1, int N2)
Definition at line 326 of file makeotf.c.
References f, N1, N2, x, and y.
Referenced by fk425m(), fk524m(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.