makevonkarmanS.c
NAME
makevonkarmanS.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'utils/error.h'
#include 'utils/args.h'
#include 'imlib/fits.h'
Defines
#define usage '\n\n\n\NAME\n\	makevonkarmanS --- von Karman structure function\n\SYNOPSIS\n\	makevonkarmanS R r0 dz Nz [-N N] [-d dy] [-y ystar]\n\\n\DESCRIPTION\n\	'makevonkarmanS' computes the function\n\\n\	S(z) = r0^(5/3) z^(-5/3) sum dy y (y^2 + (2 pi z / R)^2)^(-11/6)\n\		(1 - J0(y) exp(-(y / ystar)^2))\n\\n\	for z = iz * dz and 0 <= iz < Nz.\n\\n\	Options are:\n\		-N	Ny	# number of steps in y (10000)\n\		-d	dy	# step size in y (0.01)\n\		-y	ystar	# integration parameter (50)\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	makevonkarmanS --- von Karman structure function\n\SYNOPSIS\n\	makevonkarmanS R r0 dz Nz [-N N] [-d dy] [-y ystar]\n\\n\DESCRIPTION\n\	'makevonkarmanS' computes the function\n\\n\	S(z) = r0^(5/3) z^(-5/3) sum dy y (y^2 + (2 pi z / R)^2)^(-11/6)\n\		(1 - J0(y) exp(-(y / ystar)^2))\n\\n\	for z = iz * dz and 0 <= iz < Nz.\n\\n\	Options are:\n\		-N	Ny	# number of steps in y (10000)\n\		-d	dy	# step size in y (0.01)\n\		-y	ystar	# integration parameter (50)\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file makevonkarmanS.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 35 of file makevonkarmanS.c.
References argsinit(), argsToString(), b, dy, error_exit, exit(), flag, FLAG_ARG, getargd(), getargi(), getflag(), N, nextargtype(), S, usage, y, yy, and z.
Author
Generated automatically by Doxygen for imcat from the source code.