makegausskernel.c
NAME
makegausskernel.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../fftlib/myfft.h'
#include '../../imlib/fits.h'
#include '../../utils/arrays.h'
Defines
#define usage '\n\n\NAME\n\	makegausskernel --- calculate the kernel for gaussian psf\n\\n\SYNOPSIS\n\	makegausskernel alpha beta sigma rf [N1 N2]\n\\n\DESCRIPTION\n\	'makegausskernel' computes kernel K_alpha beta for the polarisation\n\	for gaussian psf.\n\	rf is the scale length for the gaussian weight function.\n\	sigma is the scale length for the psf.\n\	By default N1 - N2 = 256.\n\\n'
Functions
main (int argc, char *argv[])
int goodindex (int x)
Define Documentation
#define usage '\n\n\NAME\n\	makegausskernel --- calculate the kernel for gaussian psf\n\\n\SYNOPSIS\n\	makegausskernel alpha beta sigma rf [N1 N2]\n\\n\DESCRIPTION\n\	'makegausskernel' computes kernel K_alpha beta for the polarisation\n\	for gaussian psf.\n\	rf is the scale length for the gaussian weight function.\n\	sigma is the scale length for the psf.\n\	By default N1 - N2 = 256.\n\\n'
Definition at line 5 of file makegausskernel.c.
Function Documentation
int goodindex (int x)
Definition at line 98 of file makegausskernel.c.
References x.
main (int argc, char * argv[])
Definition at line 28 of file makegausskernel.c.
References add_comment(), allocFloatArray(), alpha, exit(), fits, FLOAT_PIXTYPE, goodindex(), i, ix, j, K, l, M, m, N1, N2, new2Dfitsheader(), r, sigma, usage, w, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.