makeobs_inertial.c
NAME
makeobs_inertial.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
#include 'Ffunc.h'
#include 'orbitutils/gaussdev.h'
Defines
#define usage '\nNAME\n\	makeobs_inertial - make a set of observations for an inertial observatory\n\\n\SYNOPSIS\n\	makeobs_inertial dt sigma\n\\n\DESCRIPTION\n\	makeobs_inertial reads an lc format catalog from stdin containing at least\n\	re[3], ve[3], ra[3], va[3], these being the position and velocity of\n\	the earth and the asteroid at t=0. It then generates a catalog\n\	containing direction of the asteroid at times t = -dt, 0, +dt\n\	and those times. The catalog also contains, the position of the\n\	earth re[] and the observatory rho[] wrt the earth at those times.\n\\n\	Times are given in units of earths dynamical time (approx 58 days).\n\	Distances are in AU.\n\\n\SEE ALSO\n\	maketestpscoords.pl laplace3\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	makeobs_inertial - make a set of observations for an inertial observatory\n\\n\SYNOPSIS\n\	makeobs_inertial dt sigma\n\\n\DESCRIPTION\n\	makeobs_inertial reads an lc format catalog from stdin containing at least\n\	re[3], ve[3], ra[3], va[3], these being the position and velocity of\n\	the earth and the asteroid at t=0. It then generates a catalog\n\	containing direction of the asteroid at times t = -dt, 0, +dt\n\	and those times. The catalog also contains, the position of the\n\	earth re[] and the observatory rho[] wrt the earth at those times.\n\\n\	Times are given in units of earths dynamical time (approx 58 days).\n\	Distances are in AU.\n\\n\SEE ALSO\n\	maketestpscoords.pl laplace3\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 8 of file makeobs_inertial.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 32 of file makeobs_inertial.c.
References copy(), diff(), dr, exit(), fprintvec(), gaussdev(), ge(), i, ipf, length(), makedddotr(), n, nt, ra, re, rho, scale(), sigma, t, and usage.
Author
Generated automatically by Doxygen for imcat from the source code.