makemockimage.c
NAME
makemockimage.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'imlib/fits.h'
#include 'utils/error.h'
#include 'utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	makemockimage --- generate mock deep CCD image\n\\n\SYNOPSIS\n\	makemockimage [option...]\n\		-n 	N1 N2		# size of image (1024, 1024)\n\		-p	pixsize		# size of a pixel in arcsec (0.2)\n\		-x 	xname		# get position from 2 vector input variable 'xname'\n\		-phi 	phiname		# get position angle from input variable 'phiname'\n\		-mu 	muname		# get position angle from input variable 'muname'\n\		-seed	seed		# seed for random numbers (1)\n\\n\DESCRIPTION\n\	\'makemockimage\' reads a catalogue of containing size\n\	'theta' and central surface brightness 'csb' (perhaps generated\n\	by 'makecosmocat') information and generates a fits\n\	image containing exponential disks of random orientation.\n\\n\	By default, makemockimage will generate uniform random position\n\	x, position angle phi and orientation mu (the latter being the\n\	cosine of the angle between the disk polar axis and the line\n\	of sight) but you can use -x, -phi and -mu options to\n\	read these from the input catalogue instead.\n\\n\	For dust free disk galaxies one would expect the surface\n\	brighness to vary with orientation as 1 / mu. However, images\n\	made in this way look quite unrealistic, with way too many bright\n\	edge on things, so in the default mode we take the 'optically\n\	thick' approximation and don't scale the csb.\n\\n\	If used with makecosmocat with default parameters, the flux of\n\	objects in the resulting images with number density like that of\n\	R=24 galaxies (about 5e4 per square degree) is approximately 0.4.\n\	Equivalently, running 'apphot -z 23.0' on a catalog generated\n\	from such an image should give sensible galaxy counts.\n\\n\SEE ALSO\n\	makecosmocat\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define THETA_MAX 8
#define RAND ((double)rand())/RAND_MAX
Functions
double drand48 ()
void addgalaxy (double x0, double y0, double theta, double csb, double phi, double mu, float **f, int N1, int N2)
int main (int argc, char *argv[])
Define Documentation
#define RAND ((double)rand())/RAND_MAX
Definition at line 58 of file makemockimage.c.
Referenced by main().
#define THETA_MAX 8
Definition at line 56 of file makemockimage.c.
Referenced by addgalaxy().
#define usage '\n\n\n\NAME\n\	makemockimage --- generate mock deep CCD image\n\\n\SYNOPSIS\n\	makemockimage [option...]\n\		-n 	N1 N2		# size of image (1024, 1024)\n\		-p	pixsize		# size of a pixel in arcsec (0.2)\n\		-x 	xname		# get position from 2 vector input variable 'xname'\n\		-phi 	phiname		# get position angle from input variable 'phiname'\n\		-mu 	muname		# get position angle from input variable 'muname'\n\		-seed	seed		# seed for random numbers (1)\n\\n\DESCRIPTION\n\	\'makemockimage\' reads a catalogue of containing size\n\	'theta' and central surface brightness 'csb' (perhaps generated\n\	by 'makecosmocat') information and generates a fits\n\	image containing exponential disks of random orientation.\n\\n\	By default, makemockimage will generate uniform random position\n\	x, position angle phi and orientation mu (the latter being the\n\	cosine of the angle between the disk polar axis and the line\n\	of sight) but you can use -x, -phi and -mu options to\n\	read these from the input catalogue instead.\n\\n\	For dust free disk galaxies one would expect the surface\n\	brighness to vary with orientation as 1 / mu. However, images\n\	made in this way look quite unrealistic, with way too many bright\n\	edge on things, so in the default mode we take the 'optically\n\	thick' approximation and don't scale the csb.\n\\n\	If used with makecosmocat with default parameters, the flux of\n\	objects in the resulting images with number density like that of\n\	R=24 galaxies (about 5e4 per square degree) is approximately 0.4.\n\	Equivalently, running 'apphot -z 23.0' on a catalog generated\n\	from such an image should give sensible galaxy counts.\n\\n\SEE ALSO\n\	makecosmocat\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file makemockimage.c.
Function Documentation
void addgalaxy (double x0, double y0, double theta, double csb, double phi, double mu, float ** f, int N1, int N2)
Definition at line 164 of file makemockimage.c.
References dx, dy, f, ix, N1, N2, phi, THETA_MAX, x, and y.
Referenced by main().
double drand48 ()
int main (int argc, char * argv[])
Definition at line 63 of file makemockimage.c.
References add_comment(), addgalaxy(), allocFloatArray(), error_exit, exit(), f, fits, FLOAT_PIXTYPE, lcpipe, N1, N2, new2Dfitsheader(), phi, pixsize(), RAND, usage, write2Dfloatimage(), X, x, Y, and y.
Author
Generated automatically by Doxygen for imcat from the source code.