makechart.h
NAME
makechart.h -
SYNOPSIS
Functions
void drawcursor (double x, double y, float **f, int N1, int N2)
void drawcircle (double x, double y, float r, float **f, int N1, int N2)
void zapcircle (double x, double y, float r, float **f, int N1, int N2)
void drawcollar (int i, int j, float **f, int N1, int N2)
void drawellipse (double x, double y, float r, float e, float phi0, float **f, int N1, int N2)
void zapellipse (double x, double y, float r, float e, float phi0, float **f, int N1, int N2)
Function Documentation
void drawcircle (double x, double y, float r, float ** f, int N1, int N2)
Definition at line 301 of file makechart.c.
References circval, f, i, j, N1, phi, PI, r, x, and y.
Referenced by drawcollar(), and main().
void drawcollar (int i, int j, float ** f, int N1, int N2)
Definition at line 266 of file makechart.c.
References cursval, d, drawcircle(), f, i, j, N1, N2, NE, NW, SE, and SW.
Referenced by main().
void drawcursor (double x, double y, float ** f, int N1, int N2)
Definition at line 245 of file makechart.c.
References CURS_MAX, CURS_MIN, cursval, d, f, i, j, N1, N2, x, and y.
Referenced by main().
void drawellipse (double x, double y, float r, float e, float phi0, float ** f, int N1, int N2)
Definition at line 325 of file makechart.c.
References a, b, c, circval, e, f, I(), i, j, N1, phi, PI, r, x, and y.
Referenced by main().
void zapcircle (double x, double y, float r, float ** f, int N1, int N2)
Definition at line 356 of file makechart.c.
References dx, dy, f, i, j, MAGIC, N1, r, x, and y.
Referenced by main().
void zapellipse (double x, double y, float r, float e, float phi0, float ** f, int N1, int N2)
Definition at line 378 of file makechart.c.
References a, b, c, circval, dx, dy, e, f, I(), i, j, MAGIC, N1, phi, r, x, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.