makecolourimage.c
NAME
makecolourimage.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	makecolourimage --- combines 2 or 3 images into a color fits image\n\\n\SYNOPSIS\n\	makecolourimage [options....] \n\		-o offsetsfile		# file containing positional offsets\n\		-f fits1 colorname1	# name of 1st image and its colour\n\		-f fits2 colorname2	# name of 2nd image and its colour....\n\\n\DESCRIPTION\n\	\'makecolourimage\' combines 2 or 3 images into a single color fits\n\	file using offsets in offsets.out if supplied.\n\	Names are arbitrary. Files should be supplied in increasing\n\	order of bandpass frequency.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAX_COLOURS 3
Functions
int main (int argc, char *argv[])
Define Documentation
#define MAX_COLOURS 3
Definition at line 32 of file makecolourimage.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	makecolourimage --- combines 2 or 3 images into a color fits image\n\\n\SYNOPSIS\n\	makecolourimage [options....] \n\		-o offsetsfile		# file containing positional offsets\n\		-f fits1 colorname1	# name of 1st image and its colour\n\		-f fits2 colorname2	# name of 2nd image and its colour....\n\\n\DESCRIPTION\n\	\'makecolourimage\' combines 2 or 3 images into a single color fits\n\	file using offsets in offsets.out if supplied.\n\	Names are arbitrary. Files should be supplied in increasing\n\	order of bandpass frequency.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file makecolourimage.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 34 of file makecolourimage.c.
References allocFloatArray(), appendcomment(), COM_LENGTH, copyfitsheader(), error_exit, exit(), fits, i, ipf, j, line, MAX_COLOURS, fitsheader::n, N1, N2, fitsheader::ndim, newtextcomment(), readfitsheader(), readfitsline(), usage, fitscomment::value, writefitsheader(), writefitsline(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.