make2Dotf.c
NAME
make2Dotf.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'imlib/fits.h'
#include 'utils/error.h'
#include 'utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	make2Dotf --- make 2-D fast guiding otf with offset guide star\n\SYNOPSIS\n\	make2Dotf [-N N] [-R r_outer] [-r r0] [-D D] [-o opfile] [-z zmax] [-i imname]\n\\n\DESCRIPTION\n\	'make2Dotf' computes the OTF gk(z) for perfect fast guiding.\n\\n\	Options are\n\		-N N		# image size in pixels (512)\n\		-r r0		# Fried length in m (0.2)\n\		-D D		# telescope diameter (1.0)\n\		-z zmax		# upper limit for integerized z (N/2)\n\		-d dz		# step in integer z (2)\n\		-p nphi		# number of rays in azimuthal angle (5)\n\		-g rg		# distance to guide star (1.0)\n\\n\	Output is a fits image of the OTF.\n\\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	make2Dotf --- make 2-D fast guiding otf with offset guide star\n\SYNOPSIS\n\	make2Dotf [-N N] [-R r_outer] [-r r0] [-D D] [-o opfile] [-z zmax] [-i imname]\n\\n\DESCRIPTION\n\	'make2Dotf' computes the OTF gk(z) for perfect fast guiding.\n\\n\	Options are\n\		-N N		# image size in pixels (512)\n\		-r r0		# Fried length in m (0.2)\n\		-D D		# telescope diameter (1.0)\n\		-z zmax		# upper limit for integerized z (N/2)\n\		-d dz		# step in integer z (2)\n\		-p nphi		# number of rays in azimuthal angle (5)\n\		-g rg		# distance to guide star (1.0)\n\\n\	Output is a fits image of the OTF.\n\\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file make2Dotf.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 37 of file make2Dotf.c.
References allocFloatArray(), argsinit(), error_exit, exit(), fits, flag, FLOAT_PIXTYPE, getargd(), getargi(), getflag(), ix, k, lcpipe, N, new2Dfitsheader(), phi, usage, write2Dfloatimage(), and z.
Author
Generated automatically by Doxygen for imcat from the source code.