makedensity.c
NAME
makedensity.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../catlib/cat.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/args.h'
#include '../../utils/stats_stuff.h'
Defines
#define usage '\n\n\n\NAME\n\	makedensity --- bin catalogue into FITS image\n\\n\SYNOPSIS\n\	makedensity r x1 x2 nx ..... [-v val] [-c]\n\\n\DESCRIPTION\n\	'makedensity' reads a catalogue from stdin, which must\n\	contain at least some N >=1 dimensional vector and sums the counts\n\	of objects (or with the -v option sums some specified object value) into\n\	bins in a floating point FITS image which is sent to stdout.\n\\n\	The first argument is the name of the coordinate vector. This is then\n\	followed by N triplets giving, starting with the fastest coordinate dimension,\n\	the range of dimension to be mapped and the corresponding number of pixels in\n\	the output image.\n\\n\	Use the -v option to sum some numerical object value named 'val'. If val is a scalar\n\	then the output image will have the same dimensionality as the coordinate\n\	vector, but if val is a vector or matrix then the output image will be of higher\n\	dimensionality and contain a set of images containing the the sums of the\n\	various components of val. For example, if the input catalogue contains\n\	a three dimensional coordinate r[3] = {x,y,z}, and a M1 x M2 matrix valued quantity\n\	m[M2][M1], then the result is a 5-dimensional image f[N5][N4][N3][N2][N1]\n\	with N5 = M2, N4 = M1 (and N3, N2, N1 given in the command line arguments).\n\\n\	With the -c option we assign the `charge' (v or unity) to four neighbouring\n\	pixels. This is done in such a way that if dx = (x2 - x1) / nx etc then a point\n\	with x = ix + dx / dx is assigned entirely to the pixel with index ix. The\n\	model here is that the zeroth pixel extends from x = 0 to x = dx, etc.\n\\n\	The coordinate ranges are stored as FITS header records named\n\		x0min, x0max, x1min, x1max, ....\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
#define QSCALE_TINY 1.e-8
Functions
void assigncharge (int level)
void assigncharge_cic (int level, int xoff, double q)
void setf (int level, int xoff, void *v)
main (int argc, char *argv[])
Variables
float * f
int * nx
int fsize [MAX_DIMS+1]
int vndim
int * vdim
int xdim
int gxoff
double * x
double * x1
double * x2
double * dx
double gq
void * gv
char * vname
Define Documentation
#define QSCALE_TINY 1.e-8
Definition at line 65 of file makedensity.c.
Referenced by assigncharge_cic().
#define usage '\n\n\n\NAME\n\	makedensity --- bin catalogue into FITS image\n\\n\SYNOPSIS\n\	makedensity r x1 x2 nx ..... [-v val] [-c]\n\\n\DESCRIPTION\n\	'makedensity' reads a catalogue from stdin, which must\n\	contain at least some N >=1 dimensional vector and sums the counts\n\	of objects (or with the -v option sums some specified object value) into\n\	bins in a floating point FITS image which is sent to stdout.\n\\n\	The first argument is the name of the coordinate vector. This is then\n\	followed by N triplets giving, starting with the fastest coordinate dimension,\n\	the range of dimension to be mapped and the corresponding number of pixels in\n\	the output image.\n\\n\	Use the -v option to sum some numerical object value named 'val'. If val is a scalar\n\	then the output image will have the same dimensionality as the coordinate\n\	vector, but if val is a vector or matrix then the output image will be of higher\n\	dimensionality and contain a set of images containing the the sums of the\n\	various components of val. For example, if the input catalogue contains\n\	a three dimensional coordinate r[3] = {x,y,z}, and a M1 x M2 matrix valued quantity\n\	m[M2][M1], then the result is a 5-dimensional image f[N5][N4][N3][N2][N1]\n\	with N5 = M2, N4 = M1 (and N3, N2, N1 given in the command line arguments).\n\\n\	With the -c option we assign the `charge' (v or unity) to four neighbouring\n\	pixels. This is done in such a way that if dx = (x2 - x1) / nx etc then a point\n\	with x = ix + dx / dx is assigned entirely to the pixel with index ix. The\n\	model here is that the zeroth pixel extends from x = 0 to x = dx, etc.\n\\n\	The coordinate ranges are stored as FITS header records named\n\		x0min, x0max, x1min, x1max, ....\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file makedensity.c.
Function Documentation
void assigncharge (int level)
Definition at line 204 of file makedensity.c.
References dx, f, fsize, gq, gv, gxoff, ix, nx, setf(), vname, vndim, x, and x1.
Referenced by main().
void assigncharge_cic (int level, int xoff, double q)
Definition at line 225 of file makedensity.c.
References dx, f, fsize, gq, gv, ix, nx, QSCALE_TINY, setf(), vname, vndim, x, x1, and xx.
Referenced by main().
main (int argc, char * argv[])
Definition at line 67 of file makedensity.c.
References add_comment(), object::addrlist, allocobjectcontents(), appendcomment(), argserror(), argsinit(), assigncharge(), assigncharge_cic(), byteswapline(), connectobjecttocathead(), item::dim, dx, error_exit, exit(), fitsheader::extpixtype, f, fits, flag, FLOAT_PIXTYPE, fsize, getargd(), getargi(), getargs(), getflag(), getobjectitem(), getobjectitemindex(), gq, gv, gxoff, i, item::itype, ix, fitsheader::n, NATIVE_BYTE_ORDER, fitsheader::ndim, item::ndim, newfitsheader(), newnumericcomment(), newobject(), nextargtype(), NUM_TYPE, nx, fitsheader::opbyteorder, pixsize(), readcathead(), readobject(), TEXT_ARG, usage, vdim, vname, vndim, writefitsheader(), x, x1, x2, and xdim.
void setf (int level, int xoff, void * v)
Definition at line 257 of file makedensity.c.
References f, fsize, gq, i, v, vdim, vndim, and xdim.
Referenced by assigncharge(), and assigncharge_cic().
Variable Documentation
double * dx [static]
Definition at line 61 of file makedensity.c.
float* f [static]
Definition at line 59 of file makedensity.c.
int fsize[MAX_DIMS + 1] [static]
Definition at line 60 of file makedensity.c.
Referenced by assigncharge(), assigncharge_cic(), main(), and setf().
double gq [static]
Definition at line 61 of file makedensity.c.
Referenced by assigncharge(), assigncharge_cic(), main(), and setf().
void* gv [static]
Definition at line 62 of file makedensity.c.
Referenced by assigncharge(), assigncharge_cic(), and main().
int gxoff [static]
Definition at line 60 of file makedensity.c.
Referenced by assigncharge(), and main().
int* nx [static]
Definition at line 60 of file makedensity.c.
int * vdim [static]
Definition at line 60 of file makedensity.c.
Referenced by main(), and setf().
char* vname [static]
Definition at line 63 of file makedensity.c.
Referenced by assigncharge(), assigncharge_cic(), and main().
int vndim [static]
Definition at line 60 of file makedensity.c.
Referenced by assigncharge(), assigncharge_cic(), main(), and setf().
double* x [static]
Definition at line 61 of file makedensity.c.
double * x1 [static]
Definition at line 61 of file makedensity.c.
Referenced by assigncharge(), assigncharge_cic(), and main().
double * x2 [static]
Definition at line 61 of file makedensity.c.
Referenced by main().
int xdim [static]
Definition at line 60 of file makedensity.c.
Referenced by main(), and setf().
Author
Generated automatically by Doxygen for imcat from the source code.