.TH "makedddotr.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
makedddotr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include 'vectors.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmakedddotr\fP (double *dddotr, double *\fBr\fP, double *\fBv\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void makedddotr (double * dddotr, double * r, double * v)"
.PP
Definition at line 9 of file makedddotr.c.
.PP
References dot(), i, r, and v.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
