makeshearimage.c
NAME
makeshearimage.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../imlib/fits.h'
#include '../../utils/arrays.h'
Defines
#define usage '\n\NAME\n\	makeshearimage --- generate a shear image from catalogue\n\\n\SYNOPSIS\n\	makeshearimage [options...]\n\		-N N1 N2	# size of image (128,128)\n\		-x xname	# name for spatial coordinate ('x')\n\		-X dx		# pixel size in x-coords (16.0)\n\		-o x0 y0	# origin in x-space (0.0, 0.0)\n\		-r x1 x2 y1 y2	# box for calculating nbar\n\		-e ename	# name for polarisation ('e')\n\		-p psh		# polarisability (1.0)\n\		-n nbar		# density of points in x-space\n\\n\DESCRIPTION\n\	'makeshearimage' reads a catalogue which must contain a spatial\n\	2-vector coordinate ('x' by default) and a 2-vector\n\	polarisation ('e' by default), and creates a N1 by (2 N2)\n\	fits image which is a simple binned average of the input\n\	shear values. The shear is defined as\n\		gamma_i = e_i / psh,\n\	and gamma_0 and gamma_1 are stored in the first and last N2 lines\n\	of the output image respectively.\n\	By default the density of points is estimated as the number\n\	of objects divided by the area of the image (in x-coord units)\n\	but you can supply an alternative x-rectange with the -r\n\	option.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	makeshearimage --- generate a shear image from catalogue\n\\n\SYNOPSIS\n\	makeshearimage [options...]\n\		-N N1 N2	# size of image (128,128)\n\		-x xname	# name for spatial coordinate ('x')\n\		-X dx		# pixel size in x-coords (16.0)\n\		-o x0 y0	# origin in x-space (0.0, 0.0)\n\		-r x1 x2 y1 y2	# box for calculating nbar\n\		-e ename	# name for polarisation ('e')\n\		-p psh		# polarisability (1.0)\n\		-n nbar		# density of points in x-space\n\\n\DESCRIPTION\n\	'makeshearimage' reads a catalogue which must contain a spatial\n\	2-vector coordinate ('x' by default) and a 2-vector\n\	polarisation ('e' by default), and creates a N1 by (2 N2)\n\	fits image which is a simple binned average of the input\n\	shear values. The shear is defined as\n\		gamma_i = e_i / psh,\n\	and gamma_0 and gamma_1 are stored in the first and last N2 lines\n\	of the output image respectively.\n\	By default the density of points is estimated as the number\n\	of objects divided by the area of the image (in x-coord units)\n\	but you can supply an alternative x-rectange with the -r\n\	option.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file makeshearimage.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 43 of file makeshearimage.c.
References add_comment(), allocFloatArray(), dx, e, error_exit, exit(), fits, FLOAT_PIXTYPE, gamma1(), ix, lcpipe, fitsheader::n, N1, N2, fitsheader::ndim, new2Dfitsheader(), usage, writefitsheader(), writefitsline(), writefitstail(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.