make_image.h
NAME
make_image.h -
SYNOPSIS
Functions
int check_args (int argc, char *argv[])
void add_population (int N1, int N2, int n, float f0, float r, int type)
void add_noise (int N1, int N2, float sigma)
void add_bad_col (int N1, int N2, int col)
float gasdev (void)
float ran0 (int *idum)
Function Documentation
void add_bad_col (int N1, int N2, int col)
Definition at line 243 of file make_image.c.
References f, j, MAGIC, N1, N2, and ncolours.
Referenced by main().
void add_noise (int N1, int N2, float sigma)
Definition at line 318 of file make_image.c.
References f, gasdev(), i, j, N1, N2, ncolours, and sigma.
void add_population (int N1, int N2, int n, float f0, float r, int type)
Definition at line 258 of file make_image.c.
References drand48(), error_exit, EXP, f, GAU, i, j, n, N1, N2, ncolours, and type.
Referenced by main().
int check_args (int argc, char * argv[])
Definition at line 190 of file make_image.c.
Referenced by main().
float gasdev (void)
Definition at line 607 of file ic.c.
float ran0 (int * idum)
Author
Generated automatically by Doxygen for imcat from the source code.