maketestshear.c
NAME
maketestshear.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../imlib/fits.h'
#include '../../utils/arrays.h'
Defines
#define usage '\n\NAME\n\	maketestshear --- make a test shear field\n\\n\SYNOPSIS\n\	maketestshear [options...]\n\		-n N	 	# image size (256)\n\		-o i0 j0	# lens position (128,128)\n\		-c rc		# core radius (50)\n\		-k		# generate kappa\n\		-g		# generate gradkappa\n\\n\DESCRIPTION\n\	'maketestshear' generates a float format fits image of shear\n\	for kappa = exp(-r^2 / 2 r_c^2) model\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
#define EPS 1.e-10
#define GAMMA_MODE 0
#define KAPPA_MODE 1
#define GRAD_KAPPA_MODE 2
Functions
main (int argc, char *argv[])
Define Documentation
#define EPS 1.e-10
Definition at line 32 of file maketestshear.c.
#define GAMMA_MODE 0
Definition at line 34 of file maketestshear.c.
Referenced by main().
#define GRAD_KAPPA_MODE 2
Definition at line 36 of file maketestshear.c.
Referenced by main().
#define KAPPA_MODE 1
Definition at line 35 of file maketestshear.c.
Referenced by main().
#define usage '\n\NAME\n\	maketestshear --- make a test shear field\n\\n\SYNOPSIS\n\	maketestshear [options...]\n\		-n N	 	# image size (256)\n\		-o i0 j0	# lens position (128,128)\n\		-c rc		# core radius (50)\n\		-k		# generate kappa\n\		-g		# generate gradkappa\n\\n\DESCRIPTION\n\	'maketestshear' generates a float format fits image of shear\n\	for kappa = exp(-r^2 / 2 r_c^2) model\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
Definition at line 5 of file maketestshear.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 38 of file maketestshear.c.
References add_comment(), allocFloatArray(), EPS, exit(), fits, FLOAT_PIXTYPE, gamma1(), gamma2(), GAMMA_MODE, GRAD_KAPPA_MODE, i, j, KAPPA_MODE, fitsheader::n, N, fitsheader::ndim, new2Dfitsheader(), usage, write2Dfloatimage(), writefitsheader(), writefitsline(), writefitstail(), x, Y, and y.
Author
Generated automatically by Doxygen for imcat from the source code.