makepeff.c
NAME
makepeff.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <float.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/ipbuff.h'
#include '../../utils/arrays.h'
#include '../../utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	makepeff --- compute effective polarisability\n\\n\SYNOPSIS\n\	makepeff [options...]\n\\n\DESCRIPTION\n\	'makepeff' first reads from stdin a catalogue which\n\	must contain at least the following entries:\n\		F	# windowed flux\n\		q0	# size\n\		q[2]	# polarisation\n\		R[2]	# flux response\n\		P0[2]	# size response\n\		P[2][2]	# polarisation response\n\	as created by 'getshapes2'.\n\	It bins appropriate combinations of these in a cubical\n\	array in F, p0, q space and computes P_effective.\n\\n\OPTIONS\n\	Options are\n\		-u			# print this message\n\		-F logF1 logF2 nF	# range of log_10 F and number of bins defaults to 2 3.6 8\n\		-q q1 q2 nq		# range of |q| and number of bins defaults to 0.0 0.5 32\n\		-Q q01 q02 nq0		# range of q0 and number of bins defaults to 2.5 3.5 32\n\\n\OUTPUT\n\	Output is a 3-plane FITS file with planes containing\n\		plane 0		n	# number of objects in cell = sum 1\n\		plane 1		nP	# sum P_eff\n\		plane 2		nq	# sum sqrt(q.q)\n\		plane 3		nPbar	# sum P\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Functions
float *** alloc3Darray (int N1, int N2, int N3)
float *** boxavg3D (float ***f, int N1, int N2, int N3)
float *** grad3D (float ***f, int dir, double dx, int N1, int N2, int N3)
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	makepeff --- compute effective polarisability\n\\n\SYNOPSIS\n\	makepeff [options...]\n\\n\DESCRIPTION\n\	'makepeff' first reads from stdin a catalogue which\n\	must contain at least the following entries:\n\		F	# windowed flux\n\		q0	# size\n\		q[2]	# polarisation\n\		R[2]	# flux response\n\		P0[2]	# size response\n\		P[2][2]	# polarisation response\n\	as created by 'getshapes2'.\n\	It bins appropriate combinations of these in a cubical\n\	array in F, p0, q space and computes P_effective.\n\\n\OPTIONS\n\	Options are\n\		-u			# print this message\n\		-F logF1 logF2 nF	# range of log_10 F and number of bins defaults to 2 3.6 8\n\		-q q1 q2 nq		# range of |q| and number of bins defaults to 0.0 0.5 32\n\		-Q q01 q02 nq0		# range of q0 and number of bins defaults to 2.5 3.5 32\n\\n\OUTPUT\n\	Output is a 3-plane FITS file with planes containing\n\		plane 0		n	# number of objects in cell = sum 1\n\		plane 1		nP	# sum P_eff\n\		plane 2		nq	# sum sqrt(q.q)\n\		plane 3		nPbar	# sum P\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file makepeff.c.
Function Documentation
float *** alloc3Darray (int N1, int N2, int N3)
Definition at line 221 of file makepeff.c.
References error_exit, f, i, j, N1, N2, and size.
float *** boxavg3D (float *** f, int N1, int N2, int N3)
Definition at line 244 of file makepeff.c.
References alloc3Darray(), f, N1, and N2.
float *** grad3D (float *** f, int dir, double dx, int N1, int N2, int N3)
Definition at line 268 of file makepeff.c.
References alloc3Darray(), dir, dx, error_exit, f, N1, and N2.
main (int argc, char * argv[])
Definition at line 57 of file makepeff.c.
References add_comment(), alloc3Darray(), appendcomment(), argsinit(), boxavg3D(), buff, error_exit, exit(), fits, flag, FLOAT_PIXTYPE, getargf(), getargi(), getflag(), grad3D(), ipf, n, newfitsheader(), newnumericcomment(), usage, writefitscube(), writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.