makesubimage.c
NAME
makesubimage.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	makesubimage --- extracts a subimage from a fits file\n\\n\SYNOPSIS\n\	makesubimage x y dx dy [options...]\n\		-o	# set unmapped pixels to zero\n\\n\DESCRIPTION\n\	'makesubimage' extracts a dx x dy subimage with\n\	origin at (x,y) from the input image. By default,\n\	if the subimage extends beyond the source image\n\	then extra pixels are set to MAGIC. Use -o\n\	option to force these to zero.\n\	Reads from stdin, writes to stdout.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
Functions
int main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 31 of file makesubimage.c.
#define usage '\n\n\n\NAME\n\	makesubimage --- extracts a subimage from a fits file\n\\n\SYNOPSIS\n\	makesubimage x y dx dy [options...]\n\		-o	# set unmapped pixels to zero\n\\n\DESCRIPTION\n\	'makesubimage' extracts a dx x dy subimage with\n\	origin at (x,y) from the input image. By default,\n\	if the subimage extends beyond the source image\n\	then extra pixels are set to MAGIC. Use -o\n\	option to force these to zero.\n\	Reads from stdin, writes to stdout.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file makesubimage.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 33 of file makesubimage.c.
References add_comment(), copyfitsheader(), error_exit, exit(), i, j, M1, M2, MAGIC, fitsheader::n, N1, N2, readfitsheader(), readfitsline(), skiplines(), usage, writefitsheader(), writefitsline(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.