makekernel.c
NAME
makekernel.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../fftlib/myfft.h'
#include '../../imlib/fits.h'
#include '../../utils/arrays.h'
Defines
#define usage '\n\n\NAME\n\	makekernel --- calculate the kernel for the polarizability\n\\n\SYNOPSIS\n\	makekernel [-w rf | -W alpha rf | -K alpha beta rf | -Z alpha beta rf | -R alpha rf]\n\\n\DESCRIPTION\n\	'makekernel' reads a psf image from stdin and computes various\n\	kernels for the polarisation\n\\n\	Options are:\n\		-u			# print this message\n\		-w rf			# compute w\n\		-W alpha rf		# compute W_alpha\n\		-K alpha beta rf	# compute K_alpha beta\n\		-Z alpha beta rf	# compute Z_alpha beta\n\		-R alpha rf		# compute R_alpha \n\	rf is the scale length for the gaussian weight function.\n\\n\	With -w, -W, -Z options, only the size of the psf image is used.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n'
#define wMODE 0
#define KMODE 1
#define WMODE 2
#define RMODE 3
#define ZMODE 4
Functions
main (int argc, char *argv[])
int goodindex (int x)
Define Documentation
#define KMODE 1
Definition at line 39 of file makekernel.c.
Referenced by main().
#define RMODE 3
Definition at line 41 of file makekernel.c.
Referenced by main().
#define usage '\n\n\NAME\n\	makekernel --- calculate the kernel for the polarizability\n\\n\SYNOPSIS\n\	makekernel [-w rf | -W alpha rf | -K alpha beta rf | -Z alpha beta rf | -R alpha rf]\n\\n\DESCRIPTION\n\	'makekernel' reads a psf image from stdin and computes various\n\	kernels for the polarisation\n\\n\	Options are:\n\		-u			# print this message\n\		-w rf			# compute w\n\		-W alpha rf		# compute W_alpha\n\		-K alpha beta rf	# compute K_alpha beta\n\		-Z alpha beta rf	# compute Z_alpha beta\n\		-R alpha rf		# compute R_alpha \n\	rf is the scale length for the gaussian weight function.\n\\n\	With -w, -W, -Z options, only the size of the psf image is used.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n'
Definition at line 5 of file makekernel.c.
#define WMODE 2
Definition at line 40 of file makekernel.c.
Referenced by main().
#define wMODE 0
Definition at line 38 of file makekernel.c.
Referenced by main().
#define ZMODE 4
Definition at line 42 of file makekernel.c.
Referenced by main().
Function Documentation
int goodindex (int x)
Definition at line 313 of file makekernel.c.
References x.
Referenced by main().
main (int argc, char * argv[])
Definition at line 45 of file makekernel.c.
References A, add_comment(), alloc_fft(), allocFloatArray(), alpha, B, C, ccf(), exit(), fft_type, fits, forward_fft(), g(), goodindex(), i, ix, j, K, KMODE, l, M, m, N1, N2, r, read2Dfloatimage(), RMODE, usage, W, w, WMODE, wMODE, write2Dfloatimage(), and ZMODE.
Author
Generated automatically by Doxygen for imcat from the source code.