.TH "makesubimage.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
makesubimage.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include '../imlib/fits.h'\fP
.br
\fC#include '../utils/error.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	makesubimage --- extracts \fBa\fP subimage from \fBa\fP \fBfits\fP file\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	makesubimage x y \fBdx\fP \fBdy\fP [\fBoptions\fP...]\\\fBn\fP\\		-o	# set unmapped pixels to zero\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'makesubimage' extracts \fBa\fP \fBdx\fP x \fBdy\fP subimage with\\\fBn\fP\\	origin at (x,y) from the input image.  By default,\\\fBn\fP\\	if the subimage extends beyond the source image\\\fBn\fP\\	then extra pixels are set to MAGIC.  Use -o\\\fBn\fP\\	option to force these to zero.\\\fBn\fP\\	Reads from stdin, writes to stdout.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@cita.utoronto.ca\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.br
.ti -1c
.RI "#define \fBMAGIC\fP   FLOAT_MAGIC"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MAGIC   FLOAT_MAGIC"
.PP
Definition at line 31 of file makesubimage.c.
.SS "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	makesubimage --- extracts \fBa\fP subimage from \fBa\fP \fBfits\fP file\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	makesubimage x y \fBdx\fP \fBdy\fP [\fBoptions\fP...]\\\fBn\fP\\		-o	# set unmapped pixels to zero\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'makesubimage' extracts \fBa\fP \fBdx\fP x \fBdy\fP subimage with\\\fBn\fP\\	origin at (x,y) from the input image.  By default,\\\fBn\fP\\	if the subimage extends beyond the source image\\\fBn\fP\\	then extra pixels are set to MAGIC.  Use -o\\\fBn\fP\\	option to force these to zero.\\\fBn\fP\\	Reads from stdin, writes to stdout.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@cita.utoronto.ca\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 1 of file makesubimage.c.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 33 of file makesubimage.c.
.PP
References add_comment(), copyfitsheader(), error_exit, exit(), i, j, M1, M2, MAGIC, fitsheader::n, N1, N2, readfitsheader(), readfitsline(), skiplines(), usage, writefitsheader(), writefitsline(), and writefitstail().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
