.TH "makelist.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
makelist.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   'usage: makelist \fBnobj\fP [\fBxmin\fP \fBxmax\fP \fBymin\fP \fBymax\fP [\fBseed\fP]]\\\fBn\fP\\	lay down random objects within \fBa\fP \fBrectangle\fP.\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBdrand48\fP ()"
.br
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   'usage: makelist \fBnobj\fP [\fBxmin\fP \fBxmax\fP \fBymin\fP \fBymax\fP [\fBseed\fP]]\\\fBn\fP\\	lay down random objects within \fBa\fP \fBrectangle\fP.\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 8 of file makelist.c.
.SH "Function Documentation"
.PP 
.SS "double drand48 (void)"
.PP
.SS "main (int argc, char * argv[])"
.PP
Definition at line 13 of file makelist.c.
.PP
References drand48(), exit(), nobj, usage, xmax, xmin, ymax, and ymin.
.SH "Variable Documentation"
.PP 
.SS "double x"
.PP
Definition at line 11 of file makelist.c.
.SS "double y"
.PP
Definition at line 11 of file makelist.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
