makechart.c
NAME
makechart.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/stats_stuff.h'
#include 'makechart.h'
#include '../../catlib/cat.h'
Defines
#define usage '\n\n\n\NAME\n\	makechart - overlay FITS image with object markers\n\\n\SYNOPSIS\n\	makechart [option...] < catfile > fitsout\n\		-r rname a	# draw or zap disk\n\		-c 		# draw 16-32 pixel collar\n\		-s sf		# scrunch factor (1)\n\		-f image	# fitsfile \n\		-m mask		# maskfile \n\		-z		# zap circles or ellipses around object\n\		-e ename efac	# draw an ellipse\n\		-v circval	# paint circles etc this value (MAGIC)\n\\n\DESCRIPTION\n\	\'makechart\' draws boxes or crosshairs round objects\n\	Normally uses the image found in the cat header.\n\	-f option forces it to use fitsfile\n\	With -m option it draws rectangles from maskfile\n\	which must be an 'lc' format catalogue containing\n\	entries for a air of position vectors x1[2], x2[2]\n\	for bottom-left and top-right corners respectively.\n\	Use '-r rname a' to draw circle of radius a times the value of the object item\n\	'rname', so use e.g. '-r rh 3' for circles 3 times the half-light radius.\n\	Similarly, with -e option it will draw an ellipse with ellipticity\n\	efac times the object ellipticity and with sqrt(a b) equal\n\	to the radius as calculated above.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
#define CURS_MIN 8
#define CURS_MAX 16
#define DEF_CURSOR_VAL MAGIC
#define DEF_CIRCLE_VAL MAGIC
#define NW 0
#define NE 1
#define SE 2
#define SW 3
#define PI M_PI
Functions
main (int argc, char *argv[])
void drawcursor (double x, double y, float **f, int N1, int N2)
void drawcollar (int io, int jo, float **f, int N1, int N2)
void drawcircle (double x, double y, float r, float **f, int N1, int N2)
void drawellipse (double x, double y, float r, float e, float phi0, float **f, int N1, int N2)
void zapcircle (double x, double y, float r, float **f, int N1, int N2)
void zapellipse (double x, double y, float r, float e, float phi0, float **f, int N1, int N2)
Variables
float cursval
float circval
Define Documentation
#define CURS_MAX 16
Definition at line 50 of file makechart.c.
Referenced by drawcursor().
#define CURS_MIN 8
Definition at line 49 of file makechart.c.
Referenced by drawcursor().
#define DEF_CIRCLE_VAL MAGIC
Definition at line 52 of file makechart.c.
Referenced by main().
#define DEF_CURSOR_VAL MAGIC
Definition at line 51 of file makechart.c.
Referenced by main().
#define MAGIC FLOAT_MAGIC
Definition at line 47 of file makechart.c.
#define NE 1
Definition at line 54 of file makechart.c.
Referenced by drawcollar(), and main().
#define NW 0
Definition at line 53 of file makechart.c.
Referenced by drawcollar().
#define PI M_PI
Definition at line 299 of file makechart.c.
#define SE 2
Definition at line 55 of file makechart.c.
Referenced by drawcollar().
#define SW 3
Definition at line 56 of file makechart.c.
Referenced by drawcollar().
#define usage '\n\n\n\NAME\n\	makechart - overlay FITS image with object markers\n\\n\SYNOPSIS\n\	makechart [option...] < catfile > fitsout\n\		-r rname a	# draw or zap disk\n\		-c 		# draw 16-32 pixel collar\n\		-s sf		# scrunch factor (1)\n\		-f image	# fitsfile \n\		-m mask		# maskfile \n\		-z		# zap circles or ellipses around object\n\		-e ename efac	# draw an ellipse\n\		-v circval	# paint circles etc this value (MAGIC)\n\\n\DESCRIPTION\n\	\'makechart\' draws boxes or crosshairs round objects\n\	Normally uses the image found in the cat header.\n\	-f option forces it to use fitsfile\n\	With -m option it draws rectangles from maskfile\n\	which must be an 'lc' format catalogue containing\n\	entries for a air of position vectors x1[2], x2[2]\n\	for bottom-left and top-right corners respectively.\n\	Use '-r rname a' to draw circle of radius a times the value of the object item\n\	'rname', so use e.g. '-r rh 3' for circles 3 times the half-light radius.\n\	Similarly, with -e option it will draw an ellipse with ellipticity\n\	efac times the object ellipticity and with sqrt(a b) equal\n\	to the radius as calculated above.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file makechart.c.
Function Documentation
void drawcircle (double x, double y, float r, float ** f, int N1, int N2)
Definition at line 301 of file makechart.c.
References circval, f, i, j, N1, phi, PI, r, x, and y.
Referenced by drawcollar(), and main().
void drawcollar (int io, int jo, float ** f, int N1, int N2)
Definition at line 266 of file makechart.c.
References cursval, d, drawcircle(), f, i, j, N1, N2, NE, NW, SE, and SW.
Referenced by main().
void drawcursor (double x, double y, float ** f, int N1, int N2)
Definition at line 245 of file makechart.c.
References CURS_MAX, CURS_MIN, cursval, d, f, i, j, N1, N2, x, and y.
Referenced by main().
void drawellipse (double x, double y, float r, float e, float phi0, float ** f, int N1, int N2)
Definition at line 325 of file makechart.c.
References a, b, c, circval, e, f, i, I(), j, N1, phi, PI, r, x, and y.
Referenced by main().
main (int argc, char * argv[])
Definition at line 62 of file makechart.c.
References a, add_comment(), allocobjectcontents(), b, circval, connectcatheadtoobject(), cursval, DEF_CIRCLE_VAL, DEF_CURSOR_VAL, drawcircle(), drawcollar(), drawcursor(), drawellipse(), E, e, error_exit, exit(), f, fits, getheaderitemaddress(), getobjectitemindex(), i, j, l, ll, lt(), N1, N2, newobject(), phi, r, radius, read2Dfloatimage(), readcathead(), readobject(), setaddress(), t, usage, write2Dfloatimage(), X, x, y, zapcircle(), and zapellipse().
void zapcircle (double x, double y, float r, float ** f, int N1, int N2)
Definition at line 356 of file makechart.c.
References dx, dy, f, i, j, MAGIC, N1, r, x, and y.
Referenced by main().
void zapellipse (double x, double y, float r, float e, float phi0, float ** f, int N1, int N2)
Definition at line 378 of file makechart.c.
References a, b, c, circval, dx, dy, e, f, i, I(), j, MAGIC, N1, phi, r, x, and y.
Referenced by main().
Variable Documentation
float circval [static]
Definition at line 59 of file makechart.c.
Referenced by drawcircle(), drawellipse(), main(), and zapellipse().
float cursval [static]
Definition at line 59 of file makechart.c.
Referenced by drawcollar(), drawcursor(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.