makestamps.c
NAME
makestamps.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../utils/ipbuff.h'
Defines
#define usage '\n\n\n\NAME\n\	makestamps --- extract 'postage stamp images'\n\SYNOPSIS\n\	makestamps [option...]\n\		-b b		# box side (32)\n\		-n 		# normalise images\n\		-M mag0		# normalisation magnitude\n\		-f fitsfile	# specify source fits\n\		-x xname	# name for position 2-vector (x)\n\		-m magname	# name for magnitude (mag)\n\		-N normvalname	# normalise to unit 'normvalname'\n\		-c		# generate catalog with x0[2], x[2], f, i values\n\\n\DESCRIPTION\n\	\'makestamps\' creates a set of tiny images of\n\	patches of sky around objects in the catalogue.\n\	It reads a catalogue containing positions and optionally\n\	magnitudes of nobj objects from stdin and writes to\n\	stdout a 3-D fits image of dimensions b x b x nobj.\n\\n\	It uses the images named in the catalogue header\n\	by default. Use -f option to override this.\n\\n\	With -n option the surface brightness will be\n\	scaled by a factor 10^(0.4 * (mag - mag0))\n\	where mag0 is the magnitude of the first object\n\	unless you supply a value by hand with -M option.\n\\n\	Use -N option to normalise by dividing by 'normval':\n\	e.g. do\n\		makestamps -N flux ....\n\	to normalise to unit flux.\n\\n\	Use -c option to generate lc-catalog format output with\n\	pixel values f, object number i, object coords x0[], and pixel center coords x[]\n\	with respect to the object coords.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
Functions
void getstamp (float **f, int N1, int N2, float **fstamp, int box, int ix, int iy, double ffactor)
main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 54 of file makestamps.c.
#define usage '\n\n\n\NAME\n\	makestamps --- extract 'postage stamp images'\n\SYNOPSIS\n\	makestamps [option...]\n\		-b b		# box side (32)\n\		-n 		# normalise images\n\		-M mag0		# normalisation magnitude\n\		-f fitsfile	# specify source fits\n\		-x xname	# name for position 2-vector (x)\n\		-m magname	# name for magnitude (mag)\n\		-N normvalname	# normalise to unit 'normvalname'\n\		-c		# generate catalog with x0[2], x[2], f, i values\n\\n\DESCRIPTION\n\	\'makestamps\' creates a set of tiny images of\n\	patches of sky around objects in the catalogue.\n\	It reads a catalogue containing positions and optionally\n\	magnitudes of nobj objects from stdin and writes to\n\	stdout a 3-D fits image of dimensions b x b x nobj.\n\\n\	It uses the images named in the catalogue header\n\	by default. Use -f option to override this.\n\\n\	With -n option the surface brightness will be\n\	scaled by a factor 10^(0.4 * (mag - mag0))\n\	where mag0 is the magnitude of the first object\n\	unless you supply a value by hand with -M option.\n\\n\	Use -N option to normalise by dividing by 'normval':\n\	e.g. do\n\		makestamps -N flux ....\n\	to normalise to unit flux.\n\\n\	Use -c option to generate lc-catalog format output with\n\	pixel values f, object number i, object coords x0[], and pixel center coords x[]\n\	with respect to the object coords.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file makestamps.c.
Function Documentation
void getstamp (float ** f, int N1, int N2, float ** fstamp, int box, int ix, int iy, double ffactor)
Definition at line 219 of file makestamps.c.
References dx, dy, f, MAGIC, N1, N2, x, and y.
Referenced by main().
main (int argc, char * argv[])
Definition at line 58 of file makestamps.c.
References add_comment(), allocFloatArray(), argsToString(), copyfitsheader(), error_exit, exit(), fitsheader::extpixtype, f, FLOAT_PIXTYPE, getstamp(), ix, lcpipe, line, mag, MAGIC, fitsheader::n, N1, N2, fitsheader::ndim, nobj, read2Dfloatimage(), readdoublebuff(), usage, writefitsheader(), writefitsline(), writefitstail(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.