makeobs_circ.c
NAME
makeobs_circ.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
#include 'Ffunc.h'
#include 'orbitutils/gaussdev.h'
Defines
#define usage '\nNAME\n\	makeobs_circ - make observations for a circular orbit\n\\n\SYNOPSIS\n\	makeobs_circ parfile\n\\n\DESCRIPTION\n\	makeobs_circ generates a catalog containing triplets of observations\n\	consisting of:\n\		t the time t\n\		re[] the position of the earth\n\		ve[] velocity of the earth\n\		ra[] position of the asteroid\n\		va[] velocity of the asteroid va\n\		rho[] the position of the observor relative to re[]\n\		n[] the direction vector\n\\n\	It generates these according to parameters in 'parfile', another lc cat.\n\	These are:\n\		pe the phase of the earths orbit (degrees, winter = 0.0)\n\		t0 the local time of the central observation (hours, midnight = 0.0)\n\		dt the interval between the observations (hours)\n\		ra the radius of the asteroid's orbit (AU)\n\		ia the inclination (deg)\n\		la the longitude of the ascending node (deg)\n\		pa the phase of the asteroid in its orbit (deg)\n\		sigma the uncertainty astrometry (arcsec)\n\		nreal the number of realizations\n\\n\	Both the earth and asteroid are in circular orbits.\n\\n\	Both observatory latitude and tilt of earth's axis are\n\	hard-wired to 20 deg.\n\\n\	We use an idealised model where the year has precisely 360 days\n\\n\	Output times are given in units of earths dynamical time (approx 58 days).\n\\n\	Distances are in AU.\n\\n\SEE ALSO\n\	makeobs_inertial laplace3\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	makeobs_circ - make observations for a circular orbit\n\\n\SYNOPSIS\n\	makeobs_circ parfile\n\\n\DESCRIPTION\n\	makeobs_circ generates a catalog containing triplets of observations\n\	consisting of:\n\		t the time t\n\		re[] the position of the earth\n\		ve[] velocity of the earth\n\		ra[] position of the asteroid\n\		va[] velocity of the asteroid va\n\		rho[] the position of the observor relative to re[]\n\		n[] the direction vector\n\\n\	It generates these according to parameters in 'parfile', another lc cat.\n\	These are:\n\		pe the phase of the earths orbit (degrees, winter = 0.0)\n\		t0 the local time of the central observation (hours, midnight = 0.0)\n\		dt the interval between the observations (hours)\n\		ra the radius of the asteroid's orbit (AU)\n\		ia the inclination (deg)\n\		la the longitude of the ascending node (deg)\n\		pa the phase of the asteroid in its orbit (deg)\n\		sigma the uncertainty astrometry (arcsec)\n\		nreal the number of realizations\n\\n\	Both the earth and asteroid are in circular orbits.\n\\n\	Both observatory latitude and tilt of earth's axis are\n\	hard-wired to 20 deg.\n\\n\	We use an idealised model where the year has precisely 360 days\n\\n\	Output times are given in units of earths dynamical time (approx 58 days).\n\\n\	Distances are in AU.\n\\n\SEE ALSO\n\	makeobs_inertial laplace3\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 8 of file makeobs_circ.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 55 of file makeobs_circ.c.
References assign(), exit(), fprintvec(), gaussdev(), i, ipf, length(), n, nt, ra, re, rho, rotx(), roty(), rotz(), scale(), sigma, t, t0, usage, and va.
Author
Generated automatically by Doxygen for imcat from the source code.