makegridcat.c
NAME
makegridcat.c -
SYNOPSIS
#include <stdio.h>
#include '../../imlib/fits.h'
#include '../../utils/args.h'
#include '../../catlib/cat.h'
Defines
#define usage '\n\n\NAME\n\ makegridcat - generate catalogue containing a grid of points\n\\n\SYNOPSIS\n\ makegridcat [ -u | -b ] nx [ny [nz ....]]\n\\n\DESCRIPTION\n\	Makegridcat generates a lc-format catalogue containing a unit spaced\n\	grid of points for testing purposes.\n\\n\	If invoked with a single argument nx, makegridcat generates a catalogue\n\	containing nx objects consisting of a numerical scalar x with values\n\	0,1...(nx-1).\n\	If invoked with two arguments nx, ny, it generates a catalogue\n\	containing nx * ny objects consisting of a 2-vector x[]\n\	where x[0] runs from 0 through nx-1 and x[1] runs from 0 through ny-1.\n\	If invoked with three arguments nx, ny, nz, it generates a catalogue\n\	containing nx * ny * nz objects consisting of a 3-vector x[]\n\	where x[0] runs from 0 through nx-1 and x[1] runs from 0 through ny-1\n\	and x[2] runs from 0 through nz-1, and so on.\n\\n\	Default is text format output. Use -b option to generate a binary\n\	format catalogue.\n\\n\AUTHOR\n\ Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n'
Functions
void writegridcat (int level)
main (int argc, char *argv[])
Variables
int ndim
int * dim
int binarycat
double * x
Define Documentation
#define usage '\n\n\NAME\n\ makegridcat - generate catalogue containing a grid of points\n\\n\SYNOPSIS\n\ makegridcat [ -u | -b ] nx [ny [nz ....]]\n\\n\DESCRIPTION\n\	Makegridcat generates a lc-format catalogue containing a unit spaced\n\	grid of points for testing purposes.\n\\n\	If invoked with a single argument nx, makegridcat generates a catalogue\n\	containing nx objects consisting of a numerical scalar x with values\n\	0,1...(nx-1).\n\	If invoked with two arguments nx, ny, it generates a catalogue\n\	containing nx * ny objects consisting of a 2-vector x[]\n\	where x[0] runs from 0 through nx-1 and x[1] runs from 0 through ny-1.\n\	If invoked with three arguments nx, ny, nz, it generates a catalogue\n\	containing nx * ny * nz objects consisting of a 3-vector x[]\n\	where x[0] runs from 0 through nx-1 and x[1] runs from 0 through ny-1\n\	and x[2] runs from 0 through nz-1, and so on.\n\\n\	Default is text format output. Use -b option to generate a binary\n\	format catalogue.\n\\n\AUTHOR\n\ Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n\n'
Definition at line 11 of file makegridcat.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 45 of file makegridcat.c.
References argsinit(), argsToString(), binarycat, dim, error_exit, exit(), flag, FLAG_ARG, getargi(), getflag(), i, ndim, nextargtype(), NO_ARG, usage, writegridcat(), and x.
void writegridcat (int level)
Definition at line 92 of file makegridcat.c.
References binarycat, dim, i, LC_NUM_FMT, ndim, and x.
Referenced by main().
Variable Documentation
int binarycat [static]
Definition at line 40 of file makegridcat.c.
Referenced by main(), and writegridcat().
int * dim [static]
Definition at line 40 of file makegridcat.c.
Referenced by main(), and writegridcat().
int ndim [static]
Definition at line 40 of file makegridcat.c.
Referenced by main(), and writegridcat().
double* x [static]
Definition at line 41 of file makegridcat.c.
Referenced by main(), and writegridcat().
Author
Generated automatically by Doxygen for imcat from the source code.