map.h
NAME
map.h -
SYNOPSIS
Defines
#define ULTRAFAST_MAP_MODE 0
#define FAST_MAP_MODE 1
#define TRIANGLE_MAP_MODE 2
#define FORWARDMAPMODE 1
#define INVERSEMAPMODE 0
Functions
void map (float **ftarget, int N1, int N2, float **fsource, int M1, int M2, int(*deflection)(float ri, float rj, float *di, float *dj))
long trianglecount (void)
void fastmap (float **ftarget, int N1, int N2, float **fsource, int M1, int M2, int(*deflection)(float ri, float rj, float *di, float *dj))
void ultrafastmap (float **ftarget, int N1, int N2, float **fsource, int M1, int M2, int(*deflection)(float ri, float rj, float *di, float *dj))
void set_triangle_map_mode (int mapmode)
Define Documentation
#define FAST_MAP_MODE 1
Definition at line 6 of file map.h.
Referenced by main().
#define FORWARDMAPMODE 1
Definition at line 50 of file map.h.
Referenced by addarea(), main(), and map().
#define INVERSEMAPMODE 0
Definition at line 51 of file map.h.
Referenced by main(), and map().
#define TRIANGLE_MAP_MODE 2
Definition at line 7 of file map.h.
Referenced by main().
#define ULTRAFAST_MAP_MODE 0
Definition at line 5 of file map.h.
Referenced by main().
Function Documentation
void fastmap (float ** ftarget, int N1, int N2, float ** fsource, int M1, int M2, int(* deflection)(float ri, float rj, float *di, float *dj))
Definition at line 58 of file fastmap.c.
References deflection(), dx, dy, E, exit(), f, i, ix, iy, j, M1, M2, MAGIC, N, N1, N2, S, W, x, y, and ys.
Referenced by main().
void map (float ** ftarget, int N1, int N2, float ** fsource, int M1, int M2, int(* deflection)(float ri, float rj, float *di, float *dj))
Definition at line 405 of file map.c.
References decompose(), deflection(), di, dj, FORWARDMAPMODE, freeverts(), garea, gareasum, gfsource, gfsum, gftarget, globalmapmode, gM1, gM2, gtargeti, gtargetj, i, INVERSEMAPMODE, j, M1, M2, makering(), makevertex(), N1, N2, point, trianglearea(), x, and y.
Referenced by main().
void set_triangle_map_mode (int mapmode)
Definition at line 514 of file map.c.
References globalmapmode.
Referenced by main().
long trianglecount (void)
Definition at line 485 of file map.c.
References gntriangles.
Referenced by main().
void ultrafastmap (float ** ftarget, int N1, int N2, float ** fsource, int M1, int M2, int(* deflection)(float ri, float rj, float *di, float *dj))
Definition at line 28 of file fastmap.c.
References deflection(), i, j, M1, M2, N1, N2, x, y, and ys.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.