map.c
NAME
map.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include '../utils/error.h'
#include 'fits.h'
#include 'map_private.h'
#include 'map.h'
Defines
#define TINY 1.e-8
#define NOCUT 0
#define XCUT 1
#define YCUT 2
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
#define MAX_VERTS 100000
Functions
vert * makevertex (float x, float y)
void makering (vert **basevertex, vert **point, int npoints)
void decompose (vert *basevert)
void dopolygon (vert *basevert)
void dotriangle (vert *basevert)
void printpolygon (vert *basevert)
void printvertex (vert *thevert)
void smprintpolygon (vert *basevert)
void freepolygon (vert *basevert)
void switchxy (vert *v)
void makebreakpoints (vert *v1, vert *v2, vert **V1, vert **V2, int dir, float cut)
void link (vert *r1, vert *r2, vert *l1, vert *l2, vert *R1, vert *R2, vert *L1, vert *L2)
float trianglearea (vert *basevert)
void getsourceij (vert *basevert, int *ix, int *iy)
void map (float **ftarget, int N1, int N2, float **fsource, int M1, int M2, int(*deflection)(float ri, float rj, float *di, float *dj))
void addarea (int ix, int iy, float area)
long trianglecount (void)
vert * allocvert (void)
void freeverts (void)
void set_triangle_map_mode (int mapmode)
Variables
int globalmapmode = FORWARDMAPMODE
int gM1
int gM2
int gtargeti
int gtargetj
float gareasum
float gfsum
float ** gfsource
float ** gftarget
long gntriangles = 0
float garea
int counter = 0
vert vstore [MAX_VERTS]
Define Documentation
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
Definition at line 27 of file map.c.
#define MAX_VERTS 100000
Definition at line 495 of file map.c.
Referenced by allocvert().
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
Definition at line 28 of file map.c.
#define NOCUT 0
Definition at line 23 of file map.c.
Referenced by decompose().
#define TINY 1.e-8
Definition at line 22 of file map.c.
#define XCUT 1
Definition at line 24 of file map.c.
Referenced by decompose().
#define YCUT 2
Definition at line 25 of file map.c.
Referenced by decompose(), and makebreakpoints().
Function Documentation
void addarea (int ix, int iy, float area)
Definition at line 467 of file map.c.
References FLOAT_MAGIC, FORWARDMAPMODE, garea, gareasum, gfsource, gfsum, gftarget, globalmapmode, gM2, gntriangles, gtargeti, gtargetj, and ix.
Referenced by dotriangle().
vert* allocvert (void)
Definition at line 498 of file map.c.
References counter, error_exit, MAX_VERTS, and vstore.
Referenced by dopolygon(), makebreakpoints(), and makevertex().
void decompose (vert * basevert)
Definition at line 62 of file map.c.
References dopolygon(), error_exit, link(), makebreakpoints(), vert::next, NOCUT, vert::prev, vert::x, XCUT, xmax, xmin, vert::y, YCUT, ymax, and ymin.
Referenced by map().
void dopolygon (vert * basevert)
Definition at line 186 of file map.c.
References allocvert(), dotriangle(), error_exit, vert::next, and vert::prev.
Referenced by decompose().
void dotriangle (vert * basevert)
Definition at line 227 of file map.c.
References addarea(), getsourceij(), i, j, and trianglearea().
Referenced by dopolygon().
void freepolygon (vert * basevert)
Definition at line 289 of file map.c.
References free(), and vert::next.
void freeverts (void)
Definition at line 507 of file map.c.
References counter.
Referenced by map().
void getsourceij (vert * basevert, int * ix, int * iy)
Definition at line 374 of file map.c.
References ix, MIN, vert::next, vert::prev, vert::x, and vert::y.
Referenced by dotriangle().
void link (vert * r1, vert * r2, vert * l1, vert * l2, vert * R1, vert * R2, vert * L1, vert * L2)
Definition at line 344 of file map.c.
References vert::next, and vert::prev.
Referenced by decompose().
void makebreakpoints (vert * v1, vert * v2, vert ** V1, vert ** V2, int dir, float cut)
Definition at line 316 of file map.c.
References allocvert(), dir, switchxy(), vert::x, vert::y, and YCUT.
Referenced by decompose().
void makering (vert ** basevertex, vert ** point, int npoints)
Definition at line 48 of file map.c.
References i, and point.
Referenced by map().
vert* makevertex (float x, float y)
Definition at line 33 of file map.c.
References allocvert(), vert::x, x, vert::y, and y.
Referenced by map().
void map (float ** ftarget, int N1, int N2, float ** fsource, int M1, int M2, int(* deflection)(float ri, float rj, float *di, float *dj))
Definition at line 405 of file map.c.
References decompose(), deflection(), di, dj, FORWARDMAPMODE, freeverts(), garea, gareasum, gfsource, gfsum, gftarget, globalmapmode, gM1, gM2, gtargeti, gtargetj, i, INVERSEMAPMODE, j, M1, M2, makering(), makevertex(), N1, N2, point, trianglearea(), x, and y.
Referenced by main().
void printpolygon (vert * basevert)
Definition at line 241 of file map.c.
References vert::next, and printvertex().
void printvertex (vert * thevert)
Definition at line 265 of file map.c.
References vert::x, and vert::y.
Referenced by printpolygon().
void set_triangle_map_mode (int mapmode)
Definition at line 514 of file map.c.
References globalmapmode.
Referenced by main().
void smprintpolygon (vert * basevert)
Definition at line 272 of file map.c.
References vert::next, vert::x, and vert::y.
void switchxy (vert * v)
Definition at line 305 of file map.c.
References v.
Referenced by makebreakpoints().
float trianglearea (vert * basevert)
Definition at line 361 of file map.c.
References vert::next, vert::prev, vert::x, and vert::y.
Referenced by dotriangle(), and map().
long trianglecount (void)
Definition at line 485 of file map.c.
References gntriangles.
Referenced by main().
Variable Documentation
int counter = 0 [static]
Definition at line 494 of file map.c.
Referenced by allocvert(), and freeverts().
float garea [static]
Definition at line 394 of file map.c.
Referenced by addarea(), and map().
float gareasum [static]
Definition at line 392 of file map.c.
Referenced by addarea(), and map().
float ** gfsource [static]
Definition at line 392 of file map.c.
Referenced by addarea(), and map().
float gfsum [static]
Definition at line 392 of file map.c.
Referenced by addarea(), and map().
float ** gftarget [static]
Definition at line 392 of file map.c.
Referenced by addarea(), and map().
int globalmapmode = FORWARDMAPMODE [static]
Definition at line 30 of file map.c.
Referenced by addarea(), map(), and set_triangle_map_mode().
int gM1 [static]
Definition at line 391 of file map.c.
Referenced by map().
int gM2 [static]
Definition at line 391 of file map.c.
Referenced by addarea(), and map().
long gntriangles = 0 [static]
Definition at line 393 of file map.c.
Referenced by addarea(), and trianglecount().
int gtargeti [static]
Definition at line 391 of file map.c.
Referenced by addarea(), and map().
int gtargetj [static]
Definition at line 391 of file map.c.
Referenced by addarea(), and map().
vert vstore[MAX_VERTS] [static]
Definition at line 496 of file map.c.
Referenced by allocvert().
Author
Generated automatically by Doxygen for imcat from the source code.