map_private.h
NAME
map_private.h -
SYNOPSIS
Data Structures
struct vert
Typedefs
typedef vert vert
Functions
vert * makevertex (float x, float y)
void makering (vert **basevertex, vert **point, int npoints)
void decompose (vert *basevertex)
void printpolygon (vert *basevertex)
void printvertex (vert *thevert)
void smprintpolygon (vert *basevertex)
void freepolygon (vert *basevert)
void dopolygon (vert *basevert)
void makebreakpoints (vert *v1, vert *v2, vert **V1, vert **V2, int dir, float cut)
void switchxy (vert *v)
void link (vert *r1, vert *r2, vert *l1, vert *l2, vert *R1, vert *R2, vert *L1, vert *L2)
void dotriangle (vert *basevert)
float trianglearea (vert *basevert)
void getsourceij (vert *basevert, int *ix, int *iy)
void addarea (int ix, int iy, float area)
vert * allocvert (void)
void freeverts (void)
Typedef Documentation
typedef struct vert vert
Function Documentation
void addarea (int ix, int iy, float area)
Definition at line 467 of file map.c.
References FLOAT_MAGIC, FORWARDMAPMODE, garea, gareasum, gfsource, gfsum, gftarget, globalmapmode, gM2, gntriangles, gtargeti, gtargetj, and ix.
Referenced by dotriangle().
vert* allocvert (void)
Definition at line 498 of file map.c.
References counter, error_exit, MAX_VERTS, and vstore.
Referenced by dopolygon(), makebreakpoints(), and makevertex().
void decompose (vert * basevertex)
Definition at line 62 of file map.c.
References dopolygon(), error_exit, link(), makebreakpoints(), vert::next, NOCUT, vert::prev, vert::x, XCUT, xmax, xmin, vert::y, YCUT, ymax, and ymin.
Referenced by map().
void dopolygon (vert * basevert)
Definition at line 186 of file map.c.
References allocvert(), dotriangle(), error_exit, vert::next, and vert::prev.
Referenced by decompose().
void dotriangle (vert * basevert)
Definition at line 227 of file map.c.
References addarea(), getsourceij(), i, j, and trianglearea().
Referenced by dopolygon().
void freepolygon (vert * basevert)
Definition at line 289 of file map.c.
References free(), and vert::next.
void freeverts (void)
Definition at line 507 of file map.c.
References counter.
Referenced by map().
void getsourceij (vert * basevert, int * ix, int * iy)
Definition at line 374 of file map.c.
References ix, MIN, vert::next, vert::prev, vert::x, and vert::y.
Referenced by dotriangle().
void link (vert * r1, vert * r2, vert * l1, vert * l2, vert * R1, vert * R2, vert * L1, vert * L2)
Definition at line 344 of file map.c.
References vert::next, and vert::prev.
Referenced by decompose().
void makebreakpoints (vert * v1, vert * v2, vert ** V1, vert ** V2, int dir, float cut)
Definition at line 316 of file map.c.
References allocvert(), dir, switchxy(), vert::x, vert::y, and YCUT.
Referenced by decompose().
void makering (vert ** basevertex, vert ** point, int npoints)
Definition at line 48 of file map.c.
References i, and point.
Referenced by map().
vert* makevertex (float x, float y)
Definition at line 33 of file map.c.
References allocvert(), x, vert::x, y, and vert::y.
Referenced by map().
void printpolygon (vert * basevertex)
Definition at line 241 of file map.c.
References vert::next, and printvertex().
void printvertex (vert * thevert)
Definition at line 265 of file map.c.
References vert::x, and vert::y.
Referenced by printpolygon().
void smprintpolygon (vert * basevertex)
Definition at line 272 of file map.c.
References vert::next, vert::x, and vert::y.
void switchxy (vert * v)
Definition at line 305 of file map.c.
References v.
Referenced by makebreakpoints().
float trianglearea (vert * basevert)
Definition at line 361 of file map.c.
References vert::next, vert::prev, vert::x, and vert::y.
Referenced by dotriangle(), and map().
Author
Generated automatically by Doxygen for imcat from the source code.