mapbynumericdef.c
NAME
mapbynumericdef.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../utils/error.h'
#include '../imlib/fits.h'
#include '../imlib/map.h'
Defines
#define usage '\n\n\n\NAME\n\	mapbynumericdef --- map image using numerical deflection func\n\\n\SYNOPSIS\n\	mapbynumericdef [options...] sourcefits deflectionfits\n\		-i L1 L2	# perform inverse mapping\n\		-u		# print this message\n\		-m mapmode	# type of mapping\n\		-M		# initialise image to magic\n\		-s sfac		# use scrunched deflection image\n\		-b bgfits	# background fits image to paint onto\n\\n\DESCRIPTION\n\	Mapbynumericdef maps a source image to a target image using a numerically\n\	defined deflection function. It reads a N1 x N2 image fs = 'sourcefits' and\n\	a M1 x M2 x 2 image d = 'deflectionfits' whose 0th ans 1st planes are\n\	x and y components of a deflection function.\n\	By default it generates a M1 * M2 image ft(r) = fs(r + d(r)), i.e.\n\	the deflection is given as a function of target image coordinates.\n\\n\	If either of the source images is given as 'stdin' then the image\n\	will be read from standard input.\n\\n\	With -i option it performs 'inverse' mapping --- i.e. deflection\n\	is given as a function of source image --- so the resulting image\n\	satisfies ft(x + d(x)) = fs(x) * M, where M is the magnification.\n\	With this option, the deflection\n\	function image size should be matched to the source image so\n\	M1 = N1 and M2 = N2, and the output image size is L1 x L2.\n\	Physically, inverse mapping projects a source image through a\n\	lens.\n\\n\	Use -m flag to specify mapping mode:\n\		mode = 0:	# nearest pixel\n\		mode = 1:	# linear interpolation\n\		mode = 2:	# sum over triangles\n\	the default being linear interpolation. With inverse mapping\n\	this flag is ignorred and triangle mapping is used (which\n\	can be very slow).\n\\n\	The -s option allows you to read a miniature deflection image\n\	which has been scrunched by a factor 2^sfac. This is currently\n\	not implemented for inverse mapping.\n\\n\	The -b option allows you to supply a background image to be\n\	painted onto. The size of this image will override either the\n\	dimensions determined from the deflection image size for\n\	forward mapping or the L1, L2 values set with '-i' option.\n\\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
Functions
int deflection (float ri, float rj, float *di, float *dj)
int invdeflection (float ri, float rj, float *di, float *dj)
void magicinit (float **f, int N1, int N2)
main (int argc, char *argv[])
Variables
int N1
int N2
int M1
int M2
int L1
int L2
int MM1
int MM2
int oflagset
float ** defx
float ** defy
float scalefac
Define Documentation
#define usage '\n\n\n\NAME\n\	mapbynumericdef --- map image using numerical deflection func\n\\n\SYNOPSIS\n\	mapbynumericdef [options...] sourcefits deflectionfits\n\		-i L1 L2	# perform inverse mapping\n\		-u		# print this message\n\		-m mapmode	# type of mapping\n\		-M		# initialise image to magic\n\		-s sfac		# use scrunched deflection image\n\		-b bgfits	# background fits image to paint onto\n\\n\DESCRIPTION\n\	Mapbynumericdef maps a source image to a target image using a numerically\n\	defined deflection function. It reads a N1 x N2 image fs = 'sourcefits' and\n\	a M1 x M2 x 2 image d = 'deflectionfits' whose 0th ans 1st planes are\n\	x and y components of a deflection function.\n\	By default it generates a M1 * M2 image ft(r) = fs(r + d(r)), i.e.\n\	the deflection is given as a function of target image coordinates.\n\\n\	If either of the source images is given as 'stdin' then the image\n\	will be read from standard input.\n\\n\	With -i option it performs 'inverse' mapping --- i.e. deflection\n\	is given as a function of source image --- so the resulting image\n\	satisfies ft(x + d(x)) = fs(x) * M, where M is the magnification.\n\	With this option, the deflection\n\	function image size should be matched to the source image so\n\	M1 = N1 and M2 = N2, and the output image size is L1 x L2.\n\	Physically, inverse mapping projects a source image through a\n\	lens.\n\\n\	Use -m flag to specify mapping mode:\n\		mode = 0:	# nearest pixel\n\		mode = 1:	# linear interpolation\n\		mode = 2:	# sum over triangles\n\	the default being linear interpolation. With inverse mapping\n\	this flag is ignorred and triangle mapping is used (which\n\	can be very slow).\n\\n\	The -s option allows you to read a miniature deflection image\n\	which has been scrunched by a factor 2^sfac. This is currently\n\	not implemented for inverse mapping.\n\\n\	The -b option allows you to supply a background image to be\n\	painted onto. The size of this image will override either the\n\	dimensions determined from the deflection image size for\n\	forward mapping or the L1, L2 values set with '-i' option.\n\\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
Definition at line 5 of file mapbynumericdef.c.
Function Documentation
int deflection (float ri, float rj, float * di, float * dj)
Definition at line 142 of file lensmap.c.
int invdeflection (float ri, float rj, float * di, float * dj)
Definition at line 272 of file mapbynumericdef.c.
References defx, defy, di, dj, FLOAT_MAGIC, i, j, N1, and N2.
Referenced by main().
void magicinit (float ** f, int N1, int N2)
Definition at line 293 of file mapbynumericdef.c.
References f, FLOAT_MAGIC, N1, N2, x, and y.
Referenced by main().
main (int argc, char * argv[])
Definition at line 79 of file mapbynumericdef.c.
References add_comment(), allocFloatArray(), copyfitsheader(), deflection(), defx, defy, error_exit, exit(), FAST_MAP_MODE, fastmap(), invdeflection(), INVERSEMAPMODE, L1, L2, M1, M2, magicinit(), map(), MM1, MM2, fitsheader::n, N1, N2, fitsheader::ndim, oflagset, read2Dfloatimage(), readfitsheader(), readfitsplane(), scalefac, set_triangle_map_mode(), TRIANGLE_MAP_MODE, ULTRAFAST_MAP_MODE, ultrafastmap(), usage, write2Dfloatimage(), x, and y.
Variable Documentation
float** defx [static]
Definition at line 72 of file mapbynumericdef.c.
Referenced by invdeflection(), and main().
float ** defy [static]
Definition at line 72 of file mapbynumericdef.c.
Referenced by invdeflection(), and main().
int L1 [static]
Definition at line 71 of file mapbynumericdef.c.
Referenced by main().
int L2 [static]
Definition at line 71 of file mapbynumericdef.c.
Referenced by main().
int M1 [static]
Definition at line 71 of file mapbynumericdef.c.
int M2 [static]
Definition at line 71 of file mapbynumericdef.c.
int MM1 [static]
Definition at line 71 of file mapbynumericdef.c.
Referenced by main().
int MM2 [static]
Definition at line 71 of file mapbynumericdef.c.
Referenced by main().
int N1 [static]
Definition at line 71 of file mapbynumericdef.c.
int N2 [static]
Definition at line 71 of file mapbynumericdef.c.
int oflagset [static]
Definition at line 71 of file mapbynumericdef.c.
Referenced by main().
float scalefac [static]
Definition at line 72 of file mapbynumericdef.c.
Author
Generated automatically by Doxygen for imcat from the source code.