maskcat.c
NAME
maskcat.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../catlib/cat.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	maskcat -- remove objects falling in a list of rectangles\n\SYNOPSIS\n\	maskcat	[options....] maskfile \n\		-x xname	# name for spatial coordinate ('x')\n\		-i		# inverse selection mode\n\\n\DESCRIPTION\n\	\'maskcat\' reads a catalogue from stdin, removes any objects\n\	which fall within any of a set of rectangles specified in the file\n\	'maskfile', and writes the result to stdout.\n\\n\	The mask file must be a lc-format catalogue containing\n\	(at least) a pair of position vectors x1[2], x2[2]\n\	which are diagonally opposite corners of the rectangle.\n\	Objects lying on the boundary will be rejected.\n\\n\	With the -i option, we output only those objects which fall\n\	within the union of the rectangles sepcified in maskfile.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAX_RECTS 10000
Functions
main (int argc, char *argv[])
Define Documentation
#define MAX_RECTS 10000
Definition at line 41 of file maskcat.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	maskcat -- remove objects falling in a list of rectangles\n\SYNOPSIS\n\	maskcat	[options....] maskfile \n\		-x xname	# name for spatial coordinate ('x')\n\		-i		# inverse selection mode\n\\n\DESCRIPTION\n\	\'maskcat\' reads a catalogue from stdin, removes any objects\n\	which fall within any of a set of rectangles specified in the file\n\	'maskfile', and writes the result to stdout.\n\\n\	The mask file must be a lc-format catalogue containing\n\	(at least) a pair of position vectors x1[2], x2[2]\n\	which are diagonally opposite corners of the rectangle.\n\	Objects lying on the boundary will be rejected.\n\\n\	With the -i option, we output only those objects which fall\n\	within the union of the rectangles sepcified in maskfile.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 5 of file maskcat.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 44 of file maskcat.c.
References addargscomment(), object::addrlist, allocobjectcontents(), BINARY_FILE_TYPE, connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), error_exit, exit(), getobjectitemindex(), line, MAX_RECTS, newobject(), readcathead(), readobject(), setcatopfiletype(), usage, writecathead(), writeobject(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.