mask.c
NAME
mask.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	mask - set abnormal pixels in sky-flat to MAGIC\n\\n\SYNOPSIS\n\	mask [options] < fits_in > fits_out \n\		-b inner outer 	# box for local median (3 5)\n\		-f dfcrit	# critical (f - fmedian) value (100)\n\\n\DESCRIPTION\n\	\'mask\' reads fits_in (typically a sky_flat) \n\	calculates a local median and sets to MAGIC\n\	any pixels with abs(f - f_local_median) > dfcrit \n\	Finally any neighbours of MAGIC pixels are also set to MAGIC.\n\	The MAGIC property will be inherited when the result is\n\	used to sky flatten an image\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
Functions
int floatcmp ()
int main (int argc, char *argv[])
int floatcmp (float *s1, float *s2)
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 34 of file mask.c.
#define usage '\n\n\n\NAME\n\	mask - set abnormal pixels in sky-flat to MAGIC\n\\n\SYNOPSIS\n\	mask [options] < fits_in > fits_out \n\		-b inner outer 	# box for local median (3 5)\n\		-f dfcrit	# critical (f - fmedian) value (100)\n\\n\DESCRIPTION\n\	\'mask\' reads fits_in (typically a sky_flat) \n\	calculates a local median and sets to MAGIC\n\	any pixels with abs(f - f_local_median) > dfcrit \n\	Finally any neighbours of MAGIC pixels are also set to MAGIC.\n\	The MAGIC property will be inherited when the result is\n\	used to sky flatten an image\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file mask.c.
Function Documentation
int floatcmp (float * s1, float * s2)
Definition at line 131 of file mask.c.
int floatcmp ()
Referenced by liststats(), and main().
int main (int argc, char * argv[])
Definition at line 38 of file mask.c.
References add_comment(), allocFloatArray(), di, dj, error_exit, exit(), f, fits, floatcmp(), fmedian(), i, j, MAGIC, N1, N2, read2Dfloatimage(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.