maskfits.c
NAME
maskfits.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../utils/error.h'
#include '../imlib/fits.h'
Defines
#define usage '\n\n\n\NAME\n\	maskfits - set pixels in rectangles to MAGIC\n\\n\SYNOPSIS\n\	maskfits yyy.msk\n\n\DESCRIPTION\n\	Filter which sets to magic any pixels falling\n\	within rectangles defined in yyy.msk.\n\	The latter must be an lc-format catalogue containing\n\	at least a pair of position vectors x1, x2 for\n\	diagonally opposite corners of the rectangle.\n\	Mask files may be generated by 'plotcat'.\n\	In general, these coords are floating point numbers,\n\	but get integerised on input using 'floor'.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAX_RECTS 1000
#define MAGIC FLOAT_MAGIC
Functions
main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 32 of file maskfits.c.
#define MAX_RECTS 1000
Definition at line 30 of file maskfits.c.
#define usage '\n\n\n\NAME\n\	maskfits - set pixels in rectangles to MAGIC\n\\n\SYNOPSIS\n\	maskfits yyy.msk\n\n\DESCRIPTION\n\	Filter which sets to magic any pixels falling\n\	within rectangles defined in yyy.msk.\n\	The latter must be an lc-format catalogue containing\n\	at least a pair of position vectors x1, x2 for\n\	diagonally opposite corners of the rectangle.\n\	Mask files may be generated by 'plotcat'.\n\	In general, these coords are floating point numbers,\n\	but get integerised on input using 'floor'.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file maskfits.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 34 of file maskfits.c.
References add_comment(), b, error_exit, exit(), f, fits, i, j, l, line, MAGIC, MAX_RECTS, N1, N2, r, read2Dfloatimage(), t, usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.