massmap_ft.c
NAME
massmap_ft.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../imlib/fits.h'
#include '../../utils/arrays.h'
#include '../../fftlib/myfft.h'
Defines
#define usage '\n\NAME\n\	massmap_ft --- ks93 reconstruction using FFT\n\\n\SYNOPSIS\n\	massmap_ft [options...]\n\		-m mode	 	# mode (0)\n\		-r R	 	# pad by factor R (2)\n\\n\DESCRIPTION\n\	'massmap_ft' reads a shear image in the format produced by 'makeshearimage'\n\	from stdin and reconstructs density field by fourier-space\n\	version of KS93.\n\	The input data are zero-padded onto an internal image which is\n\	by default twice the size of the original.\n\	You can use a slightly different estimator with -m option:\n\		mode = 0 for KS93 chi estimator\n\		mode = 1 for zeta estimator.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
#define EPS 1.e-10
#define CHI_MODE 0
#define ZETA_MODE 1
Functions
float chi1 (float ki, float kj)
float chi2 (float ki, float kj)
float zeta1 (float ki, float kj)
float zeta2 (float ki, float kj)
main (int argc, char *argv[])
Define Documentation
#define CHI_MODE 0
Definition at line 42 of file massmap_ft.c.
Referenced by main().
#define EPS 1.e-10
Definition at line 35 of file massmap_ft.c.
#define usage '\n\NAME\n\	massmap_ft --- ks93 reconstruction using FFT\n\\n\SYNOPSIS\n\	massmap_ft [options...]\n\		-m mode	 	# mode (0)\n\		-r R	 	# pad by factor R (2)\n\\n\DESCRIPTION\n\	'massmap_ft' reads a shear image in the format produced by 'makeshearimage'\n\	from stdin and reconstructs density field by fourier-space\n\	version of KS93.\n\	The input data are zero-padded onto an internal image which is\n\	by default twice the size of the original.\n\	You can use a slightly different estimator with -m option:\n\		mode = 0 for KS93 chi estimator\n\		mode = 1 for zeta estimator.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file massmap_ft.c.
#define ZETA_MODE 1
Definition at line 43 of file massmap_ft.c.
Referenced by main().
Function Documentation
float chi1 (float ki, float kj)
Definition at line 145 of file massmap_ft.c.
References EPS, and kk.
Referenced by main().
float chi2 (float ki, float kj)
Definition at line 154 of file massmap_ft.c.
References EPS, and kk.
Referenced by chisquared(), func(), and main().
main (int argc, char * argv[])
Definition at line 46 of file massmap_ft.c.
References add_comment(), alloc_fft(), allocFloatArray(), chi1(), chi2(), CHI_MODE, exit(), fft_type, filter(), fits, forward_fft(), gamma1(), gamma2(), i, inverse_fft(), j, M, fitsheader::n, N, fitsheader::ndim, readfitsheader(), readfitsline(), usage, write2Dfloatimage(), zeta1(), zeta2(), and ZETA_MODE.
float zeta1 (float ki, float kj)
Definition at line 163 of file massmap_ft.c.
Referenced by main().
float zeta2 (float ki, float kj)
Definition at line 177 of file massmap_ft.c.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.