massmap.c
NAME
massmap.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../utils/error.h'
#include '../../imlib/fits.h'
Defines
#define usage '\n\n\n\NAME\n\	massmap --- direct summation massmap\n\SYNOPSIS\n\	massmap [option...] \n\		-g ng			# output grid size (64)\n\		-s rs			# gaussian smoothing radius in output grid size units (2.0)\n\		-n N			# input image size	(2048)\n\		-o xo yo		# origin of cat in pixels (0,0)\n\		-R R			# radius for determining n_bar (N/4)\n\		-e pol			# output smoothed (n * e[pol] / nbar) map\n\		-d 			# output D.s\n\		-c 			# output D x s\n\		-l lossfactor		# divide final mass-map by lossfactor (1.0)\n\		-E ename		# name for 2-vector ellipticity (e)\n\		-x xname		# name for 2-vector spatial coordinate (x)\n\\n\DESCRIPTION\n\	\'massmap\' reads e[2], x[2] from a catalogue and calculates foreground\n\	surface mass density field from background galaxy ellipticities a la KS.\n\	Calculates mean galaxy number density in disk radius R around field centre\n\	Outputs Sigma / Sigma_crit unless -e option set in which case it\n\	outputs a gaussian smoothed map of (n * e[pol] / nbar) for pol = 0 or 1\n\	Use lossfactor (< 1.0) to correct for seeing\n\	Uses W(theta) = (0.1 y^4 / (1 + 0.1 y^4)) / theta^2 (where y = theta / sigma)\n\	as truly excellent approximation to bessel function window for gaussian T(k)\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define TINY 1.e-8
#define DO_MASS_MAP 0
#define DO_E_MAP 1
#define DO_DOT_MAP 2
#define DO_CROSS_MAP 3
#define PI M_PI
Functions
main (int argc, char *argv[])
Define Documentation
#define DO_CROSS_MAP 3
Definition at line 46 of file massmap.c.
Referenced by main().
#define DO_DOT_MAP 2
Definition at line 45 of file massmap.c.
Referenced by main().
#define DO_E_MAP 1
Definition at line 44 of file massmap.c.
Referenced by main().
#define DO_MASS_MAP 0
Definition at line 43 of file massmap.c.
Referenced by main().
#define PI M_PI
Definition at line 48 of file massmap.c.
#define TINY 1.e-8
Definition at line 41 of file massmap.c.
#define usage '\n\n\n\NAME\n\	massmap --- direct summation massmap\n\SYNOPSIS\n\	massmap [option...] \n\		-g ng			# output grid size (64)\n\		-s rs			# gaussian smoothing radius in output grid size units (2.0)\n\		-n N			# input image size	(2048)\n\		-o xo yo		# origin of cat in pixels (0,0)\n\		-R R			# radius for determining n_bar (N/4)\n\		-e pol			# output smoothed (n * e[pol] / nbar) map\n\		-d 			# output D.s\n\		-c 			# output D x s\n\		-l lossfactor		# divide final mass-map by lossfactor (1.0)\n\		-E ename		# name for 2-vector ellipticity (e)\n\		-x xname		# name for 2-vector spatial coordinate (x)\n\\n\DESCRIPTION\n\	\'massmap\' reads e[2], x[2] from a catalogue and calculates foreground\n\	surface mass density field from background galaxy ellipticities a la KS.\n\	Calculates mean galaxy number density in disk radius R around field centre\n\	Outputs Sigma / Sigma_crit unless -e option set in which case it\n\	outputs a gaussian smoothed map of (n * e[pol] / nbar) for pol = 0 or 1\n\	Use lossfactor (< 1.0) to correct for seeing\n\	Uses W(theta) = (0.1 y^4 / (1 + 0.1 y^4)) / theta^2 (where y = theta / sigma)\n\	as truly excellent approximation to bessel function window for gaussian T(k)\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file massmap.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 51 of file massmap.c.
References add_comment(), allocFloatArray(), DO_CROSS_MAP, DO_DOT_MAP, DO_E_MAP, DO_MASS_MAP, dx, dy, e, error_exit, fits, FLOAT_PIXTYPE, g(), lcpipe, line, N, new2Dfitsheader(), PI, scale, sigma, TINY, usage, w, write2Dfloatimage(), x, xo, y, yo, and z.
Author
Generated automatically by Doxygen for imcat from the source code.