mergecatsmain.c
NAME
mergecatsmain.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../../utils/error.h'
#include '../../catlib/cat.h'
#include 'grid.h'
Data Structures
struct ntuplet
Defines
#define usage '\n\n\NAME\n\	mergecats - merge catalogues of objects by position\n\\n\SYNOPSIS\n\	mergecats [options...] d a.cat b.cat ....\n\\n\DESCRIPTION\n\	'mergecats' reads N catalogues of objects and outputs a single\n\	merged catalogue of objects whose positions match to\n\	within tolerance d.\n\\n\	We first read all the catalogues\n\	and then for each object in turn construct an N-tuplet\n\	consisting of it and any neighbours which meet the\n\	positional tolerance criterion. We then rank the N-tuplets\n\	in order of quality of match (an N-tuplet\n\	with all slots filled ranks higher than one with one\n\	empty slot etc., otherwise rank is the sum of the\n\	N (N - 1) / 2 separations). We then output the\n\	N-tuplets (as objects with same named items as\n\	the input catalogue but where each item is a N-vector\n\	of the input values) in order of decreasing rank, but\n\	only using the objects which were not contained in a previously\n\	output N-tuplet.\n\\n\	By default, mergecats will only output complete ntuplets (i.e\n\	those with detections in all input catalogues).\n\\n\	The idea here is that if one has three input catalogues\n\	containing positionally coincidental objects B,V,I say, plus\n\	an extra nearby neighbour N detected in B only,\n\	then the algorithm will construct four triplets BVI, VIB, IBV and\n\	NVI, it will then output whichever of the first 3 triplets\n\	is tightest and then output an extra object N-- with\n\	two empty slots.\n\\n\	For efficiency we read the objects from each catalogue into\n\	a checkerboard grid of null terminated linked lists of objects.\n\	Options are:\n\\n\	-x xname	Supply name for the 2-vector spatial coord ('x')\n\\n\	-n nmin		Output only objects with >= nmin detections.\n\			With this it may be useful to use -m option:\n\\n\	-N nmax		Output only objects with <= nmax detections.\n\			With this it may be useful to use -m option:\n\\n\	-m		Prepend the output object items with a mask which\n\		 	is a binary representation of the detections. E.g\n\			mask = '10010' indicates a detection in the zeroth\n\			and third catalogues of a five catalogue merge.\n\			Leading zeros are not printed.\n\\n\	-M mask		Output only objects which match the specified mask.\n\\n\	-s		Prepend the output cat with a column containing\n\			the 'size' of the object (sum of the N (N - 1) / 2\n\			separations.\n\\n\	-d		Prepend the output cat with a column containing\n\			the number of detections.\n\\n\	-e		Exclude zero separation ntuplets\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
#define BIG_POS 1.e100
#define BIG_NEG -1.e100
#define query(a, b) ((a) > (b) ? 1 : ((a) < (b) ? -1 : 0))
Typedefs
typedef ntuplet ntuplet
Functions
int identical (cathead *cat1, cathead *cat2)
void fan (int j)
int valid (object **obj)
double sep2 (object *obj1, object *obj2)
double getsize (object **obj)
int getnobjs (object **obj)
int ntupletcmp (const void *ptr1, const void *ptr2)
void dispose (ntuplet **ntuparray, object *opobj)
main (int argc, char *argv[])
Variables
int N
int * nneighbours
int xindex
int nntuplets
int nobjsmin
int nobjsmax
int domask
int nprepends
int dosize
int dondet
int nozerosep
int themask
double d
object *** neighbourobj
object ** obj
object * nullipobj
ntuplet * ntupletbase
Define Documentation
#define BIG_NEG -1.e100
Definition at line 84 of file mergecatsmain.c.
#define BIG_POS 1.e100
Definition at line 83 of file mergecatsmain.c.
#define query(a, b) ((a) > (b) ? 1 : ((a) < (b) ? -1 : 0))
Definition at line 501 of file mergecatsmain.c.
Referenced by ntupletcmp().
#define usage '\n\n\NAME\n\	mergecats - merge catalogues of objects by position\n\\n\SYNOPSIS\n\	mergecats [options...] d a.cat b.cat ....\n\\n\DESCRIPTION\n\	'mergecats' reads N catalogues of objects and outputs a single\n\	merged catalogue of objects whose positions match to\n\	within tolerance d.\n\\n\	We first read all the catalogues\n\	and then for each object in turn construct an N-tuplet\n\	consisting of it and any neighbours which meet the\n\	positional tolerance criterion. We then rank the N-tuplets\n\	in order of quality of match (an N-tuplet\n\	with all slots filled ranks higher than one with one\n\	empty slot etc., otherwise rank is the sum of the\n\	N (N - 1) / 2 separations). We then output the\n\	N-tuplets (as objects with same named items as\n\	the input catalogue but where each item is a N-vector\n\	of the input values) in order of decreasing rank, but\n\	only using the objects which were not contained in a previously\n\	output N-tuplet.\n\\n\	By default, mergecats will only output complete ntuplets (i.e\n\	those with detections in all input catalogues).\n\\n\	The idea here is that if one has three input catalogues\n\	containing positionally coincidental objects B,V,I say, plus\n\	an extra nearby neighbour N detected in B only,\n\	then the algorithm will construct four triplets BVI, VIB, IBV and\n\	NVI, it will then output whichever of the first 3 triplets\n\	is tightest and then output an extra object N-- with\n\	two empty slots.\n\\n\	For efficiency we read the objects from each catalogue into\n\	a checkerboard grid of null terminated linked lists of objects.\n\	Options are:\n\\n\	-x xname	Supply name for the 2-vector spatial coord ('x')\n\\n\	-n nmin		Output only objects with >= nmin detections.\n\			With this it may be useful to use -m option:\n\\n\	-N nmax		Output only objects with <= nmax detections.\n\			With this it may be useful to use -m option:\n\\n\	-m		Prepend the output object items with a mask which\n\		 	is a binary representation of the detections. E.g\n\			mask = '10010' indicates a detection in the zeroth\n\			and third catalogues of a five catalogue merge.\n\			Leading zeros are not printed.\n\\n\	-M mask		Output only objects which match the specified mask.\n\\n\	-s		Prepend the output cat with a column containing\n\			the 'size' of the object (sum of the N (N - 1) / 2\n\			separations.\n\\n\	-d		Prepend the output cat with a column containing\n\			the number of detections.\n\\n\	-e		Exclude zero separation ntuplets\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file mergecatsmain.c.
Typedef Documentation
typedef struct ntuplet ntuplet
Function Documentation
void dispose (ntuplet ** ntuparray, object * opobj)
Definition at line 515 of file mergecatsmain.c.
References object::addrlist, object::cathead, domask, dondet, dosize, exit(), i, j, N, object::nitems, nntuplets, nobjsmax, nobjsmin, nprepends, nullipobj, themask, and writeobject().
Referenced by main().
void fan (int j)
Definition at line 391 of file mergecatsmain.c.
References getnobjs(), getsize(), i, j, ntuplet::mask, mult(), N, neighbourobj, ntuplet::next, nneighbours, nntuplets, ntuplet::nobjs, ntupletbase, ntuplet::obj, obj, ntuplet::size, and valid().
Referenced by main().
int getnobjs (object ** obj)
Definition at line 488 of file mergecatsmain.c.
References i, N, and obj.
Referenced by fan().
double getsize (object ** obj)
Definition at line 470 of file mergecatsmain.c.
References i, j, N, obj, sep2(), and size.
Referenced by fan().
int identical (cathead * cat1, cathead * cat2)
Referenced by main().
main (int argc, char * argv[])
Definition at line 110 of file mergecatsmain.c.
References addargscomment(), addobjectitem(), item::addr, object::addrlist, allocgrid(), allocitemcontents(), allocobjectcontents(), BIG_NEG, BIG_POS, BINARY_FILE_TYPE, copyheaderinfo(), d, item::dim, dispose(), domask, dondet, dosize, error_exit, exit(), fan(), getcatipfiletype(), getgridcoords(), getneighbours(), getobjectitem(), getobjectitemindex(), getobjects(), cathead::headeritembase, i, identical(), installitem(), item::itype, ix, j, MAX_NEIGHBOURS, N, item::name, item::ndim, neighbourobj, newitem(), newobject(), ntuplet::next, object::next, item::next, nneighbours, nntuplets, nobj, nobjsmax, nobjsmin, nozerosep, nprepends, ntupletbase, ntupletcmp(), nullipobj, NUM_TYPE, obj, cathead::objectitembase, readcathead(), readobject(), setcatipf(), setcatipfiletype(), setcatopfiletype(), setgridsize(), TEXT_TYPE, themask, usage, writecathead(), x, xindex, xmax, and xmin.
int ntupletcmp (const void * ptr1, const void * ptr2)
Definition at line 502 of file mergecatsmain.c.
References query.
Referenced by main().
double sep2 (object * obj1, object * obj2)
Definition at line 457 of file mergecatsmain.c.
References object::addrlist, dx, dy, and xindex.
Referenced by getsize(), main(), and valid().
int valid (object ** obj)
Definition at line 433 of file mergecatsmain.c.
References d, i, j, N, nozerosep, obj, and sep2().
Referenced by fan().
Variable Documentation
double d [static]
Definition at line 105 of file mergecatsmain.c.
Referenced by main(), and valid().
int domask [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by dispose(), and main().
int dondet [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by dispose(), and main().
int dosize [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by dispose(), and main().
int N [static]
Definition at line 103 of file mergecatsmain.c.
object*** neighbourobj [static]
Definition at line 106 of file mergecatsmain.c.
Referenced by fan(), and main().
int * nneighbours [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by fan(), and main().
int nntuplets [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by dispose(), fan(), and main().
int nobjsmax [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by dispose(), and main().
int nobjsmin [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by dispose(), and main().
int nozerosep [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by main(), and valid().
int nprepends [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by dispose(), and main().
ntuplet* ntupletbase [static]
Definition at line 107 of file mergecatsmain.c.
Referenced by fan(), and main().
object * nullipobj [static]
Definition at line 106 of file mergecatsmain.c.
Referenced by dispose(), and main().
object ** obj [static]
Definition at line 106 of file mergecatsmain.c.
Referenced by fan(), getnobjs(), getsize(), main(), and valid().
int themask [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by dispose(), and main().
int xindex [static]
Definition at line 103 of file mergecatsmain.c.
Referenced by main(), and sep2().
Author
Generated automatically by Doxygen for imcat from the source code.