mesh.h
NAME
mesh.h -
SYNOPSIS
Functions
void ReadNewFrame (void)
void DrawMesh (void)
void swapbytes (void *addr, int nint)
Function Documentation
void DrawMesh (void)
Definition at line 31 of file mesh.c.
References f, framenumber, i, j, Nx, Ny, recording, swapbytes(), and zscale.
Referenced by command_input_callback(), forwardstep_button_callback(), main(), rewind_button_callback(), and zscale_counter_callback().
void ReadNewFrame (void)
Definition at line 19 of file mesh.c.
References f, fits, FD_control_panel::frame_number_text, framenumber, framestring, nframes, readfitsplane(), and thecontrolpanel.
Referenced by command_input_callback(), forwardstep_button_callback(), main(), and rewind_button_callback().
void swapbytes (void * addr, int nint)
Definition at line 1212 of file cat.c.
References b, i, and nint.
Referenced by DrawMesh(), readitem(), and writeitem().
Author
Generated automatically by Doxygen for imcat from the source code.