minisky.c
NAME
minisky.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/arrays.h'
#include '../../imlib/filters.h'
Defines
#define usage '\n\n\n\NAME\n\	minisky --- make a smooth local sky flat from cat of minima\n\\n\SYNOPSIS\n\	minisky [option...] <catalogue >fits \n\		-s n		# work with scrunch^n-ed image (2)\n\		-r rf		# gaussian filter radius in real pixels (64)\n\\n\DESCRIPTION\n\	\'minisky\' reads minima from a catalogue on stdin\n\	It then creates two coarsely sampled images (chunky pixel side\n\	= 2^n real pixels); f1 is number of minima falling in pixel\n\	and f2 is sum of their fs values. These are smoothed with\n\	gaussian radius rf and then fsky = f2 / f1.\n\	This will find low-frequency sky variations (as well as any\n\	v low frequency and low surface brightness real objects.\n\	Output image needs unscrunching to full resolution\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
#define SIGMA1 0.0
#define ALPHA 1.0
#define MAGICSUBSTITUTE 0.0
#define TINYVALUE 1.0e-6
Functions
main (int argc, char *argv[])
Define Documentation
#define ALPHA 1.0
Definition at line 38 of file minisky.c.
Referenced by main().
#define MAGIC FLOAT_MAGIC
Definition at line 35 of file minisky.c.
#define MAGICSUBSTITUTE 0.0
Definition at line 39 of file minisky.c.
Referenced by main().
#define SIGMA1 0.0
Definition at line 37 of file minisky.c.
Referenced by main().
#define TINYVALUE 1.0e-6
Definition at line 40 of file minisky.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	minisky --- make a smooth local sky flat from cat of minima\n\\n\SYNOPSIS\n\	minisky [option...] <catalogue >fits \n\		-s n		# work with scrunch^n-ed image (2)\n\		-r rf		# gaussian filter radius in real pixels (64)\n\\n\DESCRIPTION\n\	\'minisky\' reads minima from a catalogue on stdin\n\	It then creates two coarsely sampled images (chunky pixel side\n\	= 2^n real pixels); f1 is number of minima falling in pixel\n\	and f2 is sum of their fs values. These are smoothed with\n\	gaussian radius rf and then fsky = f2 / f1.\n\	This will find low-frequency sky variations (as well as any\n\	v low frequency and low surface brightness real objects.\n\	Output image needs unscrunching to full resolution\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file minisky.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 43 of file minisky.c.
References add_comment(), allocFloatArray(), ALPHA, error_exit, exit(), fits, FLOAT_PIXTYPE, ix, lcpipe, line, MAGIC, MAGICSUBSTITUTE, new2Dfitsheader(), scale, schecterfilter(), SIGMA1, TINYVALUE, usage, write2Dfloatimage(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.