.TH "mnbrak.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mnbrak.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmnbrak\fP (float *ax, float *bx, float *cx, float *fa, float *\fBfb\fP, float *fc, float(*func)(float))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mnbrak (float * ax, float * bx, float * cx, float * fa, float * fb, float * fc, float(* func)(float))"
.PP
Definition at line 19 of file mnbrak.c.
.PP
References fb, func(), GLIMIT, GOLD, MAX, r, SHFT, SIGN, and TINY.
.PP
Referenced by linmin(), and main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
