mnbrak.h
NAME
mnbrak.h -
SYNOPSIS
Functions
void mnbrak (float *ax, float *bx, float *cx, float *fa, float *fb, float *fc, float(*func)(float))
Function Documentation
void mnbrak (float * ax, float * bx, float * cx, float * fa, float * fb, float * fc, float(* func)(float))
Definition at line 19 of file mnbrak.c.
References fb, func(), GLIMIT, GOLD, MAX, r, SHFT, SIGN, and TINY.
Referenced by linmin(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.