modelpsf.c
NAME
modelpsf.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/args.h'
#include '../../utils/ipbuff.h'
#include '../../utils/modefunc.h'
#include '../../utils/lu.h'
Defines
#define usage '\n\n\n\NAME\n\	modelpsf --- generate a 2D polynomial model for psf\n\\n\SYNOPSIS\n\	modelpsf starcat fitsimage [options...]\n\		-n N		# postage stamp image size (32)\n\		-l lmax		# max order for fit (1)\n\		-g		# generate psf model\n\		-s		# read stamps image\n\		-w f_bg		# use background in weighting\n\\n\DESCRIPTION\n\	'modelpsf' first reads a catalogue of stars from 'starcat'\n\	and fits for the following model for the psf:\n\\n\		fpsf(x; xobj) = sum_l fpsf_l(x) f_l(xobj)\n\\n\	where f_l(xobj) are polynomial mode functions and the fpsf_l(x)\n\	are the image valued 'mode amplitudes'.\n\\n\	The stars need to be normalised in flux, so it is necessary\n\	that the input catalogues contain an entry\n\	'flux' in addition to the position vector 'x[2]'.\n\\n\	By default it generates and reads a postage stamp album image\n\	of these stars from 'fitsimage'. We then\n\	do a least squares fit to obtain a final image model psf\n\	amplitudes fpsf_l(x).\n\\n\	With -s option 'fitsimage' is supplied as a ready made stamp\n\	album.\n\\n\	By default, objects recieve weight proportional to their\n\	flux, which is optimum in the limit of negligible sky background.\n\	Use -w option to supply a background value (input image is assumed to\n\	have had background subtracted however), and then weight\n\	objects in proportion to flux^2 / (f + f_bg).\n\\n\	With the -g option, the fits image is instead interpreted\n\	as the nmodes x N x N model psf image and we generate\n\	an nstars x N x N image containing the synthesised\n\	models. In this mode the -n flag is ignored and\n\	the input catalogue need contain only a position vector\n\	x[2].\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
#define HEADER_SIZE 1024
Functions
main (int argc, char *argv[])
Define Documentation
#define HEADER_SIZE 1024
Definition at line 65 of file modelpsf.c.
Referenced by main().
#define usage '\n\n\n\NAME\n\	modelpsf --- generate a 2D polynomial model for psf\n\\n\SYNOPSIS\n\	modelpsf starcat fitsimage [options...]\n\		-n N		# postage stamp image size (32)\n\		-l lmax		# max order for fit (1)\n\		-g		# generate psf model\n\		-s		# read stamps image\n\		-w f_bg		# use background in weighting\n\\n\DESCRIPTION\n\	'modelpsf' first reads a catalogue of stars from 'starcat'\n\	and fits for the following model for the psf:\n\\n\		fpsf(x; xobj) = sum_l fpsf_l(x) f_l(xobj)\n\\n\	where f_l(xobj) are polynomial mode functions and the fpsf_l(x)\n\	are the image valued 'mode amplitudes'.\n\\n\	The stars need to be normalised in flux, so it is necessary\n\	that the input catalogues contain an entry\n\	'flux' in addition to the position vector 'x[2]'.\n\\n\	By default it generates and reads a postage stamp album image\n\	of these stars from 'fitsimage'. We then\n\	do a least squares fit to obtain a final image model psf\n\	amplitudes fpsf_l(x).\n\\n\	With -s option 'fitsimage' is supplied as a ready made stamp\n\	album.\n\\n\	By default, objects recieve weight proportional to their\n\	flux, which is optimum in the limit of negligible sky background.\n\	Use -w option to supply a background value (input image is assumed to\n\	have had background subtracted however), and then weight\n\	objects in proportion to flux^2 / (f + f_bg).\n\\n\	With the -g option, the fits image is instead interpreted\n\	as the nmodes x N x N model psf image and we generate\n\	an nstars x N x N image containing the synthesised\n\	models. In this mode the -n flag is ignored and\n\	the input catalogue need contain only a position vector\n\	x[2].\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file modelpsf.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 67 of file modelpsf.c.
References A, add_comment(), allocFloatArray(), argsinit(), B, det(), error_exit, exit(), f(), fits, flag, FLOAT_MAGIC, getargd(), getargi(), getargs(), getflag(), HEADER_SIZE, indx, l, lcpipe, ll, m, mylubksb(), myludcmp(), fitsheader::n, N, fitsheader::ndim, nmodes, nstars, readdoublebuff(), readfitsheader(), readfitsline(), usage, writefitsheader(), writefitsline(), writefitstail(), X, x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.