modefunc.c
NAME
modefunc.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'error.h'
#include 'modefunc.h'
Functions
double f (int l, int m, double *x)
int write2Dpolymodel (char *parfile, int nmodes, int *l, int *m, int asize, double **a, int nvar, char *vardef[], char *xvar)
void get2Dpolymodel (char *filename, int **lptr, int **mptr, int *asize, double ***aptr, int *nmodesptr, int *nvar, char *vardef[], char **xname)
void getmodeamplitudes_lc (char *filename, int **lptr, int **mptr, int *asize, double ***aptr, int *nmodesptr, int *nvar, char *vardef[], char **xname)
void getmodeamplitudes_txt (char *filename, int **lptr, int **mptr, double ***aptr, int *nmodesptr)
void setorigin (double *x)
void modefunc_addargcomment (int argc, char *argv[])
int getvars (FILE *lcpipe, int *nvar, char *vardef[], int *thesize)
Variables
double x0 [2]
char * argstring = NULL
Function Documentation
double f (int l, int m, double * x)
Definition at line 16 of file modefunc.c.
References i, l, m, x, x0, and xx.
Referenced by fitdistortions(), main(), make_r(), make_re(), recircdef(), and rmodel().
void get2Dpolymodel (char * filename, int ** lptr, int ** mptr, int * asize, double *** aptr, int * nmodesptr, int * nvar, char * vardef[], char ** xname)
Definition at line 75 of file modefunc.c.
References getmodeamplitudes_lc(), and getmodeamplitudes_txt().
Referenced by main().
void getmodeamplitudes_lc (char * filename, int ** lptr, int ** mptr, int * asize, double *** aptr, int * nmodesptr, int * nvar, char * vardef[], char ** xname)
Definition at line 98 of file modefunc.c.
References a, error_exit, getvars(), i, l, lcpipe, m, nmodes, and x0.
Referenced by get2Dpolymodel().
void getmodeamplitudes_txt (char * filename, int ** lptr, int ** mptr, double *** aptr, int * nmodesptr)
Definition at line 172 of file modefunc.c.
References a, error_exit, l, line, m, nmodes, and setorigin().
Referenced by get2Dpolymodel().
int getvars (FILE * lcpipe, int * nvar, char * vardef[], int * thesize)
Definition at line 237 of file modefunc.c.
References error_exit, i, lcpipe, line, MODEFUNC_MAX_VARS, pos, and size.
Referenced by getmodeamplitudes_lc(), and main().
void modefunc_addargcomment (int argc, char * argv[])
Definition at line 225 of file modefunc.c.
References argstring.
Referenced by main().
void setorigin (double * x)
Definition at line 219 of file modefunc.c.
References x, and x0.
Referenced by getmodeamplitudes_txt(), and main().
int write2Dpolymodel (char * parfile, int nmodes, int * l, int * m, int asize, double ** a, int nvar, char * vardef[], char * xvar)
Definition at line 32 of file modefunc.c.
References a, argstring, error_exit, i, l, M, m, nmodes, and x0.
Referenced by main().
Variable Documentation
char* argstring = NULL [static]
Definition at line 14 of file modefunc.c.
Referenced by modefunc_addargcomment(), and write2Dpolymodel().
double x0[2] [static]
Definition at line 11 of file modefunc.c.
Referenced by f(), getmodeamplitudes_lc(), setorigin(), and write2Dpolymodel().
Author
Generated automatically by Doxygen for imcat from the source code.