mosaicfit.c
NAME
mosaicfit.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
Defines
#define usage '\n\NAME\n\	mosaicfit --- fit for transformation coefficients for a set of exposures\n\\n\SYNOPSIS\n\	mosaicfit [options...]\n\\n\DESCRIPTION\n\	'mosaicfit' reads a catalogue containing the result of\n\	merging all pairs of 'mosaiccat's (as created by 'mergemosaiccats1'\n\	or 'mergemosaiccats2') and which must contain entries for the\n\	spatial coords 'x', chip-number 'chip' and exp number 'exp'\n\	and magnitude 'mag' from stdin, and fits a linear\n\	model in which x,y are related to \'detector coords\' xd,yd by\n\\n\		xd = x + phi_c * y + dx_c\t\n\		yd = y - phi_c * x + dy_c\t\n\\n\	so chips are rotated thru phi_c and displaced by dx_c, dy_c\n\	relative to coordinate frame define by chip-0\n\	and where sky coords X_e,Y_e are related to detector coords by\n\\n\		X_e = (1 + alpha * (xd * xd + yd * yd)) xd\t\n\		Y_e = (1 + alpha * (xd * xd + yd * yd)) yd\t\n\\n\	and where sky coords in frame defined by exposure-0 are\n\\n\		X = X_e + Phi00_e * X_e + Phi01_e * Y_e + dX_e\t\n\		Y = Y_e + Phi10_e * X_e + Phi11_e * Y_e + dY_e\t\n\\n\	which allows for pointing shifts and rotations as well as\n\	any scale change or differential refraction.\n\	The model is linearised - so only valid for small\n\	alpha, phi_c, dx_c, dy_c, Phi_e (dX_e, dY_e can be large though)\n\	Solves by minimising squared residuals.\n\	We also read magnitudes, which we model as:\n\\n\		m_ce = m + m_c + M_e\n\\n\	where m is the true magnitude and m_c and M_e are magnitude\n\	offsets for chip and exposure (relative to chip-0, exp-0).\n\	Outputs coefficients in tabular form:\n\		alpha\t\n\		0	0	0	0	0	0	0\t\n\			....\t\n\		Phi00_m	Phi01_m	Phi10_m	Phi11_m	dX_m	dY_m	M_m\t\n\			....\t\n\		0	0	0	0\t\n\			....\t\n\		phi_n	dx_n	dy_n	m_n\t\n\			....\t\n\OPTIONS\n\	Options are\n\		-c Nc\t# number of chips (7)\n\		-e Ne\t# number of exposures (11)\n\		-n\t# don't compute magnitude shifts \n\\n\</pre><p>See also <a href=\'./mosaicfitting.ps\'> mosaicfitting.ps </a><pre>\n\\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
#define SCALE 4096.0
Functions
main (int argc, char *argv[])
Define Documentation
#define SCALE 4096.0
Definition at line 73 of file mosaicfit.c.
#define usage '\n\NAME\n\	mosaicfit --- fit for transformation coefficients for a set of exposures\n\\n\SYNOPSIS\n\	mosaicfit [options...]\n\\n\DESCRIPTION\n\	'mosaicfit' reads a catalogue containing the result of\n\	merging all pairs of 'mosaiccat's (as created by 'mergemosaiccats1'\n\	or 'mergemosaiccats2') and which must contain entries for the\n\	spatial coords 'x', chip-number 'chip' and exp number 'exp'\n\	and magnitude 'mag' from stdin, and fits a linear\n\	model in which x,y are related to \'detector coords\' xd,yd by\n\\n\		xd = x + phi_c * y + dx_c\t\n\		yd = y - phi_c * x + dy_c\t\n\\n\	so chips are rotated thru phi_c and displaced by dx_c, dy_c\n\	relative to coordinate frame define by chip-0\n\	and where sky coords X_e,Y_e are related to detector coords by\n\\n\		X_e = (1 + alpha * (xd * xd + yd * yd)) xd\t\n\		Y_e = (1 + alpha * (xd * xd + yd * yd)) yd\t\n\\n\	and where sky coords in frame defined by exposure-0 are\n\\n\		X = X_e + Phi00_e * X_e + Phi01_e * Y_e + dX_e\t\n\		Y = Y_e + Phi10_e * X_e + Phi11_e * Y_e + dY_e\t\n\\n\	which allows for pointing shifts and rotations as well as\n\	any scale change or differential refraction.\n\	The model is linearised - so only valid for small\n\	alpha, phi_c, dx_c, dy_c, Phi_e (dX_e, dY_e can be large though)\n\	Solves by minimising squared residuals.\n\	We also read magnitudes, which we model as:\n\\n\		m_ce = m + m_c + M_e\n\\n\	where m is the true magnitude and m_c and M_e are magnitude\n\	offsets for chip and exposure (relative to chip-0, exp-0).\n\	Outputs coefficients in tabular form:\n\		alpha\t\n\		0	0	0	0	0	0	0\t\n\			....\t\n\		Phi00_m	Phi01_m	Phi10_m	Phi11_m	dX_m	dY_m	M_m\t\n\			....\t\n\		0	0	0	0\t\n\			....\t\n\		phi_n	dx_n	dy_n	m_n\t\n\			....\t\n\OPTIONS\n\	Options are\n\		-c Nc\t# number of chips (7)\n\		-e Ne\t# number of exposures (11)\n\		-n\t# don't compute magnitude shifts \n\\n\</pre><p>See also <a href=\'./mosaicfitting.ps\'> mosaicfitting.ps </a><pre>\n\\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\\n'
Definition at line 6 of file mosaicfit.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 75 of file mosaicfit.c.
References A, alpha, B, c, d, dx, dX, dy, dY, e, exit(), indx, lcpipe, line, m, mag, mylubksb(), myludcmp(), n, phi, SCALE, usage, x, xp(), y, and yp().
Author
Generated automatically by Doxygen for imcat from the source code.