.TH "imview_stuff.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imview_stuff.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Xm/MainW.h>\fP
.br
\fC#include <Xm/Label.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'imview_stuff.h'\fP
.br
\fC#include '../../imlib/fits.h'\fP
.br
\fC#include '../../utils/error.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_GRAYS\fP   128"
.br
.ti -1c
.RI "#define \fBSIZE_GOAL\fP   512"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBalloc_grays\fP (int *\fBn_cells\fP)"
.br
.ti -1c
.RI "void \fBset_grays\fP (int \fBn_cells\fP, int n_lo, int n_hi)"
.br
.ti -1c
.RI "Pixmap \fBmake_pixmap\fP (int fMin, int fMax, int \fBn_cells\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Display * \fBmydisplay\fP"
.br
.ti -1c
.RI "int \fBmyscreen\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "GC \fBmygc\fP"
.br
.ti -1c
.RI "Colormap \fBcmap\fP"
.br
.ti -1c
.RI "Window \fBmywindow\fP"
.br
.ti -1c
.RI "XColor \fBgray\fP [MAX_GRAYS]"
.br
.ti -1c
.RI "unsigned long \fBpixel\fP [MAX_GRAYS]"
.br
.ti -1c
.RI "int \fBn_grays\fP"
.br
.ti -1c
.RI "Widget \fBmain_w\fP"
.br
.ti -1c
.RI "int \fBascii\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MAX_GRAYS   128"
.PP
Definition at line 9 of file motif/imview_stuff.c.
.SS "#define SIZE_GOAL   512"
.PP
Definition at line 10 of file motif/imview_stuff.c.
.SH "Function Documentation"
.PP 
.SS "void alloc_grays (int * n_cells)"
.PP
Definition at line 24 of file motif/imview_stuff.c.
.PP
References cmap, depth, exit(), False, i, info(), main_w, MAX_GRAYS, mydisplay, mygc, myscreen, mywindow, n_cells, n_grays, and pixel.
.PP
Referenced by main().
.SS "Pixmap make_pixmap (int fMin, int fMax, int n_cells)"
.PP
Definition at line 105 of file motif/imview_stuff.c.
.PP
References color_index(), depth, error_exit, exit(), f, free(), gray, i, j, malloc(), mydisplay, mygc, myscreen, mywindow, N, n_cells, read_fits_head(), read_fits_line(), scale, and SIZE_GOAL.
.PP
Referenced by main().
.SS "void set_grays (int n_cells, int n_lo, int n_hi)"
.PP
Definition at line 68 of file motif/imview_stuff.c.
.PP
References cmap, f, gray, i, mydisplay, n_cells, and pixel.
.PP
Referenced by main(), and new_fminmax().
.SH "Variable Documentation"
.PP 
.SS "int \fBascii\fP"
.PP
Definition at line 22 of file motif/imview_stuff.c.
.SS "Colormap \fBcmap\fP\fC [static]\fP"
.PP
Definition at line 16 of file motif/imview_stuff.c.
.PP
Referenced by alloc_grays(), and set_grays().
.SS "int \fBdepth\fP\fC [static]\fP"
.PP
Definition at line 14 of file motif/imview_stuff.c.
.PP
Referenced by alloc_grays(), and make_pixmap().
.SS "XColor gray[MAX_GRAYS]\fC [static]\fP"
.PP
Definition at line 18 of file motif/imview_stuff.c.
.PP
Referenced by make_pixmap(), and set_grays().
.SS "Widget \fBmain_w\fP"
.PP
Definition at line 21 of file motif/imview_stuff.c.
.SS "Display* \fBmydisplay\fP\fC [static]\fP"
.PP
Definition at line 13 of file motif/imview_stuff.c.
.PP
Referenced by alloc_grays(), make_pixmap(), and set_grays().
.SS "GC \fBmygc\fP\fC [static]\fP"
.PP
Definition at line 15 of file motif/imview_stuff.c.
.PP
Referenced by alloc_grays(), and make_pixmap().
.SS "int \fBmyscreen\fP\fC [static]\fP"
.PP
Definition at line 14 of file motif/imview_stuff.c.
.PP
Referenced by alloc_grays(), and make_pixmap().
.SS "Window \fBmywindow\fP\fC [static]\fP"
.PP
Definition at line 17 of file motif/imview_stuff.c.
.PP
Referenced by alloc_grays(), and make_pixmap().
.SS "int \fBn_grays\fP\fC [static]\fP"
.PP
Definition at line 20 of file motif/imview_stuff.c.
.PP
Referenced by alloc_grays().
.SS "unsigned long \fBpixel\fP[MAX_GRAYS]\fC [static]\fP"
.PP
Definition at line 19 of file motif/imview_stuff.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
