imview_stuff.c
NAME
imview_stuff.c -
SYNOPSIS
#include <Xm/MainW.h>
#include <Xm/Label.h>
#include <stdio.h>
#include <stdlib.h>
#include 'imview_stuff.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
Defines
#define MAX_GRAYS 128
#define SIZE_GOAL 512
Functions
void alloc_grays (int *n_cells)
void set_grays (int n_cells, int n_lo, int n_hi)
Pixmap make_pixmap (int fMin, int fMax, int n_cells)
Variables
Display * mydisplay
int myscreen
int depth
GC mygc
Colormap cmap
Window mywindow
XColor gray [MAX_GRAYS]
unsigned long pixel [MAX_GRAYS]
int n_grays
Widget main_w
int ascii
Define Documentation
#define MAX_GRAYS 128
Definition at line 9 of file motif/imview_stuff.c.
#define SIZE_GOAL 512
Definition at line 10 of file motif/imview_stuff.c.
Function Documentation
void alloc_grays (int * n_cells)
Definition at line 24 of file motif/imview_stuff.c.
References cmap, depth, exit(), False, i, info(), main_w, MAX_GRAYS, mydisplay, mygc, myscreen, mywindow, n_cells, n_grays, and pixel.
Referenced by main().
Pixmap make_pixmap (int fMin, int fMax, int n_cells)
Definition at line 105 of file motif/imview_stuff.c.
References color_index(), depth, error_exit, exit(), f, free(), gray, i, j, malloc(), mydisplay, mygc, myscreen, mywindow, N, n_cells, read_fits_head(), read_fits_line(), scale, and SIZE_GOAL.
Referenced by main().
void set_grays (int n_cells, int n_lo, int n_hi)
Definition at line 68 of file motif/imview_stuff.c.
References cmap, f, gray, i, mydisplay, n_cells, and pixel.
Referenced by main(), and new_fminmax().
Variable Documentation
int ascii
Definition at line 22 of file motif/imview_stuff.c.
Colormap cmap [static]
Definition at line 16 of file motif/imview_stuff.c.
Referenced by alloc_grays(), and set_grays().
int depth [static]
Definition at line 14 of file motif/imview_stuff.c.
Referenced by alloc_grays(), and make_pixmap().
XColor gray[MAX_GRAYS] [static]
Definition at line 18 of file motif/imview_stuff.c.
Referenced by make_pixmap(), and set_grays().
Widget main_w
Definition at line 21 of file motif/imview_stuff.c.
Display* mydisplay [static]
Definition at line 13 of file motif/imview_stuff.c.
Referenced by alloc_grays(), make_pixmap(), and set_grays().
GC mygc [static]
Definition at line 15 of file motif/imview_stuff.c.
Referenced by alloc_grays(), and make_pixmap().
int myscreen [static]
Definition at line 14 of file motif/imview_stuff.c.
Referenced by alloc_grays(), and make_pixmap().
Window mywindow [static]
Definition at line 17 of file motif/imview_stuff.c.
Referenced by alloc_grays(), and make_pixmap().
int n_grays [static]
Definition at line 20 of file motif/imview_stuff.c.
Referenced by alloc_grays().
unsigned long pixel[MAX_GRAYS] [static]
Definition at line 19 of file motif/imview_stuff.c.
Author
Generated automatically by Doxygen for imcat from the source code.