.TH "mova.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mova.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	mova - calculate moving average of tabulated \fBdata\fP\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	mova \fBxmin\fP \fBxmax\fP nbins binwidth\\\fBn\fP\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	mova calculates average of y-values (column 2) binned according\\\fBn\fP\\	to x-value (column 1) with nbins bins of width binwidth between \fBxmin\fP and \fBxmax\fP.\\\fBn\fP\\	It outputs \fBa\fP table with <y>,x,\fBn\fP for non empty bins.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser - kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\n\\NAME\\\fBn\fP\\	mova - calculate moving average of tabulated \fBdata\fP\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	mova \fBxmin\fP \fBxmax\fP nbins binwidth\\\fBn\fP\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	mova calculates average of y-values (column 2) binned according\\\fBn\fP\\	to x-value (column 1) with nbins bins of width binwidth between \fBxmin\fP and \fBxmax\fP.\\\fBn\fP\\	It outputs \fBa\fP table with <y>,x,\fBn\fP for non empty bins.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser - kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP'"
.PP
Definition at line 7 of file mova.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 27 of file mova.c.
.PP
References dx, exit(), line, usage, x, xmax, xmin, and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
