.TH "Multitype" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Multitype \- 
.SH SYNOPSIS
.br
.PP
\fC#include <f2c.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBinteger1\fP \fBg\fP"
.br
.ti -1c
.RI "\fBshortint\fP \fBh\fP"
.br
.ti -1c
.RI "\fBinteger\fP \fBi\fP"
.br
.ti -1c
.RI "\fBreal\fP \fBr\fP"
.br
.ti -1c
.RI "\fBdoublereal\fP \fBd\fP"
.br
.ti -1c
.RI "\fBcomplex\fP \fBc\fP"
.br
.ti -1c
.RI "\fBdoublecomplex\fP \fBz\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBcomplex\fP \fBMultitype::c\fP"
.PP
Definition at line 134 of file myf2c.h.
.SS "\fBdoublereal\fP \fBMultitype::d\fP"
.PP
Definition at line 133 of file myf2c.h.
.SS "\fBinteger1\fP \fBMultitype::g\fP"
.PP
Definition at line 128 of file myf2c.h.
.SS "\fBshortint\fP \fBMultitype::h\fP"
.PP
Definition at line 129 of file myf2c.h.
.SS "\fBinteger\fP \fBMultitype::i\fP"
.PP
Definition at line 130 of file myf2c.h.
.SS "\fBreal\fP \fBMultitype::r\fP"
.PP
Definition at line 132 of file myf2c.h.
.SS "\fBdoublecomplex\fP \fBMultitype::z\fP"
.PP
Definition at line 135 of file myf2c.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
