myfft.c
NAME
myfft.c -
SYNOPSIS
#include <stdio.h>
#include <limits.h>
#include <math.h>
#include 'myfft.h'
#include '../utils/error.h'
#include '../imlib/fits.h'
Defines
#define PI M_PI
Functions
void cycleimage (float **f, int Nx, int Ny, int x0, int y0)
void substitute (float **f, int Nx, int Ny, float magicsubstitute)
Define Documentation
#define PI M_PI
Definition at line 12 of file myfft.c.
Function Documentation
void cycleimage (float ** f, int Nx, int Ny, int x0, int y0)
Definition at line 18 of file myfft.c.
References F(), f, free(), Nx, Ny, x, xp(), y, and yp().
Referenced by ccf(), forward_cfft(), inverse_cfft(), main(), myfftwcfft(), and power().
void substitute (float ** f, int Nx, int Ny, float magicsubstitute)
Definition at line 90 of file myfft.c.
References f, FLOAT_MAGIC, Nx, Ny, x, and y.
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
Author
Generated automatically by Doxygen for imcat from the source code.