myfft.h
NAME
myfft.h -
SYNOPSIS
Defines
#define SHORT_IMAGE 0
#define FLOAT_IMAGE 1
#define DOUBLE_IMAGE 2
Functions
void forward_fft (float **f, int Nx, int Ny, fft_type fk)
void inverse_fft (fft_type fk, int Nx, int Ny, float **f)
void filter (fft_type fk, int Nx, int Ny, float(*filterfunc)(float ki, float kj))
void cfilter (fft_type fk, int Nx, int Ny, float(*rfunc)(float ki, float kj), float(*ifunc)(float ki, float kj))
void ccf (fft_type fk1, fft_type fk2, int Nx, int Ny, float **ff12, int x0, int y0)
void power (fft_type fk, int Nx, int Ny, float **p, int x0, int y0)
void cycleimage (float **f, int Nx, int Ny, int x0, int y0)
void alloc_fft (fft_type *fk, int Nx, int Ny)
void free_fft (fft_type fk, int Nx, int Ny)
void substitute (float **f, int Nx, int Ny, float magicsubstitute)
void copy_fft (fft_type fksrc, int Nx, int Ny, fft_type fkdest)
void get_fft (fft_type fk, int Nx, int Ny, float **fdest)
void set_fft (fft_type fk, int Nx, int Ny, float **fsrc)
void forward_cfft (float **fsrc, int nx, int ny, float **fdst)
void inverse_cfft (float **fsrc, int nx, int ny, float **fdst)
Define Documentation
#define DOUBLE_IMAGE 2
Definition at line 139 of file myfft.h.
#define FLOAT_IMAGE 1
Definition at line 138 of file myfft.h.
#define SHORT_IMAGE 0
Definition at line 137 of file myfft.h.
Function Documentation
void alloc_fft (fft_type * fk, int Nx, int Ny)
Definition at line 250 of file fft_FFTPACK.c.
References error_exit, fft_type, n, Nx, Ny, and y.
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void ccf (fft_type fk1, fft_type fk2, int Nx, int Ny, float ** ff12, int x0, int y0)
Definition at line 193 of file fft_FFTPACK.c.
References a1, a2, b1, b2, cycleimage(), fft_type, inverse_fft(), ix, n, Nx, and Ny.
Referenced by main().
void cfilter (fft_type fk, int Nx, int Ny, float(* rfunc)(float ki, float kj), float(* ifunc)(float ki, float kj))
Definition at line 167 of file fft_FFTPACK.c.
References fft_type, ifunc(), ix, n, Nx, Ny, PI, and rfunc().
Referenced by main().
void copy_fft (fft_type fksrc, int Nx, int Ny, fft_type fkdest)
Definition at line 333 of file fft_FFTPACK.c.
References fft_type, n, Nx, Ny, x, and y.
Referenced by main().
void cycleimage (float ** f, int Nx, int Ny, int x0, int y0)
Definition at line 18 of file myfft.c.
References f, F(), free(), Nx, Ny, x, xp(), y, and yp().
Referenced by ccf(), forward_cfft(), inverse_cfft(), main(), myfftwcfft(), and power().
void filter (fft_type fk, int Nx, int Ny, float(* filterfunc)(float ki, float kj))
Definition at line 147 of file fft_FFTPACK.c.
References fft_type, ix, n, Nx, Ny, and PI.
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void forward_cfft (float ** fsrc, int nx, int ny, float ** fdst)
Definition at line 393 of file fft_FFTPACK.c.
References c, cfftf_(), cffti_(), cycleimage(), free(), myfftwcfft(), nx, ny, x, and y.
Referenced by main().
void forward_fft (float ** f, int Nx, int Ny, fft_type fk)
Definition at line 32 of file fft_FFTPACK.c.
References cfftf_(), cffti_(), exit(), f, fft_type, FORWARD_X, FORWARD_Y, free(), n, Nx, nx, Ny, ny, r, rfftf_(), rffti_(), shmfree(), x, and y.
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void free_fft (fft_type fk, int Nx, int Ny)
Definition at line 270 of file fft_FFTPACK.c.
References fft_type, and free().
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void get_fft (fft_type fk, int Nx, int Ny, float ** fdest)
Definition at line 346 of file fft_FFTPACK.c.
References fft_type, ix, n, Nx, and Ny.
Referenced by main().
void inverse_cfft (float ** fsrc, int nx, int ny, float ** fdst)
Definition at line 444 of file fft_FFTPACK.c.
References c, cfftb_(), cffti_(), cycleimage(), free(), myfftwcfft(), nx, ny, x, and y.
Referenced by main().
void inverse_fft (fft_type fk, int Nx, int Ny, float ** f)
Definition at line 90 of file fft_FFTPACK.c.
References cfftb_(), cffti_(), exit(), f, fft_type, free(), INVERSE_X, INVERSE_Y, n, Nx, nx, Ny, ny, r, rfftb_(), rffti_(), shmfree(), x, and y.
Referenced by ccf(), exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
void power (fft_type fk, int Nx, int Ny, float ** p, int x0, int y0)
Definition at line 218 of file fft_FFTPACK.c.
References a, b, cycleimage(), fft_type, ix, n, Nx, Ny, x, and y.
Referenced by main().
void set_fft (fft_type fk, int Nx, int Ny, float ** fsrc)
Definition at line 372 of file fft_FFTPACK.c.
References fft_type, ix, n, Nx, and Ny.
Referenced by main().
void substitute (float ** f, int Nx, int Ny, float magicsubstitute)
Definition at line 90 of file myfft.c.
References f, FLOAT_MAGIC, Nx, Ny, x, and y.
Referenced by exponentialfilter(), gaussfilter(), kolmogorovfilter(), main(), mexicanfilter(), powerlawfilter(), and schecterfilter().
Author
Generated automatically by Doxygen for imcat from the source code.