.TH "Namelist" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Namelist \- 
.SH SYNOPSIS
.br
.PP
\fC#include <f2c.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBVardesc\fP ** \fBvars\fP"
.br
.ti -1c
.RI "int \fBnvars\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBVardesc\fP ** \fBvars\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBVardesc\fP ** \fBvars\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* \fBNamelist::name\fP"
.PP
Definition at line 151 of file myf2c.h.
.SS "char* \fBNamelist::name\fP"
.PP
Definition at line 184 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBNamelist::name\fP"
.PP
Definition at line 145 of file fftpack_c/f2c.h.
.SS "int \fBNamelist::nvars\fP"
.PP
Definition at line 153 of file myf2c.h.
.SS "\fBVardesc\fP** \fBNamelist::vars\fP"
.PP
Definition at line 152 of file myf2c.h.
.SS "\fBVardesc\fP** \fBNamelist::vars\fP"
.PP
Definition at line 185 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "\fBVardesc\fP** \fBNamelist::vars\fP"
.PP
Definition at line 146 of file fftpack_c/f2c.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
