libiis.c
NAME
libiis.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include 'libiis.h'
#include '../../imlib/fits.h'
Functions
int iis_display (float **f, int nx, int ny, float fmin, float fmax, int frame)
void iis_cur (float *x, float *y, char *ch)
void iis_drawcirc (float xcen, float ycen, float radius, int colour, int frame)
void iis_open (char *inpipe, char *outpipe, int fb, int fbx, int fby)
void iis_close ()
void iis_write (char *buf, int size)
void iis_read (char *buf, int size)
void iis_checksum (short *hdr)
void iis_error (char *error1, char *error2)
int iis_chan (int frame)
int iis_round (float i)
float iis_abs (float x)
Function Documentation
float iis_abs (float x)
Definition at line 620 of file nkkgb/libiis.c.
References x.
Referenced by iis_drawcirc().
int iis_chan (int frame)
Definition at line 601 of file nkkgb/libiis.c.
References CHAN1, CHAN2, CHAN3, CHAN4, frame, and iis_error().
Referenced by iis_display(), and iis_drawcirc().
void iis_checksum (short * hdr)
Definition at line 585 of file nkkgb/libiis.c.
References CHECK_SUM, CHECKSUMVAL, and indx.
Referenced by iis_cur(), iis_display(), and iis_drawcirc().
void iis_close ()
Definition at line 550 of file nkkgb/libiis.c.
void iis_cur (float * x, float * y, char * ch)
Definition at line 255 of file nkkgb/libiis.c.
References buf, CHECK_SUM, iis_checksum(), iis_error(), iis_write(), IMCURSOR, IREAD, SUB_UNIT, SZ_WCSTEXT, T_REGISTER, THING_COUNT, TRANSFER_ID, wcs, x, X_REGISTER, y, Y_REGISTER, and Z_REGISTER.
int iis_display (float ** f, int nx, int ny, float fmin, float fmax, int frame)
Definition at line 137 of file nkkgb/libiis.c.
References ADVXONTC, ADVYONXOV, ALLBITPL, BLOCKXFER, BUFFSZ, CHECK_SUM, f, fbconfig, FEEDBACK, FLOAT_MAGIC, FMAX, FMIN, fmin, frame, free(), iis_chan(), iis_checksum(), iis_error(), iis_write(), IIS_YELLOW, IWRITE, j, nx, ny, PACKED, REFRESH, SUB_UNIT, SZ_WCSTEXT, T_REGISTER, THING_COUNT, TRANSFER_ID, val, WCS, x, X_REGISTER, xo, xx, y, Y_REGISTER, yo, yy, and Z_REGISTER.
Referenced by main().
void iis_drawcirc (float xcen, float ycen, float radius, int colour, int frame)
Definition at line 288 of file nkkgb/libiis.c.
References ADVXONTC, ADVYONXOV, ALLBITPL, BLOCKXFER, CHECK_SUM, frame, free(), i, iis_abs(), iis_chan(), iis_checksum(), iis_error(), iis_read(), iis_round(), iis_write(), IREAD, IWRITE, j, label, PACKED, radius, RBUFFSZ, REFRESH, SUB_UNIT, SZ_WCSTEXT, T_REGISTER, THING_COUNT, TRANSFER_ID, WCS, X_REGISTER, xo, xx, y, Y_REGISTER, ymax, ymin, yo, yy, and Z_REGISTER.
void iis_error (char * error1, char * error2)
Definition at line 594 of file nkkgb/libiis.c.
References exit().
Referenced by iis_chan(), iis_cur(), iis_display(), iis_drawcirc(), iis_open(), iis_read(), and iis_write().
void iis_open (char * inpipe, char * outpipe, int fb, int fbx, int fby)
Definition at line 441 of file nkkgb/libiis.c.
References fb, fbconfig, i, iis_error(), imtdev, j, and STRSIZE.
Referenced by main().
void iis_read (char * buf, int size)
Definition at line 573 of file nkkgb/libiis.c.
References buf, iis_error(), n, and size.
Referenced by iis_drawcirc().
int iis_round (float i)
Definition at line 613 of file nkkgb/libiis.c.
References i.
Referenced by iis_drawcirc().
void iis_write (char * buf, int size)
Definition at line 559 of file nkkgb/libiis.c.
References buf, iis_error(), n, and size.
Referenced by iis_cur(), iis_display(), and iis_drawcirc().
Author
Generated automatically by Doxygen for imcat from the source code.