.TH "iisdisplay.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iisdisplay.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBopeniispipe\fP (void)"
.br
.ti -1c
.RI "int \fBiisdisplay\fP (float **f, int \fBN1\fP, int \fBN2\fP, float \fBfmin\fP, float \fBfmax\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int iisdisplay (float ** f, int N1, int N2, float fmin, float fmax)"
.PP
Definition at line 41 of file iisdisplay.c.
.PP
References ADVXONTC, ADVYONXOV, ALLBITPL, CHAN2, CHECK_SUM, data, f, ff, FLOAT_MAGIC, FMAX, fmin, IIS_YELLOW, iispipe, indx, IWRITE, ix, N1, N2, REFRESH, scale, SUB_UNIT, T_REGISTER, THING_COUNT, TRANSFER_ID, x, X_REGISTER, y, Y_REGISTER, and Z_REGISTER.
.SS "int openiispipe (void)"
.PP
Definition at line 23 of file iisdisplay.c.
.PP
References exit(), iispipe, and syspipe.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
