iis.c
NAME
iis.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include <float.h>
#include 'libiis.h'
#include '../../imlib/fits.h'
Defines
#define usage '\n\n\NAME\n\	iis - pipe fits image data into saopipe\n\\n\SYNOPSIS\n\	iis [options...]\n\	where options are:\n\		-u		# print this message\n\		-f fmin fmax	# limits for pixel values\n\		-p pipename	# supply FIFO pipe name\n\\n\DESCRIPTION\n\	\'iis\' reads a fits image from stdin, prepends an iis header\n\	and writes the output to a FIFO pipe /dev/imt1o so that saoimage can\n\	display it.\n\	If the standard FIFO does not exist (it typically won't unless\n\	you have IRAF installed) then create one with e.g.\n\		'mknod ~/dev/saopipe p'\n\	and then fire up saoimage with\n\		'saoimage -idev ~/dev/saopipe &'\n\	Beware: some old versions of saoimage crash when you try to\n\	supply 'idev' argument.\n\	Many thanks to Karl Glazebrook for refinements\n\	to original code.\n\\n\AUTHOR\n\	Nick Kaiser (kaiser@cita.utoronto.ca)\n\\n\n'
#define MAGIC FLOAT_MAGIC
#define MINFLOAT FLT_MIN
#define MAXFLOAT FLT_MAX
Functions
main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 44 of file nkkgb/iis.c.
#define MAXFLOAT FLT_MAX
Definition at line 46 of file nkkgb/iis.c.
#define MINFLOAT FLT_MIN
Definition at line 45 of file nkkgb/iis.c.
#define usage '\n\n\NAME\n\	iis - pipe fits image data into saopipe\n\\n\SYNOPSIS\n\	iis [options...]\n\	where options are:\n\		-u		# print this message\n\		-f fmin fmax	# limits for pixel values\n\		-p pipename	# supply FIFO pipe name\n\\n\DESCRIPTION\n\	\'iis\' reads a fits image from stdin, prepends an iis header\n\	and writes the output to a FIFO pipe /dev/imt1o so that saoimage can\n\	display it.\n\	If the standard FIFO does not exist (it typically won't unless\n\	you have IRAF installed) then create one with e.g.\n\		'mknod ~/dev/saopipe p'\n\	and then fire up saoimage with\n\		'saoimage -idev ~/dev/saopipe &'\n\	Beware: some old versions of saoimage crash when you try to\n\	supply 'idev' argument.\n\	Many thanks to Karl Glazebrook for refinements\n\	to original code.\n\\n\AUTHOR\n\	Nick Kaiser (kaiser@cita.utoronto.ca)\n\\n\n'
Definition at line 8 of file nkkgb/iis.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 48 of file nkkgb/iis.c.
References exit(), f, fb, fits, fmin, frame, iis_close(), iis_display(), iis_open(), MAGIC, MAXFLOAT, MINFLOAT, N1, N2, read2Dfloatimage(), usage, x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.