.TH "ntuplet" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ntuplet \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmask\fP"
.br
.ti -1c
.RI "int \fBnobjs\fP"
.br
.ti -1c
.RI "double \fBsize\fP"
.br
.ti -1c
.RI "\fBobject\fP ** \fBobj\fP"
.br
.ti -1c
.RI "\fBntuplet\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBntuplet::mask\fP"
.PP
Definition at line 86 of file mergecatsmain.c.
.PP
Referenced by fan().
.SS "struct \fBntuplet\fP* \fBntuplet::next\fP"
.PP
Definition at line 90 of file mergecatsmain.c.
.PP
Referenced by fan(), and main().
.SS "int \fBntuplet::nobjs\fP"
.PP
Definition at line 87 of file mergecatsmain.c.
.PP
Referenced by fan().
.SS "\fBobject\fP** \fBntuplet::obj\fP"
.PP
Definition at line 89 of file mergecatsmain.c.
.PP
Referenced by fan().
.SS "double \fBntuplet::size\fP"
.PP
Definition at line 88 of file mergecatsmain.c.
.PP
Referenced by fan().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
