nuketrailobjects.c
NAME
nuketrailobjects.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../../utils/error.h'
#include '../../utils/args.h'
#include '../../imlib/fits.h'
Defines
#define usage '\n\n\NAME\n\	nuketrailobjects - mask satellite trails etc\n\\n\SYNOPSIS\n\	nuketrailobjects [options....] srcfits d w\n\		-u		# print this man page\n\\n\DESCRIPTION\n\ 'nuketrailobjects' reads a catalogue from stdin which must contain\n\	a 2 vector 'x' and a scalar phi (possibly generated by\n\	'findtrailobjects') and then sets to MAGIC any pixels\n\	in srcimage lying in a strip of width (2 w + 1) straddling the\n\	line of half-length d passing through x with orientation phi.\n\	Resulting FITS image is sent to stdout.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\NAME\n\	nuketrailobjects - mask satellite trails etc\n\\n\SYNOPSIS\n\	nuketrailobjects [options....] srcfits d w\n\		-u		# print this man page\n\\n\DESCRIPTION\n\ 'nuketrailobjects' reads a catalogue from stdin which must contain\n\	a 2 vector 'x' and a scalar phi (possibly generated by\n\	'findtrailobjects') and then sets to MAGIC any pixels\n\	in srcimage lying in a strip of width (2 w + 1) straddling the\n\	line of half-length d passing through x with orientation phi.\n\	Resulting FITS image is sent to stdout.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file nuketrailobjects.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 33 of file nuketrailobjects.c.
References argsinit(), d, error_exit, exit(), fits, flag, FLAG_ARG, getargi(), getargs(), getflag(), ipf, fitsheader::n, N1, N2, nextargtype(), phi, readfitsheader(), usage, w, x, xp(), and yp().
Author
Generated automatically by Doxygen for imcat from the source code.