.TH "numobj" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
numobj \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double * \fBf\fP"
.br
.ti -1c
.RI "\fBnumobj\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double* \fBnumobj::f\fP"
.PP
Definition at line 38 of file gridavg.c.
.PP
Referenced by average(), and main().
.SS "struct \fBnumobj\fP* \fBnumobj::next\fP"
.PP
Definition at line 39 of file gridavg.c.
.PP
Referenced by average(), and main().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
