.TH "zap.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zap.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include 'zap.h'\fP
.br
\fC#include '../../imtools/magic.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBzap\fP (int \fBmode\fP, double rmax, double *x, float **f, float **fzap, short **nzap, int \fBN1\fP, int \fBN2\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void zap (int mode, double rmax, double * x, float ** f, float ** fzap, short ** nzap, int N1, int N2)"
.PP
Definition at line 10 of file objectfinding/zap.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
