.TH "obsdata.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obsdata.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLATOBSINDEG\fP   19.75"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LATOBSINDEG   19.75"
.PP
Definition at line 5 of file obsdata.h.
.PP
Referenced by airmassmin(), and main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
