ecorrect.c
NAME
ecorrect.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include '../../utils/error.h'
#include '../../catlib/cat.h'
#include 'efit_stuff.h'
Defines
#define usage '\n\n\n\SYNOPSIS\n\		ecorrect	[option...] a.cat b.cat .....\n\			-f efitdata		# file for stellar e / psm model parameters (efit.out)\n\\n\DESCRIPTION\n\		\'ecorrect\' corrects ellipticities in number of catalogues\n\		according to model for psf polarization p = e / psm as determined by efit\n\		correction applied is e -= psm * p. If you use multiple cats\n\		be sure that they correspond precisely to those fed to efit.\n\		Ecorrect generates a new catalogue with suffix '.cat.x' for\n\		each input cat.\n\\n\n\n'
#define MAX_CATS 1000
Functions
main (int argc, char *argv[])
Define Documentation
#define MAX_CATS 1000
Definition at line 25 of file old/ecorrect.c.
Referenced by main().
#define usage '\n\n\n\SYNOPSIS\n\		ecorrect	[option...] a.cat b.cat .....\n\			-f efitdata		# file for stellar e / psm model parameters (efit.out)\n\\n\DESCRIPTION\n\		\'ecorrect\' corrects ellipticities in number of catalogues\n\		according to model for psf polarization p = e / psm as determined by efit\n\		correction applied is e -= psm * p. If you use multiple cats\n\		be sure that they correspond precisely to those fed to efit.\n\		Ecorrect generates a new catalogue with suffix '.cat.x' for\n\		each input cat.\n\\n\n\n'
Definition at line 1 of file old/ecorrect.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 27 of file old/ecorrect.c.
References addargscomment(), object::addrlist, allocobjectcontents(), BINARY_FILE_TYPE, connectobjecttocathead(), e, error_exit, exit(), frame, g(), getobjectitemindex(), i, LC_NUM_FMT, MAX_CATS, N, newobject(), nframes, nmodes, order, readamplitudes(), readcathead(), readobject(), setcatipf(), setcatopf(), setcatopfiletype(), setframesize(), setnframes(), usage, writecathead(), writeobject(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.