efit_stuff.h
NAME
efit_stuff.h -
SYNOPSIS
Defines
#define GRAD1 0
#define GRAD2 1
#define GRADGRAD11 2
#define GRADGRAD12 3
#define GRADGRAD22 4
Functions
double g (int mode, int frame, double xx, double yy)
void readamplitudes (int *nmodes, int *nframes, int *framesize, int *order, double ***amp, FILE *stream)
void setnframes (int nframes)
void setframesize (int N)
Define Documentation
#define GRAD1 0
Definition at line 16 of file old/efit_stuff.h.
Referenced by g().
#define GRAD2 1
Definition at line 17 of file old/efit_stuff.h.
Referenced by g().
#define GRADGRAD11 2
Definition at line 18 of file old/efit_stuff.h.
Referenced by g().
#define GRADGRAD12 3
Definition at line 19 of file old/efit_stuff.h.
Referenced by g().
#define GRADGRAD22 4
Definition at line 20 of file old/efit_stuff.h.
Referenced by g().
Function Documentation
double g (int mode, int frame, double xx, double yy)
Definition at line 15 of file old/efit_stuff.c.
References error_exit, frame, framesize, GRAD1, GRAD2, GRADGRAD11, GRADGRAD12, GRADGRAD22, nframes, x, xx, and yy.
Referenced by fillarrays(), main(), makeresiduals(), and modelrms().
void readamplitudes (int * nmodes, int * nframes, int * framesize, int * order, double *** amp, FILE * stream)
Definition at line 50 of file old/efit_stuff.c.
References error_exit, framesize, line, nframes, nmodes, and order.
Referenced by main().
void setframesize (int N)
Definition at line 164 of file efit_stuff.c.
References framesize, and N.
Referenced by main().
void setnframes (int nframes)
Definition at line 90 of file old/efit_stuff.c.
References nframes.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.