efit.c
NAME
efit.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../utils/error.h'
#include 'efit_stuff.h'
#include '../../utils/lu.h'
#include '../../imlib/fits.h'
Defines
#define usage '\n\n\n\NAME\n\		efit --- generate model for stellar ellipticities\n\SYNOPSIS\n\		efit	[option...] a.cat b.cat ....\n\			-m emax		# reject stars with |e| > emax (0.4)\n\			-x numax	# don't use stars with |eres| > numax * sigma (3.0)\n\			-n N		# image size (2048)\n\			-o order	# output this order model to stdout (1)\n\			-r		# output e's and residuals\n\			-e ename	# name for ellipticity (e)\n\\n\DESCRIPTION\n\		\'efit\' fits the p = psm^{-1} e values of stars from a list of cat files\n\		to a model of constant offset for each frame plus a global 1st or\n\		2nd order Taylor expansion\n\		Does least squares 1st order fit, then refits ignoring outliers > numax * sigma\n\		finally refits 2nd order Taylor expansion\n\\n\n\n'
Functions
void fillarrays (void)
void makeresiduals (double *sigmae)
double modelrms (int mode1, int mode2)
void writeamplitudes (int order, int framesize)
void printoffsets (void)
void printgrads (void)
void printgradgrads (void)
main (int argc, char *argv[])
Variables
double ** x [2]
double ** e [2]
double ** eres [2]
double ereslimit
int nframes = 0 *nobj nmodes noutliers
double ** A
double * B [2]
double * a [2]
Define Documentation
#define usage '\n\n\n\NAME\n\		efit --- generate model for stellar ellipticities\n\SYNOPSIS\n\		efit	[option...] a.cat b.cat ....\n\			-m emax		# reject stars with |e| > emax (0.4)\n\			-x numax	# don't use stars with |eres| > numax * sigma (3.0)\n\			-n N		# image size (2048)\n\			-o order	# output this order model to stdout (1)\n\			-r		# output e's and residuals\n\			-e ename	# name for ellipticity (e)\n\\n\DESCRIPTION\n\		\'efit\' fits the p = psm^{-1} e values of stars from a list of cat files\n\		to a model of constant offset for each frame plus a global 1st or\n\		2nd order Taylor expansion\n\		Does least squares 1st order fit, then refits ignoring outliers > numax * sigma\n\		finally refits 2nd order Taylor expansion\n\\n\n\n'
Definition at line 5 of file old/efit.c.
Function Documentation
void fillarrays (void)
main (int argc, char * argv[])
Definition at line 51 of file old/efit.c.
References A, a, B, d, e, eres, ereslimit, error_exit, exit(), fillarrays(), frame, indx, l, line, m, makeresiduals(), modelrms(), mylubksb(), myludcmp(), N, nframes, nmodes, nobj, noutliers, order, setframesize(), setnframes(), usage, writeamplitudes(), and x.
void makeresiduals (double * sigmae)
Referenced by main().
double modelrms (int mode1, int mode2)
Definition at line 324 of file old/efit.c.
References a, frame, g(), nframes, nobj, and x.
Referenced by main().
void printgradgrads (void)
Definition at line 394 of file old/efit.c.
References a, l, and nframes.
Referenced by writeamplitudes().
void printgrads (void)
Definition at line 382 of file old/efit.c.
References a, l, and nframes.
Referenced by writeamplitudes().
void printoffsets (void)
Definition at line 370 of file old/efit.c.
References a, l, and nframes.
Referenced by writeamplitudes().
void writeamplitudes (int order, int framesize)
Definition at line 347 of file old/efit.c.
References error_exit, nframes, nmodes, order, printgradgrads(), printgrads(), and printoffsets().
Referenced by main().
Variable Documentation
double * a[2]
Definition at line 41 of file old/efit.c.
double** A
Definition at line 41 of file old/efit.c.
double * B[2]
Definition at line 41 of file old/efit.c.
double** e[2]
Definition at line 39 of file old/efit.c.
double ** eres[2]
Definition at line 39 of file old/efit.c.
double ereslimit
Definition at line 39 of file old/efit.c.
int nframes = 0 *nobj nmodes noutliers
Definition at line 40 of file old/efit.c.
double** x[2]
Definition at line 38 of file old/efit.c.
Author
Generated automatically by Doxygen for imcat from the source code.