efit_stuff.c
NAME
efit_stuff.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include '../../utils/error.h'
#include 'efit_stuff.h'
Functions
double g (int mode, int frame, double xx, double yy)
void readamplitudes (int *nmodes, int *nframes, int *framesize, int *order, double ***amp, FILE *stream)
void setnframes (int xnframes)
void setframesize (int N)
Variables
int nframes
int framesize
Function Documentation
double g (int mode, int frame, double xx, double yy)
Definition at line 15 of file old/efit_stuff.c.
References error_exit, frame, framesize, GRAD1, GRAD2, GRADGRAD11, GRADGRAD12, GRADGRAD22, nframes, x, xx, and yy.
Referenced by fillarrays(), main(), makeresiduals(), and modelrms().
void readamplitudes (int * nmodes, int * nframes, int * framesize, int * order, double *** amp, FILE * stream)
Definition at line 50 of file old/efit_stuff.c.
References error_exit, framesize, line, nframes, nmodes, and order.
Referenced by main().
void setframesize (int N)
Definition at line 97 of file old/efit_stuff.c.
References framesize, and N.
Referenced by main().
void setnframes (int xnframes)
Definition at line 90 of file old/efit_stuff.c.
References nframes.
Referenced by main().
Variable Documentation
int framesize [static]
Definition at line 13 of file old/efit_stuff.c.
Referenced by g(), readamplitudes(), and setframesize().
int nframes [static]
Definition at line 13 of file old/efit_stuff.c.
Author
Generated automatically by Doxygen for imcat from the source code.