oldfilters.c
NAME
oldfilters.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <limits.h>
#include '../utils/error.h'
#include 'filters.h'
#include 'fits.h'
#include '../fftlib/myfft.h'
Defines
#define max(a, b) ((a) < (b) ? (b) : (a))
#define min(a, b) ((a) < (b) ? (a) : (b))
#define ZMAX 10
Functions
void gaussian_kernel_filter (short **f, short **fs, int N1, int N2, int m, float rf)
void kernel_filter (short **f, short **fs, int N1, int N2, int m, float(*filterfunc)(int di, int dj))
void block_filter (short **f, short **fs, int N1, int N2, int m)
void tukey (short **f, int N1, int N2)
void schecterfilter (float **f, int N1, int N2, float **fs, float sigma1, float sigma2, float alpha, float magicsubstitute)
void kolmogorovfilter (float **f, int N1, int N2, float **fs, float sigma, float magicsubstitute)
void gaussfilter (float **f, int N1, int N2, float **fs, float A, float B, float phi, float magicsubstitute)
void mexicanfilter (float **f, int N1, int N2, float **fs, float sigma1, float sigma2, float magicsubstitute)
void powerlawfilter (float **f, int N1, int N2, float **fs, float alpha, float magicsubstitute)
void powerspectrum (float **f, int N1, int N2, float **P, int **nmodes)
float gaussianfilterfunc (int i, int j)
float schecterfilterfunction (float ki, float kj)
float kolmogorovfilterfunction (float ki, float kj)
float gaussballfunction (float ki, float kj)
float gaussellipsoidfunction (float ki, float kj)
float mexicanfilterfunction (float ki, float kj)
float powerlawfilterfunction (float ki, float kj)
Variables
float gaussballsigma
float gaussfilterparam
float schectersigma1
float schectersigma2
float schecteralpha
float kolmogorovsigmasquared
float gausssigma11
float gausssigma22
float gausssigma12
float mexicansigma1
float mexicansigma2
float powerlawalpha
Define Documentation
#define max(a, b) ((a) < (b) ? (b) : (a))
filters.c --- image processing routines Definition at line 15 of file oldfilters.c.
#define min(a, b) ((a) < (b) ? (a) : (b))
Definition at line 16 of file oldfilters.c.
#define ZMAX 10
Definition at line 387 of file oldfilters.c.
Function Documentation
void block_filter (short ** f, short ** fs, int N1, int N2, int m)
Definition at line 85 of file oldfilters.c.
References error_exit, f, i, j, m, N1, N2, and SHORT_MAGIC.
Referenced by main().
float gaussballfunction (float ki, float kj)
Definition at line 420 of file oldfilters.c.
References gaussballsigma, z, and ZMAX.
float gaussellipsoidfunction (float ki, float kj)
Definition at line 433 of file oldfilters.c.
References gausssigma11, gausssigma12, gausssigma22, z, and ZMAX.
void gaussfilter (float ** f, int N1, int N2, float ** fs, float A, float B, float phi, float magicsubstitute)
Definition at line 250 of file oldfilters.c.
References A, alloc_fft(), B, c, f, fft_type, filter(), forward_fft(), free_fft(), gaussballfunction(), gaussballsigma, gaussellipsoidfunction(), gausssigma11, gausssigma12, gausssigma22, i, inverse_fft(), j, N1, N2, phi, PI, and substitute().
Referenced by main().
void gaussian_kernel_filter (short ** f, short ** fs, int N1, int N2, int m, float rf)
Definition at line 27 of file oldfilters.c.
References f, gaussfilterparam, gaussianfilterfunc(), kernel_filter(), m, N1, and N2.
Referenced by main().
float gaussianfilterfunc (int i, int j)
Definition at line 389 of file oldfilters.c.
References gaussfilterparam, i, j, z, and ZMAX.
void kernel_filter (short ** f, short ** fs, int N1, int N2, int m, float(* filterfunc)(int di, int dj))
Definition at line 34 of file oldfilters.c.
References error_exit, f, free(), i, j, k, m, max, min, N1, N2, and SHORT_MAGIC.
Referenced by gaussian_kernel_filter().
void kolmogorovfilter (float ** f, int N1, int N2, float ** fs, float sigma, float magicsubstitute)
Definition at line 207 of file oldfilters.c.
References alloc_fft(), f, fft_type, filter(), forward_fft(), free_fft(), i, inverse_fft(), j, kolmogorovfilterfunction(), kolmogorovsigmasquared, N1, N2, sigma, and substitute().
Referenced by main().
float kolmogorovfilterfunction (float ki, float kj)
Definition at line 411 of file oldfilters.c.
References kk, and kolmogorovsigmasquared.
void mexicanfilter (float ** f, int N1, int N2, float ** fs, float sigma1, float sigma2, float magicsubstitute)
Definition at line 308 of file oldfilters.c.
References alloc_fft(), f, fft_type, filter(), forward_fft(), free_fft(), inverse_fft(), mexicanfilterfunction(), mexicansigma1, mexicansigma2, N1, N2, and substitute().
Referenced by main().
float mexicanfilterfunction (float ki, float kj)
Definition at line 447 of file oldfilters.c.
References kk, mexicansigma1, and mexicansigma2.
void powerlawfilter (float ** f, int N1, int N2, float ** fs, float alpha, float magicsubstitute)
Definition at line 342 of file oldfilters.c.
References alloc_fft(), alpha, f, fft_type, filter(), forward_fft(), free_fft(), inverse_fft(), N1, N2, powerlawalpha, powerlawfilterfunction(), and substitute().
Referenced by main().
float powerlawfilterfunction (float ki, float kj)
Definition at line 457 of file oldfilters.c.
References kk, and powerlawalpha.
void powerspectrum (float ** f, int N1, int N2, float ** P, int ** nmodes)
2-D power spectrum analysis. f[][] is N2 * N1 array. N must be power of two. P[] and nmodes[] must be allocated by calling function with dimension N / 2.
Result is P[k] = sum f exp(ik.r) averages on rings in k-space. Array nmodes[k] contains the number of modes used in averaging which is needed for uncertainty. Definition at line 374 of file oldfilters.c.
References error_exit.
void schecterfilter (float ** f, int N1, int N2, float ** fs, float sigma1, float sigma2, float alpha, float magicsubstitute)
Definition at line 156 of file oldfilters.c.
References alloc_fft(), alpha, f, fft_type, filter(), forward_fft(), free_fft(), i, inverse_fft(), j, N1, N2, schecteralpha, schecterfilterfunction(), schectersigma1, schectersigma2, and substitute().
Referenced by main().
float schecterfilterfunction (float ki, float kj)
Definition at line 401 of file oldfilters.c.
References kk, schecteralpha, schectersigma1, and schectersigma2.
void tukey (short ** f, int N1, int N2)
Definition at line 123 of file oldfilters.c.
References f, i, j, max, min, N1, and N2.
Referenced by main().
Variable Documentation
float gaussballsigma [static]
Definition at line 19 of file oldfilters.c.
Referenced by gaussballfunction(), and gaussfilter().
float gaussfilterparam [static]
Definition at line 20 of file oldfilters.c.
Referenced by gaussian_kernel_filter(), and gaussianfilterfunc().
float gausssigma11 [static]
Definition at line 23 of file oldfilters.c.
Referenced by gaussellipsoidfunction(), and gaussfilter().
float gausssigma12 [static]
Definition at line 23 of file oldfilters.c.
Referenced by gaussellipsoidfunction(), and gaussfilter().
float gausssigma22 [static]
Definition at line 23 of file oldfilters.c.
Referenced by gaussellipsoidfunction(), and gaussfilter().
float kolmogorovsigmasquared [static]
Definition at line 22 of file oldfilters.c.
Referenced by kolmogorovfilter(), and kolmogorovfilterfunction().
float mexicansigma1 [static]
Definition at line 24 of file oldfilters.c.
Referenced by mexicanfilter(), and mexicanfilterfunction().
float mexicansigma2 [static]
Definition at line 24 of file oldfilters.c.
Referenced by mexicanfilter(), and mexicanfilterfunction().
float powerlawalpha [static]
Definition at line 25 of file oldfilters.c.
Referenced by powerlawfilter(), and powerlawfilterfunction().
float schecteralpha [static]
Definition at line 21 of file oldfilters.c.
Referenced by schecterfilter(), and schecterfilterfunction().
float schectersigma1 [static]
Definition at line 21 of file oldfilters.c.
Referenced by schecterfilter(), and schecterfilterfunction().
float schectersigma2 [static]
Definition at line 21 of file oldfilters.c.
Referenced by schecterfilter(), and schecterfilterfunction().
Author
Generated automatically by Doxygen for imcat from the source code.