.TH "oldmagic.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
oldmagic.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAGIC\fP   SHRT_MIN"
.br
.ti -1c
.RI "#define \fBNORMAL_LEVEL\fP   1000"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MAGIC   SHRT_MIN"
.PP
Definition at line 1 of file oldmagic.h.
.SS "#define NORMAL_LEVEL   1000"
.PP
Definition at line 2 of file oldmagic.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
