.TH "oldobject" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
oldobject \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.ti -1c
.RI "float \fBnu\fP"
.br
.ti -1c
.RI "float \fBfs\fP"
.br
.ti -1c
.RI "float \fBrh\fP"
.br
.ti -1c
.RI "float \fBrg\fP"
.br
.ti -1c
.RI "float \fBl\fP"
.br
.ti -1c
.RI "float \fBlg\fP"
.br
.ti -1c
.RI "float \fBe\fP [2]"
.br
.ti -1c
.RI "float \fBx\fP [2]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float \fBoldobject::e\fP[2]"
.PP
Definition at line 38 of file hcat2cat.c.
.PP
Referenced by process(), and write_object().
.SS "float \fBoldobject::fs\fP"
.PP
Definition at line 34 of file hcat2cat.c.
.PP
Referenced by process(), and write_object().
.SS "int \fBoldobject::i\fP"
.PP
Definition at line 33 of file hcat2cat.c.
.PP
Referenced by process().
.SS "int \fBoldobject::j\fP"
.PP
Definition at line 33 of file hcat2cat.c.
.PP
Referenced by process().
.SS "float \fBoldobject::l\fP"
.PP
Definition at line 36 of file hcat2cat.c.
.PP
Referenced by process().
.SS "float \fBoldobject::lg\fP"
.PP
Definition at line 37 of file hcat2cat.c.
.PP
Referenced by process(), and write_object().
.SS "float \fBoldobject::nu\fP"
.PP
Definition at line 34 of file hcat2cat.c.
.PP
Referenced by process(), and write_object().
.SS "float \fBoldobject::rg\fP"
.PP
Definition at line 35 of file hcat2cat.c.
.PP
Referenced by process(), and write_object().
.SS "float \fBoldobject::rh\fP"
.PP
Definition at line 35 of file hcat2cat.c.
.PP
Referenced by process().
.SS "float \fBoldobject::x\fP[2]"
.PP
Definition at line 39 of file hcat2cat.c.
.PP
Referenced by process(), and write_object().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
