.TH "olist" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
olist \- 
.SH SYNOPSIS
.br
.PP
\fC#include <f2c.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBflag\fP \fBoerr\fP"
.br
.ti -1c
.RI "\fBftnint\fP \fBounit\fP"
.br
.ti -1c
.RI "char * \fBofnm\fP"
.br
.ti -1c
.RI "\fBftnlen\fP \fBofnmlen\fP"
.br
.ti -1c
.RI "char * \fBosta\fP"
.br
.ti -1c
.RI "char * \fBoacc\fP"
.br
.ti -1c
.RI "char * \fBofm\fP"
.br
.ti -1c
.RI "\fBftnint\fP \fBorl\fP"
.br
.ti -1c
.RI "char * \fBoblnk\fP"
.br
.ti -1c
.RI "char * \fBofnm\fP"
.br
.ti -1c
.RI "char * \fBosta\fP"
.br
.ti -1c
.RI "char * \fBoacc\fP"
.br
.ti -1c
.RI "char * \fBofm\fP"
.br
.ti -1c
.RI "char * \fBoblnk\fP"
.br
.ti -1c
.RI "char * \fBofnm\fP"
.br
.ti -1c
.RI "char * \fBosta\fP"
.br
.ti -1c
.RI "char * \fBoacc\fP"
.br
.ti -1c
.RI "char * \fBofm\fP"
.br
.ti -1c
.RI "char * \fBoblnk\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* \fBolist::oacc\fP"
.PP
Definition at line 76 of file myf2c.h.
.SS "char* \fBolist::oacc\fP"
.PP
Definition at line 109 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBolist::oacc\fP"
.PP
Definition at line 70 of file fftpack_c/f2c.h.
.SS "char* \fBolist::oblnk\fP"
.PP
Definition at line 79 of file myf2c.h.
.SS "char* \fBolist::oblnk\fP"
.PP
Definition at line 112 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBolist::oblnk\fP"
.PP
Definition at line 73 of file fftpack_c/f2c.h.
.SS "\fBflag\fP \fBolist::oerr\fP"
.PP
Definition at line 71 of file myf2c.h.
.SS "char* \fBolist::ofm\fP"
.PP
Definition at line 77 of file myf2c.h.
.SS "char* \fBolist::ofm\fP"
.PP
Definition at line 110 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBolist::ofm\fP"
.PP
Definition at line 71 of file fftpack_c/f2c.h.
.SS "char* \fBolist::ofnm\fP"
.PP
Definition at line 73 of file myf2c.h.
.SS "char* \fBolist::ofnm\fP"
.PP
Definition at line 106 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBolist::ofnm\fP"
.PP
Definition at line 67 of file fftpack_c/f2c.h.
.SS "\fBftnlen\fP \fBolist::ofnmlen\fP"
.PP
Definition at line 74 of file myf2c.h.
.SS "\fBftnint\fP \fBolist::orl\fP"
.PP
Definition at line 78 of file myf2c.h.
.SS "char* \fBolist::osta\fP"
.PP
Definition at line 75 of file myf2c.h.
.SS "char* \fBolist::osta\fP"
.PP
Definition at line 108 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBolist::osta\fP"
.PP
Definition at line 69 of file fftpack_c/f2c.h.
.SS "\fBftnint\fP \fBolist::ounit\fP"
.PP
Definition at line 72 of file myf2c.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
