.TH "op" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
op \- 
.SH SYNOPSIS
.br
.PP
\fC#include <getop.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBopno\fP"
.br
.ti -1c
.RI "double * \fBdata\fP"
.br
.ti -1c
.RI "double \fBdata\fP"
.br
.ti -1c
.RI "void * \fBaddr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* \fBop::addr\fP"
.PP
Definition at line 17 of file imtools/ic/ic2/getop.h.
.PP
Referenced by inversedoit(), inverseinit(), lintransdoit(), lintransinit(), newop(), vectordoit(), and vectorinit().
.SS "double \fBop::data\fP"
.PP
Definition at line 16 of file imtools/ic/ic2/getop.h.
.SS "double \fBop::data\fP"
.PP
Definition at line 16 of file imtools/ic/ic2/getop.h.
.PP
Referenced by constfunc(), getop(), and main().
.SS "int \fBop::opno\fP"
.PP
Definition at line 15 of file imtools/ic/ic2/getop.h.
.PP
Referenced by getop(), imvalfunc(), main(), newop(), num0func(), num1func(), and num2func().
.SS "int \fBop::type\fP"
.PP
Definition at line 14 of file imtools/ic/ic2/getop.h.
.PP
Referenced by getop(), main(), and newop().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
