.TH "op_deref.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
op_deref.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include '../../catlib/cat.h'\fP
.br
\fC#include 'stack.h'\fP
.br
\fC#include 'error.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBderefinit\fP (\fBitem\fP *operator)"
.br
.ti -1c
.RI "void \fBderefdoit\fP (\fBitem\fP *operator)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void derefdoit (\fBitem\fP * operator)"
.PP
Definition at line 55 of file op_deref.c.
.PP
References pop().
.SS "void derefinit (\fBitem\fP * operator)"
.PP
Definition at line 10 of file op_deref.c.
.PP
References item::addr, item::dim, error_exit, item::itype, item::name, item::ndim, NUM_TYPE, pop(), and TEXT_TYPE.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
