op_dot.h
NAME
op_dot.h -
SYNOPSIS
Functions
void dotinit (item *operator)
void dotdoit (item *operator)
void vsubinit (item *operator)
void vsubdoit (item *operator)
void msubinit (item *operator)
void msubdoit (item *operator)
void vaddinit (item *operator)
void vadddoit (item *operator)
void maddinit (item *operator)
void madddoit (item *operator)
void vscaleinit (item *operator)
void vscaledoit (item *operator)
void mscaleinit (item *operator)
void mscaledoit (item *operator)
void vshiftinit (item *operator)
void vshiftdoit (item *operator)
void inverseinit (item *operator)
void inversedoit (item *operator)
Function Documentation
void dotdoit (item * operator)
Definition at line 66 of file op_dot.c.
References item::addr, item::dim, error_exit, i, j, k, item::ndim, pop(), x, and y.
void dotinit (item * operator)
Definition at line 10 of file op_dot.c.
References item::addr, item::dim, error_exit, i, item::itype, j, k, item::ndim, NUM_TYPE, pop(), x, and y.
void inversedoit (item * operator)
Definition at line 437 of file op_dot.c.
References a, op::addr, det(), i, j, op, and pop().
void inverseinit (item * operator)
Definition at line 411 of file op_dot.c.
References a, op::addr, item::addr, det(), error_exit, i, j, NUM_TYPE, op, and pop().
void madddoit (item * operator)
Definition at line 268 of file op_dot.c.
References item::addr, item::dim, i, j, pop(), x, and y.
void maddinit (item * operator)
Definition at line 239 of file op_dot.c.
References item::addr, item::dim, error_exit, i, item::itype, j, item::ndim, NUM_TYPE, pop(), x, and y.
void mscaledoit (item * operator)
Definition at line 353 of file op_dot.c.
References item::addr, item::dim, i, j, pop(), x, and y.
void mscaleinit (item * operator)
Definition at line 325 of file op_dot.c.
References item::addr, item::dim, error_exit, i, item::itype, j, item::ndim, NUM_TYPE, pop(), x, and y.
void msubdoit (item * operator)
Definition at line 182 of file op_dot.c.
References item::addr, item::dim, i, j, pop(), x, and y.
void msubinit (item * operator)
Definition at line 153 of file op_dot.c.
References item::addr, item::dim, error_exit, i, item::itype, j, item::ndim, NUM_TYPE, pop(), x, and y.
void vadddoit (item * operator)
Definition at line 223 of file op_dot.c.
References item::addr, item::dim, i, pop(), x, and y.
void vaddinit (item * operator)
Definition at line 200 of file op_dot.c.
References item::addr, item::dim, error_exit, i, item::itype, item::ndim, NUM_TYPE, pop(), x, and y.
void vscaledoit (item * operator)
Definition at line 309 of file op_dot.c.
References item::addr, item::dim, i, pop(), x, and y.
void vscaleinit (item * operator)
Definition at line 286 of file op_dot.c.
References item::addr, item::dim, error_exit, i, item::itype, item::ndim, NUM_TYPE, pop(), x, and y.
void vshiftdoit (item * operator)
Definition at line 394 of file op_dot.c.
References item::addr, item::dim, i, pop(), x, and y.
void vshiftinit (item * operator)
Definition at line 371 of file op_dot.c.
References item::addr, item::dim, error_exit, i, item::itype, item::ndim, NUM_TYPE, pop(), x, and y.
void vsubdoit (item * operator)
Definition at line 137 of file op_dot.c.
References item::addr, item::dim, i, pop(), x, and y.
void vsubinit (item * operator)
Definition at line 114 of file op_dot.c.
References item::addr, item::dim, error_exit, i, item::itype, item::ndim, NUM_TYPE, pop(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.