op_misc.c
NAME
op_misc.c -
SYNOPSIS
#include <stdio.h>
#include '../../catlib/cat.h'
#include 'stack.h'
#include 'error.h'
Functions
void ifinit (item *operator)
void ifdoit (item *operator)
void enterinit (item *operator)
void enterdoit (item *operator)
Function Documentation
void enterdoit (item * operator)
Definition at line 63 of file op_misc.c.
References item::addr, copyitemcontents(), item::next, pop(), and push().
void enterinit (item * operator)
Definition at line 52 of file op_misc.c.
References item::addr, allocitemcontents(), pop(), and push().
void ifdoit (item * operator)
Definition at line 35 of file op_misc.c.
References item::addr, copyitemcontents(), item::next, and pop().
void ifinit (item * operator)
Definition at line 10 of file op_misc.c.
References item::addr, allocitemcontents(), item::dim, error_exit, i, item::itype, item::ndim, NUM_TYPE, and pop().
Author
Generated automatically by Doxygen for imcat from the source code.