op_rand.h
NAME
op_rand.h -
SYNOPSIS
Functions
void randinit (item *operator)
void randdoit (item *operator)
void grandinit (item *operator)
void granddoit (item *operator)
Function Documentation
void granddoit (item * operator)
Definition at line 45 of file op_rand.c.
References gasdev().
void grandinit (item * operator)
Definition at line 34 of file op_rand.c.
References item::addr, gasdev(), and NUM_TYPE.
void randdoit (item * operator)
Definition at line 25 of file op_rand.c.
References drand48().
void randinit (item * operator)
Definition at line 14 of file op_rand.c.
References item::addr, drand48(), and NUM_TYPE.
Author
Generated automatically by Doxygen for imcat from the source code.