op_rand.c
NAME
op_rand.c -
SYNOPSIS
#include <stdio.h>
#include '../../catlib/cat.h'
#include 'stack.h'
#include 'error.h'
#include 'math.h'
Functions
double drand48 (void)
double gasdev (void)
void randinit (item *operator)
void randdoit (item *operator)
void grandinit (item *operator)
void granddoit (item *operator)
Function Documentation
double drand48 (void)
double gasdev (void)
Definition at line 55 of file op_rand.c.
References drand48(), and r.
Referenced by add_noise(), granddoit(), grandinit(), main(), and make_pop().
void granddoit (item * operator)
Definition at line 45 of file op_rand.c.
References gasdev().
void grandinit (item * operator)
Definition at line 34 of file op_rand.c.
References item::addr, gasdev(), and NUM_TYPE.
void randdoit (item * operator)
Definition at line 25 of file op_rand.c.
References drand48().
void randinit (item * operator)
Definition at line 14 of file op_rand.c.
References item::addr, drand48(), and NUM_TYPE.
Author
Generated automatically by Doxygen for imcat from the source code.