.TH "op_strings.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
op_strings.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstreqinit\fP (\fBitem\fP *operator)"
.br
.ti -1c
.RI "void \fBstreqdoit\fP (\fBitem\fP *operator)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void streqdoit (\fBitem\fP * operator)"
.PP
Definition at line 54 of file op_strings.c.
.PP
References item::addr, and pop().
.SS "void streqinit (\fBitem\fP * operator)"
.PP
Definition at line 12 of file op_strings.c.
.PP
References item::addr, error_exit, item::itype, NUM_TYPE, pop(), and TEXT_TYPE.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
