orbanim.c
NAME
orbanim.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'imlib/fits.h'
#include 'utils/ipbuff.h'
#include 'utils/arrays.h'
Defines
#define usage '\nNAME\n\	orbanim - generate an animation of orbit trajectories\n\\n\SYNOPSIS\n\	orbanim np nframes Nx Ny [-r rname] [-d decay_factor] [-b bgfits]\n\\n\DESCRIPTION\n\	orbabim reads from stdin a catalog containing a set of nframes\n\	sets of np particles with coordinates x[2]. It generates a 3D fits\n\	image f[nframes][N][N] showing the positions of the particles\n\	in the frames.\n\\n\	The -r option is used to modulate the brightness of points.\n\	If r is less than 1, a single pixel is painted with the value r\n\	and if r is greater than one, a disk of radius r is painted.\n\\n\	With -d option, displayed intensity decays exponentially, with\n\	successive frames reduced by a factor decay_factor.\n\\n\	With -b option we use the image 'bgfits' as a background image.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	orbanim - generate an animation of orbit trajectories\n\\n\SYNOPSIS\n\	orbanim np nframes Nx Ny [-r rname] [-d decay_factor] [-b bgfits]\n\\n\DESCRIPTION\n\	orbabim reads from stdin a catalog containing a set of nframes\n\	sets of np particles with coordinates x[2]. It generates a 3D fits\n\	image f[nframes][N][N] showing the positions of the particles\n\	in the frames.\n\\n\	The -r option is used to modulate the brightness of points.\n\	If r is less than 1, a single pixel is painted with the value r\n\	and if r is greater than one, a disk of radius r is painted.\n\\n\	With -d option, displayed intensity decays exponentially, with\n\	successive frames reduced by a factor decay_factor.\n\\n\	With -b option we use the image 'bgfits' as a background image.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 8 of file orbanim.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 33 of file orbanim.c.
References allocFloatArray(), exit(), f, fb, fits, FLOAT_PIXTYPE, i, ipf, ix, fitsheader::n, fitsheader::ndim, newfitsheader(), nframes, Nx, Ny, r, readfitsheader(), readfitsplane(), usage, writefitsheader(), writefitsplane(), writefitstail(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.