kepler.h
NAME
kepler.h -
SYNOPSIS
Data Structures
struct keplerorbit
Typedefs
typedef keplerorbit keplerorbit
Functions
void assignkeplerorbitfrombuffer (keplerorbit *orbit, double *buffer)
void fillbufferfromkeplerorbit (keplerorbit *orbit, double *buffer)
int keplertocartesian (keplerorbit *theorbit, double *r, double *v)
int cartesiantokepler (double *r, double *v, keplerorbit *theorbit)
Typedef Documentation
typedef struct keplerorbit keplerorbit
Function Documentation
void assignkeplerorbitfrombuffer (keplerorbit * orbit, double * buffer)
Definition at line 14 of file kepler_heasley/kepler.c.
References keplerorbit::a, keplerorbit::e, keplerorbit::i, keplerorbit::M, keplerorbit::Omega, and keplerorbit::omega.
Referenced by main().
int cartesiantokepler (double * r, double * v, keplerorbit * theorbit)
Definition at line 34 of file kepler_heasley/kepler.c.
References keplerorbit::a, copy(), keplerorbit::e, EMU, keplerorbit::i, ilmnts_(), K, keplerorbit::M, keplerorbit::omega, keplerorbit::Omega, r, scale(), t, theorbit, and v.
Referenced by chisquared(), and main().
void fillbufferfromkeplerorbit (keplerorbit * orbit, double * buffer)
Definition at line 24 of file kepler_heasley/kepler.c.
References keplerorbit::a, keplerorbit::e, keplerorbit::i, keplerorbit::M, keplerorbit::Omega, and keplerorbit::omega.
Referenced by main().
int keplertocartesian (keplerorbit * theorbit, double * r, double * v)
Definition at line 71 of file kepler_heasley/kepler.c.
References keplerorbit::a, copy(), keplerorbit::e, EMU, keplerorbit::i, irrdot_(), K, keplerorbit::M, keplerorbit::omega, keplerorbit::Omega, r, scale(), t, theorbit, and v.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.