.TH "kepler.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kepler.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'kepler.h'\fP
.br
\fC#include '../orbitutils/vectors.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBEMU\fP   0.0002959122370203"
.br
.ti -1c
.RI "#define \fBK\fP   0.01720209895"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBassignkeplerorbitfrombuffer\fP (\fBkeplerorbit\fP *orbit, double *buffer)"
.br
.ti -1c
.RI "void \fBfillbufferfromkeplerorbit\fP (\fBkeplerorbit\fP *orbit, double *buffer)"
.br
.ti -1c
.RI "int \fBcartesiantokepler\fP (double *\fBr\fP, double *\fBv\fP, \fBkeplerorbit\fP *\fBtheorbit\fP)"
.br
.ti -1c
.RI "int \fBkeplertocartesian\fP (\fBkeplerorbit\fP *\fBtheorbit\fP, double *\fBr\fP, double *\fBv\fP)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define EMU   0.0002959122370203"
.PP
Definition at line 11 of file orbitutils/kepler.c.
.SS "#define K   0.01720209895"
.PP
Definition at line 12 of file orbitutils/kepler.c.
.SH "Function Documentation"
.PP 
.SS "void assignkeplerorbitfrombuffer (\fBkeplerorbit\fP * orbit, double * buffer)"
.PP
Definition at line 14 of file orbitutils/kepler.c.
.PP
References keplerorbit::a, keplerorbit::e, keplerorbit::i, keplerorbit::M, keplerorbit::Omega, and keplerorbit::omega.
.PP
Referenced by main().
.SS "int cartesiantokepler (double * r, double * v, \fBkeplerorbit\fP * theorbit)"
.PP
Definition at line 34 of file orbitutils/kepler.c.
.PP
References keplerorbit::a, copy(), keplerorbit::e, EMU, keplerorbit::i, ilmnts_(), K, keplerorbit::M, keplerorbit::omega, keplerorbit::Omega, r, scale(), t, theorbit, and v.
.PP
Referenced by chisquared(), and main().
.SS "void fillbufferfromkeplerorbit (\fBkeplerorbit\fP * orbit, double * buffer)"
.PP
Definition at line 24 of file orbitutils/kepler.c.
.PP
References keplerorbit::a, keplerorbit::e, keplerorbit::i, keplerorbit::M, keplerorbit::Omega, and keplerorbit::omega.
.PP
Referenced by main().
.SS "int keplertocartesian (\fBkeplerorbit\fP * theorbit, double * r, double * v)"
.PP
Definition at line 68 of file orbitutils/kepler.c.
.PP
References keplerorbit::a, copy(), keplerorbit::e, EMU, keplerorbit::i, irrdot_(), K, keplerorbit::M, keplerorbit::omega, keplerorbit::Omega, r, scale(), t, theorbit, and v.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
