orbit.c
NAME
orbit.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
#include 'Ffunc.h'
Defines
#define USAGE 'usage : orbit\n'
#define DTINY 1.0e-20
#define FTOL 1.0e-8
#define NITERMAX 100
Functions
main (int argc, char *argv[])
Define Documentation
#define DTINY 1.0e-20
Definition at line 9 of file orbit.c.
#define FTOL 1.0e-8
Definition at line 10 of file orbit.c.
#define NITERMAX 100
Definition at line 11 of file orbit.c.
#define USAGE 'usage : orbit\n'
Definition at line 7 of file orbit.c.
Referenced by main().
Function Documentation
main (int argc, char * argv[])
Definition at line 14 of file orbit.c.
References assign(), copy(), d, dFdd(), diff(), dot(), dr, drand48(), DTINY, exit(), F(), FTOL, ge(), getperp(), i, length(), n, NITERMAX, nobs, nt, printvec(), ra, re, scale(), sigma, t, tmp, and va.
Author
Generated automatically by Doxygen for imcat from the source code.