kepler.c
NAME
kepler.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'kepler.h'
#include '../orbitutils/vectors.h'
Defines
#define EMU 0.0002959122370203
#define K 0.01720209895
Functions
void assignkeplerorbitfrombuffer (keplerorbit *orbit, double *buffer)
void fillbufferfromkeplerorbit (keplerorbit *orbit, double *buffer)
int cartesiantokepler (double *r, double *v, keplerorbit *theorbit)
int keplertocartesian (keplerorbit *theorbit, double *r, double *v)
Define Documentation
#define EMU 0.0002959122370203
Definition at line 11 of file orbitutils/kepler.c.
#define K 0.01720209895
Definition at line 12 of file orbitutils/kepler.c.
Function Documentation
void assignkeplerorbitfrombuffer (keplerorbit * orbit, double * buffer)
Definition at line 14 of file orbitutils/kepler.c.
References keplerorbit::a, keplerorbit::e, keplerorbit::i, keplerorbit::M, keplerorbit::Omega, and keplerorbit::omega.
Referenced by main().
int cartesiantokepler (double * r, double * v, keplerorbit * theorbit)
Definition at line 34 of file orbitutils/kepler.c.
References keplerorbit::a, copy(), keplerorbit::e, EMU, keplerorbit::i, ilmnts_(), K, keplerorbit::M, keplerorbit::omega, keplerorbit::Omega, r, scale(), t, theorbit, and v.
Referenced by chisquared(), and main().
void fillbufferfromkeplerorbit (keplerorbit * orbit, double * buffer)
Definition at line 24 of file orbitutils/kepler.c.
References keplerorbit::a, keplerorbit::e, keplerorbit::i, keplerorbit::M, keplerorbit::Omega, and keplerorbit::omega.
Referenced by main().
int keplertocartesian (keplerorbit * theorbit, double * r, double * v)
Definition at line 68 of file orbitutils/kepler.c.
References keplerorbit::a, copy(), keplerorbit::e, EMU, keplerorbit::i, irrdot_(), K, keplerorbit::M, keplerorbit::omega, keplerorbit::Omega, r, scale(), t, theorbit, and v.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.