orbs2obs.c
NAME
orbs2obs.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
#include 'deltam.h'
#include 'airmassmin.h'
#include 'planetdata.h'
#include 'obsdata.h'
Defines
#define usage '\nNAME\n\	orbs2obs\n\\n\SYNOPSIS\n\	orbs2obs np nf dt [-w weather.cat]\n\\n\DESCRIPTION\n\	orbs2obs reads from stdin an lc catalog containing nf\n\	frames of np+1 records containing at least heliocentric\n\	phase-space coordinates r[3] and v[3], as well as\n\	scalars risk and v_inf. The first record\n\	in each frame is understood to contain the coordinates of\n\	the observer, and orb2obs computes various observocentric\n\	properties such as the angular speed, delta-magnitude etc.\n\	Timestep dt is given in units of the Earth's dynamical time.\n\\n\	It first computes helio-centric coords of the object, relative\n\	to the center of Earth, and at the integrator timestep. It then\n\	finds the time (on hourly intervals) for which the object has\n\	the minimum air mass, subject to constraints on the sun (> 18 deg\n\	below horizon) and moon (below horizon).\n\\n\	It then computes the position of observer and object at the time\n\	of observation, and computes other properties.\n\\n\	Quantities output are:\n\	ra[3], va[3]	# position and velocity of the object\n\	re[3], ve[3]	# position of the Earth\n\	rho[3]		# position of observatory wrt Earth\n\	rlen		# Earth-object distance\n\	dotn		# angular speed\n\	mu		# cosine of angle from opposition\n\	dm[3]		# phase angle/distance magnitude shift (3 models)\n\	lambda, beta	# ecliptic coords\n\	lon, lat	# helio-ecliptic coords\n\	pnum		# particle number\n\	fnum		# frame number\n\	airmass_min	# minimum air mass (on the hour)\n\	risk		# risk factor\n\	v_inf		# collision velocity\n\	alpha, delta	# equatorial coords\n\	t_int		# time of integrator time-step (in t_dyn)\n\	t_obs		# time of observation\n\	t_local		# local time in hours\n\\n\	With -w flag we read nf records from weather.cat containing\n\	frac_clear, extinct, seeing, and these are also output.\n\\n\SEE ALSO\n\	evolveorbits\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	orbs2obs\n\\n\SYNOPSIS\n\	orbs2obs np nf dt [-w weather.cat]\n\\n\DESCRIPTION\n\	orbs2obs reads from stdin an lc catalog containing nf\n\	frames of np+1 records containing at least heliocentric\n\	phase-space coordinates r[3] and v[3], as well as\n\	scalars risk and v_inf. The first record\n\	in each frame is understood to contain the coordinates of\n\	the observer, and orb2obs computes various observocentric\n\	properties such as the angular speed, delta-magnitude etc.\n\	Timestep dt is given in units of the Earth's dynamical time.\n\\n\	It first computes helio-centric coords of the object, relative\n\	to the center of Earth, and at the integrator timestep. It then\n\	finds the time (on hourly intervals) for which the object has\n\	the minimum air mass, subject to constraints on the sun (> 18 deg\n\	below horizon) and moon (below horizon).\n\\n\	It then computes the position of observer and object at the time\n\	of observation, and computes other properties.\n\\n\	Quantities output are:\n\	ra[3], va[3]	# position and velocity of the object\n\	re[3], ve[3]	# position of the Earth\n\	rho[3]		# position of observatory wrt Earth\n\	rlen		# Earth-object distance\n\	dotn		# angular speed\n\	mu		# cosine of angle from opposition\n\	dm[3]		# phase angle/distance magnitude shift (3 models)\n\	lambda, beta	# ecliptic coords\n\	lon, lat	# helio-ecliptic coords\n\	pnum		# particle number\n\	fnum		# frame number\n\	airmass_min	# minimum air mass (on the hour)\n\	risk		# risk factor\n\	v_inf		# collision velocity\n\	alpha, delta	# equatorial coords\n\	t_int		# time of integrator time-step (in t_dyn)\n\	t_obs		# time of observation\n\	t_local		# local time in hours\n\\n\	With -w flag we read nf records from weather.cat containing\n\	frac_clear, extinct, seeing, and these are also output.\n\\n\SEE ALSO\n\	evolveorbits\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 10 of file orbs2obs.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 64 of file orbs2obs.c.
References add(), airmassmin(), alpha, assign(), ASTEROID_G_DARK, ASTEROID_G_LIGHT, ASTEROID_G_MEDIUM, AU, AXISTILTINDEG, copy(), DAYSPERYEAR, deltam(), diff(), dot(), exit(), i, ipf, LATOBSINDEG, length(), n, nf, r, R_EARTH, roty(), scale(), tmpvec, usage, and v.
Author
Generated automatically by Doxygen for imcat from the source code.