otftopsf.c
NAME
otftopsf.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'utils/error.h'
#include 'utils/args.h'
#include 'utils/ipbuff.h'
#include 'imlib/fits.h'
Defines
#define usage '\n\n\n\NAME\n\	otftopsf --- compute PSF from makeotf output\n\SYNOPSIS\n\	otftopsf dtheta thetamax [-l lambda]\n\\n\DESCRIPTION\n\	'otftopsf' reads a file containing z gk(z) from stdin and\n\	computes\n\\n\		g(theta) = 2 pi int dz z J0(2 pi theta z / lambda) gk(z) / lambda^2\n\\n\	for theta = 0 - thetamax with increment dtheta.\n\	The quantity output is g(theta) x (1 radian / 1 arcsec)^2.\n\	Command line args are given in units of arcseconds.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	otftopsf --- compute PSF from makeotf output\n\SYNOPSIS\n\	otftopsf dtheta thetamax [-l lambda]\n\\n\DESCRIPTION\n\	'otftopsf' reads a file containing z gk(z) from stdin and\n\	computes\n\\n\		g(theta) = 2 pi int dz z J0(2 pi theta z / lambda) gk(z) / lambda^2\n\\n\	for theta = 0 - thetamax with increment dtheta.\n\	The quantity output is g(theta) x (1 radian / 1 arcsec)^2.\n\	Command line args are given in units of arcseconds.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file otftopsf.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 33 of file otftopsf.c.
References arcsec, argsinit(), argsToString(), error_exit, exit(), flag, FLAG_ARG, g(), getargd(), getflag(), ipf, ix, nextargtype(), readdoublebuff(), usage, and z.
Author
Generated automatically by Doxygen for imcat from the source code.