.TH "otftopsf.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
otftopsf.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include 'utils/error.h'\fP
.br
\fC#include 'utils/args.h'\fP
.br
\fC#include 'utils/ipbuff.h'\fP
.br
\fC#include 'imlib/fits.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	otftopsf --- compute PSF from makeotf output\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	otftopsf dtheta thetamax [-\fBl\fP lambda]\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'otftopsf' reads \fBa\fP file containing \fBz\fP gk(\fBz\fP) from stdin and\\\fBn\fP\\	computes\\\fBn\fP\\\\\fBn\fP\\		g(theta) = 2 pi int dz \fBz\fP J0(2 pi theta \fBz\fP / lambda) gk(\fBz\fP) / lambda^2\\\fBn\fP\\\\\fBn\fP\\	for theta = 0 - thetamax with increment dtheta.\\\fBn\fP\\	The quantity output is g(theta) x (1 radian / 1 \fBarcsec\fP)^2.\\\fBn\fP\\	Command \fBline\fP args are given in units of arcseconds.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\n\\\fBn\fP\\\fBn\fP\\NAME\\\fBn\fP\\	otftopsf --- compute PSF from makeotf output\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	otftopsf dtheta thetamax [-\fBl\fP lambda]\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	'otftopsf' reads \fBa\fP file containing \fBz\fP gk(\fBz\fP) from stdin and\\\fBn\fP\\	computes\\\fBn\fP\\\\\fBn\fP\\		g(theta) = 2 pi int dz \fBz\fP J0(2 pi theta \fBz\fP / lambda) gk(\fBz\fP) / lambda^2\\\fBn\fP\\\\\fBn\fP\\	for theta = 0 - thetamax with increment dtheta.\\\fBn\fP\\	The quantity output is g(theta) x (1 radian / 1 \fBarcsec\fP)^2.\\\fBn\fP\\	Command \fBline\fP args are given in units of arcseconds.\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser:  kaiser@hawaii.edu\\\fBn\fP\\\\\fBn\fP\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 1 of file otftopsf.c.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
Definition at line 33 of file otftopsf.c.
.PP
References arcsec, argsinit(), argsToString(), error_exit, exit(), flag, FLAG_ARG, g(), getargd(), getflag(), ipf, ix, nextargtype(), readdoublebuff(), usage, and z.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
