overscancorr.c
NAME
overscancorr.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	overscancorr - dark subtraction using overscan region\n\\n\SYNOPSIS\n\	overscancorr [options....] \n\		-x xmin xmax	# overscan region in x (2052,2086)\n\		-y ymin ymax	# overscan region in y (0,2047)\n\\n\DESCRIPTION\n\	\'overscancorr\' corrects for the bias dc level. Reads the\n\	overscan region and fits a linear ramp model along the\n\	long (y) axis. The dc and gradient is subtracted from the\n\	image.\n\\n\AUTHOR\n\	Gordon Squires\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
Functions
int main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 33 of file overscancorr.c.
#define usage '\n\n\n\NAME\n\	overscancorr - dark subtraction using overscan region\n\\n\SYNOPSIS\n\	overscancorr [options....] \n\		-x xmin xmax	# overscan region in x (2052,2086)\n\		-y ymin ymax	# overscan region in y (0,2047)\n\\n\DESCRIPTION\n\	\'overscancorr\' corrects for the bias dc level. Reads the\n\	overscan region and fits a linear ramp model along the\n\	long (y) axis. The dc and gradient is subtracted from the\n\	image.\n\\n\AUTHOR\n\	Gordon Squires\n\\n\n\n'
Definition at line 5 of file overscancorr.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 35 of file overscancorr.c.
References add_comment(), b, b1, b2, error_exit, exit(), f, fits, i, IMAX, IMIN, j, m, MAGIC, N1, N2, read2Dfloatimage(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.