painttriangle.h
NAME
painttriangle.h -
SYNOPSIS
Functions
void painttriangle (float ***fim, int fdim, double x1, double x2, int Nx, double y1, double y2, int Ny, double **xt, double **ft, int favgmode)
Function Documentation
void painttriangle (float *** fim, int fdim, double x1, double x2, int Nx, double y1, double y2, int Ny, double ** xt, double ** ft, int favgmode)
Definition at line 15 of file painttriangle.c.
References F_INTERP, F_MEAN, F_MEDIAN, i, ix, j, m, MAX, mean(), median(), MIN, Nx, Ny, pointintriangle(), x, xmax, xmin, y, ymax, and ymin.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.