painttriangle.c
NAME
painttriangle.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'average.h'
Defines
#define MAX(a, b) ((a) > (b) ? (a) : (b))
#define MIN(a, b) ((a) < (b) ? (a) : (b))
Functions
int pointintriangle (double x, double y, double **xt)
void painttriangle (float ***fim, int fdim, double x1, double x2, int Nx, double y1, double y2, int Ny, double **xt, double **ft, int favgmode)
Define Documentation
#define MAX(a, b) ((a) > (b) ? (a) : (b))
Definition at line 10 of file painttriangle.c.
#define MIN(a, b) ((a) < (b) ? (a) : (b))
Definition at line 11 of file painttriangle.c.
Function Documentation
void painttriangle (float *** fim, int fdim, double x1, double x2, int Nx, double y1, double y2, int Ny, double ** xt, double ** ft, int favgmode)
Definition at line 15 of file painttriangle.c.
References F_INTERP, F_MEAN, F_MEDIAN, i, ix, j, m, MAX, mean(), median(), MIN, Nx, Ny, pointintriangle(), x, xmax, xmin, y, ymax, and ymin.
Referenced by main().
int pointintriangle (double x, double y, double ** xt)
Definition at line 86 of file painttriangle.c.
References c, i, j, x, and y.
Referenced by painttriangle().
Author
Generated automatically by Doxygen for imcat from the source code.