.TH "painttriangle.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
painttriangle.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpainttriangle\fP (float ***fim, int fdim, double \fBx1\fP, double \fBx2\fP, int \fBNx\fP, double y1, double y2, int \fBNy\fP, double **xt, double **ft, int favgmode)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void painttriangle (float *** fim, int fdim, double x1, double x2, int Nx, double y1, double y2, int Ny, double ** xt, double ** ft, int favgmode)"
.PP
Definition at line 15 of file painttriangle.c.
.PP
References F_INTERP, F_MEAN, F_MEDIAN, i, ix, j, m, MAX, mean(), median(), MIN, Nx, Ny, pointintriangle(), x, xmax, xmin, y, ymax, and ymin.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
