pair.c
NAME
pair.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../utils/error.h'
#include '../catlib/cat.h'
Defines
#define usage '\n\n\NAME\n\	pair - generate a catalogue containing pairs of objects from input catalogue \n\\n\SYNOPSIS\n\	pair [options...]\n\		-d	# only output N (N - 1) / 2 distinct pairs\n\\n\DESCRIPTION\n\ 'pair' reads a catalogue from stdin and writes to stdout a catalogue\n\	which has object items with the same names as in the input cat\n\	but where each object is a 2-vector formed from a pair of\n\	input objects. By default all N (N - 1) pairs are output.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\NAME\n\	pair - generate a catalogue containing pairs of objects from input catalogue \n\\n\SYNOPSIS\n\	pair [options...]\n\		-d	# only output N (N - 1) / 2 distinct pairs\n\\n\DESCRIPTION\n\ 'pair' reads a catalogue from stdin and writes to stdout a catalogue\n\	which has object items with the same names as in the input cat\n\	but where each object is a 2-vector formed from a pair of\n\	input objects. By default all N (N - 1) pairs are output.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file pair.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 32 of file pair.c.
References addargscomment(), addobjectitem(), item::addr, object::addrlist, allocitemcontents(), allocobjectcontents(), BINARY_FILE_TYPE, copyheaderinfo(), item::dim, error_exit, exit(), i, item::itype, item::name, item::ndim, newitem(), newobject(), object::next, item::next, object::nitems, cathead::objectitembase, readcathead(), readobject(), setcatopfiletype(), usage, writecathead(), and writeobject().
Author
Generated automatically by Doxygen for imcat from the source code.