.TH "pair" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pair \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBm\fP"
.br
.ti -1c
.RI "double \fBdr\fP"
.br
.ti -1c
.RI "double \fBphi\fP"
.br
.ti -1c
.RI "double \fBdm\fP"
.br
.ti -1c
.RI "\fBpair\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double \fBpair::dm\fP"
.PP
Definition at line 18 of file matchpairs.c.
.PP
Referenced by main().
.SS "double \fBpair::dr\fP"
.PP
Definition at line 18 of file matchpairs.c.
.PP
Referenced by main().
.SS "double \fBpair::m\fP"
.PP
Definition at line 18 of file matchpairs.c.
.PP
Referenced by main().
.SS "struct \fBpair\fP* \fBpair::next\fP"
.PP
Definition at line 19 of file matchpairs.c.
.PP
Referenced by main().
.SS "double \fBpair::phi\fP"
.PP
Definition at line 18 of file matchpairs.c.
.PP
Referenced by main().
.SS "double \fBpair::x\fP"
.PP
Definition at line 18 of file matchpairs.c.
.PP
Referenced by main().
.SS "double \fBpair::y\fP"
.PP
Definition at line 18 of file matchpairs.c.
.PP
Referenced by main().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
