.TH "particle" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
particle \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double * \fBx\fP"
.br
.ti -1c
.RI "double \fBf\fP"
.br
.ti -1c
.RI "\fBparticle\fP * \fBnext\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "\fBparticle\fP * \fBnext\fP"
.br
.ti -1c
.RI "char \fBline\fP [MAX_STRING_LENGTH]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double \fBparticle::f\fP"
.PP
Definition at line 24 of file findcluster.c.
.PP
Referenced by main().
.SS "char \fBparticle::line\fP[MAX_STRING_LENGTH]"
.PP
Definition at line 31 of file mergelists.c.
.PP
Referenced by main().
.SS "struct \fBparticle\fP* \fBparticle::next\fP"
.PP
Definition at line 30 of file mergelists.c.
.SS "struct \fBparticle\fP* \fBparticle::next\fP"
.PP
Definition at line 25 of file findcluster.c.
.PP
Referenced by main().
.SS "double \fBparticle::x\fP"
.PP
Definition at line 29 of file mergelists.c.
.SS "double* \fBparticle::x\fP"
.PP
Definition at line 23 of file findcluster.c.
.PP
Referenced by distance(), getcoords(), and main().
.SS "double \fBparticle::y\fP"
.PP
Definition at line 29 of file mergelists.c.
.PP
Referenced by distance(), getcoords(), and main().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
