.TH "passf5.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
passf5.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpassf5_\fP (\fBinteger\fP *ido, \fBinteger\fP *l1, \fBreal\fP *cc, \fBreal\fP *ch, \fBreal\fP *wa1, \fBreal\fP *wa2, \fBreal\fP *wa3, \fBreal\fP *wa4)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int passf5_ (\fBinteger\fP * ido, \fBinteger\fP * l1, \fBreal\fP * cc, \fBreal\fP * ch, \fBreal\fP * wa1, \fBreal\fP * wa2, \fBreal\fP * wa3, \fBreal\fP * wa4)"
.PP
Definition at line 9 of file passf5.c.
.PP
References integer, k, and real.
.PP
Referenced by cfftf1_().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
