.TH "passf.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
passf.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpassf_\fP (\fBinteger\fP *nac, \fBinteger\fP *ido, \fBinteger\fP *ip, \fBinteger\fP *l1, \fBinteger\fP *idl1, \fBreal\fP *cc, \fBreal\fP *c1, \fBreal\fP *c2, \fBreal\fP *ch, \fBreal\fP *ch2, \fBreal\fP *wa)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int passf_ (\fBinteger\fP * nac, \fBinteger\fP * ido, \fBinteger\fP * ip, \fBinteger\fP * l1, \fBinteger\fP * idl1, \fBreal\fP * cc, \fBreal\fP * c1, \fBreal\fP * c2, \fBreal\fP * ch, \fBreal\fP * ch2, \fBreal\fP * wa)"
.PP
Definition at line 9 of file passf.c.
.PP
References integer, j, k, l, nt, and real.
.PP
Referenced by cfftf1_().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
