pastecats.c
NAME
pastecats.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../utils/error.h'
#include '../catlib/cat.h'
Defines
#define usage '\n\n\NAME\n\	pastecats - combine catalogues \n\\n\SYNOPSIS\n\	pastecats a.cat b.cat ....\n\\n\DESCRIPTION\n\	'pastecats' reads a set of catalogues and combines them\n\	line by line into a single catalogue.\n\	It reads the object contents information from each of\n\	the input headers in turn, and installs each item into\n\	the output catalogue's list of object items. If no object\n\	item names are repeated then the result is essentially the same\n\	as using the unix 'paste' facility. If an item name appears\n\	more than once then the output catalogue will contain a single\n\	object item of that name, whose value comes from the last input\n\	object item of that name (though the position of the object\n\	in the list of items is determined by the first occurrence).\n\	The input catalogues will normally have the same length\n\	and be in some ordered correspondence with each other.\n\	Pastecats will return with exit value -1 if it appears\n\	that the catalogues do not have identical numbers of objects.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\NAME\n\	pastecats - combine catalogues \n\\n\SYNOPSIS\n\	pastecats a.cat b.cat ....\n\\n\DESCRIPTION\n\	'pastecats' reads a set of catalogues and combines them\n\	line by line into a single catalogue.\n\	It reads the object contents information from each of\n\	the input headers in turn, and installs each item into\n\	the output catalogue's list of object items. If no object\n\	item names are repeated then the result is essentially the same\n\	as using the unix 'paste' facility. If an item name appears\n\	more than once then the output catalogue will contain a single\n\	object item of that name, whose value comes from the last input\n\	object item of that name (though the position of the object\n\	in the list of items is determined by the first occurrence).\n\	The input catalogues will normally have the same length\n\	and be in some ordered correspondence with each other.\n\	Pastecats will return with exit value -1 if it appears\n\	that the catalogues do not have identical numbers of objects.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file pastecats.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 42 of file pastecats.c.
References addargscomment(), addobjectitem(), item::addr, allocitemcontents(), BINARY_FILE_TYPE, connectobjecttocathead(), copyheaderinfo(), copyitem(), error_exit, exit(), i, newobject(), item::next, readcathead(), readobject(), setcatipf(), setcatopfiletype(), usage, writecathead(), and writeobject().
Author
Generated automatically by Doxygen for imcat from the source code.