.TH "peak" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peak \- 
.SH SYNOPSIS
.br
.PP
\fC#include <hfindpeaks.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "float \fBrf\fP"
.br
.ti -1c
.RI "float \fBfs\fP"
.br
.ti -1c
.RI "float \fBnu\fP"
.br
.ti -1c
.RI "float \fBe1\fP"
.br
.ti -1c
.RI "float \fBe2\fP"
.br
.ti -1c
.RI "float \fBx\fP [2]"
.br
.ti -1c
.RI "\fBpeak\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float \fBpeak::e1\fP"
.PP
Definition at line 7 of file hfindpeaks.h.
.PP
Referenced by getpeaks(), and output().
.SS "float \fBpeak::e2\fP"
.PP
Definition at line 7 of file hfindpeaks.h.
.PP
Referenced by getpeaks(), and output().
.SS "float \fBpeak::fs\fP"
.PP
Definition at line 7 of file hfindpeaks.h.
.PP
Referenced by getpeaks(), and output().
.SS "int \fBpeak::i\fP"
.PP
Definition at line 6 of file hfindpeaks.h.
.PP
Referenced by getcoords(), getpeaks(), and neighbours().
.SS "int \fBpeak::j\fP"
.PP
Definition at line 6 of file hfindpeaks.h.
.PP
Referenced by getcoords(), getpeaks(), and neighbours().
.SS "int \fBpeak::level\fP"
.PP
Definition at line 6 of file hfindpeaks.h.
.PP
Referenced by getpeaks().
.SS "struct \fBpeak\fP* \fBpeak::next\fP"
.PP
Definition at line 8 of file hfindpeaks.h.
.PP
Referenced by addnewline(), disposeof(), getpeaks(), install(), main(), and process().
.SS "float \fBpeak::nu\fP"
.PP
Definition at line 7 of file hfindpeaks.h.
.PP
Referenced by disposeof(), getpeaks(), and output().
.SS "float \fBpeak::rf\fP"
.PP
Definition at line 7 of file hfindpeaks.h.
.PP
Referenced by getpeaks(), and output().
.SS "float \fBpeak::x\fP[2]"
.PP
Definition at line 7 of file hfindpeaks.h.
.PP
Referenced by getpeaks(), and output().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
