.TH "pgplottest.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgplottest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cpgplot.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <math.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBerror_exit\fP(\fBa\fP)   fprintf(stderr, (\fBa\fP)); exit(-1);"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define error_exit(\fBa\fP)   fprintf(stderr, (\fBa\fP)); exit(-1);"
.PP
Definition at line 12 of file pgplottest.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 14 of file pgplottest.c.
.PP
References error_exit, exit(), nx, and ny.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
