phasetopsf.c
NAME
phasetopsf.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/error.h'
#include 'utils/arrays.h'
#include 'utils/args.h'
#include 'imlib/fits.h'
#include 'fftlib/myfft.h'
Defines
#define usage '\n\NAME\n\	phasetopsf - computes PSF from phase screen FITS image\n\\n\SYNOPSIS\n\	phasetopsf [-N Nout] [-D D] [-p pupil]\n\\n\	Options are:\n\		-N Nout		# output only central Nout x Nout subimage (N)\n\		-D D		# mirror diameter in pixels (N)\n\		-p pupilim	# supply pupil image.\n\\n\DESCRIPTION\n\\n\	phasetopsf reads a stream of N x N phase screen samples from stdin and sends to\n\	stdout a stream of psfs.\n\\n\	With -p option we ignore any D value supplied with the -D option and we\n\	read the pupil from 'pupilim'. If this is 2N x 2N then it is treated as a\n\	real amplitude transmission function $0 <= T <= 1$. If it is 2 x 2N x 2N\n\	the first plane is consisered to be the real amplitude transmission function\n\	and the second plane is the phase in radians.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	phasetopsf - computes PSF from phase screen FITS image\n\\n\SYNOPSIS\n\	phasetopsf [-N Nout] [-D D] [-p pupil]\n\\n\	Options are:\n\		-N Nout		# output only central Nout x Nout subimage (N)\n\		-D D		# mirror diameter in pixels (N)\n\		-p pupilim	# supply pupil image.\n\\n\DESCRIPTION\n\\n\	phasetopsf reads a stream of N x N phase screen samples from stdin and sends to\n\	stdout a stream of psfs.\n\\n\	With -p option we ignore any D value supplied with the -D option and we\n\	read the pupil from 'pupilim'. If this is 2N x 2N then it is treated as a\n\	real amplitude transmission function $0 <= T <= 1$. If it is 2 x 2N x 2N\n\	the first plane is consisered to be the real amplitude transmission function\n\	and the second plane is the phase in radians.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
Definition at line 15 of file phasetopsf.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 42 of file phasetopsf.c.
References a, add_comment(), alloc_fft(), allocFloatArray(), argsinit(), b, copyfitsheader(), error_exit, exit(), fft_type, flag, forward_fft(), frame, g(), get_fft(), getargi(), getargs(), getflag(), ix, M, fitsheader::n, N, fitsheader::ndim, nframes, phi, r, readfitsheader(), readfitsplane(), usage, writefitsheader(), writefitsplane(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.