pixdist.c
NAME
pixdist.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	pixdist - compute histogram of pixel values in a FITS image\n\\n\SYNOPSIS\n\	pixdist [options...]\n\		-d fmin fmax	# histogram range\n\		-n nbins	# number of bins (40)\n\\n\DESCRIPTION\n\	\'pixdist\' generates a histogram of pixel values from a fits image.\n\	Use -d option to specify range of pixvalues (default = fmin fmax)\n\	Use -n option to specify number of bins.\n\\n\	Output is a lc-format catalogue with object items f, n\n\	giving the bin center and count\n\	and with header items overcount, undercount \n\	giving the count of pixels outside the histogram range.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	pixdist - compute histogram of pixel values in a FITS image\n\\n\SYNOPSIS\n\	pixdist [options...]\n\		-d fmin fmax	# histogram range\n\		-n nbins	# number of bins (40)\n\\n\DESCRIPTION\n\	\'pixdist\' generates a histogram of pixel values from a fits image.\n\	Use -d option to specify range of pixvalues (default = fmin fmax)\n\	Use -n option to specify number of bins.\n\\n\	Output is a lc-format catalogue with object items f, n\n\	giving the bin center and count\n\	and with header items overcount, undercount \n\	giving the count of pixels outside the histogram range.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file pixdist.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 36 of file pixdist.c.
References argsToString(), error_exit, exit(), f, fits, FLOAT_MAGIC, fmin, i, j, N1, N2, read2Dfloatimage(), usage, and val.
Author
Generated automatically by Doxygen for imcat from the source code.