.TH "pixel" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixel \- 
.SH SYNOPSIS
.br
.PP
\fC#include <apphot.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBr\fP"
.br
.ti -1c
.RI "double \fBf\fP"
.br
.ti -1c
.RI "double \fBfcum\fP"
.br
.ti -1c
.RI "double \fBnu\fP"
.br
.ti -1c
.RI "double \fBnucum\fP"
.br
.ti -1c
.RI "double \fBnus\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBfixed\fP"
.br
.ti -1c
.RI "float \fBf\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float \fBpixel::f\fP"
.PP
Definition at line 13 of file fixedges.c.
.SS "double \fBpixel::f\fP"
.PP
Definition at line 7 of file apphot.h.
.SS "double \fBpixel::fcum\fP"
.PP
Definition at line 8 of file apphot.h.
.SS "int \fBpixel::fixed\fP"
.PP
Definition at line 12 of file fixedges.c.
.SS "double \fBpixel::nu\fP"
.PP
Definition at line 9 of file apphot.h.
.SS "double \fBpixel::nucum\fP"
.PP
Definition at line 10 of file apphot.h.
.SS "double \fBpixel::nus\fP"
.PP
Definition at line 11 of file apphot.h.
.SS "double \fBpixel::r\fP"
.PP
Definition at line 6 of file apphot.h.
.PP
Referenced by pixcmp().
.SS "int \fBpixel::x\fP"
.PP
Definition at line 12 of file fixedges.c.
.SS "int \fBpixel::y\fP"
.PP
Definition at line 12 of file fixedges.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
