planetephem.c
NAME
planetephem.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'jpleph.h'
Defines
#define usage '\nNAME\n\	planetephem - compute position of a planet at a given time\n\\n\SYNOPSIS\n\	planetephem timetype time target center\n\\n\DESCRIPTION\n\	planetephem is a wrapper for the JPL subroutine PLEPH.\n\\n\	timetype should be either 'JD' (Julian date) or 'MJD' (mean\n\	Julian date) or 'Y2K' (time in days relative to start of Y2K).\n\\n\	The numbering convention for 'target' and 'center' is:\n\		1 = mercury\n\		2 = venus\n\		3 = earth\n\		4 = mars\n\		5 = jupiter\n\		6 = saturn\n\		7 = uranus\n\		8 = neptune\n\		9 = pluto\n\		10 = moon\n\		11 = sun\n\		12 = solar-system barycenter\n\		13 = earth-moon barycenter\n\\n\	If nutations are wanted, set target = 14, center = 0\n\	For librations, set target = 15, center = 0.\n\\n\	Output are the cartesian position (in AU) and velocities\n\	in (AU per (yr / 2 PI)) in the ecliptic coordinate frame.\n\\n\	Planetephem expects to find the path to the binary\n\	ephemeris file in the environment variable JPL_EPHEMERIDES\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
#define K 0.01720209895
#define MJD_Y2K 51544.0
#define JD0 2400000.5
#define OBLIQUITYINDEG 23.43929111
Functions
main (int argc, char *argv[])
Define Documentation
#define JD0 2400000.5
Definition at line 57 of file planetephem.c.
Referenced by main().
#define K 0.01720209895
Definition at line 52 of file planetephem.c.
#define MJD_Y2K 51544.0
Definition at line 55 of file planetephem.c.
Referenced by main().
#define OBLIQUITYINDEG 23.43929111
Definition at line 60 of file planetephem.c.
Referenced by main().
#define usage '\nNAME\n\	planetephem - compute position of a planet at a given time\n\\n\SYNOPSIS\n\	planetephem timetype time target center\n\\n\DESCRIPTION\n\	planetephem is a wrapper for the JPL subroutine PLEPH.\n\\n\	timetype should be either 'JD' (Julian date) or 'MJD' (mean\n\	Julian date) or 'Y2K' (time in days relative to start of Y2K).\n\\n\	The numbering convention for 'target' and 'center' is:\n\		1 = mercury\n\		2 = venus\n\		3 = earth\n\		4 = mars\n\		5 = jupiter\n\		6 = saturn\n\		7 = uranus\n\		8 = neptune\n\		9 = pluto\n\		10 = moon\n\		11 = sun\n\		12 = solar-system barycenter\n\		13 = earth-moon barycenter\n\\n\	If nutations are wanted, set target = 14, center = 0\n\	For librations, set target = 15, center = 0.\n\\n\	Output are the cartesian position (in AU) and velocities\n\	in (AU per (yr / 2 PI)) in the ecliptic coordinate frame.\n\\n\	Planetephem expects to find the path to the binary\n\	ephemeris file in the environment variable JPL_EPHEMERIDES\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 12 of file planetephem.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 62 of file planetephem.c.
References c, exit(), i, JD0, jpl_init_ephemeris(), jpl_pleph(), K, MJD_Y2K, OBLIQUITYINDEG, r, usage, v, y, and z.
Author
Generated automatically by Doxygen for imcat from the source code.