.TH "planetdata.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
planetdata.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAU\fP   1.496e13"
.br
.ti -1c
.RI "#define \fBG_NEWTON\fP   6.67259\fBe\fP-8"
.br
.ti -1c
.RI "#define \fBM_EARTH\fP   5.976e27"
.br
.ti -1c
.RI "#define \fBR_EARTH\fP   6.378e8"
.br
.ti -1c
.RI "#define \fBAXISTILTINDEG\fP   23.45"
.br
.ti -1c
.RI "#define \fBDAYSPERYEAR\fP   365.25"
.br
.ti -1c
.RI "#define \fBM_SUN\fP   1.99e33"
.br
.ti -1c
.RI "#define \fBM_JUPITER\fP   1.899e30"
.br
.ti -1c
.RI "#define \fBA_JUPITER\fP   5.204529"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define A_JUPITER   5.204529"
.PP
Definition at line 16 of file planetdata.h.
.PP
Referenced by addjupitergravity(), and jupiteron().
.SS "#define AU   1.496e13"
.PP
Definition at line 6 of file planetdata.h.
.PP
Referenced by main().
.SS "#define AXISTILTINDEG   23.45"
.PP
Definition at line 11 of file planetdata.h.
.PP
Referenced by airmassmin(), and main().
.SS "#define DAYSPERYEAR   365.25"
.PP
Definition at line 12 of file planetdata.h.
.PP
Referenced by main().
.SS "#define G_NEWTON   6.67259\fBe\fP-8"
.PP
Definition at line 7 of file planetdata.h.
.PP
Referenced by main().
.SS "#define M_EARTH   5.976e27"
.PP
Definition at line 8 of file planetdata.h.
.PP
Referenced by main().
.SS "#define M_JUPITER   1.899e30"
.PP
Definition at line 15 of file planetdata.h.
.PP
Referenced by jupiteron().
.SS "#define M_SUN   1.99e33"
.PP
Definition at line 14 of file planetdata.h.
.PP
Referenced by jupiteron(), and main().
.SS "#define R_EARTH   6.378e8"
.PP
Definition at line 9 of file planetdata.h.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
