platepos.c
NAME
platepos.c -
SYNOPSIS
#include <math.h>
#include <string.h>
#include <stdio.h>
#include 'wcs.h'
Functions
int platepos (double xpix, double ypix, struct WorldCoor *wcs, double *xpos, double *ypos)
int platepix (double xpos, double ypos, struct WorldCoor *wcs, double *xpix, double *ypix)
Function Documentation
int platepix (double xpos, double ypos, struct WorldCoor * wcs, double	* xpix, double	* ypix)
Definition at line 112 of file platepos.c.
References dx, dy, f, g(), gx, i, wcs, x, and y.
Referenced by wcs2pix().
int platepos (double xpix, double ypix, struct WorldCoor * wcs, double	* xpos, double	* ypos)
Definition at line 21 of file platepos.c.
References ra, wcs, x, and y.
Referenced by pix2wcs().
Author
Generated automatically by Doxygen for imcat from the source code.