plotcatmain.c
NAME
plotcatmain.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <unistd.h>
#include 'cpgplot.h'
#include 'cpgellipses.h'
#include 'getrange.h'
#include 'rectangles.h'
#include 'lcfilter.h'
#include '../../utils/error.h'
#include '../../imlib/fits.h'
#include '../../utils/colormaps.h'
#include 'labels.h'
Defines
#define MARGIN 0.03
#define RFRACDEFAULT 0.01
#define EMAX 0.9
#define NVERT 8
#define MAX_MODES 20
#define SYMBOL_TYPE 0
#define POLY_TYPE 1
#define XY_MODE 0
#define XY_SHADE_MODE 1
#define XY_SYMBOL_MODE 2
#define XY_SYMBOL_SHADE_MODE 3
#define XY_R_MODE 4
#define XY_E_MODE 5
#define XY_R_SHADE_MODE 6
#define XY_E_SHADE_MODE 7
#define XY_R_E_MODE 8
#define XY_R_E_SHADE_MODE 9
#define XY_HIST_MODE 10
#define XY_ERRY_MODE 11
#define XY_SYMBOL_ERRY_MODE 12
Functions
int getcifromshade (float shade)
int main (int argc, char *argv[])
Variables
int cilo
int cihi
Define Documentation
#define EMAX 0.9
Definition at line 25 of file plotcatmain.c.
Referenced by main().
#define MARGIN 0.03
Definition at line 23 of file plotcatmain.c.
#define MAX_MODES 20
Definition at line 28 of file plotcatmain.c.
Referenced by main().
#define NVERT 8
Definition at line 26 of file plotcatmain.c.
Referenced by main().
#define POLY_TYPE 1
Definition at line 31 of file plotcatmain.c.
Referenced by main().
#define RFRACDEFAULT 0.01
Definition at line 24 of file plotcatmain.c.
Referenced by main().
#define SYMBOL_TYPE 0
Definition at line 30 of file plotcatmain.c.
Referenced by main().
#define XY_E_MODE 5
Definition at line 38 of file plotcatmain.c.
Referenced by main().
#define XY_E_SHADE_MODE 7
Definition at line 40 of file plotcatmain.c.
Referenced by main().
#define XY_ERRY_MODE 11
Definition at line 44 of file plotcatmain.c.
Referenced by main().
#define XY_HIST_MODE 10
Definition at line 43 of file plotcatmain.c.
Referenced by main().
#define XY_MODE 0
Definition at line 33 of file plotcatmain.c.
Referenced by main().
#define XY_R_E_MODE 8
Definition at line 41 of file plotcatmain.c.
Referenced by main().
#define XY_R_E_SHADE_MODE 9
Definition at line 42 of file plotcatmain.c.
Referenced by main().
#define XY_R_MODE 4
Definition at line 37 of file plotcatmain.c.
Referenced by main().
#define XY_R_SHADE_MODE 6
Definition at line 39 of file plotcatmain.c.
Referenced by main().
#define XY_SHADE_MODE 1
Definition at line 34 of file plotcatmain.c.
Referenced by main().
#define XY_SYMBOL_ERRY_MODE 12
Definition at line 45 of file plotcatmain.c.
Referenced by main().
#define XY_SYMBOL_MODE 2
Definition at line 35 of file plotcatmain.c.
Referenced by main().
#define XY_SYMBOL_SHADE_MODE 3
Definition at line 36 of file plotcatmain.c.
Referenced by main().
Function Documentation
int getcifromshade (float shade)
Definition at line 960 of file plotcatmain.c.
References cihi, cilo, and shade.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 51 of file plotcatmain.c.
References a, addfiltercondition(), b, cihi, cilo, cpgellipses(), deactivate(), dofilter(), e1, EMAX, error_exit, exit(), fits, FLOAT_MAGIC, fmin, getcifromshade(), getcolormap(), getrange(), getrect(), installrect(), ix, MASK_MODE, MAX_MODES, N1, N2, label::next, NOEDIT_MODE, npts, NVERT, phi, POLY_TYPE, r, read2Dfloatimage(), REJECT_MODE, RFRACDEFAULT, SELECT_MODE, setposfirst(), shade, startfilter(), SYMBOL_TYPE, label::text, type, label::x, x, xmax, xmin, XY_E_MODE, XY_E_SHADE_MODE, XY_ERRY_MODE, XY_HIST_MODE, XY_MODE, XY_R_E_MODE, XY_R_E_SHADE_MODE, XY_R_MODE, XY_R_SHADE_MODE, XY_SHADE_MODE, XY_SYMBOL_ERRY_MODE, XY_SYMBOL_MODE, XY_SYMBOL_SHADE_MODE, label::y, y, ymax, and ymin.
Variable Documentation
int cihi [static]
Definition at line 48 of file plotcatmain.c.
Referenced by getcifromshade(), and main().
int cilo [static]
Definition at line 48 of file plotcatmain.c.
Referenced by getcifromshade(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.