poidev.c
NAME
poidev.c -
SYNOPSIS
#include <math.h>
Defines
#define PI 3.141592654
Functions
float poidev (float xm, long *idum)
Define Documentation
#define PI 3.141592654
Definition at line 2 of file poidev.c.
Function Documentation
float poidev (float xm, long * idum)
Definition at line 4 of file poidev.c.
References g(), gammln(), PI, ran1(), t, xx, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.