.TH "poidev.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
poidev.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3.141592654"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBpoidev\fP (float xm, long *idum)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define PI   3.141592654"
.PP
Definition at line 2 of file poidev.c.
.SH "Function Documentation"
.PP 
.SS "float poidev (float xm, long * idum)"
.PP
Definition at line 4 of file poidev.c.
.PP
References g(), gammln(), PI, ran1(), t, xx, and y.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
