powell.c
NAME
powell.c -
SYNOPSIS
#include <math.h>
#include 'nrutil.h'
Defines
#define NRANSI
#define ITMAX 200
Functions
void powell (float p[], float **xi, int n, float ftol, int *iter, float *fret, float(*func)(float[]))
Define Documentation
#define ITMAX 200
Definition at line 4 of file powell.c.
#define NRANSI
Definition at line 2 of file powell.c.
Function Documentation
void powell (float p[], float ** xi, int n, float ftol, int * iter, float * fret, float(* func)(float[]))
Definition at line 6 of file powell.c.
References free_vector(), func(), i, ITMAX, j, linmin(), n, nrerror(), SQR, t, and vector().
Referenced by findmin(), fitall(), gaussfit(), gaussfitn(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.