powell.h
NAME
powell.h -
SYNOPSIS
Functions
void powell (float p[], float **xi, int n, float ftol, int *iter, float *fret, float(*func)(float[]))
Function Documentation
void powell (float p[], float ** xi, int n, float ftol, int * iter, float * fret, float(* func)(float[]))
Definition at line 6 of file powell.c.
References free_vector(), func(), i, ITMAX, j, linmin(), n, nrerror(), SQR, t, and vector().
Referenced by findmin(), fitall(), gaussfit(), gaussfitn(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.