.TH "printimage.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
printimage.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintimage\fP (int Ncolors, int \fBN1\fP, int \fBN2\fP, unsigned char ***\fBc\fP, int width, int height)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void printimage (int Ncolors, int N1, int N2, unsigned char *** c, int width, int height)"
.PP
Definition at line 10 of file printimage.c.
.PP
References c, color, error_exit, get_print_opf(), i, j, N1, N2, ps(), psstring, and psstringlen.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
