print_image.c
NAME
print_image.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	print_image -- prints a square image on the LaserWriter\n\\n\SYNOPSIS\n\	print_image	fitsfile [option...] \n\		-f fmin fmax	# max and min f values\n\		-n		# don't print header info\n\		-b		# draw a box oround image\n\		-c comment	# use (quoted if multiword) comment as label\n\		-p pw ph mx my	# set page width, height, margins (612, 792, 50, 50)\n\		-P		# include setpagedevice\n\		-g		# pipe output through gs to compress\n\\n\DESCRIPTION\n\	\'print_image\' reads a fits file and sends\n\	postscript file to stdout\n\\n\	The range of values may be specified with the -f option,\n\	otherwise the range is 0 (=white) to 255 (=black).\n\\n\	Supports 3-color images.\n\\n\	If fitsfile = '-' then we read from stdin.\n\\n\	Default page size info is 612x792 = (8.5x11)in with 50 pt margin\n\	so the actual inked area is 512x692. Use -p option to change this.\n\\n\	The -P option is provided to include a 'setpagedevice' command giving\n\	the physical total page size. This is used for big prints on\n\	the designjet, but seems to be problematic with latex epsf handling.\n\	Do not use this with -g option.\n\\n\	With the -g option we pipe the output through\n\		gs -q -sDEVICE=pswrite -sOutputFile=- -dNOPAUSE -\n\	which will result in a much smaller output file.\n\	Do not use this with -P option.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
void print_im (int N1, int N2, int Ncolors, double(*gray)(), char *caption)
void setpagesize (int pagewidth, int pageheight, int pagemargin)
void print_caption (char *caption)
void psDrawChar (char aChar)
void ps (char *string)
void set_print_opf (FILE *thefile)
main (int argc, char *argv[])
Variables
char * psstring
FILE * opf
Define Documentation
#define usage '\n\n\n\NAME\n\	print_image -- prints a square image on the LaserWriter\n\\n\SYNOPSIS\n\	print_image	fitsfile [option...] \n\		-f fmin fmax	# max and min f values\n\		-n		# don't print header info\n\		-b		# draw a box oround image\n\		-c comment	# use (quoted if multiword) comment as label\n\		-p pw ph mx my	# set page width, height, margins (612, 792, 50, 50)\n\		-P		# include setpagedevice\n\		-g		# pipe output through gs to compress\n\\n\DESCRIPTION\n\	\'print_image\' reads a fits file and sends\n\	postscript file to stdout\n\\n\	The range of values may be specified with the -f option,\n\	otherwise the range is 0 (=white) to 255 (=black).\n\\n\	Supports 3-color images.\n\\n\	If fitsfile = '-' then we read from stdin.\n\\n\	Default page size info is 612x792 = (8.5x11)in with 50 pt margin\n\	so the actual inked area is 512x692. Use -p option to change this.\n\\n\	The -P option is provided to include a 'setpagedevice' command giving\n\	the physical total page size. This is used for big prints on\n\	the designjet, but seems to be problematic with latex epsf handling.\n\	Do not use this with -g option.\n\\n\	With the -g option we pipe the output through\n\		gs -q -sDEVICE=pswrite -sOutputFile=- -dNOPAUSE -\n\	which will result in a much smaller output file.\n\	Do not use this with -P option.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file print_image.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 64 of file print_image.c.
References argsToString(), ascii, c, caption, color, error_exit, exit(), f, fits, FLOAT_MAGIC, fmin, i, j, fitsheader::n, N, N1, N2, fitsheader::ndim, opf, print_caption(), ps(), psstring, psstringlen, readfitsheader(), readfitsline(), and usage.
void print_caption (char * caption)
Definition at line 36 of file psutils.c.
void print_im (int N1, int N2, int Ncolors, double(* gray)(), char * caption)
Definition at line 299 of file print_image.c.
References color, gray(), i, j, N1, N2, ps(), and psstring.
void ps (char * string)
Definition at line 12 of file psutils.c.
void psDrawChar (char aChar)
Definition at line 18 of file psutils.c.
void set_print_opf (FILE * thefile)
Definition at line 57 of file psutils.c.
void setpagesize (int pagewidth, int pageheight, int pagemargin)
Variable Documentation
FILE* opf [static]
Definition at line 54 of file print_image.c.
Referenced by main().
char* psstring
Definition at line 53 of file print_image.c.
Author
Generated automatically by Doxygen for imcat from the source code.