printimage.h
NAME
printimage.h -
SYNOPSIS
Functions
void printimage (int Ncolors, int N1, int N2, unsigned char ***c, int width, int height)
Function Documentation
void printimage (int Ncolors, int N1, int N2, unsigned char *** c, int width, int height)
Definition at line 10 of file printimage.c.
References c, color, error_exit, get_print_opf(), i, j, N1, N2, ps(), psstring, and psstringlen.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.