print_stuff.h
NAME
print_stuff.h -
SYNOPSIS
Functions
void print_im (int N1, int N2, int Ncolors, double(*gray)(), char *caption)
void setpagesize (int pagewidth, int pageheight, int pagemargin, int dosetpagedevice)
void print_caption (char *caption)
void psDrawChar (char aChar)
void ps (char *string)
void set_print_opf (FILE *thefile)
Function Documentation
void print_caption (char * caption)
Definition at line 36 of file psutils.c.
References c, caption, h, len, ps(), psDrawChar(), psstring, size, and v.
Referenced by main(), and print_im().
void print_im (int N1, int N2, int Ncolors, double(* gray)(), char * caption)
Definition at line 47 of file print_stuff.c.
References caption, color, error_exit, gdosetpagedevice, gray(), i, j, N1, N2, page_height, page_margin, page_width, print_caption(), ps(), psstring, and psstringlen.
Referenced by printall(), and printselection().
void ps (char * string)
Definition at line 12 of file psutils.c.
References opf.
Referenced by main(), print_caption(), print_im(), printimage(), and psDrawChar().
void psDrawChar (char aChar)
Definition at line 18 of file psutils.c.
References ps(), and psstring.
Referenced by print_caption().
void set_print_opf (FILE * thefile)
Definition at line 57 of file psutils.c.
References opf.
Referenced by main(), printall(), and printselection().
void setpagesize (int pagewidth, int pageheight, int pagemargin, int dosetpagedevice)
Definition at line 209 of file print_stuff.c.
References gdosetpagedevice, page_height, page_margin, and page_width.
Author
Generated automatically by Doxygen for imcat from the source code.