print_stuff_nk.c
NAME
print_stuff_nk.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <signal.h>
#include 'print_stuff.h'
#include '../../utils/error.h'
#include '../../imlib/fits.h'
Defines
#define PAGE_WIDTH 512
#define PAGE_HEIGHT 692
#define PAGE_MARGIN 50
#define EPSF_A 50
#define EPSF_B 50
Functions
void print_im (int N1, int N2, int Ncolors, double(*gray)(), char *caption)
void ps (char *string)
void psDrawChar (char aChar)
void print_caption (char *caption)
void set_print_opf (FILE *thefile)
void setpagesize (int pagewidth, int pageheight, int pagemargin, int dosetpagedevice)
Variables
int page_width = PAGE_WIDTH
int page_height = PAGE_HEIGHT
int page_margin = PAGE_MARGIN
int gdosetpagedevice = 0
int psstringlen
char * psstring
FILE * opf = stdout
Define Documentation
#define EPSF_A 50
Definition at line 31 of file print_stuff_nk.c.
#define EPSF_B 50
Definition at line 32 of file print_stuff_nk.c.
#define PAGE_HEIGHT 692
Definition at line 29 of file print_stuff_nk.c.
#define PAGE_MARGIN 50
Definition at line 30 of file print_stuff_nk.c.
#define PAGE_WIDTH 512
print_stuff.c functions for printing images as postscript
public use: int print_im(int N1, int N2, int Ncolors, double (*gray)(), char *caption);
private use: void print_caption(char *caption) void psDrawChar(char aChar) void ps(char *string)
print_im() is passed a function which returns gray(i,j,col) on range 0-1.0 where col = 0,1,2 for r,g,b Definition at line 28 of file print_stuff_nk.c.
Function Documentation
void print_caption (char * caption)
Definition at line 176 of file print_stuff_nk.c.
References c, caption, h, len, ps(), psDrawChar(), psstring, size, and v.
Referenced by main(), and print_im().
void print_im (int N1, int N2, int Ncolors, double(* gray)(), char * caption)
Definition at line 46 of file print_stuff_nk.c.
References caption, color, error_exit, gdosetpagedevice, gray(), i, j, N1, N2, page_height, page_margin, page_width, print_caption(), ps(), psstring, and psstringlen.
Referenced by printall(), and printselection().
void ps (char * string)
Definition at line 152 of file print_stuff_nk.c.
References opf.
Referenced by main(), print_caption(), print_im(), printimage(), and psDrawChar().
void psDrawChar (char aChar)
Definition at line 158 of file print_stuff_nk.c.
References ps(), and psstring.
Referenced by print_caption().
void set_print_opf (FILE * thefile)
Definition at line 198 of file print_stuff_nk.c.
References opf.
Referenced by main(), printall(), and printselection().
void setpagesize (int pagewidth, int pageheight, int pagemargin, int dosetpagedevice)
Definition at line 205 of file print_stuff_nk.c.
References gdosetpagedevice, page_height, page_margin, and page_width.
Variable Documentation
int gdosetpagedevice = 0 [static]
Definition at line 38 of file print_stuff_nk.c.
Referenced by print_im(), and setpagesize().
FILE* opf = stdout [static]
Definition at line 44 of file print_stuff_nk.c.
Referenced by ps(), and set_print_opf().
int page_height = PAGE_HEIGHT [static]
Definition at line 36 of file print_stuff_nk.c.
Referenced by print_im(), and setpagesize().
int page_margin = PAGE_MARGIN [static]
Definition at line 37 of file print_stuff_nk.c.
Referenced by print_im(), and setpagesize().
int page_width = PAGE_WIDTH [static]
Definition at line 35 of file print_stuff_nk.c.
Referenced by print_im(), and setpagesize().
char* psstring
Definition at line 42 of file print_stuff_nk.c.
int psstringlen
Definition at line 41 of file print_stuff_nk.c.
Author
Generated automatically by Doxygen for imcat from the source code.