print_stuff_mac.c
NAME
print_stuff_mac.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <signal.h>
#include 'print_stuff.h'
#include 'error.h'
#include 'fits.h'
Defines
#define PAGE_WIDTH 512
#define PAGE_HEIGHT 700
Functions
void ps (char *string)
void psDrawChar (char aChar)
void print_caption (char *caption)
void print_im (int N, int fmin, int fmax, char *caption)
Variables
int psstringlen
char * psstring
FILE * lprpipe
Define Documentation
#define PAGE_HEIGHT 700
Definition at line 25 of file print_stuff_mac.c.
Referenced by print_im().
#define PAGE_WIDTH 512
functions for printing images on the laser_writer int print_im(short **f, int N); void ps(char *string); void PrPicDoc(PicHandle thePic, THPrint hPrint);
print_im() requires an 8-bit image (i.e. f-values of 0-256) Definition at line 24 of file print_stuff_mac.c.
Referenced by print_im().
Function Documentation
void print_caption (char * caption)
Definition at line 160 of file print_stuff_mac.c.
References c, caption, h, len, ps(), psDrawChar(), psstring, size, and v.
void print_im (int N, int fmin, int fmax, char * caption)
Definition at line 52 of file print_stuff_mac.c.
References ascii, caption, error_exit, f, fmin, free(), i, j, N, PAGE_HEIGHT, PAGE_WIDTH, print_caption(), ps(), psstring, psstringlen, and read_fits_line().
void ps (char * string)
Definition at line 124 of file print_stuff_mac.c.
References len.
Referenced by eps_init().
void psDrawChar (char aChar)
Definition at line 142 of file print_stuff_mac.c.
References ps(), and psstring.
Variable Documentation
FILE* lprpipe
Definition at line 49 of file print_stuff_mac.c.
char* psstring
Definition at line 28 of file print_stuff_mac.c.
Referenced by main(), print_caption(), print_im(), printimage(), and psDrawChar().
int psstringlen
Definition at line 27 of file print_stuff_mac.c.
Referenced by main(), print_im(), and printimage().
Author
Generated automatically by Doxygen for imcat from the source code.