projectfits.c
NAME
projectfits.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	projectfits - average over rows, cols etc of a FITS file\n\\n\SYNOPSIS\n\	projectfits [-u] [-d M] d\n\\n\DESCRIPTION\n\	\'projectfits\' reads a FITS image of arbitrary dimensionality D from\n\	stdin and outputs a D-1 dimensional image to stdout which\n\	contains the average along the d'th dimension, where\n\	d=0 is the fastest direction (row average), d=1 is the next\n\	fastest direction (column average) etc.\n\\n\	Options:\n\		-u		# print this message\n\		-d M		# deproject \n\\n\	With the -d option we stretch out a N-dimensional image along\n\	the d'th direction to make a N+1 dimensional image. For example,\n\	with a 3-D input image fin[Nz][Ny][Nx], the result of\n\		projectfits -d 10 2\n\	is to make a 4-dimensional image fout[Nz][10][Ny][Nx] with\n\		fout[z][t][y][x] = fin[z][y][x].\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int project (int level)
int deproject (int level)
int main (int argc, char *argv[])
Variables
float * fout
float * fin
int * fsizein
int * fsizeout
int * xin
int * xout
int d
int deproj
int Ndeproj
int nlines
fitsheader * fitsin
fitsheader * fitsout
Define Documentation
#define usage '\n\n\n\NAME\n\	projectfits - average over rows, cols etc of a FITS file\n\\n\SYNOPSIS\n\	projectfits [-u] [-d M] d\n\\n\DESCRIPTION\n\	\'projectfits\' reads a FITS image of arbitrary dimensionality D from\n\	stdin and outputs a D-1 dimensional image to stdout which\n\	contains the average along the d'th dimension, where\n\	d=0 is the fastest direction (row average), d=1 is the next\n\	fastest direction (column average) etc.\n\\n\	Options:\n\		-u		# print this message\n\		-d M		# deproject \n\\n\	With the -d option we stretch out a N-dimensional image along\n\	the d'th direction to make a N+1 dimensional image. For example,\n\	with a 3-D input image fin[Nz][Ny][Nx], the result of\n\		projectfits -d 10 2\n\	is to make a 4-dimensional image fout[Nz][10][Ny][Nx] with\n\		fout[z][t][y][x] = fin[z][y][x].\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file projectfits.c.
Function Documentation
int deproject (int level)
Definition at line 204 of file projectfits.c.
References d, fin, fitsin, fitsout, fout, fsizein, fsizeout, i, fitsheader::n, fitsheader::ndim, xin, and xout.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 49 of file projectfits.c.
References add_comment(), argsinit(), copyfitsheader(), d, deproj, deproject(), error_exit, exit(), fin, fitsin, fitsout, flag, FLAG_ARG, fout, fsizein, fsizeout, getargi(), getflag(), i, fitsheader::n, Ndeproj, fitsheader::ndim, nextargtype(), nlines, project(), readfitsheader(), readfitsline(), usage, writefitsheader(), writefitsline(), writefitstail(), xin, and xout.
int project (int level)
Definition at line 168 of file projectfits.c.
References d, ff, fin, fitsin, fitsout, FLOAT_MAGIC, fout, fsizein, fsizeout, i, fitsheader::n, fitsheader::ndim, xin, and xout.
Referenced by main().
Variable Documentation
int d [static]
Definition at line 43 of file projectfits.c.
int deproj [static]
Definition at line 43 of file projectfits.c.
Referenced by main().
float * fin [static]
Definition at line 42 of file projectfits.c.
Referenced by deproject(), main(), and project().
fitsheader* fitsin [static]
Definition at line 44 of file projectfits.c.
Referenced by deproject(), main(), and project().
fitsheader * fitsout [static]
Definition at line 44 of file projectfits.c.
Referenced by deproject(), main(), and project().
float* fout [static]
Definition at line 42 of file projectfits.c.
Referenced by deproject(), main(), and project().
int* fsizein [static]
Definition at line 43 of file projectfits.c.
Referenced by deproject(), main(), and project().
int * fsizeout [static]
Definition at line 43 of file projectfits.c.
Referenced by deproject(), main(), and project().
int Ndeproj [static]
Definition at line 43 of file projectfits.c.
Referenced by main().
int nlines [static]
Definition at line 43 of file projectfits.c.
Referenced by main().
int * xin [static]
Definition at line 43 of file projectfits.c.
Referenced by deproject(), main(), and project().
int * xout [static]
Definition at line 43 of file projectfits.c.
Referenced by deproject(), main(), and project().
Author
Generated automatically by Doxygen for imcat from the source code.