.TH "PSCmap" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSCmap \- 
.SH SYNOPSIS
.br
.PP
\fC#include <eps.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBIsDefault\fP"
.br
.ti -1c
.RI "int \fBncolors\fP"
.br
.ti -1c
.RI "int \fBmin\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.ti -1c
.RI "unsigned char \fBr\fP [256]"
.br
.ti -1c
.RI "unsigned char \fBg\fP [256]"
.br
.ti -1c
.RI "unsigned char \fBb\fP [256]"
.br
.ti -1c
.RI "char * \fBcmap_name\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBPSCmap::b\fP[256]"
.PP
Definition at line 65 of file eps.h.
.SS "char* \fBPSCmap::cmap_name\fP"
.PP
Definition at line 66 of file eps.h.
.SS "unsigned char \fBPSCmap::g\fP[256]"
.PP
Definition at line 64 of file eps.h.
.SS "int \fBPSCmap::IsDefault\fP"
.PP
Definition at line 60 of file eps.h.
.SS "int \fBPSCmap::max\fP"
.PP
Definition at line 62 of file eps.h.
.SS "int \fBPSCmap::min\fP"
.PP
Definition at line 62 of file eps.h.
.SS "int \fBPSCmap::ncolors\fP"
.PP
Definition at line 61 of file eps.h.
.SS "unsigned char \fBPSCmap::r\fP[256]"
.PP
Definition at line 63 of file eps.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
