.TH "PSImage" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSImage \- 
.SH SYNOPSIS
.br
.PP
\fC#include <eps.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcols\fP"
.br
.ti -1c
.RI "int \fBrows\fP"
.br
.ti -1c
.RI "int \fBcolorClass\fP"
.br
.ti -1c
.RI "int \fBcompression\fP"
.br
.ti -1c
.RI "int \fBannotate\fP"
.br
.ti -1c
.RI "int \fBllx\fP"
.br
.ti -1c
.RI "int \fBlly\fP"
.br
.ti -1c
.RI "int \fBurx\fP"
.br
.ti -1c
.RI "int \fBury\fP"
.br
.ti -1c
.RI "float \fBz1\fP"
.br
.ti -1c
.RI "float \fBz2\fP"
.br
.ti -1c
.RI "int \fBztype\fP"
.br
.ti -1c
.RI "float \fBoffset\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "char * \fBlabel\fP"
.br
.ti -1c
.RI "\fBPSPage\fP \fBpage\fP"
.br
.ti -1c
.RI "\fBPSCmap\fP \fBcmap\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBPSImage::annotate\fP"
.PP
Definition at line 75 of file eps.h.
.SS "\fBPSCmap\fP \fBPSImage::cmap\fP"
.PP
Definition at line 83 of file eps.h.
.SS "int \fBPSImage::colorClass\fP"
.PP
Definition at line 73 of file eps.h.
.SS "int \fBPSImage::cols\fP"
.PP
Definition at line 71 of file eps.h.
.SS "int \fBPSImage::compression\fP"
.PP
Definition at line 74 of file eps.h.
.SS "char* \fBPSImage::label\fP"
.PP
Definition at line 80 of file eps.h.
.SS "int \fBPSImage::llx\fP"
.PP
Definition at line 76 of file eps.h.
.SS "int \fBPSImage::lly\fP"
.PP
Definition at line 76 of file eps.h.
.SS "float \fBPSImage::offset\fP"
.PP
Definition at line 79 of file eps.h.
.SS "\fBPSPage\fP \fBPSImage::page\fP"
.PP
Definition at line 82 of file eps.h.
.SS "int \fBPSImage::rows\fP"
.PP
Definition at line 72 of file eps.h.
.SS "float \fBPSImage::scale\fP"
.PP
Definition at line 79 of file eps.h.
.SS "int \fBPSImage::urx\fP"
.PP
Definition at line 76 of file eps.h.
.SS "int \fBPSImage::ury\fP"
.PP
Definition at line 76 of file eps.h.
.SS "float \fBPSImage::z1\fP"
.PP
Definition at line 77 of file eps.h.
.SS "float \fBPSImage::z2\fP"
.PP
Definition at line 77 of file eps.h.
.SS "int \fBPSImage::ztype\fP"
.PP
Definition at line 78 of file eps.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
