.TH "PSPageInfo" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSPageInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBsizex\fP"
.br
.ti -1c
.RI "float \fBsizey\fP"
.br
.ti -1c
.RI "int \fBnpixx\fP"
.br
.ti -1c
.RI "int \fBnpixy\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBPSPageInfo::npixx\fP"
.PP
Definition at line 76 of file eps.c.
.SS "int \fBPSPageInfo::npixy\fP"
.PP
Definition at line 76 of file eps.c.
.SS "float \fBPSPageInfo::sizex\fP"
.PP
Definition at line 75 of file eps.c.
.SS "float \fBPSPageInfo::sizey\fP"
.PP
Definition at line 75 of file eps.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
