.TH "PSPage" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSPage \- 
.SH SYNOPSIS
.br
.PP
\fC#include <eps.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBorientation\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "float \fBmaxscale\fP"
.br
.ti -1c
.RI "int \fBdpi\fP"
.br
.ti -1c
.RI "int \fBpage_type\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBPSPage::dpi\fP"
.PP
Definition at line 53 of file eps.h.
.SS "int \fBPSPage::flags\fP"
.PP
Definition at line 55 of file eps.h.
.SS "float \fBPSPage::maxscale\fP"
.PP
Definition at line 52 of file eps.h.
.SS "int \fBPSPage::orientation\fP"
.PP
Definition at line 50 of file eps.h.
.SS "int \fBPSPage::page_type\fP"
.PP
Definition at line 54 of file eps.h.
.SS "float \fBPSPage::scale\fP"
.PP
Definition at line 51 of file eps.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
