psutils.c
NAME
psutils.c -
SYNOPSIS
#include <stdio.h>
#include 'psutils.h'
Functions
void ps (char *string)
void psDrawChar (char aChar)
void print_caption (char *caption)
void set_print_opf (FILE *thefile)
FILE * get_print_opf (void)
void psline (double x1, double y1, double x2, double y2)
Variables
char psstring [10000]
FILE * opf
Function Documentation
FILE* get_print_opf (void)
Definition at line 62 of file psutils.c.
References opf.
Referenced by printimage().
void print_caption (char * caption)
Definition at line 36 of file psutils.c.
void ps (char * string)
Definition at line 12 of file psutils.c.
void psDrawChar (char aChar)
Definition at line 18 of file psutils.c.
void psline (double x1, double y1, double x2, double y2)
Definition at line 68 of file psutils.c.
References opf.
Referenced by contourplot(), and mgoline_().
void set_print_opf (FILE * thefile)
Definition at line 57 of file psutils.c.
Variable Documentation
FILE* opf [static]
Definition at line 10 of file psutils.c.
Referenced by get_print_opf(), ps(), psline(), and set_print_opf().
char psstring[10000] [static]
Definition at line 9 of file psutils.c.
Author
Generated automatically by Doxygen for imcat from the source code.