r2n.c
NAME
r2n.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
Defines
#define usage '\nNAME\n\	r2n - get perpendicular components of a vector\n\\n\SYNOPSIS\n\	r2n rname x y z\n\\n\DESCRIPTION\n\	r2n reads an lc catalog containing positions rname[3]\n\	from stdin, evolves the positions and outputs a two-vector\n\	n[2] which are the components of the unit vector |rname|\n\	perpendicular to the direction (x, y, z).\n\\n\	The reference vector (x, y, z) need not be normalized.\n\\n\SEE ALSO\n\	maketestpparfile.pl makeobs_circ laplace3 tcl_evolve\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	r2n - get perpendicular components of a vector\n\\n\SYNOPSIS\n\	r2n rname x y z\n\\n\DESCRIPTION\n\	r2n reads an lc catalog containing positions rname[3]\n\	from stdin, evolves the positions and outputs a two-vector\n\	n[2] which are the components of the unit vector |rname|\n\	perpendicular to the direction (x, y, z).\n\\n\	The reference vector (x, y, z) need not be normalized.\n\\n\SEE ALSO\n\	maketestpparfile.pl makeobs_circ laplace3 tcl_evolve\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 6 of file r2n.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 27 of file r2n.c.
References assign(), dot(), exit(), i, ipf, length(), n0, nt, phi, r, scale(), usage, x, y, and z.
Author
Generated automatically by Doxygen for imcat from the source code.