radecio.h
NAME
radecio.h -
SYNOPSIS
Defines
#define HMS_ANGLE_TYPE 0
#define DECIMAL_ANGLE_TYPE 1
Functions
int decimaltoxms (double angle, char *hmsstring)
int xmstodecimal (char *hmsstring, double *result)
double getangle (char *argstring, int *type)
double getra (char *argstring, int *type)
double getdec (char *argstring, int *type)
Define Documentation
#define DECIMAL_ANGLE_TYPE 1
Definition at line 6 of file radecio.h.
Referenced by getangle().
#define HMS_ANGLE_TYPE 0
Definition at line 5 of file radecio.h.
Referenced by getangle(), getra(), and main().
Function Documentation
int decimaltoxms (double angle, char * hmsstring)
Definition at line 10 of file radecio.c.
References angle, h, m, and sign.
Referenced by main().
double getangle (char * argstring, int * type)
Definition at line 49 of file radecio.c.
References angle, DECIMAL_ANGLE_TYPE, error_exit, HMS_ANGLE_TYPE, pos, type, and xmstodecimal().
Referenced by getdec(), getra(), and main().
double getdec (char * argstring, int * type)
Definition at line 84 of file radecio.c.
References error_exit, getangle(), and type.
Referenced by main().
double getra (char * argstring, int * type)
Definition at line 69 of file radecio.c.
References error_exit, getangle(), HMS_ANGLE_TYPE, ra, and type.
Referenced by main().
int xmstodecimal (char * hmsstring, double * result)
Definition at line 27 of file radecio.c.
References error_exit, h, m, and sign.
Referenced by getangle(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.