.TH "radfg.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
radfg.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBradfg_\fP (\fBinteger\fP *ido, \fBinteger\fP *ip, \fBinteger\fP *l1, \fBinteger\fP *idl1, \fBreal\fP *cc, \fBreal\fP *c1, \fBreal\fP *c2, \fBreal\fP *ch, \fBreal\fP *ch2, \fBreal\fP *wa)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int radfg_ (\fBinteger\fP * ido, \fBinteger\fP * ip, \fBinteger\fP * l1, \fBinteger\fP * idl1, \fBreal\fP * cc, \fBreal\fP * c1, \fBreal\fP * c2, \fBreal\fP * ch, \fBreal\fP * ch2, \fBreal\fP * wa)"
.PP
Definition at line 9 of file radfg.c.
.PP
References integer, j, k, l, and real.
.PP
Referenced by rfftf1_().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
