.TH "ran1.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ran1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBM1\fP   259200"
.br
.ti -1c
.RI "#define \fBIA1\fP   7141"
.br
.ti -1c
.RI "#define \fBIC1\fP   54773"
.br
.ti -1c
.RI "#define \fBRM1\fP   (1.0/\fBM1\fP)"
.br
.ti -1c
.RI "#define \fBM2\fP   134456"
.br
.ti -1c
.RI "#define \fBIA2\fP   8121"
.br
.ti -1c
.RI "#define \fBIC2\fP   28411"
.br
.ti -1c
.RI "#define \fBRM2\fP   (1.0/\fBM2\fP)"
.br
.ti -1c
.RI "#define \fBM3\fP   243000"
.br
.ti -1c
.RI "#define \fBIA3\fP   4561"
.br
.ti -1c
.RI "#define \fBIC3\fP   51349"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBran1\fP (int *idum)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define IA1   7141"
.PP
Definition at line 8 of file ran1.c.
.PP
Referenced by ran1().
.SS "#define IA2   8121"
.PP
Definition at line 12 of file ran1.c.
.PP
Referenced by ran1().
.SS "#define IA3   4561"
.PP
Definition at line 16 of file ran1.c.
.PP
Referenced by ran1().
.SS "#define IC1   54773"
.PP
Definition at line 9 of file ran1.c.
.PP
Referenced by ran1().
.SS "#define IC2   28411"
.PP
Definition at line 13 of file ran1.c.
.PP
Referenced by ran1().
.SS "#define IC3   51349"
.PP
Definition at line 17 of file ran1.c.
.PP
Referenced by ran1().
.SS "#define \fBM1\fP   259200"
.PP
Definition at line 7 of file ran1.c.
.PP
Referenced by fastmap(), getshape2(), getshape3(), ifunc(), main(), map(), ran1(), rfunc(), and ultrafastmap().
.SS "#define \fBM2\fP   134456"
.PP
Definition at line 11 of file ran1.c.
.PP
Referenced by fastmap(), getshape2(), getshape3(), ifunc(), main(), map(), ran1(), rfunc(), and ultrafastmap().
.SS "#define M3   243000"
.PP
Definition at line 15 of file ran1.c.
.PP
Referenced by ran1().
.SS "#define RM1   (1.0/\fBM1\fP)"
.PP
Definition at line 10 of file ran1.c.
.PP
Referenced by ran1().
.SS "#define RM2   (1.0/\fBM2\fP)"
.PP
Definition at line 14 of file ran1.c.
.PP
Referenced by ran1().
.SH "Function Documentation"
.PP 
.SS "float ran1 (int * idum)"
.PP
Definition at line 20 of file ran1.c.
.PP
References exit(), IA1, IA2, IA3, IC1, IC2, IC3, j, M1, M2, M3, r, RM1, and RM2.
.PP
Referenced by poidev().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
