.TH "ran1.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ran1.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBran1\fP (int *idum)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float ran1 (int * idum)"
.PP
Definition at line 20 of file ran1.c.
.PP
References exit(), IA1, IA2, IA3, IC1, IC2, IC3, j, M1, M2, M3, r, RM1, and RM2.
.PP
Referenced by poidev().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
