readusnoacat.c
NAME
readusnoacat.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include 'utils/error.h'
#include 'imlib/fits.h'
#include 'readusnoacat.h'
#include 'getxfromradecfunc.h'
#include 'radecio.h'
Defines
#define usage '\n\NAME\n\	readusnoacat --- extract catalogue from USNO-A database\n\\n\SYNOPSIS\n\	readusnoacat ra dl dec ddec\n\\n\DESCRIPTION\n\	Readusnoacat extracts a lc-format catalogue from the\n\	US Naval Observatory all-sky astrometric catalogue.\n\\n\	All objects with ra lying in the range\n\	ra +- (dl / cos(dec)) and dec in the range\n\	dec +- ddec (epoch 2000) are extracted. \n\	The parameterisation of the range in longitude dl\n\	is chosen so that in the small angle approximation\n\	one obtains a box of height ddec and width dl both in\n\	degrees.\n\\n\	Angle arguments may be given in decimal notation, in\n\	which case they are interpreted as degrees, or as\n\	colon separated triplets, in which case they are interpreted\n\	as h:m:s (for ra, dra) and d:m:s (dec, ddec)\n\\n\	Readusnoacat expects to find an environment variable\n\	USNOADIR telling it the directory containing the source\n\	catalogue files.\n\\n\	The output catalogue contains the following entries:\n\		x[2]		# sterographic sky coords\n\		RA		# right ascension [deg]\n\		DEC		# declination [deg]\n\		rmag		# red magnitude\n\		bmag		# blue magnitude\n\		qflag		# indicates mag error if set\n\		gflag		# indicates a correlated GSC entry\n\		fieldno		# source image number\n\	See the USNO-A readme files for more information on the\n\	meaning of the flags.\n\\n\	x[2] is a stereographic projection (in units of degrees).\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
#define SPDBANDWIDTH10 75
#define SPDBANDWIDTH 7.5
#define swap_word(a)
Functions
main (int argc, char *argv[])
int getobjects (char *basefilename, double ra0, double ra1, double dec0, double dec1, double rao, double deco)
Variables
FILE * lcpipe
Define Documentation
#define SPDBANDWIDTH 7.5
Definition at line 64 of file readusnoacat.c.
Referenced by main().
#define SPDBANDWIDTH10 75
Definition at line 63 of file readusnoacat.c.
Referenced by main().
#define swap_word(a)
Value:.nf
( ((a) << 24) | \
                      (((a) << 8) & 0x00ff0000) | \
                      (((a) >> 8) & 0x0000ff00) | \
        ((unsigned int)(a) >>24) )
Definition at line 66 of file readusnoacat.c.
Referenced by getobjects().
#define usage '\n\NAME\n\	readusnoacat --- extract catalogue from USNO-A database\n\\n\SYNOPSIS\n\	readusnoacat ra dl dec ddec\n\\n\DESCRIPTION\n\	Readusnoacat extracts a lc-format catalogue from the\n\	US Naval Observatory all-sky astrometric catalogue.\n\\n\	All objects with ra lying in the range\n\	ra +- (dl / cos(dec)) and dec in the range\n\	dec +- ddec (epoch 2000) are extracted. \n\	The parameterisation of the range in longitude dl\n\	is chosen so that in the small angle approximation\n\	one obtains a box of height ddec and width dl both in\n\	degrees.\n\\n\	Angle arguments may be given in decimal notation, in\n\	which case they are interpreted as degrees, or as\n\	colon separated triplets, in which case they are interpreted\n\	as h:m:s (for ra, dra) and d:m:s (dec, ddec)\n\\n\	Readusnoacat expects to find an environment variable\n\	USNOADIR telling it the directory containing the source\n\	catalogue files.\n\\n\	The output catalogue contains the following entries:\n\		x[2]		# sterographic sky coords\n\		RA		# right ascension [deg]\n\		DEC		# declination [deg]\n\		rmag		# red magnitude\n\		bmag		# blue magnitude\n\		qflag		# indicates mag error if set\n\		gflag		# indicates a correlated GSC entry\n\		fieldno		# source image number\n\	See the USNO-A readme files for more information on the\n\	meaning of the flags.\n\\n\	x[2] is a stereographic projection (in units of degrees).\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file readusnoacat.c.
Function Documentation
int getobjects (char * basefilename, double ra0, double ra1, double dec0, double dec1, double rao, double deco)
Definition at line 137 of file readusnoacat.c.
main (int argc, char * argv[])
Definition at line 73 of file readusnoacat.c.
References argsToString(), error_exit, exit(), getdec(), getobjects(), getra(), lcpipe, ra, SPDBANDWIDTH, SPDBANDWIDTH10, type, and usage.
Variable Documentation
FILE* lcpipe
Definition at line 71 of file readusnoacat.c.
Referenced by getmodeamplitudes_lc(), getobjects(), getvars(), main(), outputrcat(), and readmergedcat().
Author
Generated automatically by Doxygen for imcat from the source code.