read4shooter.c
NAME
read4shooter.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include 'magic.h'
#include '../utils/arrays.h'
Defines
#define usage '\n\n\n\SYNOPSIS\n\	read4shooter [option...]\n\\n\DESCRIPTION\n\	converts a 4-shooter image to fits format\n\	Reads and writes from stdin, stdout\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define swap_half(a) ( ((a & 0xff) << 8) | ((unsigned short)(a) >> 8) )
#define N1 816
#define N2 800
#define NREC 160
Functions
short sheaderrecord ()
main (int argc, char *argv[])
short sheaderrecord (int i)
Variables
char buff [8192]
Define Documentation
#define N1 816
Definition at line 30 of file read4shooter.c.
#define N2 800
Definition at line 31 of file read4shooter.c.
#define NREC 160
Definition at line 32 of file read4shooter.c.
Referenced by main().
#define swap_half(a) ( ((a & 0xff) << 8) | ((unsigned short)(a) >> 8) )
Definition at line 29 of file read4shooter.c.
#define usage '\n\n\n\SYNOPSIS\n\	read4shooter [option...]\n\\n\DESCRIPTION\n\	converts a 4-shooter image to fits format\n\	Reads and writes from stdin, stdout\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 5 of file read4shooter.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 38 of file read4shooter.c.
References add_1comment(), add_comment(), buff, comment, error_exit, exit(), f, i, j, MAGIC, N1, N2, NREC, sheaderrecord(), swap_half, usage, write_fits_head(), write_fits_line(), and write_fits_tail().
short sheaderrecord (int i)
Definition at line 124 of file read4shooter.c.
References buff, i, and swap_half.
short sheaderrecord ()
Referenced by main().
Variable Documentation
char buff[8192]
Definition at line 36 of file read4shooter.c.
Referenced by main(), readdoublebuff(), readmergedcat(), sheaderrecord(), and writehotpixel().
Author
Generated automatically by Doxygen for imcat from the source code.