.TH "read.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
read.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   'usage: read fifo\\\fBn\fP'"
.br
.ti -1c
.RI "#define \fBBUFFSIZE\fP   1024"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define BUFFSIZE   1024"
.PP
Definition at line 5 of file read.c.
.SS "#define \fBusage\fP   'usage: read fifo\\\fBn\fP'"
.PP
Definition at line 3 of file read.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 7 of file read.c.
.PP
References BUFFSIZE, exit(), ipf, and usage.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
