readusnoacat.h
NAME
readusnoacat.h -
SYNOPSIS
Functions
int getobjects (char *basefilename, double ra0, double ra1, double dec0, double dec1, double rao, double deco)
int getxcoords (double ra, double dec, double rao, double deco, double *x)
Function Documentation
int getobjects (char * basefilename, double ra0, double ra1, double dec0, double dec1, double rao, double deco)
Definition at line 137 of file readusnoacat.c.
References catfile, exit(), getxcoords(), lcpipe, ra, swap_word, and x.
int getxcoords (double ra, double dec, double rao, double deco, double * x)
Definition at line 15 of file getxfromradecfunc.c.
References i, phi, ra, x, xo, and xp().
Referenced by getobjects(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.