readusnobcat.c
NAME
readusnobcat.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include 'utils/error.h'
#include 'imlib/fits.h'
#include 'getxfromradecfunc.h'
#include 'radecio.h'
Defines
#define usage '\n\NAME\n\	readusnobcat --- extract lc-format sub-catalogue from USNO-B database\n\\n\SYNOPSIS\n\	readusnobcat ra dec dr [-all]\n\\n\DESCRIPTION\n\	Readusnobcat extracts a lc-format catalogue from the\n\	US Naval Observatory all-sky astrometric catalogue (version B).\n\\n\	Objects are selected if they lie within stereographic distance\n\	dr (in degrees) of the tangent point ra dec.\n\\n\	Arguments ra, dec may be given in decimal notation, in\n\	which case they are interpreted as degrees, or as\n\	colon separated triplets, in which case they are interpreted\n\	as h:m:s (for ra, dra) and d:m:s (dec, ddec)\n\\n\	Readusnobcat expects to find an environment variable\n\	USNOBDIR telling it the directory containing the source\n\	catalogue files.\n\\n\	We do not output objects that are flagged as likely false\n\	unless the optional argument -all is provided.\n\\n\	The output catalogue contains the following entries:\n\		x[2]		# stereographic sky coords\n\		RA		# right ascension [deg]\n\		DEC		# declination [deg]\n\		muRA		# proper motion in RA [arcsec/yr]\n\		muDEC		# proper motion in DEC [arcsec/yr]\n\		sigmaRA		# uncertainty in RA [deg]\n\		sigmaDEC	# uncertainty in DEC [deg]\n\		sigmamuRA	# uncertainty in proper motion in RA [arcsec/yr]\n\		sigmamuDEC	# uncertainty in proper motion in DEC [arcsec/yr]\n\		ndet		# number of detections\n\		mag[5]		# magnitudes, [B1, R1, B2, R2, N]\n\		stargal[5]	# star/galaxy classifier (0=galaxy, 11=star)\n\	See the USNO-B readme files for more information on the\n\	meaning of the flags.\n\\n\	x[2] is a stereographic projection (in units of degrees).\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
#define SPDBANDWIDTH 1.0
#define swap_word(a)
Functions
int getobjects (char *basefilename, double ra0, double ra1, double dec0, double dec1, double rao, double deco, double dr)
main (int argc, char *argv[])
Variables
int outputallobjects
Define Documentation
#define SPDBANDWIDTH 1.0
Definition at line 64 of file readusnobcat.c.
#define swap_word(a)
Value:.nf
( ((a) << 24) | \
                      (((a) << 8) & 0x00ff0000) | \
                      (((a) >> 8) & 0x0000ff00) | \
        ((unsigned int)(a) >>24) )
Definition at line 66 of file readusnobcat.c.
#define usage '\n\NAME\n\	readusnobcat --- extract lc-format sub-catalogue from USNO-B database\n\\n\SYNOPSIS\n\	readusnobcat ra dec dr [-all]\n\\n\DESCRIPTION\n\	Readusnobcat extracts a lc-format catalogue from the\n\	US Naval Observatory all-sky astrometric catalogue (version B).\n\\n\	Objects are selected if they lie within stereographic distance\n\	dr (in degrees) of the tangent point ra dec.\n\\n\	Arguments ra, dec may be given in decimal notation, in\n\	which case they are interpreted as degrees, or as\n\	colon separated triplets, in which case they are interpreted\n\	as h:m:s (for ra, dra) and d:m:s (dec, ddec)\n\\n\	Readusnobcat expects to find an environment variable\n\	USNOBDIR telling it the directory containing the source\n\	catalogue files.\n\\n\	We do not output objects that are flagged as likely false\n\	unless the optional argument -all is provided.\n\\n\	The output catalogue contains the following entries:\n\		x[2]		# stereographic sky coords\n\		RA		# right ascension [deg]\n\		DEC		# declination [deg]\n\		muRA		# proper motion in RA [arcsec/yr]\n\		muDEC		# proper motion in DEC [arcsec/yr]\n\		sigmaRA		# uncertainty in RA [deg]\n\		sigmaDEC	# uncertainty in DEC [deg]\n\		sigmamuRA	# uncertainty in proper motion in RA [arcsec/yr]\n\		sigmamuDEC	# uncertainty in proper motion in DEC [arcsec/yr]\n\		ndet		# number of detections\n\		mag[5]		# magnitudes, [B1, R1, B2, R2, N]\n\		stargal[5]	# star/galaxy classifier (0=galaxy, 11=star)\n\	See the USNO-B readme files for more information on the\n\	meaning of the flags.\n\\n\	x[2] is a stereographic projection (in units of degrees).\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file readusnobcat.c.
Function Documentation
int getobjects (char * basefilename, double ra0, double ra1, double dec0, double dec1, double rao, double deco, double dr)
Definition at line 160 of file readusnobcat.c.
References catfile, dr, exit(), getxcoords(), i, nobj, outputallobjects, ra, swap_word, and x.
Referenced by main().
main (int argc, char * argv[])
Definition at line 75 of file readusnobcat.c.
References argsToString(), dr, error_exit, exit(), getdec(), getobjects(), getra(), i, outputallobjects, ra, SPDBANDWIDTH, type, and usage.
Variable Documentation
int outputallobjects [static]
Definition at line 73 of file readusnobcat.c.
Referenced by getobjects(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.