rectangles.c
NAME
rectangles.c -
SYNOPSIS
#include <stdlib.h>
#include <math.h>
#include 'rectangles.h'
Data Structures
struct rectangle
Defines
#define MAX_RECTS 1000
Typedefs
typedef rectangle rectangle
Functions
int installrect (float x1, float x2, float y1, float y2)
int deactivate (float x, float y, float *x1, float *x2, float *y1, float *y2)
void setposfirst (void)
int getrect (float *x1, float *x2, float *y1, float *y2)
Variables
rectangle * rectlis [MAX_RECTS]
int pos = 0 lastpos
Define Documentation
#define MAX_RECTS 1000
Definition at line 9 of file rectangles.c.
Typedef Documentation
typedef struct rectangle rectangle
Function Documentation
int deactivate (float x, float y, float * x1, float * x2, float * y1, float * y2)
Definition at line 43 of file rectangles.c.
References pos, rectlis, x, and y.
Referenced by main().
int getrect (float * x1, float * x2, float * y1, float * y2)
Definition at line 79 of file rectangles.c.
References pos, and rectlis.
Referenced by main().
int installrect (float x1, float x2, float y1, float y2)
Definition at line 20 of file rectangles.c.
References pos, and rectlis.
Referenced by main().
void setposfirst (void)
Definition at line 73 of file rectangles.c.
References pos.
Referenced by main().
Variable Documentation
int pos = 0 lastpos [static]
Definition at line 17 of file rectangles.c.
Referenced by deactivate(), getrect(), installrect(), and setposfirst().
rectangle* rectlis[MAX_RECTS] [static]
Definition at line 16 of file rectangles.c.
Referenced by deactivate(), getrect(), and installrect().
Author
Generated automatically by Doxygen for imcat from the source code.