.TH "rectangle" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rectangle \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx1\fP"
.br
.ti -1c
.RI "float \fBx2\fP"
.br
.ti -1c
.RI "float \fBy1\fP"
.br
.ti -1c
.RI "float \fBy2\fP"
.br
.ti -1c
.RI "int \fBactive\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBrectangle::active\fP"
.PP
Definition at line 13 of file rectangles.c.
.SS "float \fBrectangle::x1\fP"
.PP
Definition at line 12 of file rectangles.c.
.SS "float \fBrectangle::x2\fP"
.PP
Definition at line 12 of file rectangles.c.
.SS "float \fBrectangle::y1\fP"
.PP
Definition at line 12 of file rectangles.c.
.SS "float \fBrectangle::y2\fP"
.PP
Definition at line 12 of file rectangles.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
