rectangles.h
NAME
rectangles.h -
SYNOPSIS
Functions
int installrect (float x1, float x2, float y1, float y2)
int deactivate (float x, float y, float *x1, float *x2, float *y1, float *y2)
void setposfirst (void)
int getrect (float *x1, float *x2, float *y1, float *y2)
Function Documentation
int deactivate (float x, float y, float * x1, float * x2, float * y1, float * y2)
Definition at line 43 of file rectangles.c.
References pos, rectlis, x, and y.
Referenced by main().
int getrect (float * x1, float * x2, float * y1, float * y2)
Definition at line 79 of file rectangles.c.
References pos, and rectlis.
Referenced by main().
int installrect (float x1, float x2, float y1, float y2)
Definition at line 20 of file rectangles.c.
References pos, and rectlis.
Referenced by main().
void setposfirst (void)
Definition at line 73 of file rectangles.c.
References pos.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.