fitstack.c
NAME
fitstack.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'fitstack.h'
#include 'utils/modefunc.h'
#include 'fitstack_read.h'
Defines
#define usage '\n\NAME\n\	fitstack --- fit for transformation coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitstack nexp [options....]\n\		-l lmin lmax		# min and max order for distortion polynomials\n\		-i niter		# number of iterations (1)\n\		-c outcat		# output catalogue containing magc, r-values\n\		-o x0 y0		# origin for spatial coordinates (0, 0)\n\		-d distparfilename	# file for distortion model parameters\n\		-t transparfilename	# file for linear transformation params\n\\n\DESCRIPTION\n\	'fitstack' reads from stdin a catalogue containing the result of\n\	merging all pairs of cats for a stack of 'nexp' images (as created\n\	by 'mergestack') and which must contain entries for\n\	spatial coords 'x[2][2]', magnitude 'mag[2]' and exposure number 'exp[2]'.\n\	It then fits a model in which sky coords (in frame defined by exposure-0) are\n\		r = r_e + dphi_e r_e + d_e\n\	where the 2x2 matrix dphi allows for rotations between\n\	exposures and possibly atmospheric refraction, and we set\n\	dphi = d = 0 for the 0th exposure.\n\	It will also optionally then fit for distortion of telescope\n\	using a model in which sky coords r are related to detector coords x by\n\		r_e = x_e + sum a_m f_m(x_e)\n\	where m labels the modes, and where each mode coefficient a_m\n\	is a 2-vector and the modes are polynomials\n\	of order 'lmin' through 'lmax'.\n\	For lmin = 2, lmax = 4 say, the modes are:\n\		x^2, xy, y^2, x^3, x^2 y, x y^2, y^3,\n\		x^4, x^3 y, x^2 y^2, x y^3, y^4.\n\	With -o option, these become polynomials in position relative\n\	to specified spatial origin.\n\	We also read magnitudes, which we model as:\n\		m_e = m + M_e\n\	where m is the true magnitude and M_e is the magnitude\n\	offset the e'th exposure (relative to exp-0).\n\	Use the '-c' option to generate a merged catalogue which contains,\n\	in addition to the source catalogue values, the sky coordinates 'r'\n\	and also corrected magnitudes 'magc', which can then be filtered\n\	to remove bad pairs and then fed back to 'fitstack' to improve\n\	the solution.\n\	See also fitstack.tex.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
#define SCALE 1.0
Functions
main (int argc, char *argv[])
int make_r (void)
int make_re (void)
int make_z (void)
int fitextinctions (void)
int fittranslations (void)
int fitdistortions (void)
int allocatearrays (void)
double *** allocpositionvector (void)
int printtranslations (char *parfile)
double chisquared (void)
int outputrcat (char *outputcatfilename)
Variables
double *** x
double ** mag
double *** re = NULL ***r = NULL ***z = NULL
int ** e
int nprs
int nexp
int nmodes
int lmin
int lmax
int * ll
int * mm
double * d [2]
double * phi [2][2]
double * a [2]
double * dm
int * indxt
int * indxd
int * indxm
int ntcoefft
int ndcoefft
int nmcoefft
int dodistfit
double ** At
double * Bt
double ** Ad
double * Bd
double ** Am
double * Bm
double det
double * Ct [2]
double * Cd [2]
double * Cm
Define Documentation
#define SCALE 1.0
Definition at line 62 of file registration/fitstack.c.
#define usage '\n\NAME\n\	fitstack --- fit for transformation coefficients for a set of exposures\n\\n\SYNOPSIS\n\	fitstack nexp [options....]\n\		-l lmin lmax		# min and max order for distortion polynomials\n\		-i niter		# number of iterations (1)\n\		-c outcat		# output catalogue containing magc, r-values\n\		-o x0 y0		# origin for spatial coordinates (0, 0)\n\		-d distparfilename	# file for distortion model parameters\n\		-t transparfilename	# file for linear transformation params\n\\n\DESCRIPTION\n\	'fitstack' reads from stdin a catalogue containing the result of\n\	merging all pairs of cats for a stack of 'nexp' images (as created\n\	by 'mergestack') and which must contain entries for\n\	spatial coords 'x[2][2]', magnitude 'mag[2]' and exposure number 'exp[2]'.\n\	It then fits a model in which sky coords (in frame defined by exposure-0) are\n\		r = r_e + dphi_e r_e + d_e\n\	where the 2x2 matrix dphi allows for rotations between\n\	exposures and possibly atmospheric refraction, and we set\n\	dphi = d = 0 for the 0th exposure.\n\	It will also optionally then fit for distortion of telescope\n\	using a model in which sky coords r are related to detector coords x by\n\		r_e = x_e + sum a_m f_m(x_e)\n\	where m labels the modes, and where each mode coefficient a_m\n\	is a 2-vector and the modes are polynomials\n\	of order 'lmin' through 'lmax'.\n\	For lmin = 2, lmax = 4 say, the modes are:\n\		x^2, xy, y^2, x^3, x^2 y, x y^2, y^3,\n\		x^4, x^3 y, x^2 y^2, x y^3, y^4.\n\	With -o option, these become polynomials in position relative\n\	to specified spatial origin.\n\	We also read magnitudes, which we model as:\n\		m_e = m + M_e\n\	where m is the true magnitude and M_e is the magnitude\n\	offset the e'th exposure (relative to exp-0).\n\	Use the '-c' option to generate a merged catalogue which contains,\n\	in addition to the source catalogue values, the sky coordinates 'r'\n\	and also corrected magnitudes 'magc', which can then be filtered\n\	to remove bad pairs and then fed back to 'fitstack' to improve\n\	the solution.\n\	See also fitstack.tex.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
Definition at line 6 of file registration/fitstack.c.
Function Documentation
int allocatearrays (void)
Definition at line 455 of file registration/fitstack.c.
Referenced by main().
double*** allocpositionvector (void)
Definition at line 501 of file registration/fitstack.c.
Referenced by allocpositionvector(), make_r(), make_re(), and make_z().
double chisquared (void)
Definition at line 541 of file registration/fitstack.c.
Referenced by main().
int fitdistortions (void)
Definition at line 405 of file registration/fitstack.c.
References a, Ad, Bd, Cd, det, e, f(), i, indxd, j, ll, m, M, mm, mylubksb(), myludcmp(), n, ndcoefft, nmodes, nprs, phi, x, and z.
Referenced by main().
int fitextinctions (void)
Definition at line 301 of file registration/fitstack.c.
References Am, Bm, Cm, det, dm, e, i, indxm, j, m, mag, mylubksb(), myludcmp(), n, nexp, nmcoefft, and nprs.
Referenced by main().
int fittranslations (void)
Definition at line 344 of file registration/fitstack.c.
Referenced by main().
main (int argc, char * argv[])
Definition at line 80 of file registration/fitstack.c.
References a, allocatearrays(), chi2(), chisquared(), dodistfit, error_exit, exit(), fitdistortions(), fitextinctions(), fittranslations(), i, j, l, ll, lmax, lmin, M, m, make_r(), make_re(), make_z(), mm, modefunc_addargcomment(), n, ndcoefft, nexp, nmcoefft, nmodes, nprs, ntcoefft, outputrcat(), printtranslations(), readmergedcat(), setorigin(), usage, and write2Dpolymodel().
int make_r (void)
Definition at line 223 of file registration/fitstack.c.
Referenced by main().
int make_re (void)
Definition at line 254 of file registration/fitstack.c.
References a, allocpositionvector(), f(), i, ll, M, mm, n, nmodes, nprs, re, x, and xx.
Referenced by main().
int make_z (void)
Definition at line 279 of file registration/fitstack.c.
References allocpositionvector(), d, e, i, j, n, nprs, phi, x, and z.
Referenced by main().
int outputrcat (char * outputcatfilename)
Definition at line 557 of file registration/fitstack.c.
int printtranslations (char * parfile)
Definition at line 522 of file registration/fitstack.c.
Variable Documentation
double* a[2] [static]
Definition at line 73 of file registration/fitstack.c.
double ** Ad [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by allocatearrays(), and fitdistortions().
double ** Am [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by allocatearrays(), and fitextinctions().
double** At [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by allocatearrays(), and fittranslations().
double * Bd [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by allocatearrays(), and fitdistortions().
double * Bm [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by allocatearrays(), and fitextinctions().
double * Bt [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by allocatearrays(), and fittranslations().
double * Cd[2] [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by allocatearrays(), and fitdistortions().
double * Cm [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by allocatearrays(), and fitextinctions().
double * Ct[2] [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by allocatearrays(), and fittranslations().
double* d[2] [static]
Definition at line 71 of file registration/fitstack.c.
double det [static]
Definition at line 78 of file registration/fitstack.c.
Referenced by fitdistortions(), fitextinctions(), and fittranslations().
double* dm [static]
Definition at line 75 of file registration/fitstack.c.
Referenced by allocatearrays(), fitextinctions(), outputrcat(), and printtranslations().
int dodistfit [static]
Definition at line 77 of file registration/fitstack.c.
Referenced by allocatearrays(), and main().
int** e
Definition at line 66 of file registration/fitstack.c.
int * indxd [static]
Definition at line 77 of file registration/fitstack.c.
Referenced by allocatearrays(), and fitdistortions().
int * indxm [static]
Definition at line 77 of file registration/fitstack.c.
Referenced by allocatearrays(), and fitextinctions().
int* indxt [static]
Definition at line 77 of file registration/fitstack.c.
Referenced by allocatearrays(), and fittranslations().
int * ll [static]
Definition at line 69 of file registration/fitstack.c.
Referenced by fitdistortions(), main(), make_r(), and make_re().
int lmax [static]
Definition at line 69 of file registration/fitstack.c.
Referenced by main().
int lmin [static]
Definition at line 69 of file registration/fitstack.c.
Referenced by main().
double ** mag
Definition at line 65 of file registration/fitstack.c.
Referenced by fitextinctions(), main(), outputrcat(), printselection(), and readmergedcat().
int * mm [static]
Definition at line 69 of file registration/fitstack.c.
Referenced by fitdistortions(), main(), make_r(), and make_re().
int ndcoefft [static]
Definition at line 77 of file registration/fitstack.c.
Referenced by allocatearrays(), fitdistortions(), and main().
int nexp [static]
Definition at line 69 of file registration/fitstack.c.
Referenced by allocatearrays(), fitextinctions(), fittranslations(), main(), and printtranslations().
int nmcoefft [static]
Definition at line 77 of file registration/fitstack.c.
Referenced by allocatearrays(), fitextinctions(), and main().
int nmodes [static]
Definition at line 69 of file registration/fitstack.c.
int nprs [static]
Definition at line 69 of file registration/fitstack.c.
Referenced by allocpositionvector(), chisquared(), fitdistortions(), fitextinctions(), fittranslations(), main(), make_r(), make_re(), make_z(), and outputrcat().
int ntcoefft [static]
Definition at line 77 of file registration/fitstack.c.
Referenced by allocatearrays(), fittranslations(), and main().
double * phi[2][2] [static]
Definition at line 71 of file registration/fitstack.c.
double *** re = NULL ***r = NULL ***z = NULL
Definition at line 65 of file registration/fitstack.c.
double*** x
Definition at line 65 of file registration/fitstack.c.
Author
Generated automatically by Doxygen for imcat from the source code.