register.c
NAME
register.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../utils/arrays.h'
#include '../fftlib/myfft.h'
#include '../utils/error.h'
#include '../imlib/filters.h'
Defines
#define usage 'usage: register xylist x'y'list [options...]\n\	read 2 lists of coords: (x,y), (x',y') and determine\n\	scale, rotation and translation that maps (x',y') => (x,y)\n\		x = a (x' cos - y' sin) + x0\n\		y = a (x' sin + y' cos) + y0\n\	It works by cross-correlating images of wrapped lnr, phi\n\	values for pairs of objects and locating peak to determine\n\	a, phi. We then rotate and scale x' y', generate images\n\	of x,y positions and cross correlate these to get x0, y0.\n\	Outputs x0, y0, a, phi.\n\	Options are:\n\		-i imsize	# internal image size (512)\n\		-p phi1 phi2	# range for phi wrapping (0, PI)\n\		-a a1 a2	# find peaks only in this range of scale\n\		-d dlnr		# range of lnr for wrapping (1.0)\n\\n\n'
#define PI M_PI
#define MAX_OBJECTS 100000
#define BIG_NEG -1.e10
#define BIG_POS 1.e10;
Functions
float mexicanfilterfunction (float ki, float kj)
main (int argc, char *argv[])
Define Documentation
#define BIG_NEG -1.e10
Definition at line 34 of file register.c.
#define BIG_POS 1.e10;
Definition at line 35 of file register.c.
#define MAX_OBJECTS 100000
Definition at line 33 of file register.c.
#define PI M_PI
Definition at line 32 of file register.c.
#define usage 'usage: register xylist x'y'list [options...]\n\	read 2 lists of coords: (x,y), (x',y') and determine\n\	scale, rotation and translation that maps (x',y') => (x,y)\n\		x = a (x' cos - y' sin) + x0\n\		y = a (x' sin + y' cos) + y0\n\	It works by cross-correlating images of wrapped lnr, phi\n\	values for pairs of objects and locating peak to determine\n\	a, phi. We then rotate and scale x' y', generate images\n\	of x,y positions and cross correlate these to get x0, y0.\n\	Outputs x0, y0, a, phi.\n\	Options are:\n\		-i imsize	# internal image size (512)\n\		-p phi1 phi2	# range for phi wrapping (0, PI)\n\		-a a1 a2	# find peaks only in this range of scale\n\		-d dlnr		# range of lnr for wrapping (1.0)\n\\n\n'
Definition at line 15 of file register.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 39 of file register.c.
References a1, a2, alloc_fft(), allocFloatArray(), BIG_NEG, BIG_POS, c, ccf(), dx, dy, error_exit, exit(), fft_type, forward_fft(), i, ipf, ix, line, MAX_OBJECTS, mexicanfilter(), n, nobj, phi, PI, usage, x, X, y, and Y.
float mexicanfilterfunction (float ki, float kj)
Definition at line 498 of file filters.c.
Referenced by mexicanfilter().
Author
Generated automatically by Doxygen for imcat from the source code.