fitstack.h
NAME
fitstack.h -
SYNOPSIS
Functions
int make_r (void)
int make_re (void)
int make_z (void)
int fitextinctions (void)
int fittranslations (void)
int fitdistortions (void)
int allocatearrays (void)
double *** allocpositionvector (void)
int printtranslations (char *parfilename)
double chisquared (void)
int outputrcat (char *outputcatfilename)
Function Documentation
int allocatearrays (void)
Definition at line 455 of file registration/fitstack.c.
double*** allocpositionvector (void)
Definition at line 501 of file registration/fitstack.c.
double chisquared (void)
Definition at line 541 of file registration/fitstack.c.
References chi2(), i, nprs, and r.
int fitdistortions (void)
Definition at line 405 of file registration/fitstack.c.
References a, Ad, Bd, Cd, det, e, f(), i, indxd, j, ll, M, m, mm, mylubksb(), myludcmp(), n, ndcoefft, nmodes, nprs, phi, x, and z.
Referenced by main().
int fitextinctions (void)
Definition at line 301 of file registration/fitstack.c.
References Am, Bm, Cm, det, dm, e, i, indxm, j, m, mag, mylubksb(), myludcmp(), n, nexp, nmcoefft, and nprs.
Referenced by main().
int fittranslations (void)
Definition at line 344 of file registration/fitstack.c.
int make_r (void)
Definition at line 223 of file registration/fitstack.c.
int make_re (void)
Definition at line 254 of file registration/fitstack.c.
References a, allocpositionvector(), f(), i, ll, M, mm, n, nmodes, nprs, re, x, and xx.
Referenced by main().
int make_z (void)
Definition at line 279 of file registration/fitstack.c.
References allocpositionvector(), d, e, i, j, n, nprs, phi, x, and z.
Referenced by main().
int outputrcat (char * outputcatfilename)
Definition at line 557 of file registration/fitstack.c.
References dm, e, exit(), lcpipe, mag, nprs, r, and x.
int printtranslations (char * parfilename)
Definition at line 522 of file registration/fitstack.c.
References d, dm, error_exit, i, nexp, and phi.
Author
Generated automatically by Doxygen for imcat from the source code.