removecrs.c
NAME
removecrs.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'imlib/fits.h'
#include 'utils/error.h'
#include 'utils/stats_stuff.h'
#include 'utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	removecrs - replace cosmic rays with MAGIC\n\\n\SYNOPSIS\n\	removecrs	[option...]\n\		-c	nuc	# threshold for centre pixel(default = 20)\n\		-s 	nus	# threshold for surrounding pixels (default 5)\n\		-n	nn	# required number of neighbours (default = 4)\n\n\\n\DESCRIPTION\n\	'removecrs' replaces cosmic rays with MAGIC.\n\n\	A pixel is replaced provided f > mode + nuc * sigma and\n\	at least nn immediate neighbours have f < mode + nus * sigma\n\	Reads from stdin and writes to stdout\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
Functions
main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 32 of file removecrs.c.
#define usage '\n\n\n\NAME\n\	removecrs - replace cosmic rays with MAGIC\n\\n\SYNOPSIS\n\	removecrs	[option...]\n\		-c	nuc	# threshold for centre pixel(default = 20)\n\		-s 	nus	# threshold for surrounding pixels (default 5)\n\		-n	nn	# required number of neighbours (default = 4)\n\n\\n\DESCRIPTION\n\	'removecrs' replaces cosmic rays with MAGIC.\n\n\	A pixel is replaced provided f > mode + nuc * sigma and\n\	at least nn immediate neighbours have f < mode + nus * sigma\n\	Reads from stdin and writes to stdout\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file removecrs.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 34 of file removecrs.c.
References add_comment(), allocFloatArray(), error_exit, exit(), f, fdo_stats(), fits, fstatsrec::fmode, i, j, MAGIC, N1, N2, read2Dfloatimage(), fstatsrec::sigma, usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.