rfftb1.c
NAME
rfftb1.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int rfftb1_ (integer *n, real *c__, real *ch, real *wa, integer *ifac)
Function Documentation
int rfftb1_ (integer * n, real * c__, real * ch, real * wa, integer * ifac)
Definition at line 9 of file rfftb1.c.
References integer, n, nf, radb2_(), radb3_(), radb4_(), radb5_(), radbg_(), and real.
Referenced by rfftb_().
Author
Generated automatically by Doxygen for imcat from the source code.