.TH "rfftf.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rfftf.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrfftf_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *r__, \fBreal\fP *wsave)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int rfftf_ (\fBinteger\fP * n, \fBreal\fP * r__, \fBreal\fP * wsave)"
.PP
Definition at line 9 of file rfftf.c.
.PP
References integer, n, real, and rfftf1_().
.PP
Referenced by cosqf1_(), cost_(), ezfftf_(), forward_fft(), main(), and MAIN__().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
