.TH "rffti1.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rffti1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrffti1_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *wa, \fBinteger\fP *ifac)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int rffti1_ (\fBinteger\fP * n, \fBreal\fP * wa, \fBinteger\fP * ifac)"
.PP
Definition at line 9 of file rffti1.c.
.PP
References integer, j, n, nf, and real.
.PP
Referenced by rffti_().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
