rfftf1.c
NAME
rfftf1.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int rfftf1_ (integer *n, real *c__, real *ch, real *wa, integer *ifac)
Function Documentation
int rfftf1_ (integer * n, real * c__, real * ch, real * wa, integer * ifac)
Definition at line 9 of file rfftf1.c.
References integer, n, nf, radf2_(), radf3_(), radf4_(), radf5_(), radfg_(), and real.
Referenced by rfftf_(), and sint1_().
Author
Generated automatically by Doxygen for imcat from the source code.