.TH "rfftf1.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rfftf1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrfftf1_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *c__, \fBreal\fP *ch, \fBreal\fP *wa, \fBinteger\fP *ifac)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int rfftf1_ (\fBinteger\fP * n, \fBreal\fP * c__, \fBreal\fP * ch, \fBreal\fP * wa, \fBinteger\fP * ifac)"
.PP
Definition at line 9 of file rfftf1.c.
.PP
References integer, n, nf, radf2_(), radf3_(), radf4_(), radf5_(), radfg_(), and real.
.PP
Referenced by rfftf_(), and sint1_().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
