rffti.c
NAME
rffti.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int rffti_ (integer *n, real *wsave)
Function Documentation
int rffti_ (integer * n, real * wsave)
Definition at line 9 of file rffti.c.
References integer, n, real, and rffti1_().
Referenced by cosqi_(), costi_(), forward_fft(), inverse_fft(), main(), MAIN__(), and sinti_().
Author
Generated automatically by Doxygen for imcat from the source code.