rfftb.c
NAME
rfftb.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int rfftb_ (integer *n, real *r__, real *wsave)
Function Documentation
int rfftb_ (integer * n, real * r__, real * wsave)
Definition at line 9 of file rfftb.c.
References integer, n, real, and rfftb1_().
Referenced by cosqb1_(), ezfftb_(), inverse_fft(), main(), and MAIN__().
Author
Generated automatically by Doxygen for imcat from the source code.