rfftf.c
NAME
rfftf.c -
SYNOPSIS
#include <math.h>
#include 'f2c.h'
Functions
int rfftf_ (integer *n, real *r__, real *wsave)
Function Documentation
int rfftf_ (integer * n, real * r__, real * wsave)
Definition at line 9 of file rfftf.c.
References integer, n, real, and rfftf1_().
Referenced by cosqf1_(), cost_(), ezfftf_(), forward_fft(), main(), and MAIN__().
Author
Generated automatically by Doxygen for imcat from the source code.