.TH "rlft3.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rlft3.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrlft3\fP (float ***\fBdata\fP, float **speq, unsigned long nn1, unsigned long nn2, unsigned long nn3, int isign)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void rlft3 (float *** data, float ** speq, unsigned long nn1, unsigned long nn2, unsigned long nn3, int isign)"
.PP
Definition at line 3 of file rlft3.c.
.PP
References fourn(), and nrerror().
.PP
Referenced by forward_fft(), and inverse_fft().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
