rlft3.c
NAME
rlft3.c -
SYNOPSIS
#include <math.h>
Functions
void rlft3 (float ***data, float **speq, unsigned long nn1, unsigned long nn2, unsigned long nn3, int isign)
Function Documentation
void rlft3 (float *** data, float ** speq, unsigned long nn1, unsigned long nn2, unsigned long nn3, int isign)
Definition at line 3 of file rlft3.c.
References fourn(), and nrerror().
Referenced by forward_fft(), and inverse_fft().
Author
Generated automatically by Doxygen for imcat from the source code.