.TH "rpn.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rpn.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBrpnfunc\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBrpnfunc\fP \fBrpnfunc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrpnfunc\fP * \fBnewrpnfunction\fP (char *name, char *string)"
.br
.ti -1c
.RI "void \fBevalrpnfunction\fP (\fBrpnfunc\fP *thefunction)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBrpnfunc\fP   \fBrpnfunc\fP"
.PP
.SH "Function Documentation"
.PP 
.SS "void evalrpnfunction (\fBrpnfunc\fP * thefunction)"
.PP
Definition at line 48 of file rpn.c.
.PP
References GEN_OP_TYPE, genfunc(), item::itype, rpnfunc::name, item::name, item::next, rpnfunc::nop, NUM1_OP_TYPE, num1func(), NUM2_OP_TYPE, num2func(), NUM_TYPE, op, rpnfunc::oplist, pop(), push(), rpnfunc::result, and TEXT_TYPE.
.PP
Referenced by main(), parseheaderexpr(), and parsename().
.SS "\fBrpnfunc\fP* newrpnfunction (char * name, char * string)"
.PP
Definition at line 16 of file rpn.c.
.PP
References getop(), MAX_OPS, rpnfunc::name, rpnfunc::nop, op, and rpnfunc::oplist.
.PP
Referenced by main(), parseheaderexpr(), and parsename().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
