rpn.c
NAME
rpn.c -
SYNOPSIS
#include <stdio.h>
#include '../../catlib/cat.h'
#include 'getop.h'
#include 'stack.h'
#include 'operators.h'
#include 'rpn.h'
#include 'error.h'
Defines
#define MAX_OPS 1024
Functions
rpnfunc * newrpnfunction (char *name, char *string)
void evalrpnfunction (rpnfunc *therpnfunc)
Define Documentation
#define MAX_OPS 1024
Definition at line 14 of file rpn.c.
Referenced by main(), and newrpnfunction().
Function Documentation
void evalrpnfunction (rpnfunc * therpnfunc)
Definition at line 48 of file rpn.c.
References GEN_OP_TYPE, genfunc(), item::itype, item::name, rpnfunc::name, item::next, rpnfunc::nop, NUM1_OP_TYPE, num1func(), NUM2_OP_TYPE, num2func(), NUM_TYPE, op, rpnfunc::oplist, pop(), push(), rpnfunc::result, and TEXT_TYPE.
Referenced by main(), parseheaderexpr(), and parsename().
rpnfunc* newrpnfunction (char * name, char * string)
Definition at line 16 of file rpn.c.
References getop(), MAX_OPS, rpnfunc::name, rpnfunc::nop, op, and rpnfunc::oplist.
Referenced by main(), parseheaderexpr(), and parsename().
Author
Generated automatically by Doxygen for imcat from the source code.