rpn.h
NAME
rpn.h -
SYNOPSIS
Data Structures
struct rpnfunc
Typedefs
typedef rpnfunc rpnfunc
Functions
rpnfunc * newrpnfunction (char *name, char *string)
void evalrpnfunction (rpnfunc *thefunction)
Typedef Documentation
typedef struct rpnfunc rpnfunc
Function Documentation
void evalrpnfunction (rpnfunc * thefunction)
Definition at line 48 of file rpn.c.
References GEN_OP_TYPE, genfunc(), item::itype, rpnfunc::name, item::name, item::next, rpnfunc::nop, NUM1_OP_TYPE, num1func(), NUM2_OP_TYPE, num2func(), NUM_TYPE, op, rpnfunc::oplist, pop(), push(), rpnfunc::result, and TEXT_TYPE.
Referenced by main(), parseheaderexpr(), and parsename().
rpnfunc* newrpnfunction (char * name, char * string)
Definition at line 16 of file rpn.c.
References getop(), MAX_OPS, rpnfunc::name, rpnfunc::nop, op, and rpnfunc::oplist.
Referenced by main(), parseheaderexpr(), and parsename().
Author
Generated automatically by Doxygen for imcat from the source code.