.TH "rpnfunc" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rpnfunc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <rpn.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBnop\fP"
.br
.ti -1c
.RI "\fBitem\fP ** \fBoplist\fP"
.br
.ti -1c
.RI "\fBitem\fP * \fBresult\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* \fBrpnfunc::name\fP"
.PP
Definition at line 6 of file rpn.h.
.PP
Referenced by evalrpnfunction(), and newrpnfunction().
.SS "int \fBrpnfunc::nop\fP"
.PP
Definition at line 7 of file rpn.h.
.PP
Referenced by evalrpnfunction(), and newrpnfunction().
.SS "\fBitem\fP** \fBrpnfunc::oplist\fP"
.PP
Definition at line 8 of file rpn.h.
.PP
Referenced by evalrpnfunction(), and newrpnfunction().
.SS "\fBitem\fP* \fBrpnfunc::result\fP"
.PP
Definition at line 9 of file rpn.h.
.PP
Referenced by evalrpnfunction(), main(), and parseheaderexpr().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
