.TH "runcom.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
runcom.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <unistd.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\nNAME\\\fBn\fP\\        runcom - run \fBa\fP command for rshloop\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\        runcom comfile [-\fBv\fP]\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\        runcom reads \fBa\fP command from comfile and then executes it,\\\fBn\fP\\	capturing the stderr and stdout in temporary files\\\fBn\fP\\	/\fBtmp\fP/runcom.PID.stderr and /\fBtmp\fP/runcom.PID.stderr.\\\fBn\fP\\	It then sends those to stdout.\\\fBn\fP\\\\\fBn\fP\\SEE ALSO\\\fBn\fP\\        rshloop\\\fBn\fP\\AUTHOR\\\fBn\fP\\        Nick Kaiser --- kaiser@hawaii.edu\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\nNAME\\\fBn\fP\\        runcom - run \fBa\fP command for rshloop\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\        runcom comfile [-\fBv\fP]\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\        runcom reads \fBa\fP command from comfile and then executes it,\\\fBn\fP\\	capturing the stderr and stdout in temporary files\\\fBn\fP\\	/\fBtmp\fP/runcom.PID.stderr and /\fBtmp\fP/runcom.PID.stderr.\\\fBn\fP\\	It then sends those to stdout.\\\fBn\fP\\\\\fBn\fP\\SEE ALSO\\\fBn\fP\\        rshloop\\\fBn\fP\\AUTHOR\\\fBn\fP\\        Nick Kaiser --- kaiser@hawaii.edu\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 5 of file runcom.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 23 of file runcom.c.
.PP
References exit(), usage, and verbose.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
