scrunch.c
NAME
scrunch.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
#include '../imlib/scrunch_stuff.h'
Defines
#define usage '\n\n\n\NAME\n\	scrunch - demagnify image by factor 2\n\\n\SYNOPSIS\n\	scrunch [-m | -c]\n\		-m	# take median (mean is default)\n\		-c	# conservative mean\n\\n\DESCRIPTION\n\	Scrunches a fits image down by a factor 2.\n\	Works in stream processing mode.\n\	With -c option output is MAGIC if any of source pixels are MAGIC.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	scrunch - demagnify image by factor 2\n\\n\SYNOPSIS\n\	scrunch [-m | -c]\n\		-m	# take median (mean is default)\n\		-c	# conservative mean\n\\n\DESCRIPTION\n\	Scrunches a fits image down by a factor 2.\n\	Works in stream processing mode.\n\	With -c option output is MAGIC if any of source pixels are MAGIC.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file scrunch.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 31 of file scrunch.c.
References add_comment(), argsinit(), CMEAN, copyfitsheader(), error_exit, exit(), flag, getflag(), MEAN, MEDIAN, fitsheader::n, readfitsheader(), scrunch_stream(), usage, writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.