scrunch_stuff.c
NAME
scrunch_stuff.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'fits.h'
#include 'scrunch_stuff.h'
#include '../utils/error.h'
Functions
int xfloatcmp ()
void scrunch_stream (fitsheader *fitsin, fitsheader *fitsout, int mode)
int xfloatcmp (float *s1, float *s2)
Function Documentation
void scrunch_stream (fitsheader * fitsin, fitsheader * fitsout, int mode)
Definition at line 20 of file scrunch_stuff.c.
References CMEAN, error_exit, f, FLOAT_MAGIC, free(), i, j, k, MEAN, MEDIAN, fitsheader::n, readfitsline(), writefitsline(), and xfloatcmp().
Referenced by main().
int xfloatcmp (float * s1, float * s2)
Definition at line 101 of file scrunch_stuff.c.
int xfloatcmp ()
scrunch_stream
works in stream mode
tries to patch bad pixels
Referenced by scrunch_stream().
Author
Generated automatically by Doxygen for imcat from the source code.