scrunch_stuff.h
NAME
scrunch_stuff.h -
SYNOPSIS
Defines
#define MEAN 1
#define MEDIAN 2
#define CMEAN 3
Functions
void scrunch_stream (fitsheader *fitsin, fitsheader *fitsout, int mode)
Define Documentation
#define CMEAN 3
Definition at line 3 of file scrunch_stuff.h.
Referenced by main(), and scrunch_stream().
#define MEAN 1
Definition at line 1 of file scrunch_stuff.h.
Referenced by main(), and scrunch_stream().
#define MEDIAN 2
Definition at line 2 of file scrunch_stuff.h.
Referenced by main(), and scrunch_stream().
Function Documentation
void scrunch_stream (fitsheader * fitsin, fitsheader * fitsout, int mode)
Definition at line 20 of file scrunch_stuff.c.
References CMEAN, error_exit, f, FLOAT_MAGIC, free(), i, j, k, MEAN, MEDIAN, fitsheader::n, readfitsline(), writefitsline(), and xfloatcmp().
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.