setwcsinfo.c
NAME
setwcsinfo.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/error.h'
#include 'utils/args.h'
#include 'imlib/fits.h'
Defines
#define usage '\n\NAME\n\	setwcsinfo --- insert world coordinate system info into fits header\n\\n\SYNOPSIS\n\	setwcsinfo CTYPE1 CDELT1 CRVAL1 CRPIX1 CTYPE2 CDELT2 CRVAL2 CRPIX2 CROTA2 [-c | -p] [-e EPOCH EQUINOX]\n\\n\DESCRIPTION\n\	setwcsinfo reads a fits image from stdin, removes\n\	any existing WCS info; inserts new ones; and writes\n\	out the data.\n\\n\	Rotation angle CROTA2 must be given in degrees.\n\\n\	With -c option we encode the rotation and scaling in the CDn_m matrix. However,\n\	this practice is deprecated.\n\\n\	With -p option we encode the rotation angle in the PCnnnmmm matrix.\n\\n\	Refer to Greisen and Calabretta, 96 for description\n\	of FITS WCS convention.\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
#define NNAMES 32
#define CROTA2_ENCODING 0
#define CD_ENCODING 1
#define PC_ENCODING 2
Functions
main (int argc, char *argv[])
Define Documentation
#define CD_ENCODING 1
Definition at line 45 of file setwcsinfo.c.
Referenced by main().
#define CROTA2_ENCODING 0
Definition at line 44 of file setwcsinfo.c.
Referenced by main().
#define NNAMES 32
Definition at line 42 of file setwcsinfo.c.
Referenced by main().
#define PC_ENCODING 2
Definition at line 46 of file setwcsinfo.c.
Referenced by main().
#define usage '\n\NAME\n\	setwcsinfo --- insert world coordinate system info into fits header\n\\n\SYNOPSIS\n\	setwcsinfo CTYPE1 CDELT1 CRVAL1 CRPIX1 CTYPE2 CDELT2 CRVAL2 CRPIX2 CROTA2 [-c | -p] [-e EPOCH EQUINOX]\n\\n\DESCRIPTION\n\	setwcsinfo reads a fits image from stdin, removes\n\	any existing WCS info; inserts new ones; and writes\n\	out the data.\n\\n\	Rotation angle CROTA2 must be given in degrees.\n\\n\	With -c option we encode the rotation and scaling in the CDn_m matrix. However,\n\	this practice is deprecated.\n\\n\	With -p option we encode the rotation angle in the PCnnnmmm matrix.\n\\n\	Refer to Greisen and Calabretta, 96 for description\n\	of FITS WCS convention.\n\\n\AUTHOR\n\	Nick Kaiser	kaiser@hawaii.edu\n\\n\n'
Definition at line 5 of file setwcsinfo.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 48 of file setwcsinfo.c.
References argsinit(), c, CD_ENCODING, CROTA2_ENCODING, error_exit, exit(), fitsheader::extpixtype, f, fits, flag, FLAG_ARG, getargs(), getflag(), i, fitsheader::intpixtype, fitsheader::n, newnumericcomment(), newtextcomment(), nextargtype(), NNAMES, PC_ENCODING, pixsize(), prependcomment(), readfitsheader(), readfitsline(), removenamedcomments(), S, usage, writefitsheader(), writefitsline(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.