sheartogradkappa.c
NAME
sheartogradkappa.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include '../../imlib/fits.h'
#include '../../utils/arrays.h'
Defines
#define usage '\n\NAME\n\	sheartogradkappa --- calculate gradkappa image from shear image\n\\n\SYNOPSIS\n\	sheartogradkappa\n\\n\DESCRIPTION\n\	'sheartogradkappa' reads shear from a fits file on stdin and calculates\n\	grad - kappa which is sent to stdout\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	sheartogradkappa --- calculate gradkappa image from shear image\n\\n\SYNOPSIS\n\	sheartogradkappa\n\\n\DESCRIPTION\n\	'sheartogradkappa' reads shear from a fits file on stdin and calculates\n\	grad - kappa which is sent to stdout\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n'
Definition at line 5 of file sheartogradkappa.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 25 of file sheartogradkappa.c.
References add_comment(), allocFloatArray(), copyfitsheader(), exit(), gamma1(), gamma2(), i, j, fitsheader::n, N1, N2, readfitsheader(), readfitsline(), usage, writefitsheader(), writefitsline(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.