.TH "shmalloc.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shmalloc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/ipc.h>\fP
.br
\fC#include <sys/shm.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include 'shmalloc.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
