shmalloc.h
NAME
shmalloc.h -
SYNOPSIS
Functions
int shmalloc (void **addrptr, int size)
int shmfree (int shmid)
int allocFloatArray_shm (float ***fout, int N1, int N2)
Function Documentation
int allocFloatArray_shm (float *** fout, int N1, int N2)
Referenced by main().
int shmalloc (void ** addrptr, int size)
int shmfree (int shmid)
Referenced by forward_fft(), inverse_fft(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.