simulate.h
NAME
simulate.h -
SYNOPSIS
Functions
void add_noise (float **f, int N1, int N2, float sigma)
float gasdev (void)
float ran0 (void)
int make_pop (float A, float g, float lmin, float lnrbar, float lnrsig, float e, float mumin, int N1, int N2, float **f)
Function Documentation
void add_noise (float ** f, int N1, int N2, float sigma)
Definition at line 154 of file simulate.c.
References f, gasdev(), i, j, N1, N2, and sigma.
Referenced by main().
float gasdev (void)
Definition at line 607 of file ic.c.
References drand48(), r, and ran0().
int make_pop (float A, float g, float lmin, float lnrbar, float lnrsig, float e, float mumin, int N1, int N2, float ** f)
Definition at line 198 of file simulate.c.
References A, catfile, di, dj, drand48(), e, f, g(), gasdev(), i, j, l, LN_L_MAX, n, N1, N2, outputcat, phi, PI, r, x, and y.
Referenced by main().
float ran0 (void)
Referenced by gasdev().
Author
Generated automatically by Doxygen for imcat from the source code.