simulate.c
NAME
simulate.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'simulate.h'
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
#include '../imlib/filters.h'
#include '../utils/ran1.h'
Defines
#define usage '\n\n\n\NAME\n\	simulate --- generate mock fits image\n\\n\SYNOPSIS\n\	simulate [option...]\n\		-n N1 N2		# size of image (256, 256)\n\		-S As gs		# amp and slope of stellar lum fun (As = 3e-4; gs = -1.5)\n\		-G Ag gg		# amp and slope of galaxy lum fun (Ag = 1e-2; gg = -2)\n\		-R rbar lnrsig		# av and SD log-normal distn of galaxy sizes (rbar = 2.0; lnrsig = 0.3)\n\		-s sigma		# rms sky fluctuation (0)\n\		-i seed			# for ran num generator (1)\n\		-l lmin			# min luminosity (50)\n\		-e e			# global ellipticity (0.0)\n\		-m mumin		# min cos theta for galaxy inclination (0.5)\n\		-c catfile		# output object positions to an lc-format catalogue\n\\n\DESCRIPTION\n\	\'simulate\' generates a mock fits image\n\	Galaxies and stars have power law lum funs\n\	Galaxies lave log normal distn of sizes.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define LN_L_MAX 16
Functions
double drand48 ()
int main (int argc, char *argv[])
void add_noise (float **f, int N1, int N2, float sigma)
float gasdev (void)
int make_pop (float A, float g, float lmin, float lnrbar, float lnrsig, float e, float mumin, int N1, int N2, float **f)
Variables
FILE * catfile
int outputcat
Define Documentation
#define LN_L_MAX 16
Definition at line 189 of file simulate.c.
Referenced by make_pop().
#define usage '\n\n\n\NAME\n\	simulate --- generate mock fits image\n\\n\SYNOPSIS\n\	simulate [option...]\n\		-n N1 N2		# size of image (256, 256)\n\		-S As gs		# amp and slope of stellar lum fun (As = 3e-4; gs = -1.5)\n\		-G Ag gg		# amp and slope of galaxy lum fun (Ag = 1e-2; gg = -2)\n\		-R rbar lnrsig		# av and SD log-normal distn of galaxy sizes (rbar = 2.0; lnrsig = 0.3)\n\		-s sigma		# rms sky fluctuation (0)\n\		-i seed			# for ran num generator (1)\n\		-l lmin			# min luminosity (50)\n\		-e e			# global ellipticity (0.0)\n\		-m mumin		# min cos theta for galaxy inclination (0.5)\n\		-c catfile		# output object positions to an lc-format catalogue\n\\n\DESCRIPTION\n\	\'simulate\' generates a mock fits image\n\	Galaxies and stars have power law lum funs\n\	Galaxies lave log normal distn of sizes.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file simulate.c.
Function Documentation
void add_noise (float ** f, int N1, int N2, float sigma)
Definition at line 154 of file simulate.c.
References f, gasdev(), i, j, N1, N2, and sigma.
Referenced by main().
double drand48 ()
float gasdev (void)
Definition at line 167 of file simulate.c.
References drand48(), r, and ran0().
int main (int argc, char * argv[])
Definition at line 51 of file simulate.c.
References add_comment(), add_noise(), allocFloatArray(), catfile, e, error_exit, exit(), f, fits, FLOAT_PIXTYPE, make_pop(), N1, N2, new2Dfitsheader(), nstars, outputcat, rbar, sigma, usage, and write2Dfloatimage().
int make_pop (float A, float g, float lmin, float lnrbar, float lnrsig, float e, float mumin, int N1, int N2, float ** f)
Definition at line 198 of file simulate.c.
References A, catfile, di, dj, drand48(), e, f, g(), gasdev(), i, j, l, LN_L_MAX, n, N1, N2, outputcat, phi, PI, r, x, and y.
Referenced by main().
Variable Documentation
FILE* catfile
Definition at line 48 of file simulate.c.
Referenced by getobjects(), main(), and make_pop().
int outputcat
Definition at line 49 of file simulate.c.
Referenced by main(), and make_pop().
Author
Generated automatically by Doxygen for imcat from the source code.