.TH "sint1.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sint1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'f2c.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsint1_\fP (\fBinteger\fP *\fBn\fP, \fBreal\fP *war, \fBreal\fP *was, \fBreal\fP *xh, \fBreal\fP *x, \fBinteger\fP *ifac)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int sint1_ (\fBinteger\fP * n, \fBreal\fP * war, \fBreal\fP * was, \fBreal\fP * xh, \fBreal\fP * x, \fBinteger\fP * ifac)"
.PP
Definition at line 9 of file sint1.c.
.PP
References integer, k, n, real, rfftf1_(), and x.
.PP
Referenced by sint_().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
