.TH "sleeper.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sleeper.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <unistd.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\nNAME\\\fBn\fP\\	sleeper - sleep and then return stdout and stderr test messages\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	sleeper processid delay dostdout dostderr\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	sleeper sleeps for delay seconds.  Then, if dostdout is\\\fBn\fP\\	non zero, it sends to stdout the message\\\fBn\fP\\		# stdout from procid processid\\\fBn\fP\\	If dostderr is non-zero it sends to stderr, the string\\\fBn\fP\\		# stderr from procid processid\\\fBn\fP\\	If dostderr is greater than 1 it exits with failure\\\fBn\fP\\	status, otherwise it returns with success status.\\\fBn\fP\\\\\fBn\fP\\SEE ALSO\\\fBn\fP\\	rshloop runcom\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser --- kaiser@hawaii.edu\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\nNAME\\\fBn\fP\\	sleeper - sleep and then return stdout and stderr test messages\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	sleeper processid delay dostdout dostderr\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	sleeper sleeps for delay seconds.  Then, if dostdout is\\\fBn\fP\\	non zero, it sends to stdout the message\\\fBn\fP\\		# stdout from procid processid\\\fBn\fP\\	If dostderr is non-zero it sends to stderr, the string\\\fBn\fP\\		# stderr from procid processid\\\fBn\fP\\	If dostderr is greater than 1 it exits with failure\\\fBn\fP\\	status, otherwise it returns with success status.\\\fBn\fP\\\\\fBn\fP\\SEE ALSO\\\fBn\fP\\	rshloop runcom\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser --- kaiser@hawaii.edu\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 4 of file sleeper.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 26 of file sleeper.c.
.PP
References exit(), and usage.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
