sliceimage.c
NAME
sliceimage.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	sliceimage - cut a 2-D FITS image into a grid of sub-sections\n\\n\SYNOPSIS\n\	sliceimage [-u] [-i] [-l] nx ny\n\\n\DESCRIPTION\n\	In its default mode, sliceimage reads a 2D image fin[N2][N1], whose fast\n\	dimension N1 must be a multiple of nx and whose slow index\n\	N2 must be a multiple of ny, from stdin and sends to stdout\n\	a 4-D image fout[ny][nx][N2/ny][N1/nx] such that\n\\n\		fout[y][x][Y][X] = fin[y * N2 / ny + Y][x + N1 / nx + X]\t\n\\n\	This slices a single image into a grid of contiguous patches.\n\\n\	With -i option it performs the inverse operation. The arguments\n\	nx and ny are ignored.\n\\n\	With -l option it outputs instead a 3-dimensional image\n\\n\		fout[y * nx + x][Y][X] = fin[y * N2 / ny + Y][x + N1 / nx + X]\t\n\\n\	and writes nx and ny to the FITS header as SLICE_NX and SLICE_NY.\n\\n\	With -u option it sends this man page to stderr and exits\n\	with abnormal status.\n\\n\SEE ALSO\n\	flatten(1), getplane(1), getplanes(1), stackplanes(1).\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	sliceimage - cut a 2-D FITS image into a grid of sub-sections\n\\n\SYNOPSIS\n\	sliceimage [-u] [-i] [-l] nx ny\n\\n\DESCRIPTION\n\	In its default mode, sliceimage reads a 2D image fin[N2][N1], whose fast\n\	dimension N1 must be a multiple of nx and whose slow index\n\	N2 must be a multiple of ny, from stdin and sends to stdout\n\	a 4-D image fout[ny][nx][N2/ny][N1/nx] such that\n\\n\		fout[y][x][Y][X] = fin[y * N2 / ny + Y][x + N1 / nx + X]\t\n\\n\	This slices a single image into a grid of contiguous patches.\n\\n\	With -i option it performs the inverse operation. The arguments\n\	nx and ny are ignored.\n\\n\	With -l option it outputs instead a 3-dimensional image\n\\n\		fout[y * nx + x][Y][X] = fin[y * N2 / ny + Y][x + N1 / nx + X]\t\n\\n\	and writes nx and ny to the FITS header as SLICE_NX and SLICE_NY.\n\\n\	With -u option it sends this man page to stderr and exits\n\	with abnormal status.\n\\n\SEE ALSO\n\	flatten(1), getplane(1), getplanes(1), stackplanes(1).\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file sliceimage.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 47 of file sliceimage.c.
References add_comment(), appendcomment(), argsinit(), dx, dy, error_exit, exit(), fitsheader::extpixtype, f, fits, flag, FLAG_ARG, free(), getargi(), getcommentbyname(), getflag(), getnumericvalue(), ix, l, fitsheader::n, fitsheader::ndim, newnumericcomment(), nextargtype(), nx, NX, ny, NY, pixsize(), readfitsheader(), removenamedcomments(), usage, writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.