sm_stuff.h
NAME
sm_stuff.h -
SYNOPSIS
Functions
void smcontour (float **f, int N1, int N2, int df, int nplus, int nminus, int comc, char *comv[])
void smprofile (float **f, int N1, int N2, int ic, int jc)
Function Documentation
void smcontour (float ** f, int N1, int N2, int df, int nplus, int nminus, int comc, char * comv[])
Definition at line 27 of file sm_stuff.c.
References error_exit, f, fits, FLOAT_PIXTYPE, i, j, N1, N2, new2Dfitsheader(), and write2Dfloatimage().
void smprofile (float ** f, int N1, int N2, int ic, int jc)
Definition at line 78 of file sm_stuff.c.
References error_exit, exit(), f, FLOAT_MAGIC, i, j, MAX, N1, N2, and sigma.
Author
Generated automatically by Doxygen for imcat from the source code.