sm_stuff.c
NAME
sm_stuff.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'fits.h'
Defines
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
Functions
void smcontour (float **f, int N1, int N2, int df, int nplus, int nminus, int comc, char *comv[])
void smprofile (float **f, int N1, int N2, int ic, int jc)
Define Documentation
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
Definition at line 18 of file sm_stuff.c.
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
Definition at line 19 of file sm_stuff.c.
Function Documentation
void smcontour (float ** f, int N1, int N2, int df, int nplus, int nminus, int comc, char * comv[])
Definition at line 27 of file sm_stuff.c.
References error_exit, f, fits, FLOAT_PIXTYPE, i, j, N1, N2, new2Dfitsheader(), and write2Dfloatimage().
void smprofile (float ** f, int N1, int N2, int ic, int jc)
Definition at line 78 of file sm_stuff.c.
References error_exit, exit(), f, FLOAT_MAGIC, i, j, MAX, N1, N2, and sigma.
Author
Generated automatically by Doxygen for imcat from the source code.