smooth.c
NAME
smooth.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../imlib/filters.h'
#include '../utils/arrays.h'
#include '../fftlib/myfft.h'
Defines
#define usage '\n\NAME\n\	smooth --- spatially filter a fits image\n\\n\SYNOPSIS\n\	smooth [option...]\n\\n\DESCRIPTION\n\	'smooth' reads a fits image from standard input and writes a\n\	smoothed version to standard output.\n\\n\	Various types of smoothing are provided:\n\		-k	m rf		# smooth with m x m gaussian kernel\n\		-b 	m		# m x m box filter\n\		-t 			# tukey-style running median\n\		-f 	a s1 s2		# fft filter (1+k^2 s1^2)^-a/2 exp(-0.5 k^2 s2^2)\n\		-g	a b phi		# gaussian: major/minor = a/b, pos angle phi [deg]\n\		-K	r		# fft kolmogorov turb: exp(-0.5 (k r)^(5/3))\n\		-p	alpha		# power law: transfer function = k^(alpha)\n\		-e	r gamma		# generalized exponential: exp(-(k r)^gamma)\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
#define SCHECHTERFILTER 0
#define GAUSSFILTER 1
#define KOLMOGOROVFILTER 2
#define POWERLAWFILTER 3
#define EXPONENTIALFILTER 4
#define MAGIC FLOAT_MAGIC
Functions
main (int argc, char *argv[])
Define Documentation
#define EXPONENTIALFILTER 4
Definition at line 45 of file smooth.c.
Referenced by main().
#define GAUSSFILTER 1
Definition at line 42 of file smooth.c.
Referenced by main().
#define KOLMOGOROVFILTER 2
Definition at line 43 of file smooth.c.
Referenced by main().
#define MAGIC FLOAT_MAGIC
Definition at line 47 of file smooth.c.
#define POWERLAWFILTER 3
Definition at line 44 of file smooth.c.
Referenced by main().
#define SCHECHTERFILTER 0
Definition at line 41 of file smooth.c.
Referenced by main().
#define usage '\n\NAME\n\	smooth --- spatially filter a fits image\n\\n\SYNOPSIS\n\	smooth [option...]\n\\n\DESCRIPTION\n\	'smooth' reads a fits image from standard input and writes a\n\	smoothed version to standard output.\n\\n\	Various types of smoothing are provided:\n\		-k	m rf		# smooth with m x m gaussian kernel\n\		-b 	m		# m x m box filter\n\		-t 			# tukey-style running median\n\		-f 	a s1 s2		# fft filter (1+k^2 s1^2)^-a/2 exp(-0.5 k^2 s2^2)\n\		-g	a b phi		# gaussian: major/minor = a/b, pos angle phi [deg]\n\		-K	r		# fft kolmogorov turb: exp(-0.5 (k r)^(5/3))\n\		-p	alpha		# power law: transfer function = k^(alpha)\n\		-e	r gamma		# generalized exponential: exp(-(k r)^gamma)\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file smooth.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 49 of file smooth.c.
References A, a, add_comment(), allocFloatArray(), B, block_filter(), error_exit, exit(), exponentialfilter(), EXPONENTIALFILTER, f, ff, fits, gaussfilter(), GAUSSFILTER, gaussian_kernel_filter(), i, j, kolmogorovfilter(), KOLMOGOROVFILTER, MAGIC, N1, N2, phi, powerlawfilter(), POWERLAWFILTER, read2Dfloatimage(), read2Dfloatimage_shm(), SCHECHTERFILTER, schecterfilter(), shmfree(), tukey(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.