smpopup.h
NAME
smpopup.h -
SYNOPSIS
Functions
void smpopup (void(*drawfn)(void), void(*cursorfn)(float x, float y, int key), char *geomstring)
void drawfn (void)
void cursorfn (float x, float y, int key)
Function Documentation
void cursorfn (float x, float y, int key)
Definition at line 225 of file smselect.c.
References drawfn(), drawselectionbox(), key, smx1, smx2, smy1, smy2, x, and y.
Referenced by smpopup().
void drawfn (void)
Definition at line 210 of file smselect.c.
References smN, smx, smxlim1, smxlim2, smxname, smy, smylim1, smylim2, and smyname.
void smpopup (void(* drawfn)(void), void(* cursorfn)(float x, float y, int key), char * geomstring)
Definition at line 20 of file smpopup.c.
References cursorfn(), drawfn(), key, x, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.