smpopup.c
NAME
smpopup.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include 'smpopup.h'
Functions
void smpopup (void(*drawfn)(void), void(*cursorfn)(float x, float y, int key), char *geomstring)
Function Documentation
void smpopup (void(* drawfn)(void), void(* cursorfn)(float x, float y, int key), char * geomstring)
Definition at line 20 of file smpopup.c.
References cursorfn(), drawfn(), key, x, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.