.TH "smpopup.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
smpopup.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'smpopup.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsmpopup\fP (void(*drawfn)(void), void(*cursorfn)(float x, float y, int \fBkey\fP), char *geomstring)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void smpopup (void(* drawfn)(void), void(* cursorfn)(float x, float y, int \fBkey\fP), char * geomstring)"
.PP
Definition at line 20 of file smpopup.c.
.PP
References cursorfn(), drawfn(), key, x, and y.
.PP
Referenced by main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
