smtest.c
NAME
smtest.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include '../utils/smpopup.h'
Functions
main ()
void drawfn (void)
void cursorfn (float x, float y, int key)
Function Documentation
void cursorfn (float x, float y, int key)
Definition at line 24 of file smtest.c.
References drawfn(), drawselectionbox(), key, smx1, smx2, smy1, smy2, x, and y.
Referenced by smpopup().
void drawfn (void)
Definition at line 14 of file smtest.c.
References smN, smx, smxlim1, smxlim2, smxname, smy, smylim1, smylim2, and smyname.
main ()
Definition at line 9 of file smtest.c.
References cursorfn(), drawfn(), and smpopup().
Author
Generated automatically by Doxygen for imcat from the source code.