.TH "sortobject" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sortobject \- 
.SH SYNOPSIS
.br
.PP
\fC#include <lc.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBobject\fP * \fBobj\fP"
.br
.ti -1c
.RI "double \fBsortval\fP"
.br
.ti -1c
.RI "\fBsortobject\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBsortobject\fP* \fBsortobject::next\fP"
.PP
Definition at line 8 of file lc.h.
.PP
Referenced by main().
.SS "\fBobject\fP* \fBsortobject::obj\fP"
.PP
Definition at line 6 of file lc.h.
.PP
Referenced by main().
.SS "double \fBsortobject::sortval\fP"
.PP
Definition at line 7 of file lc.h.
.PP
Referenced by main().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
