spinflip.c
NAME
spinflip.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	spinflip - apply 90 degree rotations or parity flips to FITS image\n\\n\SYNOPSIS\n\	spinflip mii mij mji mjj\n\\n\DESCRIPTION\n\	\'spinflip\' reflects images or rotates them through multiples\n\	of 90 degrees according to\n\		di' = Mii * di + Mij * dj\n\		dj' = Mji * di + Mjj * dj\n\	with matrix elements M = -1, 0, 1 and with the constraint\n\		Mii^2 + Mij^2 = Mji^2 + Mjj^2 = 1\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	spinflip - apply 90 degree rotations or parity flips to FITS image\n\\n\SYNOPSIS\n\	spinflip mii mij mji mjj\n\\n\DESCRIPTION\n\	\'spinflip\' reflects images or rotates them through multiples\n\	of 90 degrees according to\n\		di' = Mii * di + Mij * dj\n\		dj' = Mji * di + Mjj * dj\n\	with matrix elements M = -1, 0, 1 and with the constraint\n\		Mii^2 + Mij^2 = Mji^2 + Mjj^2 = 1\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file spinflip.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 30 of file spinflip.c.
References add_comment(), allocFloatArray(), error_exit, exit(), fits, i, j, N, N1, N2, read2Dfloatimage(), usage, and write2Dfloatimage().
Author
Generated automatically by Doxygen for imcat from the source code.