.TH "splaynode" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
splaynode \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtriedge\fP \fBkeyedge\fP"
.br
.ti -1c
.RI "\fBpoint\fP \fBkeydest\fP"
.br
.ti -1c
.RI "\fBsplaynode\fP * \fBlchild\fP"
.br
.ti -1c
.RI "\fBsplaynode\fP * \fBrchild\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBpoint\fP \fBsplaynode::keydest\fP"
.PP
Definition at line 566 of file triangle.c.
.SS "struct \fBtriedge\fP \fBsplaynode::keyedge\fP"
.PP
Definition at line 565 of file triangle.c.
.SS "struct \fBsplaynode\fP* \fBsplaynode::lchild\fP"
.PP
Definition at line 567 of file triangle.c.
.SS "struct \fBsplaynode\fP * \fBsplaynode::rchild\fP"
.PP
Definition at line 567 of file triangle.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
