stackpsfs.c
NAME
stackpsfs.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'utils/error.h'
#include 'utils/arrays.h'
#include 'utils/args.h'
#include 'imlib/fits.h'
Defines
#define usage '\n\NAME\n\	stackpsfs --- read a fits stream of PSFs and average after recentering\n\\n\SYNOPSIS\n\	stackpsfs [-n nplanes]\n\\n\DESCRIPTION\n\\n\	stackpsfs reads a fits stream of PSFs and averages after recentering.\n\	It generates a 4 x N2 x N1 image consiting of 4 image planes:\n\		0	# straight average\n\		1	# center on centroid\n\		2	# center on g^2 wighted centoid\n\		3	# center on peak\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
Functions
int shiftandadd (int dx, int dy, float **fsrc, int N, float **fdst)
main (int argc, char *argv[])
Define Documentation
#define usage '\n\NAME\n\	stackpsfs --- read a fits stream of PSFs and average after recentering\n\\n\SYNOPSIS\n\	stackpsfs [-n nplanes]\n\\n\DESCRIPTION\n\\n\	stackpsfs reads a fits stream of PSFs and averages after recentering.\n\	It generates a 4 x N2 x N1 image consiting of 4 image planes:\n\		0	# straight average\n\		1	# center on centroid\n\		2	# center on g^2 wighted centoid\n\		3	# center on peak\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\\n\n'
Definition at line 14 of file stackpsfs.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 37 of file stackpsfs.c.
References add_comment(), allocFloatArray(), argsinit(), error_exit, exit(), fits, flag, g(), getargi(), getflag(), ix, fitsheader::n, N, fitsheader::ndim, readfitsheader(), readfitsplane(), shiftandadd(), usage, writefitsheader(), writefitsplane(), and writefitstail().
int shiftandadd (int dx, int dy, float ** fsrc, int N, float ** fdst)
Definition at line 142 of file stackpsfs.c.
References dx, dy, N, x, xp(), y, and yp().
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.