stackplanes.c
NAME
stackplanes.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	stackplanes --- concatenate a set of fits files to multidimensional image\n\\n\SYNOPSIS\n\	stackplanes fits1 fits2...\n\	stackplanes nplanes\n\\n\DESCRIPTION\n\	In the first invocation form (with 2 or more arguments)\n\	\'stackplanes\' reads a set of N-dimensional images from\n\	the files given as arguments and sends to stdout a single\n\	(N+1)-dimensional fits images whose planes are the input\n\	images.\n\\n\	In the second invocation form, \'stackplanes\' reads a\n\	single N-dimensional fits image, whose slowest dimension\n\	must be an integral multiple of nplanes, from stdin and\n\	generates a N+1 dimensional image whose planes are simply\n\	concatenated in the input image.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	stackplanes --- concatenate a set of fits files to multidimensional image\n\\n\SYNOPSIS\n\	stackplanes fits1 fits2...\n\	stackplanes nplanes\n\\n\DESCRIPTION\n\	In the first invocation form (with 2 or more arguments)\n\	\'stackplanes\' reads a set of N-dimensional images from\n\	the files given as arguments and sends to stdout a single\n\	(N+1)-dimensional fits images whose planes are the input\n\	images.\n\\n\	In the second invocation form, \'stackplanes\' reads a\n\	single N-dimensional fits image, whose slowest dimension\n\	must be an integral multiple of nplanes, from stdin and\n\	generates a N+1 dimensional image whose planes are simply\n\	concatenated in the input image.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file stackplanes.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 35 of file stackplanes.c.
References add_comment(), copyfitsheader(), error_exit, exit(), fitsheader::extpixtype, f, free(), good, fitsheader::ipstream, line, fitsheader::n, fitsheader::ndim, fitsheader::opstream, pixsize(), readfitsheader(), usage, writefitsheader(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.