.TH "statobj" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statobj \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float * \fBf\fP"
.br
.ti -1c
.RI "\fBstatobj\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float* \fBstatobj::f\fP"
.PP
Definition at line 92 of file catstats.c.
.PP
Referenced by main().
.SS "struct \fBstatobj\fP* \fBstatobj::next\fP"
.PP
Definition at line 93 of file catstats.c.
.PP
Referenced by main().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
