stats_stuff.c
NAME
stats_stuff.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'stats_stuff.h'
#include 'error.h'
#include 'ran1.h'
#include '../imlib/fits.h'
Defines
#define good(x) (x != SHRT_MIN && x != SHRT_MAX && x != SHORT_MAGIC)
#define fgood(x) (x != FLOAT_MAGIC)
#define DEFSAMPLEFRAC 0.1
#define HUGE_VAL 1.0e20
#define MAX_SAMPLE_SIZE 10000
#define BINS 1000
#define SIG_FACTOR 1.0
#define BIG_FACTOR 4
Functions
double drand48 ()
void fdo_stats (float **f, int N1, int N2, int margin, fstatsrec *srec)
int liststats (float *fsample, int samplesize, float *medianptr, float *lquartptr, float *uquartptr, float *sigmaptr)
int floatcmp (float *f1, float *f2)
int findmode (float **f, int N1, int N2, float lquart, float uquart, float *mode, float *flquart)
Define Documentation
#define BIG_FACTOR 4
Definition at line 171 of file stats_stuff.c.
Referenced by findmode().
#define BINS 1000
Definition at line 169 of file stats_stuff.c.
Referenced by findmode().
#define DEFSAMPLEFRAC 0.1
Definition at line 40 of file stats_stuff.c.
Referenced by fdo_stats().
#define fgood(x) (x != FLOAT_MAGIC)
Definition at line 36 of file stats_stuff.c.
Referenced by fdo_stats().
#define good(x) (x != SHRT_MIN && x != SHRT_MAX && x != SHORT_MAGIC)
routines for calulating statistics of fields:
mostly straightforward 'cept for the mode & sigma where we first make a crude estimate of the mode as the most frequently occuring value and estimate sigma from sub-mode f values. We then refine this by making a least squares fit to the mode ± sigma / 2 region
aug 4th '92: revised fdo_stats now estimates quartiles and median from a random sample calculates sigma from width of inner 25 percent range Fri Aug 7 09:29:37 EDT 1992 do_stats also converted to sampling technique mode determined by smoothed histogram method incorporates findmode() - formerly in analyse.c general purpose routine liststats() to return mode, medians, quartiles from an unsorted list.
Tue Nov 25 11:21:48 HST 2003 fixed the mean bug in fdo_stats Definition at line 35 of file stats_stuff.c.
Referenced by main().
#define HUGE_VAL 1.0e20
Definition at line 41 of file stats_stuff.c.
Referenced by fdo_stats().
#define MAX_SAMPLE_SIZE 10000
Definition at line 42 of file stats_stuff.c.
Referenced by fdo_stats().
#define SIG_FACTOR 1.0
Definition at line 170 of file stats_stuff.c.
Referenced by findmode().
Function Documentation
double drand48 ()
void fdo_stats (float ** f, int N1, int N2, int margin, fstatsrec * srec)
Definition at line 48 of file stats_stuff.c.
References fstatsrec::badpix, DEFSAMPLEFRAC, f, fgood, findmode(), fstatsrec::flowerquartile, fstatsrec::fmax, fstatsrec::fmean, fstatsrec::fmedian, fmin, fstatsrec::fmin, fstatsrec::fmode, free(), fstatsrec::fupperquartile, fstatsrec::goodpix, HUGE_VAL, i, j, liststats(), MAX_SAMPLE_SIZE, median(), N1, N2, fstatsrec::samplesize, sigma, and fstatsrec::sigma.
Referenced by main().
int findmode (float ** f, int N1, int N2, float lquart, float uquart, float * mode, float * flquart)
Definition at line 184 of file stats_stuff.c.
References b, BIG_FACTOR, BINS, f, fmin, free(), i, j, N1, N2, and SIG_FACTOR.
Referenced by fdo_stats(), and main().
int floatcmp (float * f1, float * f2)
Definition at line 164 of file stats_stuff.c.
int liststats (float * fsample, int samplesize, float * medianptr, float * lquartptr, float * uquartptr, float * sigmaptr)
Definition at line 133 of file stats_stuff.c.
References floatcmp(), median(), and sigma.
Referenced by dosky(), fdo_stats(), getsky(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.