stats_stuff.h
NAME
stats_stuff.h -
SYNOPSIS
Data Structures
struct fstatsrec
Typedefs
typedef fstatsrec fstatsrec
Functions
void fdo_stats (float **f, int N1, int N2, int margin, fstatsrec *fsrec)
int liststats (float *fsample, int samplesize, float *median, float *lquart, float *uquart, float *sigma)
int findmode (float **f, int N1, int N2, float lquart, float uquart, float *mode, float *flquart)
Typedef Documentation
typedef struct fstatsrec fstatsrec
Function Documentation
void fdo_stats (float ** f, int N1, int N2, int margin, fstatsrec * fsrec)
Definition at line 48 of file stats_stuff.c.
References fstatsrec::badpix, DEFSAMPLEFRAC, f, fgood, findmode(), fstatsrec::flowerquartile, fstatsrec::fmax, fstatsrec::fmean, fstatsrec::fmedian, fstatsrec::fmin, fmin, fstatsrec::fmode, free(), fstatsrec::fupperquartile, fstatsrec::goodpix, HUGE_VAL, i, j, liststats(), MAX_SAMPLE_SIZE, median(), N1, N2, fstatsrec::samplesize, fstatsrec::sigma, and sigma.
Referenced by main().
int findmode (float ** f, int N1, int N2, float lquart, float uquart, float * mode, float * flquart)
Definition at line 184 of file stats_stuff.c.
References b, BIG_FACTOR, BINS, f, fmin, free(), i, j, N1, N2, and SIG_FACTOR.
Referenced by fdo_stats(), and main().
int liststats (float * fsample, int samplesize, float * median, float * lquart, float * uquart, float * sigma)
Definition at line 133 of file stats_stuff.c.
References floatcmp(), median(), and sigma.
Referenced by dosky(), fdo_stats(), getsky(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.