stats.c
NAME
stats.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../utils/stats_stuff.h'
#include '../utils/error.h'
#include '../utils/arrays.h'
#include '../imlib/fits.h'
Defines
#define usage '\n\n\n\NAME\n\	stats -- calculate simple statistics for an image\n\\n\SYNOPSIS\n\	stats 	[option...]\n\		-m n	# ignore outer n pixel margin (def = 0)\n\		-v stat	# just output value for 'stat', which\n\			can be one of:\n\			N1 N2 pixtype min max mean mode median\n\			lquart uquart sigma\n\\n\DESCRIPTION\n\	\'stats\' reads a 2-D fits file from stdin\n\	and writes the descriptive statistics listed above to stdout.\n\	Mode, sigma are computed as described in the 'catstats' man\n\	page.\n\\n\	If stats is given an image of dimensionality 3 then\n\	it will generate a lc-format output giving the stats\n\	for the NAXIS3 planes (each of size NAXIS2 x NAXIS1)\n\	and with an index 'i = 0 ... NAXIS3 - 1' giving the plane number.\n\	With an image of dimensionality 4 it generates statistics\n\	for the NAXIS4 x NAXIS3 planes, and the index i becomes\n\	a 2-vector with i[0] = 0...NAXIS3-1, i[1] = 0...NAXIS4-1,\n\	and similarly for higher dimensions.\n\\n\SEE ALSO\n\	catstats(1)\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	stats -- calculate simple statistics for an image\n\\n\SYNOPSIS\n\	stats 	[option...]\n\		-m n	# ignore outer n pixel margin (def = 0)\n\		-v stat	# just output value for 'stat', which\n\			can be one of:\n\			N1 N2 pixtype min max mean mode median\n\			lquart uquart sigma\n\\n\DESCRIPTION\n\	\'stats\' reads a 2-D fits file from stdin\n\	and writes the descriptive statistics listed above to stdout.\n\	Mode, sigma are computed as described in the 'catstats' man\n\	page.\n\\n\	If stats is given an image of dimensionality 3 then\n\	it will generate a lc-format output giving the stats\n\	for the NAXIS3 planes (each of size NAXIS2 x NAXIS1)\n\	and with an index 'i = 0 ... NAXIS3 - 1' giving the plane number.\n\	With an image of dimensionality 4 it generates statistics\n\	for the NAXIS4 x NAXIS3 planes, and the index i becomes\n\	a 2-vector with i[0] = 0...NAXIS3-1, i[1] = 0...NAXIS4-1,\n\	and similarly for higher dimensions.\n\\n\SEE ALSO\n\	catstats(1)\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
calculate simple statistics for an image Definition at line 7 of file stats.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 52 of file stats.c.
References allocFloatArray(), fstatsrec::badpix, error_exit, exit(), fitsheader::extpixtype, f, fdo_stats(), fits, fstatsrec::flowerquartile, fstatsrec::fmax, fstatsrec::fmean, fstatsrec::fmedian, fstatsrec::fmin, fstatsrec::fmode, fstatsrec::fupperquartile, fstatsrec::goodpix, i, j, MAX_FITS_DIM, fitsheader::n, N1, N2, fitsheader::ndim, readfitsheader(), readfitsplane(), fstatsrec::samplesize, fstatsrec::sigma, and usage.
Author
Generated automatically by Doxygen for imcat from the source code.