surfdens.c
NAME
surfdens.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../../utils/error.h'
#include '../../imlib/fits.h'
#include '../../utils/arrays.h'
Defines
#define usage '\n\n\n\NAME\n\	surfdens --- generate a fits image from a catalogue\n\\n\SYNOPSIS\n\	surfdens [option...]\n\		-x xname		# name for position vector ('x')\n\		-r x1 x2 y1 y2		# range of coordinates\n\		-n N1 N2		# image size in pixels\n\		-w weight		# weight points by this value\n\		-s 			# generate 16 bit image\n\		-d 			# print input lc filter string an quit\n\		-m			# set points to MAGIC value\n\		-f fitsfile		# supply source image\n\\n\DESCRIPTION\n\	\'surfdens\' reads a catalogue from stdin and calculates\n\	a surface density map by binning counts onto an image.\n\	By default it looks for 2-vector entry 'x', gets the image size\n\	from the catalogue header, sets the range of\n\	coordinates to be 0-N1, 0-N2, and uses unit weight per object.\n\	Specify name for weight with -w option.\n\	Fits image is output to stdout.\n\\n\	With the -m option, occupied pixels are set to MAGIC value and\n\	-w option, if present, is ignored.\n\\n\	With the -f option we initialise the image to 'fitsfile' and\n\	the -n and -s options, if present, are ignored (the output image\n\	inheriting the pixel type of the source image.\n\\n\NOTES\n\	If you want to use an rpn expression in the input lc filter\n\	you will need to double quote it. E.g.:\n\		surfdens -w \''w = %%x[0]'\'\n\	to get a weight proportional to x-position.\n\	To use a pair of scalar catalogue object values do e.g.:\n\		surfdens -x 'fs nu'.\n\\n\	See also 'makedensity' which can handle arbitrary dimension\n\	FITS file and position variables.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAGIC FLOAT_MAGIC
Functions
main (int argc, char *argv[])
Define Documentation
#define MAGIC FLOAT_MAGIC
Definition at line 57 of file surfdens.c.
#define usage '\n\n\n\NAME\n\	surfdens --- generate a fits image from a catalogue\n\\n\SYNOPSIS\n\	surfdens [option...]\n\		-x xname		# name for position vector ('x')\n\		-r x1 x2 y1 y2		# range of coordinates\n\		-n N1 N2		# image size in pixels\n\		-w weight		# weight points by this value\n\		-s 			# generate 16 bit image\n\		-d 			# print input lc filter string an quit\n\		-m			# set points to MAGIC value\n\		-f fitsfile		# supply source image\n\\n\DESCRIPTION\n\	\'surfdens\' reads a catalogue from stdin and calculates\n\	a surface density map by binning counts onto an image.\n\	By default it looks for 2-vector entry 'x', gets the image size\n\	from the catalogue header, sets the range of\n\	coordinates to be 0-N1, 0-N2, and uses unit weight per object.\n\	Specify name for weight with -w option.\n\	Fits image is output to stdout.\n\\n\	With the -m option, occupied pixels are set to MAGIC value and\n\	-w option, if present, is ignored.\n\\n\	With the -f option we initialise the image to 'fitsfile' and\n\	the -n and -s options, if present, are ignored (the output image\n\	inheriting the pixel type of the source image.\n\\n\NOTES\n\	If you want to use an rpn expression in the input lc filter\n\	you will need to double quote it. E.g.:\n\		surfdens -w \''w = %%x[0]'\'\n\	to get a weight proportional to x-position.\n\	To use a pair of scalar catalogue object values do e.g.:\n\		surfdens -x 'fs nu'.\n\\n\	See also 'makedensity' which can handle arbitrary dimension\n\	FITS file and position variables.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file surfdens.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 60 of file surfdens.c.
References add_comment(), allocFloatArray(), error_exit, exit(), f, fits, FLOAT_PIXTYPE, ix, lcpipe, line, MAGIC, N1, N2, new2Dfitsheader(), read2Dfloatimage(), SHORT_PIXTYPE, usage, w, write2Dfloatimage(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.