surfaceplot.c
NAME
surfaceplot.c -
SYNOPSIS
#include 'stdio.h'
#include 'tonry3d.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include 'psutils.h'
Functions
int surfaceplot (fitsheader *fits, float width, float height, float alt, float az, float zfac, float zoff)
int mgoline_ (float *x1, float *y1, float *x2, float *y2)
Function Documentation
int mgoline_ (float * x1, float * y1, float * x2, float * y2)
Definition at line 17 of file surfaceplot.c.
References psline().
Referenced by mgonxtvu_().
int surfaceplot (fitsheader * fits, float width, float height, float alt, float az, float zfac, float zoff)
Definition at line 7 of file surfaceplot.c.
References allocFloatArray(), f, fits, mgoplt3d_(), fitsheader::n, and readfitsplane().
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.