tablesort.c
NAME
tablesort.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
Data Structures
struct thing
Defines
#define usage '\n\n\n\NAME\n\	tablesort --- sort a table of numbers\n\SYNOPSIS\n\	tablesort	col\n\DESCRIPTION\n\		tablesort read lines of a table from stdin\n\		lines beginning with \'#\' and empty lines are ignored\n\		lines sorted in ascending order of colth column values.\n\		negative column number for descending order\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
#define MAX_LINE_LENGTH 4096
#define MAX_COLS 32
#define MAX_WORD_LENGTH 128
Typedefs
typedef thing thing
Functions
main (int argc, char *argv[])
int install (double x, thing *thething)
int writeasc (thing *thething)
int writedesc (thing *thething)
Variables
char theline [MAX_LINE_LENGTH]
Define Documentation
#define MAX_COLS 32
Definition at line 20 of file tablesort.c.
#define MAX_LINE_LENGTH 4096
Definition at line 19 of file tablesort.c.
#define MAX_WORD_LENGTH 128
Definition at line 21 of file tablesort.c.
#define usage '\n\n\n\NAME\n\	tablesort --- sort a table of numbers\n\SYNOPSIS\n\	tablesort	col\n\DESCRIPTION\n\		tablesort read lines of a table from stdin\n\		lines beginning with \'#\' and empty lines are ignored\n\		lines sorted in ascending order of colth column values.\n\		negative column number for descending order\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file tablesort.c.
Typedef Documentation
typedef struct thing thing
Function Documentation
int install (double x, thing * thething)
Definition at line 80 of file tablesort.c.
References thing::left, thing::line, thing::occupied, thing::right, theline, x, and thing::x.
Referenced by main().
main (int argc, char * argv[])
Definition at line 33 of file tablesort.c.
References exit(), install(), MAX_COLS, MAX_LINE_LENGTH, MAX_WORD_LENGTH, theline, usage, writeasc(), writedesc(), and x.
int writeasc (thing * thething)
Definition at line 100 of file tablesort.c.
References thing::left, thing::line, and thing::right.
Referenced by main().
int writedesc (thing * thething)
Definition at line 111 of file tablesort.c.
References thing::left, thing::line, and thing::right.
Referenced by main().
Variable Documentation
char theline[MAX_LINE_LENGTH]
Definition at line 31 of file tablesort.c.
Referenced by disposeof(), install(), main(), makecell(), and removedead().
Author
Generated automatically by Doxygen for imcat from the source code.