tcl.c
NAME
tcl.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
#include 'planetdata.h'
#include 'tcl.h'
Functions
void tcl (double dt, int nsteps, double *r, double *v)
void jupiteron (double phase)
void addjupitergravity (double *g, double *r)
Variables
int dojupiter = 0
double jupiterphase
double jupiteromega
double jupitermass
double * jupiterr
Function Documentation
void addjupitergravity (double * g, double * r)
Definition at line 59 of file tcl.c.
References A_JUPITER, assign(), g(), i, jupitermass, jupiterphase, jupiterr, length(), r, and scale().
Referenced by tcl().
void jupiteron (double phase)
Definition at line 50 of file tcl.c.
References A_JUPITER, dojupiter, jupitermass, jupiteromega, jupiterphase, jupiterr, M_JUPITER, and M_SUN.
Referenced by main().
void tcl (double dt, int nsteps, double * r, double * v)
Definition at line 11 of file tcl.c.
References addjupitergravity(), copy(), dojupiter, free(), g(), i, jupiteromega, jupiterphase, length(), r, scale(), and v.
Referenced by chisquared(), and main().
Variable Documentation
int dojupiter = 0 [static]
Definition at line 8 of file tcl.c.
Referenced by jupiteron(), and tcl().
double jupitermass [static]
Definition at line 9 of file tcl.c.
Referenced by addjupitergravity(), and jupiteron().
double jupiteromega [static]
Definition at line 9 of file tcl.c.
Referenced by jupiteron(), and tcl().
double jupiterphase [static]
Definition at line 9 of file tcl.c.
Referenced by addjupitergravity(), jupiteron(), and tcl().
double * jupiterr [static]
Definition at line 9 of file tcl.c.
Referenced by addjupitergravity(), and jupiteron().
Author
Generated automatically by Doxygen for imcat from the source code.