tcl.h
NAME
tcl.h -
SYNOPSIS
Functions
void tcl (double dt, int nsteps, double *r, double *v)
void jupiteron (double phase)
void addjupitergravity (double *g, double *r)
Function Documentation
void addjupitergravity (double * g, double * r)
Definition at line 59 of file tcl.c.
References A_JUPITER, assign(), g(), i, jupitermass, jupiterphase, jupiterr, length(), r, and scale().
Referenced by tcl().
void jupiteron (double phase)
Definition at line 50 of file tcl.c.
References A_JUPITER, dojupiter, jupitermass, jupiteromega, jupiterphase, jupiterr, M_JUPITER, and M_SUN.
Referenced by main().
void tcl (double dt, int nsteps, double * r, double * v)
Definition at line 11 of file tcl.c.
References addjupitergravity(), copy(), dojupiter, free(), g(), i, jupiteromega, jupiterphase, length(), r, scale(), and v.
Referenced by chisquared(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.