tcl_evolve.c
NAME
tcl_evolve.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
Defines
#define usage '\nNAME\n\	tcl_evolve\n\\n\SYNOPSIS\n\	tcl_evolve dt nsteps\n\\n\DESCRIPTION\n\	tcl_evolve reads an lc catalog containing positions re[3], ra[3]\n\	and velocities ve[3], va[3] from stdin, evolves the positions and\n\	velocities through n steps of length dt using time centered\n\	leapfrog, and writes the results to stdout.\n\\n\	Times are given in units of earths dynamical time (approx 58 days).\n\	Distances are in AU.\n\\n\SEE ALSO\n\	maketestpparfile.pl makeobs_circ laplace3\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	tcl_evolve\n\\n\SYNOPSIS\n\	tcl_evolve dt nsteps\n\\n\DESCRIPTION\n\	tcl_evolve reads an lc catalog containing positions re[3], ra[3]\n\	and velocities ve[3], va[3] from stdin, evolves the positions and\n\	velocities through n steps of length dt using time centered\n\	leapfrog, and writes the results to stdout.\n\\n\	Times are given in units of earths dynamical time (approx 58 days).\n\	Distances are in AU.\n\\n\SEE ALSO\n\	maketestpparfile.pl makeobs_circ laplace3\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 6 of file tcl_evolve.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 27 of file tcl_evolve.c.
References copy(), exit(), fprintvec(), ge(), i, ipf, length(), nt, ra, re, scale(), usage, and va.
Author
Generated automatically by Doxygen for imcat from the source code.