tcl_evolveN.c
NAME
tcl_evolveN.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
#include 'tcl.h'
#include 'utils/ipbuff.h'
Defines
#define usage '\nNAME\n\	tcl_evolveN\n\\n\SYNOPSIS\n\	tcl_evolveN dt nsteps nrep\n\\n\DESCRIPTION\n\	tcl_evolve reads an lc catalog containing a set of positions r[3]\n\	and velocities v[3] from stdin, evolves the positions and\n\	velocities through nrep repetitions of nsteps steps of length dt\n\	using time centered leapfrog, and writes the results to stdout.\n\\n\	Times are given in units of earths dynamical time (approx 58 days).\n\	Distances are in AU.\n\\n\SEE ALSO\n\	maketestpparfile.pl makeobs_circ laplace3 tcl_evolve\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	tcl_evolveN\n\\n\SYNOPSIS\n\	tcl_evolveN dt nsteps nrep\n\\n\DESCRIPTION\n\	tcl_evolve reads an lc catalog containing a set of positions r[3]\n\	and velocities v[3] from stdin, evolves the positions and\n\	velocities through nrep repetitions of nsteps steps of length dt\n\	using time centered leapfrog, and writes the results to stdout.\n\\n\	Times are given in units of earths dynamical time (approx 58 days).\n\	Distances are in AU.\n\\n\SEE ALSO\n\	maketestpparfile.pl makeobs_circ laplace3 tcl_evolve\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 8 of file tcl_evolveN.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 29 of file tcl_evolveN.c.
References buff, exit(), i, ipf, r, readdoublebuff(), tcl(), usage, and v.
Author
Generated automatically by Doxygen for imcat from the source code.