temp.c
NAME
temp.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'amoeba_dbl.h'
#include 'amotry_dbl.h'
#include '../../utils/nrutil.h'
Defines
#define NDIM 3
Functions
float myfunc (float *x)
main (int argc, char *argv[])
Define Documentation
#define NDIM 3
Definition at line 10 of file temp.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 12 of file temp.c.
References amoeba(), drand48(), i, j, matrix(), myfunc(), NDIM, vector(), x, and y.
float myfunc (float * x)
Definition at line 39 of file temp.c.
References NDIM, and x.
Author
Generated automatically by Doxygen for imcat from the source code.