.TH "temp.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
temp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'amoeba_dbl.h'\fP
.br
\fC#include 'amotry_dbl.h'\fP
.br
\fC#include '../../utils/nrutil.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNDIM\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBmyfunc\fP (float *x)"
.br
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define NDIM   3"
.PP
Definition at line 10 of file temp.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 12 of file temp.c.
.PP
References amoeba(), drand48(), i, j, matrix(), myfunc(), NDIM, vector(), x, and y.
.SS "float myfunc (float * x)"
.PP
Definition at line 39 of file temp.c.
.PP
References NDIM, and x.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
