powell_dbl.c
NAME
powell_dbl.c -
SYNOPSIS
#include <math.h>
#include '../../utils/nrutil.h'
Defines
#define NRANSI
#define ITMAX 200
Functions
void powell (double p[], double **xi, int n, double ftol, int *iter, double *fret, double(*func)(double[]))
Define Documentation
#define ITMAX 200
Definition at line 13 of file test/powell_dbl.c.
#define NRANSI
Definition at line 11 of file test/powell_dbl.c.
Function Documentation
void powell (double p[], double ** xi, int n, double ftol, int * iter, double * fret, double(* func)(double[]))
Definition at line 15 of file test/powell_dbl.c.
References free(), func(), i, ITMAX, j, linmin(), n, nrerror(), SQR, and t.
Author
Generated automatically by Doxygen for imcat from the source code.