amoeba.h
NAME
amoeba.h -
SYNOPSIS
Functions
void amoeba (float **p, float y[], int ndim, float ftol, float(*funk)(float[]), int *nfunk)
Function Documentation
void amoeba (float ** p, float y[], int ndim, float ftol, float(* funk)(float[]), int * nfunk)
Definition at line 13 of file photometry/fitting/amoeba.c.
References amotry(), free_vector(), GET_PSUM, i, j, NMAX, nrerror(), SWAP, swap, vector(), and y.
Author
Generated automatically by Doxygen for imcat from the source code.