testrpn.c
NAME
testrpn.c -
SYNOPSIS
#include <stdio.h>
#include '../../catlib/cat.h'
#include 'getop.h'
#include 'stack.h'
#include 'operators.h'
#include 'rpn.h'
#include 'error.h'
Functions
main (int argc, char *argv[])
Function Documentation
main (int argc, char * argv[])
Definition at line 16 of file testrpn.c.
References addobjectitem(), allocobjectcontents(), copyheaderinfo(), error_exit, evalrpnfunction(), getobjectitemindex(), inheritcontents(), newitem(), newobject(), newrpnfunction(), readcathead(), readobject(), rpnfunc::result, setaddress(), setsourcecathead(), TEXT_TYPE, writecathead(), and writeobject().
Author
Generated automatically by Doxygen for imcat from the source code.