amoeba_dbl.c
NAME
amoeba_dbl.c -
SYNOPSIS
#include <math.h>
#include '../../utils/nrutil.h'
Defines
#define NRANSI
#define NMAX 50000
#define GET_PSUM
#define SWAP(a, b) {swap=(a);(a)=(b);(b)=swap;}
Functions
void amoeba (double **p, double y[], int ndim, double ftol, double(*funk)(double[]), int *nfunk)
Define Documentation
#define GET_PSUM
Value:.nf
for (j=0;j<ndim;j++) {\
          for (sum=0.0,i=0;i<mpts;i++) sum += p[i][j];\
          psum[j]=sum;}
Definition at line 12 of file test/amoeba_dbl.c.
#define NMAX 50000
Definition at line 11 of file test/amoeba_dbl.c.
#define NRANSI
Definition at line 9 of file test/amoeba_dbl.c.
#define SWAP(a, b) {swap=(a);(a)=(b);(b)=swap;}
Definition at line 16 of file test/amoeba_dbl.c.
Function Documentation
void amoeba (double ** p, double y[], int ndim, double ftol, double(* funk)(double[]), int * nfunk)
Definition at line 18 of file test/amoeba_dbl.c.
References amotry(), free(), GET_PSUM, i, j, NMAX, nrerror(), SWAP, swap, and y.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.