linmin_dbl.c
NAME
linmin_dbl.c -
SYNOPSIS
#include '../../utils/nrutil.h'
Defines
#define NRANSI
#define TOL 2.0e-4
Functions
void linmin (double p[], double xi[], int n, double *fret, double(*func)(double[]))
Variables
int ncom
double * pcom
double * xicom
double(* nrfunc )(double[])
Define Documentation
#define NRANSI
Definition at line 10 of file test/linmin_dbl.c.
#define TOL 2.0e-4
Definition at line 12 of file test/linmin_dbl.c.
Function Documentation
void linmin (double p[], double xi[], int n, double * fret, double(* func)(double[]))
Definition at line 17 of file test/linmin_dbl.c.
References brent(), f, f1dim(), fb, free(), func(), j, mnbrak(), n, ncom, nrfunc, pcom, TOL, x, xicom, xmin, and xx.
Variable Documentation
int ncom
Definition at line 14 of file test/linmin_dbl.c.
double(* nrfunc)(double [])
Definition at line 15 of file test/linmin_dbl.c.
double* pcom
Definition at line 15 of file test/linmin_dbl.c.
double * xicom
Definition at line 15 of file test/linmin_dbl.c.
Author
Generated automatically by Doxygen for imcat from the source code.