.TH "fitstack_read.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fitstack_read.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreadmergedcat\fP (int \fBnexp\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int readmergedcat (int nexp)"
.PP
Definition at line 22 of file registration/fitstack_read.c.
.PP
References buff, BUFF_SIZE, e, error_exit, exit(), free(), i, j, lcpipe, mag, MAX_BUFFS, N_FIELDS, and x.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
