.TH "amotry_dbl.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amotry_dbl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../../utils/nrutil.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNRANSI\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBamotry\fP (double **p, double y[], double psum[], int \fBndim\fP, double(*funk)(double[]), int ihi, double fac)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define NRANSI"
.PP
Definition at line 8 of file test/amotry_dbl.c.
.SH "Function Documentation"
.PP 
.SS "double amotry (double ** p, double y[], double psum[], int ndim, double(* funk)(double[]), int ihi, double fac)"
.PP
Definition at line 11 of file test/amotry_dbl.c.
.PP
References free(), j, and y.
.PP
Referenced by amoeba().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
