.TH "testrpn.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testrpn.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include '../../catlib/cat.h'\fP
.br
\fC#include 'getop.h'\fP
.br
\fC#include 'stack.h'\fP
.br
\fC#include 'operators.h'\fP
.br
\fC#include 'rpn.h'\fP
.br
\fC#include 'error.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 16 of file testrpn.c.
.PP
References addobjectitem(), allocobjectcontents(), copyheaderinfo(), error_exit, evalrpnfunction(), getobjectitemindex(), inheritcontents(), newitem(), newobject(), newrpnfunction(), readcathead(), readobject(), rpnfunc::result, setaddress(), setsourcecathead(), TEXT_TYPE, writecathead(), and writeobject().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
