.TH "amoeba.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amoeba.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBamoeba\fP (float **p, float y[], int \fBndim\fP, float ftol, float(*funk)(float[]), int *nfunk)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void amoeba (float ** p, float y[], int ndim, float ftol, float(* funk)(float[]), int * nfunk)"
.PP
Definition at line 13 of file photometry/fitting/amoeba.c.
.PP
References amotry(), free_vector(), GET_PSUM, i, j, NMAX, nrerror(), SWAP, swap, vector(), and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
