.TH "f1dim_dbl.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f1dim_dbl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../../utils/nrutil.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNRANSI\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBf1dim\fP (double x)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBncom\fP"
.br
.ti -1c
.RI "double * \fBpcom\fP"
.br
.ti -1c
.RI "double * \fBxicom\fP"
.br
.ti -1c
.RI "double(* \fBnrfunc\fP )(double[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define NRANSI"
.PP
Definition at line 10 of file test/f1dim_dbl.c.
.SH "Function Documentation"
.PP 
.SS "double f1dim (double x)"
.PP
Definition at line 16 of file test/f1dim_dbl.c.
.PP
References f, free(), j, ncom, pcom, x, and xicom.
.SH "Variable Documentation"
.PP 
.SS "int \fBncom\fP"
.PP
Definition at line 13 of file test/f1dim_dbl.c.
.SS "double(* \fBnrfunc\fP)(double [])"
.PP
Definition at line 14 of file test/f1dim_dbl.c.
.SS "double* \fBpcom\fP"
.PP
Definition at line 14 of file test/f1dim_dbl.c.
.SS "double * \fBxicom\fP"
.PP
Definition at line 14 of file test/f1dim_dbl.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
