testpowell.c
NAME
testpowell.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include '../../utils/nrutil.h'
Defines
#define NDIM 3
Functions
void powell (double p[], double **xi, int n, double ftol, int *iter, double *fret, double(*func)(double[]))
double myfunc (double *x)
main (int argc, char *argv[])
Define Documentation
#define NDIM 3
Definition at line 10 of file test/testpowell.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 12 of file test/testpowell.c.
References i, myfunc(), NDIM, powell(), and y.
double myfunc (double * x)
Referenced by main().
void powell (double p[], double ** xi, int n, double ftol, int * iter, double * fret, double(* func)(double[]))
Definition at line 15 of file orbits/orbitutils/powell_dbl.c.
References free(), func(), i, ITMAX, j, linmin(), n, nrerror(), SQR, and t.
Author
Generated automatically by Doxygen for imcat from the source code.