fitstack.h
NAME
fitstack.h -
SYNOPSIS
Functions
int make_r (void)
int allocatearrays (void)
double *** allocpositionvector (void)
int printtranslations (void)
int printdistortions (void)
double chisquared (double *v)
int outputrcat (void)
int fittranslations (void)
Function Documentation
int allocatearrays (void)
Definition at line 455 of file registration/fitstack.c.
References a, Ad, Am, At, Bd, Bm, Bt, Cd, Cm, Ct, d, dm, dodistfit, i, indxd, indxm, indxt, j, m, ndcoefft, nexp, nmcoefft, nmodes, ntcoefft, and phi.
double*** allocpositionvector (void)
Definition at line 501 of file registration/fitstack.c.
References allocpositionvector(), error_exit, i, j, n, and nprs.
double chisquared (double * v)
Definition at line 281 of file test/fitstack.c.
int fittranslations (void)
Definition at line 344 of file registration/fitstack.c.
References At, Bt, Ct, d, det, e, i, indxt, j, m, mylubksb(), myludcmp(), n, ne, nexp, nprs, ntcoefft, phi, and re.
int make_r (void)
Definition at line 223 of file registration/fitstack.c.
References a, allocpositionvector(), d, e, f(), i, j, ll, M, mm, n, nmodes, nprs, phi, r, x, and xx.
int outputrcat (void)
Definition at line 312 of file test/fitstack.c.
References C, n, N, w, and x.
int printdistortions (void)
Definition at line 271 of file test/fitstack.c.
References d, and n.
int printtranslations (void)
Definition at line 260 of file test/fitstack.c.
References n.
Author
Generated automatically by Doxygen for imcat from the source code.