testfits.c
NAME
testfits.c -
SYNOPSIS
#include <stdio.h>
#include <limits.h>
#include <math.h>
#include 'fits.h'
Functions
main (int argc, char *argv[])
Function Documentation
main (int argc, char * argv[])
Definition at line 6 of file testfits.c.
References fitsheader::bscaling, copyfitsheader(), exit(), f, fits, FLOAT_PIXTYPE, fitsheader::linebuffer, fitsheader::n, N1, N2, read2Dfloatimage(), removenamedcomments(), write2Dfloatimage(), writefitsheader(), writefitsline(), writefitstail(), x, and y.
Author
Generated automatically by Doxygen for imcat from the source code.