.TH "testfits.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testfits.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'fits.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 6 of file testfits.c.
.PP
References fitsheader::bscaling, copyfitsheader(), exit(), f, fits, FLOAT_PIXTYPE, fitsheader::linebuffer, fitsheader::n, N1, N2, read2Dfloatimage(), removenamedcomments(), write2Dfloatimage(), writefitsheader(), writefitsline(), writefitstail(), x, and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
