.TH "testamoeba.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testamoeba.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'amoeba_dbl.h'\fP
.br
\fC#include 'amotry_dbl.h'\fP
.br
\fC#include '../../utils/nrutil.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNDIM\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBmyfunc\fP (double *x)"
.br
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define NDIM   3"
.PP
Definition at line 10 of file testamoeba.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 12 of file testamoeba.c.
.PP
References amoeba(), drand48(), i, j, myfunc(), NDIM, x, and y.
.SS "double myfunc (double * x)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
