testkepler.c
NAME
testkepler.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include 'vectors.h'
#include 'kepler.h'
Defines
#define usage '\nNAME\n\	testkepler\n\\n\SYNOPSIS\n\	testkepler \n\\n\DESCRIPTION\n\	testkepler reads r[3], v[3] values from stdin in lc-format\n\	and converts these to Kepler elements and back again.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\nNAME\n\	testkepler\n\\n\SYNOPSIS\n\	testkepler \n\\n\DESCRIPTION\n\	testkepler reads r[3], v[3] values from stdin in lc-format\n\	and converts these to Kepler elements and back again.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 12 of file testkepler.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 26 of file testkepler.c.
References buff, cartesiantokepler(), exit(), fillbufferfromkeplerorbit(), ipf, keplertocartesian(), r, theorbit, usage, and v.
Author
Generated automatically by Doxygen for imcat from the source code.