amoeba.c
NAME
amoeba.c -
SYNOPSIS
#include <math.h>
#include '../../utils/nrutil.h'
Defines
#define NRANSI
#define NMAX 5000
#define GET_PSUM
#define SWAP(a, b) {swap=(a);(a)=(b);(b)=swap;}
Functions
void amoeba (float **p, float y[], int ndim, float ftol, float(*funk)(float[]), int *nfunk)
Define Documentation
#define GET_PSUM
Value:.nf
for (j=1;j<=ndim;j++) {\
          for (sum=0.0,i=1;i<=mpts;i++) sum += p[i][j];\
          psum[j]=sum;}
Definition at line 5 of file test/amoeba.c.
#define NMAX 5000
Definition at line 4 of file test/amoeba.c.
#define NRANSI
Definition at line 2 of file test/amoeba.c.
#define SWAP(a, b) {swap=(a);(a)=(b);(b)=swap;}
Definition at line 9 of file test/amoeba.c.
Function Documentation
void amoeba (float ** p, float y[], int ndim, float ftol, float(* funk)(float[]), int * nfunk)
Definition at line 11 of file test/amoeba.c.
References amotry(), free_vector(), GET_PSUM, i, j, NMAX, nrerror(), SWAP, swap, vector(), and y.
Author
Generated automatically by Doxygen for imcat from the source code.