.TH "amotry.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amotry.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBamotry\fP (float **p, float y[], float psum[], int \fBndim\fP, float(*funk)(float[]), int ihi, float fac)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float amotry (float ** p, float y[], float psum[], int ndim, float(* funk)(float[]), int ihi, float fac)"
.PP
Definition at line 4 of file photometry/fitting/amotry.c.
.PP
References free_vector(), j, vector(), and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
