.TH "thing" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thing \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBthing\fP * \fBleft\fP"
.br
.ti -1c
.RI "\fBthing\fP * \fBright\fP"
.br
.ti -1c
.RI "char \fBline\fP [MAX_LINE_LENGTH]"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "int \fBoccupied\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBthing\fP* \fBthing::left\fP"
.PP
Definition at line 24 of file tablesort.c.
.PP
Referenced by install(), writeasc(), and writedesc().
.SS "char \fBthing::line\fP[MAX_LINE_LENGTH]"
.PP
Definition at line 26 of file tablesort.c.
.PP
Referenced by install(), writeasc(), and writedesc().
.SS "int \fBthing::occupied\fP"
.PP
Definition at line 28 of file tablesort.c.
.PP
Referenced by install().
.SS "struct \fBthing\fP* \fBthing::right\fP"
.PP
Definition at line 25 of file tablesort.c.
.PP
Referenced by install(), writeasc(), and writedesc().
.SS "double \fBthing::x\fP"
.PP
Definition at line 27 of file tablesort.c.
.PP
Referenced by install().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
