trackpeak.c
NAME
trackpeak.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'utils/error.h'
#include 'utils/args.h'
#include 'imlib/fits.h'
#include 'findpeak.h'
Defines
#define usage '\n\n\n\NAME\n\	trackpeak --- read stream of PSF images and track cell averaged peak\n\SYNOPSIS\n\	trackpeak [-x nx] \n\\n\DESCRIPTION\n\	'trackpeak' reads a 3D FITS image consisting of a stream\n\	of PSF images, average them with a cell of size nx * nx * nt\n\\n\	Options\n\		-x nx		# cell size in angle (6)\n\		-t nt		# cell size on time (3)\n\		-n nphotons	# number of photons (100)\n\		-r readnoise	# read noise in electrons (2.0)\n\		-T		# only output peak position\n\		-o opfname	# save accumulated psfs as opfname.fits\n\		-O opfname	# ditto, but don't output the video stream\n\		-N nframes	# only read the first nframes frames\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
float poidev (float xm, long *idum)
int getcentroid (float **f, int N1, int N2, double *xc, double *yc)
int main (int argc, char *argv[])
float ran1 (long *idum)
Define Documentation
#define usage '\n\n\n\NAME\n\	trackpeak --- read stream of PSF images and track cell averaged peak\n\SYNOPSIS\n\	trackpeak [-x nx] \n\\n\DESCRIPTION\n\	'trackpeak' reads a 3D FITS image consisting of a stream\n\	of PSF images, average them with a cell of size nx * nx * nt\n\\n\	Options\n\		-x nx		# cell size in angle (6)\n\		-t nt		# cell size on time (3)\n\		-n nphotons	# number of photons (100)\n\		-r readnoise	# read noise in electrons (2.0)\n\		-T		# only output peak position\n\		-o opfname	# save accumulated psfs as opfname.fits\n\		-O opfname	# ditto, but don't output the video stream\n\		-N nframes	# only read the first nframes frames\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file trackpeak.c.
Function Documentation
int getcentroid (float ** f, int N1, int N2, double * xc, double * yc)
Definition at line 262 of file trackpeak.c.
References f, N1, N2, x, and y.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 40 of file trackpeak.c.
References add_comment(), allocFloatArray(), argsinit(), copyfitsheader(), error_exit, exit(), fb, findpeak(), flag, getargf(), getargi(), getargs(), getcentroid(), getflag(), ix, M1, M2, fitsheader::n, N1, N2, fitsheader::ndim, nt, nx, fitsheader::opstream, poidev(), readfitsheader(), readfitsplane(), sigma, t, usage, writefitsheader(), writefitsplane(), writefitstail(), X, x, Y, y, and ys.
float poidev (float xm, long * idum)
Definition at line 4 of file poidev.c.
References g(), gammln(), PI, ran1(), t, xx, and y.
Referenced by main().
float ran1 (long * idum)
Definition at line 256 of file trackpeak.c.
References drand48().
Author
Generated automatically by Doxygen for imcat from the source code.