.TH "transformlist.c" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transformlist.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <math.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   'usage: transformlist \fBa\fP \fBphi\fP \fBdx\fP \fBdy\fP\\\fBn\fP\\	applies transformation\\\fBn\fP\\		\fBx0\fP = \fBa\fP (x cos \fBphi\fP - y sin \fBphi\fP) + \fBdx\fP\\\fBn\fP\\		y0 = \fBa\fP (x sin \fBphi\fP + y cos \fBphi\fP) + \fBdy\fP\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   'usage: transformlist \fBa\fP \fBphi\fP \fBdx\fP \fBdy\fP\\\fBn\fP\\	applies transformation\\\fBn\fP\\		\fBx0\fP = \fBa\fP (x cos \fBphi\fP - y sin \fBphi\fP) + \fBdx\fP\\\fBn\fP\\		y0 = \fBa\fP (x sin \fBphi\fP + y cos \fBphi\fP) + \fBdy\fP\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 7 of file transformlist.c.
.SH "Function Documentation"
.PP 
.SS "main (int argc, char * argv[])"
.PP
Definition at line 12 of file transformlist.c.
.PP
References a, dx, dy, exit(), line, phi, usage, x, and y.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
