transposebits.c
NAME
transposebits.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	transposebits - swap order of bits and numbers in a FITS file\n\\n\SYNOPSIS\n\	transposebits [-i]\n\\n\DESCRIPTION\n\	\'transposebits\' reads a FITS file a line at a time and transposes the\n\	order of bits and numbers such that if the input bit\n\	array is b[x][i], where 0 <= x < N1, and 0 <= i < |BITPIX|\n\	then the output line is the bit array b[i][x]. Thus the\n\	N1 lowest order bits will be output first, followed by the N1\n\	second lowest and so on. This may aid compression.\n\\n\	Use -i option to perform the inverse transpose.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	transposebits - swap order of bits and numbers in a FITS file\n\\n\SYNOPSIS\n\	transposebits [-i]\n\\n\DESCRIPTION\n\	\'transposebits\' reads a FITS file a line at a time and transposes the\n\	order of bits and numbers such that if the input bit\n\	array is b[x][i], where 0 <= x < N1, and 0 <= i < |BITPIX|\n\	then the output line is the bit array b[i][x]. Thus the\n\	N1 lowest order bits will be output first, followed by the N1\n\	second lowest and so on. This may aid compression.\n\\n\	Use -i option to perform the inverse transpose.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file transposebits.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 33 of file transposebits.c.
References add_comment(), b, error_exit, exit(), fitsheader::extpixtype, fits, i, fitsheader::ipstream, fitsheader::n, N, N1, N2, fitsheader::ndim, fitsheader::opstream, readfitsheader(), usage, writefitsheader(), writefitstail(), and x.
Author
Generated automatically by Doxygen for imcat from the source code.