transformimage.c
NAME
transformimage.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../utils/error.h'
#include '../imlib/fits.h'
#include '../imlib/map.h'
Defines
#define usage '\n\n\n\NAME\n\	transformimage - apply spatial linear transformation to a FITS image\n\\n\SYNOPSIS\n\	transformimage [options...]\n\		-p psi_xx psi_xy psi_yx psi_yy	# distortion matrix (1,0,0,1)\n\		-t t_x t_y			# translation vector (0,0)\n\		-n N1 N2			# size of output image\n\		-m mode				# mapping mode (1)\n\		-c				# keep image centre fixed\n\		-C				# keep center of (N1/2, N2/2) pixel fixed\n\		-i				# do inverse transformation\n\		-f fitsfile			# source for target image\n\\n\DESCRIPTION\n\	\'transformimage\' applies a general linear transformation to a source\n\	image fs(x) to make a target image f(r) = fs(x(r))\n\	where the mapping is x_i(r) = psi_ij r_j + t_i.\n\	By default output image = input image size.\n\	Use -m option to specify mode, where these are (in order of expense)\n\		mode = 0:	# nearest pixel\n\		mode = 1:	# linear interpolation\n\		mode = 2:	# sum over triangles\n\	With -c option we calculate t_x, t_y so that the centre\n\	pixel is mapped to centre of output pixel.\n\	By default, target image is initialised to zero\n\	but use -f option to read in an image on which we paint\n\	the mapped pixels.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
#define TINY 1.e-50
#define PRESERVE_ORIGIN 0
#define PRESERVE_IMAGE_CENTER 1
#define PRESERVE_PIXEL_CENTER 2
Functions
int deflection (float ri, float rj, float *di, float *dj)
main (int argc, char *argv[])
Variables
float psi [2][2]
float t [2]
Define Documentation
#define PRESERVE_IMAGE_CENTER 1
Definition at line 55 of file transformimage.c.
Referenced by main().
#define PRESERVE_ORIGIN 0
Definition at line 54 of file transformimage.c.
Referenced by main().
#define PRESERVE_PIXEL_CENTER 2
Definition at line 56 of file transformimage.c.
Referenced by main().
#define TINY 1.e-50
Definition at line 52 of file transformimage.c.
#define usage '\n\n\n\NAME\n\	transformimage - apply spatial linear transformation to a FITS image\n\\n\SYNOPSIS\n\	transformimage [options...]\n\		-p psi_xx psi_xy psi_yx psi_yy	# distortion matrix (1,0,0,1)\n\		-t t_x t_y			# translation vector (0,0)\n\		-n N1 N2			# size of output image\n\		-m mode				# mapping mode (1)\n\		-c				# keep image centre fixed\n\		-C				# keep center of (N1/2, N2/2) pixel fixed\n\		-i				# do inverse transformation\n\		-f fitsfile			# source for target image\n\\n\DESCRIPTION\n\	\'transformimage\' applies a general linear transformation to a source\n\	image fs(x) to make a target image f(r) = fs(x(r))\n\	where the mapping is x_i(r) = psi_ij r_j + t_i.\n\	By default output image = input image size.\n\	Use -m option to specify mode, where these are (in order of expense)\n\		mode = 0:	# nearest pixel\n\		mode = 1:	# linear interpolation\n\		mode = 2:	# sum over triangles\n\	With -c option we calculate t_x, t_y so that the centre\n\	pixel is mapped to centre of output pixel.\n\	By default, target image is initialised to zero\n\	but use -f option to read in an image on which we paint\n\	the mapped pixels.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 5 of file transformimage.c.
Function Documentation
int deflection (float ri, float rj, float * di, float * dj)
Definition at line 142 of file lensmap.c.
main (int argc, char * argv[])
Definition at line 58 of file transformimage.c.
References a, add_comment(), allocFloatArray(), b, c, copyfitsheader(), d, deflection(), det(), e1, error_exit, exit(), FAST_MAP_MODE, fastmap(), M1, M2, map(), fitsheader::n, N1, N2, PRESERVE_IMAGE_CENTER, PRESERVE_ORIGIN, PRESERVE_PIXEL_CENTER, psi, read2Dfloatimage(), t, t0, TINY, TRIANGLE_MAP_MODE, ULTRAFAST_MAP_MODE, ultrafastmap(), usage, and write2Dfloatimage().
Variable Documentation
float psi[2][2]
Definition at line 50 of file transformimage.c.
Referenced by main(), and slaDeuler().
float t[2]
Definition at line 50 of file transformimage.c.
Author
Generated automatically by Doxygen for imcat from the source code.