.TH "transform" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transform \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fft_NR.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float *** \fBdata\fP"
.br
.ti -1c
.RI "float ** \fBspeq\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float*** \fBtransform::data\fP"
.PP
Definition at line 5 of file fft_NR.h.
.SS "float** \fBtransform::speq\fP"
.PP
Definition at line 6 of file fft_NR.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
