.TH "triangulateio" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
triangulateio \- 
.SH SYNOPSIS
.br
.PP
\fC#include <triangle.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "REAL * \fBpointlist\fP"
.br
.ti -1c
.RI "REAL * \fBpointattributelist\fP"
.br
.ti -1c
.RI "int * \fBpointmarkerlist\fP"
.br
.ti -1c
.RI "int \fBnumberofpoints\fP"
.br
.ti -1c
.RI "int \fBnumberofpointattributes\fP"
.br
.ti -1c
.RI "int * \fBtrianglelist\fP"
.br
.ti -1c
.RI "REAL * \fBtriangleattributelist\fP"
.br
.ti -1c
.RI "REAL * \fBtrianglearealist\fP"
.br
.ti -1c
.RI "int * \fBneighborlist\fP"
.br
.ti -1c
.RI "int \fBnumberoftriangles\fP"
.br
.ti -1c
.RI "int \fBnumberofcorners\fP"
.br
.ti -1c
.RI "int \fBnumberoftriangleattributes\fP"
.br
.ti -1c
.RI "int * \fBsegmentlist\fP"
.br
.ti -1c
.RI "int * \fBsegmentmarkerlist\fP"
.br
.ti -1c
.RI "int \fBnumberofsegments\fP"
.br
.ti -1c
.RI "REAL * \fBholelist\fP"
.br
.ti -1c
.RI "int \fBnumberofholes\fP"
.br
.ti -1c
.RI "REAL * \fBregionlist\fP"
.br
.ti -1c
.RI "int \fBnumberofregions\fP"
.br
.ti -1c
.RI "int * \fBedgelist\fP"
.br
.ti -1c
.RI "int * \fBedgemarkerlist\fP"
.br
.ti -1c
.RI "REAL * \fBnormlist\fP"
.br
.ti -1c
.RI "int \fBnumberofedges\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int* \fBtriangulateio::edgelist\fP"
.PP
Definition at line 273 of file triangle.h.
.SS "int* \fBtriangulateio::edgemarkerlist\fP"
.PP
Definition at line 274 of file triangle.h.
.SS "REAL* \fBtriangulateio::holelist\fP"
.PP
Definition at line 267 of file triangle.h.
.SS "int* \fBtriangulateio::neighborlist\fP"
.PP
Definition at line 258 of file triangle.h.
.SS "REAL* \fBtriangulateio::normlist\fP"
.PP
Definition at line 275 of file triangle.h.
.SS "int \fBtriangulateio::numberofcorners\fP"
.PP
Definition at line 260 of file triangle.h.
.SS "int \fBtriangulateio::numberofedges\fP"
.PP
Definition at line 276 of file triangle.h.
.SS "int \fBtriangulateio::numberofholes\fP"
.PP
Definition at line 268 of file triangle.h.
.SS "int \fBtriangulateio::numberofpointattributes\fP"
.PP
Definition at line 253 of file triangle.h.
.SS "int \fBtriangulateio::numberofpoints\fP"
.PP
Definition at line 252 of file triangle.h.
.SS "int \fBtriangulateio::numberofregions\fP"
.PP
Definition at line 271 of file triangle.h.
.SS "int \fBtriangulateio::numberofsegments\fP"
.PP
Definition at line 265 of file triangle.h.
.SS "int \fBtriangulateio::numberoftriangleattributes\fP"
.PP
Definition at line 261 of file triangle.h.
.SS "int \fBtriangulateio::numberoftriangles\fP"
.PP
Definition at line 259 of file triangle.h.
.SS "REAL* \fBtriangulateio::pointattributelist\fP"
.PP
Definition at line 250 of file triangle.h.
.SS "REAL* \fBtriangulateio::pointlist\fP"
.PP
Definition at line 249 of file triangle.h.
.SS "int* \fBtriangulateio::pointmarkerlist\fP"
.PP
Definition at line 251 of file triangle.h.
.SS "REAL* \fBtriangulateio::regionlist\fP"
.PP
Definition at line 270 of file triangle.h.
.SS "int* \fBtriangulateio::segmentlist\fP"
.PP
Definition at line 263 of file triangle.h.
.SS "int* \fBtriangulateio::segmentmarkerlist\fP"
.PP
Definition at line 264 of file triangle.h.
.SS "REAL* \fBtriangulateio::trianglearealist\fP"
.PP
Definition at line 257 of file triangle.h.
.SS "REAL* \fBtriangulateio::triangleattributelist\fP"
.PP
Definition at line 256 of file triangle.h.
.SS "int* \fBtriangulateio::trianglelist\fP"
.PP
Definition at line 255 of file triangle.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
