triangle.c
NAME
triangle.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <sys/time.h>
Data Structures
struct badface
struct badsegment
struct edge
struct event
struct memorypool
struct splaynode
struct triedge
Defines
#define REAL double
#define INEXACT
#define FILENAMESIZE 512
#define INPUTLINESIZE 512
#define TRIPERBLOCK 4092
#define SHELLEPERBLOCK 508
#define POINTPERBLOCK 4092
#define VIRUSPERBLOCK 1020
#define BADSEGMENTPERBLOCK 252
#define BADTRIPERBLOCK 4092
#define SPLAYNODEPERBLOCK 508
#define DEADPOINT -1073741824
#define VOID int
#define SAMPLEFACTOR 11
#define SAMPLERATE 10
#define PI 3.141592653589793238462643383279502884197169399375105820974944592308
#define SQUAREROOTTWO 1.4142135623730950488016887242096980785696718753769480732
#define ONETHIRD 0.333333333333333333333333333333333333333333333333333333333333
#define decode(ptr, triedge)
#define encode(triedge) (triangle) ((unsigned long) (triedge).tri | (unsigned long) (triedge).orient)
#define sym(triedge1, triedge2)
#define symself(triedge)
#define lnext(triedge1, triedge2)
#define lnextself(triedge) (triedge).orient = plus1mod3[(triedge).orient]
#define lprev(triedge1, triedge2)
#define lprevself(triedge) (triedge).orient = minus1mod3[(triedge).orient]
#define onext(triedge1, triedge2)
#define onextself(triedge)
#define oprev(triedge1, triedge2)
#define oprevself(triedge)
#define dnext(triedge1, triedge2)
#define dnextself(triedge)
#define dprev(triedge1, triedge2)
#define dprevself(triedge)
#define rnext(triedge1, triedge2)
#define rnextself(triedge)
#define rprev(triedge1, triedge2)
#define rprevself(triedge)
#define org(triedge, pointptr) pointptr = (point) (triedge).tri[plus1mod3[(triedge).orient] + 3]
#define dest(triedge, pointptr) pointptr = (point) (triedge).tri[minus1mod3[(triedge).orient] + 3]
#define apex(triedge, pointptr) pointptr = (point) (triedge).tri[(triedge).orient + 3]
#define setorg(triedge, pointptr) (triedge).tri[plus1mod3[(triedge).orient] + 3] = (triangle) pointptr
#define setdest(triedge, pointptr) (triedge).tri[minus1mod3[(triedge).orient] + 3] = (triangle) pointptr
#define setapex(triedge, pointptr) (triedge).tri[(triedge).orient + 3] = (triangle) pointptr
#define setvertices2null(triedge)
#define bond(triedge1, triedge2)
#define dissolve(triedge) (triedge).tri[(triedge).orient] = (triangle) dummytri
#define triedgecopy(triedge1, triedge2)
#define triedgeequal(triedge1, triedge2)
#define infect(triedge)
#define uninfect(triedge)
#define infected(triedge) (((unsigned long) (triedge).tri[6] & (unsigned long) 2l) != 0)
#define elemattribute(triedge, attnum) ((REAL *) (triedge).tri)[elemattribindex + (attnum)]
#define setelemattribute(triedge, attnum, value) ((REAL *) (triedge).tri)[elemattribindex + (attnum)] = value
#define areabound(triedge) ((REAL *) (triedge).tri)[areaboundindex]
#define setareabound(triedge, value) ((REAL *) (triedge).tri)[areaboundindex] = value
#define sdecode(sptr, edge)
#define sencode(edge) (shelle) ((unsigned long) (edge).sh | (unsigned long) (edge).shorient)
#define ssym(edge1, edge2)
#define ssymself(edge) (edge).shorient = 1 - (edge).shorient
#define spivot(edge1, edge2)
#define spivotself(edge)
#define snext(edge1, edge2)
#define snextself(edge)
#define sorg(edge, pointptr) pointptr = (point) (edge).sh[2 + (edge).shorient]
#define sdest(edge, pointptr) pointptr = (point) (edge).sh[3 - (edge).shorient]
#define setsorg(edge, pointptr) (edge).sh[2 + (edge).shorient] = (shelle) pointptr
#define setsdest(edge, pointptr) (edge).sh[3 - (edge).shorient] = (shelle) pointptr
#define mark(edge) (* (int *) ((edge).sh + 6))
#define setmark(edge, value) * (int *) ((edge).sh + 6) = value
#define sbond(edge1, edge2)
#define sdissolve(edge) (edge).sh[(edge).shorient] = (shelle) dummysh
#define shellecopy(edge1, edge2)
#define shelleequal(edge1, edge2)
#define tspivot(triedge, edge)
#define stpivot(edge, triedge)
#define tsbond(triedge, edge)
#define tsdissolve(triedge) (triedge).tri[6 + (triedge).orient] = (triangle) dummysh
#define stdissolve(edge) (edge).sh[4 + (edge).shorient] = (shelle) dummytri
#define pointmark(pt) ((int *) (pt))[pointmarkindex]
#define setpointmark(pt, value) ((int *) (pt))[pointmarkindex] = value
#define point2tri(pt) ((triangle *) (pt))[point2triindex]
#define setpoint2tri(pt, value) ((triangle *) (pt))[point2triindex] = value
#define STARTINDEX 1
#define Absolute(a) ((a) >= 0.0 ? (a) : -(a))
#define Fast_Two_Sum_Tail(a, b, x, y)
#define Fast_Two_Sum(a, b, x, y)
#define Two_Sum_Tail(a, b, x, y)
#define Two_Sum(a, b, x, y)
#define Two_Diff_Tail(a, b, x, y)
#define Two_Diff(a, b, x, y)
#define Split(a, ahi, alo)
#define Two_Product_Tail(a, b, x, y)
#define Two_Product(a, b, x, y)
#define Two_Product_Presplit(a, b, bhi, blo, x, y)
#define Square_Tail(a, x, y)
#define Square(a, x, y)
#define Two_One_Sum(a1, a0, b, x2, x1, x0)
#define Two_One_Diff(a1, a0, b, x2, x1, x0)
#define Two_Two_Sum(a1, a0, b1, b0, x3, x2, x1, x0)
#define Two_Two_Diff(a1, a0, b1, b0, x3, x2, x1, x0)
Typedefs
typedef REAL ** triangle
typedef REAL ** shelle
typedef REAL * point
Enumerations
enum wordtype { POINTER, FLOATINGPOINT }
enum locateresult { INTRIANGLE, ONEDGE, ONVERTEX, OUTSIDE }
enum insertsiteresult { SUCCESSFULPOINT, ENCROACHINGPOINT, VIOLATINGPOINT, DUPLICATEPOINT }
enum finddirectionresult { WITHIN, LEFTCOLLINEAR, RIGHTCOLLINEAR }
enum circumcenterresult { OPPOSITEORG, OPPOSITEDEST, OPPOSITEAPEX }
Functions
void * malloc ()
void free ()
void exit ()
double strtod ()
long strtol ()
void poolrestart ()
char * readline ()
char * findfield ()
void syntax ()
void info ()
void internalerror ()
void parsecommandline (int argc, char **argv)
void printtriangle (struct triedge *t)
void printshelle (struct edge *s)
void poolinit (struct memorypool *pool, int bytecount, int itemcount, enum wordtype wtype, int alignment)
void poolrestart (struct memorypool *pool)
void pooldeinit (struct memorypool *pool)
VOID * poolalloc (struct memorypool *pool)
void pooldealloc (struct memorypool *pool, VOID *dyingitem)
void traversalinit (struct memorypool *pool)
VOID * traverse (struct memorypool *pool)
void dummyinit (int trianglewords, int shellewords)
void initializepointpool ()
void initializetrisegpools ()
void triangledealloc (triangle *dyingtriangle)
triangle * triangletraverse ()
void shelledealloc (shelle *dyingshelle)
shelle * shelletraverse ()
void pointdealloc (point dyingpoint)
point pointtraverse ()
void badsegmentdealloc (struct edge *dyingseg)
edge * badsegmenttraverse ()
point getpoint (int number)
void triangledeinit ()
void maketriangle (struct triedge *newtriedge)
void makeshelle (struct edge *newedge)
void exactinit ()
int fast_expansion_sum_zeroelim (int elen, REAL *e, int flen, REAL *f, REAL *h)
int scale_expansion_zeroelim (int elen, REAL *e, REAL b, REAL *h)
REAL estimate (int elen, REAL *e)
REAL counterclockwiseadapt (point pa, point pb, point pc, REAL detsum)
REAL counterclockwise (point pa, point pb, point pc)
REAL incircleadapt (point pa, point pb, point pc, point pd, REAL permanent)
REAL incircle (point pa, point pb, point pc, point pd)
void triangleinit ()
unsigned long randomnation (unsigned int choices)
void checkmesh ()
void checkdelaunay ()
void enqueuebadtri (struct triedge *instri, REAL angle, point insapex, point insorg, point insdest)
badface * dequeuebadtri ()
int checkedge4encroach (struct edge *testedge)
void testtriangle (struct triedge *testtri)
void makepointmap ()
enum locateresult preciselocate (point searchpoint, struct triedge *searchtri)
enum locateresult locate (point searchpoint, struct triedge *searchtri)
void insertshelle (struct triedge *tri, int shellemark)
void flip (struct triedge *flipedge)
enum insertsiteresult insertsite (point insertpoint, struct triedge *searchtri, struct edge *splitedge, int segmentflaws, int triflaws)
void triangulatepolygon (struct triedge *firstedge, struct triedge *lastedge, int edgecount, int doflip, int triflaws)
void deletesite (struct triedge *deltri)
void pointsort (point *sortarray, int arraysize)
void pointmedian (point *sortarray, int arraysize, int median, int axis)
void alternateaxes (point *sortarray, int arraysize, int axis)
void mergehulls (struct triedge *farleft, struct triedge *innerleft, struct triedge *innerright, struct triedge *farright, int axis)
void divconqrecurse (point *sortarray, int vertices, int axis, struct triedge *farleft, struct triedge *farright)
long removeghosts (struct triedge *startghost)
long divconqdelaunay ()
void boundingbox ()
long removebox ()
long incrementaldelaunay ()
void eventheapinsert (struct event **heap, int heapsize, struct event *newevent)
void eventheapify (struct event **heap, int heapsize, int eventnum)
void eventheapdelete (struct event **heap, int heapsize, int eventnum)
void createeventheap (struct event ***eventheap, struct event **events, struct event **freeevents)
int rightofhyperbola (struct triedge *fronttri, point newsite)
REAL circletop (point pa, point pb, point pc, REAL ccwabc)
void check4deadevent (struct triedge *checktri, struct event **freeevents, struct event **eventheap, int *heapsize)
splaynode * splay (struct splaynode *splaytree, point searchpoint, struct triedge *searchtri)
splaynode * splayinsert (struct splaynode *splayroot, struct triedge *newkey, point searchpoint)
splaynode * circletopinsert (struct splaynode *splayroot, struct triedge *newkey, point pa, point pb, point pc, REAL topy)
splaynode * frontlocate (struct splaynode *splayroot, struct triedge *bottommost, point searchpoint, struct triedge *searchtri, int *farright)
long sweeplinedelaunay ()
long delaunay ()
long reconstruct (char *elefilename, char *areafilename, char *polyfilename, FILE *polyfile)
enum finddirectionresult finddirection (struct triedge *searchtri, point endpoint)
void segmentintersection (struct triedge *splittri, struct edge *splitshelle, point endpoint2)
int scoutsegment (struct triedge *searchtri, point endpoint2, int newmark)
void conformingedge (point endpoint1, point endpoint2, int newmark)
void delaunayfixup (struct triedge *fixuptri, int leftside)
void constrainededge (struct triedge *starttri, point endpoint2, int newmark)
void insertsegment (point endpoint1, point endpoint2, int newmark)
void markhull ()
int formskeleton (FILE *polyfile, char *polyfilename)
void infecthull ()
void plague ()
void regionplague (REAL attribute, REAL area)
void carveholes (REAL *holelist, int holes, REAL *regionlist, int regions)
void tallyencs ()
void precisionerror ()
void repairencs (int flaws)
void tallyfaces ()
enum circumcenterresult findcircumcenter (point torg, point tdest, point tapex, point circumcenter, REAL *xi, REAL *eta)
void splittriangle (struct badface *badtri)
void enforcequality ()
void highorder ()
char * readline (char *string, FILE *infile, char *infilename)
char * findfield (char *string)
void readnodes (char *nodefilename, char *polyfilename, FILE **polyfile)
void readholes (FILE *polyfile, char *polyfilename, REAL **hlist, int *holes, REAL **rlist, int *regions)
void finishfile (FILE *outfile, int argc, char **argv)
void writenodes (char *nodefilename, int argc, char **argv)
void numbernodes ()
void writeelements (char *elefilename, int argc, char **argv)
void writepoly (char *polyfilename, REAL *holelist, int holes, REAL *regionlist, int regions, int argc, char **argv)
void writeedges (char *edgefilename, int argc, char **argv)
void writevoronoi (char *vnodefilename, char *vedgefilename, int argc, char **argv)
void writeneighbors (char *neighborfilename, int argc, char **argv)
void writeoff (char *offfilename, int argc, char **argv)
void quality_statistics ()
void statistics ()
int main (int argc, char **argv)
Variables
memorypool triangles
memorypool shelles
memorypool points
memorypool viri
memorypool badsegments
memorypool badtriangles
memorypool splaynodes
badface * queuefront [64]
badface ** queuetail [64]
REAL xmin
REAL xmax
REAL ymin
REAL ymax
REAL xminextreme
int inpoints
int inelements
int insegments
int holes
int regions
long edges
int mesh_dim
int nextras
int eextras
long hullsize
int triwords
int shwords
int pointmarkindex
int point2triindex
int highorderindex
int elemattribindex
int areaboundindex
int checksegments
int readnodefile
long samples
unsigned long randomseed
REAL splitter
REAL epsilon
REAL resulterrbound
REAL ccwerrboundA
REAL ccwerrboundB
REAL ccwerrboundC
REAL iccerrboundA
REAL iccerrboundB
REAL iccerrboundC
long incirclecount
long counterclockcount
long hyperbolacount
long circumcentercount
long circletopcount
int poly
int refine
int quality
int vararea
int fixedarea
int regionattrib
int convex
int firstnumber
int edgesout
int voronoi
int neighbors
int geomview
int nobound
int nopolywritten
int nonodewritten
int noelewritten
int noiterationnum
int noholes
int noexact
int incremental
int sweepline
int dwyer
int splitseg
int docheck
int quiet
int verbose
int useshelles
int order
int nobisect
int steiner
int steinerleft
REAL minangle
REAL goodangle
REAL maxarea
char innodefilename [FILENAMESIZE]
char inelefilename [FILENAMESIZE]
char inpolyfilename [FILENAMESIZE]
char areafilename [FILENAMESIZE]
char outnodefilename [FILENAMESIZE]
char outelefilename [FILENAMESIZE]
char outpolyfilename [FILENAMESIZE]
char edgefilename [FILENAMESIZE]
char vnodefilename [FILENAMESIZE]
char vedgefilename [FILENAMESIZE]
char neighborfilename [FILENAMESIZE]
char offfilename [FILENAMESIZE]
point infpoint1
point infpoint2
point infpoint3
triangle * dummytri
triangle * dummytribase
shelle * dummysh
shelle * dummyshbase
triedge recenttri
int plus1mod3 [3] = {1, 2, 0}
int minus1mod3 [3] = {2, 0, 1}
Define Documentation
#define Absolute(a) ((a) >= 0.0 ? (a) : -(a))
* Definition at line 3899 of file triangle.c.
Referenced by counterclockwiseadapt(), incircle(), and incircleadapt().
#define apex(triedge, pointptr) pointptr = (point) (triedge).tri[(triedge).orient + 3]
Definition at line 919 of file triangle.c.
Referenced by checkdelaunay(), checkedge4encroach(), checkmesh(), delaunayfixup(), finddirection(), flip(), insertsite(), mergehulls(), plague(), preciselocate(), printtriangle(), quality_statistics(), reconstruct(), regionplague(), rightofhyperbola(), scoutsegment(), segmentintersection(), splittriangle(), sweeplinedelaunay(), testtriangle(), triangulatepolygon(), writeelements(), writeoff(), and writevoronoi().
#define areabound(triedge) ((REAL *) (triedge).tri)[areaboundindex]
Definition at line 988 of file triangle.c.
Referenced by insertsite(), printtriangle(), and testtriangle().
#define BADSEGMENTPERBLOCK 252
Definition at line 264 of file triangle.c.
Referenced by enforcequality().
#define BADTRIPERBLOCK 4092
Definition at line 266 of file triangle.c.
Referenced by enforcequality().
#define bond(triedge1, triedge2)
Value:.nf
(triedge1).tri[(triedge1).orient] = encode(triedge2); \
  (triedge2).tri[(triedge2).orient] = encode(triedge1)
Definition at line 938 of file triangle.c.
Referenced by deletesite(), divconqrecurse(), flip(), insertsite(), mergehulls(), reconstruct(), and sweeplinedelaunay().
#define DEADPOINT -1073741824
Definition at line 274 of file triangle.c.
Referenced by pointdealloc(), pointtraverse(), and reconstruct().
#define decode(ptr, triedge)
Value:.nf
(triedge).orient = (int) ((unsigned long) (ptr) & (unsigned long) 3l); \
  (triedge).tri = (triangle *) \
                  ((unsigned long) (ptr) ^ (unsigned long) (triedge).orient)
Definition at line 788 of file triangle.c.
Referenced by insertsegment(), printshelle(), printtriangle(), reconstruct(), and sweeplinedelaunay().
#define dest(triedge, pointptr) pointptr = (point) (triedge).tri[minus1mod3[(triedge).orient] + 3]
Definition at line 916 of file triangle.c.
Referenced by carveholes(), checkdelaunay(), checkmesh(), delaunayfixup(), finddirection(), flip(), highorder(), infecthull(), insertshelle(), insertsite(), jpl_state(), locate(), mergehulls(), plague(), preciselocate(), printtriangle(), quality_statistics(), reconstruct(), regionplague(), rightofhyperbola(), scoutsegment(), segmentintersection(), splay(), splayinsert(), splittriangle(), sweeplinedelaunay(), testtriangle(), triangulatepolygon(), writeedges(), writeelements(), writeoff(), and writevoronoi().
#define dissolve(triedge) (triedge).tri[(triedge).orient] = (triangle) dummytri
Definition at line 947 of file triangle.c.
Referenced by plague(), removebox(), and removeghosts().
#define dnext(triedge1, triedge2)
Value:.nf
sym(triedge1, triedge2); \
  lprevself(triedge2);
Definition at line 862 of file triangle.c.
Referenced by deletesite().
#define dnextself(triedge)
Value:.nf
symself(triedge); \
  lprevself(triedge);
Definition at line 866 of file triangle.c.
#define dprev(triedge1, triedge2)
Value:.nf
lnext(triedge1, triedge2); \
  symself(triedge2);
Definition at line 874 of file triangle.c.
#define dprevself(triedge)
Value:.nf
lnextself(triedge); \
  symself(triedge);
Definition at line 878 of file triangle.c.
#define elemattribute(triedge, attnum) ((REAL *) (triedge).tri)[elemattribindex + (attnum)]
Definition at line 980 of file triangle.c.
Referenced by insertsite(), and writeelements().
#define encode(triedge) (triangle) ((unsigned long) (triedge).tri | (unsigned long) (triedge).orient)
Definition at line 797 of file triangle.c.
Referenced by makepointmap(), reconstruct(), removebox(), removeghosts(), and sweeplinedelaunay().
#define Fast_Two_Sum(a, b, x, y)
Value:.nf
x = (REAL) (a + b); \
  Fast_Two_Sum_Tail(a, b, x, y)
Definition at line 3919 of file triangle.c.
Referenced by fast_expansion_sum_zeroelim(), and scale_expansion_zeroelim().
#define Fast_Two_Sum_Tail(a, b, x, y)
Value:.nf
bvirt = x - a; \
  y = b - bvirt
Definition at line 3915 of file triangle.c.
#define FILENAMESIZE 512
Definition at line 248 of file triangle.c.
Referenced by parsecommandline().
#define INEXACT
Definition at line 243 of file triangle.c.
Referenced by counterclockwiseadapt(), fast_expansion_sum_zeroelim(), incircleadapt(), and scale_expansion_zeroelim().
#define infect(triedge)
Value:.nf
(triedge).tri[6] = (triangle) \
                     ((unsigned long) (triedge).tri[6] | (unsigned long) 2l)
Definition at line 965 of file triangle.c.
Referenced by carveholes(), infecthull(), plague(), and regionplague().
#define infected(triedge) (((unsigned long) (triedge).tri[6] & (unsigned long) 2l) != 0)
Definition at line 975 of file triangle.c.
Referenced by carveholes(), infecthull(), plague(), and regionplague().
#define INPUTLINESIZE 512
Definition at line 253 of file triangle.c.
Referenced by formskeleton(), readholes(), readline(), readnodes(), and reconstruct().
#define lnext(triedge1, triedge2)
Value:.nf
(triedge2).tri = (triedge1).tri; \
  (triedge2).orient = plus1mod3[(triedge1).orient]
Definition at line 818 of file triangle.c.
Referenced by constrainededge(), delaunayfixup(), divconqrecurse(), flip(), insertsite(), mergehulls(), preciselocate(), removebox(), removeghosts(), repairencs(), scoutsegment(), sweeplinedelaunay(), and testtriangle().
#define lnextself(triedge) (triedge).orient = plus1mod3[(triedge).orient]
Definition at line 822 of file triangle.c.
Referenced by divconqrecurse(), flip(), infecthull(), insertsite(), locate(), markhull(), mergehulls(), preciselocate(), removebox(), repairencs(), scoutsegment(), splittriangle(), sweeplinedelaunay(), and testtriangle().
#define lprev(triedge1, triedge2)
Value:.nf
(triedge2).tri = (triedge1).tri; \
  (triedge2).orient = minus1mod3[(triedge1).orient]
Definition at line 827 of file triangle.c.
Referenced by deletesite(), divconqrecurse(), flip(), insertsite(), mergehulls(), preciselocate(), reconstruct(), removebox(), removeghosts(), sweeplinedelaunay(), and testtriangle().
#define lprevself(triedge) (triedge).orient = minus1mod3[(triedge).orient]
Definition at line 831 of file triangle.c.
Referenced by constrainededge(), delaunayfixup(), divconqrecurse(), insertsite(), mergehulls(), preciselocate(), removebox(), removeghosts(), scoutsegment(), splittriangle(), and sweeplinedelaunay().
#define mark(edge) (* (int *) ((edge).sh + 6))
Definition at line 1063 of file triangle.c.
Referenced by highorder(), infecthull(), insertshelle(), insertsite(), plague(), printshelle(), repairencs(), segmentintersection(), writeedges(), and writepoly().
#define ONETHIRD 0.333333333333333333333333333333333333333333333333333333333333
Definition at line 303 of file triangle.c.
#define onext(triedge1, triedge2)
Value:.nf
lprev(triedge1, triedge2); \
  symself(triedge2);
Definition at line 838 of file triangle.c.
Referenced by deletesite(), finddirection(), plague(), sweeplinedelaunay(), and triangulatepolygon().
#define onextself(triedge)
Value:.nf
lprevself(triedge); \
  symself(triedge);
Definition at line 842 of file triangle.c.
Referenced by deletesite(), finddirection(), frontlocate(), plague(), segmentintersection(), and triangulatepolygon().
#define oprev(triedge1, triedge2)
Value:.nf
sym(triedge1, triedge2); \
  lnextself(triedge2);
Definition at line 850 of file triangle.c.
Referenced by constrainededge(), deletesite(), infecthull(), markhull(), plague(), sweeplinedelaunay(), and triangulatepolygon().
#define oprevself(triedge)
Value:.nf
symself(triedge); \
  lnextself(triedge);
Definition at line 854 of file triangle.c.
Referenced by constrainededge(), finddirection(), and plague().
#define org(triedge, pointptr) pointptr = (point) (triedge).tri[plus1mod3[(triedge).orient] + 3]
Definition at line 913 of file triangle.c.
Referenced by carveholes(), check4deadevent(), checkdelaunay(), checkmesh(), conformingedge(), constrainededge(), delaunayfixup(), deletesite(), finddirection(), flip(), highorder(), infecthull(), insertsegment(), insertshelle(), insertsite(), locate(), makepointmap(), mergehulls(), plague(), preciselocate(), printtriangle(), quality_statistics(), regionplague(), removebox(), removeghosts(), scoutsegment(), segmentintersection(), splittriangle(), sweeplinedelaunay(), testtriangle(), writeedges(), writeelements(), writeoff(), and writevoronoi().
#define PI 3.141592653589793238462643383279502884197169399375105820974944592308
Definition at line 295 of file triangle.c.
#define point2tri(pt) ((triangle *) (pt))[point2triindex]
Definition at line 1134 of file triangle.c.
Referenced by insertsegment().
#define pointmark(pt) ((int *) (pt))[pointmarkindex]
Definition at line 1129 of file triangle.c.
Referenced by infecthull(), insertshelle(), plague(), pointtraverse(), reconstruct(), removebox(), removeghosts(), writeedges(), writeelements(), writenodes(), writeoff(), and writepoly().
#define POINTPERBLOCK 4092
Definition at line 261 of file triangle.c.
Referenced by initializepointpool().
#define REAL double
Definition at line 200 of file triangle.c.
Referenced by boundingbox(), carveholes(), circletop(), circletopinsert(), constrainededge(), counterclockwise(), counterclockwiseadapt(), divconqrecurse(), enqueuebadtri(), estimate(), eventheapdelete(), eventheapify(), eventheapinsert(), exactinit(), fast_expansion_sum_zeroelim(), findcircumcenter(), finddirection(), incircle(), incircleadapt(), initializepointpool(), initializetrisegpools(), insertsite(), locate(), main(), parsecommandline(), pointmedian(), pointsort(), poolalloc(), poolinit(), preciselocate(), quality_statistics(), readholes(), readnodes(), reconstruct(), regionplague(), repairencs(), rightofhyperbola(), scale_expansion_zeroelim(), segmentintersection(), splittriangle(), sweeplinedelaunay(), testtriangle(), traverse(), writeelements(), writenodes(), writepoly(), and writevoronoi().
#define rnext(triedge1, triedge2)
Value:.nf
sym(triedge1, triedge2); \
  lnextself(triedge2); \
  symself(triedge2);
Definition at line 886 of file triangle.c.
#define rnextself(triedge)
Value:.nf
symself(triedge); \
  lnextself(triedge); \
  symself(triedge);
Definition at line 891 of file triangle.c.
#define rprev(triedge1, triedge2)
Value:.nf
sym(triedge1, triedge2); \
  lprevself(triedge2); \
  symself(triedge2);
Definition at line 900 of file triangle.c.
#define rprevself(triedge)
Value:.nf
symself(triedge); \
  lprevself(triedge); \
  symself(triedge);
Definition at line 905 of file triangle.c.
#define SAMPLEFACTOR 11
Definition at line 287 of file triangle.c.
Referenced by locate().
#define SAMPLERATE 10
Definition at line 291 of file triangle.c.
Referenced by sweeplinedelaunay().
#define sbond(edge1, edge2)
Value:.nf
(edge1).sh[(edge1).shorient] = sencode(edge2); \
  (edge2).sh[(edge2).shorient] = sencode(edge1)
Definition at line 1070 of file triangle.c.
Referenced by insertsite().
#define sdecode(sptr, edge)
Value:.nf
(edge).shorient = (int) ((unsigned long) (sptr) & (unsigned long) 1l); \
  (edge).sh = (shelle *) \
              ((unsigned long) (sptr) & ~ (unsigned long) 3l)
Definition at line 1002 of file triangle.c.
Referenced by printshelle(), and printtriangle().
#define sdest(edge, pointptr) pointptr = (point) (edge).sh[3 - (edge).shorient]
Definition at line 1051 of file triangle.c.
Referenced by checkedge4encroach(), printshelle(), repairencs(), and writepoly().
#define sdissolve(edge) (edge).sh[(edge).shorient] = (shelle) dummysh
Definition at line 1077 of file triangle.c.
#define sencode(edge) (shelle) ((unsigned long) (edge).sh | (unsigned long) (edge).shorient)
Definition at line 1011 of file triangle.c.
#define setapex(triedge, pointptr) (triedge).tri[(triedge).orient + 3] = (triangle) pointptr
Definition at line 928 of file triangle.c.
Referenced by boundingbox(), divconqrecurse(), flip(), insertsite(), mergehulls(), reconstruct(), and sweeplinedelaunay().
#define setareabound(triedge, value) ((REAL *) (triedge).tri)[areaboundindex] = value
Definition at line 990 of file triangle.c.
Referenced by insertsite(), maketriangle(), reconstruct(), and regionplague().
#define setdest(triedge, pointptr) (triedge).tri[minus1mod3[(triedge).orient] + 3] = (triangle) pointptr
Definition at line 925 of file triangle.c.
Referenced by boundingbox(), divconqrecurse(), flip(), insertsite(), mergehulls(), reconstruct(), and sweeplinedelaunay().
#define setelemattribute(triedge, attnum, value) ((REAL *) (triedge).tri)[elemattribindex + (attnum)] = value
Definition at line 983 of file triangle.c.
Referenced by carveholes(), insertsite(), maketriangle(), reconstruct(), and regionplague().
#define setmark(edge, value) * (int *) ((edge).sh + 6) = value
Definition at line 1065 of file triangle.c.
Referenced by infecthull(), insertshelle(), makeshelle(), plague(), and reconstruct().
#define setorg(triedge, pointptr) (triedge).tri[plus1mod3[(triedge).orient] + 3] = (triangle) pointptr
Definition at line 922 of file triangle.c.
Referenced by boundingbox(), check4deadevent(), deletesite(), divconqrecurse(), flip(), insertsite(), mergehulls(), plague(), reconstruct(), and sweeplinedelaunay().
#define setpoint2tri(pt, value) ((triangle *) (pt))[point2triindex] = value
Definition at line 1136 of file triangle.c.
Referenced by makepointmap().
#define setpointmark(pt, value) ((int *) (pt))[pointmarkindex] = value
Definition at line 1131 of file triangle.c.
Referenced by conformingedge(), highorder(), infecthull(), insertshelle(), numbernodes(), plague(), pointdealloc(), readnodes(), removebox(), removeghosts(), repairencs(), segmentintersection(), splittriangle(), and writenodes().
#define setsdest(edge, pointptr) (edge).sh[3 - (edge).shorient] = (shelle) pointptr
Definition at line 1057 of file triangle.c.
Referenced by insertshelle(), insertsite(), and reconstruct().
#define setsorg(edge, pointptr) (edge).sh[2 + (edge).shorient] = (shelle) pointptr
Definition at line 1054 of file triangle.c.
Referenced by insertshelle(), and reconstruct().
#define setvertices2null(triedge)
Value:.nf
(triedge).tri[3] = (triangle) NULL; \
  (triedge).tri[4] = (triangle) NULL; \
  (triedge).tri[5] = (triangle) NULL;
Definition at line 931 of file triangle.c.
#define shellecopy(edge1, edge2)
Value:.nf
(edge2).sh = (edge1).sh; \
  (edge2).shorient = (edge1).shorient
Definition at line 1082 of file triangle.c.
Referenced by checkedge4encroach(), and insertsite().
#define shelleequal(edge1, edge2)
Value:.nf
(((edge1).sh == (edge2).sh) && \
   ((edge1).shorient == (edge2).shorient))
Definition at line 1088 of file triangle.c.
#define SHELLEPERBLOCK 508
Definition at line 260 of file triangle.c.
Referenced by initializetrisegpools().
#define snext(edge1, edge2)
Value:.nf
sptr = (edge1).sh[1 - (edge1).shorient]; \
  sdecode(sptr, edge2)
Definition at line 1037 of file triangle.c.
#define snextself(edge)
Value:.nf
sptr = (edge).sh[1 - (edge).shorient]; \
  sdecode(sptr, edge)
Definition at line 1041 of file triangle.c.
Referenced by repairencs().
#define sorg(edge, pointptr) pointptr = (point) (edge).sh[2 + (edge).shorient]
Definition at line 1048 of file triangle.c.
Referenced by checkedge4encroach(), printshelle(), reconstruct(), repairencs(), and writepoly().
#define spivot(edge1, edge2)
Value:.nf
sptr = (edge1).sh[(edge1).shorient]; \
  sdecode(sptr, edge2)
Definition at line 1026 of file triangle.c.
Referenced by insertsite().
#define spivotself(edge)
Value:.nf
sptr = (edge).sh[(edge).shorient]; \
  sdecode(sptr, edge)
Definition at line 1030 of file triangle.c.
#define SPLAYNODEPERBLOCK 508
Definition at line 268 of file triangle.c.
Referenced by sweeplinedelaunay().
#define Split(a, ahi, alo)
Value:.nf
c = (REAL) (splitter * a); \
  abig = (REAL) (c - a); \
  ahi = c - abig; \
  alo = a - ahi
Definition at line 3945 of file triangle.c.
Referenced by scale_expansion_zeroelim().
#define Square(a, x, y)
Value:.nf
x = (REAL) (a * a); \
  Square_Tail(a, x, y)
Definition at line 3982 of file triangle.c.
Referenced by incircleadapt().
#define Square_Tail(a, x, y)
Value:.nf
Split(a, ahi, alo); \
  err1 = x - (ahi * ahi); \
  err3 = err1 - ((ahi + ahi) * alo); \
  y = (alo * alo) - err3
Definition at line 3976 of file triangle.c.
#define SQUAREROOTTWO 1.4142135623730950488016887242096980785696718753769480732
Definition at line 299 of file triangle.c.
Referenced by repairencs().
#define ssym(edge1, edge2)
Value:.nf
(edge2).sh = (edge1).sh; \
  (edge2).shorient = 1 - (edge1).shorient
Definition at line 1016 of file triangle.c.
Referenced by checkedge4encroach().
#define ssymself(edge) (edge).shorient = 1 - (edge).shorient
Definition at line 1020 of file triangle.c.
Referenced by insertshelle(), and insertsite().
#define STARTINDEX 1
Referenced by parsecommandline().
#define stdissolve(edge) (edge).sh[4 + (edge).shorient] = (shelle) dummytri
Definition at line 1122 of file triangle.c.
Referenced by plague().
#define stpivot(edge, triedge)
Value:.nf
ptr = (triangle) (edge).sh[4 + (edge).shorient]; \
  decode(ptr, triedge)
Definition at line 1105 of file triangle.c.
Referenced by checkedge4encroach(), and repairencs().
#define sym(triedge1, triedge2)
Value:.nf
ptr = (triedge1).tri[(triedge1).orient]; \
  decode(ptr, triedge2);
Definition at line 808 of file triangle.c.
Referenced by checkdelaunay(), checkmesh(), delaunayfixup(), deletesite(), flip(), highorder(), insertshelle(), insertsite(), mergehulls(), plague(), preciselocate(), reconstruct(), regionplague(), removebox(), removeghosts(), repairencs(), sweeplinedelaunay(), triangulatepolygon(), writeedges(), writeneighbors(), and writevoronoi().
#define symself(triedge)
Value:.nf
ptr = (triedge).tri[(triedge).orient]; \
  decode(ptr, triedge);
Definition at line 812 of file triangle.c.
Referenced by carveholes(), infecthull(), insertsegment(), insertsite(), locate(), markhull(), mergehulls(), removebox(), removeghosts(), and sweeplinedelaunay().
#define triedgecopy(triedge1, triedge2)
Value:.nf
(triedge2).tri = (triedge1).tri; \
  (triedge2).orient = (triedge1).orient
Definition at line 952 of file triangle.c.
Referenced by carveholes(), conformingedge(), divconqrecurse(), enqueuebadtri(), frontlocate(), infecthull(), insertsegment(), insertsite(), locate(), markhull(), mergehulls(), preciselocate(), removebox(), removeghosts(), scoutsegment(), splay(), splayinsert(), sweeplinedelaunay(), and triangulatepolygon().
#define triedgeequal(triedge1, triedge2)
Value:.nf
(((triedge1).tri == (triedge2).tri) && \
   ((triedge1).orient == (triedge2).orient))
Definition at line 958 of file triangle.c.
Referenced by deletesite(), frontlocate(), infecthull(), markhull(), plague(), removebox(), removeghosts(), and sweeplinedelaunay().
#define TRIPERBLOCK 4092
Definition at line 259 of file triangle.c.
Referenced by initializetrisegpools(), and locate().
#define tsbond(triedge, edge)
Value:.nf
(triedge).tri[6 + (triedge).orient] = (triangle) sencode(edge); \
  (edge).sh[4 + (edge).shorient] = (shelle) encode(triedge)
Definition at line 1111 of file triangle.c.
Referenced by deletesite(), flip(), insertshelle(), insertsite(), and reconstruct().
#define tsdissolve(triedge) (triedge).tri[6 + (triedge).orient] = (triangle) dummysh
Definition at line 1117 of file triangle.c.
Referenced by flip(), insertsite(), plague(), and reconstruct().
#define tspivot(triedge, edge)
Value:.nf
sptr = (shelle) (triedge).tri[6 + (triedge).orient]; \
  sdecode(sptr, edge)
Definition at line 1098 of file triangle.c.
Referenced by checkdelaunay(), conformingedge(), constrainededge(), delaunayfixup(), deletesite(), flip(), highorder(), infecthull(), insertshelle(), insertsite(), plague(), regionplague(), repairencs(), scoutsegment(), testtriangle(), and writeedges().
#define Two_Diff(a, b, x, y)
Value:.nf
x = (REAL) (a - b); \
  Two_Diff_Tail(a, b, x, y)
Definition at line 3941 of file triangle.c.
#define Two_Diff_Tail(a, b, x, y)
Value:.nf
bvirt = (REAL) (a - x); \
  avirt = x + bvirt; \
  bround = bvirt - b; \
  around = a - avirt; \
  y = around + bround
Definition at line 3934 of file triangle.c.
Referenced by counterclockwiseadapt(), and incircleadapt().
#define Two_One_Diff(a1, a0, b, x2, x1, x0)
Value:.nf
Two_Diff(a0, b , _i, x0); \
  Two_Sum( a1, _i, x2, x1)
Definition at line 3993 of file triangle.c.
#define Two_One_Sum(a1, a0, b, x2, x1, x0)
Value:.nf
Two_Sum(a0, b , _i, x0); \
  Two_Sum(a1, _i, x2, x1)
Definition at line 3989 of file triangle.c.
#define Two_Product(a, b, x, y)
Value:.nf
x = (REAL) (a * b); \
  Two_Product_Tail(a, b, x, y)
Definition at line 3959 of file triangle.c.
Referenced by counterclockwiseadapt(), and incircleadapt().
#define Two_Product_Presplit(a, b, bhi, blo, x, y)
Value:.nf
x = (REAL) (a * b); \
  Split(a, ahi, alo); \
  err1 = x - (ahi * bhi); \
  err2 = err1 - (alo * bhi); \
  err3 = err2 - (ahi * blo); \
  y = (alo * blo) - err3
Definition at line 3966 of file triangle.c.
Referenced by scale_expansion_zeroelim().
#define Two_Product_Tail(a, b, x, y)
Value:.nf
Split(a, ahi, alo); \
  Split(b, bhi, blo); \
  err1 = x - (ahi * bhi); \
  err2 = err1 - (alo * bhi); \
  err3 = err2 - (ahi * blo); \
  y = (alo * blo) - err3
Definition at line 3951 of file triangle.c.
#define Two_Sum(a, b, x, y)
Value:.nf
x = (REAL) (a + b); \
  Two_Sum_Tail(a, b, x, y)
Definition at line 3930 of file triangle.c.
Referenced by fast_expansion_sum_zeroelim(), and scale_expansion_zeroelim().
#define Two_Sum_Tail(a, b, x, y)
Value:.nf
bvirt = (REAL) (x - a); \
  avirt = x - bvirt; \
  bround = b - bvirt; \
  around = a - avirt; \
  y = around + bround
Definition at line 3923 of file triangle.c.
#define Two_Two_Diff(a1, a0, b1, b0, x3, x2, x1, x0)
Value:.nf
Two_One_Diff(a1, a0, b0, _j, _0, x0); \
  Two_One_Diff(_j, _0, b1, x3, x2, x1)
Definition at line 4001 of file triangle.c.
Referenced by counterclockwiseadapt(), and incircleadapt().
#define Two_Two_Sum(a1, a0, b1, b0, x3, x2, x1, x0)
Value:.nf
Two_One_Sum(a1, a0, b0, _j, _0, x0); \
  Two_One_Sum(_j, _0, b1, x3, x2, x1)
Definition at line 3997 of file triangle.c.
Referenced by incircleadapt().
#define uninfect(triedge)
Value:.nf
(triedge).tri[6] = (triangle) \
                     ((unsigned long) (triedge).tri[6] & ~ (unsigned long) 2l)
Definition at line 969 of file triangle.c.
Referenced by plague(), and regionplague().
#define VIRUSPERBLOCK 1020
Definition at line 262 of file triangle.c.
Referenced by carveholes().
#define VOID int
Definition at line 280 of file triangle.c.
Typedef Documentation
typedef REAL* point
Definition at line 515 of file triangle.c.
Referenced by alternateaxes(), boundingbox(), carveholes(), check4deadevent(), checkdelaunay(), checkedge4encroach(), checkmesh(), circletop(), circletopinsert(), conformingedge(), constrainededge(), counterclockwise(), counterclockwiseadapt(), createeventheap(), delaunayfixup(), deletesite(), divconqdelaunay(), divconqrecurse(), enqueuebadtri(), findcircumcenter(), finddirection(), flip(), formskeleton(), frontlocate(), getpoint(), highorder(), incircle(), incircleadapt(), incrementaldelaunay(), infecthull(), insertsegment(), insertshelle(), insertsite(), locate(), main(), makepointmap(), makering(), map(), mergehulls(), numbernodes(), plague(), pointdealloc(), pointmedian(), pointsort(), pointtraverse(), preciselocate(), printshelle(), printtriangle(), quality_statistics(), readnodes(), reconstruct(), regionplague(), removebox(), removeghosts(), repairencs(), rightofhyperbola(), scoutsegment(), segmentintersection(), splay(), splayinsert(), splittriangle(), sweeplinedelaunay(), testtriangle(), triangulatepolygon(), writeedges(), writeelements(), writenodes(), writeoff(), writepoly(), and writevoronoi().
typedef REAL** shelle
Definition at line 498 of file triangle.c.
Referenced by checkdelaunay(), conformingedge(), constrainededge(), delaunayfixup(), deletesite(), dummyinit(), flip(), highorder(), infecthull(), insertshelle(), insertsite(), makeshelle(), plague(), reconstruct(), regionplague(), repairencs(), scoutsegment(), shelledealloc(), shelletraverse(), tallyencs(), testtriangle(), writeedges(), and writepoly().
typedef REAL** triangle
Definition at line 482 of file triangle.c.
Enumeration Type Documentation
enum circumcenterresult
Enumeration values:
OPPOSITEORG
OPPOSITEDEST
OPPOSITEAPEX
Definition at line 366 of file triangle.c.
Referenced by findcircumcenter(), and splittriangle().
enum finddirectionresult
Enumeration values:
WITHIN
LEFTCOLLINEAR
RIGHTCOLLINEAR
Definition at line 361 of file triangle.c.
Referenced by finddirection(), scoutsegment(), and segmentintersection().
enum insertsiteresult
Enumeration values:
SUCCESSFULPOINT
ENCROACHINGPOINT
VIOLATINGPOINT
DUPLICATEPOINT
Definition at line 353 of file triangle.c.
Referenced by conformingedge(), insertsite(), repairencs(), segmentintersection(), and splittriangle().
enum locateresult
Enumeration values:
INTRIANGLE
ONEDGE
ONVERTEX
OUTSIDE
Definition at line 346 of file triangle.c.
Referenced by carveholes(), insertsite(), locate(), and preciselocate().
enum wordtype
Enumeration values:
POINTER
FLOATINGPOINT
Definition at line 340 of file triangle.c.
Referenced by poolinit().
Function Documentation
void alternateaxes (point * sortarray, int arraysize, int axis)
Definition at line 7103 of file triangle.c.
References point, and pointmedian().
Referenced by divconqdelaunay().
void badsegmentdealloc (struct edge * dyingseg)
Definition at line 3713 of file triangle.c.
References badsegments, pooldealloc(), and VOID.
Referenced by repairencs().
struct edge* badsegmenttraverse ()
Definition at line 3732 of file triangle.c.
References badsegments, and traverse().
Referenced by repairencs().
void boundingbox ()
* Definition at line 7766 of file triangle.c.
References dummytri, exit(), infpoint1, infpoint2, infpoint3, memorypool::itembytes, maketriangle(), malloc(), point, points, printtriangle(), REAL, setapex, setdest, setorg, triedge::tri, triangle, verbose, xmax, xmin, ymax, and ymin.
Referenced by incrementaldelaunay().
void carveholes (REAL * holelist, int holes, REAL * regionlist, int regions)
Definition at line 10428 of file triangle.c.
References convex, counterclockwise(), dest, dummytri, eextras, exit(), free(), holes, i, infect, infected, infecthull(), memorypool::items, locate(), locateresult, malloc(), noholes, org, triedge::orient, OUTSIDE, plague(), point, POINTER, poolalloc(), pooldeinit(), poolinit(), quiet, REAL, refine, regionattrib, regionplague(), regions, setelemattribute, symself, traversalinit(), triedge::tri, triangle, triangles, triangletraverse(), triedgecopy, vararea, verbose, viri, VIRUSPERBLOCK, xmax, xmin, ymax, and ymin.
Referenced by main().
void check4deadevent (struct triedge * checktri, struct event ** freeevents, struct event ** eventheap, int * heapsize)
Definition at line 8189 of file triangle.c.
References eventheapdelete(), org, point, setorg, and VOID.
Referenced by sweeplinedelaunay().
void checkdelaunay ()
Definition at line 5169 of file triangle.c.
References apex, checksegments, dest, dummysh, dummytri, incircle(), noexact, org, triedge::orient, point, printtriangle(), quiet, edge::sh, shelle, sym, traversalinit(), triedge::tri, triangle, triangles, triangletraverse(), and tspivot.
Referenced by main().
int checkedge4encroach (struct edge * testedge)
Definition at line 5344 of file triangle.c.
References apex, badsegments, dummytri, nobisect, point, poolalloc(), sdest, shellecopy, sorg, ssym, stpivot, triedge::tri, triangle, and verbose.
Referenced by insertsite(), repairencs(), and tallyencs().
void checkmesh ()
* Definition at line 5077 of file triangle.c.
References apex, counterclockwise(), dest, dummytri, noexact, org, triedge::orient, point, printtriangle(), quiet, sym, traversalinit(), triedge::tri, triangle, triangles, and triangletraverse().
Referenced by main().
REAL circletop (point pa, point pb, point pc, REAL ccwabc)
Definition at line 8161 of file triangle.c.
References circletopcount, point, and REAL.
Referenced by sweeplinedelaunay().
struct splaynode* circletopinsert (struct splaynode * splayroot, struct triedge * newkey, point pa, point pb, point pc, REAL topy)
Definition at line 8356 of file triangle.c.
References counterclockwise(), dummytri, point, REAL, splay(), and splayinsert().
Referenced by sweeplinedelaunay().
void conformingedge (point endpoint1, point endpoint2, int newmark)
Definition at line 9439 of file triangle.c.
References DUPLICATEPOINT, i, insertsite(), insertsiteresult, internalerror(), nextras, org, point, pointdealloc(), points, poolalloc(), scoutsegment(), setpointmark, shelle, steinerleft, SUCCESSFULPOINT, triedge::tri, triangle, triedgecopy, tspivot, verbose, and VIOLATINGPOINT.
Referenced by insertsegment().
void constrainededge (struct triedge * starttri, point endpoint2, int newmark)
Definition at line 9666 of file triangle.c.
References counterclockwise(), delaunayfixup(), dummysh, flip(), insertshelle(), lnext, lprevself, oprev, oprevself, org, point, REAL, scoutsegment(), segmentintersection(), edge::sh, shelle, triangle, and tspivot.
Referenced by insertsegment().
REAL counterclockwise (point pa, point pb, point pc)
Definition at line 4335 of file triangle.c.
References ccwerrboundA, counterclockcount, counterclockwiseadapt(), det(), noexact, point, and REAL.
Referenced by carveholes(), checkmesh(), circletopinsert(), constrainededge(), delaunayfixup(), divconqrecurse(), findcircumcenter(), finddirection(), insertsite(), locate(), mergehulls(), preciselocate(), quality_statistics(), and sweeplinedelaunay().
REAL counterclockwiseadapt (point pa, point pb, point pc, REAL detsum)
Definition at line 4251 of file triangle.c.
References Absolute, B, c, ccwerrboundB, ccwerrboundC, det(), estimate(), fast_expansion_sum_zeroelim(), INEXACT, point, REAL, resulterrbound, t0, Two_Diff_Tail, Two_Product, and Two_Two_Diff.
Referenced by counterclockwise().
void createeventheap (struct event *** eventheap, struct event ** events, struct event ** freeevents)
Definition at line 8090 of file triangle.c.
References eventheapinsert(), exit(), i, inpoints, malloc(), point, points, pointtraverse(), traversalinit(), and VOID.
Referenced by sweeplinedelaunay().
long delaunay ()
* Definition at line 8632 of file triangle.c.
References divconqdelaunay(), eextras, incremental, incrementaldelaunay(), initializetrisegpools(), quiet, sweepline, and sweeplinedelaunay().
Referenced by main().
void delaunayfixup (struct triedge * fixuptri, int leftside)
Definition at line 9555 of file triangle.c.
References apex, counterclockwise(), dest, dummysh, dummytri, flip(), incircle(), lnext, lprevself, org, point, edge::sh, shelle, sym, triedge::tri, triangle, and tspivot.
Referenced by constrainededge().
void deletesite (struct triedge * deltri)
Definition at line 6830 of file triangle.c.
References bond, dnext, dummysh, dummytri, internalerror(), lprev, nobisect, onext, onextself, oprev, org, point, pointdealloc(), setorg, edge::sh, shelle, sym, testtriangle(), triedge::tri, triangle, triangledealloc(), triangulatepolygon(), triedgeequal, tsbond, tspivot, and verbose.
Referenced by splittriangle().
struct badface* dequeuebadtri ()
Definition at line 5306 of file triangle.c.
References badface::nextface, queuefront, and queuetail.
Referenced by enforcequality().
long divconqdelaunay ()
Definition at line 7683 of file triangle.c.
References alternateaxes(), divconqrecurse(), dwyer, exit(), free(), i, inpoints, j, malloc(), point, points, pointsort(), pointtraverse(), quiet, removeghosts(), traversalinit(), and verbose.
Referenced by delaunay().
void divconqrecurse (point * sortarray, int vertices, int axis, struct triedge * farleft, struct triedge * farright)
Definition at line 7472 of file triangle.c.
References bond, counterclockwise(), lnext, lnextself, lprev, lprevself, maketriangle(), mergehulls(), point, printtriangle(), REAL, setapex, setdest, setorg, triedgecopy, and verbose.
Referenced by divconqdelaunay().
void dummyinit (int trianglewords, int shellewords)
Definition at line 3435 of file triangle.c.
References memorypool::alignbytes, dummysh, dummyshbase, dummytri, dummytribase, exit(), malloc(), shelle, shelles, shwords, triangle, triangles, triwords, and useshelles.
Referenced by initializetrisegpools().
void enforcequality ()
Definition at line 11020 of file triangle.c.
References BADSEGMENTPERBLOCK, badsegments, badtriangles, BADTRIPERBLOCK, dequeuebadtri(), fixedarea, i, memorypool::items, minangle, POINTER, poolinit(), queuefront, queuetail, quiet, repairencs(), splittriangle(), steinerleft, tallyencs(), tallyfaces(), vararea, and verbose.
Referenced by main().
void enqueuebadtri (struct triedge * instri, REAL angle, point insapex, point insorg, point insdest)
Definition at line 5257 of file triangle.c.
References angle, badtriangles, badface::nextface, point, poolalloc(), queuetail, REAL, triedgecopy, and verbose.
Referenced by testtriangle().
REAL estimate (int elen, REAL * e)
Definition at line 4217 of file triangle.c.
References e, and REAL.
Referenced by counterclockwiseadapt(), and incircleadapt().
void eventheapdelete (struct event ** heap, int heapsize, int eventnum)
Definition at line 8052 of file triangle.c.
References eventheapify(), and REAL.
Referenced by check4deadevent(), and sweeplinedelaunay().
void eventheapify (struct event ** heap, int heapsize, int eventnum)
Definition at line 8001 of file triangle.c.
References REAL.
Referenced by eventheapdelete().
void eventheapinsert (struct event ** heap, int heapsize, struct event * newevent)
* Definition at line 7965 of file triangle.c.
References REAL.
Referenced by createeventheap(), and sweeplinedelaunay().
void exactinit ()
Definition at line 4024 of file triangle.c.
References ccwerrboundA, ccwerrboundB, ccwerrboundC, epsilon, iccerrboundA, iccerrboundB, iccerrboundC, REAL, resulterrbound, splitter, and verbose.
Referenced by triangleinit().
void exit ()
Referenced by addfiltercondition(), alloc_grays(), alloc_shades(), argserror(), boundingbox(), carveholes(), copyitemcontents(), cpgellipses(), createeventheap(), deleteheaderitem(), deleteobjectitem(), dispose(), divconqdelaunay(), dofilter(), dummyinit(), error_exit(), fastmap(), formskeleton(), forward_fft(), get_fft(), getaddress(), getargs(), getheaderitemaddress(), getobjectitem(), getobjectitemindex(), getobjects(), getop(), gettype(), iis_error(), info(), inheritcontents(), internalerror(), inverse_fft(), main(), make_pixmap(), makecell(), makeXImage(), myworkproc1(), newitem(), newitembydimarray(), newop(), newopitem(), newtonraphson(), nrerror(), openfits(), openiispipe(), openiostream(), outputrcat(), parsecommandline(), poolalloc(), poolinit(), quit_button_callback(), ran1(), readcathead(), readholes(), readitem(), readline(), readmergedcat(), readnewitem(), readnodes(), reconstruct(), repairencs(), set_fft(), setaddress(), setheaderitemaddress(), size(), smprofile(), sscanitem(), sscannewitem(), startfilter(), sweeplinedelaunay(), syntax(), Syntax(), writeedges(), writeelements(), writeitem(), writeneighbors(), writenodes(), writeoff(), writepoly(), and writevoronoi().
int fast_expansion_sum_zeroelim (int elen, REAL * e, int flen, REAL * f, REAL * h)
Definition at line 4077 of file triangle.c.
References e, f, Fast_Two_Sum, h, INEXACT, REAL, and Two_Sum.
Referenced by counterclockwiseadapt(), and incircleadapt().
enum circumcenterresult findcircumcenter (point torg, point tdest, point tapex, point circumcenter, REAL * xi, REAL * eta)
Definition at line 10844 of file triangle.c.
References circumcentercount, circumcenterresult, counterclockcount, counterclockwise(), dx, dy, noexact, OPPOSITEAPEX, OPPOSITEDEST, OPPOSITEORG, point, and REAL.
Referenced by splittriangle(), and writevoronoi().
enum finddirectionresult finddirection (struct triedge * searchtri, point endpoint)
* Definition at line 9174 of file triangle.c.
References apex, counterclockwise(), dest, dummytri, finddirectionresult, internalerror(), LEFTCOLLINEAR, onext, onextself, oprevself, org, point, REAL, RIGHTCOLLINEAR, triedge::tri, triangle, and WITHIN.
Referenced by scoutsegment(), and segmentintersection().
char* findfield (char * string)
Definition at line 11229 of file triangle.c.
char* findfield ()
Referenced by formskeleton(), readholes(), readnodes(), and reconstruct().
void finishfile (FILE * outfile, int argc, char ** argv)
Definition at line 11642 of file triangle.c.
References i.
Referenced by writeedges(), writeelements(), writeneighbors(), writenodes(), writeoff(), writepoly(), and writevoronoi().
void flip (struct triedge * flipedge)
Definition at line 6008 of file triangle.c.
References apex, bond, checksegments, dest, dummysh, dummytri, lnext, lnextself, lprev, org, point, printtriangle(), setapex, setdest, setorg, edge::sh, shelle, sym, triedge::tri, triangle, tsbond, tsdissolve, tspivot, and verbose.
Referenced by constrainededge(), delaunayfixup(), sweeplinedelaunay(), and triangulatepolygon().
int formskeleton (FILE * polyfile, char * polyfilename)
Definition at line 9910 of file triangle.c.
References convex, exit(), findfield(), firstnumber, getpoint(), i, inpoints, inpolyfilename, INPUTLINESIZE, insertsegment(), makepointmap(), markhull(), point, poly, quiet, readline(), strtol(), and verbose.
Referenced by main().
void free ()
Referenced by amoeba(), amotry(), apphot(), average(), avsigclip2(), cartesiantokepler(), carveholes(), cdl_applyZscale(), cdl_close(), cdl_displayFITS(), cdl_displayIRAF(), cdl_getFITSPixels(), cdl_getIRAFPixels(), cdl_readFITSHdr(), cdl_readHeader(), cdl_removeMarker(), cdl_zscale(), closeiostream(), copystring(), cpgellipses(), cycleimage(), disposeof(), divconqdelaunay(), doplot(), dosky(), eps_close(), f1dim(), fdo_stats(), findmode(), fitLine(), fixholes(), fk42gal(), fk52gal(), forward_cfft(), forward_fft(), fread_fits_line(), free3DFloatArray(), free_convert_matrix(), free_cvector(), free_dmatrix(), free_dvector(), free_f3tensor(), free_fft(), free_imatrix(), free_ivector(), free_lvector(), free_matrix(), free_submatrix(), free_vector(), freecathead(), freecell(), freeFloatArray(), freeitem(), freeitemcontents(), freeobject(), freepolygon(), freeShortArray(), fwrite_fits(), gal2fk4(), gal2fk5(), getop(), iis_display(), iis_drawcirc(), imd_close(), imd_displayImage(), imd_readSubRaster(), imd_writeImage(), imd_writeSubRaster(), inverse_cfft(), inverse_fft(), invertmatrix(), jpl_close_ephemeris(), kernel_filter(), linmin(), linmodelsolve(), main(), make_pixmap(), makeitemlist(), myfftwcfft(), pooldeinit(), powell(), print_im(), process(), readitem(), readmergedcat(), reconstruct(), removebox(), sampleImage(), scrunch_stream(), sscanitem(), tcl(), triangledeinit(), updatelinebuffer(), vx_iisclose(), vx_iisio(), vx_initFrame(), wcsinit(), and writename().
struct splaynode* frontlocate (struct splaynode * splayroot, struct triedge * bottommost, point searchpoint, struct triedge * searchtri, int * farright)
Definition at line 8387 of file triangle.c.
References onextself, point, rightofhyperbola(), splay(), triangle, triedgecopy, and triedgeequal.
Referenced by sweeplinedelaunay().
point getpoint (int number)
Definition at line 3759 of file triangle.c.
References memorypool::alignbytes, memorypool::firstblock, firstnumber, memorypool::itemsperblock, memorypool::itemwords, number, point, points, and VOID.
Referenced by formskeleton(), and reconstruct().
void highorder ()
* Definition at line 11109 of file triangle.c.
References memorypool::deaditemstack, dest, dummysh, dummytri, highorderindex, i, mark, nextras, org, triedge::orient, point, points, poolalloc(), quiet, setpointmark, edge::sh, shelle, sym, traversalinit(), triedge::tri, triangle, triangles, triangletraverse(), tspivot, useshelles, verbose, and VOID.
Referenced by main().
REAL incircle (point pa, point pb, point pc, point pd)
Definition at line 4970 of file triangle.c.
References Absolute, det(), iccerrboundA, incircleadapt(), incirclecount, noexact, point, and REAL.
Referenced by checkdelaunay(), delaunayfixup(), insertsite(), mergehulls(), and triangulatepolygon().
REAL incircleadapt (point pa, point pb, point pc, point pd, REAL permanent)
Definition at line 4396 of file triangle.c.
References Absolute, c, det(), estimate(), fast_expansion_sum_zeroelim(), iccerrboundB, iccerrboundC, INEXACT, point, REAL, resulterrbound, scale_expansion_zeroelim(), Square, Two_Diff_Tail, Two_Product, Two_Two_Diff, Two_Two_Sum, and v.
Referenced by incircle().
long incrementaldelaunay ()
Definition at line 7918 of file triangle.c.
References boundingbox(), DUPLICATEPOINT, i, insertsite(), point, points, pointtraverse(), quiet, removebox(), traversalinit(), triedge::tri, triangle, and verbose.
Referenced by delaunay().
void infecthull ()
* Definition at line 10049 of file triangle.c.
References dest, dummysh, dummytri, infect, infected, lnextself, mark, oprev, org, triedge::orient, point, pointmark, poolalloc(), setmark, setpointmark, edge::sh, shelle, symself, triedge::tri, triangle, triedgecopy, triedgeequal, tspivot, verbose, and viri.
Referenced by carveholes().
void info ()
Definition at line 1226 of file triangle.c.
References exit().
Referenced by alloc_grays(), alloc_shades(), and parsecommandline().
void initializepointpool ()
Definition at line 3518 of file triangle.c.
References FLOATINGPOINT, mesh_dim, nextras, point2triindex, POINTER, pointmarkindex, POINTPERBLOCK, points, poly, poolinit(), REAL, and triangle.
Referenced by readnodes().
void initializetrisegpools ()
Definition at line 3549 of file triangle.c.
References areaboundindex, dummyinit(), eextras, elemattribindex, highorderindex, memorypool::itemwords, neighbors, order, POINTER, poolinit(), REAL, regionattrib, SHELLEPERBLOCK, shelles, triangle, triangles, TRIPERBLOCK, useshelles, vararea, and voronoi.
Referenced by delaunay(), and reconstruct().
void insertsegment (point endpoint1, point endpoint2, int newmark)
Definition at line 9760 of file triangle.c.
References conformingedge(), constrainededge(), decode, dummytri, internalerror(), locate(), ONVERTEX, org, triedge::orient, point, point2tri, recenttri, scoutsegment(), splitseg, symself, triedge::tri, triangle, triedgecopy, and verbose.
Referenced by formskeleton().
void insertshelle (struct triedge * tri, int shellemark)
* Definition at line 5909 of file triangle.c.
References dest, dummysh, makeshelle(), mark, org, point, pointmark, printshelle(), setmark, setpointmark, setsdest, setsorg, edge::sh, shelle, ssymself, sym, triangle, tsbond, tspivot, and verbose.
Referenced by constrainededge(), insertsite(), markhull(), reconstruct(), and scoutsegment().
enum insertsiteresult insertsite (point insertpoint, struct triedge * searchtri, struct edge * splitedge, int segmentflaws, int triflaws)
Definition at line 6151 of file triangle.c.
References apex, areabound, badsegments, bond, checkedge4encroach(), checksegments, counterclockwise(), dest, dummysh, dummytri, DUPLICATEPOINT, eextras, elemattribute, ENCROACHINGPOINT, hullsize, i, incircle(), infpoint1, infpoint2, infpoint3, insertshelle(), insertsiteresult, lnext, lnextself, locate(), locateresult, lprev, lprevself, maketriangle(), mark, nobisect, ONEDGE, ONVERTEX, org, triedge::orient, OUTSIDE, point, poolalloc(), preciselocate(), printtriangle(), REAL, recenttri, sbond, setapex, setareabound, setdest, setelemattribute, setorg, setsdest, edge::sh, shelle, shellecopy, spivot, ssymself, SUCCESSFULPOINT, sym, symself, testtriangle(), triedge::tri, triangle, triedgecopy, tsbond, tsdissolve, tspivot, vararea, verbose, and VIOLATINGPOINT.
Referenced by conformingedge(), incrementaldelaunay(), repairencs(), segmentintersection(), and splittriangle().
void internalerror ()
Definition at line 2657 of file triangle.c.
References exit().
Referenced by conformingedge(), deletesite(), finddirection(), insertsegment(), repairencs(), and segmentintersection().
enum locateresult locate (point searchpoint, struct triedge * searchtri)
Definition at line 5771 of file triangle.c.
References memorypool::alignbytes, counterclockwise(), dest, dist, memorypool::firstblock, i, memorypool::items, memorypool::itemwords, j, lnextself, locateresult, memorypool::maxitems, ONEDGE, ONVERTEX, org, triedge::orient, point, preciselocate(), randomnation(), REAL, recenttri, SAMPLEFACTOR, samples, symself, triedge::tri, triangle, triangles, triedgecopy, TRIPERBLOCK, verbose, and VOID.
Referenced by carveholes(), insertsegment(), and insertsite().
int main (int argc, char ** argv)
Definition at line 12921 of file triangle.c.
References areafilename, carveholes(), checkdelaunay(), checkmesh(), checksegments, convex, delaunay(), docheck, edgefilename, edges, edgesout, eextras, enforcequality(), formskeleton(), free(), geomview, highorder(), holes, hullsize, inelefilename, infpoint1, infpoint2, infpoint3, innodefilename, inpolyfilename, insegments, memorypool::items, l, neighborfilename, neighbors, nextras, noelewritten, noiterationnum, nonodewritten, nopolywritten, numbernodes(), offfilename, order, outelefilename, outnodefilename, outpolyfilename, parsecommandline(), point, points, poly, quality, quiet, readholes(), readnodefile, readnodes(), REAL, reconstruct(), refine, regions, shelles, statistics(), triangledeinit(), triangleinit(), triangles, useshelles, vedgefilename, vnodefilename, voronoi, writeedges(), writeelements(), writeneighbors(), writenodes(), writeoff(), writepoly(), and writevoronoi().
void makepointmap ()
* Definition at line 5552 of file triangle.c.
References encode, org, triedge::orient, point, setpoint2tri, traversalinit(), triedge::tri, triangle, triangles, triangletraverse(), and verbose.
Referenced by formskeleton().
void makeshelle (struct edge * newedge)
Definition at line 3861 of file triangle.c.
References dummysh, dummytri, poolalloc(), setmark, shelle, and shelles.
Referenced by insertshelle(), and reconstruct().
void maketriangle (struct triedge * newtriedge)
* Definition at line 3824 of file triangle.c.
References dummysh, dummytri, eextras, i, poolalloc(), setareabound, setelemattribute, triangle, triangles, useshelles, and vararea.
Referenced by boundingbox(), divconqrecurse(), insertsite(), mergehulls(), reconstruct(), and sweeplinedelaunay().
void* malloc ()
Referenced by boundingbox(), carveholes(), cdl_applyZscale(), cdl_doPolygonMark(), cdl_getFITSPixels(), cdl_getIRAFPixels(), cdl_getPixRegion(), cdl_initBoxMarker(), cdl_initLineMarker(), cdl_initPointLabelMarker(), cdl_initPolygonMarker(), cdl_initPolylineMarker(), cdl_initTextMarker(), cdl_mapFrame(), cdl_markBox(), cdl_markCircAnnuli(), cdl_markCircle(), cdl_markEllipAnnuli(), cdl_markEllipse(), cdl_markLine(), cdl_markPoint(), cdl_markPointLabel(), cdl_markPolygon(), cdl_markPolyline(), cdl_markText(), cdl_readFITSHdr(), cdl_readFrameBuffer(), cdl_readHeader(), cdl_readImage(), cdl_readSubRaster(), com_readData(), convert_matrix(), createeventheap(), cvector(), divconqdelaunay(), dmatrix(), dummyinit(), dvector(), eps_setLabel(), eps_setTransform(), eqstrn(), f3tensor(), fitLine(), imatrix(), imd_displayImage(), imd_loadImtoolrc(), imd_open(), imd_readFrameBuffer(), imd_readImage(), imd_readSubRaster(), imd_writeImage(), imd_writeSubRaster(), ivector(), lvector(), make_pixmap(), makeXImage(), matrix(), poolalloc(), poolinit(), readholes(), reconstruct(), sampleImage(), submatrix(), vector(), vx_iisio(), vx_initFrame(), writeedges(), writeelements(), writeneighbors(), writenodes(), writepoly(), and writevoronoi().
void markhull ()
Definition at line 9864 of file triangle.c.
References dummytri, insertshelle(), lnextself, oprev, triedge::orient, symself, triedge::tri, triangle, triedgecopy, and triedgeequal.
Referenced by formskeleton().
void mergehulls (struct triedge * farleft, struct triedge * innerleft, struct triedge * innerright, struct triedge * farright, int axis)
Definition at line 7162 of file triangle.c.
References apex, bond, counterclockwise(), dest, dwyer, incircle(), lnext, lnextself, lprev, lprevself, maketriangle(), org, point, printtriangle(), setapex, setdest, setorg, sym, symself, triangle, triedgecopy, and verbose.
Referenced by divconqrecurse().
void numbernodes ()
Definition at line 11799 of file triangle.c.
References firstnumber, point, points, pointtraverse(), setpointmark, and traversalinit().
Referenced by main().
void parsecommandline (int argc, char ** argv)
Definition at line 2674 of file triangle.c.
References areafilename, convex, docheck, dwyer, edgefilename, edgesout, exit(), FILENAMESIZE, firstnumber, fixedarea, geomview, goodangle, i, incremental, inelefilename, info(), innodefilename, inpolyfilename, j, k, maxarea, minangle, neighborfilename, neighbors, nobisect, nobound, noelewritten, noexact, noholes, noiterationnum, nonodewritten, nopolywritten, offfilename, order, outelefilename, outnodefilename, outpolyfilename, PI, poly, quality, quiet, REAL, refine, regionattrib, splitseg, STARTINDEX, steiner, steinerleft, strtod(), sweepline, syntax(), useshelles, vararea, vedgefilename, verbose, vnodefilename, and voronoi.
Referenced by main().
void plague ()
Definition at line 10122 of file triangle.c.
References apex, dest, dissolve, dummysh, dummytri, hullsize, infect, infected, mark, onext, onextself, oprev, oprevself, org, triedge::orient, point, pointdealloc(), pointmark, poolalloc(), poolrestart(), setmark, setorg, setpointmark, edge::sh, shelle, shelledealloc(), stdissolve, sym, traversalinit(), traverse(), triedge::tri, triangle, triangledealloc(), triedgeequal, tsdissolve, tspivot, uninfect, verbose, and viri.
Referenced by carveholes().
void pointdealloc (point dyingpoint)
Definition at line 3676 of file triangle.c.
References DEADPOINT, point, points, pooldealloc(), setpointmark, and VOID.
Referenced by conformingedge(), deletesite(), plague(), reconstruct(), and splittriangle().
void pointmedian (point * sortarray, int arraysize, int median, int axis)
Definition at line 7030 of file triangle.c.
References median(), point, randomnation(), and REAL.
Referenced by alternateaxes().
void pointsort (point * sortarray, int arraysize)
* Definition at line 6961 of file triangle.c.
References point, randomnation(), and REAL.
Referenced by divconqdelaunay().
point pointtraverse ()
Definition at line 3691 of file triangle.c.
References DEADPOINT, point, pointmark, points, and traverse().
Referenced by createeventheap(), divconqdelaunay(), incrementaldelaunay(), numbernodes(), writenodes(), and writeoff().
VOID* poolalloc (struct memorypool * pool)
Definition at line 3272 of file triangle.c.
References exit(), malloc(), newitem(), POINTER, REAL, and VOID.
Referenced by carveholes(), checkedge4encroach(), conformingedge(), enqueuebadtri(), highorder(), infecthull(), insertsite(), makeshelle(), maketriangle(), plague(), readnodes(), regionplague(), repairencs(), segmentintersection(), splayinsert(), and splittriangle().
void pooldealloc (struct memorypool * pool, VOID * dyingitem)
Definition at line 3335 of file triangle.c.
References VOID.
Referenced by badsegmentdealloc(), pointdealloc(), shelledealloc(), splay(), splittriangle(), and triangledealloc().
void pooldeinit (struct memorypool * pool)
Definition at line 3256 of file triangle.c.
References free(), and VOID.
Referenced by carveholes(), sweeplinedelaunay(), and triangledeinit().
void poolinit (struct memorypool * pool, int bytecount, int itemcount, enum wordtype wtype, int alignment)
* Definition at line 3174 of file triangle.c.
References exit(), malloc(), POINTER, poolrestart(), REAL, VOID, and wordtype.
Referenced by carveholes(), enforcequality(), initializepointpool(), initializetrisegpools(), and sweeplinedelaunay().
void poolrestart (struct memorypool * pool)
Definition at line 3228 of file triangle.c.
References VOID.
void poolrestart ()
Referenced by plague(), poolinit(), and regionplague().
enum locateresult preciselocate (point searchpoint, struct triedge * searchtri)
Definition at line 5637 of file triangle.c.
References apex, counterclockwise(), dest, dummytri, INTRIANGLE, lnext, lnextself, locateresult, lprev, lprevself, ONEDGE, ONVERTEX, org, OUTSIDE, point, REAL, sym, triangle, triedgecopy, and verbose.
Referenced by insertsite(), and locate().
void precisionerror ()
Definition at line 10638 of file triangle.c.
Referenced by repairencs(), and splittriangle().
void printshelle (struct edge * s)
Definition at line 3094 of file triangle.c.
References decode, dummysh, dummytri, mark, triedge::orient, point, sdecode, sdest, edge::sh, edge::shorient, sorg, and triedge::tri.
Referenced by insertshelle().
void printtriangle (struct triedge * t)
* Definition at line 3010 of file triangle.c.
References apex, areabound, decode, dest, dummysh, dummytri, org, triedge::orient, point, sdecode, edge::sh, edge::shorient, t, triedge::tri, useshelles, and vararea.
Referenced by boundingbox(), checkdelaunay(), checkmesh(), divconqrecurse(), flip(), insertsite(), and mergehulls().
void quality_statistics ()
* Definition at line 12614 of file triangle.c.
References apex, counterclockwise(), dest, dx, dy, i, j, k, minus1mod3, org, triedge::orient, PI, plus1mod3, point, REAL, traversalinit(), triedge::tri, triangle, triangles, triangletraverse(), xmax, xmin, ymax, and ymin.
Referenced by statistics().
unsigned long randomnation (unsigned int choices)
Definition at line 5058 of file triangle.c.
References l, and randomseed.
Referenced by locate(), pointmedian(), pointsort(), and sweeplinedelaunay().
void readholes (FILE * polyfile, char * polyfilename, REAL ** hlist, int * holes, REAL ** rlist, int * regions)
Definition at line 11524 of file triangle.c.
References exit(), findfield(), firstnumber, holes, i, INPUTLINESIZE, malloc(), readline(), REAL, refine, regionattrib, regions, strtod(), strtol(), and vararea.
Referenced by main().
char* readline (char * string, FILE * infile, char * infilename)
* Definition at line 11190 of file triangle.c.
References exit(), and INPUTLINESIZE.
char* readline ()
Referenced by formskeleton(), readholes(), readnodes(), and reconstruct().
void readnodes (char * nodefilename, char * polyfilename, FILE ** polyfile)
Definition at line 11265 of file triangle.c.
References exit(), findfield(), firstnumber, i, initializepointpool(), innodefilename, inpoints, INPUTLINESIZE, j, mesh_dim, nextras, point, points, poly, poolalloc(), quiet, readline(), readnodefile, REAL, setpointmark, strtod(), strtol(), x, xmax, xmin, xminextreme, y, ymax, and ymin.
Referenced by main().
long reconstruct (char * elefilename, char * areafilename, char * polyfilename, FILE * polyfile)
Definition at line 8708 of file triangle.c.
References apex, areafilename, bond, DEADPOINT, decode, dest, dummytri, eextras, encode, exit(), findfield(), firstnumber, free(), getpoint(), hullsize, i, inelements, initializetrisegpools(), inpoints, inpolyfilename, INPUTLINESIZE, insegments, insertshelle(), memorypool::items, j, lprev, makeshelle(), maketriangle(), malloc(), triedge::orient, point, pointdealloc(), pointmark, points, poly, quiet, readline(), REAL, setapex, setareabound, setdest, setelemattribute, setmark, setorg, setsdest, setsorg, edge::sh, shelle, shelles, shelletraverse(), edge::shorient, sorg, strtod(), strtol(), sym, traversalinit(), triedge::tri, triangle, triangles, triangletraverse(), tsbond, tsdissolve, vararea, and verbose.
Referenced by main().
void regionplague (REAL attribute, REAL area)
Definition at line 10323 of file triangle.c.
References apex, dest, dummysh, dummytri, eextras, infect, infected, org, triedge::orient, point, poolalloc(), poolrestart(), REAL, regionattrib, setareabound, setelemattribute, edge::sh, shelle, sym, traversalinit(), traverse(), triedge::tri, triangle, tspivot, uninfect, vararea, verbose, and viri.
Referenced by carveholes().
long removebox ()
Definition at line 7828 of file triangle.c.
References dissolve, dummytri, encode, free(), hullsize, infpoint1, infpoint2, infpoint3, l, lnext, lnextself, lprev, lprevself, org, triedge::orient, point, pointmark, poly, setpointmark, sym, symself, triedge::tri, triangle, triangledealloc(), triedgecopy, triedgeequal, and verbose.
Referenced by incrementaldelaunay().
long removeghosts (struct triedge * startghost)
Definition at line 7627 of file triangle.c.
References dissolve, dummytri, encode, hullsize, lnext, lprev, lprevself, org, point, pointmark, poly, setpointmark, sym, symself, triedge::tri, triangle, triangledealloc(), triedgecopy, triedgeequal, and verbose.
Referenced by divconqdelaunay(), and sweeplinedelaunay().
void repairencs (int flaws)
Definition at line 10670 of file triangle.c.
References badsegmentdealloc(), badsegments, badsegmenttraverse(), checkedge4encroach(), dummysh, dummytri, ENCROACHINGPOINT, exit(), i, insertsite(), insertsiteresult, internalerror(), memorypool::items, lnext, lnextself, mark, nextras, point, points, poolalloc(), precisionerror(), REAL, sdest, setpointmark, edge::sh, shelle, snextself, sorg, SQUAREROOTTWO, steinerleft, stpivot, SUCCESSFULPOINT, sym, traversalinit(), triedge::tri, triangle, tspivot, and verbose.
Referenced by enforcequality().
int rightofhyperbola (struct triedge * fronttri, point newsite)
Definition at line 8129 of file triangle.c.
References apex, dest, hyperbolacount, point, and REAL.
Referenced by frontlocate(), splay(), and splayinsert().
int scale_expansion_zeroelim (int elen, REAL * e, REAL b, REAL * h)
Definition at line 4166 of file triangle.c.
References b, c, e, Fast_Two_Sum, h, INEXACT, REAL, Split, Two_Product_Presplit, and Two_Sum.
Referenced by incircleadapt().
int scoutsegment (struct triedge * searchtri, point endpoint2, int newmark)
Definition at line 9361 of file triangle.c.
References apex, dest, dummysh, finddirection(), finddirectionresult, insertshelle(), LEFTCOLLINEAR, lnext, lnextself, lprevself, org, point, RIGHTCOLLINEAR, segmentintersection(), edge::sh, shelle, triedgecopy, and tspivot.
Referenced by conformingedge(), constrainededge(), and insertsegment().
void segmentintersection (struct triedge * splittri, struct edge * splitshelle, point endpoint2)
Definition at line 9261 of file triangle.c.
References apex, dest, finddirection(), finddirectionresult, i, insertsite(), insertsiteresult, internalerror(), mark, nextras, onextself, org, point, points, poolalloc(), REAL, setpointmark, steinerleft, SUCCESSFULPOINT, triangle, tx, ty, and verbose.
Referenced by constrainededge(), and scoutsegment().
void shelledealloc (shelle * dyingshelle)
Definition at line 3641 of file triangle.c.
References pooldealloc(), shelle, shelles, and VOID.
Referenced by plague().
shelle* shelletraverse ()
Definition at line 3657 of file triangle.c.
References shelle, shelles, and traverse().
Referenced by reconstruct(), tallyencs(), and writepoly().
struct splaynode* splay (struct splaynode * splaytree, point searchpoint, struct triedge * searchtri)
Definition at line 8215 of file triangle.c.
References dest, point, pooldealloc(), rightofhyperbola(), splaynodes, triedgecopy, and VOID.
Referenced by circletopinsert(), and frontlocate().
struct splaynode* splayinsert (struct splaynode * splayroot, struct triedge * newkey, point searchpoint)
Definition at line 8327 of file triangle.c.
References dest, point, poolalloc(), rightofhyperbola(), splaynodes, and triedgecopy.
Referenced by circletopinsert(), and sweeplinedelaunay().
void splittriangle (struct badface * badtri)
Definition at line 10912 of file triangle.c.
References apex, badtriangles, circumcenterresult, deletesite(), dest, ENCROACHINGPOINT, findcircumcenter(), i, insertsite(), insertsiteresult, lnextself, lprevself, nextras, OPPOSITEDEST, OPPOSITEORG, org, point, pointdealloc(), points, poolalloc(), pooldealloc(), precisionerror(), quiet, REAL, setpointmark, steinerleft, SUCCESSFULPOINT, verbose, VIOLATINGPOINT, and VOID.
Referenced by enforcequality().
void statistics ()
Definition at line 12812 of file triangle.c.
References badsegments, badtriangles, circletopcount, circumcentercount, counterclockcount, edges, holes, hullsize, hyperbolacount, incirclecount, inelements, inpoints, insegments, memorypool::itembytes, memorypool::items, memorypool::maxitems, points, poly, quality_statistics(), refine, shelles, splaynodes, triangles, verbose, and viri.
Referenced by main().
double strtod ()
Referenced by parsecommandline(), readholes(), readnodes(), and reconstruct().
long strtol ()
Referenced by formskeleton(), readholes(), readnodes(), and reconstruct().
long sweeplinedelaunay ()
Definition at line 8414 of file triangle.c.
References apex, bond, check4deadevent(), circletop(), circletopinsert(), counterclockwise(), createeventheap(), decode, dest, encode, eventheapdelete(), eventheapinsert(), exit(), flip(), frontlocate(), inpoints, lnext, lnextself, lprev, lprevself, maketriangle(), onext, oprev, org, point, POINTER, pooldeinit(), poolinit(), randomnation(), REAL, removeghosts(), SAMPLERATE, setapex, setdest, setorg, splayinsert(), SPLAYNODEPERBLOCK, splaynodes, sym, symself, triangle, triedgecopy, triedgeequal, verbose, VOID, xmin, and xminextreme.
Referenced by delaunay().
void syntax ()
* Definition at line 1155 of file triangle.c.
References exit().
Referenced by parsecommandline().
void tallyencs ()
* Definition at line 10613 of file triangle.c.
References checkedge4encroach(), edge::sh, shelle, shelles, shelletraverse(), edge::shorient, and traversalinit().
Referenced by enforcequality().
void tallyfaces ()
Definition at line 10811 of file triangle.c.
References triedge::orient, testtriangle(), traversalinit(), triedge::tri, triangle, triangles, triangletraverse(), and verbose.
Referenced by enforcequality().
void testtriangle (struct triedge * testtri)
Definition at line 5426 of file triangle.c.
References angle, apex, areabound, dest, dummysh, enqueuebadtri(), fixedarea, goodangle, lnext, lnextself, lprev, maxarea, org, PI, point, quiet, REAL, edge::sh, shelle, tspivot, and vararea.
Referenced by deletesite(), insertsite(), tallyfaces(), and triangulatepolygon().
void traversalinit (struct memorypool * pool)
Definition at line 3353 of file triangle.c.
References VOID.
Referenced by carveholes(), checkdelaunay(), checkmesh(), createeventheap(), divconqdelaunay(), highorder(), incrementaldelaunay(), makepointmap(), numbernodes(), plague(), quality_statistics(), reconstruct(), regionplague(), repairencs(), tallyencs(), tallyfaces(), writeedges(), writeelements(), writeneighbors(), writenodes(), writeoff(), writepoly(), and writevoronoi().
VOID* traverse (struct memorypool * pool)
Definition at line 3384 of file triangle.c.
References newitem(), POINTER, REAL, and VOID.
Referenced by badsegmenttraverse(), plague(), pointtraverse(), regionplague(), shelletraverse(), and triangletraverse().
void triangledealloc (triangle * dyingtriangle)
Definition at line 3605 of file triangle.c.
References pooldealloc(), triangle, triangles, and VOID.
Referenced by deletesite(), plague(), removebox(), and removeghosts().
void triangledeinit ()
Definition at line 3791 of file triangle.c.
References badsegments, badtriangles, dummyshbase, dummytribase, fixedarea, free(), minangle, points, pooldeinit(), quality, shelles, triangles, useshelles, and vararea.
Referenced by main().
void triangleinit ()
* Definition at line 5032 of file triangle.c.
References badsegments, badtriangles, checksegments, circletopcount, circumcentercount, counterclockcount, exactinit(), hyperbolacount, incirclecount, memorypool::itembytes, l, memorypool::maxitems, points, randomseed, recenttri, samples, shelles, splaynodes, triedge::tri, triangle, triangles, and viri.
Referenced by main().
triangle* triangletraverse ()
Definition at line 3622 of file triangle.c.
References traverse(), triangle, and triangles.
Referenced by carveholes(), checkdelaunay(), checkmesh(), highorder(), makepointmap(), quality_statistics(), reconstruct(), tallyfaces(), writeedges(), writeelements(), writeneighbors(), writeoff(), and writevoronoi().
void triangulatepolygon (struct triedge * firstedge, struct triedge * lastedge, int edgecount, int doflip, int triflaws)
Definition at line 6742 of file triangle.c.
References apex, dest, flip(), i, incircle(), onext, onextself, oprev, point, sym, testtriangle(), triangle, triedgecopy, and verbose.
Referenced by deletesite().
void writeedges (char * edgefilename, int argc, char ** argv)
Definition at line 12094 of file triangle.c.
References dest, dummysh, dummytri, edgefilename, edges, exit(), finishfile(), firstnumber, malloc(), mark, nobound, org, triedge::orient, point, pointmark, quiet, edge::sh, shelle, sym, traversalinit(), triedge::tri, triangle, triangles, triangletraverse(), tspivot, and useshelles.
Referenced by main().
void writeelements (char * elefilename, int argc, char ** argv)
Definition at line 11828 of file triangle.c.
References apex, dest, eextras, elemattribute, exit(), finishfile(), firstnumber, highorderindex, i, memorypool::items, malloc(), order, org, triedge::orient, point, pointmark, quiet, REAL, traversalinit(), triedge::tri, triangle, triangles, and triangletraverse().
Referenced by main().
void writeneighbors (char * neighborfilename, int argc, char ** argv)
Definition at line 12454 of file triangle.c.
References dummytri, exit(), finishfile(), firstnumber, memorypool::items, malloc(), neighborfilename, triedge::orient, quiet, sym, traversalinit(), triedge::tri, triangle, triangles, and triangletraverse().
Referenced by main().
void writenodes (char * nodefilename, int argc, char ** argv)
Definition at line 11678 of file triangle.c.
References exit(), finishfile(), firstnumber, i, memorypool::items, malloc(), mesh_dim, nextras, nobound, point, pointmark, points, pointtraverse(), quiet, REAL, setpointmark, and traversalinit().
Referenced by main().
void writeoff (char * offfilename, int argc, char ** argv)
Definition at line 12554 of file triangle.c.
References apex, dest, edges, exit(), finishfile(), memorypool::items, offfilename, org, triedge::orient, point, pointmark, points, pointtraverse(), quiet, traversalinit(), triedge::tri, triangle, triangles, and triangletraverse().
Referenced by main().
void writepoly (char * polyfilename, REAL * holelist, int holes, REAL * regionlist, int regions, int argc, char ** argv)
Definition at line 11961 of file triangle.c.
References exit(), finishfile(), firstnumber, holes, i, memorypool::items, malloc(), mark, mesh_dim, nextras, nobound, point, pointmark, quiet, REAL, regions, sdest, edge::sh, shelle, shelles, shelletraverse(), edge::shorient, sorg, and traversalinit().
Referenced by main().
void writevoronoi (char * vnodefilename, char * vedgefilename, int argc, char ** argv)
Definition at line 12247 of file triangle.c.
References apex, dest, dummytri, edges, exit(), findcircumcenter(), finishfile(), firstnumber, i, memorypool::items, malloc(), nextras, org, triedge::orient, point, quiet, REAL, sym, traversalinit(), triedge::tri, triangle, triangles, triangletraverse(), vedgefilename, and vnodefilename.
Referenced by main().
Variable Documentation
int areaboundindex
Definition at line 645 of file triangle.c.
Referenced by initializetrisegpools().
char areafilename[FILENAMESIZE]
Definition at line 716 of file triangle.c.
Referenced by main(), parsecommandline(), and reconstruct().
struct memorypool badsegments
Definition at line 617 of file triangle.c.
Referenced by badsegmentdealloc(), badsegmenttraverse(), checkedge4encroach(), enforcequality(), insertsite(), repairencs(), statistics(), triangledeinit(), and triangleinit().
struct memorypool badtriangles
Definition at line 618 of file triangle.c.
Referenced by enforcequality(), enqueuebadtri(), splittriangle(), statistics(), triangledeinit(), and triangleinit().
REAL ccwerrboundA
Definition at line 654 of file triangle.c.
Referenced by counterclockwise(), and exactinit().
REAL ccwerrboundB
Definition at line 654 of file triangle.c.
Referenced by counterclockwiseadapt(), and exactinit().
REAL ccwerrboundC
Definition at line 654 of file triangle.c.
Referenced by counterclockwiseadapt(), and exactinit().
int checksegments
Definition at line 646 of file triangle.c.
Referenced by checkdelaunay(), flip(), insertsite(), main(), and triangleinit().
long circletopcount
Definition at line 661 of file triangle.c.
Referenced by circletop(), statistics(), and triangleinit().
long circumcentercount
Definition at line 660 of file triangle.c.
Referenced by findcircumcenter(), statistics(), and triangleinit().
int convex
Definition at line 694 of file triangle.c.
Referenced by carveholes(), formskeleton(), main(), and parsecommandline().
long counterclockcount
Definition at line 658 of file triangle.c.
Referenced by counterclockwise(), findcircumcenter(), statistics(), and triangleinit().
int docheck
Definition at line 701 of file triangle.c.
Referenced by main(), and parsecommandline().
shelle* dummysh
Definition at line 740 of file triangle.c.
Referenced by checkdelaunay(), constrainededge(), delaunayfixup(), deletesite(), dummyinit(), flip(), highorder(), infecthull(), insertshelle(), insertsite(), makeshelle(), maketriangle(), plague(), printshelle(), printtriangle(), regionplague(), repairencs(), scoutsegment(), testtriangle(), and writeedges().
shelle* dummyshbase
Definition at line 741 of file triangle.c.
Referenced by dummyinit(), and triangledeinit().
triangle* dummytri
Definition at line 733 of file triangle.c.
Referenced by boundingbox(), carveholes(), checkdelaunay(), checkedge4encroach(), checkmesh(), circletopinsert(), delaunayfixup(), deletesite(), dummyinit(), finddirection(), flip(), highorder(), infecthull(), insertsegment(), insertsite(), makeshelle(), maketriangle(), markhull(), plague(), preciselocate(), printshelle(), printtriangle(), reconstruct(), regionplague(), removebox(), removeghosts(), repairencs(), writeedges(), writeneighbors(), and writevoronoi().
triangle* dummytribase
Definition at line 734 of file triangle.c.
Referenced by dummyinit(), and triangledeinit().
int dwyer
Definition at line 699 of file triangle.c.
Referenced by divconqdelaunay(), mergehulls(), and parsecommandline().
char edgefilename[FILENAMESIZE]
Definition at line 720 of file triangle.c.
Referenced by main(), parsecommandline(), and writeedges().
long edges
Definition at line 634 of file triangle.c.
Referenced by cdl_selectFB(), main(), statistics(), writeedges(), writeoff(), and writevoronoi().
int edgesout
Definition at line 696 of file triangle.c.
Referenced by main(), and parsecommandline().
int eextras
Definition at line 637 of file triangle.c.
Referenced by carveholes(), delaunay(), initializetrisegpools(), insertsite(), main(), maketriangle(), reconstruct(), regionplague(), and writeelements().
int elemattribindex
Definition at line 644 of file triangle.c.
Referenced by initializetrisegpools().
REAL epsilon
Definition at line 652 of file triangle.c.
Referenced by exactinit().
int firstnumber
Definition at line 695 of file triangle.c.
Referenced by formskeleton(), getpoint(), numbernodes(), parsecommandline(), readholes(), readnodes(), reconstruct(), writeedges(), writeelements(), writeneighbors(), writenodes(), writepoly(), and writevoronoi().
int fixedarea
Definition at line 694 of file triangle.c.
Referenced by enforcequality(), parsecommandline(), testtriangle(), and triangledeinit().
int geomview
Definition at line 696 of file triangle.c.
Referenced by main(), and parsecommandline().
REAL goodangle
Definition at line 707 of file triangle.c.
Referenced by parsecommandline(), and testtriangle().
int highorderindex
Definition at line 643 of file triangle.c.
Referenced by highorder(), initializetrisegpools(), and writeelements().
int holes
Definition at line 632 of file triangle.c.
Referenced by carveholes(), main(), readholes(), statistics(), and writepoly().
long hullsize
Definition at line 638 of file triangle.c.
Referenced by insertsite(), main(), plague(), reconstruct(), removebox(), removeghosts(), and statistics().
long hyperbolacount
Definition at line 659 of file triangle.c.
Referenced by rightofhyperbola(), statistics(), and triangleinit().
REAL iccerrboundA
Definition at line 655 of file triangle.c.
Referenced by exactinit(), and incircle().
REAL iccerrboundB
Definition at line 655 of file triangle.c.
Referenced by exactinit(), and incircleadapt().
REAL iccerrboundC
Definition at line 655 of file triangle.c.
Referenced by exactinit(), and incircleadapt().
long incirclecount
Definition at line 657 of file triangle.c.
Referenced by incircle(), statistics(), and triangleinit().
int incremental
Definition at line 699 of file triangle.c.
Referenced by delaunay(), and parsecommandline().
char inelefilename[FILENAMESIZE]
Definition at line 714 of file triangle.c.
Referenced by main(), and parsecommandline().
int inelements
Definition at line 630 of file triangle.c.
Referenced by reconstruct(), and statistics().
point infpoint1
Definition at line 729 of file triangle.c.
Referenced by boundingbox(), insertsite(), main(), and removebox().
point infpoint2
Definition at line 729 of file triangle.c.
Referenced by boundingbox(), insertsite(), main(), and removebox().
point infpoint3
Definition at line 729 of file triangle.c.
Referenced by boundingbox(), insertsite(), main(), and removebox().
char innodefilename[FILENAMESIZE]
Definition at line 713 of file triangle.c.
Referenced by main(), parsecommandline(), and readnodes().
int inpoints
Definition at line 629 of file triangle.c.
Referenced by createeventheap(), divconqdelaunay(), formskeleton(), readnodes(), reconstruct(), statistics(), and sweeplinedelaunay().
char inpolyfilename[FILENAMESIZE]
Definition at line 715 of file triangle.c.
Referenced by formskeleton(), main(), parsecommandline(), and reconstruct().
int insegments
Definition at line 631 of file triangle.c.
Referenced by main(), reconstruct(), and statistics().
REAL maxarea
Definition at line 708 of file triangle.c.
Referenced by parsecommandline(), and testtriangle().
int mesh_dim
Definition at line 635 of file triangle.c.
Referenced by initializepointpool(), readnodes(), writenodes(), and writepoly().
REAL minangle
Definition at line 707 of file triangle.c.
Referenced by enforcequality(), parsecommandline(), and triangledeinit().
int minus1mod3[3] = {2, 0, 1}
Definition at line 779 of file triangle.c.
Referenced by quality_statistics().
char neighborfilename[FILENAMESIZE]
Definition at line 723 of file triangle.c.
Referenced by main(), parsecommandline(), and writeneighbors().
int neighbors
Definition at line 696 of file triangle.c.
Referenced by initializetrisegpools(), main(), and parsecommandline().
int nextras
Definition at line 636 of file triangle.c.
Referenced by conformingedge(), highorder(), initializepointpool(), main(), readnodes(), repairencs(), segmentintersection(), splittriangle(), writenodes(), writepoly(), and writevoronoi().
int nobisect
Definition at line 705 of file triangle.c.
Referenced by checkedge4encroach(), deletesite(), insertsite(), and parsecommandline().
int nobound
Definition at line 697 of file triangle.c.
Referenced by parsecommandline(), writeedges(), writenodes(), and writepoly().
int noelewritten
Definition at line 697 of file triangle.c.
Referenced by main(), and parsecommandline().
int noexact
Definition at line 698 of file triangle.c.
Referenced by checkdelaunay(), checkmesh(), counterclockwise(), findcircumcenter(), incircle(), and parsecommandline().
int noholes
Definition at line 698 of file triangle.c.
Referenced by carveholes(), and parsecommandline().
int noiterationnum
Definition at line 697 of file triangle.c.
Referenced by main(), and parsecommandline().
int nonodewritten
Definition at line 697 of file triangle.c.
Referenced by main(), and parsecommandline().
int nopolywritten
Definition at line 697 of file triangle.c.
Referenced by main(), and parsecommandline().
char offfilename[FILENAMESIZE]
Definition at line 724 of file triangle.c.
Referenced by main(), parsecommandline(), and writeoff().
int order
Definition at line 704 of file triangle.c.
Referenced by initializetrisegpools(), main(), parsecommandline(), readamplitudes(), slaDeuler(), writeamplitudes(), and writeelements().
char outelefilename[FILENAMESIZE]
Definition at line 718 of file triangle.c.
Referenced by main(), and parsecommandline().
char outnodefilename[FILENAMESIZE]
Definition at line 717 of file triangle.c.
Referenced by main(), and parsecommandline().
char outpolyfilename[FILENAMESIZE]
Definition at line 719 of file triangle.c.
Referenced by main(), and parsecommandline().
int plus1mod3[3] = {1, 2, 0}
* Definition at line 778 of file triangle.c.
Referenced by quality_statistics().
int point2triindex
Definition at line 642 of file triangle.c.
Referenced by initializepointpool().
int pointmarkindex
Definition at line 641 of file triangle.c.
Referenced by initializepointpool().
struct memorypool points
Definition at line 615 of file triangle.c.
Referenced by boundingbox(), conformingedge(), createeventheap(), divconqdelaunay(), getpoint(), highorder(), incrementaldelaunay(), initializepointpool(), main(), numbernodes(), pointdealloc(), pointtraverse(), readnodes(), reconstruct(), repairencs(), segmentintersection(), splittriangle(), statistics(), triangledeinit(), triangleinit(), writenodes(), and writeoff().
int poly
Definition at line 694 of file triangle.c.
Referenced by formskeleton(), initializepointpool(), main(), parsecommandline(), readnodes(), reconstruct(), removebox(), removeghosts(), and statistics().
int quality
Definition at line 694 of file triangle.c.
Referenced by main(), parsecommandline(), and triangledeinit().
struct badface* queuefront[64]
Definition at line 624 of file triangle.c.
Referenced by dequeuebadtri(), and enforcequality().
struct badface** queuetail[64]
Definition at line 625 of file triangle.c.
Referenced by dequeuebadtri(), enforcequality(), and enqueuebadtri().
int quiet
Definition at line 702 of file triangle.c.
Referenced by carveholes(), checkdelaunay(), checkmesh(), delaunay(), divconqdelaunay(), enforcequality(), formskeleton(), highorder(), incrementaldelaunay(), main(), parsecommandline(), readnodes(), reconstruct(), splittriangle(), testtriangle(), writeedges(), writeelements(), writeneighbors(), writenodes(), writeoff(), writepoly(), and writevoronoi().
unsigned long randomseed
Definition at line 649 of file triangle.c.
Referenced by randomnation(), and triangleinit().
int readnodefile
Definition at line 647 of file triangle.c.
Referenced by main(), and readnodes().
struct triedge recenttri
Definition at line 746 of file triangle.c.
Referenced by insertsegment(), insertsite(), locate(), and triangleinit().
int refine
Definition at line 694 of file triangle.c.
Referenced by carveholes(), main(), parsecommandline(), readholes(), and statistics().
int regionattrib
Definition at line 694 of file triangle.c.
Referenced by carveholes(), initializetrisegpools(), parsecommandline(), readholes(), and regionplague().
int regions
Definition at line 633 of file triangle.c.
Referenced by carveholes(), main(), readholes(), and writepoly().
REAL resulterrbound
Definition at line 653 of file triangle.c.
Referenced by counterclockwiseadapt(), exactinit(), and incircleadapt().
long samples
Definition at line 648 of file triangle.c.
Referenced by locate(), and triangleinit().
struct memorypool shelles
Definition at line 614 of file triangle.c.
Referenced by dummyinit(), initializetrisegpools(), main(), makeshelle(), reconstruct(), shelledealloc(), shelletraverse(), statistics(), tallyencs(), triangledeinit(), triangleinit(), and writepoly().
int shwords
Definition at line 640 of file triangle.c.
Referenced by dummyinit().
struct memorypool splaynodes
Definition at line 619 of file triangle.c.
Referenced by splay(), splayinsert(), statistics(), sweeplinedelaunay(), and triangleinit().
int splitseg
Definition at line 700 of file triangle.c.
Referenced by insertsegment(), and parsecommandline().
REAL splitter
Definition at line 651 of file triangle.c.
Referenced by exactinit().
int steiner
Definition at line 706 of file triangle.c.
Referenced by parsecommandline().
int steinerleft
Definition at line 706 of file triangle.c.
Referenced by conformingedge(), enforcequality(), parsecommandline(), repairencs(), segmentintersection(), and splittriangle().
int sweepline
Definition at line 699 of file triangle.c.
Referenced by delaunay(), and parsecommandline().
struct memorypool triangles
Definition at line 613 of file triangle.c.
Referenced by carveholes(), checkdelaunay(), checkmesh(), dummyinit(), highorder(), initializetrisegpools(), locate(), main(), makepointmap(), maketriangle(), quality_statistics(), reconstruct(), statistics(), tallyfaces(), triangledealloc(), triangledeinit(), triangleinit(), triangletraverse(), writeedges(), writeelements(), writeneighbors(), writeoff(), and writevoronoi().
int triwords
Definition at line 639 of file triangle.c.
Referenced by dummyinit().
int useshelles
Definition at line 703 of file triangle.c.
Referenced by dummyinit(), highorder(), initializetrisegpools(), main(), maketriangle(), parsecommandline(), printtriangle(), triangledeinit(), and writeedges().
int vararea
Definition at line 694 of file triangle.c.
Referenced by carveholes(), enforcequality(), initializetrisegpools(), insertsite(), maketriangle(), parsecommandline(), printtriangle(), readholes(), reconstruct(), regionplague(), testtriangle(), and triangledeinit().
char vedgefilename[FILENAMESIZE]
Definition at line 722 of file triangle.c.
Referenced by main(), parsecommandline(), and writevoronoi().
int verbose
Definition at line 702 of file triangle.c.
Referenced by boundingbox(), carveholes(), checkedge4encroach(), conformingedge(), deletesite(), divconqdelaunay(), divconqrecurse(), enforcequality(), enqueuebadtri(), exactinit(), flip(), formskeleton(), highorder(), incrementaldelaunay(), infecthull(), insertsegment(), insertshelle(), insertsite(), locate(), main(), makepointmap(), mergehulls(), parsecommandline(), plague(), preciselocate(), reconstruct(), regionplague(), removebox(), removeghosts(), repairencs(), segmentintersection(), splittriangle(), statistics(), sweeplinedelaunay(), tallyfaces(), and triangulatepolygon().
struct memorypool viri
Definition at line 616 of file triangle.c.
Referenced by carveholes(), infecthull(), plague(), regionplague(), statistics(), and triangleinit().
char vnodefilename[FILENAMESIZE]
Definition at line 721 of file triangle.c.
Referenced by main(), parsecommandline(), and writevoronoi().
int voronoi
Definition at line 696 of file triangle.c.
Referenced by initializetrisegpools(), main(), and parsecommandline().
REAL xmax
Definition at line 627 of file triangle.c.
REAL xmin
Definition at line 627 of file triangle.c.
REAL xminextreme
Definition at line 628 of file triangle.c.
Referenced by readnodes(), and sweeplinedelaunay().
REAL ymax
Definition at line 627 of file triangle.c.
REAL ymin
Definition at line 627 of file triangle.c.
Author
Generated automatically by Doxygen for imcat from the source code.