.TH "triangle" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
triangle \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBL\fP"
.br
.ti -1c
.RI "double \fBM\fP"
.br
.ti -1c
.RI "double \fBS\fP"
.br
.ti -1c
.RI "double \fBphi\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBm\fP"
.br
.ti -1c
.RI "double \fBs\fP"
.br
.ti -1c
.RI "\fBtriangle\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBtriangle\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double \fBtriangle::L\fP"
.PP
Definition at line 21 of file matchtriplets.c.
.PP
Referenced by main().
.SS "double \fBtriangle::m\fP"
.PP
Definition at line 21 of file matchtriplets.c.
.PP
Referenced by main().
.SS "double \fBtriangle::M\fP"
.PP
Definition at line 21 of file matchtriplets.c.
.PP
Referenced by main().
.SS "struct \fBtriangle\fP* \fBtriangle::next\fP"
.PP
Definition at line 22 of file matchtriplets.c.
.SS "struct \fBtriangle\fP* \fBtriangle::next\fP"
.PP
Definition at line 26 of file matchobjects.c.
.PP
Referenced by main().
.SS "double \fBtriangle::phi\fP"
.PP
Definition at line 21 of file matchtriplets.c.
.PP
Referenced by main().
.SS "double \fBtriangle::s\fP"
.PP
Definition at line 21 of file matchtriplets.c.
.PP
Referenced by main().
.SS "double \fBtriangle::S\fP"
.PP
Definition at line 21 of file matchtriplets.c.
.PP
Referenced by main().
.SS "double \fBtriangle::x\fP"
.PP
Definition at line 21 of file matchtriplets.c.
.PP
Referenced by main().
.SS "double \fBtriangle::y\fP"
.PP
Definition at line 21 of file matchtriplets.c.
.PP
Referenced by main().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
