triangulatecat.c
NAME
triangulatecat.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'triangle.h'
#include 'utils/args.h'
#include 'utils/iostream.h'
#include 'utils/ipbuff.h'
#include 'catlib/cat.h'
#include 'imlib/fits.h'
#include 'utils/error.h'
#include 'utils/arrays.h'
#include 'painttriangle.h'
#include 'fixedges.h'
#include 'average.h'
Defines
#define REAL double
#define usage '\nNAME\n\	triangulatecat - Delauney tesselation of a catalogue\n\\n\SYNOPSIS\n\	triangulatecat srccat [-c | -f x1 x2 Nx y1 y2 Ny] [-m | -M]\n\\n\DESCRIPTION\n\	Triangulatecat performs Delauney tesselation using Shewchuk's code.\n\	Input catalog should contain a 2-vector x[2] and scalar or 1-D vector f[N].\n\\n\	Default is to output the triangles x[3][2], f[3][N].\n\	With -c option we output an average cat x[2] = xbar[2], f[N] = fbar[N].\n\	Ditto with -c -m options.\n\	With -c -M options we output a median cat x[2] = xbar[2], f[N] = fmedian[N].\n\	With -f ... option we output a Nx by Ny FITS image consisting of\n\	triangular linear ramp segments, or, with -m or -M options the triangles\n\	are uniform and painted with the mean or median f[] value respectively.\n\\n\	Uses iostream utilities so use '-' for standard input, 'somecommand |' to\n\	read from a process etc.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
#define OP_TRIANGLES 0
#define OP_AVGCAT 1
#define OP_FITS 2
Functions
double mean (double **y, int j)
double median (double **y, int j)
main (int argc, char *argv[])
Define Documentation
#define OP_AVGCAT 1
Definition at line 44 of file triangulatecat.c.
Referenced by main().
#define OP_FITS 2
Definition at line 45 of file triangulatecat.c.
Referenced by main().
#define OP_TRIANGLES 0
Definition at line 43 of file triangulatecat.c.
Referenced by main().
#define REAL double
Definition at line 4 of file triangulatecat.c.
#define usage '\nNAME\n\	triangulatecat - Delauney tesselation of a catalogue\n\\n\SYNOPSIS\n\	triangulatecat srccat [-c | -f x1 x2 Nx y1 y2 Ny] [-m | -M]\n\\n\DESCRIPTION\n\	Triangulatecat performs Delauney tesselation using Shewchuk's code.\n\	Input catalog should contain a 2-vector x[2] and scalar or 1-D vector f[N].\n\\n\	Default is to output the triangles x[3][2], f[3][N].\n\	With -c option we output an average cat x[2] = xbar[2], f[N] = fbar[N].\n\	Ditto with -c -m options.\n\	With -c -M options we output a median cat x[2] = xbar[2], f[N] = fmedian[N].\n\	With -f ... option we output a Nx by Ny FITS image consisting of\n\	triangular linear ramp segments, or, with -m or -M options the triangles\n\	are uniform and painted with the mean or median f[] value respectively.\n\\n\	Uses iostream utilities so use '-' for standard input, 'somecommand |' to\n\	read from a process etc.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 17 of file triangulatecat.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 50 of file triangulatecat.c.
References add_comment(), addargscomment(), object::addrlist, allocFloatArray(), allocobjectcontents(), appendcomment(), argsinit(), c, closeiostream(), connectobjecttocathead(), item::dim, error_exit, exit(), iostream::f, f, F_INTERP, F_MEAN, F_MEDIAN, fits, fixedges(), fixholes(), flag, FLAG_ARG, FLOAT_MAGIC, FLOAT_PIXTYPE, getargd(), getargi(), getargs(), getflag(), getobjectitem(), getobjectitemindex(), i, item::itype, ix, MAX_FITS_DIM, mean(), median(), item::ndim, newfitsheader(), newnumericcomment(), newobject(), object::next, nextargtype(), nobj, NUM_TYPE, Nx, Ny, OP_AVGCAT, OP_FITS, OP_TRIANGLES, openiostream(), opmode, painttriangle(), readcathead(), readobject(), REAL, setcatipf(), t, triangulate(), usage, v, writecathead(), writefitsheader(), writefitsplane(), writefitstail(), writeobject(), and x.
double mean (double ** y, int j)
Definition at line 8 of file average.c.
References c, j, and y.
double median (double ** y, int j)
Definition at line 20 of file average.c.
References j, and y.
Author
Generated automatically by Doxygen for imcat from the source code.