.TH "triedge" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
triedge \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtriangle\fP * \fBtri\fP"
.br
.ti -1c
.RI "int \fBorient\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBtriedge::orient\fP"
.PP
Definition at line 491 of file triangle.c.
.PP
Referenced by carveholes(), checkdelaunay(), checkmesh(), highorder(), infecthull(), insertsegment(), insertsite(), locate(), makepointmap(), markhull(), plague(), printshelle(), printtriangle(), quality_statistics(), reconstruct(), regionplague(), removebox(), tallyfaces(), writeedges(), writeelements(), writeneighbors(), writeoff(), and writevoronoi().
.SS "\fBtriangle\fP* \fBtriedge::tri\fP"
.PP
Definition at line 490 of file triangle.c.
.PP
Referenced by boundingbox(), carveholes(), checkdelaunay(), checkedge4encroach(), checkmesh(), conformingedge(), delaunayfixup(), deletesite(), finddirection(), flip(), highorder(), incrementaldelaunay(), infecthull(), insertsegment(), insertsite(), locate(), makepointmap(), markhull(), plague(), printshelle(), printtriangle(), quality_statistics(), reconstruct(), regionplague(), removebox(), removeghosts(), repairencs(), tallyfaces(), triangleinit(), writeedges(), writeelements(), writeneighbors(), writeoff(), and writevoronoi().

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
