triplets.c
NAME
triplets.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
Defines
#define usage 'usage: triplets [dmax]\n\	reads a list of coords and finds triangles with max side dmax\n\	orders vertices so long, medium and short sides are\n\	L = AB; M = BC; S = CA and prints out\n\	L, M, S, phi, xA, yA where\n\	phi = atan2(yB - yA, xB - xA)\n\n'
#define WHOPPER 1.e10
#define MAX_OBJECTS 1000
#define dist(i, j) sqrt((x[i]-x[j])*(x[i]-x[j])+(y[i]-y[j])*(y[i]-y[j]))
Functions
void print (int ia, int ib, int ic)
main (int argc, char *argv[])
int inorder (double d1, double d2, double d3)
Variables
double x [MAX_OBJECTS]
double y [MAX_OBJECTS]
Define Documentation
#define dist(i, j) sqrt((x[i]-x[j])*(x[i]-x[j])+(y[i]-y[j])*(y[i]-y[j]))
Definition at line 20 of file triplets.c.
#define MAX_OBJECTS 1000
Definition at line 18 of file triplets.c.
#define usage 'usage: triplets [dmax]\n\	reads a list of coords and finds triangles with max side dmax\n\	orders vertices so long, medium and short sides are\n\	L = AB; M = BC; S = CA and prints out\n\	L, M, S, phi, xA, yA where\n\	phi = atan2(yB - yA, xB - xA)\n\n'
Definition at line 10 of file triplets.c.
#define WHOPPER 1.e10
Definition at line 17 of file triplets.c.
Function Documentation
int inorder (double d1, double d2, double d3)
Definition at line 105 of file triplets.c.
Referenced by main().
main (int argc, char * argv[])
Definition at line 25 of file triplets.c.
References dist, dmax, exit(), inorder(), line, n, print(), usage, WHOPPER, x, and y.
void print (int ia, int ib, int ic)
Definition at line 95 of file triplets.c.
References dist, phi, x, and y.
Referenced by main().
Variable Documentation
double x[MAX_OBJECTS]
Definition at line 22 of file triplets.c.
double y[MAX_OBJECTS]
Definition at line 22 of file triplets.c.
Author
Generated automatically by Doxygen for imcat from the source code.