unmergecat.c
NAME
unmergecat.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include '../../utils/error.h'
#include '../../catlib/cat.h'
Defines
#define usage '\n\n\NAME\n\	unmergecat - extract one member from a merged catalogue\n\\n\SYNOPSIS\n\	unmergecat N\n\\n\DESCRIPTION\n\	'unmergecat' reads a merged catalogue created by 'mergecats'.\n\	Ignorring any object items which are not vectors of things\n\	(e.g. the 'detection mask' or number of detections column)\n\	it creates a new catalogue in which each object item\n\	is the (N-1)th element of the item of the same name in the\n\	input catalogue.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Functions
main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\NAME\n\	unmergecat - extract one member from a merged catalogue\n\\n\SYNOPSIS\n\	unmergecat N\n\\n\DESCRIPTION\n\	'unmergecat' reads a merged catalogue created by 'mergecats'.\n\	Ignorring any object items which are not vectors of things\n\	(e.g. the 'detection mask' or number of detections column)\n\	it creates a new catalogue in which each object item\n\	is the (N-1)th element of the item of the same name in the\n\	input catalogue.\n\\n\AUTHOR\n\	Nick Kaiser --- kaiser@cita.utoronto.ca\n\\n\n'
Definition at line 5 of file unmergecat.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 32 of file unmergecat.c.
References addargscomment(), addobjectitem(), item::addr, allocitemcontents(), BINARY_FILE_TYPE, connectobjecttocathead(), copyheaderinfo(), item::dim, error_exit, exit(), i, item::itype, N, item::name, item::ndim, newitem(), newobject(), item::next, cathead::objectitembase, readcathead(), readobject(), setcatopfiletype(), usage, writecathead(), and writeobject().
Author
Generated automatically by Doxygen for imcat from the source code.