unpackextensions.c
NAME
unpackextensions.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
#include '../utils/args.h'
Defines
#define usage '\n\n\n\NAME\n\	unpackextensions --- extract extensions from multi-part FITS file\n\\n\SYNOPSIS\n\	unpackextensions extname fmt\n\\n\DESCRIPTION\n\	\'unpackextensions\' is used to separate a multi-component\n\	FITS file where a number of separate images (of arbitrary\n\	dimensionality) have been packed as extensions.\n\\n\	We first read the primary header, check that it has \n\	EXTEND = T and get the number of extensions from the\n\	NEXTEND header item value.\n\	Then, for each extension, we read the header and image data and\n\	write them to a file with name 'filename' given by\n\		sprintf(filename, fmt, EXTNAME) where\n\	'fmt' is a format string and EXTNAME is the integerized value\n\	of the header item named 'extname'.\n\\n\	For example, to unpack a CFHT archive format CFH12K file\n\	504338o.fits to 504338o00.fits 504338o01.fits ... 504338o11.fits\n\	you can do\n\\n\		unpackextensions IMAGEID 504338o\%.2d.fits < 504338o.fits\n\\n\	since IMAGEID (or CHIPID) contains the chip number as an integer.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	unpackextensions --- extract extensions from multi-part FITS file\n\\n\SYNOPSIS\n\	unpackextensions extname fmt\n\\n\DESCRIPTION\n\	\'unpackextensions\' is used to separate a multi-component\n\	FITS file where a number of separate images (of arbitrary\n\	dimensionality) have been packed as extensions.\n\\n\	We first read the primary header, check that it has \n\	EXTEND = T and get the number of extensions from the\n\	NEXTEND header item value.\n\	Then, for each extension, we read the header and image data and\n\	write them to a file with name 'filename' given by\n\		sprintf(filename, fmt, EXTNAME) where\n\	'fmt' is a format string and EXTNAME is the integerized value\n\	of the header item named 'extname'.\n\\n\	For example, to unpack a CFHT archive format CFH12K file\n\	504338o.fits to 504338o00.fits 504338o01.fits ... 504338o11.fits\n\	you can do\n\\n\		unpackextensions IMAGEID 504338o\%.2d.fits < 504338o.fits\n\\n\	since IMAGEID (or CHIPID) contains the chip number as an integer.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@hawaii.edu\n\\n\n\n'
Definition at line 1 of file unpackextensions.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 46 of file unpackextensions.c.
References argsinit(), error_exit, exit(), fitsheader::extpixtype, fits, flag, FLAG_ARG, free(), getargs(), getcommentbyname(), getnumericvalue(), fitsheader::hasextensions, i, fitsheader::isextension, fitsheader::n, fitsheader::ndim, nextargtype(), fitsheader::nextensions, nim, fitsheader::opstream, pixsize(), readfitsheader(), usage, and writefitsheader().
Author
Generated automatically by Doxygen for imcat from the source code.