unscrunch.c
NAME
unscrunch.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../imlib/fits.h'
#include '../utils/error.h'
Defines
#define usage '\n\n\n\NAME\n\	unscrunch - expand a FITS image by a factor 2\n\\n\SYNOPSIS\n\	unscrunch\n\\n\DESCRIPTION\n\	expands a fits image by a factor 2.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Functions
int main (int argc, char *argv[])
Define Documentation
#define usage '\n\n\n\NAME\n\	unscrunch - expand a FITS image by a factor 2\n\\n\SYNOPSIS\n\	unscrunch\n\\n\DESCRIPTION\n\	expands a fits image by a factor 2.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@cita.utoronto.ca\n\\n\n\n'
Definition at line 1 of file unscrunch.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 25 of file unscrunch.c.
References add_comment(), copyfitsheader(), error_exit, exit(), i, j, fitsheader::n, readfitsheader(), readfitsline(), usage, writefitsheader(), writefitsline(), and writefitstail().
Author
Generated automatically by Doxygen for imcat from the source code.