.TH "usagetemplate.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usagetemplate.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBusage\fP   '\\nNAME\\\fBn\fP\\	command - short description for makewhatis\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	......\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	......\\\fBn\fP\\\\\fBn\fP\\SEE ALSO\\\fBn\fP\\	......\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser --- kaiser@hawaii.edu\\\fBn\fP\\\fBn\fP'"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBusage\fP   '\\nNAME\\\fBn\fP\\	command - short description for makewhatis\\\fBn\fP\\\\\fBn\fP\\SYNOPSIS\\\fBn\fP\\	......\\\fBn\fP\\\\\fBn\fP\\DESCRIPTION\\\fBn\fP\\	......\\\fBn\fP\\\\\fBn\fP\\SEE ALSO\\\fBn\fP\\	......\\\fBn\fP\\\\\fBn\fP\\AUTHOR\\\fBn\fP\\	Nick Kaiser --- kaiser@hawaii.edu\\\fBn\fP\\\fBn\fP'"
.PP
Definition at line 1 of file usagetemplate.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
