.TH "lu.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lu.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBludcmp\fP (double **\fBa\fP, int \fBn\fP, int *\fBindx\fP, double *\fBd\fP)"
.br
.ti -1c
.RI "void \fBlubksb\fP (double **\fBa\fP, int \fBn\fP, int *\fBindx\fP, double *\fBb\fP)"
.br
.ti -1c
.RI "void \fBmyludcmp\fP (double **\fBa\fP, int \fBn\fP, int *\fBindx\fP, double *\fBd\fP)"
.br
.ti -1c
.RI "void \fBmylubksb\fP (double **\fBa\fP, int \fBn\fP, int *\fBindx\fP, double *\fBb\fP)"
.br
.ti -1c
.RI "void \fBinvertmatrix\fP (double **\fBa\fP, double **ainv, int \fBn\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void invertmatrix (double ** a, double ** ainv, int n)"
.PP
Definition at line 112 of file imcattools/orbits/orbitutils/lu.c.
.PP
References a, A, B, d, free(), i, indx, j, mylubksb(), myludcmp(), and n.
.PP
Referenced by main().
.SS "void lubksb (double ** a, int n, int * indx, double * b)"
.PP
Definition at line 89 of file imcattools/orbits/orbitutils/lu.c.
.PP
References a, b, i, indx, j, and n.
.PP
Referenced by mylubksb().
.SS "void ludcmp (double ** a, int n, int * indx, double * d)"
.PP
Definition at line 36 of file imcattools/orbits/orbitutils/lu.c.
.PP
References a, d, dvector(), free_dvector(), i, indx, j, k, n, nrerror(), and TINY.
.PP
Referenced by myludcmp().
.SS "void mylubksb (double ** a, int n, int * indx, double * b)"
.PP
Definition at line 23 of file imcattools/orbits/orbitutils/lu.c.
.PP
References a, b, i, indx, lubksb(), and n.
.PP
Referenced by fitdistortions(), fitextinctions(), fittranslations(), invertmatrix(), linmodelsolve(), and main().
.SS "void myludcmp (double ** a, int n, int * indx, double * d)"
.PP
Definition at line 11 of file imcattools/orbits/orbitutils/lu.c.
.PP
References a, d, i, indx, ludcmp(), and n.
.PP
Referenced by det(), fitdistortions(), fitextinctions(), fittranslations(), invertmatrix(), linmodelsolve(), and main().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
