lu.c
NAME
lu.c -
SYNOPSIS
#include <math.h>
#include 'lu.h'
Defines
#define TINY 1.0e-20;
Functions
void myludcmp (double **a, int n, int *indx, double *d)
void mylubksb (double **a, int n, int *indx, double *b)
void ludcmp (double **a, int n, int *indx, double *d)
void lubksb (double **a, int n, int *indx, double *b)
void invertmatrix (double **a, double **ainv, int n)
Define Documentation
#define TINY 1.0e-20;
Definition at line 9 of file utils/lu.c.
Function Documentation
void invertmatrix (double ** a, double ** ainv, int n)
Definition at line 112 of file utils/lu.c.
References a, A, B, d, free(), i, indx, j, mylubksb(), myludcmp(), and n.
Referenced by main().
void lubksb (double ** a, int n, int * indx, double * b)
Definition at line 89 of file utils/lu.c.
References a, b, i, indx, j, and n.
Referenced by mylubksb().
void ludcmp (double ** a, int n, int * indx, double * d)
Definition at line 36 of file utils/lu.c.
References a, d, dvector(), free_dvector(), i, indx, j, k, n, nrerror(), and TINY.
Referenced by myludcmp().
void mylubksb (double ** a, int n, int * indx, double * b)
Definition at line 23 of file utils/lu.c.
References a, b, i, indx, lubksb(), and n.
Referenced by fitdistortions(), fitextinctions(), fittranslations(), invertmatrix(), linmodelsolve(), and main().
void myludcmp (double ** a, int n, int * indx, double * d)
Definition at line 11 of file utils/lu.c.
References a, d, i, indx, ludcmp(), and n.
Referenced by det(), fitdistortions(), fitextinctions(), fittranslations(), invertmatrix(), linmodelsolve(), and main().
Author
Generated automatically by Doxygen for imcat from the source code.