.TH "error.h" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBerror_exit\fP (char *message)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void error_exit (char * message)"
.PP
miscellaneous service routines Definition at line 10 of file error.c.
.PP
References exit().
.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
