nrutil.c
NAME
nrutil.c -
SYNOPSIS
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include 'nrutil.h'
Defines
#define NR_END 0
#define FREE_ARG char*
Functions
void nrerror (char error_text[])
float * vector (long nl, long nh)
int * ivector (long nl, long nh)
unsigned char * cvector (long nl, long nh)
unsigned long * lvector (long nl, long nh)
double * dvector (long nl, long nh)
float ** matrix (long nrl, long nrh, long ncl, long nch)
double ** dmatrix (long nrl, long nrh, long ncl, long nch)
int ** imatrix (long nrl, long nrh, long ncl, long nch)
float ** submatrix (float **a, long oldrl, long oldrh, long oldcl, long oldch, long newrl, long newcl)
float ** convert_matrix (float *a, long nrl, long nrh, long ncl, long nch)
float *** f3tensor (long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
void free_vector (float *v, long nl, long nh)
void free_ivector (int *v, long nl, long nh)
void free_cvector (unsigned char *v, long nl, long nh)
void free_lvector (unsigned long *v, long nl, long nh)
void free_dvector (double *v, long nl, long nh)
void free_matrix (float **m, long nrl, long nrh, long ncl, long nch)
void free_dmatrix (double **m, long nrl, long nrh, long ncl, long nch)
void free_imatrix (int **m, long nrl, long nrh, long ncl, long nch)
void free_submatrix (float **b, long nrl, long nrh, long ncl, long nch)
void free_convert_matrix (float **b, long nrl, long nrh, long ncl, long nch)
void free_f3tensor (float ***t, long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
Define Documentation
#define FREE_ARG char*
Definition at line 6 of file utils/nrutil.c.
#define NR_END 0
Definition at line 5 of file utils/nrutil.c.
Function Documentation
float** convert_matrix (float * a, long nrl, long nrh, long ncl, long nch)
Definition at line 160 of file utils/nrutil.c.
References a, i, j, m, malloc(), NR_END, and nrerror().
unsigned char* cvector (long nl, long nh)
Definition at line 37 of file utils/nrutil.c.
References malloc(), NR_END, nrerror(), and v.
double** dmatrix (long nrl, long nrh, long ncl, long nch)
Definition at line 91 of file utils/nrutil.c.
References i, m, malloc(), NR_END, and nrerror().
double* dvector (long nl, long nh)
Definition at line 57 of file utils/nrutil.c.
References malloc(), NR_END, nrerror(), and v.
float*** f3tensor (long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
Definition at line 182 of file utils/nrutil.c.
References i, j, malloc(), NR_END, nrerror(), and t.
void free_convert_matrix (float ** b, long nrl, long nrh, long ncl, long nch)
Definition at line 274 of file utils/nrutil.c.
References b, free(), FREE_ARG, and NR_END.
void free_cvector (unsigned char * v, long nl, long nh)
Definition at line 229 of file utils/nrutil.c.
References free(), FREE_ARG, NR_END, and v.
void free_dmatrix (double ** m, long nrl, long nrh, long ncl, long nch)
Definition at line 254 of file utils/nrutil.c.
References free(), FREE_ARG, m, and NR_END.
void free_dvector (double * v, long nl, long nh)
Definition at line 241 of file utils/nrutil.c.
References free(), FREE_ARG, NR_END, and v.
void free_f3tensor (float *** t, long nrl, long nrh, long ncl, long nch, long ndl, long ndh)
Definition at line 280 of file utils/nrutil.c.
References free(), FREE_ARG, NR_END, and t.
void free_imatrix (int ** m, long nrl, long nrh, long ncl, long nch)
Definition at line 261 of file utils/nrutil.c.
References free(), FREE_ARG, m, and NR_END.
void free_ivector (int * v, long nl, long nh)
Definition at line 223 of file utils/nrutil.c.
References free(), FREE_ARG, NR_END, and v.
void free_lvector (unsigned long * v, long nl, long nh)
Definition at line 235 of file utils/nrutil.c.
References free(), FREE_ARG, NR_END, and v.
void free_matrix (float ** m, long nrl, long nrh, long ncl, long nch)
Definition at line 247 of file utils/nrutil.c.
References free(), FREE_ARG, m, and NR_END.
void free_submatrix (float ** b, long nrl, long nrh, long ncl, long nch)
Definition at line 268 of file utils/nrutil.c.
References b, free(), FREE_ARG, and NR_END.
void free_vector (float * v, long nl, long nh)
Definition at line 217 of file utils/nrutil.c.
References free(), FREE_ARG, NR_END, and v.
int** imatrix (long nrl, long nrh, long ncl, long nch)
Definition at line 115 of file utils/nrutil.c.
References i, m, malloc(), NR_END, and nrerror().
int* ivector (long nl, long nh)
Definition at line 27 of file utils/nrutil.c.
References malloc(), NR_END, nrerror(), and v.
unsigned long* lvector (long nl, long nh)
Definition at line 47 of file utils/nrutil.c.
References malloc(), NR_END, nrerror(), and v.
float** matrix (long nrl, long nrh, long ncl, long nch)
Definition at line 67 of file utils/nrutil.c.
References i, m, malloc(), NR_END, and nrerror().
void nrerror (char error_text[])
Definition at line 8 of file utils/nrutil.c.
References exit().
float** submatrix (float ** a, long oldrl, long oldrh, long oldcl, long oldch, long newrl, long newcl)
Definition at line 140 of file utils/nrutil.c.
References a, i, j, m, malloc(), NR_END, and nrerror().
float* vector (long nl, long nh)
Definition at line 17 of file utils/nrutil.c.
References malloc(), NR_END, nrerror(), and v.
Author
Generated automatically by Doxygen for imcat from the source code.