.TH "Vardesc" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vardesc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <f2c.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBaddr\fP"
.br
.ti -1c
.RI "\fBftnlen\fP * \fBdims\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBaddr\fP"
.br
.ti -1c
.RI "\fBftnlen\fP * \fBdims\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBaddr\fP"
.br
.ti -1c
.RI "\fBftnlen\fP * \fBdims\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* \fBVardesc::addr\fP"
.PP
Definition at line 144 of file myf2c.h.
.SS "char* \fBVardesc::addr\fP"
.PP
Definition at line 177 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBVardesc::addr\fP"
.PP
Definition at line 138 of file fftpack_c/f2c.h.
.SS "\fBftnlen\fP* \fBVardesc::dims\fP"
.PP
Definition at line 145 of file myf2c.h.
.SS "\fBftnlen\fP* \fBVardesc::dims\fP"
.PP
Definition at line 178 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "\fBftnlen\fP* \fBVardesc::dims\fP"
.PP
Definition at line 139 of file fftpack_c/f2c.h.
.SS "char* \fBVardesc::name\fP"
.PP
Definition at line 143 of file myf2c.h.
.SS "char* \fBVardesc::name\fP"
.PP
Definition at line 176 of file imcattools/orbits/kepler_heasley/f2c.h.
.SS "char* \fBVardesc::name\fP"
.PP
Definition at line 137 of file fftpack_c/f2c.h.
.SS "int \fBVardesc::type\fP"
.PP
Definition at line 146 of file myf2c.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
