vectors.c
NAME
vectors.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include 'vectors.h'
Functions
void assign (double *vec, double v0, double v1, double v2)
double length (double *vec)
void diff (double *dst, double *src1, double *src2)
void add (double *dst, double *src1, double *src2)
void scale (double *vec, double scalefactor)
void copy (double *dst, double *src)
void printvec (double *vec, char *name)
void fprintvec (double *vec, FILE *stream)
double dot (double *vec1, double *vec2)
void getperp (double *dst, double *src, double *n)
void rotx (double *vec, double angle)
void roty (double *vec, double angle)
void rotz (double *vec, double angle)
void cross (double *dst, double *a, double *b)
Function Documentation
void add (double * dst, double * src1, double * src2)
Definition at line 38 of file vectors.c.
References i.
Referenced by main().
void assign (double * vec, double v0, double v1, double v2)
Definition at line 10 of file vectors.c.
Referenced by addjupitergravity(), airmassmin(), cartesiantokepler(), getbasis(), keplertocartesian(), keplertocartesian_shapiro(), main(), rotx(), roty(), and rotz().
void copy (double * dst, double * src)
Definition at line 56 of file vectors.c.
References i.
Referenced by airmassmin(), cartesiantokepler(), keplertocartesian(), main(), and tcl().
void cross (double * dst, double * a, double * b)
Definition at line 144 of file vectors.c.
References a, and b.
Referenced by cartesiantokepler().
void diff (double * dst, double * src1, double * src2)
Definition at line 29 of file vectors.c.
References i.
Referenced by main(), and wcsdist().
double dot (double * vec1, double * vec2)
Definition at line 85 of file vectors.c.
References i.
Referenced by airmassmin(), cartesiantokepler(), cdl_doBoxMark(), cdl_doDashedLine(), cdl_drawThickDashVec(), getperp(), main(), and makedddotr().
void fprintvec (double * vec, FILE * stream)
Definition at line 76 of file vectors.c.
References i.
Referenced by main().
void getperp (double * dst, double * src, double * n)
Definition at line 97 of file vectors.c.
References dot(), i, and n.
Referenced by main().
double length (double * vec)
Definition at line 17 of file vectors.c.
References i.
Referenced by addjupitergravity(), airmassmin(), cartesiantokepler(), chisquared(), main(), tcl(), write_fits_head(), write_fits_head_ND(), write_fits_tail(), write_fits_tail_ND(), and writefitstail().
void printvec (double * vec, char * name)
Definition at line 65 of file vectors.c.
References i.
Referenced by main().
void rotx (double * vec, double angle)
Definition at line 108 of file vectors.c.
References angle, assign(), x, y, and z.
Referenced by keplertocartesian(), and main().
void roty (double * vec, double angle)
Definition at line 120 of file vectors.c.
References angle, assign(), x, y, and z.
Referenced by airmassmin(), and main().
void rotz (double * vec, double angle)
Definition at line 132 of file vectors.c.
References angle, assign(), x, y, and z.
Referenced by keplertocartesian(), and main().
void scale (double * vec, double scalefactor)
Definition at line 47 of file vectors.c.
References i.
Referenced by addjupitergravity(), airmassmin(), cartesiantokepler(), chisquared(), keplertocartesian(), main(), and tcl().
Author
Generated automatically by Doxygen for imcat from the source code.