vximtool.c
NAME
vximtool.c -
SYNOPSIS
#include <sys/times.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/un.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
Data Structures
struct Ctran
struct FbConfig
struct FrameBuf
struct iism70
struct IoChan
struct VXimData
Defines
#define MAX_FBCONFIG 128
#define MAX_FRAMES 4
#define MAX_CLIENTS 8
#define DEF_NFRAMES 1
#define DEF_FRAME_WIDTH 512
#define DEF_FRAME_HEIGHT 512
#define SZ_LABEL 256
#define SZ_IMTITLE 128
#define SZ_WCSBUF 320
#define SZ_FIFOBUF 4000
#define SZ_FNAME 256
#define SZ_LINE 256
#define DEF_PORT 5137
#define DEF_PROXY_PORT 5136
#define I_DEVNAME '/dev/imt1o'
#define O_DEVNAME '/dev/imt1i'
#define DEF_UNIXADDR '/tmp/.IMT%d'
#define FBCONFIG_1 '.imtoolrc'
#define FBCONFIG_2 '/usr/local/lib/imtoolrc'
#define FBCONFIG_ENV1 'imtoolrc'
#define FBCONFIG_ENV2 'IMTOOLRC'
#define IO_TIMEOUT 30
#define MAXCONN 5
#define SZ_IOBUF 65536
#define SZ_FIFOBUF 4000
#define SZ_WCSBUF 320
#define SZ_FNAME 256
#define SZ_IMCURVAL 160
#define MEMORY 01
#define LUT 02
#define FEEDBACK 05
#define IMCURSOR 020
#define WCS 021
#define PACKED 0040000
#define COMMAND 0100000
#define IIS_READ 0100000
#define IMC_SAMPLE 0040000
#define IMT_FBCONFIG 077
#define XYMASK 077777
#define CMS_DATASTART 1
#define CMS_DATAEND 200
#define CMS_DATARANGE 200
#define W_UNITARY 0
#define W_LINEAR 1
#define W_LOG 2
#define W_DEFFORMAT ' %7.2f %7.2f %7.1f%c'
#define IO_FIFO 1
#define IO_INET 2
#define IO_UNIX 3
#define abs(a) (((a)<0)?(-(a)):(a))
#define min(a, b) ((a)<(b)?(a):(b))
#define max(a, b) ((a)<(b)?(b):(a))
#define SELWIDTH 32
Typedefs
typedef * CtranPtr
typedef * FrameBufPtr
typedef * FbConfigPtr
typedef * IoChanPtr
typedef * VXimDataPtr
Functions
void vx_iisclose ()
void vx_connectClient ()
void vx_disconnectClient ()
void vx_iisio ()
void set_fbconfig ()
void vx_retCursorVal ()
void vx_initialize ()
void vx_initFrame ()
void vx_eraseFrame ()
void get_fbconfig ()
void Usage ()
void printoption ()
int vx_iisopen ()
int decode_frameno ()
void bswap2 ()
IoChanPtr open_fifo ()
IoChanPtr open_inet ()
IoChanPtr open_unix ()
IoChanPtr get_iochan ()
CtranPtr wcs_update ()
main (int argc, char **argv)
int vx_iisopen (VXimDataPtr vxim)
void vx_iisclose (VXimDataPtr vxim)
IoChanPtr open_fifo (VXimDataPtr vxim)
IoChanPtr open_inet (VXimDataPtr vxim)
IoChanPtr open_unix (VXimDataPtr vxim)
void vx_connectClient (IoChanPtr chan, int *source)
void vx_disconnectClient (IoChanPtr chan)
IoChanPtr get_iochan (VXimDataPtr vxim)
void vx_iisio (IoChanPtr chan, int *fd_addr, int source)
void set_fbconfig (IoChanPtr chan, int config, int frame)
int decode_frameno (int z)
void bswap2 (char *a, char *b, int nbytes)
void vx_retCursorVal (int dataout, float sx, float sy, int wcs, int key, char *strval)
CtranPtr wcs_update (VXimDataPtr vxim, FrameBufPtr fr)
void vx_initialize (VXimDataPtr vxim, int config, int nframes, int reset)
void vx_initFrame (VXimDataPtr vxim, int frame, int nframes, FbConfigPtr config)
void vx_eraseFrame (VXimDataPtr vxim, int frame)
void get_fbconfig (VXimDataPtr vxim)
void printoption (char *st)
Variables
VXimData server_data
int keep_raster = 1
int errno
int background = 0
int verbose = 0
int interactive = 0
float cursor_x = 1.0 cursor_y = 1.0
fd_set fds
fd_set allset
int cpos = 0
Define Documentation
#define abs(a) (((a)<0)?(-(a)):(a))
Definition at line 217 of file vximtool.c.
Referenced by cdl_drawThickDashVec(), cdl_drawThickVector(), kepler_(), lmodelfunc(), makezernikeR(), mgoplt3d_(), readlmodel(), vx_iisio(), and wcs_update().
#define CMS_DATAEND 200
Definition at line 115 of file vximtool.c.
#define CMS_DATARANGE 200
Definition at line 116 of file vximtool.c.
#define CMS_DATASTART 1
Definition at line 114 of file vximtool.c.
#define COMMAND 0100000
Definition at line 98 of file vximtool.c.
#define DEF_FRAME_HEIGHT 512
Definition at line 62 of file vximtool.c.
#define DEF_FRAME_WIDTH 512
Definition at line 61 of file vximtool.c.
#define DEF_NFRAMES 1
Definition at line 60 of file vximtool.c.
#define DEF_PORT 5137
Definition at line 72 of file vximtool.c.
#define DEF_PROXY_PORT 5136
Definition at line 73 of file vximtool.c.
Referenced by main().
#define DEF_UNIXADDR '/tmp/.IMT%d'
Definition at line 76 of file vximtool.c.
#define FBCONFIG_1 '.imtoolrc'
Definition at line 77 of file vximtool.c.
#define FBCONFIG_2 '/usr/local/lib/imtoolrc'
Definition at line 78 of file vximtool.c.
#define FBCONFIG_ENV1 'imtoolrc'
Definition at line 79 of file vximtool.c.
#define FBCONFIG_ENV2 'IMTOOLRC'
Definition at line 80 of file vximtool.c.
#define FEEDBACK 05
Definition at line 93 of file vximtool.c.
#define I_DEVNAME '/dev/imt1o'
Definition at line 74 of file vximtool.c.
#define IIS_READ 0100000
Definition at line 99 of file vximtool.c.
#define IMC_SAMPLE 0040000
Definition at line 100 of file vximtool.c.
#define IMCURSOR 020
Definition at line 94 of file vximtool.c.
#define IMT_FBCONFIG 077
Definition at line 101 of file vximtool.c.
#define IO_FIFO 1
Definition at line 167 of file vximtool.c.
Referenced by open_fifo(), vx_iisclose(), and vx_iisio().
#define IO_INET 2
Definition at line 168 of file vximtool.c.
Referenced by main(), open_inet(), vx_disconnectClient(), vx_iisclose(), and vx_iisio().
#define IO_TIMEOUT 30
Definition at line 83 of file vximtool.c.
Referenced by vx_iisio().
#define IO_UNIX 3
Definition at line 169 of file vximtool.c.
Referenced by main(), open_unix(), vx_disconnectClient(), and vx_iisclose().
#define LUT 02
Definition at line 92 of file vximtool.c.
#define max(a, b) ((a)<(b)?(b):(a))
Definition at line 223 of file vximtool.c.
#define MAX_CLIENTS 8
Definition at line 59 of file vximtool.c.
Referenced by get_iochan().
#define MAX_FBCONFIG 128
Definition at line 55 of file vximtool.c.
#define MAX_FRAMES 4
Definition at line 57 of file vximtool.c.
#define MAXCONN 5
Definition at line 84 of file vximtool.c.
Referenced by open_inet(), and open_unix().
#define MEMORY 01
Definition at line 91 of file vximtool.c.
#define min(a, b) ((a)<(b)?(a):(b))
Definition at line 220 of file vximtool.c.
#define O_DEVNAME '/dev/imt1i'
Definition at line 75 of file vximtool.c.
#define PACKED 0040000
Definition at line 97 of file vximtool.c.
#define SELWIDTH 32
Definition at line 231 of file vximtool.c.
Referenced by main().
#define SZ_FIFOBUF 4000
Definition at line 86 of file vximtool.c.
#define SZ_FIFOBUF 4000
Definition at line 86 of file vximtool.c.
Referenced by vx_iisio().
#define SZ_FNAME 256
Definition at line 88 of file vximtool.c.
#define SZ_FNAME 256
Definition at line 88 of file vximtool.c.
#define SZ_IMCURVAL 160
Definition at line 89 of file vximtool.c.
#define SZ_IMTITLE 128
Definition at line 65 of file vximtool.c.
Referenced by wcs_update().
#define SZ_IOBUF 65536
Definition at line 85 of file vximtool.c.
Referenced by vx_iisio().
#define SZ_LABEL 256
Definition at line 64 of file vximtool.c.
#define SZ_LINE 256
Definition at line 69 of file vximtool.c.
#define SZ_WCSBUF 320
Definition at line 87 of file vximtool.c.
#define SZ_WCSBUF 320
Definition at line 87 of file vximtool.c.
#define W_DEFFORMAT ' %7.2f %7.2f %7.1f%c'
Definition at line 122 of file vximtool.c.
Referenced by vx_iisio(), and wcs_update().
#define W_LINEAR 1
Definition at line 120 of file vximtool.c.
#define W_LOG 2
Definition at line 121 of file vximtool.c.
#define W_UNITARY 0
Definition at line 119 of file vximtool.c.
#define WCS 021
Definition at line 95 of file vximtool.c.
#define XYMASK 077777
Definition at line 102 of file vximtool.c.
Referenced by vx_iisio().
Typedef Documentation
typedef * CtranPtr
Referenced by vx_iisio(), and wcs_update().
typedef * FbConfigPtr
Referenced by vx_initFrame().
typedef * FrameBufPtr
Referenced by set_fbconfig(), vx_eraseFrame(), vx_iisclose(), vx_iisio(), vx_initFrame(), and wcs_update().
typedef * IoChanPtr
Referenced by main(), open_fifo(), open_inet(), open_unix(), set_fbconfig(), vx_connectClient(), vx_disconnectClient(), vx_iisclose(), and vx_iisio().
typedef * VXimDataPtr
Referenced by get_fbconfig(), get_iochan(), main(), open_fifo(), open_inet(), open_unix(), set_fbconfig(), vx_connectClient(), vx_eraseFrame(), vx_iisclose(), vx_iisio(), vx_iisopen(), vx_initFrame(), vx_initialize(), and wcs_update().
Function Documentation
void bswap2 (char 	* a, char * b, int nbytes) [static]
Definition at line 1433 of file vximtool.c.
References a, b, and op.
void bswap2 () [static]
int decode_frameno (int z) [static]
Definition at line 1401 of file vximtool.c.
References max, n, and z.
int decode_frameno ()
Referenced by vx_iisio().
void get_fbconfig (VXimDataPtr vxim) [static]
Definition at line 1685 of file vximtool.c.
References DEF_FRAME_HEIGHT, DEF_FRAME_WIDTH, FBCONFIG_1, FBCONFIG_ENV1, FBCONFIG_ENV2, i, max, MAX_FBCONFIG, min, nframes, SZ_LINE, and VXimDataPtr.
void get_fbconfig () [static]
Referenced by vx_initialize().
IoChanPtr get_iochan (VXimDataPtr vxim) [static]
Definition at line 844 of file vximtool.c.
References i, MAX_CLIENTS, and VXimDataPtr.
IoChanPtr get_iochan ()
Referenced by open_fifo(), open_inet(), and open_unix().
main (int argc, char	** argv)
Definition at line 310 of file vximtool.c.
References allset, background, buf, cdl_open(), CDLPtr, DEF_PROXY_PORT, exit(), fds, i, interactive, IO_INET, IO_UNIX, IoChanPtr, keep_raster, MAX_FRAMES, min, n, SELWIDTH, server_data, SZ_FNAME, Usage(), verbose, vx_connectClient(), vx_iisclose(), vx_iisio(), vx_iisopen(), vx_initialize(), and VXimDataPtr.
IoChanPtr open_fifo (VXimDataPtr vxim) [static]
Definition at line 562 of file vximtool.c.
References get_iochan(), IO_FIFO, IoChanPtr, verbose, and VXimDataPtr.
IoChanPtr open_fifo () [static]
Referenced by vx_iisopen().
IoChanPtr open_inet (VXimDataPtr vxim) [static]
Definition at line 646 of file vximtool.c.
References errno, get_iochan(), IO_INET, IoChanPtr, MAXCONN, verbose, and VXimDataPtr.
IoChanPtr open_inet ()
Referenced by vx_iisopen().
IoChanPtr open_unix (VXimDataPtr vxim) [static]
Definition at line 707 of file vximtool.c.
References errno, get_iochan(), IO_UNIX, IoChanPtr, MAXCONN, SZ_FNAME, verbose, and VXimDataPtr.
IoChanPtr open_unix ()
Referenced by vx_iisopen().
void printoption (char * st) [static]
Definition at line 1805 of file vximtool.c.
References cpos, and st.
void printoption ()
Referenced by Usage().
void set_fbconfig (IoChanPtr chan, int config, int frame) [static]
Definition at line 1364 of file vximtool.c.
References fb, frame, FrameBufPtr, i, IoChanPtr, max, vx_initFrame(), vx_initialize(), and VXimDataPtr.
void set_fbconfig ()
Referenced by vx_iisio().
void Usage ()
Definition at line 1771 of file vximtool.c.
References printoption().
Referenced by main().
void vx_connectClient (IoChanPtr chan, int * source) [static]
Definition at line 774 of file vximtool.c.
References allset, IoChanPtr, and VXimDataPtr.
void vx_connectClient ()
Referenced by main().
void vx_disconnectClient (IoChanPtr chan) [static]
Definition at line 811 of file vximtool.c.
References allset, IO_INET, IO_UNIX, IoChanPtr, and verbose.
void vx_disconnectClient ()
Referenced by vx_iisio().
void vx_eraseFrame (VXimDataPtr vxim, int frame) [static]
Definition at line 1658 of file vximtool.c.
References fb, frame, FrameBufPtr, keep_raster, and VXimDataPtr.
void vx_eraseFrame ()
Referenced by vx_iisio().
void vx_iisclose (VXimDataPtr vxim) [static]
Definition at line 506 of file vximtool.c.
References fb, FrameBufPtr, free(), i, IO_FIFO, IO_INET, IO_UNIX, IoChanPtr, j, keep_raster, and VXimDataPtr.
void vx_iisclose () [static]
Referenced by main().
void vx_iisio (IoChanPtr chan, int * fd_addr, int source) [static]
Definition at line 868 of file vximtool.c.
References abs, bswap2(), buf, cdl_clearFrame(), cdl_readCursor(), cdl_readSubRaster(), cdl_setCursor(), cdl_setFBConfig(), cdl_setFrame(), cdl_setWCS(), cdl_writeSubRaster(), COMMAND, CtranPtr, cursor_x, decode_frameno(), fb, FEEDBACK, frame, FrameBufPtr, free(), i, IIS_READ, IMC_SAMPLE, IMCURSOR, IO_FIFO, IO_INET, IO_TIMEOUT, IoChanPtr, keep_raster, key, LUT, malloc(), max, MAX_FRAMES, MEMORY, min, n, op, PACKED, pix, set_fbconfig(), SZ_FIFOBUF, SZ_FNAME, SZ_IMCURVAL, SZ_IOBUF, SZ_WCSBUF, verbose, vx_disconnectClient(), vx_eraseFrame(), vx_retCursorVal(), VXimDataPtr, W_DEFFORMAT, wcs, WCS, wcs_update(), x, XYMASK, y, and z.
void vx_iisio () [static]
Referenced by main().
int vx_iisopen (VXimDataPtr vxim) [static]
Definition at line 480 of file vximtool.c.
References open_fifo(), open_inet(), open_unix(), and VXimDataPtr.
int vx_iisopen () [static]
Referenced by main().
void vx_initFrame (VXimDataPtr vxim, int frame, int nframes, FbConfigPtr config) [static]
Definition at line 1626 of file vximtool.c.
References fb, FbConfigPtr, frame, FrameBufPtr, free(), keep_raster, malloc(), MAX_FRAMES, nframes, and VXimDataPtr.
void vx_initFrame ()
Referenced by set_fbconfig(), and vx_initialize().
void vx_initialize (VXimDataPtr vxim, int config, int nframes, int reset) [static]
Definition at line 1598 of file vximtool.c.
References get_fbconfig(), nframes, reset, vx_initFrame(), and VXimDataPtr.
void vx_initialize () [static]
Referenced by main(), and set_fbconfig().
void vx_retCursorVal (int dataout, float sx, float sy, int wcs, int key, char	* strval) [static]
Definition at line 1473 of file vximtool.c.
References interactive, key, SZ_IMCURVAL, and wcs.
void vx_retCursorVal ()
Referenced by vx_iisio().
CtranPtr wcs_update (VXimDataPtr vxim, FrameBufPtr fr) [static]
Definition at line 1533 of file vximtool.c.
References abs, buf, CtranPtr, FrameBufPtr, SZ_IMTITLE, VXimDataPtr, W_DEFFORMAT, W_LINEAR, W_UNITARY, z1, and z2.
CtranPtr wcs_update () [static]
Referenced by vx_iisio().
Variable Documentation
fd_set allset [static]
Definition at line 244 of file vximtool.c.
Referenced by main(), vx_connectClient(), and vx_disconnectClient().
int background = 0 [static]
Definition at line 240 of file vximtool.c.
Referenced by main().
int cpos = 0 [static]
Definition at line 1797 of file vximtool.c.
Referenced by printoption().
float cursor_x = 1.0 cursor_y = 1.0 [static]
Definition at line 243 of file vximtool.c.
Referenced by vx_iisio().
int errno
Definition at line 239 of file vximtool.c.
Referenced by open_inet(), and open_unix().
fd_set fds [static]
Definition at line 244 of file vximtool.c.
Referenced by main().
int interactive = 0 [static]
Definition at line 242 of file vximtool.c.
Referenced by main(), and vx_retCursorVal().
int keep_raster = 1 [static]
Definition at line 238 of file vximtool.c.
Referenced by main(), vx_eraseFrame(), vx_iisclose(), vx_iisio(), and vx_initFrame().
VXimData server_data
Initial value:.nf
 {
  1,
  DEF_NFRAMES,
  FBCONFIG_2,
  O_DEVNAME,
  I_DEVNAME,
  DEF_UNIXADDR,
  DEF_PORT,
  1,
  1,
  2,
  512, 512
}
Definition at line 200 of file vximtool.c.
Referenced by main().
int verbose = 0 [static]
Definition at line 241 of file vximtool.c.
Referenced by main(), open_fifo(), open_inet(), open_unix(), vx_disconnectClient(), and vx_iisio().
Author
Generated automatically by Doxygen for imcat from the source code.