.TH "VXimData" 3 "23 Dec 2003" "imcat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VXimData \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdef_config\fP"
.br
.ti -1c
.RI "int \fBdef_nframes\fP"
.br
.ti -1c
.RI "char * \fBimtoolrc\fP"
.br
.ti -1c
.RI "char * \fBinput_fifo\fP"
.br
.ti -1c
.RI "char * \fBoutput_fifo\fP"
.br
.ti -1c
.RI "char * \fBunixaddr\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "int \fBdisplay_frame\fP"
.br
.ti -1c
.RI "int \fBfb_configno\fP"
.br
.ti -1c
.RI "int \fBnframes\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "\fBIoChan\fP \fBchan\fP [MAX_CLIENTS]"
.br
.ti -1c
.RI "\fBFrameBufPtr\fP \fBdf_p\fP"
.br
.ti -1c
.RI "\fBFrameBuf\fP \fBframes\fP [MAX_FRAMES]"
.br
.ti -1c
.RI "\fBFbConfig\fP \fBfb_config\fP [MAX_FBCONFIG]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBIoChan\fP \fBVXimData::chan\fP[MAX_CLIENTS]"
.PP
Definition at line 189 of file vximtool.c.
.SS "int \fBVXimData::def_config\fP"
.PP
Definition at line 176 of file vximtool.c.
.SS "int \fBVXimData::def_nframes\fP"
.PP
Definition at line 177 of file vximtool.c.
.SS "\fBFrameBufPtr\fP \fBVXimData::df_p\fP"
.PP
Definition at line 190 of file vximtool.c.
.SS "int \fBVXimData::display_frame\fP"
.PP
Definition at line 185 of file vximtool.c.
.SS "\fBFbConfig\fP \fBVXimData::fb_config\fP[MAX_FBCONFIG]"
.PP
Definition at line 192 of file vximtool.c.
.SS "int \fBVXimData::fb_configno\fP"
.PP
Definition at line 186 of file vximtool.c.
.SS "\fBFrameBuf\fP \fBVXimData::frames\fP[MAX_FRAMES]"
.PP
Definition at line 191 of file vximtool.c.
.SS "int \fBVXimData::height\fP"
.PP
Definition at line 188 of file vximtool.c.
.SS "char* \fBVXimData::imtoolrc\fP"
.PP
Definition at line 178 of file vximtool.c.
.SS "char* \fBVXimData::input_fifo\fP"
.PP
Definition at line 179 of file vximtool.c.
.SS "int \fBVXimData::nframes\fP"
.PP
Definition at line 187 of file vximtool.c.
.SS "char* \fBVXimData::output_fifo\fP"
.PP
Definition at line 180 of file vximtool.c.
.SS "int \fBVXimData::port\fP"
.PP
Definition at line 182 of file vximtool.c.
.SS "char* \fBVXimData::unixaddr\fP"
.PP
Definition at line 181 of file vximtool.c.
.SS "int \fBVXimData::width\fP"
.PP
Definition at line 188 of file vximtool.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for imcat from the source code.
