warpimage.c
NAME
warpimage.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include '../utils/error.h'
#include '../imlib/map.h'
#include '../imlib/fits.h'
#include '../utils/modefunc.h'
Defines
#define usage '\n\n\n\NAME\n\	warpimage - apply spatial transformation to a FITS image\n\\n\SYNOPSIS\n\	warpimage [options...] distparfile\n\		-n N1 N2	# size of output image\n\		-g sf N1 N2 	# generate distortion image\n\		-m		# initialise image to magic\n\		-M mode		# mapping mode (1)\n\		-q qparfile	# recircularise\n\\n\DESCRIPTION\n\	\'warpimage\' reads a fits file from stdin and applies a\n\	spatial transformation according\n\	to the parameters in 'distparfile' such that:\n\		r = x + sum_m a_m f_m(x)\n\	where mode functions are polynomials in x[0], x[1].\n\	Use -p and -d options to apply a further linear transformation:\n\		r_i => phi_ij r_j + d_j\n\	By default output image = input image size.\n\	Output image is initialised to zero, unless you use -m option.\n\\n\	Use -M option to specify mode, where these are (in order of expense)\n\		mode = 0:	# nearest pixel\n\		mode = 1:	# linear interpolation\n\		mode = 2:	# sum over triangles \n\\n\	With -g option (and s = 0) we generate a N1 by (2 * N2) image\n\	whose lower and upper halves contain the x, y components\n\	of the distortion d = r-x. Set 'sf' to be some small\n\	integer to create a deflection image which has been demagnified\n\	by a factor 2^sf, but N1, N2 are given in source image pixel\n\	scale, so '-g 3 1024 1024' will generate a 128 x 256 pixel image.\n\\n\	With -q option we read a parameter file for a model of the field\n\	q = e / P_sm and then make appropriate additional deflections\n\	to recircularise the psf.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
Functions
void deflection (float ri, float rj, float *di, float *dj)
void recircdef (float ri, float rj, float *di, float *dj)
main (int argc, char *argv[])
Variables
int nmodes
int * l
int * m
double ** a
int nqmodes
int * lq
int * mq
int defsign
double ** qpar
double scalefac
Define Documentation
#define usage '\n\n\n\NAME\n\	warpimage - apply spatial transformation to a FITS image\n\\n\SYNOPSIS\n\	warpimage [options...] distparfile\n\		-n N1 N2	# size of output image\n\		-g sf N1 N2 	# generate distortion image\n\		-m		# initialise image to magic\n\		-M mode		# mapping mode (1)\n\		-q qparfile	# recircularise\n\\n\DESCRIPTION\n\	\'warpimage\' reads a fits file from stdin and applies a\n\	spatial transformation according\n\	to the parameters in 'distparfile' such that:\n\		r = x + sum_m a_m f_m(x)\n\	where mode functions are polynomials in x[0], x[1].\n\	Use -p and -d options to apply a further linear transformation:\n\		r_i => phi_ij r_j + d_j\n\	By default output image = input image size.\n\	Output image is initialised to zero, unless you use -m option.\n\\n\	Use -M option to specify mode, where these are (in order of expense)\n\		mode = 0:	# nearest pixel\n\		mode = 1:	# linear interpolation\n\		mode = 2:	# sum over triangles \n\\n\	With -g option (and s = 0) we generate a N1 by (2 * N2) image\n\	whose lower and upper halves contain the x, y components\n\	of the distortion d = r-x. Set 'sf' to be some small\n\	integer to create a deflection image which has been demagnified\n\	by a factor 2^sf, but N1, N2 are given in source image pixel\n\	scale, so '-g 3 1024 1024' will generate a 128 x 256 pixel image.\n\\n\	With -q option we read a parameter file for a model of the field\n\	q = e / P_sm and then make appropriate additional deflections\n\	to recircularise the psf.\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
Definition at line 5 of file warpimage.c.
Function Documentation
void deflection (float ri, float rj, float * di, float * dj)
Definition at line 142 of file lensmap.c.
References di, dj, ic, jc, nclusters, rc, and re.
Referenced by fastmap(), main(), map(), and ultrafastmap().
main (int argc, char * argv[])
Definition at line 67 of file warpimage.c.
References a, add_comment(), allocFloatArray(), deflection(), defsign, di, dj, dx, dy, error_exit, exit(), FAST_MAP_MODE, fastmap(), fits, FLOAT_MAGIC, FLOAT_PIXTYPE, get2Dpolymodel(), ix, l, lq, m, M1, M2, magicinit(), map(), MODEFUNC_MAX_VARS, mq, fitsheader::n, N1, N2, newfitsheader(), nmodes, nqmodes, qpar, read2Dfloatimage(), recircdef(), scalefac, TRIANGLE_MAP_MODE, ULTRAFAST_MAP_MODE, ultrafastmap(), usage, write2Dfloatimage(), writefitsheader(), writefitsplane(), and writefitstail().
void recircdef (float ri, float rj, float * di, float * dj)
Definition at line 269 of file warpimage.c.
References a, d, defsign, di, dj, f(), i, l, lq, m, mq, nmodes, nqmodes, phi, qpar, r, and x.
Referenced by main().
Variable Documentation
double** a
Definition at line 62 of file warpimage.c.
int defsign
Definition at line 63 of file warpimage.c.
Referenced by main(), and recircdef().
int * l
Definition at line 61 of file warpimage.c.
int * lq
Definition at line 63 of file warpimage.c.
Referenced by main(), and recircdef().
int * m
Definition at line 61 of file warpimage.c.
int * mq
Definition at line 63 of file warpimage.c.
Referenced by main(), and recircdef().
int nmodes
Definition at line 61 of file warpimage.c.
int nqmodes
Definition at line 63 of file warpimage.c.
Referenced by main(), and recircdef().
double** qpar
Definition at line 64 of file warpimage.c.
Referenced by main(), and recircdef().
double scalefac
Definition at line 65 of file warpimage.c.
Author
Generated automatically by Doxygen for imcat from the source code.