warpcat.c
NAME
warpcat.c -
SYNOPSIS
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include 'utils/error.h'
#include 'catlib/cat.h'
#include 'imlib/fits.h'
#include 'utils/modefunc.h'
Defines
#define usage '\n\n\n\NAME\n\	warpcat - apply spatial transformation to a catalogue\n\\n\SYNOPSIS\n\	warpcat [options...] distparfile\n\		-p psi_xx psi_xy psi_yx psi_yy\n\		-d d_x d_y\n\\n\DESCRIPTION\n\	\'warpcat\' reads a catalogue from stdin and applies a\n\	spatial transformation to position vector x[2] according\n\	to the parameters in 'distparfile'. It sends to stdout\n\	a catalogue with extra vector\n\		r = x + sum_m a_m f_m(x)\n\	where mode functions are polynomials in x[0], x[1].\n\	Use -p and -d options to apply a further linear transformation:\n\		r_i => phi_ij r_j + d_j\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
#define TINY 1.e-50
Functions
void rmodel (double *x, double *r)
main (int argc, char *argv[])
Variables
float phi [2][2]
float d [2]
int nmodes
int * l
int * m
double ** a
Define Documentation
#define TINY 1.e-50
Definition at line 44 of file warpcat.c.
#define usage '\n\n\n\NAME\n\	warpcat - apply spatial transformation to a catalogue\n\\n\SYNOPSIS\n\	warpcat [options...] distparfile\n\		-p psi_xx psi_xy psi_yx psi_yy\n\		-d d_x d_y\n\\n\DESCRIPTION\n\	\'warpcat\' reads a catalogue from stdin and applies a\n\	spatial transformation to position vector x[2] according\n\	to the parameters in 'distparfile'. It sends to stdout\n\	a catalogue with extra vector\n\		r = x + sum_m a_m f_m(x)\n\	where mode functions are polynomials in x[0], x[1].\n\	Use -p and -d options to apply a further linear transformation:\n\		r_i => phi_ij r_j + d_j\n\\n\AUTHOR\n\	Nick Kaiser: kaiser@ifa.hawaii.edu\n\\n\n\n'
Definition at line 5 of file warpcat.c.
Function Documentation
main (int argc, char * argv[])
Definition at line 46 of file warpcat.c.
References a, addargscomment(), addobjectitem(), object::addrlist, allocitemcontents(), allocobjectcontents(), connectobjecttocathead(), copycontentinfo(), copyheaderinfo(), d, error_exit, exit(), get2Dpolymodel(), getcatipfiletype(), getobjectitemindex(), i, inheritcontents(), l, m, MODEFUNC_MAX_VARS, newitem(), newobject(), nmodes, NUM_TYPE, phi, r, readcathead(), readobject(), rmodel(), setcatopfiletype(), usage, writecathead(), writeobject(), and x.
void rmodel (double * x, double * r)
Definition at line 158 of file warpcat.c.
References a, f(), i, l, m, nmodes, r, and x.
Referenced by main().
Variable Documentation
double** a
Definition at line 42 of file warpcat.c.
float d[2]
Definition at line 40 of file warpcat.c.
int * l
Definition at line 41 of file warpcat.c.
int * m
Definition at line 41 of file warpcat.c.
int nmodes
Definition at line 41 of file warpcat.c.
float phi[2][2]
Definition at line 40 of file warpcat.c.
Author
Generated automatically by Doxygen for imcat from the source code.