wcs.h
NAME
wcs.h -
SYNOPSIS
Data Structures
struct WorldCoor
Defines
#define PI 3.141592653589793
#define degrad(x) ((x)*PI/180.)
#define raddeg(x) ((x)*180./PI)
#define hrdeg(x) ((x)*15.)
#define deghr(x) ((x)/15.)
#define hrrad(x) degrad(hrdeg(x))
#define radhr(x) deghr(raddeg(x))
Functions
WorldCoor * wcsinit ()
WorldCoor * wcsninit ()
WorldCoor * wcsset ()
int iswcs ()
int nowcs ()
void wcsshift ()
void wcscent ()
void wcssize ()
void wcsfull ()
double wcsdist ()
void wcscominit ()
void wcscom ()
void wcsoutinit ()
int pix2wcst ()
void pix2wcs ()
void wcs2pix ()
Define Documentation
#define deghr(x) ((x)/15.)
Definition at line 69 of file wcs.h.
#define degrad(x) ((x)*PI/180.)
Definition at line 66 of file wcs.h.
Referenced by fk425m(), fk42gal(), fk4prec(), fk524m(), fk52gal(), fk5prec(), gal2fk4(), gal2fk5(), wcsdist(), wcsinit(), wcsset(), wcssize(), worldpix(), and worldpos().
#define hrdeg(x) ((x)*15.)
Definition at line 68 of file wcs.h.
#define hrrad(x) degrad(hrdeg(x))
Definition at line 70 of file wcs.h.
Referenced by wcsinit().
#define PI 3.141592653589793
Definition at line 62 of file wcs.h.
#define raddeg(x) ((x)*180./PI)
Definition at line 67 of file wcs.h.
Referenced by fk425m(), fk42gal(), fk4prec(), fk524m(), fk52gal(), fk5prec(), gal2fk4(), gal2fk5(), wcsdist(), worldpix(), and worldpos().
#define radhr(x) deghr(raddeg(x))
Definition at line 71 of file wcs.h.
Function Documentation
int iswcs ()
Referenced by pix2wcs(), pix2wcst(), wcs2pix(), wcscom(), wcscominit(), wcsfull(), wcsoutinit(), and wcssize().
int nowcs ()
Referenced by main(), and wcsshift().
void pix2wcs ()
Referenced by main(), pix2wcst(), wcscent(), wcsfull(), and wcssize().
int pix2wcst ()
Referenced by wcscent(), and wcscom().
void wcs2pix ()
void wcscent ()
void wcscom ()
void wcscominit ()
double wcsdist ()
Referenced by wcscent(), wcsfull(), and wcssize().
void wcsfull ()
struct WorldCoor* wcsinit ()
Referenced by main(), and wcsninit().
struct WorldCoor* wcsninit ()
void wcsoutinit ()
struct WorldCoor* wcsset ()
void wcsshift ()
void wcssize ()
Author
Generated automatically by Doxygen for imcat from the source code.