wcs.c
NAME
wcs.c -
SYNOPSIS
#include <string.h>
#include <stdio.h>
#include <math.h>
#include 'wcs.h'
#include 'fitshead.h'
#include <stdlib.h>
Functions
void wcseq ()
WorldCoor * wcsninit (char *hstring, int lhstring)
WorldCoor * wcsinit (char *hstring)
void wcseq (char *hstring, struct WorldCoor *wcs)
WorldCoor * wcsset (double cra, double cdec, double secpix, double xrpix, double yrpix, int nxpix, int nypix, double rotate, int equinox, double epoch, char *proj)
int iswcs (struct WorldCoor *wcs)
int nowcs (struct WorldCoor *wcs)
void wcsshift (struct WorldCoor *wcs, double cra, double cdec, char *coorsys)
void wcscent (struct WorldCoor *wcs)
void wcssize (struct WorldCoor *wcs, double *cra, double *cdec, double *dra, double *ddec)
void wcsfull (struct WorldCoor *wcs, double *cra, double *cdec, double *width, double *height)
double wcsdist (double x1, double y1, double x2, double y2)
void wcscominit (struct WorldCoor *wcs, char *command)
void wcscom (struct WorldCoor *wcs, char *filename, double xfile, double yfile)
void wcsoutinit (struct WorldCoor *wcs, char *coorsys)
char * wcsout (struct WorldCoor *wcs)
int pix2wcst (struct WorldCoor *wcs, double xpix, double ypix, char *wcstring, int lstr)
void pix2wcs (struct WorldCoor *wcs, double xpix, double ypix, double *xpos, double *ypos)
void wcs2pix (struct WorldCoor *wcs, double xpos, double ypos, double *xpix, double *ypix, int *offscl)
void wcserr ()
Variables
char wcserrmsg [80]
Function Documentation
int iswcs (struct WorldCoor * wcs)
Definition at line 628 of file wcs.c.
References wcs.
int nowcs (struct WorldCoor * wcs)
Definition at line 643 of file wcs.c.
References wcs.
void pix2wcs (struct WorldCoor * wcs, double xpix, double ypix, double	* xpos, double* ypos)
Definition at line 1142 of file wcs.c.
References fk425e(), fk42gal(), fk4prec(), fk524e(), fk52gal(), fk5prec(), iswcs(), platepos(), wcs, worldpos(), xp(), and yp().
int pix2wcst (struct	WorldCoor * wcs, double xpix, double ypix, char	* wcstring, int lstr)
Definition at line 1031 of file wcs.c.
References dec2str(), deg2str(), iswcs(), pix2wcs(), ra2str(), and wcs.
void wcs2pix (struct WorldCoor * wcs, double xpos, double ypos, double	* xpix, double* ypix, int	* offscl)
Definition at line 1204 of file wcs.c.
References fk425e(), fk4prec(), fk524e(), fk5prec(), iswcs(), platepix(), wcs, worldpix(), xp(), and yp().
void wcscent (struct WorldCoor * wcs)
Definition at line 688 of file wcs.c.
References pix2wcs(), pix2wcst(), wcs, and wcsdist().
void wcscom (struct WorldCoor * wcs, char	* filename, double xfile, double yfile)
Definition at line 915 of file wcs.c.
References ier, iswcs(), pix2wcst(), strsrch(), and wcs.
void wcscominit (struct WorldCoor * wcs, char * command)
Definition at line 888 of file wcs.c.
References iswcs(), and wcs.
double wcsdist (double x1, double y1, double x2, double y2)
Definition at line 845 of file wcs.c.
References degrad, diff(), i, raddeg, and w.
void wcseq (char	* hstring, struct WorldCoor * wcs) [static]
Definition at line 450 of file wcs.c.
References hgetdate(), hgeti4(), hgetr8(), hgets(), and wcs.
void wcseq () [static]
Referenced by wcsinit().
void wcserr ()
Definition at line 1262 of file wcs.c.
References wcserrmsg.
void wcsfull (struct WorldCoor * wcs, double	* cra, double	* cdec, double	* width, double	* height)
Definition at line 798 of file wcs.c.
References iswcs(), pix2wcs(), wcs, and wcsdist().
struct WorldCoor* wcsinit (char * hstring)
Definition at line 63 of file wcs.c.
References degrad, free(), hgetdate(), hgetdec(), hgeti4(), hgetr8(), hgetra(), hgets(), hrrad, i, ksearch(), str, wcs, wcseq(), and wcserrmsg.
struct WorldCoor* wcsninit (char	* hstring, int lhstring)
Definition at line 50 of file wcs.c.
References hlength(), and wcsinit().
char* wcsout (struct	WorldCoor * wcs)
Definition at line 1019 of file wcs.c.
References wcs.
void wcsoutinit (struct WorldCoor * wcs, char * coorsys)
Definition at line 962 of file wcs.c.
References iswcs(), and wcs.
struct WorldCoor* wcsset (double cra, double cdec, double secpix, double xrpix, double yrpix, int nxpix, int nypix, double rotate, int equinox, double epoch, char	* proj)
Definition at line 542 of file wcs.c.
References degrad, rotate(), str, and wcs.
void wcsshift (struct WorldCoor * wcs, double cra, double cdec, char	* coorsys)
Definition at line 658 of file wcs.c.
References nowcs(), and wcs.
void wcssize (struct WorldCoor * wcs, double	* cra, double	* cdec, double	* dra, double	* ddec)
Definition at line 746 of file wcs.c.
References degrad, iswcs(), pix2wcs(), wcs, and wcsdist().
Variable Documentation
char wcserrmsg[80] [static]
Definition at line 45 of file wcs.c.
Referenced by wcserr(), and wcsinit().
Author
Generated automatically by Doxygen for imcat from the source code.