wcscon.c
NAME
wcscon.c -
SYNOPSIS
#include <math.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include 'wcs.h'
Defines
#define DAS2R 4.8481368110953599358991410235794797595635330237270e-6
Functions
void slaDcs2c ()
void slaDmxv ()
void slaDcc2s ()
void slaDeuler ()
void fk524 (double *ra, double *dec)
void fk524e (double *ra, double *dec, double epoch)
void fk524m (double *ra, double *dec, double *rapm, double *decpm)
void fk425 (double *ra, double *dec)
void fk425e (double *ra, double *dec, double epoch)
void fk425m (double *ra, double *dec, double *rapm, double *decpm)
void fk42gal (double *dtheta, double *dphi)
void gal2fk4 (double *dtheta, double *dphi)
void fk52gal (double *dtheta, double *dphi)
void gal2fk5 (double *dtheta, double *dphi)
char * eqstrn (double dra, double ddec)
void jpcon (pos, double *rra, double *rdec, double *r)
void jpcop (double rra, double rdec, double r, pos)
void fk4prec (double ep0, double ep1, double *ra, double *dec)
void fk5prec (double ep0, double ep1, double *ra, double *dec)
void mprecfk4 (double bep0, double bep1, rmatp)
void mprecfk5 (double ep0, double ep1, rmatp)
Variables
double a [3] = {-1.62557e-6, -0.31919e-6, -0.13843e-6}
double ad [3] = {1.245e-3, -1.580e-3, -0.659e-3}
double emi [6][6]
double em [6][6]
int idg = 0
double bgal [3][3]
double jgal [3][3]
Define Documentation
#define DAS2R 4.8481368110953599358991410235794797595635330237270e-6
Definition at line 984 of file wcscon.c.
Referenced by mprecfk4(), and mprecfk5().
Function Documentation
char* eqstrn (double dra, double ddec)
Definition at line 797 of file wcscon.c.
References malloc(), xp(), and yp().
Referenced by fk42gal(), fk52gal(), gal2fk4(), and gal2fk5().
void fk425 (double	* ra, double	* dec)
Definition at line 315 of file wcscon.c.
References fk425m(), and ra.
Referenced by main().
void fk425e (double	* ra, double	* dec, double epoch)
Definition at line 336 of file wcscon.c.
References fk425m(), and ra.
Referenced by pix2wcs(), and wcs2pix().
void fk425m (double	* ra, double * dec, double	* rapm, double * decpm)
Definition at line 358 of file wcscon.c.
References a, ad, degrad, e2, em, i, j, ra, raddeg, w, x, y, z, and zero().
Referenced by fk425(), and fk425e().
void fk42gal (double * dtheta, double * dphi)
Definition at line 557 of file wcscon.c.
References bgal, degrad, eqstrn(), free(), i, idg, jpcon(), jpcop(), pos, r, and raddeg.
Referenced by main(), and pix2wcs().
void fk4prec (double ep0, double ep1, double * ra, double * dec)
Definition at line 894 of file wcscon.c.
References degrad, mprecfk4(), ra, raddeg, slaDcc2s(), slaDcs2c(), slaDmxv(), and slaDranrm().
Referenced by pix2wcs(), and wcs2pix().
void fk524 (double	* ra, double	* dec)
Definition at line 66 of file wcscon.c.
References fk524m(), and ra.
Referenced by main().
void fk524e (double	* ra, double	* dec, double epoch)
Definition at line 84 of file wcscon.c.
References fk524m(), and ra.
Referenced by pix2wcs(), and wcs2pix().
void fk524m (double	* ra, double	* dec, double	* rapm, double	* decpm)
Definition at line 105 of file wcscon.c.
References a, ad, degrad, e2, emi, i, j, ra, raddeg, w, x, y, z, and zero().
Referenced by fk524(), and fk524e().
void fk52gal (double * dtheta, double * dphi)
Definition at line 690 of file wcscon.c.
References degrad, eqstrn(), free(), i, idg, jgal, jpcon(), jpcop(), pos, r, and raddeg.
Referenced by main(), and pix2wcs().
void fk5prec (double ep0, double ep1, double * ra, double * dec)
Definition at line 938 of file wcscon.c.
References degrad, mprecfk5(), ra, raddeg, slaDcc2s(), slaDcs2c(), slaDmxv(), and slaDranrm().
Referenced by pix2wcs(), and wcs2pix().
void gal2fk4 (double * dtheta, double * dphi)
Definition at line 615 of file wcscon.c.
References bgal, degrad, eqstrn(), free(), i, idg, jpcon(), jpcop(), pos, r, and raddeg.
Referenced by main().
void gal2fk5 (double * dtheta, double * dphi)
Definition at line 745 of file wcscon.c.
References degrad, eqstrn(), free(), i, idg, jgal, jpcon(), jpcop(), pos, r, and raddeg.
Referenced by main().
void jpcon (pos, double * rra, double * rdec, double * r)
Definition at line 845 of file wcscon.c.
References pos, r, x, y, z, and z2.
Referenced by fk42gal(), fk52gal(), gal2fk4(), and gal2fk5().
void jpcop (double rra, double rdec, double r, pos)
Definition at line 877 of file wcscon.c.
References pos, and r.
Referenced by fk42gal(), fk52gal(), gal2fk4(), and gal2fk5().
void mprecfk4 (double bep0, double bep1, rmatp)
Definition at line 987 of file wcscon.c.
References DAS2R, slaDeuler(), t, w, and z.
Referenced by fk4prec().
void mprecfk5 (double ep0, double ep1, rmatp)
Definition at line 1032 of file wcscon.c.
References DAS2R, slaDeuler(), t, t0, w, and z.
Referenced by fk5prec().
void slaDcc2s ()
Referenced by fk4prec(), and fk5prec().
void slaDcs2c ()
Referenced by fk4prec(), and fk5prec().
void slaDeuler ()
Referenced by mprecfk4(), and mprecfk5().
void slaDmxv ()
Referenced by fk4prec(), and fk5prec().
Variable Documentation
double a[3] = {-1.62557e-6, -0.31919e-6, -0.13843e-6} [static]
Definition at line 40 of file wcscon.c.
double ad[3] = {1.245e-3, -1.580e-3, -0.659e-3} [static]
Definition at line 41 of file wcscon.c.
Referenced by fk425m(), and fk524m().
double bgal[3][3] [static]
Initial value:.nf
 {
  -0.066988739415,-0.872755765852,-0.483538914632,
   0.492728466075,-0.450346958020, 0.744584633283,
  -0.867600811151,-0.188374601723, 0.460199784784}
Definition at line 548 of file wcscon.c.
Referenced by fk42gal(), and gal2fk4().
double em[6][6] [static]
Initial value:.nf
 {
   0.999925678186902, 0.011182059571766, 0.004857946721186,
  -0.000541652366951, 0.237917612131583, -0.436111276039270,
  -0.011182059642247, 0.999937478448132, -0.000027147426498,
  -0.237968129744288, -0.002660763319071, 0.012259092261564,
  -0.004857946558960, -0.000027176441185, 0.999988199738770,
   0.436227555856097, -0.008537771074048, 0.002119110818172,
   0.000002423950176, 0.000000027106627, 0.000000011776559,
   0.999947035154614, 0.011182506007242, 0.004857669948650,
  -0.000000027106627, 0.000002423978783, -0.000000000065816,
  -0.011182506121805, 0.999958833818833, -0.000027137309539,
  -0.000000011776558, -0.000000000065874, 0.000002424101735,
  -0.004857669684959, -0.000027184471371, 1.000009560363559}
Definition at line 295 of file wcscon.c.
Referenced by fk425m().
double emi[6][6] [static]
Initial value:.nf
 {
   0.999925679499910, -0.011181482788805, -0.004859004008828,
  -0.000541640798032, -0.237963047085011, 0.436218238658637,
   0.011181482840782, 0.999937484898031, -0.000027155744957,
   0.237912530551179, -0.002660706488970, -0.008537588719453,
   0.004859003889183, -0.000027177143501, 0.999988194601879,
  -0.436101961325347, 0.012258830424865, 0.002119065556992,
  -0.000002423898405, 0.000000027105439, 0.000000011777422,
   0.999904322043106, -0.011181451601069, -0.004858519608686,
  -0.000000027105439, -0.000002423927017, 0.000000000065851,
   0.011181451608968, 0.999916125340107, -0.000027162614355,
  -0.000000011777422, 0.000000000065846, -0.000002424049954,
   0.004858519590501, -0.000027165866691, 0.999966838131419}
Definition at line 46 of file wcscon.c.
Referenced by fk524m().
int idg = 0
Definition at line 533 of file wcscon.c.
Referenced by fk42gal(), fk52gal(), gal2fk4(), and gal2fk5().
double jgal[3][3] [static]
Initial value:.nf
 {
  -0.054875539726,-0.873437108010,-0.483834985808,
   0.494109453312,-0.444829589425, 0.746982251810,
  -0.867666135858,-0.198076386122, 0.455983795705}
Definition at line 682 of file wcscon.c.
Referenced by fk52gal(), and gal2fk5().
Author
Generated automatically by Doxygen for imcat from the source code.