xfv.c
NAME
xfv.c -
SYNOPSIS
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/extensions/shape.h>
#include <Imlib.h>
#include 'utils/error.h'
#include 'utils/arrays.h'
#include 'utils/args.h'
#include 'imlib/fits.h'
Defines
#define usage '\n\n\NAME\n\ xfv --- FITS stream viewer\n\\n\SYNOPSIS\n\ xvf [-b blocksize]\n\\n\DESCRIPTION\n\ xvf is an X-based FITS Viewer for viewing 3D FITS\n\ images as a movie. It reads from stdin a series of\n\	8 bit FITS images. These can either be monochrome,\n\	in which case the image is 3D: f[NFRAMES][NY][NX], or\n\	or in RGB format: f[NFRAMES][3][NY][NX] and\n\	consisting of the R, G, B planes of a set of images.\n\\n\	It does no scaling.\n\\n\	You can use 'colorize' to convert monochrome to color.\n\\n\AUTHOR\n\ Nick Kaiser --- kaiser@hawaii.edu\n\n'
Functions
int getimageplane (void)
int main (int argc, char **argv)
Variables
unsigned char * srcdat
unsigned char * imdat
int w
int h
int rgbsourceimage
Define Documentation
#define usage '\n\n\NAME\n\ xfv --- FITS stream viewer\n\\n\SYNOPSIS\n\ xvf [-b blocksize]\n\\n\DESCRIPTION\n\ xvf is an X-based FITS Viewer for viewing 3D FITS\n\ images as a movie. It reads from stdin a series of\n\	8 bit FITS images. These can either be monochrome,\n\	in which case the image is 3D: f[NFRAMES][NY][NX], or\n\	or in RGB format: f[NFRAMES][3][NY][NX] and\n\	consisting of the R, G, B planes of a set of images.\n\\n\	It does no scaling.\n\\n\	You can use 'colorize' to convert monochrome to color.\n\\n\AUTHOR\n\ Nick Kaiser --- kaiser@hawaii.edu\n\n'
Definition at line 15 of file xfv.c.
Function Documentation
int getimageplane (void)
Definition at line 165 of file xfv.c.
References c, h, imdat, rgbsourceimage, srcdat, w, x, and y.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 41 of file xfv.c.
References argsinit(), error_exit, fitsheader::extpixtype, f, False, fits, flag, getargi(), getflag(), getimageplane(), h, imdat, m, fitsheader::n, fitsheader::ndim, nframes, readfitsheader(), rgbsourceimage, srcdat, UCHAR_PIXTYPE, usage, and w.
Variable Documentation
int h [static]
Definition at line 39 of file xfv.c.
unsigned char * imdat [static]
Definition at line 37 of file xfv.c.
Referenced by getimageplane(), and main().
int rgbsourceimage [static]
Definition at line 39 of file xfv.c.
Referenced by getimageplane(), and main().
unsigned char* srcdat [static]
Definition at line 37 of file xfv.c.
Referenced by getimageplane(), and main().
int w [static]
Definition at line 39 of file xfv.c.
Author
Generated automatically by Doxygen for imcat from the source code.