ximbuttons.c
NAME
ximbuttons.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include <X11/Xlib.h>
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <X11/cursorfont.h>
#include <X11/Xaw/Dialog.h>
#include 'ximbuttons.h'
#include 'ximfront.h'
#include 'ximback.h'
#include '../../imlib/fits.h'
Defines
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
#define ABS(x) ((x < 0) ? (-x) : (x))
#define CONTOURPLOT 0
#define PROFILEPLOT 1
#define CUSTOMPLOT 2
#define MAGIC SHORT_MAGIC
Functions
void Zoom (Widget w, XtPointer client_data, XtPointer call_data)
void UnZoom (Widget w, XtPointer client_data, XtPointer call_data)
void makepopup (Widget button, XtPointer client_data, XtPointer call_data)
void Cancel (Widget button, XtPointer client_data, XtPointer call_data)
void OkPrint (Widget button, XtPointer client_data, XtPointer call_data)
void OkMakemask (Widget button, XtPointer client_data, XtPointer call_data)
void Contour (Widget button, XtPointer client_data, XtPointer call_data)
void Profile (Widget button, XtPointer client_data, XtPointer call_data)
void Custom (Widget button, XtPointer client_data, XtPointer call_data)
void Makemask (void)
void Print (void)
void printclick (int i, int j)
void plotclick (int i, int j)
void Title (Widget w, XtPointer client_data, XtPointer call_data)
void picclick (Widget w, XtPointer client_data, XtPointer call_data)
void openmaskfile (char *maskfilename)
void closemaskfile (void)
void addmaskpoint (int i, int j)
void doplot (int icentre, int jcentre, int iside, int jside, int level, int plottype)
Variables
int makingmask = 0 printing = 0 gotfirstprintclick
int plotting = 0 gotfirstplotclick plottype
int firstmaskpoint
int hitok
int hitcancel
char filename [128]
char customcommand [256]
FILE * maskf
int N1 []
int N2 []
short ** f [MAX_FITS_DIM][MAX_LEVELS]
Define Documentation
#define ABS(x) ((x < 0) ? (-x) : (x))
Definition at line 34 of file ximbuttons.c.
#define CONTOURPLOT 0
Definition at line 36 of file ximbuttons.c.
Referenced by Contour(), and doplot().
#define CUSTOMPLOT 2
Definition at line 38 of file ximbuttons.c.
Referenced by Custom(), and doplot().
#define MAGIC SHORT_MAGIC
Definition at line 40 of file ximbuttons.c.
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
Definition at line 32 of file ximbuttons.c.
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
Definition at line 33 of file ximbuttons.c.
#define PROFILEPLOT 1
Definition at line 37 of file ximbuttons.c.
Referenced by doplot(), and Profile().
Function Documentation
void addmaskpoint (int i, int j)
Definition at line 405 of file ximbuttons.c.
References b, firstmaskpoint, i, j, l, maskf, r, and t.
Referenced by picclick().
void Cancel (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 165 of file ximbuttons.c.
References hitcancel, and hitok.
Referenced by makepopup().
void closemaskfile (void)
Definition at line 396 of file ximbuttons.c.
References maskf.
Referenced by Makemask().
void Contour (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 200 of file ximbuttons.c.
References CONTOURPLOT, and plotting.
Referenced by makepopup().
void Custom (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 223 of file ximbuttons.c.
References customcommand, CUSTOMPLOT, and plotting.
Referenced by makepopup().
void doplot (int icentre, int jcentre, int iside, int jside, int level, int plottype)
Definition at line 437 of file ximbuttons.c.
References ABS, appendcomment(), CONTOURPLOT, customcommand, CUSTOMPLOT, di, dj, error_exit, f, ff, fits, free(), i, fitsheader::intpixtype, j, MAGIC, MAX, MIN, N, N1, N2, new2Dfitsheader(), newtextcomment(), fitsheader::opstream, PROFILEPLOT, SHORT_PIXTYPE, writefitsheader(), writefitsline(), and writefitstail().
Referenced by plotclick().
void Makemask (void)
Definition at line 236 of file ximbuttons.c.
References closemaskfile(), filename, hitok, makingmask, and openmaskfile().
Referenced by makepopup(), and OkMakemask().
void makepopup (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 78 of file ximbuttons.c.
References Cancel(), Contour(), Custom(), error_exit, MAKEMASK, Makemask(), makingmask, n, OkMakemask(), OkPrint(), PLOT, PRINT, Print(), Profile(), TITLE, x, xfgetwidgetnumber(), and y.
Referenced by main(), and Title().
void OkMakemask (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 187 of file ximbuttons.c.
References filename, hitcancel, hitok, and Makemask().
Referenced by makepopup().
void OkPrint (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 175 of file ximbuttons.c.
References filename, hitcancel, hitok, and Print().
Referenced by makepopup().
void openmaskfile (char * maskfilename)
Definition at line 385 of file ximbuttons.c.
References error_exit, firstmaskpoint, and maskf.
Referenced by Makemask().
void picclick (Widget w, XtPointer client_data, XtPointer call_data)
Definition at line 321 of file ximbuttons.c.
References addmaskpoint(), color, GetPixelValue(), i, j, LASTUSERI, LASTUSERJ, MAGIC, makingmask, MAX_COLORS, n, NCOLORS, PICWIDGET, PIXVALLABEL, plotclick(), plotting, POSLABEL, printclick(), setlabelstring(), TOPLEVEL, xbgetvalue(), xbsetvalue(), and xfgetwidget().
Referenced by main().
void plotclick (int i, int j)
Definition at line 294 of file ximbuttons.c.
References doplot(), i, j, LEVEL, plotting, and xbgetvalue().
Referenced by picclick().
void Print (void)
Definition at line 251 of file ximbuttons.c.
References filename, hitok, LEVEL, printall(), and xbgetvalue().
Referenced by makepopup(), and OkPrint().
void printclick (int i, int j)
Definition at line 268 of file ximbuttons.c.
References filename, i, j, LEVEL, printselection(), and xbgetvalue().
Referenced by picclick().
void Profile (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 211 of file ximbuttons.c.
References plotting, and PROFILEPLOT.
Referenced by makepopup().
void Title (Widget w, XtPointer client_data, XtPointer call_data)
Definition at line 313 of file ximbuttons.c.
References makepopup(), and w.
Referenced by main().
void UnZoom (Widget w, XtPointer client_data, XtPointer call_data)
Definition at line 60 of file ximbuttons.c.
References destroyzoompixmap(), LEVEL, NLEVELS, showpixmap(), xbgetvalue(), and xbsetvalue().
Referenced by main().
void Zoom (Widget w, XtPointer client_data, XtPointer call_data)
Definition at line 42 of file ximbuttons.c.
References createzoompixmap(), fillzoompixmap(), LEVEL, showpixmap(), xbgetvalue(), and xbsetvalue().
Referenced by main().
Variable Documentation
char customcommand[256] [static]
Definition at line 26 of file ximbuttons.c.
Referenced by Custom(), and doplot().
short** f[MAX_FITS_DIM][MAX_LEVELS]
Definition at line 30 of file ximbuttons.c.
char filename[128] [static]
Definition at line 26 of file ximbuttons.c.
Referenced by Makemask(), OkMakemask(), OkPrint(), Print(), and printclick().
int firstmaskpoint [static]
Definition at line 24 of file ximbuttons.c.
Referenced by addmaskpoint(), and openmaskfile().
int hitcancel [static]
Definition at line 25 of file ximbuttons.c.
Referenced by Cancel(), OkMakemask(), and OkPrint().
int hitok [static]
Definition at line 25 of file ximbuttons.c.
Referenced by Cancel(), Makemask(), OkMakemask(), OkPrint(), and Print().
int makingmask = 0 printing = 0 gotfirstprintclick [static]
Definition at line 22 of file ximbuttons.c.
Referenced by Makemask(), makepopup(), and picclick().
FILE* maskf [static]
Definition at line 27 of file ximbuttons.c.
Referenced by addmaskpoint(), closemaskfile(), and openmaskfile().
int N1[]
Definition at line 29 of file ximbuttons.c.
int N2[]
Definition at line 29 of file ximbuttons.c.
int plotting = 0 gotfirstplotclick plottype [static]
Definition at line 23 of file ximbuttons.c.
Referenced by Contour(), Custom(), picclick(), plotclick(), and Profile().
Author
Generated automatically by Doxygen for imcat from the source code.