ximbuttons.h
NAME
ximbuttons.h -
SYNOPSIS
Functions
void Zoom (Widget w, XtPointer client_data, XtPointer call_data)
void UnZoom (Widget w, XtPointer client_data, XtPointer call_data)
void makepopup (Widget button, XtPointer client_data, XtPointer call_data)
void Cancel (Widget button, XtPointer client_data, XtPointer call_data)
void OkPrint (Widget button, XtPointer client_data, XtPointer call_data)
void OkMakemask (Widget button, XtPointer client_data, XtPointer call_data)
void Makemask (void)
void Print (void)
void printclick (int i, int j)
void Title (Widget w, XtPointer client_data, XtPointer call_data)
void picclick (Widget w, XtPointer client_data, XtPointer call_data)
void openmaskfile (char *maskfilename)
void closemaskfile (void)
void addmaskpoint (int i, int j)
void Contour (Widget button, XtPointer client_data, XtPointer call_data)
void Profile (Widget button, XtPointer client_data, XtPointer call_data)
void Custom (Widget button, XtPointer client_data, XtPointer call_data)
void plotclick (int i, int j)
void doplot (int icentre, int jcentre, int iside, int jside, int level, int plottype)
Function Documentation
void addmaskpoint (int i, int j)
Definition at line 405 of file ximbuttons.c.
References b, firstmaskpoint, i, j, l, maskf, r, and t.
Referenced by picclick().
void Cancel (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 165 of file ximbuttons.c.
References hitcancel, and hitok.
Referenced by makepopup().
void closemaskfile (void)
Definition at line 396 of file ximbuttons.c.
References maskf.
Referenced by Makemask().
void Contour (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 200 of file ximbuttons.c.
References CONTOURPLOT, and plotting.
Referenced by makepopup().
void Custom (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 223 of file ximbuttons.c.
References customcommand, CUSTOMPLOT, and plotting.
Referenced by makepopup().
void doplot (int icentre, int jcentre, int iside, int jside, int level, int plottype)
Definition at line 437 of file ximbuttons.c.
References ABS, appendcomment(), CONTOURPLOT, customcommand, CUSTOMPLOT, di, dj, error_exit, f, ff, fits, free(), i, fitsheader::intpixtype, j, MAGIC, MAX, MIN, N, N1, N2, new2Dfitsheader(), newtextcomment(), fitsheader::opstream, PROFILEPLOT, SHORT_PIXTYPE, writefitsheader(), writefitsline(), and writefitstail().
Referenced by plotclick().
void Makemask (void)
Definition at line 236 of file ximbuttons.c.
References closemaskfile(), filename, hitok, makingmask, and openmaskfile().
Referenced by makepopup(), and OkMakemask().
void makepopup (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 78 of file ximbuttons.c.
References Cancel(), Contour(), Custom(), error_exit, Makemask(), MAKEMASK, makingmask, n, OkMakemask(), OkPrint(), PLOT, Print(), PRINT, Profile(), TITLE, x, xfgetwidgetnumber(), and y.
Referenced by main(), and Title().
void OkMakemask (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 187 of file ximbuttons.c.
References filename, hitcancel, hitok, and Makemask().
Referenced by makepopup().
void OkPrint (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 175 of file ximbuttons.c.
References filename, hitcancel, hitok, and Print().
Referenced by makepopup().
void openmaskfile (char * maskfilename)
Definition at line 385 of file ximbuttons.c.
References error_exit, firstmaskpoint, and maskf.
Referenced by Makemask().
void picclick (Widget w, XtPointer client_data, XtPointer call_data)
Definition at line 321 of file ximbuttons.c.
References addmaskpoint(), color, GetPixelValue(), i, j, LASTUSERI, LASTUSERJ, MAGIC, makingmask, MAX_COLORS, n, NCOLORS, PICWIDGET, PIXVALLABEL, plotclick(), plotting, POSLABEL, printclick(), setlabelstring(), TOPLEVEL, xbgetvalue(), xbsetvalue(), and xfgetwidget().
Referenced by main().
void plotclick (int i, int j)
Definition at line 294 of file ximbuttons.c.
References doplot(), i, j, LEVEL, plotting, and xbgetvalue().
Referenced by picclick().
void Print (void)
Definition at line 251 of file ximbuttons.c.
References filename, hitok, LEVEL, printall(), and xbgetvalue().
Referenced by makepopup(), and OkPrint().
void printclick (int i, int j)
Definition at line 268 of file ximbuttons.c.
References filename, i, j, LEVEL, printselection(), and xbgetvalue().
Referenced by picclick().
void Profile (Widget button, XtPointer client_data, XtPointer call_data)
Definition at line 211 of file ximbuttons.c.
References plotting, and PROFILEPLOT.
Referenced by makepopup().
void Title (Widget w, XtPointer client_data, XtPointer call_data)
Definition at line 313 of file ximbuttons.c.
References makepopup(), and w.
Referenced by main().
void UnZoom (Widget w, XtPointer client_data, XtPointer call_data)
Definition at line 60 of file ximbuttons.c.
References destroyzoompixmap(), LEVEL, NLEVELS, showpixmap(), xbgetvalue(), and xbsetvalue().
Referenced by main().
void Zoom (Widget w, XtPointer client_data, XtPointer call_data)
Definition at line 42 of file ximbuttons.c.
References createzoompixmap(), fillzoompixmap(), LEVEL, showpixmap(), xbgetvalue(), and xbsetvalue().
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.