ximback.c
NAME
ximback.c -
SYNOPSIS
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include 'ximfront.h'
#include 'ximback.h'
#include 'ximcolor.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
#include '../../utils/stats_stuff.h'
Defines
#define MAX_SHADES 4096
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
#define MAGIC SHORT_MAGIC
Functions
int xbgetvalue (int thename)
void xbsetvalue (int thename, int thevalue)
void alloc_shades (void)
void readdataheader ()
void allocatedata (void)
void readdata (void)
void makescrunchedviews (void)
Pixmap create_pixmap (int level)
void fill_pixmap (void)
void makepreview (void)
void makeXImage (int N1, int N2)
short ** alloc_f (int N1, int N2)
void GetPixelValue (int pixx, int pixy, int height, int width, int *useri, int *userj, short *pixval)
Pixmap createzoompixmap (void)
void fillzoompixmap (void)
void destroyzoompixmap (void)
int myworkproc1 (XtPointer client_data)
void showpixmap (void)
int myworkproc2 (XtPointer client_data)
int myworkproc3 (XtPointer client_data)
Variables
int level
int nlevels
int ncolors
int lastuseri
int lastuserj
int blocksize = 1
int myscreen
int depth
GC mygc
Window mywindow
XImage * theimage
int imwidth
int imheight
int zoomi
int zoomj
Pixmap thezoompixmap
Pixmap pixmap [MAX_LEVELS]
char caption [2048]
Colormap cmap
Display * mydisplay
XColor shade [MAX_SHADES]
unsigned long pixel [MAX_SHADES]
unsigned int n_shades
short ** f [MAX_FITS_DIM][MAX_LEVELS]
int N1 [MAX_LEVELS]
int N2 [MAX_LEVELS]
fitsheader * gfits
Define Documentation
#define MAGIC SHORT_MAGIC
Definition at line 26 of file ximback.c.
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
Definition at line 23 of file ximback.c.
#define MAX_SHADES 4096
Definition at line 21 of file ximback.c.
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
Definition at line 24 of file ximback.c.
Function Documentation
short** alloc_f (int N1, int N2)
Definition at line 366 of file ximback.c.
References f, i, N1, and N2.
Referenced by allocatedata().
void alloc_shades (void)
Definition at line 99 of file ximback.c.
References cmap, color, depth, error_exit, exit(), False, i, info(), mydisplay, mygc, myscreen, mywindow, n_shades, pixel, set_shades(), setcolorscheme(), shade, TOPLEVEL, and xfgetwidget().
void allocatedata (void)
Definition at line 198 of file ximback.c.
References alloc_f(), color, f, level, N1, N2, ncolors, and nlevels.
Referenced by myworkproc1().
Pixmap create_pixmap (int level)
Definition at line 254 of file ximback.c.
References blocksize, depth, level, mydisplay, mywindow, N1, and N2.
Pixmap createzoompixmap (void)
Definition at line 438 of file ximback.c.
References depth, imheight, imwidth, mydisplay, mywindow, and thezoompixmap.
Referenced by Zoom().
void destroyzoompixmap (void)
Definition at line 482 of file ximback.c.
References mydisplay, and thezoompixmap.
Referenced by UnZoom().
void fill_pixmap (void)
Definition at line 267 of file ximback.c.
References blocksize, color_index(), f, fits, gfmax, gfmin, imheight, imwidth, ix, level, m, MAX, MIN, mydisplay, mygc, n, N1, N2, n_shades, pixmap, readfitsplane(), shade, theimage, x, xx, y, and yy.
void fillzoompixmap (void)
Definition at line 445 of file ximback.c.
References blocksize, color_index(), i, imheight, imwidth, j, LASTUSERI, LASTUSERJ, level, mydisplay, mygc, N1, shade, theimage, thezoompixmap, x, xbgetvalue(), xx, y, yy, zoomi, and zoomj.
Referenced by Zoom().
void GetPixelValue (int pixx, int pixy, int height, int width, int * useri, int * userj, short * pixval)
Definition at line 379 of file ximback.c.
References blocksize, color, f, i, imheight, imwidth, j, level, N1, N2, ncolors, zoomi, and zoomj.
Referenced by picclick().
void makepreview (void)
Definition at line 301 of file ximback.c.
References color, f, fill_pixmap(), i, j, level, N1, N2, and ncolors.
Referenced by myworkproc1().
void makescrunchedviews (void)
Definition at line 219 of file ximback.c.
References color, f, i, j, level, MAGIC, N1, N2, ncolors, and nlevels.
Referenced by myworkproc2().
void makeXImage (int N1, int N2)
Definition at line 328 of file ximback.c.
References blocksize, depth, exit(), imheight, imwidth, malloc(), mydisplay, myscreen, N1, N2, and theimage.
int myworkproc1 (XtPointer client_data)
Definition at line 488 of file ximback.c.
References A_MAX, alloc_shades(), allocatedata(), color, create_pixmap(), error_exit, exit(), fill_pixmap(), fits, FLABEL, frame, level, makepreview(), makeXImage(), MAX_COLORS, mydisplay, fitsheader::n, N1, N2, ncolors, newslidervalue(), nlevels, pixmap, readdata(), readdataheader(), set_shades(), setlabelstring(), setsliderval(), showpixmap(), SLIDER2, timestep, TLABEL, and xfgetwidget().
int myworkproc2 (XtPointer client_data)
Definition at line 566 of file ximback.c.
References makescrunchedviews().
Referenced by main().
int myworkproc3 (XtPointer client_data)
Definition at line 574 of file ximback.c.
References fill_pixmap(), level, nlevels, and showpixmap().
Referenced by main().
void readdata (void)
Definition at line 209 of file ximback.c.
References color, f, gfits, i, N2, ncolors, and readfitsline().
Referenced by myworkproc1().
void readdataheader (void)
Definition at line 140 of file ximback.c.
References fitsheader::basecomment, blocksize, caption, color, error_exit, fits, gfits, GOODSIZE, fitsheader::intpixtype, level, MAX_LEVELS, fitsheader::n, N1, N2, fitscomment::name, NAME_LENGTH, ncolors, fitsheader::ndim, fitscomment::next, nlevels, readfitsheader(), SHORT_PIXTYPE, fitscomment::value, VALUE_LENGTH, and xfgetvalue().
Referenced by myworkproc1().
void showpixmap (void)
Definition at line 544 of file ximback.c.
References blocksize, imheight, imwidth, level, n, N1, N2, PICWIDGET, pixmap, thezoompixmap, and xfgetwidget().
int xbgetvalue (int thename)
Definition at line 52 of file ximback.c.
References error_exit, LASTUSERI, lastuseri, LASTUSERJ, lastuserj, LEVEL, level, NCOLORS, ncolors, NLEVELS, and nlevels.
Referenced by fillzoompixmap(), picclick(), plotclick(), Print(), printclick(), setcolorscheme(), UnZoom(), and Zoom().
void xbsetvalue (int thename, int thevalue)
Definition at line 79 of file ximback.c.
References error_exit, LASTUSERI, lastuseri, LASTUSERJ, lastuserj, LEVEL, and level.
Referenced by picclick(), UnZoom(), and Zoom().
Variable Documentation
int blocksize = 1 [static]
Definition at line 30 of file ximback.c.
Referenced by create_pixmap(), fill_pixmap(), fillzoompixmap(), GetPixelValue(), makeXImage(), and readdataheader().
char caption[2048]
Definition at line 38 of file ximback.c.
Colormap cmap
Definition at line 41 of file ximback.c.
int depth [static]
Definition at line 31 of file ximback.c.
Referenced by alloc_shades(), create_pixmap(), createzoompixmap(), and makeXImage().
short** f[MAX_FITS_DIM][MAX_LEVELS]
Definition at line 46 of file ximback.c.
fitsheader* gfits
Definition at line 48 of file ximback.c.
Referenced by readdata(), and readdataheader().
int imheight [static]
Definition at line 35 of file ximback.c.
Referenced by createzoompixmap(), fill_pixmap(), fillzoompixmap(), GetPixelValue(), makeXImage(), and showpixmap().
int imwidth [static]
Definition at line 35 of file ximback.c.
Referenced by createzoompixmap(), fill_pixmap(), fillzoompixmap(), GetPixelValue(), makeXImage(), and showpixmap().
int lastuseri [static]
Definition at line 30 of file ximback.c.
Referenced by xbgetvalue(), and xbsetvalue().
int lastuserj [static]
Definition at line 30 of file ximback.c.
Referenced by xbgetvalue(), and xbsetvalue().
int level [static]
Definition at line 29 of file ximback.c.
Referenced by allocatedata(), create_pixmap(), fill_pixmap(), fillzoompixmap(), GetPixelValue(), makepreview(), makescrunchedviews(), myworkproc1(), myworkproc3(), readdataheader(), showpixmap(), xbgetvalue(), and xbsetvalue().
Display* mydisplay
Definition at line 42 of file ximback.c.
GC mygc [static]
Definition at line 32 of file ximback.c.
Referenced by alloc_shades(), fill_pixmap(), and fillzoompixmap().
int myscreen [static]
Definition at line 31 of file ximback.c.
Referenced by alloc_shades(), and makeXImage().
Window mywindow [static]
Definition at line 33 of file ximback.c.
Referenced by alloc_shades(), create_pixmap(), and createzoompixmap().
int N1[MAX_LEVELS]
Definition at line 47 of file ximback.c.
int N2[MAX_LEVELS]
Definition at line 47 of file ximback.c.
unsigned int n_shades
Definition at line 45 of file ximback.c.
int ncolors [static]
Definition at line 29 of file ximback.c.
Referenced by allocatedata(), GetPixelValue(), makepreview(), makescrunchedviews(), myworkproc1(), readdata(), readdataheader(), and xbgetvalue().
int nlevels [static]
Definition at line 29 of file ximback.c.
Referenced by allocatedata(), makescrunchedviews(), myworkproc1(), myworkproc3(), readdataheader(), and xbgetvalue().
unsigned long pixel[MAX_SHADES]
Definition at line 44 of file ximback.c.
Pixmap pixmap[MAX_LEVELS] [static]
Definition at line 37 of file ximback.c.
Referenced by fill_pixmap(), myworkproc1(), and showpixmap().
XColor shade[MAX_SHADES]
Definition at line 43 of file ximback.c.
XImage* theimage [static]
Definition at line 34 of file ximback.c.
Referenced by fill_pixmap(), fillzoompixmap(), and makeXImage().
Pixmap thezoompixmap [static]
Definition at line 37 of file ximback.c.
Referenced by createzoompixmap(), destroyzoompixmap(), fillzoompixmap(), and showpixmap().
int zoomi [static]
Definition at line 36 of file ximback.c.
Referenced by fillzoompixmap(), and GetPixelValue().
int zoomj [static]
Definition at line 36 of file ximback.c.
Referenced by fillzoompixmap(), and GetPixelValue().
Author
Generated automatically by Doxygen for imcat from the source code.