ximback.h
NAME
ximback.h -
SYNOPSIS
Defines
#define MAX_LEVELS 10
#define MAX_COLORS 3
#define LEVEL 0
#define NLEVELS 1
#define NCOLORS 2
#define LASTUSERI 3
#define LASTUSERJ 4
Functions
int xbgetvalue (int thename)
void xbsetvalue (int thename, int thevalue)
void alloc_shades (void)
Pixmap create_pixmap (int level)
void fill_pixmap (void)
void makepreview (void)
void readdataheader (void)
void allocatedata (void)
void readdata (void)
short ** alloc_f (int N1, int N2)
void makescrunchedviews (void)
void makeXImage (int N1, int N2)
void GetPixelValue (int pixi, int pixj, int height, int width, int *useri, int *userj, short *pixval)
Pixmap createzoompixmap (void)
void fillzoompixmap (void)
void destroyzoompixmap (void)
void showpixmap (void)
int myworkproc1 (XtPointer client_data)
int myworkproc2 (XtPointer client_data)
int myworkproc3 (XtPointer client_data)
Define Documentation
#define LASTUSERI 3
Definition at line 13 of file ximback.h.
Referenced by fillzoompixmap(), picclick(), xbgetvalue(), and xbsetvalue().
#define LASTUSERJ 4
Definition at line 14 of file ximback.h.
Referenced by fillzoompixmap(), picclick(), xbgetvalue(), and xbsetvalue().
#define LEVEL 0
Definition at line 10 of file ximback.h.
Referenced by plotclick(), Print(), printclick(), UnZoom(), xbgetvalue(), xbsetvalue(), and Zoom().
#define MAX_COLORS 3
Definition at line 6 of file ximback.h.
Referenced by color_index(), myworkproc1(), picclick(), and set_shades().
#define MAX_LEVELS 10
Definition at line 5 of file ximback.h.
Referenced by readdataheader().
#define NCOLORS 2
Definition at line 12 of file ximback.h.
Referenced by picclick(), setcolorscheme(), and xbgetvalue().
#define NLEVELS 1
Definition at line 11 of file ximback.h.
Referenced by UnZoom(), and xbgetvalue().
Function Documentation
short** alloc_f (int N1, int N2)
Definition at line 366 of file ximback.c.
References f, i, N1, and N2.
Referenced by allocatedata().
void alloc_shades (void)
Definition at line 104 of file back.c.
References cmap, color, depth, error_exit, exit(), False, i, info(), mydisplay, mygc, myscreen, mywindow, n_shades, pixel, set_shades(), setcolorscheme(), shade, TOPLEVEL, and xfgetwidget().
void allocatedata (void)
Definition at line 198 of file ximback.c.
References alloc_f(), color, f, level, N1, N2, ncolors, and nlevels.
Referenced by myworkproc1().
Pixmap create_pixmap (int level)
Definition at line 254 of file ximback.c.
References blocksize, depth, level, mydisplay, mywindow, N1, and N2.
Pixmap createzoompixmap (void)
Definition at line 438 of file ximback.c.
References depth, imheight, imwidth, mydisplay, mywindow, and thezoompixmap.
Referenced by Zoom().
void destroyzoompixmap (void)
Definition at line 482 of file ximback.c.
References mydisplay, and thezoompixmap.
Referenced by UnZoom().
void fill_pixmap (void)
Definition at line 174 of file back.c.
References blocksize, color_index(), f, fits, gfmax, gfmin, imheight, imwidth, ix, level, m, MAX, MIN, mydisplay, mygc, n, N1, N2, n_shades, pixmap, readfitsplane(), shade, theimage, x, xx, y, and yy.
void fillzoompixmap (void)
Definition at line 445 of file ximback.c.
References blocksize, color_index(), i, imheight, imwidth, j, LASTUSERI, LASTUSERJ, level, mydisplay, mygc, N1, shade, theimage, thezoompixmap, x, xbgetvalue(), xx, y, yy, zoomi, and zoomj.
Referenced by Zoom().
void GetPixelValue (int pixi, int pixj, int height, int width, int * useri, int * userj, short * pixval)
Definition at line 379 of file ximback.c.
References blocksize, color, f, i, imheight, imwidth, j, level, N1, N2, ncolors, zoomi, and zoomj.
Referenced by picclick().
void makepreview (void)
Definition at line 301 of file ximback.c.
References color, f, fill_pixmap(), i, j, level, N1, N2, and ncolors.
Referenced by myworkproc1().
void makescrunchedviews (void)
Definition at line 219 of file ximback.c.
References color, f, i, j, level, MAGIC, N1, N2, ncolors, and nlevels.
Referenced by myworkproc2().
void makeXImage (int N1, int N2)
Definition at line 328 of file ximback.c.
References blocksize, depth, exit(), imheight, imwidth, malloc(), mydisplay, myscreen, N1, N2, and theimage.
int myworkproc1 (XtPointer client_data)
Definition at line 246 of file back.c.
References A_MAX, alloc_shades(), allocatedata(), color, create_pixmap(), error_exit, exit(), fill_pixmap(), fits, FLABEL, frame, level, makepreview(), makeXImage(), MAX_COLORS, mydisplay, fitsheader::n, N1, N2, ncolors, newslidervalue(), nlevels, pixmap, readdata(), readdataheader(), set_shades(), setlabelstring(), setsliderval(), showpixmap(), SLIDER2, timestep, TLABEL, and xfgetwidget().
int myworkproc2 (XtPointer client_data)
Definition at line 566 of file ximback.c.
References makescrunchedviews().
Referenced by main().
int myworkproc3 (XtPointer client_data)
Definition at line 574 of file ximback.c.
References fill_pixmap(), level, nlevels, and showpixmap().
Referenced by main().
void readdata (void)
Definition at line 209 of file ximback.c.
References color, f, gfits, i, N2, ncolors, and readfitsline().
Referenced by myworkproc1().
void readdataheader (void)
Definition at line 140 of file ximback.c.
References fitsheader::basecomment, blocksize, caption, color, error_exit, fits, gfits, GOODSIZE, fitsheader::intpixtype, level, MAX_LEVELS, fitsheader::n, N1, N2, fitscomment::name, NAME_LENGTH, ncolors, fitsheader::ndim, fitscomment::next, nlevels, readfitsheader(), SHORT_PIXTYPE, fitscomment::value, VALUE_LENGTH, and xfgetvalue().
Referenced by myworkproc1().
void showpixmap (void)
Definition at line 268 of file back.c.
References blocksize, imheight, imwidth, level, n, N1, N2, PICWIDGET, pixmap, thezoompixmap, and xfgetwidget().
int xbgetvalue (int thename)
Definition at line 52 of file ximback.c.
References error_exit, lastuseri, LASTUSERI, lastuserj, LASTUSERJ, level, LEVEL, ncolors, NCOLORS, nlevels, and NLEVELS.
Referenced by fillzoompixmap(), picclick(), plotclick(), Print(), printclick(), setcolorscheme(), UnZoom(), and Zoom().
void xbsetvalue (int thename, int thevalue)
Definition at line 79 of file ximback.c.
References error_exit, lastuseri, LASTUSERI, lastuserj, LASTUSERJ, level, and LEVEL.
Referenced by picclick(), UnZoom(), and Zoom().
Author
Generated automatically by Doxygen for imcat from the source code.