ximcolor.c
NAME
ximcolor.c -
SYNOPSIS
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Intrinsic.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include 'ximback.h'
#include 'ximcolor.h'
#include 'ximfront.h'
#include '../../imlib/fits.h'
#include '../../utils/error.h'
Defines
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
#define GREENFACTOR 2
#define CAPTION psfilename
#define MAX_COLS 65535
Functions
void setcolorscheme (void)
void set_shades (void)
int color_index (int level, int i, int j)
float newslidervalue (int index)
void colorsetlevel (int level)
void printall (int level, char *psfilename)
void printselection (int level, int i1, int j1, int i2, int j2, char *psfilename)
double gray (int i, int j, int color)
void setsliderval (int index, double theval)
Variables
int gfmin [MAX_COLORS]
int gfmax [MAX_COLORS]
XColor shade []
unsigned long pixel []
unsigned int n_shades
short ** f [MAX_FITS_DIM][MAX_LEVELS]
Display * mydisplay
Colormap cmap
int N1 [MAX_LEVELS]
int N2 [MAX_LEVELS]
char caption []
int ncc [MAX_COLORS]
int mul [MAX_COLORS]
int ngray
int n_shades_used
float Fmin
float Fmax
float A
float Y = GREENFACTOR Q0 CFmax[3]
double sliderval [MAX_COLORS]
int ncolors
int clevel
int io
int jo
Define Documentation
#define CAPTION psfilename
Definition at line 36 of file ximcolor.c.
#define GREENFACTOR 2
Definition at line 31 of file ximcolor.c.
Referenced by gray(), and set_shades().
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
Definition at line 29 of file ximcolor.c.
#define MAX_COLS 65535
Definition at line 125 of file ximcolor.c.
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
Definition at line 30 of file ximcolor.c.
Function Documentation
int color_index (int level, int i, int j)
Definition at line 217 of file ximcolor.c.
References color, f, gfmax, gfmin, i, j, l, MAX, MAX_COLORS, MIN, mul, ncc, ncolors, and ngray.
Referenced by fill_pixmap(), and fillzoompixmap().
void colorsetlevel (int level)
Definition at line 307 of file ximcolor.c.
References clevel.
Referenced by printall(), and printselection().
double gray (int i, int j, int color)
Definition at line 358 of file ximcolor.c.
References A, clevel, color, error_exit, f, Fmax, Fmin, GREENFACTOR, i, io, j, jo, l, MAX, N1, N2, ncolors, and shade.
Referenced by print_im().
float newslidervalue (int index)
Definition at line 256 of file ximcolor.c.
References A, A_MAX, error_exit, Fmax, Fmin, gfmax, gfmin, ncolors, Q0_MAX, and sliderval.
Referenced by myworkproc1(), setcolorscheme(), and sliderChanged().
void printall (int level, char * psfilename)
Definition at line 312 of file ximcolor.c.
References CAPTION, colorsetlevel(), error_exit, gray(), io, jo, N1, N2, ncolors, print_im(), and set_print_opf().
Referenced by main(), and Print().
void printselection (int level, int i1, int j1, int i2, int j2, char * psfilename)
Definition at line 331 of file ximcolor.c.
References CAPTION, colorsetlevel(), error_exit, gray(), io, jo, mag, ncolors, print_im(), and set_print_opf().
Referenced by printclick().
void set_shades (void)
Definition at line 132 of file ximcolor.c.
References a, A_MAX, b, cmap, colormapindex, error_exit, g(), getrgbfromcmap(), GREENFACTOR, i, j, l, MAX, MAX_COLORS, MAX_COLS, MIN, mul, mydisplay, n_shades, n_shades_used, ncc, ncolors, pixel, Q0_MAX, r, shade, and sliderval.
void setcolorscheme (void)
Definition at line 59 of file ximcolor.c.
References A_MAX, error_exit, FMAX, FMIN, gfmax, gfmin, i, mul, n_shades, n_shades_used, ncc, ncolors, NCOLORS, newslidervalue(), ngray, setslider(), val, xbgetvalue(), and xfgetvalue().
void setsliderval (int index, double theval)
Definition at line 405 of file ximcolor.c.
References sliderval.
Referenced by myworkproc1(), and sliderChanged().
Variable Documentation
float A [static]
Definition at line 54 of file ximcolor.c.
char caption[]
Definition at line 50 of file ximcolor.c.
int clevel [static]
Definition at line 305 of file ximcolor.c.
Referenced by colorsetlevel(), and gray().
Colormap cmap
Definition at line 48 of file ximcolor.c.
short** f[MAX_FITS_DIM][MAX_LEVELS]
Definition at line 46 of file ximcolor.c.
float Fmax [static]
Definition at line 54 of file ximcolor.c.
Referenced by gray(), and newslidervalue().
float Fmin [static]
Definition at line 54 of file ximcolor.c.
Referenced by gray(), and newslidervalue().
int gfmax[MAX_COLORS] [static]
Definition at line 40 of file ximcolor.c.
Referenced by color_index(), newslidervalue(), and setcolorscheme().
int gfmin[MAX_COLORS] [static]
Definition at line 40 of file ximcolor.c.
Referenced by color_index(), newslidervalue(), and setcolorscheme().
int io [static]
Definition at line 305 of file ximcolor.c.
Referenced by gray(), printall(), and printselection().
int jo [static]
Definition at line 305 of file ximcolor.c.
Referenced by gray(), printall(), and printselection().
int mul[MAX_COLORS] [static]
Definition at line 53 of file ximcolor.c.
Referenced by color_index(), set_shades(), and setcolorscheme().
Display* mydisplay
Definition at line 47 of file ximcolor.c.
int N1[MAX_LEVELS]
Definition at line 49 of file ximcolor.c.
int N2[MAX_LEVELS]
Definition at line 49 of file ximcolor.c.
unsigned int n_shades
Definition at line 45 of file ximcolor.c.
int n_shades_used [static]
Definition at line 53 of file ximcolor.c.
Referenced by set_shades(), and setcolorscheme().
int ncc[MAX_COLORS] [static]
Definition at line 53 of file ximcolor.c.
Referenced by color_index(), set_shades(), and setcolorscheme().
int ncolors [static]
Definition at line 56 of file ximcolor.c.
Referenced by color_index(), gray(), newslidervalue(), printall(), printselection(), set_shades(), and setcolorscheme().
int ngray [static]
Definition at line 53 of file ximcolor.c.
Referenced by color_index(), and setcolorscheme().
unsigned long pixel[]
Definition at line 44 of file ximcolor.c.
XColor shade[]
Definition at line 43 of file ximcolor.c.
double sliderval[MAX_COLORS] [static]
Definition at line 55 of file ximcolor.c.
Referenced by newslidervalue(), set_shades(), and setsliderval().
float Y = GREENFACTOR Q0 CFmax[3] [static]
Definition at line 54 of file ximcolor.c.
Author
Generated automatically by Doxygen for imcat from the source code.