ximcolor.h
NAME
ximcolor.h -
SYNOPSIS
Defines
#define Q0_MAX 1
#define A_MAX 4
Functions
void setcolorscheme (void)
void set_shades (void)
int color_index (int level, int i, int j)
float newslidervalue (int index)
void printall (int level, char *psfilename)
void printselection (int level, int i1, int j1, int i2, int j2, char *psfilename)
void colorsetlevel (int level)
double gray (int i, int j, int color)
void setsliderval (int index, double theval)
Define Documentation
#define A_MAX 4
Definition at line 6 of file ximcolor.h.
#define Q0_MAX 1
Definition at line 5 of file ximcolor.h.
Function Documentation
int color_index (int level, int i, int j)
Definition at line 217 of file ximcolor.c.
References color, f, gfmax, gfmin, i, j, l, MAX, MAX_COLORS, MIN, mul, ncc, ncolors, and ngray.
Referenced by fill_pixmap(), and fillzoompixmap().
void colorsetlevel (int level)
Definition at line 307 of file ximcolor.c.
References clevel.
Referenced by printall(), and printselection().
double gray (int i, int j, int color)
Definition at line 358 of file ximcolor.c.
References A, clevel, color, error_exit, f, Fmax, Fmin, GREENFACTOR, i, io, j, jo, l, MAX, N1, N2, ncolors, and shade.
Referenced by print_im().
float newslidervalue (int index)
Definition at line 256 of file ximcolor.c.
References A, A_MAX, error_exit, Fmax, Fmin, gfmax, gfmin, ncolors, Q0_MAX, and sliderval.
Referenced by myworkproc1(), setcolorscheme(), and sliderChanged().
void printall (int level, char * psfilename)
Definition at line 312 of file ximcolor.c.
References CAPTION, colorsetlevel(), error_exit, gray(), io, jo, N1, N2, ncolors, print_im(), and set_print_opf().
Referenced by main(), and Print().
void printselection (int level, int i1, int j1, int i2, int j2, char * psfilename)
Definition at line 331 of file ximcolor.c.
References CAPTION, colorsetlevel(), error_exit, gray(), io, jo, mag, ncolors, print_im(), and set_print_opf().
Referenced by printclick().
void set_shades (void)
Definition at line 76 of file back.c.
References a, A_MAX, b, cmap, colormapindex, error_exit, g(), getrgbfromcmap(), GREENFACTOR, i, j, l, MAX, MAX_COLORS, MAX_COLS, MIN, mul, mydisplay, n_shades, n_shades_used, ncc, ncolors, pixel, Q0_MAX, r, shade, and sliderval.
void setcolorscheme (void)
Definition at line 59 of file ximcolor.c.
References A_MAX, error_exit, FMAX, FMIN, gfmax, gfmin, i, mul, n_shades, n_shades_used, ncc, NCOLORS, ncolors, newslidervalue(), ngray, setslider(), val, xbgetvalue(), and xfgetvalue().
void setsliderval (int index, double theval)
Definition at line 405 of file ximcolor.c.
References sliderval.
Referenced by myworkproc1(), and sliderChanged().
Author
Generated automatically by Doxygen for imcat from the source code.