ximfront.c
NAME
ximfront.c -
SYNOPSIS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include <X11/Xlib.h>
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Shell.h>
#include <X11/cursorfont.h>
#include <X11/Xaw/Label.h>
#include <X11/Xaw/Box.h>
#include <X11/Xaw/Form.h>
#include <X11/Xaw/Command.h>
#include <X11/Xaw/Viewport.h>
#include <X11/Xaw/Scrollbar.h>
#include <X11/Xaw/Dialog.h>
#include <X11/Xaw/Cardinals.h>
#include 'ximfront.h'
#include 'ximback.h'
#include 'ximbuttons.h'
#include 'ximcolor.h'
#include '../../utils/error.h'
Data Structures
struct _AppResources
Defines
#define MAX_SLIDERS 5
Typedefs
typedef _AppResources AppResources
Functions
main (int argc, char **argv)
void Syntax (XtAppContext app_con, char *call)
void makeslider (int index, Widget fromVert, Widget fromHoriz)
void xfgetargstring (char **argstrptr)
int xfgetvalue (int name)
void makewidgetdatabase (void)
int xfgetwidgetnumber (Widget thewidget)
Widget xfgetwidget (int thenumber)
void sliderChanged (Widget w, XtPointer closure, XtPointer call_data)
void setslider (int index, float thumbpos, char *label, char *value)
void setlabelstring (Widget w, char *thestring)
void setlabelnumber (Widget w, float thenumber)
Variables
XtResource resources []
String fallback_resources []
XrmOptionDescRec options []
char * helpmsg []
Widget toplevel
Widget picwidget
Widget viewport
Widget topform
Widget title
Widget controls
Widget stats
Widget buttons
Widget sliders
Widget slider [MAX_SLIDERS]
Widget scrollbar [MAX_SLIDERS]
Widget sliderlabel [MAX_SLIDERS]
Widget slidervalue [MAX_SLIDERS]
Widget zoom
Widget unzoom
Widget makemask
Widget print
Widget plot
Widget poslabel
Widget pixvallabel
Widget pixrangelabel
Pixmap pixmap [MAX_LEVELS]
Widget widgetlist [100]
int numberlist [100]
AppResources app_resources
char argstring [256]
Define Documentation
#define MAX_SLIDERS 5
Definition at line 80 of file ximfront.c.
Referenced by sliderChanged().
Typedef Documentation
typedef struct _AppResources AppResources
Function Documentation
main (int argc, char ** argv)
Definition at line 99 of file ximfront.c.
References app_resources, argsToString(), argstring, buttons, color, controls, fallback_resources, _AppResources::goodwindowsize, makemask, makepopup(), makeslider(), makewidgetdatabase(), myworkproc1(), myworkproc2(), myworkproc3(), options, picclick(), picwidget, pixvallabel, plot, poslabel, print, resources, slider, sliders, stats, Syntax(), Title(), title, topform, toplevel, True, UnZoom(), unzoom, viewport, Zoom(), and zoom.
void makeslider (int index, Widget fromVert, Widget fromHoriz)
Definition at line 260 of file ximfront.c.
References scrollbar, slider, sliderChanged(), sliderlabel, sliders, and slidervalue.
Referenced by main().
void makewidgetdatabase (void)
Definition at line 317 of file ximfront.c.
References flabel, FLABEL, MAKEMASK, makemask, numberlist, PICWIDGET, picwidget, PIXVALLABEL, pixvallabel, PLOT, plot, POSLABEL, poslabel, PRINT, print, slider, SLIDER2, TITLE, title, tlabel, TLABEL, TOPLEVEL, toplevel, and widgetlist.
void setlabelnumber (Widget w, float thenumber)
Definition at line 421 of file ximfront.c.
References setlabelstring(), and w.
Referenced by sliderChanged().
void setlabelstring (Widget w, char * thestring)
Definition at line 408 of file ximfront.c.
References n, and w.
Referenced by myworkproc1(), picclick(), setlabelnumber(), and setslider().
void setslider (int index, float thumbpos, char * label, char * value)
Definition at line 393 of file ximfront.c.
References label, n, scrollbar, setlabelstring(), sliderlabel, and slidervalue.
Referenced by setcolorscheme().
void sliderChanged (Widget w, XtPointer closure, XtPointer call_data)
Definition at line 375 of file ximfront.c.
References MAX_SLIDERS, newslidervalue(), scrollbar, set_shades(), setlabelnumber(), setsliderval(), slidervalue, and w.
Referenced by makeslider().
void Syntax (XtAppContext app_con, char * call)
Definition at line 242 of file ximfront.c.
References exit(), and helpmsg.
Referenced by main().
void xfgetargstring (char ** argstrptr)
Definition at line 288 of file ximfront.c.
References argstring.
int xfgetvalue (int name)
Definition at line 296 of file ximfront.c.
References app_resources, error_exit, _AppResources::fmax, FMAX, _AppResources::fmin, FMIN, GOODSIZE, and _AppResources::goodwindowsize.
Referenced by readdataheader(), and setcolorscheme().
Widget xfgetwidget (int thenumber)
Definition at line 359 of file ximfront.c.
References error_exit, numberlist, and widgetlist.
Referenced by alloc_shades(), myworkproc1(), picclick(), and showpixmap().
int xfgetwidgetnumber (Widget thewidget)
Definition at line 343 of file ximfront.c.
References error_exit, numberlist, and widgetlist.
Referenced by makepopup().
Variable Documentation
AppResources app_resources [static]
Definition at line 95 of file ximfront.c.
Referenced by main(), and xfgetvalue().
char argstring[256] [static]
Definition at line 96 of file ximfront.c.
Referenced by main(), and xfgetargstring().
Widget buttons [static]
Definition at line 84 of file ximfront.c.
Referenced by main().
Widget controls [static]
Definition at line 84 of file ximfront.c.
Referenced by main().
String fallback_resources[]
Initial value:.nf
 {
  '*Viewport*allowVert: True',
  '*Viewport*allowHoriz: True',
        '*Scrollbar*length: 100',
  '*picwidget.cursor: crosshair',
  '*picwidget.foreground: yellow',
  '*Form.background: DarkSlateBlue',
  '*Command.background: CornflowerBlue',
  '*Label.background: LightBlue',
  '*Scrollbar.background: LightBlue',
  '*picwidget.background: grey',
    NULL,
}
Definition at line 51 of file ximfront.c.
char* helpmsg[] [static]
Initial value:.nf
 {
    '-min fmin minimum f-value (0)',
    '-max fmax maximum f-value (256)',
    '-goodsize good window size (512)',
NULL }
Definition at line 72 of file ximfront.c.
Referenced by Syntax().
Widget makemask [static]
Definition at line 87 of file ximfront.c.
Referenced by main(), and makewidgetdatabase().
int numberlist[100] [static]
Definition at line 92 of file ximfront.c.
Referenced by makewidgetdatabase(), xfgetwidget(), and xfgetwidgetnumber().
XrmOptionDescRec options[] [static]
Initial value:.nf
 {
    {'-goodsize', 'goodwindowsize', XrmoptionSepArg, NULL},
    {'-min', 'fmin', XrmoptionSepArg, NULL},
    {'-max', 'fmax', XrmoptionSepArg, NULL},
}
Definition at line 65 of file ximfront.c.
Referenced by main().
Widget picwidget [static]
Definition at line 83 of file ximfront.c.
Referenced by main(), and makewidgetdatabase().
Pixmap pixmap[MAX_LEVELS] [static]
Definition at line 89 of file ximfront.c.
Widget pixrangelabel [static]
Definition at line 88 of file ximfront.c.
Widget pixvallabel [static]
Definition at line 88 of file ximfront.c.
Referenced by main(), and makewidgetdatabase().
Widget plot [static]
Definition at line 87 of file ximfront.c.
Referenced by main(), and makewidgetdatabase().
Widget poslabel [static]
Definition at line 88 of file ximfront.c.
Referenced by main(), and makewidgetdatabase().
Widget print [static]
Definition at line 87 of file ximfront.c.
Referenced by main(), and makewidgetdatabase().
XtResource resources[] [static]
Initial value:.nf
 {
    {'fmin', 'Fmin', XtRInt, sizeof(int),
     XtOffsetOf(AppResources, fmin), XtRImmediate, (XtPointer) 0},
    {'fmax', 'Fmax', XtRInt, sizeof(int),
     XtOffsetOf(AppResources, fmax), XtRImmediate, (XtPointer) 256},
    {'goodwindowsize', 'Goodwindowsize', XtRInt, sizeof(int),
     XtOffsetOf(AppResources, goodwindowsize), XtRImmediate, (XtPointer) 512},
}
Definition at line 42 of file ximfront.c.
Referenced by main().
Widget scrollbar[MAX_SLIDERS] [static]
Definition at line 85 of file ximfront.c.
Referenced by makeslider(), setslider(), and sliderChanged().
Widget slider[MAX_SLIDERS] [static]
Definition at line 85 of file ximfront.c.
Referenced by main(), makeslider(), and makewidgetdatabase().
Widget sliderlabel[MAX_SLIDERS] [static]
Definition at line 86 of file ximfront.c.
Referenced by makeslider(), and setslider().
Widget sliders [static]
Definition at line 84 of file ximfront.c.
Referenced by main(), and makeslider().
Widget slidervalue[MAX_SLIDERS] [static]
Definition at line 86 of file ximfront.c.
Referenced by makeslider(), setslider(), and sliderChanged().
Widget stats [static]
Definition at line 84 of file ximfront.c.
Referenced by main().
Widget title [static]
Definition at line 84 of file ximfront.c.
Widget topform [static]
Definition at line 84 of file ximfront.c.
Referenced by main().
Widget toplevel [static]
Definition at line 82 of file ximfront.c.
Referenced by main(), and makewidgetdatabase().
Widget unzoom [static]
Definition at line 87 of file ximfront.c.
Referenced by main().
Widget viewport [static]
Definition at line 83 of file ximfront.c.
Referenced by main().
Widget widgetlist[100] [static]
Definition at line 91 of file ximfront.c.
Referenced by makewidgetdatabase(), xfgetwidget(), and xfgetwidgetnumber().
Widget zoom [static]
Definition at line 87 of file ximfront.c.
Referenced by main().
Author
Generated automatically by Doxygen for imcat from the source code.