ximfront.h
NAME
ximfront.h -
SYNOPSIS
Defines
#define TITLE 1
#define PRINT 2
#define MAKEMASK 3
#define TOPLEVEL 4
#define PICWIDGET 5
#define POSLABEL 6
#define PIXVALLABEL 7
#define SLIDER2 8
#define PLOT 9
#define FMAX 100
#define FMIN 101
#define GOODSIZE 102
Functions
void Syntax (XtAppContext app_con, char *call)
void makeslider (int index, Widget fromVert, Widget fromHoriz)
void xfgetargstring (char **argstrptr)
void makewidgetdatabase (void)
int xfgetvalue (int thename)
int xfgetwidgetnumber (Widget button)
Widget xfgetwidget (int thenumber)
void sliderChanged (Widget w, XtPointer closure, XtPointer call_data)
void setslider (int index, float thumbpos, char *label, char *value)
void setlabelstring (Widget w, char *thestring)
void setlabelnumber (Widget w, float thenumber)
Define Documentation
#define FMAX 100
Definition at line 17 of file ximfront.h.
#define FMIN 101
Definition at line 18 of file ximfront.h.
#define GOODSIZE 102
Definition at line 19 of file ximfront.h.
#define MAKEMASK 3
Definition at line 8 of file ximfront.h.
Referenced by makepopup(), and makewidgetdatabase().
#define PICWIDGET 5
Definition at line 10 of file ximfront.h.
#define PIXVALLABEL 7
Definition at line 12 of file ximfront.h.
Referenced by makewidgetdatabase(), and picclick().
#define PLOT 9
Definition at line 14 of file ximfront.h.
Referenced by makepopup(), and makewidgetdatabase().
#define POSLABEL 6
Definition at line 11 of file ximfront.h.
Referenced by makewidgetdatabase(), and picclick().
#define PRINT 2
Definition at line 7 of file ximfront.h.
Referenced by makepopup(), and makewidgetdatabase().
#define SLIDER2 8
Definition at line 13 of file ximfront.h.
Referenced by makewidgetdatabase(), and myworkproc1().
#define TITLE 1
Definition at line 6 of file ximfront.h.
Referenced by makepopup(), and makewidgetdatabase().
#define TOPLEVEL 4
Definition at line 9 of file ximfront.h.
Function Documentation
void makeslider (int index, Widget fromVert, Widget fromHoriz)
Definition at line 260 of file ximfront.c.
References scrollbar, slider, sliderChanged(), sliderlabel, sliders, and slidervalue.
Referenced by main().
void makewidgetdatabase (void)
Definition at line 236 of file front.c.
References FLABEL, flabel, makemask, MAKEMASK, numberlist, PICWIDGET, picwidget, pixvallabel, PIXVALLABEL, plot, PLOT, poslabel, POSLABEL, print, PRINT, slider, SLIDER2, title, TITLE, TLABEL, tlabel, TOPLEVEL, toplevel, and widgetlist.
void setlabelnumber (Widget w, float thenumber)
Definition at line 297 of file front.c.
References setlabelstring(), and w.
Referenced by sliderChanged().
void setlabelstring (Widget w, char * thestring)
Definition at line 284 of file front.c.
References n, and w.
Referenced by myworkproc1(), picclick(), setlabelnumber(), and setslider().
void setslider (int index, float thumbpos, char * label, char * value)
Definition at line 393 of file ximfront.c.
References label, n, scrollbar, setlabelstring(), sliderlabel, and slidervalue.
Referenced by setcolorscheme().
void sliderChanged (Widget w, XtPointer closure, XtPointer call_data)
Definition at line 375 of file ximfront.c.
References MAX_SLIDERS, newslidervalue(), scrollbar, set_shades(), setlabelnumber(), setsliderval(), slidervalue, and w.
Referenced by makeslider().
void Syntax (XtAppContext app_con, char * call)
Definition at line 193 of file front.c.
References exit(), and helpmsg.
Referenced by main().
void xfgetargstring (char ** argstrptr)
Definition at line 210 of file front.c.
References argstring.
int xfgetvalue (int thename)
Definition at line 218 of file front.c.
References app_resources, error_exit, _AppResources::fmax, FMAX, _AppResources::fmin, FMIN, GOODSIZE, and _AppResources::goodwindowsize.
Referenced by readdataheader(), and setcolorscheme().
Widget xfgetwidget (int thenumber)
Definition at line 268 of file front.c.
References error_exit, numberlist, and widgetlist.
Referenced by alloc_shades(), myworkproc1(), picclick(), and showpixmap().
int xfgetwidgetnumber (Widget button)
Definition at line 252 of file front.c.
References error_exit, numberlist, and widgetlist.
Referenced by makepopup().
Author
Generated automatically by Doxygen for imcat from the source code.