.\" Process this file with
.\" groff -man -Tascii makemanpage.1
.\"
.TH makemanpage 1 Imcat

.SH NAME
./makemanpage \- perl script to generate a man page 

.SH SYNOPSIS
.B ./makemanpage commandname | libname headers


.SH DESCRIPTION
With a single argument we invoke the command \'commandname\' with \'-u\'
option to genenerate the man-page.

With multiple arguments we output a man page for a library \'libname\'

