/*
 * gen2Dpolymodelimage.c
 */


#define	usage "\n\n\n\
NAME\n\
	gen2Dpolymodelimage --- generate 2D spatial polynomial model as fits image\n\
\n\
SYNOPSIS\n\
	gen2Dpolymodelimage parfile N1 N2\n\
\n\
DESCRIPTION\n\
	'gen2Dpolymodelimage' generates a N1 x N2 float format fits image\n\
	whose value is given by\n\
		f = sum_l sum_m a_lm f_lm(x)\n\
	where the mode coefficients are given in a parameters file (as\n\
	generated by fit2Dpolymodel perhaps) 'parfile'.\n\
\n\
	Currently only works for fit to a scalar function.\n\
\n\
AUTHOR\n\
	Nick Kaiser --- kaiser@ifa.hawaii.edu\n\
\n\n\n"		


#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>

#include "../catlib/cat.h"					/* READ THIS! */
#include "../utils/error.h"
#include "../utils/modefunc.h"
#include "../utils/arrays.h"
#include "../imlib/fits.h"

static	double		**var;
static	int		varind;
void	getaddresses(void *addr, int ndim, int *dim);

main(int argc, char *argv[])	
{
	char		*parfilename, *parfilexname, varname[128];
	double		x[2];
	char		*vardef[MODEFUNC_MAX_VARS];
	int		*l, *m, mode, nmodes, nvar, asize, ndim, idim, dim[5], pos, i;
	double		**a;
	double		fm;
	int		N1, N2, ix, iy;
	float		**F;
	fitsheader	*fits;


	/* parse args */
	if (argc != 4)
		error_exit(usage);
	parfilename = argv[1];
	if ((1 != sscanf(argv[2], "%d", &N1)) || (1 != sscanf(argv[3], "%d", &N2))) {
		error_exit(usage);
	}
	/* read the parameter file */
	get2Dpolymodel(parfilename, &l, &m, &asize, &a, &nmodes, &nvar, vardef, &parfilexname);

	/* parse the vardef string */
	sscanf(vardef[2], "%d%n", &ndim, &pos);
	vardef[2] += pos;
	for (idim = 0; idim < ndim; idim++) {
		sscanf(vardef[2], "%d%n", &(dim[idim]), &pos);
		vardef[2]+= pos;
	}
	sscanf(vardef[2], "%s", varname);

	if (ndim != 1 || dim[0] != 1) {
		error_exit("gen2Dpolymodelimage: sorry, I can only handle scalar models\n");
	}
	
	allocFloatArray(&F, N1, N2);
	fits = new2Dfitsheader(N1, N2, FLOAT_PIXTYPE);

	for (iy = 0; iy < N2; iy++) {
		x[1] = (double) iy;
		for (ix = 0; ix < N1; ix++) {
			x[0] = (double) ix;
			F[iy][ix] = 0.0;
			for (mode = 0; mode < nmodes; mode++) {
				fm = f(l[mode], m[mode], x);
				F[iy][ix] += a[0][mode] * fm;
			}
		}
	}
	write2Dfloatimage(F, fits);
	exit(0);
}



